### ISSUE TITLE
args after -- fail

### ISSUE THREAD

**Issue by pocc** [pre-commit/pre-commit#1000]
## Problem

Occasionally it is necessary to use `--` to signify [options that take an argument](https://unix.stackexchange.com/questions/11376/what-does-double-dash-mean-also-known-as-bare-double-dash). When `--` is used, any file arguments are ignored.

## Description

I am using `oclint`, which identifies potential problems in c code. `--` is required to specify compiler options. This is my current configuration:

```yaml
[-- skipped for brevity --]

-   repo: local
    hooks:
    -   id: oclint
        name: oclint
        description: Find warnings/errors in C/CPP code
        entry: oclint
        types: [c]
        pass_filenames: true
        args: [
            -enable-clang-static-analyzer,
            -enable-global-analysis,
            --,
            -report-type=json,
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON,
        ]
        language: system
```

When running on a valid c file, I get this output:

```bash
oclint...................................................................Failed
hookid: oclint

oclint: Not enough positional command line arguments specified!
Must specify at least 1 positional argument: See: /usr/local/bin/oclint -help
```

## Solution

Looking at the code, it looks like you are appending file arguments to the end instead of infixing them before `--`. A pull request that fixes this will be coming in a few.

**Comment by asottile** [comment]
Do you have an example that's broken? I'm not sure I understand your problem statement -- typically `--` just means "don't parse these arguments as normal" and doesn't have any special significance for file or not -- I don't think it would be correct for pre-commit to attach any special behaviour to that

**Comment by pocc** [comment]
I've updated the question with additional context.

**Comment by asottile** [comment]
makes sense, I still think the current behaviour is as correct as it could be without potentially breaking existing things.  `oclint`'s usage of `--` isn't universally applicable

One thing that you can do is use a script to redirect the arguments where you want them, for instance (untested):

```yaml
entry: bash -c 'oclint -enable-clang-static-analyzer ... "$@" -- -report-type-json ...'
```

(If you don't want to inline that all in the yaml, it could easily be moved out to another script)

Even something like this might work (again untested, might be off-by-one somewhere):

```python
#!/usr/bin/env python3
import os
import sys


def main():
    eq_eq = sys.argv.index('==')
    dash_dash = sys.argv.index('--')
    cmd = (
        ['oclint'] +
        sys.argv[:dash_dash] +
        sys.argv[eq_eq + 1:] + 
        sys.argv[dash_dash:eq_eq]
    )
    os.execvp(cmd[0], cmd)

if __name__ == '__main__':
    exit(main())
```

```yaml
-   repo: local
    hooks:
    -   id: oclint
        name: oclint
        description: Find warnings/errors in C/CPP code
        entry: ./oclint-pre-commit-wrapper
        types: [c]
        pass_filenames: true
        args: [
            -enable-clang-static-analyzer,
            -enable-global-analysis,
            --,
            -report-type=json,
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON,
        ]
        language: script
```
