### ISSUE TITLE
Support for .NET Core linters?

### ISSUE THREAD

**Issue by cgranade** [pre-commit/pre-commit#1002]
Would it be possible to add .NET linters such as https://github.com/dotnet/format as hooks? I took a look at the advice in #926, but it wasn't clear to me the best way to add a hook for .NET Core executables such as `dotnet-format`. Thanks for the help!

**Comment by asottile** [comment]
yep!

until there's core language support for `.net` things in `pre-commit` you can manage the installation separately and use a [`language: system`](https://pre-commit.com/#system) hook -- something like:

```yaml
-   id: dotnet-format
    name: dotnet-format
    language: system
    entry: dotnet-format
    types: ['c#']
```

it would be pretty cool to see core support for something like `language: nuget` or `language: dotnet` or something though, especially given the cross platform support :)
