### ISSUE TITLE
ipynb output cleaning filter

### ISSUE THREAD

**Issue by basnijholt** [pre-commit/pre-commit#1020]
I use a pre-commit hook to cleanup Jupyter notebook (`ipynb`) files of its output and meta data, with this script https://github.com/basnijholt/ipynb_git_filters/blob/master/ipynb_filter.py

How would I put this in my config?

I tried:
```
-   repo: local
    hooks:
    -   id: remove_ipynb_output
        name: clean ipynb
        entry: ./ipynb_filter.py
        language: python
        files: '(?s:.*\\.ipynb)\\Z'
```

but none of the `ipynb` files are touched.

I would also like the output to only be removed in git, but not the actual file. Is that possible?
