### ISSUE TITLE
check-yaml to treat NULL as error

### ISSUE THREAD

**Issue by AnthonyWC** [pre-commit/pre-commit#1025]
In the existing https://github.com/pre-commit/pre-commit-hooks for check-yaml, is there an option or way to treat NULL as error?

e.g. 
```
 ---
 foo:
   - bar
   -
```

will pass with:
```
 repos:

 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v2.1.0
   hooks:
     - id: check-yaml
       verbose: true
```
