### ISSUE TITLE
Branch name validation?

### ISSUE THREAD

**Issue by Jawdeath** [pre-commit/pre-commit#1034]
Hello!

Is there an inbox variant  in pre-commit of validating git branch name? 
Or I need to edit hook file manually and add regular expression?

thank's for the answer

**Comment by marcjay** [comment]
Hey, take a look at the `no-commit-to-branch` hook over in https://github.com/pre-commit/pre-commit-hooks - that should do what you want

This is an example hook config that would block commits to the master branch and any branch that matches the regex '`release/.*`'

```
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.1
  hooks:
    - id: no-commit-to-branch
      args: ['--branch', 'master', '--pattern', 'release/.*']
```

**Comment by Jawdeath** [comment]
That's it! Thank you!

**Comment by Jawdeath** [comment]
Sorry, is there a way to set restriction to commit not only to master, but to current branch? 
To force people to name branches right way. 
This is for avoiding branches with not valid names on the server.

**Comment by marcjay** [comment]
Could you expand on what 'the right way looks like'? i.e. what a valid name looks like? If the inverse can be expressed as a regex, it should be possible with the existing hook

**Comment by Jawdeath** [comment]
The case is that we need all the branches to match some pattern. For example, in the first case developer creates branch named 'bla-bla' and made some changes. Then he wants to push this to the origin branch 'bla-bla'. And we want to have only branches like '123-projectname-short-description'. 
So, to have an opportunity to ban usage of not valid branch names.

I hope, I explained)

**Comment by marcjay** [comment]
Yeah that makes sense, I'm sure someone else can express the regex in a better way, but this looks perfectly achievable with a regex with a negative lookahead - you will want to customise the regex I imagine however, but this works with the examples above: `^(?![0-9]{1,5}-projectname).*`

With the following `.pre-commit-config.yaml`:
```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: no-commit-to-branch
        args: ['--pattern', '^(?![0-9]{1,5}-projectname).*']
```

I get the following test output:

By default that hooks blocks commits to master
```
(master +) $ pre-commit run
Don't commit to branch...................................................Failed
```
Valid names pass
```
$ git checkout -b 123-projectname-short-description
Switched to a new branch '123-projectname-short-description'
(123-projectname-short-description +) $ pre-commit run
Don't commit to branch...................................................Passed
```

Invalid names fail
```
$ git checkout -b bla-bla
Switched to a new branch 'bla-bla'
(bla-bla +) $ pre-commit run
Don't commit to branch...................................................Failed
```

Does that cover what you're looking for?

**Comment by Jawdeath** [comment]
I've got it, I thought I must use --branch flag, I see now, it's not necessary. And the last question  -is there a way to validate commit message also?

**Comment by marcjay** [comment]
Yup there is 😄 - take a look at https://pre-commit.com/#pre-commit-for-commit-messages

There's a [gitlint](https://github.com/jorisroovers/gitlint) project you might want to take a look at: https://jorisroovers.github.io/gitlint/#using-gitlint-through-pre-commit 

Otherwise it's straightforward to write a custom hook e.g. in bash or python that does this - see the pre-commit docs

**Comment by Jawdeath** [comment]
No, commit pass
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
    - id: no-commit-to-branch
    args: ['--pattern', '(RTB|AQA)_\d+(_\w+)*']

my current branch is named 'lol'.  Don't commit to branch...................................................Passed

**Comment by marcjay** [comment]
Ah, there's a misunderstanding here - the hook is designed to stop you from committing to branches which match some test - either string comparison or regex - i.e "I don't want anyone to commit to a branch named X". X could be the master branch for instance

What you want to do is the reverse of what this hook offers - "I don't want anyone to commit to a branch that's not named like X"

Therefore to reverse this behaviour, you need to reverse/negate the regex - your regex above is saying "I don't want anyone committing to a branch named like RTB123... or AQA123..". So the inverse of that regex would be something like `^(?!(RTB|AQA)\d+(\w+)*).*` - that is what you want to use in your config, and that should work.

So try:
```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: no-commit-to-branch
        args: ['--pattern', '^(?!(RTB|AQA)\d+(\w+)*).*']
```
