### ISSUE TITLE
Pre-commit ignoring args (for ansible-lint)

### ISSUE THREAD

**Issue by fauust** [pre-commit/pre-commit#1047]
Hi,
here is my pre-commit configuration :
```
  - repo: https://github.com/willthames/ansible-lint
    rev: v4.1.0
    hooks:
      - id: ansible-lint
        args: ['-x 602']
```
Pre-commit hook still complains about 602 errors while `$ ansible-lint -x 602 file.yml` doesn't on the same yaml file (I am using the same ansible-lint version installed with pip).

Am I missing something?

Here is a problematic yaml file part for testing :
```
- name: Create error log file (if configured).
  command: "touch {{ mysql_log_error }}"
  args:
    creates: "{{ mysql_log_error }}"
    warn: false
  when:
    - mysql_log == ""
    - mysql_log_error != ""
  tags:
    - mariadb
```
