### ISSUE TITLE
daemon hook

### ISSUE THREAD

**Issue by Fandekasp** [pre-commit/pre-commit#1050]
Use case: 
* Auto-update my tags with ctags on pre-commit
* The update takes time and I don't want to wait for it to finish.

Config tried:
```yml
---
repos:
  - repo: local
    hooks:
      - id: ctags
        name: Update tags
        entry: git ctags &  # git config --global alias.ctags '!.git/hooks/ctags*'
        language: system
```

Adding `&` after `git ctags` didn't change anything, and pre-commit still waits for ctags to finish before commiting.

What is the proper way to daemon-start a command?
