### ISSUE TITLE
How can I fail my commit if black test doesn't pass?

### ISSUE THREAD

**Issue by aviskarkc10** [pre-commit/pre-commit#1053]
My `.pre-commit-config.yml` looks like this:
```
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
```
Whenever I commit my code, the commit is made and only then the hook runs and formats my code with black. What should I do so that my commit is never made if the hook discovers problems with my code?
