### ISSUE TITLE
git commit running long time where as pre-commit running fine

### ISSUE THREAD

**Issue by lokesh1729** [pre-commit/pre-commit#1060]
![image](https://user-images.githubusercontent.com/13495829/59565176-8a70e400-906d-11e9-81f8-5f0160bad526.png)
@asottile 

As the picture shows, I did not understand why `git commit` is taking long time where as `pre-commit run` is taking less time. I have tried `rm -rf ~/.caches/pre-commit` and then installed hooks again, but still the same. `git commit` was hanging for 40 seconds and then it was running... can you tell me what's happening??? I have put debug statements in `.git/hooks/pre-commit` file, I see that in the startup there was a delay....

**Comment by asottile** [comment]
wow that's pretty painful -- can you show the output of:

```
ls -al .git/hooks
pre-commit install
```

it might be possible that there's a `legacy` hook that's silently taking a long time ?

**Comment by lokesh1729** [comment]
this is the output:

![image](https://user-images.githubusercontent.com/13495829/59578690-0f4c1400-90e7-11e9-9e2b-15784a65d8aa.png)


I don't have any legacy hooks I think.... here's my config


```
repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      name: black
      types: [python]
      language_version: python3.6
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
    - id: isort
      name: isort
      types: [python]
      language: python
-   repo: local
    hooks:
    - id: pylint
      name: pylint
      language: system
      types: [python]
      entry: "pylint --rcfile=.pylintrc --load-plugins=pylint_django --load-plugins=pylint_django.checkers.db_performance"
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    - id: flake8
      name: flake8
      types: [python]
      language: python
exclude: ^(config|scripts|db\.sqlite3|\.git|\.flake8|\.gitignore|\.pylintrc|README|pyproject\.toml|\.coverage)$
```
