### ISSUE TITLE
`pre-commit run foo` does not work for pre-push hook `foo`

### ISSUE THREAD

**Issue by madkinsz** [pre-commit/pre-commit#1078]
Hi!

It appears that one cannot run run `pre-push` hooks ids with `pre-commit run`.

e.g.
```
- repo: local
  hooks:
  - id: hadolint
    name: Hadolint
    description: Haskell-based Docker image linter
    language: docker_image
    types:
      - dockerfile
    entry: --entrypoint /bin/hadolint hadolint/hadolint:latest --ignore DL3013 --ignore DL3018 --ignore DL3008 -
  -   id: pytest
      name: Python tests
      entry: --entrypoint pytest mycompany/image:0.13 -v
      language: docker_image
      types: [python]
      stages: [push]
```

```
~/
❯ pre-commit run pytest
No hook with id `pytest`

~/
❯ pre-commit run hadolint
Hadolint.............................................(no files to check)Skipped
```

If I remove `stages: [push]` I can run pytest with the same command as above.
