### ISSUE TITLE
pre-commit changing time a file was last changed

### ISSUE THREAD

**Issue by lorenzwalthert** [pre-commit/pre-commit#1080]
in [lorenzwalthert/pre-commit-hooks](https://github.com/lorenzwalthert/pre-commit-hooks), we want to create a hook that ensures a source file `README.Rmd` is not newer than its derivative `README.md` (because in that case, one forgot to re-generate the derivative from the source). The bash script we use as hook looks as follows:

```bash
if [[ README.Rmd -nt README.md ]]
then
    echo >&2 "README.md is out of date; please re-knit README.Rmd."
    exit 1
fi

num_readmes=$(git diff --cached --name-only | grep -Eic '^README\.[R]?md$')

if [[ "$num_readmes" -lt 2 ]]
then
    echo >&2 "README.Rmd and README.md should be both staged."
    exit 1
fi
```

However, it seems pre-commit changes the attribute *last modified on* of  `README.Rmd` *before* it invokes the entry point. When running the bash script standalone, the *last modified* attribute of `README.Rmd` does not change. The hook passes when I reverse the condition for checking which file is younger (`if [[ README.md -nt README.Rmd ]]`), so we can exclude the possibility that the condition returns a non-zero exit value because of some other problem in the condition. 

The consequence of changing *last modified* attribute of `README.Rmd` seems that the hook always fails, even if before invoking pre-commit, the derivative was indeed newer than the source file.

Any ideas why that happens or how to work around that? The relevant section of `.pre-commit-hooks.config` look like this:

```yaml
-   id: readme-rmd-rendered
    name: readme-rmd-rendered
    description: make sure README.Rmd hasn't been edited more recently than README.md
    entry: bin/readme-rmd-rendered
    language: script
    files: 'README\.[Rr]?md$'
```

Any help appreciated.
