### ISSUE TITLE
vscode doesn't respect virtual environment

### ISSUE THREAD

**Issue by DaveParr** [pre-commit/pre-commit#1101]
> Apologies if this is the wrong place for this, but I thought I might just be missing something that is already possible

Using the following config:
```
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      name: Format python with black
      language_version: python3.7
-   repo: local
    hooks:
      - id: pytest
        name: Check pytest unit tests pass
        entry: pipenv run pytest
        pass_filenames: false
        language: python
        types: [python]
```
I can successfully run the commit for a build I know is passing via the command line as long as I am in a venv/virtual environment in that terminal

However, in using VSCode and clicking the commit _button_ I get errors specifically relating to using the _system_ install of python 3.7 which don't have my dependencies for testing installed on them. e.g. 'scipy not installed'

Is this something I've done wrong, something that isn't supported or something that vscode hasn't respected in the button?
