### ISSUE TITLE
Conflicting pre-commit rewrites prevent commit

### ISSUE THREAD

**Issue by ChrisCummins** [pre-commit/pre-commit#1104]
Hi all,

I've recently discovered this project - what a great tool! I had implemented my own ad-hoc hooks but this is far nicer.

Now, I have a problem. Suppose you have two hooks, `A` and `B`, which both rewrite files. `A` adds an empty newline to the end of the file, and `B` removes an empty newline at the end of the file.  The result of running both hooks is a no-op, however, both pre-commit hooks will modify the file, which will be flagged as failures, preventing the commit.

For a real-world example, I found that `yapf` and `add-trailing-comma` hooks will provide such a conflict:

```
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.28.0
    hooks:
      - id: yapf
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v1.4.1
    hooks:
      - id: add-trailing-comma
```

`yapf` will remove trailing commas, and `add-trailing-comma` will duly add them back. The end result is no modification.

**Workaround**: The workaround is to run the normal pre-commit pipeline, then, after checking that no files were *actually* modified using `git status`, to run the commit again using `git commit --no-verify`.

**Solution**: The solution, as far as I can see, is to checksum the file before running any hooks, and then checksum it again at the end of the pipeline. Only if the two checksums differ should the file be flagged as modified (the individual hooks can continue to report that the files have been modified).

I am not at all familiar with the internals of this project, so I don't know how great of a change this would take to implement. If you don't checksum files, but only use mtimes, then this won't work.

If someone familiar with the codebase points me in the right direction, I'd be happy to take a look at implementing this.

Cheers,
Chris
