### ISSUE TITLE
How to run pre-commit inside folder

### ISSUE THREAD

**Issue by imomaliev** [pre-commit/pre-commit#1110]
Hi! I have project structure like this
```
.
├── README.md
├── backend
│   ├── Pipfile
│   ├── Pipfile.lock
│   ├── mypy.ini
│   ├── pylintrc
│   ├── pyproject.toml
│   ├── src
│   ├── tests
│   └── tox.ini
├── docker
│   ├── backend
│   └── postgres
├── docker-compose.yml
└── .pre-commit-config.yaml

```

I would like to run pre-commit's flake8 inside `backend` folder, how could I achieve this?

**Comment by naktu** [comment]
Hi! Send you path via args.

**Comment by imomaliev** [comment]
@naktu it wouldn't work correctly. I need it to be run from inside folder not to have run on folder. 

it should be like this
```
cd backend/

**Comment by naktu** [comment]
Can you show your pre-commit configuration file?

**Comment by imomaliev** [comment]
@naktu 
```
default_language_version:
  python: python3.7

default_stages: [commit, push]

repos:
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        name: black
        language: system
        entry: black
        args: [--config=backend/pyproject.toml, --check, --diff, backend/]
        types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: flake8
        name: flake8
        language: system
        entry: flake8
        additional_dependencies: ["flake8-bugbear==19.3.0", "flake8-django==0.0.4", "flake8-docstrings==1.3.1", "pylint-django==2.0.11"]
        args: [--config=backend/tox.ini, backend]
        types: [python]
```
