### ISSUE TITLE
Access to files in hook repository from hook execution

### ISSUE THREAD

**Issue by renannprado** [pre-commit/pre-commit#1135]
I'm trying to have a shared configuration for `gitlint` that will be used by multiple repositories I own and I wouldn't like to have one `.gitlint` config file per repository. I would like to have it in my custom hooks repository and just use it like any other hook, but pre-configured.

I've been successful to do that, I created a new hook repository where I basically create a "new hook" that in the end is just `gitlint`, but passing more default parameters.

However I would rather use the configuration file that `gitlint` provides so that I don't have to put in my `entry` configuration all the parameters I have.

But when I do something like

```yaml
  entry: gitlint --config my_path/.gitlint
```

This file is not found by gitlint because the current working directory where the script is run is always the directory where you're executing the hook, so I have no access to anything in the hook repo.

I was just wondering if there's a way to do that and if not, if this could be an interesting feature to add to `pre-commit` or any other advise on how to do that would be helpful.

Thanks!

**Comment by asottile** [comment]
A script can usually find the path to itself by using `argv[0]` -- does that work for you? (you'd then join paths from there to find your particular configuration)

**Comment by renannprado** [comment]
I suppose that would work. Then I suppose I could do the following:

1 - write a python script that wraps `gitlint` execution
2 - execute gitlint with this `argv[0]`

What I'm attempting so far is literally using `gitlint` as a dependency and I don't have to write anything else other than the below. But with what is provided by `pre-commit` today, there's no better way to do it other than this, right?

I could easily do it with `script` (because I'm not familiar with python), but the problem is that if I have a bash script, then I can't use the `additional_dependencies`, right?

This is my `.pre-commit-hooks.yaml`:

```yaml
- id: commit-message-linter
  name: commit-message-linter
  entry: gitlint --config pre_commit_hooks/.gitlint
  description: Linter for commit messages
  language: python
  verbose: true
  additional_dependencies: ["gitlint==v0.12.0"]
```
