### ISSUE TITLE
Conditional hooks (run only if docker is present or if docker is not present)

### ISSUE THREAD

**Issue by henryiii** [pre-commit/pre-commit#1146]
I would like to setup a clang-format hook. It's quite easy:

```yaml
- repo: local
  hooks:
  - id: docker-clang-format
    name: Docker Clang Format
    language: docker_image
    types:
    - c++
    entry: unibeautify/clang-format:latest
    args:
    - -style=file
    - -i
```

However, some of the developers I'm working with do not like installing docker, so I'd like to have a fallback hook that uses the user's local clang-format (risking version incompatibilities).

I *think* the easiest way to do this would be to have a conditional entry, that would check to see if the docker command is present (or the `docker_image` language is available). Then I could add two hooks, on if docker is available, one if docker is not. Maybe a fallback hook and a deactivated (unless called as a fallback) would be better. Any ideas?

And let me know if I am mistaken and this is currently possible!
