### ISSUE TITLE
Enforce always_run contract to all types of hooks

### ISSUE THREAD

**Issue by dtanedo** [pre-commit/pre-commit#1147]
Hi,

We have a configuration file which is like this

```
minimum_pre_commit_version: 1.18.3
fail_fast: true
repos:
-   repo: sample
      rev: v1.2.0
      hooks:
        - id: sample-hook-one
          verbose: true
          always_run: true
        - id: sample-hook-two
          stages: [push]
        - id: sample-hook-three
          stages: [push]
```

sample_hook_one runs only once during **git commit** while it runs multiple times in **git push**.
I think it should run once during push so that the **always_run option** is the same across all options.
