### ISSUE TITLE
[question] is it possible to run all hooks of a repository?

### ISSUE THREAD

**Issue by acecilia** [pre-commit/pre-commit#1158]
Hello:

I would like to have a `pre-commit-hooks` repository containing my custom hooks, and when used in a project, use all of the hooks in the repository. Is this possible? I could not find information about it in the docs neither the open or closed issues.

To sum up, instead of having the content of `.pre-commit-config.yaml` as:
```
repos:
  - repo: https://github.com/acecilia/newpre-commit-hooks
    rev: 1.0.0
    hooks:
      - id: hook1
      - id: hook2
      - id: hook3
      - id: hook4
      - id: hook5
      ...
```

have it as:

```
repos:
  - repo: https://github.com/acecilia/newpre-commit-hooks
    rev: 1.0.0
    hooks: all
```

Thanks!
