### ISSUE TITLE
Misleading error message when entry script is present but not executable

### ISSUE THREAD

**Issue by nixjdm** [pre-commit/pre-commit#1159]
Hi! I'm getting acquainted with pre-commit (I love it by the way). I tried adding a prepare-commit-msg script with

```yaml
-   repo: local
    hooks:
      - id: some-id
        name: Some Name
        stages: [prepare-commit-msg]
        entry: ./bin/prepare-commit-msg.sh
        language: script
```

At first I neglected to `chmod +x bin/prepare-commit-msg.sh`, so when I tried it out, I got the message

```
Executable `[path]/bin/prepare-commit-msg.sh` not found
```

The file was present, it just wasn't marked executable. I squinted for a short while looking for a typo somewhere before realizing my mistake.
