### ISSUE TITLE
How can I run pre-commit stage for setup.py file which is in different path?

### ISSUE THREAD

**Issue by virad3** [pre-commit/pre-commit#1164]
```yaml
repos:
  - repo: local
    hooks:
      - id: unittests
        name: unittests
        entry: python -m discover tests
        language: python
        language_version: python3.6
```
I need to install the local package using different setup file. Say **setup_test.py**
What configuration should I used to enable this feature in my project?
