### ISSUE TITLE
.pre-commit-hooks.yaml does not exist

### ISSUE THREAD

**Issue by jeunii** [pre-commit/pre-commit#1166]
Its my first time using `pre-commit` today.

I first installed it using `brew install pre-commit` on my macbook. 
```
pre-commit --version
pre-commit 1.18.3
```
Then in my repo I have a file (created and committed) `.pre-commit-hooks.yaml` whose contents are
```
- id: trailing-whitespace
  name: Trim Trailing Whitespace
  entry: trailing-whitespace-fixer
```
And then I create a file `.pre-commit-config.yaml` whose contents are
```
repos:
- repo:<URL>/test-repo
  rev: master
  hooks:
  - id: trailing-whitespace
```
When I run `pre-commit run -a`, I get the Error
```
pre_commit.clientlib.InvalidManifestError:
=====> /Users/yser/.cache/pre-commit/repo08_hn1ux/.pre-commit-hooks.yaml does not exist
```
Would you know what this happens ?
