### ISSUE TITLE
Executable `/bin/bash` not found on Windows

### ISSUE THREAD

**Issue by steigenTI** [pre-commit/pre-commit#1171]
When I run `pre-commit run --all-files` I get an error message that says `Executable '/bin/bash' not found`

I have Cygwin installed and `cygwin/bin` added to my path.

See my config file below.

`.pre-commit-config.yaml`
```
repos:
- repo: https://github.com/digitalpulp/pre-commit-php.git
  rev: 1.3.0
  hooks:
  - id: php-cs
    files: ^web\/(modules\/custom|themes\/my_theme)\/.+.php$
    args: [--standard=Drupal -p]
```
