### ISSUE TITLE
Platform dependent local repo entry

### ISSUE THREAD

**Issue by thejcannon** [pre-commit/pre-commit#1194]
Thanks to the lovely fact that on Windows, executable Python scripts in a virtual environment go in `Scripts` and on non-Windows go in `bin`. I'm not sure if there's a way to specify my local repo hook to work on both platforms.

**Comment by asottile** [comment]
untested, but you should be able to expand on this

### `./scripts/run-venv-foo`

```bash
#!/usr/bin/env bash
set -euo pipefail

if [ ! -d venv ]; then
    echo 'virtualenv `venv` does not exist -- make sure to set up your dev environment!'
    exit 1
fi

if [ -d venv/Scripts ]; then
    exec venv/Scripts/foo "$@"
else
    exec venv/bin/foo "$@"
fi
```

### `.pre-commit-config.yaml`

```yaml
repos:
-   repo: local
    hooks:
    -   id: local-foo
        name: foo
        language: script
        types: [text]
        entry: ./scripts/run-venv-foo
```

**Comment by asottile** [comment]
hope that helped!

**Comment by thejcannon** [comment]
Sorry, should've commented immediately. That certainly works, but doesn't scale that well if there are multiple scripts to invoke.

Consider allowing entry to be a string or a dict:
```yaml
...
entry:
-   Win: ./venv/Scripts/foo
    Unix: ./venv/bin/foo
args: ['baz', 'bar']
```
(Sorry if my YAML is off, I don't have YAML goggles yet)
