### ISSUE TITLE
saving the cache when running in CI

### ISSUE THREAD

**Issue by bryanlarsen** [pre-commit/pre-commit#1207]
Here's our .gitlab-ci.yml:

```
pre_commit:
  stage: build_test
  image: bryanlarsen/pre-commit
  cache:
    paths:
      - pre-commit-cache/
  script:
      - PRE_COMMIT_HOME=$(pwd)/pre-commit-cache pre-commit run --all-files
```

I believe this should re-use the cache, and it's saving a whole bunch of files in pre-commit-cache but it ends up initializing all of the environments on every run.  Help?

**Comment by asottile** [comment]
looks correct to me, have you been able to debug whether the cache is being saved / restored properly? 

if you run the command twice does it reuse the environments?

(we're not really a CI debugging service so you'll need to do a bit of due diligence here!)

**Comment by asottile** [comment]
I notice you're also using a pretty old version of `pre-commit`?

**Comment by asottile** [comment]
@bryanlarsen could you provide more information?

**Comment by bradym** [comment]
I've been struggling with this today, doesn't seem to be related to pre-commit. Here's what finally got it working for me.

```
pre_commit:
    stage: pre_build
    image: bryanlarsen/pre-commit
    script:
      - PRE_COMMIT_HOME=$CI_PROJECT_DIR/.cache/pre-commit pre-commit run --files $(git diff-tree --no-commit-id --name-only -m -r "$CI_COMMIT_SHA")
    cache:
      paths:
        - $CI_PROJECT_DIR/.cache
    rules:
    - exists:
        - .pre-commit-config.yaml
```

**Comment by asottile** [comment]
sweet!  I plan to better document caching in the docs as well as `PRE_COMMIT_HOME`

**Comment by playpauseandstop** [comment]
Hi,

Just want you to know that I have an issue with caching pre-commit repos between Gitlab CI runs and recipe from https://github.com/pre-commit/pre-commit/issues/1207#issuecomment-554555279 helped me as well.

Thanks @bradym!

----

ps. Previously I've tried to cache `.cache/pre-commit` or `/root/.cache/pre-commit` directories, where I supposed pre-commit by default cache repos it used, but Gitlab CI said that no files found on given locations.

**Comment by asottile** [comment]
I've improved the docs around this: https://pre-commit.com/#managing-ci-caches

If someone would like to add other CI providers, please submit a PR to https://github.com/pre-commit/pre-commit.github.io (I don't have enough experience with gitlab CI / circle / etc.)

**Comment by MaxWinterstein** [comment]
I cannot get this to work as desired, maybe someone can point me in the right direction.  
It seems the cache is pulled correctly but the first black run still takes over 1 minute.


`gitlab-ci.yaml`
```yaml
.pre-commit:
  stage: test
  image: bryanlarsen/pre-commit
  script:
    - pip install --upgrade pre-commit # update pre-commit as the image is pretty old
    - pre-commit run -v --all-files --show-diff-on-failure
    - pre-commit run -v --all-files --show-diff-on-failure
  variables:
    PRE_COMMIT_HOME: $CI_PROJECT_DIR/.cache/pre-commit
  cache:
    key: pre-commit
    policy: pull-push
    paths:
      - $CI_PROJECT_DIR/.cache
```

`.pre-commit-config`
```
repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3

    # Version must match the one specified in .gitlab-ci.yaml
  - repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
      - id: isort
```

Job output:
```bash
[2020/11/03 18:17:08] $ pre-commit run -v --all-files --show-diff-on-failure
[2020/11/03 18:18:16] black....................................................................Passed
[2020/11/03 18:18:16] - hook id: black
[2020/11/03 18:18:16] - duration: 67.08s
[2020/11/03 18:18:16] 
[2020/11/03 18:18:16] All done! ✨ 🍰 ✨
[2020/11/03 18:18:16] 352 files left unchanged.
[2020/11/03 18:18:16] 
[2020/11/03 18:18:18] isort....................................................................Passed
[2020/11/03 18:18:18] - hook id: isort
[2020/11/03 18:18:18] - duration: 2.42s
[2020/11/03 18:18:19] $ pre-commit run -v --all-files --show-diff-on-failure
[2020/11/03 18:18:20] black....................................................................Passed
[2020/11/03 18:18:20] - hook id: black
[2020/11/03 18:18:20] - duration: 0.68s
[2020/11/03 18:18:20] 
[2020/11/03 18:18:20] All done! ✨ 🍰 ✨
[2020/11/03 18:18:20] 352 files left unchanged.
[2020/11/03 18:18:20] 
[2020/11/03 18:18:22] isort....................................................................Passed
[2020/11/03 18:18:22] - hook id: isort
[2020/11/03 18:18:22] - duration: 2.41s
```

Why is the first run always taking so long? Tried to exclude the `.cache/` folder but this seems not to improve anything.
