### ISSUE TITLE
Use with ruby bundler

### ISSUE THREAD

**Issue by revolter** [pre-commit/pre-commit#1208]
I added a local ruby hook with this configuration:

```yaml
-   repo: local
    hooks:
    -   id: check-xcode-version
        name: Check Xcode version
        description: Ensures that the version specified in the `.xcode-version` file is valid
        entry: bundle exec ruby hooks/check_xcode_version.rb
        language: ruby
        files: .xcode-version
```

and it crashes with error:

```
/Users/revolt/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.0.2) required by your /Users/revolt/Development/Project/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.0.2`
	from /Users/revolt/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
	from /Users/revolt/.rbenv/versions/2.6.4/bin/bundle:23:in `<main>'
```

Running `bundle exec ruby hooks/check_xcode_version.rb` directly in terminal works.

What could be the problem?
