### ISSUE TITLE
Filtering which files to pass VS filtering for which files to trigger the hook

### ISSUE THREAD

**Issue by cb109** [pre-commit/pre-commit#1214]
I am not sure if my use case can be handled by the existing CLI, if it can please let me know, otherwise consider this a humble feature request.

I would like to run an expensive hook **only when** some specific files have changed, **without** passing those filenames to the hook command/script. It seems right now I can only do `pass_filenames: true` with `files: <regex>` and `types: [...]` to control whether the hook is triggered, but then I must call a command that takes those filenames as arguments. Using `pass_filenames: false` will fix that, but I cannot fine-control whether to call the hook anymore.

My example is this:
```yaml
- repo: local
  hooks:
  - id: checkmigrations
    name: check that there are no django migration conflicts
    entry: python manage.py checkmigrations
    language: system
    files: (models|migrations)/
    types: [python]
```

This fails because the `checkmigrations` command doesn't take any arguments, but is called like:

```bash
python manage.py checkmigrations models/mymodel.py migrations/1234_model.py
```
 My workaround is to write a custom command that wraps this and just accepts arguments without doing anything with them.

Am I missing a combination of options to achieve what I want? It would be great to have this level of control. Adoption of the pre-commit rules is heavily linked to how long it takes to run and I am trying to minimize the cases in which hooks are run unnecessarily.

**Comment by asottile** [comment]
`pass_filenames: false` is what you want, it will still trigger only if the specified files/types are matched but won't pass along those matched filenames

**Comment by cb109** [comment]
Thanks for clarifying, will give that a try. I probably got something wrong somewhere

**Comment by cb109** [comment]
Of course I got my regex wrong. So I can use one of the following, both do what I want:
```yaml
pass_filenames: false
files: (models|migrations)/.*\.py
```
or
```yaml
pass_filenames: false
files: (models|migrations)/
types: [python]
```

@asottile Sorry for bothering, thank you for the swift support and of course for the tool itself! :tada:
