### ISSUE TITLE
RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.

### ISSUE THREAD

**Issue by allen-munsch** [pre-commit/pre-commit#1225]
Having an issue with getting pre-commit  to `pre-commit install -f --install-hooks`:

```shell
pre-commit install -f --install-hooks
pre-commit installed at .git/hooks/pre-commit
[INFO] Initializing environment for https://github.com/prettier/prettier.
An unexpected error has occurred: CalledProcessError: Command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
Return code: 128
Expected return code: 0
Output: (none)
Errors: 
    error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
    fatal: The remote end hung up unexpectedly
    fatal: early EOF
    fatal: index-pack failed
```

`.pre-commit-config.yaml`:

```yaml
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6
  - repo: https://github.com/prettier/prettier
    rev: 1.19.1
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: python -m pylint.__main__
        language: system
        types: [python]
        exclude: migrations
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v5.16.0
    hooks:
      - id: eslint
        files: assets/js
        exclude: tests
        additional_dependencies:
          - eslint@2.9.0
          - eslint-plugin-mocha@5.3.0
          - eslint-plugin-react@3.16.1
          - eslint-plugin-promise@latest
          - babel-eslint@6.1.2
  - repo: git://github.com/awebdeveloper/pre-commit-tslint
    rev: v0.0.2
    hooks:
      - id: tslint
        additional_dependencies:
          - tslint@5.12.1
          - typescript@3.0.1
```

Adding git configurations doesn't appear to get passed along?:

`GIT_CURL_VERBOSE=1 pre-commit install -f --install-hooks`

```shell
export GIT_TRACE_PACKET=1
export GIT_TRACE=1
export GIT_CURL_VERBOSE=1
```

From:

```
def no_git_env(_env=None):
    # Too many bugs dealing with environment variables and GIT:
    # https://github.com/pre-commit/pre-commit/issues/300
    # In git 2.6.3 (maybe others), git exports GIT_WORK_TREE while running
    # pre-commit hooks
    # In git 1.9.1 (maybe others), git exports GIT_DIR and GIT_INDEX_FILE
    # while running pre-commit hooks in submodules.
    # GIT_DIR: Causes git clone to clone wrong thing
    # GIT_INDEX_FILE: Causes 'error invalid object ...' during commit
    print(os.environ.keys())
    _env = _env if _env is not None else os.environ
    return {
        k: v for k, v in _env.items()
        if not k.startswith('GIT_') or
        k in {'GIT_EXEC_PATH', 'GIT_SSH', 'GIT_SSH_COMMAND'}
    }
```

I can see the env variables in `os.environ`

I've also increased the `git config --global http.postBuffer 1048576000`

Any other suggestions?
