### ISSUE TITLE
Use defaults to avoid repeated hook id/name/entry

### ISSUE THREAD

**Issue by bhrutledge** [pre-commit/pre-commit#1240]
In my continued quest to single-source the versions of linters and formatters between pre-commit and my Python virtual environment (see #1233 and https://github.com/pre-commit/pre-commit/issues/945#issuecomment-563978549), I tried [repository local hooks](https://pre-commit.com/#repository-local-hooks) as suggested by #945. It works well, but I ended up with a config like:

```
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        types: [python]
```

The repetition of `id`, `name`, and `entry` bugs me. 😉 

Could `name` and `entry` default to the value of `id`?

**Comment by asottile** [comment]
`repo: local` and `language: system` both are escape hatches and not the supported golden path to use tools

the metadata for `repo: local` is the full `.pre-commit-hooks.yaml` and is meant to be very explicit

so no, I won't do this -- but thank you for the issue!

If you want a supported configuration, use this with no repetition:

```yaml
repos:
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
-   repo: https://github.com/pycqa/pydocstyle
    rev: 5.0.1
    hooks:
    -   id: pydocstyle
```
