### ISSUE TITLE
Exclude argument does not work for autopep8 hook. 

### ISSUE THREAD

**Issue by pcbt** [pre-commit/pre-commit#1285]
Hi,
 I want to exclude an specific file from autopep8 hook, here are the confs I tried:
```
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
        args:
        - -i
        - -r
        - src
        always_run: true
        exclude: template.__init__.py
```
This one simple does not work and formats the ```src/template.__init__.py``` file.
```
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
        args:
        - -i
        - -r
        - src
        - --exclude=template.__init__,py
        always_run: true
```
This one does not work when I modify the ```src/template.__init__.py``` file and gives this error:
```
autopep8.................................................................Failed
- hook id: autopep8
- exit code: 2

usage: autopep8 [-h] [--version] [-v] [-d] [-i] [--global-config filename]
                [--ignore-local-config] [-r] [-j n] [-p n] [-a]
                [--experimental] [--exclude globs] [--list-fixes]
                [--ignore errors] [--select errors] [--max-line-length n]
                [--line-range line line] [--hang-closing] [--exit-code]
                [files [files ...]]
autopep8: error: unrecognized arguments: src/template.__init__.py
```
By the way ```autopep8 -i -r src --exclude=template._init__.py``` works as expected. How can I exclude a specific file?

**Comment by asottile** [comment]
mmm so you've missed some fundamental bits about pre-commit, let's do some basic engineering and try and get us to a minimal reproduction -- I'll hopefully teach you where you went wrong along the way :)

one of the design aspects of pre-commit is "reasonable defaults" -- that is you ~generally shouldn't need to change things (or much) to get your desired output.

Let's start with the most basic autopep8 configuration:

```yaml
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
```

based on the values here, this sets some defaults, notably it already gives you [`-i`](https://github.com/pre-commit/mirrors-autopep8/blob/751466f46bd015149429ab7dffcc43b803e57dfa/.pre-commit-hooks.yaml#L6)

if we apply exclude here:


```yaml
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
        # your value for exclude would also work, I'm just being more specific
        exclude: template\.__init__\.py$
```

then it works! perfect!

but let's look at the things you tried and why they don't work.

first let's look at `args`

```yaml
        args:
        - -i
        - -r
        - src
```

this changes the autopep8 command from `autopep8 -i {filenames}` to `autopep8 -i -r src {filenames}`

you can read more about the command line building [here](https://pre-commit.com/#arguments-pattern-in-hooks) though generally it's pretty straightforward in that pre-commit takes `entry` + `args` + `filenames` and calls it

the reason you *don't* want this, is you're **always running against all your files**.  even if no python file changed you're spending all this time running `autopep8` for no reason.  part of the optimizations that pre-commit makes is it [knows what changed](https://pre-commit.com/#pre-commit-during-commits) and will [only run against that](https://pre-commit.com/#pre-commit-during-merges).

let's look at some sample commands that might've run if you touched specific files.

let's say you only touch `src/foo.py` and  `src/template.__init__.py` with that configuration you'd run something like:

```bash
autopep8 -i -r src src/foo.py src/template.__init__.py
```

if you used your exclude it would run

```bash
autopep8 -i -r src src/foo.py
```

notice that it's still running against `src` in both of those!

___

now let's look at the other option you set, `always_run: true`.  this option is for _very rare cases_ where you can't properly express the files that may change the output of a hook.  an example is running tests, you may only care about a few test files but data files, dependencies, etc. can change the result of those tests.  it also is ~usually coupled with `pass_filenames: false`.  In general you *don't* want this option and should rely on pre-commit to decide when it needs to run your hook (if you need to run everything, use `pre-commit run --all-files` as suggested in the [usage in continuous integration](https://pre-commit.com/#usage-in-continuous-integration) section).

___

if you do want to limit `autopep8` to only lint the `src` directory (this seems to be your intention given the `args`) you should do so with the `files` regex:

```yaml
    files: ^src/
```

___

putting this all together you end up with something like:

```yaml
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
        files: ^src/
        exclude: template\.__init__\.py$
```

___

as for the error message you have above you've left out some important details or failed to copy paste properly -- your configuration with `--exclude` in args has a typo so it can't run (there's a `,`) and the error message you have doesn't match that
