### ISSUE TITLE
Question - When writing a custom hook, how to access the value given to --hook-stage

### ISSUE THREAD

**Issue by martyzz1** [pre-commit/pre-commit#1294]
I'm trying to write a pre-commit hook which wraps around husky. Our frontend team use husky, and the the existing eslint hook available to pre-commit doesn't really cover the things my team have done with husky. 

Husky works by having the same hook script defined for every git hook.....   It then uses the filename of the git hook to work out which actual hook to invoke...

I noticed that pre-commit passes a --hook-stage into itself at run time, and I'm wondering if this is exposed to custom hooks in some way - as this would be really very useful....

**Comment by asottile** [comment]
we don't expose anything like this directly today (it could be an environment variable, `PRE_COMMIT_HOOK_STAGE`)

however, you can still accomplish this today with the given facilities:

```yaml
-   repo: meta
    hooks:
    -   id: identity
        args: [--push]
        stages: [push]
    -   id: identity
        args: [--commit]
        stages: [commit]
```

```console
$ pre-commit run identity --hook-stage commit --files setup.cfg 
identity.................................................................Passed
- hook id: identity
- duration: 0.04s

--commit
setup.cfg

$ pre-commit run identity --hook-stage push --files setup.cfg 
identity.................................................................Passed
- hook id: identity
- duration: 0.03s

--push
setup.cfg

```

(this works because pre-commit lets you repeat a hook id)
