### ISSUE TITLE
Solution: pylint in venv (tox) with pre-commit hook

### ISSUE THREAD

**Issue by Cielquan** [pre-commit/pre-commit#1309]
I like some others have/had problems with running the dynamic checking of pylint with a pre-commit hook and virtual environments.
After some testing I found a solution, which also works in CI (Travis at least). I use tox for managing my venvs in a project and CI but this solution should also work with manual managed venvs.

Here is the important part of my config:

`tox.ini`:
```
...
[testenv:pre-commit]
description = format the code
passenv =
    SSH_AUTH_SOCK
    http_proxy
    https_proxy
    no_proxy
deps =
    {[testenv]deps}
    pylint >= 2.4, < 3
    pre-commit >= 2, < 3
extras =
    {[testenv]extras}
    docs
commands =
    pre-commit run --all-files --show-diff-on-failure
...
```
`{[testenv]deps}` is `pip >= 20` and `{[testenv]extras}` is `testing`

`.pre-commit-config.yaml`:
```
repos:
...
  - repo: local
    hooks:
      - id: pylint
        args: [--ignore=version.py]
        name: pylint
        entry: .tox/pre-commit/bin/pylint
        language: system
        types: [python]
...
```

The important part is the entry in `.pre-commit-config.yaml`. 

As these configs are easy reproducible because of the relative path pointing to a tox venv its easy to use.

Maybe this is worth mentioning in the docs as a tip?

**Comment by asottile** [comment]
thanks for the recipe!

**Comment by jenstroeger** [comment]
Hmm. Suppose I have a git repo, with an `app` folder that contains a Python package in a venv, but also a bunch of other sibling folders. Running:
```
project > PYTHONPATH=app ./bin/pylint --rcfile=./pylint.cfg app
```
works and it checks only the Python files in `app/`. My pre-commit config is
```yaml
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: bin/pylint
        language: python
        args:
          [
            "--rcfile=pylint.cfg",
            "app"
          ]
```
and the init hook for pylint is set to
```
init-hook="import sys; sys.path.append('app')"
```
Still, pylint runs over _all_ files in the repo, and not the `app/` folder. Any tips?
