### ISSUE TITLE
Cannot specify custom Python shebang for hook executable

### ISSUE THREAD

**Issue by kbsezginel** [pre-commit/pre-commit#1312]
I am working on a shared Python environment with `python3.6` as executable and I want the shebang to point to the correct executable `#!/usr/bin/env python3.6`. However, even though I specify 
```
default_language_version:
    python: python3.6
```
or  `language_version: python3.6` in `hooks`, it always picks `#!/usr/bin/env python` as the shebang even though there is no `python` executable. Is there a way to specify a custom shebang?

**Comment by asottile** [comment]
could you provide a reproduction? I'm not sure which shebang you are referring to

**Comment by kbsezginel** [comment]
Sure, I am using the following `.pre-commit-config.yaml`:
```
default_language_version:
    python: python3.6
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
        - id: black
```
and when I run `pre-commit install` it adds `#!/usr/bin/env python` to the hook executable (`.git/hooks/pre-commit`). 

I am on `pre-commit 2.0.1`.
