### ISSUE TITLE
Display file being acted on? (specifically when using curl)

### ISSUE THREAD

**Issue by ChrisWeiss** [pre-commit/pre-commit#1313]
I'm trying to build a more generic version of the Jenkins linter that leverages curl to submit the file being reviewed to the Jenkins server's linting endpoint (based on https://github.com/Lucas-C/pre-commit-hooks).
The problem is, the file under test is being passed in as POST data in the curl statement so the name is not echoed as part of the process. If several files are submitted and one fails, I have no way of knowing which file it was.

Hook:
```
-   repo: local
    hooks:
    -   id: Jenkinsfile-linter
        name: Check Jenkinsfile following the scripted-pipeline syntax using Jenkins API
        language: system
        entry: sh -c '! curl --silent https://re.jenkins.bmx.nikecloud.com/job/cweiss/job/linter/1/replay/checkScriptCompile --user $JENKINS_USER:$JENKINS_TOKEN --data-urlencode value@$@ | grep -F "\"status\":\"fail\""'
        files: \.groovy$
        verbose: true
```

Sample Output (run against a dozen or so matching files):
```
❯ pre-commit run --all-files
Check Jenkinsfile following the scripted-pipeline syntax using Jenkins API.......................Failed
- hook id: Jenkinsfile-linter
- duration: 6.07s
- exit code: 1

[{"column":55,"line":88,"message":"expecting ')', found ';'","status":"fail"}]
```

This may just be a shell usage issue - I didn't have any luck appending things like `&& echo $@` or `; echo $@` with no success. It seems like an option to echo the filename under test might be handy under other circumstances as well.
