### ISSUE TITLE
Top level option to run all hooks in docker container.

### ISSUE THREAD

**Issue by verhovsky** [pre-commit/pre-commit#1315]
We use https://github.com/asottile/reorder_python_imports through pre-commit. The problem is that some people have some libraries not installed outside the docker container, so that hook produces different groupings based on whether it's run from the container or outside it. So I've changed the hook to use `language: docker_image`, like this:

```yaml
-   repo: local
    hooks:
    -   id: reorder-python-imports
        name: reorder-python-imports (inside the Docker container)
        types: [python]
        exclude: '/migrations/'
        language: docker_image
        entry: docker.example.com:9028/some/path/container_name:latest reorder_python_imports "--application-directories=/some/dir:/some/dir/some/subdir"
```

Then I noticed that I still get different results in a different hook because I have a more recent clang-format version installed outside the container. 

Can I please get a config option that causes pre-commit to run everything inside a specified docker container?
