### ISSUE TITLE
Custom --workdir with Docker hooks.

### ISSUE THREAD

**Issue by CathalMullan** [pre-commit/pre-commit#1330]
Looking for clarity if this is expected behaviour or not.

Some of my unit tests need to be executed within a specific directory, and as such the working directory of the image needs to be changed.

I can pass additional Docker run options before the image part of `entry` and override the defaults. The documentation mentions this only for `--entrypoint`, but seemingly any option can be passed in.

```yaml
- id: test
  name: Example.
  entry: --workdir /src/tests my_image:latest
  language: docker_image
```

Is this overriding of `--workdir` expected (and supported) or not?
If it is, might be worthwhile documenting it further.
