### ISSUE TITLE
[question] phpstan-hook gives different result than from bash

### ISSUE THREAD

**Issue by leberknecht** [pre-commit/pre-commit#1333]
Ahoi!
I have this hook: 

.pre-commit-config.yaml
```yaml
    -   id: phpstan
        name: phpstan
        entry: ./api/vendor/bin/phpstan analyze api/src --level 4
        language: system
        files: ^api/
        types: [php]
```
changes  and this config-section do have an impact on `git commit` which is good, but: i have tweaked phpstand-rules a little bit:

api/phpstan.neon
```yaml
parameters:
    excludes_analyse:
        - %currentWorkingDirectory%/src/DoctrineMigrations/*
        - %currentWorkingDirectory%/src/DataFixtures/*
        - %currentWorkingDirectory%/src/Hook/*

    includes:
        - vendor/phpstan/phpstan-doctrine/extension.neon
    disallowFloatsEverywhere: true

#
#   this is the same as vendor/phpstan/phpstan/conf/config.level0.neon
#   just without PHPStan\Rules\Methods\CallMethodsRule
#
rules:
    - PHPStan\Rules\Arrays\DuplicateKeysInLiteralArraysRule
[...]
```
I have removed some rules that dont make much sense for my case. 
When i fire phpstan manually from the project-root dir like this:
```
 % ./api/vendor/bin/phpstan analyze api/src --level 4
Note: Using configuration file /home/delf/dev/efi/phpstan.neon.
 176/176 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

                                                                                                                        
 [OK] No errors                                                                                                         
```
..then all is fine. 
But when i fire the git commit, i get some errors (which looks like the rule-modifications in `
api/phpstan.neon` were ignored):
```
% git commit -am "..."   
phpcs....................................................................Passed
phpstan..................................................................Failed
hookid: phpstan-new

------ ------------------------------------------------------------------------- 
  Line   tests/Service/ReportShareServiceTest.php                                 
 ------ ------------------------------------------------------------------------- 
  71     Property App\Tests\Service\ReportShareServiceTest::$userRepoMock         
         (App\Repository\UserRepository&PHPUnit\Framework\MockObject\MockObject)  
         does not accept PHPUnit\Framework\MockObject\MockObject.                 
[...]
```
Not sure though, but it looks like the working-dir of the spawned process is somehow different than the project root. Is that possible, or can anyone provide some tips how i can dig into this and debug what causes this problem?
