### ISSUE TITLE
A way to suspend errors

### ISSUE THREAD

**Issue by Nihisil** [pre-commit/pre-commit#1342]
Is there a way to suspend error for specific hooks?

Configuration:
```
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
```

I want to see errors from `flake8` always. And from `black`, I don't want to have a blocking commit error. 

So, `black` will format files and show what files were formatted before commit, but these issues will not block the commit itself. Is there a configuration for behavior like that?
