### ISSUE TITLE
Support updating additional_dependencies in autoupdate

### ISSUE THREAD

**Issue by styurin** [pre-commit/pre-commit#1351]
`autoupdate` is not updating versions of libraries in `additional_dependencies`.

For example, I have this config:

```
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-bugbear==18.8.0
          - flake8-builtins==1.4.1
          - flake8-comprehensions==1.4.1
          - flake8-tidy-imports==1.1.0
```

After running `pre-commit autoupdate` only the version of flake8 is updated to 3.7.9.

Two reasons to do update additional dependencies:
- old versions of libraries in additional dependencies may not be compatible with latest versions of top level hooks.
- in some cases these additional dependencies need to be in sync in multiple hooks, for example, yesqa needs the same dependencies as flake8.

I would be great if these dependencies were updated when running `autoupdate`.

**Comment by asottile** [comment]
there's a duplicate somewhere but it's very difficult to do this correctly and so it is intentionally not done:

- the contents of `additional_dependencies` are not parsed in any way, just forwarded along to the underlying tools (they are not structured data)
- each language has their own format of the strings contained in there (and there is no consistency there)
- pre-commit doesn't know anything about the various language-specific package repositories and couldn't gain information to update those properly (`autoupdate` works because the packaging unit of pre-commit is a `git` repository with a linear history)
- even for `python` supporting this would be difficult, a common use case is to use `additional_dependencies: ['--index-url', 'https://mycompany.example.com/simple', ...]` and so we would need to understand the full argument parsing of `pip` which is very out of scope

So while this sounds like a good idea, it's kind of intractably difficult to implement without ballooning complexity

**Comment by AIGeneratedUsername** [comment]
While all describe here https://github.com/pre-commit/pre-commit/issues/1351#issuecomment-594111058 is true, but, at the same time, many people just want to update their Flake8 plugins. 

### Here is a workaround for @styurin and anyone who comes here from the web search:

1. Create a separate file with pinned Flake8 plugins. E.g. "requirements_flake8_plugins.txt":
```
flake8-bugbear==18.8.0
flake8-builtins==1.4.1
flake8-comprehensions==1.4.1
flake8-tidy-imports==1.1.0
```
2. Make the file as cache key. Follow Github or GitLab CI/CD documentation about how to do that.
```yaml
  cache:
    - key:
        files:
          - requirements_flake8_plugins.txt
      paths:
        - .cache/pre_commit_cache/
```
3. Bump automatically Flake8 plugin pinned versions in the file. You may use "dependabot" or "renovatebot".
4. When the file will be changes, the cache will be invalidated.
