### ISSUE TITLE
On a Windows system, in either win7 or win2012R2, performing a pre-commit reports pip install  error

### ISSUE THREAD

**Issue by xiaohuazi123** [pre-commit/pre-commit#1407]
Hi All,
I have another problem, when I commit, the pre-commit prints out the error, this error seems not to be my own code problem, it seems to be a pre-commit problem

The problem environment
Windows 7
Python version: Python 3.7.6

Here's the detail log
```  
Linux Py2.7 ZeroMQ Requirements......................(no files to check)Skipped
Darwin Py2.7 ZeroMQ Requirements.....................(no files to check)Skipped
Windows Py2.7 ZeroMQ Requirements....................(no files to check)Skipped
Cloud Py2.7 Requirements.............................(no files to check)Skipped
Linux Py2.7 Crypto Requirements......................(no files to check)Skipped
Darwin Py2.7 Crypto Requirements.....................(no files to check)Skipped
Windows Py2.7 Crypto Requirements....................(no files to check)Skipped
Linux Py3.4 ZeroMQ Requirements......................(no files to check)Skipped
Cloud Py3.4 Requirements.............................(no files to check)Skipped
Linux Py3.4 Crypto Requirements......................(no files to check)Skipped
Linux Py3.5 ZeroMQ Requirements......................(no files to check)Skipped
Darwin Py3.5 ZeroMQ Requirements.....................(no files to check)Skipped
Windows Py3.5 ZeroMQ Requirements....................(no files to check)Skipped
Cloud Py3.5 Requirements.............................(no files to check)Skipped
Docs Py3.5 Requirements..............................(no files to check)Skipped
Linux Py3.5 Crypto Requirements......................(no files to check)Skipped
Darwin Py3.5 Crypto Requirements.....................(no files to check)Skipped
Windows Py3.5 Crypto Requirements....................(no files to check)Skipped
Lint Py3.5 Requirements..............................(no files to check)Skipped
Linux Py3.6 ZeroMQ Requirements......................(no files to check)Skipped
Darwin Py3.6 ZeroMQ Requirements.....................(no files to check)Skipped
Windows Py3.6 ZeroMQ Requirements....................(no files to check)Skipped
Cloud Py3.6 Requirements.............................(no files to check)Skipped
Docs Py3.6 Requirements..............................(no files to check)Skipped
Linux Py3.6 Crypto Requirements......................(no files to check)Skipped
Darwin Py3.6 Crypto Requirements.....................(no files to check)Skipped
Windows Py3.6 Crypto Requirements....................(no files to check)Skipped
Lint Py3.6 Requirements..............................(no files to check)Skipped
Linux Py3.7 ZeroMQ Requirements......................(no files to check)Skipped
Darwin Py3.7 ZeroMQ Requirements.....................(no files to check)Skipped
Windows Py3.7 ZeroMQ Requirements....................(no files to check)Skipped
Cloud Py3.7 Requirements.............................(no files to check)Skipped
Docs Py3.7 Requirements..............................(no files to check)Skipped
Linux Py3.7 Crypto Requirements......................(no files to check)Skipped
Darwin Py3.7 Crypto Requirements.....................(no files to check)Skipped
Windows Py3.7 Crypto Requirements....................(no files to check)Skipped
Lint Py3.7 Requirements..............................(no files to check)Skipped
Lint Salt................................................................Failed
- hook id: nox-py2
- exit code: 1

Running session lint-salt-pre-commit
Processing pkg\windows\req.txt
Processing requirements\static\windows.in
pip install --progress-bar=off -r requirements\base.txt --constraint requirements\static\py3.7\windows.txt --constraint requirements\static\py3.7\windows-crypto.txt
pip install --progress-bar=off -r requirements\zeromq.txt --constraint requirements\static\py3.7\windows.txt --constraint requirements\static\py3.7\windows-crypto.txt
pip install --progress-bar=off -r requirements\pytest.txt --constraint requirements\static\py3.7\windows.txt --constraint requirements\static\py3.7\windows-crypto.txt
pip install --progress-bar=off -r pkg\windows\req.txt --constraint requirements\static\py3.7\windows.txt --constraint requirements\static\py3.7\windows-crypto.txt
Command pip install --progress-bar=off -r pkg\windows\req.txt --constraint requirements\static\py3.7\windows.txt --constraint requirements\static\py3.7\windows-crypto.txt failed with exit code 1:
Ignoring backports-abc: markers 'python_version < "3.0"' don't match your environmentIgnoring enum34: markers 'python_version < "3.4"' don't match your environmentIgnoring futures: markers 'python_version < "3.0"' don't match your environmentIgnoring singledispatch: markers 'python_version < "3.4"' don't match your environmentLooking in indexes: http://pypi.douban.com/simpleCollecting backports.ssl-match-hostname==3.7.0.1  Downloading http://pypi.doubanio.com/packages/ff/2b/8265224812912bc5b7a607c44bf7b027554e1b9775e9ee0de8032e3de4b2/backports.ssl_match_hostname-3.7.0.1.tar.gz (5.7 kB)Requirement already satisfied: certifi==2019.3.9 in c:\users\administrator\.cache\pre-commit\repok6ii9wh0\py_env-python3\lib\site-packages (from -c requirements\static\py3.7\windows.txt (line 18)) (2019.3.9)Collecting cffi==1.12.2  Downloading http://pypi.doubanio.com/packages/18/dd/3936f31df9d4c6e07d7dbbee2bda3ebde49c20e0ff9364c753601cd4b4bd/cffi-1.12.2-cp37-cp37m-win_amd64.whl (170 kB)Collecting cherrypy==17.4.1  Downloading http://pypi.doubanio.com/packages/de/62/caa09bdd89ff16ef0c6caf9453ef45e28a4a0cb88739267fbb14a16336a8/CherryPy-17.4.1-py2.py3-none-any.whl (421 kB)Collecting contextlib2==0.5.5  Downloading http://pypi.doubanio.com/packages/a2/71/8273a7eeed0aff6a854237ab5453bc9aa67deb49df4832801c21f0ff3782/contextlib2-0.5.5-py2.py3-none-any.whl (8.1 kB)Collecting cryptography==2.6.1  Downloading http://pypi.doubanio.com/packages/00/39/088ba8da28dd77582219d4b77263d5aedac37c5c1c31f75859f241b9fcd2/cryptography-2.6.1-cp37-cp37m-win_amd64.whl (1.5 MB)Collecting gitpython==2.1.10  Downloading http://pypi.doubanio.com/packages/ac/c9/96d7c86c623cb065976e58c0f4898170507724d6b4be872891d763d686f4/GitPython-2.1.10-py2.py3-none-any.whl (449 kB)Requirement already satisfied: idna==2.8 in c:\users\administrator\.cache\pre-commit\repok6ii9wh0\py_env-python3\lib\site-packages (from -c requirements\static\py3.7\windows.txt (line 40)) (2.8)Collecting ioloop==0.1a0  Downloading http://pypi.doubanio.com/packages/96/ac/d55158ea1150d71bf3a6287c6d95fe4ee1cbeb9ea7143a1999b279b8da47/ioloop-0.1a.tar.gz (2.4 kB)Collecting ipaddress==1.0.22  Downloading http://pypi.doubanio.com/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl (18 kB)Requirement already satisfied: jinja2==2.10.1 in c:\users\administrator\.cache\pre-commit\repok6ii9wh0\py_env-python3\lib\site-packages (from -c requirements\static\py3.7\windows.txt (line 45)) (2.10.1)Collecting libnacl==1.6.1  Downloading http://pypi.doubanio.com/packages/60/55/0ce2a0b37264b8ec2be2765fdeefc5e7991b54f78bc9142120fa3f352782/libnacl-1.6.1-py2.py3-none-any.whl (14 kB)Collecting lxml==4.3.0  Downloading http://pypi.doubanio.com/packages/61/4d/d2ef69cff5e90e58d6b2a1c3b39e5034c86801e17858c491df7a9602e379/lxml-4.3.0-cp37-cp37m-win_amd64.whl (3.6 MB)Collecting mako==1.0.7  Downloading http://pypi.doubanio.com/packages/eb/f3/67579bb486517c0d49547f9697e36582cd19dafb5df9e687ed8e22de57fa/Mako-1.0.7.tar.gz (564 kB)Requirement already satisfied: markupsafe==1.1.1 in c:\users\administrator\.cache\pre-commit\repok6ii9wh0\py_env-python3\lib\site-packages (from -c requirements\static\py3.7\windows.txt (line 55)) (1.1.1)Requirement already satisfied: more-itertools==5.0.0 in c:\users\administrator\.cache\pre-commit\repok6ii9wh0\py_env-python3\lib\site-packages (from -c requirements\static\py3.7\windows.txt (line 57)) (5.0.0)Collecting msgpack-python==0.5.6  Downloading http://pypi.doubanio.com/packages/8a/20/6eca772d1a5830336f84aca1d8198e5a3f4715cd1c7fc36d3cc7f7185091/msgpack-python-0.5.6.tar.gz (138 kB)Collecting portend==2.4  Downloading http://pypi.doubanio.com/packages/54/18/d288ef3cfcaac40c9c3674d92ef8313bf137deeced810d60d9722c0a327a/portend-2.4-py2.py3-none-any.whl (5.0 kB)Requirement already satisfied: psutil==5.6.1 in c:\users\administrator\.cache\pre-commit\repok6ii9wh0\py_env-python3\lib\site-packages (from -c requirements\static\py3.7\windows.txt (line 66)) (5.6.1)Collecting pyasn1==0.4.5  Downloading http://pypi.doubanio.com/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl (73 kB)Collecting pycparser==2.19  Downloading http://pypi.doubanio.com/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158 kB)Requirement already satisfied: pycryptodomex==3.8.1 in c:\users\administrator\.cache\pre-commit\repok6ii9wh0\py_env-python3\lib\site-packages (from -c requirements\static\py3.7\windows.txt (line 73)) (3.8.1)Collecting pycurl==7.43.0.2  Downloading http://pypi.doubanio.com/packages/e8/e4/0dbb8735407189f00b33d84122b9be52c790c7c3b25286826f4e1bdb7bde/pycurl-7.43.0.2.tar.gz (214 kB)    ERROR: Command errored out with exit status 10:     command: 'C:\Users\Administrator\.cache\pre-commit\repok6ii9wh0\py_env-python3\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\pip-install-_8sdu0vq\\pycurl\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\pip-install-_8sdu0vq\\pycurl\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-install-_8sdu0vq\pycurl\pip-egg-info'         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-install-_8sdu0vq\pycurl\    Complete output (1 lines):    Please specify --curl-dir=/path/to/built/libcurl    ----------------------------------------ERROR: Command errored out with exit status 10: python setup.py egg_info Check the logs for full command output.Session lint-salt-pre-commit failed.

Lint Tests...........................................(no files to check)Skipped


```

**Comment by asottile** [comment]
nope, it's failing to isntall a package unrelated to pre-commit

like I said [here](https://github.com/pre-commit/pre-commit/issues/1400#issuecomment-615549612) if it's pre-commit crashing you'll see pre-commit's log file mentioned

reading that, it looks like it is failing to install pycurl -- you may want to try 7.43.0.2 which I believe is the last version supporting python 2

**Comment by xiaohuazi123** [comment]
Hey @asottile ,
This should be the PIP installation list provided by saltstack. There is something wrong with it. I will submit a bug report to their repository.


This is the contents of their <.pre-committ-config.yaml> file
I've already commented out the part of python 2.7.
.pre-commit-config.yaml
```  
exclude: ^(doc/_static/.*|doc/_themes/.*)$
repos:
  - repo: https://github.com/saltstack/pip-tools-compile-impersonate
    rev: master
    hooks:
      - id: pip-tools-compile
        alias: compile-linux-py2.7-zmq-requirements
        name: Linux Py2.7 ZeroMQ Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/linux\.in)$
        exclude: ^requirements/static/(lint|cloud|docs|darwin|windows)\.in$
        args:
          - -v
          - --py-version=2.7
          - --platform=linux
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt

      # - id: pip-tools-compile
      #   alias: compile-darwin-py2.7-zmq-requirements
      #   name: Darwin Py2.7 ZeroMQ Requirements
      #   files: ^(pkg/osx/(req|req_ext)\.txt|requirements/((base|zeromq|pytest)\.txt|static/darwin\.in))$
      #   args:
      #     - -v
      #     - --py-version=2.7
      #     - --platform=darwin
      #     - --include=pkg/osx/req.txt
      #     - --include=pkg/osx/req_ext.txt
      #     - --include=requirements/base.txt
      #     - --include=requirements/zeromq.txt
      #     - --include=requirements/pytest.txt
      #     - --passthrough-line-from-input=^pyobjc(.*)$

      # - id: pip-tools-compile
      #   alias: compile-windows-py2.7-zmq-requirements
      #   name: Windows Py2.7 ZeroMQ Requirements
      #   files: ^(pkg/windows/(req|req_win)\.txt|requirements/((base|zeromq|pytest)\.txt|static/windows\.in))$
      #   args:
      #     - -v
      #     - --py-version=2.7
      #     - --platform=windows
      #     - --include=pkg/windows/req.txt
      #     - --include=pkg/windows/req_win.txt
      #     - --include=requirements/base.txt
      #     - --include=requirements/zeromq.txt
      #     - --include=requirements/pytest.txt

      # - id: pip-tools-compile
      #   alias: compile-cloud-py2.7-requirements
      #   name: Cloud Py2.7 Requirements
      #   files: ^requirements/(static/cloud\.in)$
      #   args:
      #     - -v
      #     - --py-version=2.7

      # - id: pip-tools-compile
      #   alias: compile-linux-crypto-py2.7-requirements
      #   name: Linux Py2.7 Crypto Requirements
      #   files: ^requirements/(crypto\.txt|static/crypto\.in)$
      #   args:
      #     - -v
      #     - --py-version=2.7
      #     - --platform=linux
      #     - --out-prefix=linux

      # - id: pip-tools-compile
      #   alias: compile-darwin-crypto-py2.7-requirements
      #   name: Darwin Py2.7 Crypto Requirements
      #   files: ^requirements/(crypto\.txt|static/crypto\.in)$
      #   args:
      #     - -v
      #     - --py-version=2.7
      #     - --platform=darwin
      #     - --out-prefix=darwin

      # - id: pip-tools-compile
      #   alias: compile-windows-crypto-py2.7-requirements
      #   name: Windows Py2.7 Crypto Requirements
      #   files: ^requirements/(crypto\.txt|static/crypto\.in)$
      #   args:
      #     - -v
      #     - --py-version=2.7
      #     - --platform=windows
      #     - --out-prefix=windows


      - id: pip-tools-compile
        alias: compile-linux-py3.4-zmq-requirements
        name: Linux Py3.4 ZeroMQ Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/linux\.in)$
        exclude: ^requirements/static/(centos-6|amzn-2018\.03|lint|cloud|docs|darwin|windows)\.in$
        args:
          - -v
          - --py-version=3.4
          - --platform=linux
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt

      - id: pip-tools-compile
        alias: compile-cloud-py3.4-requirements
        name: Cloud Py3.4 Requirements
        files: ^requirements/(static/cloud\.in)$
        args:
          - -v
          - --py-version=3.4

      - id: pip-tools-compile
        alias: compile-linux-crypto-py3.4-requirements
        name: Linux Py3.4 Crypto Requirements
        files: ^requirements/(crypto\.txt|static/crypto\.in)$
        args:
          - -v
          - --py-version=3.4
          - --platform=linux
          - --out-prefix=linux


      - id: pip-tools-compile
        alias: compile-linux-py3.5-zmq-requirements
        name: Linux Py3.5 ZeroMQ Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/linux\.in)$
        exclude: ^requirements/static/(centos-6|amzn-2018\.03|lint|cloud|docs|darwin|windows)\.in$
        args:
          - -v
          - --py-version=3.5
          - --platform=linux
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt

      - id: pip-tools-compile
        alias: compile-darwin-py3.5-zmq-requirements
        name: Darwin Py3.5 ZeroMQ Requirements
        files: ^(pkg/osx/(req|req_ext)\.txt|requirements/((base|zeromq|pytest)\.txt|static/darwin\.in))$
        args:
          - -v
          - --py-version=3.5
          - --platform=darwin
          - --include=pkg/osx/req.txt
          - --include=pkg/osx/req_ext.txt
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt
          - --passthrough-line-from-input=^pyobjc(.*)$

      - id: pip-tools-compile
        alias: compile-windows-py3.5-zmq-requirements
        name: Windows Py3.5 ZeroMQ Requirements
        files: ^(pkg/windows/(req|req_win)\.txt|requirements/((base|zeromq|pytest)\.txt|static/windows\.in))$
        args:
          - -v
          - --py-version=3.5
          - --platform=windows
          - --include=pkg/windows/req.txt
          - --include=pkg/windows/req_win.txt
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt

      - id: pip-tools-compile
        alias: compile-cloud-py3.5-requirements
        name: Cloud Py3.5 Requirements
        files: ^requirements/(static/cloud\.in)$
        args:
          - -v
          - --py-version=3.5

      - id: pip-tools-compile
        alias: compile-doc-requirements
        name: Docs Py3.5 Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/docs\.in)$
        args:
          - -v
          - --py-version=3.5
          - --platform=linux

      - id: pip-tools-compile
        alias: compile-linux-crypto-py3.5-requirements
        name: Linux Py3.5 Crypto Requirements
        files: ^requirements/(crypto\.txt|static/crypto\.in)$
        args:
          - -v
          - --py-version=3.5
          - --platform=linux
          - --out-prefix=linux

      - id: pip-tools-compile
        alias: compile-darwin-crypto-py3.5-requirements
        name: Darwin Py3.5 Crypto Requirements
        files: ^requirements/(crypto\.txt|static/crypto\.in)$
        args:
          - -v
          - --py-version=3.5
          - --platform=darwin
          - --out-prefix=darwin

      - id: pip-tools-compile
        alias: compile-windows-crypto-py3.5-requirements
        name: Windows Py3.5 Crypto Requirements
        files: ^requirements/(crypto\.txt|static/crypto\.in)$
        args:
          - -v
          - --py-version=3.5
          - --platform=windows
          - --out-prefix=windows

      - id: pip-tools-compile
        alias: compile-lint-py3.5-requirements
        name: Lint Py3.5 Requirements
        files: ^requirements/static/lint\.in$
        args:
          - -v
          - --py-version=3.5
          - --platform=linux


      - id: pip-tools-compile
        alias: compile-linux-py3.6-zmq-requirements
        name: Linux Py3.6 ZeroMQ Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/linux\.in)$
        exclude: ^requirements/static/(centos-6|amzn-2018\.03|lint|cloud|docs|darwin|windows)\.in$
        args:
          - -v
          - --py-version=3.6
          - --platform=linux
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt

      - id: pip-tools-compile
        alias: compile-darwin-py3.6-zmq-requirements
        name: Darwin Py3.6 ZeroMQ Requirements
        files: ^(pkg/osx/(req|req_ext)\.txt|requirements/((base|zeromq|pytest)\.txt|static/darwin\.in))$
        args:
          - -v
          - --py-version=3.6
          - --platform=darwin
          - --include=pkg/osx/req.txt
          - --include=pkg/osx/req_ext.txt
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt
          - --passthrough-line-from-input=^pyobjc(.*)$

      - id: pip-tools-compile
        alias: compile-windows-py3.6-zmq-requirements
        name: Windows Py3.6 ZeroMQ Requirements
        files: ^(pkg/windows/(req|req_win)\.txt|requirements/((base|zeromq|pytest)\.txt|static/windows\.in))$
        args:
          - -v
          - --py-version=3.6
          - --platform=windows
          - --include=pkg/windows/req.txt
          - --include=pkg/windows/req_win.txt
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt

      - id: pip-tools-compile
        alias: compile-cloud-py3.6-requirements
        name: Cloud Py3.6 Requirements
        files: ^requirements/(static/cloud\.in)$
        args:
          - -v
          - --py-version=3.6

      - id: pip-tools-compile
        alias: compile-doc-requirements
        name: Docs Py3.6 Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/docs\.in)$
        args:
          - -v
          - --py-version=3.6
          - --platform=linux

      - id: pip-tools-compile
        alias: compile-linux-crypto-py3.6-requirements
        name: Linux Py3.6 Crypto Requirements
        files: ^requirements/(crypto\.txt|static/crypto\.in)$
        args:
          - -v
          - --py-version=3.6
          - --platform=linux
          - --out-prefix=linux

      - id: pip-tools-compile
        alias: compile-darwin-crypto-py3.6-requirements
        name: Darwin Py3.6 Crypto Requirements
        files: ^requirements/(crypto\.txt|static/crypto\.in)$
        args:
          - -v
          - --py-version=3.6
          - --platform=darwin
          - --out-prefix=darwin

      - id: pip-tools-compile
        alias: compile-windows-crypto-py3.6-requirements
        name: Windows Py3.6 Crypto Requirements
        files: ^requirements/(crypto\.txt|static/crypto\.in)$
        args:
          - -v
          - --py-version=3.6
          - --platform=windows
          - --out-prefix=windows

      - id: pip-tools-compile
        alias: compile-lint-py3.6-requirements
        name: Lint Py3.6 Requirements
        files: ^requirements/static/lint\.in$
        args:
          - -v
          - --py-version=3.6
          - --platform=linux


      - id: pip-tools-compile
        alias: compile-linux-py3.7-zmq-requirements
        name: Linux Py3.7 ZeroMQ Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/linux\.in)$
        exclude: ^requirements/static/(centos-6|amzn-2018\.03|lint|cloud|docs|darwin|windows)\.in$
        args:
          - -v
          - --py-version=3.7
          - --platform=linux
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt

      - id: pip-tools-compile
        alias: compile-darwin-py3.7-zmq-requirements
        name: Darwin Py3.7 ZeroMQ Requirements
        files: ^(pkg/osx/(req|req_ext)\.txt|requirements/((base|zeromq|pytest)\.txt|static/darwin\.in))$
        args:
          - -v
          - --py-version=3.7
          - --platform=darwin
          - --include=pkg/osx/req.txt
          - --include=pkg/osx/req_ext.txt
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt
          - --passthrough-line-from-input=^pyobjc(.*)$

      - id: pip-tools-compile
        alias: compile-windows-py3.7-zmq-requirements
        name: Windows Py3.7 ZeroMQ Requirements
        files: ^(pkg/windows/(req|req_win)\.txt|requirements/((base|zeromq|pytest)\.txt|static/windows\.in))$
        args:
          - -v
          - --py-version=3.7
          - --platform=windows
          - --include=pkg/windows/req.txt
          - --include=pkg/windows/req_win.txt
          - --include=requirements/base.txt
          - --include=requirements/zeromq.txt
          - --include=requirements/pytest.txt

      - id: pip-tools-compile
        alias: compile-cloud-py3.7-requirements
        name: Cloud Py3.7 Requirements
        files: ^requirements/(static/cloud\.in)$
        args:
          - -v
          - --py-version=3.7

      - id: pip-tools-compile
        alias: compile-doc-requirements
        name: Docs Py3.7 Requirements
        files: ^requirements/((base|zeromq|pytest)\.txt|static/docs\.in)$
        args:
          - -v
          - --py-version=3.7
          - --platform=linux

      - id: pip-tools-compile
        alias: compile-linux-crypto-py3.7-requirements
        name: Linux Py3.7 Crypto Requirements
        files: ^requirements/(crypto\.txt|static/crypto\.in)$
        args:
          - -v
          - --py-version=3.7
          - --platform=linux
          - --out-prefix=linux

      - id: pip-tools-compile
        alias: compile-darwin-crypto-py3.7-requirements
        name: Darwin Py3.7 Crypto Requirements
        files: ^requirements/(crypto\.txt|static/crypto\.in)$
        args:
          - -v
          - --py-version=3.7
          - --platform=darwin
          - --out-prefix=darwin

      - id: pip-tools-compile
        alias: compile-windows-crypto-py3.7-requirements
        name: Windows Py3.7 Crypto Requirements
        files: ^requirements/(crypto\.txt|static/crypto\.in)$
        args:
          - -v
          - --py-version=3.7
          - --platform=windows
          - --out-prefix=windows

      - id: pip-tools-compile
        alias: compile-lint-py3.7-requirements
        name: Lint Py3.7 Requirements
        files: ^requirements/static/lint\.in$
        args:
          - -v
          - --py-version=3.7
          - --platform=linux


  - repo: https://github.com/saltstack/salt-nox-pre-commit
    rev: master
    hooks:
      - id: nox-py2
        alias: lint-salt
        name: Lint Salt
        files: ^((setup|noxfile)|salt/.*)\.py$
        args:
          - -e
          - lint-salt-pre-commit
          - --

  - repo: https://github.com/saltstack/salt-nox-pre-commit
    rev: master
    hooks:
      - id: nox-py2
        alias: lint-tests
        name: Lint Tests
        files: ^tests/.*\.py$
        args:
          - -e
          - lint-tests-pre-commit
          - --


```
