### ISSUE TITLE
Generation requirements.txt by poetry

### ISSUE THREAD

**Issue by jarekkar** [pre-commit/pre-commit#1414]
I am trying to add hook which before commit would update my file `requirements.txt` according to changes in `pyproject.toml` and `poetry.lock` (I use `poetry` as a dependencies manager). I prepared file `.pre-commit-config.yaml`:
```
repos:
- repo: local
  hooks:
  - id: update-requirements-txt
    name: update-requirements-txt
    description: 'Generate requirements.txt based on poetry.lock'
    entry: poetry
    args: [export, --format, requirements.txt, --output, requirements.txt]
    language: system
    pass_filenames: false
``` 
Next I made a test:
1. Add new dependency to `pyproject.toml`
2. Invoke command `poetry update` - to modify file 'poetry.lock'
3. Invoke command `git add pyproject.toml poetry.lock`
4. Commit change

In the result files `pyproject.toml` and `poetry.lock` were committed, and file `requirements.txt` has not been changed.

Could you please help with this problem?
