### ISSUE TITLE
[Question] How can I have the config apply in a child directory, when commiting from a parent?

### ISSUE THREAD

**Issue by symonk** [pre-commit/pre-commit#1416]
we have something like this:

```
core_product:
    QA:
        auto_framework:
                      pre-commit-config.yaml
```

How, when commiting inside core_product can we have it use the `.pre-commit-config.yaml` from /QA/auto_framework/.pre-commit-config.yaml` ?

I tried doing pre-commit install --config `/QA/automation_framework/.pre-commit-config.yaml` but when commiting higher up, it states no `.pre-commit-config.yaml` found.

Is this possible? I set it all up using a virtualenv / makescript.  the install doesnt seem to honour the --config flag set, is there another way? (I dont want people to have to manually configure stuff after its been installed by me just to make it work)
