### ISSUE TITLE
No way to properly run hooks into subdirectory

### ISSUE THREAD

**Issue by mamyn0va** [pre-commit/pre-commit#1417]
Hi, I have a git repo with a `.pre-commit-config.yaml` at the root.
The Go code is under src with `go.mod` and `go.sum`.
I have no way to properly run hooks for Go files under src.
My workaround is to create a shell script for each Go hook at the root (e.g. `./go-unit-tests.sh`) and to change directory before running the cmd:

## go-unit-tests.sh

```shell
#!/usr/bin/env sh

cd src && go test ./...
```

And then set an entry for this hook in config file:

## .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.3.5
  hooks:
    - id: go-unit-tests
      name: Run Go tests (go test)
      entry: ./go-unit-tests.sh
```

This way, the hook is correctly ran but I was wondering if there is another clean way to achieve this?

**Comment by asottile** [comment]
nope, that's the current best solution -- there's additional threads on this here: https://github.com/pre-commit/pre-commit/issues?q=is%3Aissue+is%3Aclosed+monorepo

note that you don't actually need `dnephin/pre-commit-golang` (since your config isn't actually using any of it) there and can just use a `local` hook:

```yaml
-   repo: local
    hooks:
    -   id: go-unit-tests
        name: run go test s(go test)
        language: system
        entry: bash -c 'cd subdir && exec go test ./...'
        pass_filenames: false
        types: [go]
        files: ^subdir/
```

**Comment by mamyn0va** [comment]
Thanks for the inline solution with entry, it's much better.

**Comment by DanKaplanSES** [comment]
I'm a little confused by @asottile comment. If the `entry` is already running the correct command, isn't `pass_filenames`, `types`, and `files` redundant?

**Comment by sfc-gh-kbregula** [comment]
@asottile  using `bash -c trick "cd ..."` trick, unfortunately, causes the `pass_filename` option to not work properly.

For example, when we have the following configuration file:
```yaml
-   repo: local
    hooks:
    -   id: favorite-linter
        name: Favourite linter
        language: system
        entry: bash -c 'cd subdir && exec yarn favourite-linter'
        pass_filenames: true
        files: ^subdir/.+\.js$
```
This will execute the command:
```python
["bash -c 'cd subdir && exec favourite-linter'", "/subdir/src/index.js"]
```
Filenames will not be passed to the subprocess by the bash script.
In my case, I could still use the --cwd option for yarn to properly pass arguments to a subprocess.
```yaml
-   repo: local
    hooks:
    -   id: favorite-linter
        name: Favourite linter
        language: system
        entry: yarn --cwd subdir favourite-linter
        pass_filenames: true
        files: ^subdir/.+\.js$
```
Unfortunately, that causes another problem. The paths are created relative to the git toplevel directory, and the current working directory is set to `/subdir`, so pre-commit will execute the following command:
```python
["yarn", "--cwd", "subdir", "favourite-linter", "/subdir/src/index.js"]
```
but yarn will execute the command:
```
["favourite-linter", "/subdir/src/index.js"]
```
with the current working directory set to `/subdir/`, so `favourite-linter` will look for the `subdir/subdir/src/index.js` file.

As a workaround, I therefore wrote the `run_in_subdirectory.py` script which fix all the paths passed to it in arguments.

For the following config:
```yaml
-   repo: local
    hooks:
    -   id: favorite-linter
        name: Favourite linter
        language: system
        entry: ./scripts/run_in_subdirectory.py subdir/ favourite-linter
        pass_filenames: true
        files: ^subdir/.+\.js$
```
pre-commit will execute the command:
```
["./scripts/run_in_subdirectory.py", "subdir/" ,"favourite-linter", "/subdir/src/index.js"]
```
this script will execute the command:
```
["favourite-linter", "src/index.js"]
```
with the current working directory set to `/subdir/`.

Here is real-world usage: https://github.com/streamlit/streamlit/pull/5062/files
