### ISSUE TITLE
Running hooks on multiple language versions

### ISSUE THREAD

**Issue by cjolowicz** [pre-commit/pre-commit#1425]
In projects supporting multiple Python versions (or other language versions), what is the suggested way to run a hook on each of these versions? For example, flake8 will behave differently depending on which Python version it is run with.

Judging from the documentation and existing issues in this repository, it seems that you need to add a hook for each language version. If so, would it make sense to add a `language_versions` keyword accepting a list of versions? Would you be willing to accept a PR for this?

Thanks for the excellent tool!

**Comment by asottile** [comment]
hooks can be repeated, so a new setting is unnecessary:

```yaml
repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.0a2
    hooks:
    -   id: flake8
        alias: flake8-py2
        name: flake8 (py2)
        language_version: python2
    -   id: flake8
        alias: flake8-py3
        name: flake8 (py3)
        language_version: python3
```

(`language_versions` also wouldn't be very helpful / used since you almost always want to set `name`+`alias` when duping hooks)
