### ISSUE TITLE
I _think_ pre-commit ignores scoped package registries in npmrc

### ISSUE THREAD

**Issue by sysadmiral** [pre-commit/pre-commit#1452]
Hi,

Firstly - great tool! It has become indispensable in my development routine and I champion it whenever I can! :heart: 

My issue is npm related so I will be using a lot of npm terminology. I have an issue where I am using a hook that requires the fetching of another npm module but it seems to fail to pull the package.

More detail:
My `npmrc` is set to use public registry for most things and for our orgs scoped packages use our private registry.

My `npmrc` looks like this (with placeholders for secrets):

```
registry=https://registry.npmjs.org
@${myscope}:registry=https://${myprivateregistry}
//${myprivateregistry}/:_authtoken=foo
```

In pre-commit I am using the hook `https://github.com/alessandrojcm/commitlint-pre-commit-hook` which you can extend with "shared configuration":

```
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.2
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
```

I've forked the `@commitlint/config-conventional` configuration and created an org specific package which is published to our private registry.

If I set the hook to use our configuration (scoped package) the package is never installed and the hook subsequently fails.

I think the mechanism for `additional_dependencies` is ignoring the scoped private registry in `npmrc`.
