### ISSUE TITLE
Entry points for different OS

### ISSUE THREAD

**Issue by Cielquan** [pre-commit/pre-commit#1455]
In #1309 I shared a config:
```
repos:
...
  - repo: local
    hooks:
      - id: pylint
        args: [--ignore=version.py]
        name: pylint
        entry: .tox/pre-commit/bin/pylint
        language: system
        types: [python]
...
```

The Config works fine on my linux machine but on windows the `entry` is a problem and I need to change it to `.tox/pre-commit/Scripts/pylint.exe`. So I need to change `bin`to `Scripts` and append `.exe`. 

Is there a way to use the same config for both OS without the need to change it every time I change the machine? Like: 
```
repos:
...
  - repo: local
    hooks:
      - id: pylint
        args: [--ignore=version.py]
        name: pylint
        entry-win: .tox/pre-commit/Scripts/pylint.exe
        entry-linux: .tox/pre-commit/bin/pylint
        language: system
        types: [python]
...
```

If not I would like to propose it as a feature request. :)

**Comment by asottile** [comment]
using `repo: local` and especially `language: system` is all-bets-off at-your-own-support territory as these are both escape hatches from the normal golden-path way to accomplish things in the framework

that said, it's easy for you to accomplish this without needing special features from pre-commit by writing a small script to do your platform-specific logic:

```yaml
-   id: pylint
    entry: ./.pre-commit-scripts/run-pylint
    ...
```

```python
#!/usr/bin/env python3
import subprocess
import sys

def main():
    if sys.platform == 'win32':
        cmd = (r'.tox\pre-commit\Scripts\pylint.exe', *sys.argv[1:])
    else:
        cmd = ('.tox/pre-commit/bin/pylint', *sys.argv[1:])
    return subprocess.call(cmd)

if __name__ == '__main__':
    exit(main())
```

**Comment by Cielquan** [comment]
It would have reduced the amount of additional files but I understand what you are saying.

I did not think that far. Thanks for the idea and snippet though. :)

**Comment by Cielquan** [comment]
I use `tox` to mange almost all the stuff. For usage of `pre-commit` I run `tox -e pre-commit` which creates an venv with the needed dependencies etc. and runs `pre-commit`.

So I came up with another solution:
`tox` has a `platform` config parameter which you can utilize to have platform specific behavior. So `pre-commit` calls a special `tox` venv, which itself calls then `pylint` with the appropriate executable.

`.pre-commit-config.yaml`:
```
repos:
...
  - repo: local
    hooks:
      - id: pylint
        args: [--ignore=version.py]
        name: pylint
        entry: tox -e pylint-win,pylint-nix --
        language: system
        types: [python]
...
```

`tox.ini`:
```
...
[testenv:pylint]
platform =
    nix: linux|darwin
    win: win32
commands =
    nix: .tox/pre-commit/bin/pylint
    win: .tox/pre-commit/Scripts/pylint.exe
...
```

I think there are more elegant ways to do this, but this works for me without additional files.
