### ISSUE TITLE
pre-commit repeatedly installs environments when nothing has changed

### ISSUE THREAD

**Issue by zaneselvans** [pre-commit/pre-commit#1458]
For some reason,`pre-commit` has recently started re-installing environments for all of the hooks every time it runs. I have tried updating all the hooks, as well as running `pre-commit uninstall` followed by `pre-commit install --install-hooks` to re-set the environment, but it continues with the same behavior or installing all of the environments with every commit. There are no errors, and it says it's going to save and re-use the installed environment, but it never does.  The following output now precedes any commit:

```sh
$ pre-commit run --all-files
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-autopep8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/doc8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/bandit.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
```

I've looked in the `.git/hooks/` directory and the pre-commit script is there. And when I run `pre-commit uninstall` it disappears as expected, and is replaced when I re-install.  Is there something else I can clear out? Are there known reasons why the environments might not be getting saved? I've searched around a bit but have not found any references to this problem.

I'm running pre-commit v2.4.0 on Ubuntu 20.04. The repository contains mostly python files.  The contents of my `.pre-commit-config.yaml` file is:

```yaml
repos:

# Quick content checks based on grepping for python specific patterns:
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.5.1
  hooks:
  - id: python-check-blanket-noqa   # Prohibit overly broad QA exclusions.
  - id: python-no-eval              # Never use eval() it's dangerous.
  - id: python-no-log-warn          # logger.warning(), not old .warn()

# Other file formatting, plus common Git mistakes & text file standardization:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.0.0
  hooks:
  - id: check-added-large-files # Don't accidentally commit giant files.
  - id: check-merge-conflict    # Watch for lingering merge markers.
  - id: check-yaml              # Validate all YAML files.
  - id: check-case-conflict     # Avoid case sensitivity in file names.
  - id: debug-statements        # Watch for lingering debugger calls.
  - id: end-of-file-fixer       # Ensure there's a newline at EOF.
  - id: mixed-line-ending       # Only newlines, no line-feeds.
  - id: trailing-whitespace     # Remove trailing whitespace.
  - id: name-tests-test         # Follow PyTest naming convention.

# Attempt to enforce standardized PEP8 style formatting:
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5.2
  hooks:
  - id: autopep8

# Make sure import statements are sorted uniformly.
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
  - id: isort

# Check for PEP8 non-compliance, code complexity, and syntax errors:
# Make sure the following plugins are installed as well:
# - flake8-docstrings
# - flake8-builtins
# - pep8-naming
- repo: https://github.com/PyCQA/flake8
  rev: 3.8.1
  hooks:
  - id: flake8
    args: [--format, "%(path)40s:%(row)-4d %(code)s %(text)s"]

# Check for errors in restructuredtext (.rst) files under the doc hierarchy
- repo: https://github.com/PyCQA/doc8
  rev: 0.8.1rc3
  hooks:
  - id: doc8
    args: [--ignore-path, docs/_build]

# Check for known security vulnerabilities:
- repo: https://github.com/PyCQA/bandit
  rev: 1.6.2
  hooks:
  - id: bandit
    args: [-c, .bandit.yml]
```

**Comment by erikr** [comment]
Thank you for posting this issue. I have had the same problem, on the same version of `pre-commit` and Ubuntu as you.

**Comment by asottile** [comment]
I changed the recreation logic in 2.4.0 so it's probably related to that

could you provide the following for me?

```bash
/usr/bin/python3 --version --version
head -1 $(which pre-commit)
$(head -1 $(which pre-commit)) --version --version
$(head -1 $(which pre-commit)) -m virtualenv testvenv && cat testvenv/pyvenv.cfg
```

**Comment by asottile** [comment]
and `$(head -1 $(which pre-comit)) -m pip freeze --all` for good measure

**Comment by zaneselvans** [comment]
```
$ /usr/bin/python3 --version --version
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0]
```

```
$ head -1 $(which pre-commit)
#!/home/zane/miniconda3/envs/pudl-dev/bin/python
```

```
$ /home/zane/miniconda3/envs/pudl-dev/bin/python --version --version
Python 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 08:20:52) 
[GCC 7.3.0]
```

```
$ /home/zane/miniconda3/envs/pudl-dev/bin/python -m virtualenv testvenv && cat testvenv/pyvenv.cfg
Using base prefix '/home/zane/miniconda3/envs/pudl-dev'
New python executable in /home/zane/code/catalyst/pudl/testvenv/bin/python
copying /home/zane/miniconda3/envs/pudl-dev/bin/python => /home/zane/code/catalyst/pudl/testvenv/bin/python
Installing setuptools, pip, wheel...
done.
cat: testvenv/pyvenv.cfg: No such file or directory
```

```
$ /home/zane/miniconda3/envs/pudl-dev/bin/python -m pip freeze --all
addfips==0.2.2
alabaster==0.7.12
attrs==19.3.0
autopep8==1.5.2
Babel==2.8.0
backcall==0.1.0
bandit==1.6.2
bitarray==1.2.1
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1588608214987/work
bokeh==2.0.1
boto3 @ file:///home/conda/feedstock_root/build_artifacts/boto3_1589321512408/work
botocore @ file:///home/conda/feedstock_root/build_artifacts/botocore_1589319487521/work
brotlipy==0.7.0
-e git+git@github.com:catalyst-cooperative/pudl.git@cb8d429c0fb334962ccf6d945138b2a239fa6a1c#egg=catalystcoop.pudl
cchardet==2.1.6
certifi==2020.4.5.1
cffi==1.14.0
cfgv==3.1.0
chardet==3.0.4
click==7.1.2
click-default-group==1.2.1
click-plugins==1.1.1
cligj==0.5.0
cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1588164361239/work
cmarkgfm==0.4.2
colorama==0.4.3
coloredlogs==14.0
coverage==5.1
cryptography==2.9.2
cycler==0.10.0
cytoolz==0.10.1
dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1588975274559/work
datapackage==1.12.2
dbfread==2.0.7
decorator==4.4.2
defusedxml==0.6.0
Deprecated @ file:///home/conda/feedstock_root/build_artifacts/deprecated_1589409885623/work
descartes==1.1.0
distributed @ file:///home/conda/feedstock_root/build_artifacts/distributed_1588976146330/work
doc8==0.8.0
docutils==0.15.2
editdistance==0.5.3
entrypoints==0.3
et-xmlfile==1.0.1
fancycompleter==0.8
filelock==3.0.10
Fiona==1.8.13
flake8 @ file:///home/conda/feedstock_root/build_artifacts/flake8_1589343427411/work
flake8-builtins==1.5.2
flake8-colors==0.1.6
flake8-docstrings==1.5.0
flake8-polyfill==1.0.2
fsspec==0.7.3
future==0.18.2
GDAL==3.0.4
geopandas==0.7.0
gitdb @ file:///home/conda/feedstock_root/build_artifacts/gitdb_1588651542737/work
GitPython @ file:///home/conda/feedstock_root/build_artifacts/gitpython_1588692249495/work
goodtables==2.4.2
HeapDict==1.0.1
humanfriendly==8.2
identify @ file:///home/conda/feedstock_root/build_artifacts/identify_1588285327745/work
idna==2.9
ijson @ file:///home/conda/feedstock_root/build_artifacts/ijson_1589189584509/work
imagesize==1.2.0
importlib-metadata==1.6.0
importlib-resources==1.5.0
ipdb==0.12.3
ipykernel==5.2.1
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1588362967447/work
ipython-genutils==0.2.0
ipywidgets==7.5.1
isodate==0.6.0
isort==4.3.21
jdcal==1.4.1
jedi==0.17.0
jeepney==0.4.3
Jinja2==2.11.2
jmespath @ file:///home/conda/feedstock_root/build_artifacts/jmespath_1589369830981/work
joblib==0.14.1
json5==0.9.0
jsonlines==1.2.0
jsonpointer==2.0
jsonschema==3.2.0
jupyter-client==6.1.3
jupyter-console==6.1.0
jupyter-core==4.6.3
jupyterlab==2.1.2
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1588946599005/work
keyring @ file:///home/conda/feedstock_root/build_artifacts/keyring_1588433932455/work
kiwisolver==1.2.0
linear-tsv==1.1.0
llvmlite==0.31.0
locket==0.2.0
lxml==4.5.0
MarkupSafe==1.1.1
matplotlib==3.2.1
mccabe==0.6.1
mistune==0.8.4
more-itertools==8.2.0
msgpack==1.0.0
munch==2.5.0
nbconvert==5.6.1
nbdime @ file:///home/conda/feedstock_root/build_artifacts/nbdime_1588773248389/work
nbformat==5.0.6
nbval==0.9.5
networkx==2.4
nodeenv==1.3.5
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1588887220875/work
numba==0.48.0
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1588605082776/work
olefile==0.46
openpyxl==3.0.3
packaging==20.1
palettable==3.3.0
pandas==1.0.3
pandocfilters==1.4.2
parso==0.7.0
partd==1.1.0
patsy==0.5.1
pbr==5.4.2
pdbpp==0.10.0
pep8-naming==0.10.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.1.2
pip==20.1
pkginfo==1.5.0.1
pluggy @ file:///home/conda/feedstock_root/build_artifacts/pluggy_1588623599192/work
pre-commit @ file:///home/conda/feedstock_root/build_artifacts/pre-commit_1589330149804/work
prometheus-client==0.7.1
prompt-toolkit==3.0.5
psutil==5.7.0
ptyprocess==0.6.0
py==1.8.1
pyarrow==0.17.0
pybloom-live==3.0.0
pycodestyle @ file:///home/conda/feedstock_root/build_artifacts/pycodestyle_1589305246696/work
pycparser==2.20
pydocstyle==5.0.2
pyflakes==2.2.0
Pygments==2.6.1
pyOpenSSL==19.1.0
pyparsing==2.4.7
pyproj @ file:///home/conda/feedstock_root/build_artifacts/pyproj_1588596072923/work
PyQt5==5.12.3
PyQt5-sip==4.19.18
PyQtChart==5.12
PyQtWebEngine==5.12.1
pyrsistent==0.16.0
pysal==2.1.0
PySocks==1.7.1
pytest==5.4.2
pytest-cov==2.8.1
python-dateutil==2.8.1
python-snappy==0.5.4
pytz==2020.1
PyYAML==5.3.1
pyzmq==19.0.1
qtconsole @ file:///home/conda/feedstock_root/build_artifacts/qtconsole_1589392299544/work
QtPy==1.9.0
readme-renderer==24.0
requests==2.23.0
requests-toolbelt==0.9.1
restructuredtext-lint==1.3.0
rfc3986==1.3.2
Rtree==0.9.4
s3transfer==0.3.3
scikit-learn @ file:///home/conda/feedstock_root/build_artifacts/scikit-learn_1589375559000/work
scipy==1.4.1
seaborn==0.10.1
SecretStorage==3.1.2
Send2Trash==1.5.0
setuptools==46.3.0.post20200513
setuptools-scm==3.5.0
Shapely==1.7.0
simpleeval==0.9.10
six==1.14.0
smmap @ file:///home/conda/feedstock_root/build_artifacts/smmap_1588651577140/work
snowballstemmer==2.0.0
sortedcontainers==2.1.0
Sphinx==2.4.4
sphinx-issues==1.2.0
sphinx-rtd-theme==0.4.3
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
SQLAlchemy @ file:///home/conda/feedstock_root/build_artifacts/sqlalchemy_1589421757847/work
statistics==1.0.3.5
statsmodels==0.11.1
stevedore==1.30.1
tableschema @ file:///home/conda/feedstock_root/build_artifacts/tableschema_1588161682277/work
tableschema-sql==1.3.1
tabulator @ file:///home/conda/feedstock_root/build_artifacts/tabulator_1589356761331/work
tblib==1.6.0
terminado==0.8.3
testpath==0.4.4
threadpoolctl==2.0.0
timezonefinder @ file:///home/conda/feedstock_root/build_artifacts/timezonefinder_1589458417234/work
toml==0.10.0
toolz==0.10.0
tornado==6.0.4
tox @ file:///home/conda/feedstock_root/build_artifacts/tox_1588454137929/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1588513834538/work
traitlets==4.3.3
twine==3.1.1
typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1588470653596/work
unicodecsv==0.14.1
urllib3==1.25.9
virtualenv==16.7.5
wcwidth==0.1.9
webencodings==0.5.1
wheel==0.34.2
widgetsnbextension==3.5.1
wmctrl==0.3
wrapt==1.12.1
xlrd==1.2.0
XlsxWriter==1.2.8
zict==2.0.0
zipp==3.1.0
```

**Comment by sappjw** [comment]
When I revert to 2.3.0 (no other environment changes) this problem disappears.

**Comment by asottile** [comment]
you're installing incompatible dependencies.  pre-commit 2.4 requires virtualenv>=20

**Comment by asottile** [comment]
looks like the conda forge package screwed up the latest release: https://github.com/conda-forge/pre-commit-feedstock/pull/20

**Comment by nicoddemus** [comment]
The fixed package should be available in the next hour or so. 🎉 

Thanks to everyone who helped!

I think this can be closed now.

**Comment by asottile** [comment]
sweet!  thanks again for doing the grunt work on this one @nicoddemus <3

**Comment by nicoddemus** [comment]
Sure, my pleasure. 👍

**Comment by MartinVedani** [comment]
Good day @asottile / @nicoddemus, I am currently having this same issue when trying to use pre-commit and ansible-lint hooks (it tries to install ALL of ansible in a venv).

When I add "additional_dependencies" to my current .pre-commit-config.yaml like this:

```
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v5.3.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        types: [file]
        additional_dependencies: ['ansible-base:2.10.17']
```
I am getting this error:

```
 $ git commit -m 'lint test 2' .pre-commit-config.yaml
[INFO] Installing environment for https://github.com/ansible-community/ansible-lint.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/martin.vedani/.cache/pre-commit/repow8vq8qf0/py_env-python3/bin/python', '-mpip', 'install', '.', 'ansible-base:2.10.17')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    ERROR: Invalid requirement: 'ansible-base:2.10.17'
```

Should I install conda-forge or change any of the versions used below? I am tied to ansible-base 2.10.17

```
$ pip show pre-commit
Name: pre-commit
Version: 2.18.1
Summary: A framework for managing and maintaining multi-language pre-commit hooks.
Home-page: https://github.com/pre-commit/pre-commit
Author: Anthony Sottile
Author-email: asottile@umich.edu
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
```

```
$ pip show virtualenv
Name: virtualenv
Version: 20.14.1
Summary: Virtual Python Environment builder
Home-page: https://virtualenv.pypa.io/
Author: Bernat Gabor
Author-email: gaborjbernat@gmail.com
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
```

```
$ pip show ansible-base
Name: ansible-base
Version: 2.10.17
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /usr/local/lib/python3.8/dist-packages
```

```
$ pip show ansible-lint
Name: ansible-lint
Version: 5.3.2
Summary: Checks playbooks for practices and behaviour that could potentially be improved
Home-page: https://github.com/ansible-community/ansible-lint
Author: Will Thames
Author-email: will@thames.id.au
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
```

```
$ /usr/bin/python3 --version --version
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]
```

```
$ head -1 $(which pre-commit)
#!/usr/bin/python3
```
