### ISSUE TITLE
allow declaring local hooks with less repetition

### ISSUE THREAD

**Issue by mvdan** [pre-commit/pre-commit#1460]
First of all, thanks for working on open source :)

A few people have been asking that I add a `.pre-commit-hooks.yaml` file to one of my repos, but in the interest of not adding more top-level "dot files", I ended up just adding a short section to the README, like one might do for Docker or other ways to run a tool: https://github.com/mvdan/sh#pre-commit

This works well, because the YAML is really just a few lines. However, I was thinking that pre-commit could go a bit further and allow declaring only the bare minimum in one's YAML. Below is what is currently in the README:

```
  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        minimum_pre_commit_version: 2.4.0
        language: golang
        additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.1.1]
        entry: shfmt
        args: [-w]
        types: [shell]
```

Ideally, I think this should be enough:

```
  - repo: local
    hooks:
      - id: shfmt
        language: golang
        additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.1.1]
        args: [-w]
        types: [shell]
```

Here's my reasoning:

1) `name` could default to `id` when not defined

2) `entry` seems redundant; from `language: golang` and `additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.1.1]`, we could infer that we're running `shfmt`. That is, when `additional_dependencies` is just one Go main package. Alternatively, we could fall back to `id` when not defined.

3) I assume `minimum_pre_commit_version` could be ommitted after some time, perhaps a year after these changes have been released in a stable version. Or I could just rely on the user to define it at the top level, instead of for each hook separately.
