### ISSUE TITLE
Local hooks are executed multiple times per run

### ISSUE THREAD

**Issue by Cielquan** [pre-commit/pre-commit#1466]
EDIT: 
After further investigation I think its a `mypy` issue after all? I will open another issue at mypy.

-----

As follow-up to #1455 I use a caller script to call `mypy` and  `pylint` from the `pre-commit` hook.

While looking into a topic I have with `mypy` I found out that both `mypy` and `pylint` are actually called twice by `pre-commit`.

When I run `pre-commit run --all-files` or let it be called by `tox` (makes no difference) both entry points in the `local` `repo` are called twice.

I found this out by adding this snippet
```python
    with open("testfile", "a") as f:
        f.write(sys.executable)
        f.write("\n" + str(sys.argv[:]) + "\n\n\n")
```
to the top of the `main()` function in my caller script.

The result is here:

```
/home/krys/Python_Projects/.testing/python_test/.tox/dev/bin/python3
['./.pre_commit_tool_runner', 'pylint', 'pre-commit,dev', '.pre_commit_tool_runner', 'tests/test_python_test.py']


/home/krys/Python_Projects/.testing/python_test/.tox/dev/bin/python3
['./.pre_commit_tool_runner', 'pylint', 'pre-commit,dev', 'src/python_test/python_tester.py', 'docs/source/conf.py', 'src/python_test/__init__.py', 'tests/conftest.py']


/home/krys/Python_Projects/.testing/python_test/.tox/dev/bin/python3
['./.pre_commit_tool_runner', 'mypy', 'pre-commit,dev', '--warn-unused-ignores', 'src/python_test/python_tester.py', 'docs/source/conf.py', 'src/python_test/__init__.py', 'tests/conftest.py']


/home/krys/Python_Projects/.testing/python_test/.tox/dev/bin/python3
['./.pre_commit_tool_runner', 'mypy', 'pre-commit,dev', '--warn-unused-ignores', '.pre_commit_tool_runner', 'tests/test_python_test.py']
```

If you repeat the test, the arguments for the separate calls do **not** change. Even the order stays.

- Is this behavior intended? 
- If yes, can one deactivate it?

This behavior hurts `mypy`  by a great margin. If I call `.tox/pre-commit/bin/mypy tests/ src/python_test/` my result is a *success* but if i call `.tox/pre-commit/bin/mypy tests/` the result is an *error* because `python_test` is imported in the tests and is not available. The same is happening when the call is split like one can see above.

Below you can find the configs:

-----

`.pre_commit_tool_runner` :
```python
#!/usr/bin/env python3
"""Script to call executables in `tox` envs

The script takes two mandatory arguments:
1. the executable to call like e.g. `pylint`
2. a string with comma separated `tox` envs to check for the executable

All other arguments after are passed to the tool on call.

The script considers OS and calls the tool accordingly.
"""
import subprocess
import sys

from pathlib import Path


def main():
    """Call given `tool` form given `tox` env"""
    tool = sys.argv[1]

    if sys.platform == "win32":
        exe = Path("Scripts/" + tool + ".exe")
    else:
        exe = Path("bin/" + tool)

    tox = Path(".tox")
    envs = sys.argv[2].split(",")

    cmd = None
    for env in envs:
        path = Path(tox / env / exe)
        if path.is_file():
            cmd = (str(path), *sys.argv[3:])

    if cmd is None:
        print(
            "No '{}' executable found. Make sure one of the "
            "following `tox` envs is accessible: {}".format(tool, envs)
        )
        return 1

    return subprocess.call(cmd)


if __name__ == "__main__":
    sys.exit(main())
```

`.pre-commit-config.yaml`:
```yaml
minimum_pre_commit_version: "1.15"
default_stages: [commit, push]

repos:
...
  #: Hooks managed via tox `pre-commit` venv
  - repo: local
    hooks:
      #: pylint - python linter
      - id: pylint
        name: pylint
        entry: ./.pre_commit_tool_runner pylint pre-commit,dev
        language: system
        types: [python]
      #: mypy - python type checker
      - id: mypy
        args: ["--warn-unused-ignores"]
        name: mypy
        entry: ./.pre_commit_tool_runner mypy pre-commit,dev
        language: system
        types: [python]
...
```

`tox.ini`:
```ini
...
[testenv:pre-commit]
description = format and check the code
passenv =
    SSH_AUTH_SOCK
extras =
    pre-commit
    testing
    docs
ignore_errors = True
commands =
    pre-commit run --all-files --show-diff-on-failure
    python -c 'import pathlib;print("HINT: run \"\{\} install\" to add checks as pre-commit hook".format(pathlib.Path(r"{envdir}")/"bin"/"pre-commit"))'
...
```

`Project structure`:
- python_test
  - src
    - python_test
      - __ init __.py
      - python_tester.py
      - py.typed
  - tests
    - test_python_tester.py
  - docs
    - source
      - conf.py
  - .pre-commit-config.yaml
  - .pre_commit_tool_runner
  - pyproject.toml
  - tox.ini
