### ISSUE TITLE
Segfaults and deleting/reseting unstaged changes

### ISSUE THREAD

**Issue by Liamdoult** [pre-commit/pre-commit#1469]
Hi,

I have had crazy bug with `pre-commit`. It may not be a `pre-commit` bug but rather a `pre-commit-hooks` issue. But either way, I would appreciate support with resolving this issue.

__Context__
Before I explain the issue, I would like to provide some context. 

pre-commit 2.4.0
Python 3.7.3

Here is my `.pre-commit-config.yaml` file:
``` yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.30.0'
    hooks:
    -   id: yapf

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        exclude: test/|setup.py
```

We are using `yapf` for formatting, `pylint` for symantics and the usual `pre-commit-hooks`. This has been working well for us for a few months now. We had not updated or changed configs for this project.

__Issue__
I have been receiving segmentation faults when attempting to run pre-commit. This applies to both manual run and as a git hook:

![image](https://user-images.githubusercontent.com/12427907/82879516-f245d500-9f34-11ea-998a-ee5f1fd4b1ad.png)

This has also resulted in tracked unstaged changes to either be reset or deleted:

![image](https://user-images.githubusercontent.com/12427907/82880129-e1e22a00-9f35-11ea-8164-f3ba6c1ab4eb.png)

__Attempts__
In an attempt to resolve this I have tried:
- Updating/Reinstalling pre-commit
- Updating tasks
- Resetting the hook

__Steps to reproduce___
I have note yet been able to figure out where things went wrong, so it is hard to replicate.

Could you guide me on where I can collect more information on this issue for you?
