### ISSUE TITLE
Cannot run --files on Windows

### ISSUE THREAD

**Issue by harrybiddle** [pre-commit/pre-commit#1476]
(pre-commit version 2.4.0) We're running in to an odd issue on Windows

```
$ pre-commit run --files my_file.py
black................................................(no files to check)Skipped
```

However, running `pre-commit run --all-files` _will_ correctly format the file. Equally, running `pre-commit run --files my_file.py` in the same repository on a Mac works fine.

It's like the file is somehow not being read in Windows... Has anybody else encountered this?

**Comment by asottile** [comment]
please share your configuration -- I suspect you've got an `exclude:` or `types:` which is causing that file to be skipped

**Comment by harrybiddle** [comment]
Hey @asottile ,

Here are the configuration files. The file we were trying to format was `./trase/supplychain/test/test_supplychain.py`.

However, I thought that we had ruled out this being a configuration issue, for two reasons:

1. Running `pre-commit run --all-files` _does_ format the file, so it must be correct in the configuration
2. Running the same command on a Mac works

Thank you for any help!
 - .pre-commit-config.yaml:

    ```yaml
    exclude: '^(?!trase/).*$'
    repos:
    -   repo: https://github.com/ambv/black
        rev: 19.10b0
        hooks:
        - id: black
          language_version: python3.6
    -   repo: https://github.com/timothycrosley/isort
        rev: 4.3.21
        hooks:
        -   id: isort
    ```

 - .gitignore:

    ```
    __pycache__/
    .ipynb_checkpoints/
    .vscode/
    .venv/
    ORI/
    IN/
    PRE/
    OUT/
    POST/
    *.pyc
    *.mps
    *.lp
    *.txt
    .DS_Store
    poetry.toml
    .pytest_cache
    Tutorial_1/
    Tutorial_2/
    Tutorial_3/
    result.log
    main.py
    **/*.idea*
    .idea/*
    **/*~
    **/*#
    **/.#*
    ```
