### ISSUE TITLE
Tests not passing in pre-commit

### ISSUE THREAD

**Issue by MatteoGioioso** [pre-commit/pre-commit#1478]
So, my tests are passing, but when I run the pre-commit they fail, like if they are a version behind or cached. I have read somewhere that pre-commit is run against only staged files and therefore that would make sense to fail. However I just want to run my tests as they are at the moment of the pre-commit.
I read somewhere that you might want to pass `--all-files` to `pre-commit run`, but not really sure on how to run those in the pre-commit.yaml

This is my pre-commit config:

```yaml
repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.3.5
    hooks:
      - id: go-fmt
      - id: go-imports
  - repo: local # this one fails
    hooks:
      - id: test
        name: test
        language: golang
        entry: make test
        verbose: true
        always_run: true

```

this is the make command:

```
test:
	GO_ENV=testing go test ./...
```

`pre-commit version: 2.4.0`
