### ISSUE TITLE
Allow running local hooks defined in `.pre-commit-hooks.yaml`

### ISSUE THREAD

**Issue by FFY00** [pre-commit/pre-commit#1481]
What I would like to do is very simple:

`.pre-commit-hooks.yaml`
```yaml
- id: custom
  name: custom
  entry: custom
  language: python
  types: [python]
```

`.pre-commit-config.yaml`
```yaml
repos:
  - repo: local
    hooks:
      - id: custom
      - id: custom
        args: ['something']
      - id: custom
        args: ['something-else']
```

**Comment by asottile** [comment]
I believe you're looking for [`pre-commit try-repo`](https://pre-commit.com/#developing-hooks-interactively)

there will not be inclusion implemented (there's no point to it)

**Comment by FFY00** [comment]
I don't want `try-repo`, if I understand correcty. I want to declare and use hooks in my repo. I want them to be run on `git commit`. Am I missing anything obvious here?

**Comment by asottile** [comment]
yes, `repo: local` is for "configuration-only" hooks.  the normal inclusion method is for remote repositories.  the cache invalidation problem would be intractable for what you're suggesting (and unnecessary, just use `repo: local`)

**Comment by FFY00** [comment]
I'm sorry, I still don't get it.

I am able to write the hooks as:
```yaml
repos:
  - repo: local
    hooks:
      - id: custom
        name: custom
        entry: custom
        language: python
        types: [python]
      - id: custom
        name: custom
        entry: custom
        language: python
        types: [python]
        args: ['something']
      - id: custom
        name: custom
        entry: custom
        language: python
        types: [python]
        args: ['something-else']
```

But that is very annoying, especially when you have multiple hooks.

If I simplify them as in the original example I get the following:
```
An error has occurred: InvalidConfigError:
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='local')
==> At key: hooks
==> At Hook(id='custom')
=====> Missing required key: name
```

> yes, `repo: local` is for "configuration-only" hooks.

Sorry if I am bothering but I don't think I follow, can you elaborate.

> the normal inclusion method is for remote repositories.

> the cache invalidation problem would be intractable for what you're suggesting (and unnecessary, just use `repo: local`)

I don't think I have enough context here but I don't understand why. I can achieve what I want, it's just ugly. I don't understand why you can just read `.pre-commit-hooks.yaml` and declare the hook as you do for remote repos.

**Comment by asottile** [comment]
`repo: local` is the escape hatch from the _normal way_, it's supposed to be ugly.  maybe you should try with yaml anchors or merge keys if you want to reduce duplication (or make a remote repository to house your hook that you need to dupe)

it can't be read because that's not how it works.  the point of `repo: local` is you put the full configuration of the hook into the file itself.  There's no external file dependencies available because it is a blank repository.  if there were files, you'd have an incredibly difficult cache invalidation problem (you'd essentially have to invalidate for any change in the repository) whereas if it's config-only the cache is easy to manage (it's only based on the configuration itself).

**Comment by FFY00** [comment]
> blank repository

I was under the impression `pre-commit` would clone the local repository on `repo: local` (hint: `git clone . target/clone/path`) or something. Maybe this was a false assumption from my part uppon reading #1245.

Anyway, special handling could be implemented since you do know the path of the repo. You could also just deal with this when you first read the file (also read `.pre-commit-hooks.yaml` and merge them).

I can use yaml anchors as follows:
```yaml
hooks:
  - &custom
    id: custom
    name: custom
    entry: custom
    language: python
    types: [python]

repos:
  - repo: local
    hooks:
      - <<: *custom
      - <<: *custom
        args: ['something']
      - <<: *custom
        args: ['something-else']
```

But that's a bit ugly and increases complexity quite a bit. It still solves the problem so it would be an acceptable solution.

The only issue I have here is that now `pre-commit` spits out the following warning, which is undesirable.
```
[WARNING] Unexpected key(s) present at root: hooks
```

Would it be possible to provide a namespace to use such configurations? Something like `data`, `user_data`, etc. that would be ignored by the warning, and that `pre-commit` would commit to not use in the future?

**Comment by asottile** [comment]
no need, you can do this:

```yaml
repos:
  - repo: local
    hooks:
      - &custom
        id: custom
        name: custom
        entry: custom
        language: python
        types: [python]
      - <<: *custom
        args: ['something']
      - <<: *custom
        args: ['something-else']
```

**Comment by FFY00** [comment]
Yes, but it solves *very badly* the following use-case.

```yaml
repos:
  - repo: local
    hooks:
      - &custom
        id: custom
        name: custom
        entry: custom
        language: python
        types: [python]
        args: ['some-arg']
		exclude_types: ['something']
		language_version: python3.5
      - <<: *custom
        args: ['something']
		exclude_types: ['something-else']
		exclude: something
		language_version: python3
		files: something
      - <<: *custom
        args: ['something-else']
		exclude_types: []
		exclude: something-else
		language_version: python3
		files: something-else
```

The fields get overwritten but this is just a mess. This approach is fine as long as one of the hooks is trivial, but if you have several hooks with different configs, everything is all over the place.

**Comment by asottile** [comment]
you'd have the same number of lines with inclusion so I'm not sure what you want

**Comment by FFY00** [comment]
You would have this which is much more readable. And better mimics the lack of `.pre-commit-hooks.yaml`.

```yaml
hooks:
  - &custom
    id: custom
    name: custom
    entry: custom
    language: python
    types: [python]

repos:
  - repo: local
    hooks:
      - <<: *custom
		args: ['some-arg']
        exclude_types: ['something']
        language_version: python3.5
      - <<: *custom
        args: ['something']
        exclude_types: ['something-else']
        exclude: something
        files: something
      - <<: *custom
        args: ['something-else']
        exclude: something-else
        files: something-else
```

I don't think that saving a key to do this sort of stuff is unreasonable.
