### ISSUE TITLE
makefile target is always processed

### ISSUE THREAD

**Issue by PierreR** [pre-commit/pre-commit#1482]
I have a make file that is not firing (because the timestamp of the build product is later than its deps):
```
→ make examples                                                                                                                                                                                                                            
make: Nothing to be done for 'examples'.
```
but when I add this rules to .pre-commit-configuration.yaml

```
  - repo: local
    hooks:
      - id: make-examples
        name: 'Make examples'
        entry: 'make examples'
        language: system
        pass_filenames: false
```
The make target is always processed. 

Is there anything I can do to further debug this issue ?

Thanks
