### ISSUE TITLE
Custom PyPI dependencies

### ISSUE THREAD

**Issue by nihaals** [pre-commit/pre-commit#1486]
When using [isort](https://github.com/timothycrosley/isort), if you want to use `pyproject.toml` as your configuration file, you need to install `toml`. Is there a way to do this? Manually reading the error, getting the path to the Python venv and installing it wouldn't work great for CI.

Error:
`/home/.../.cache/pre-commit/repo.../py_env-python3/lib/python3.8/site-packages/isort/settings.py:358: UserWarning: Found /.../pyproject.toml with [tool.isort] section, but toml package is not installed. To configure isort with /.../pyproject.toml, install with 'isort[pyproject]'.`

Relevant config:
```yaml
  - repo: https://github.com/timothycrosley/isort
    rev: '4.3.21'
    hooks:
      - id: isort
        args:
          - '-c'
```
