### ISSUE TITLE
pre-commit hook ignores isort config

### ISSUE THREAD

**Issue by pmeier** [pre-commit/pre-commit#1495]
There is another issue (#842) with a similar name. My problem is not about package discovery so the proposed solution does not fit my problem.

---

I want to run a check with [`isort`](https://github.com/timothycrosley/isort) as a `pre-commit` hook. My `pre-commit-config.yaml` looks like this:

```yaml
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
        args: [--check-only]
        additional_dependencies: [toml]
```

My `isort` config is part of the `pyproject.toml`:

```toml
[tool.isort]

skip = [
  "my_awesome_package/__init__.py",
]
known_third_party = ["awesome_third_party_package"]
known_first_party = ["my_awesome_package"]
```

If I run `isort` from the console the configuration is automatically detected. If run as a pre-commit hook it ignores the config and fails since `my_awesome_package/__init__.py` is not correctly sorted.

Is this a problem with `pre-commit` or should I bring this up on `isort`?
