### ISSUE TITLE
pre-comit hangs on a brakeman local hook  run

### ISSUE THREAD

**Issue by joshio1** [pre-commit/pre-commit#1498]
I am trying to get [brakeman](https://github.com/presidentbeef/brakeman) run as a local hook.
This is my pre-commit-config.yaml file.

```
repos:
  - repo: local
    hooks:
      - id: brakeman
        name: brakeman
        entry: bash -c 'brakeman'
        language: system
```

After running the above config file using `pre-commit run -a`, the execution hangs and I have to keyboard interrupt it.
Note that brakeman runs fine when run directly on the command line.

**Comment by asottile** [comment]
as written, that will pass every file in your repository as a positional argument

can you show what you're running outside pre-commit. there isn't really anything special happening beyond that

**Comment by joshio1** [comment]
Outside pre-commit, if I run `brakeman` I get a report on my command line.
If I run `brakeman .`, even then it runs fine outside pre-commit.
However, if I use any of the above two commands inside pre-commit, it hangs indefinitely.

**Comment by asottile** [comment]
it probably isn't hanging indefinitely, it's ruby so it's probably just very very very slow running a bunch of times when `brakeman` does not expect positional arguments

you _probably_ want [`pass_filenames: false`](https://pre-commit.com/#creating-new-hooks)

try this:

```yaml
repos:
  - repo: local
    hooks:
      - id: brakeman
        name: brakeman
        entry: brakeman .
        language: system
        pass_filenames: false
```
