### ISSUE TITLE
Parse (additional) hook arguments from the command line

### ISSUE THREAD

**Issue by blaggacao** [pre-commit/pre-commit#1501]
https://github.com/TekWizely/pre-commit-golang/pull/3/files#diff-04c6e90faac2675aa89e2176d2eec7d8

> This is a work-around for pre-commit not allowing to pass arguments to hooks. (... on the cli)

It's not fair to put the burden onto the maintainer of the pre-commit plugin.

Instead of:
```shell
FORMAT= pre-commit run go-returns
```
I want:
```shell
pre-commit run go-returns -w
```

For avoidance of conflict, this should override the arguments passed from the yaml.

**Comment by asottile** [comment]
why doesn't `args: [-w]` work?

**Comment by blaggacao** [comment]
Precisely, for the following:

- when using in ci or, notably, as true pre-commits, I *do not want* autmatic modifications to my workdir *
- still, I want to use pre-commit as a task runner using the same environment and workflow (and very nice output) as pre-commit **

\ * might be that I'm crafting a series of commits from hucnks and the last thing is that some random linting goes in the way at that stage.

\ ** see this example: https://github.com/xoe-labs/coredns-ldap/blob/acde5ca0d65d3184abb87d783abdcb171880ad6d/justfile#L3-L6 (note: for prettier to always ramble, I don't care in a golang repo)

**Comment by asottile** [comment]
sounds like you should use `args` like the rest of the framework

**Comment by blaggacao** [comment]
How would I do that? Did I miss or overlook something?

**Comment by asottile** [comment]
here's a sketch for example:

```yaml
    hooks:
    -   id: gofmt
        alias: gofmt-write
        stages: [manual]
        args: [-w]
    -   id: gofmt
        alias: gofmt-ro
        stages: [commit]
        args: []
```
