### ISSUE TITLE
args doesn't seem to get passed to a hook

### ISSUE THREAD

**Issue by robinbowes** [pre-commit/pre-commit#1503]
I'm trying to pass an arg to a hook.

I'm using this config:

```
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.31.0
  hooks:
    - id: terraform_validate
      args: [--foo=bar, --baz=waz]
```

And invoking a local copy of the hook using `try-repo` like this:
```
 pre-commit try-repo -c .pre-commit-config.yaml ../../../pre-commit-terraform terraform_validate -a
```

I've put this command at the top of the script but the only output is the list of files that are passed in, ie. the `--foo` and `--bar` args do not get passed:

```
echo "args: " "$@"
```

This is pre-commit v2.5.1 (also tested in v2.4.0)

Am I doing something wrong?
