### ISSUE TITLE
How to create my own pre-commit repo

### ISSUE THREAD

**Issue by xiangchen2011** [pre-commit/pre-commit#1512]
I just want to write my own repo which contains the tools I used for my project. e.g. `yapf`,`clang-format`. Thus, instead of writing multiple hooks, I can write the config yaml file as follows:
```yaml
repo: git@github.com:xx/pre-commit-hooks
    rev: master
    hooks:
    -   id: clang-format
    -   id: yapf
```
