### ISSUE TITLE
Understanding how to run commit-msg hook

### ISSUE THREAD

**Issue by cristian05** [pre-commit/pre-commit#1517]
I'm trying to run a **node script to validate my commit message**, this script has a npm dependecy that is [chalk](https://github.com/chalk/chalk). The script is on my local machine and works well with [husky](https://github.com/typicode/husky) and `package.json`, but I can't get it to work with `pre-commit`. 

### I run:
`pre-commit install --hook-type commit-msg`
`git add -A`
`git commit -m "my wrong message"`

This passed but my commit is not valid, because im using [Angular commit message convention](https://gist.github.com/stephenparish/9941e89d80e2bc58a153#format-of-the-commit-message). 

### The output
```
Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Validate Commit Message..................................................Passed
````

Im doing something wrong in my configuration?

### .pre-commit-config.yaml
```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: validate-commit-message
        name: Validate Commit Message
        language: node
        language_version: 14.4.0
        entry: node scripts/git/commit-message.js
        additional_dependencies: ['chalk']
        stages:
          - commit-msg
```

**Comment by asottile** [comment]
In order to fail the commit-msg stage, the hook must exit nonzero -- does your script exit nonzero for problems?

**Comment by cristian05** [comment]
@asottile yes, it does.

```
const fs = require('fs');
const checkMessage = require('./validate-commit-message'); check with some regex the message
const theme = require('../shared/theme'); // console colors related things

const messageFile = process.env.GIT_PARAMS; // I think the problem comes from here

let isValid = true;

if (messageFile) {
  const commitMessage = fs.readFileSync(messageFile, { encoding: 'utf-8' });
  const firstLine = commitMessage.split('\n')[0];
  isValid = checkMessage(firstLine);

  if (!isValid) {
    console.error(theme.header`\nCheck CONTRIBUTING.md at the root of the repo for more information.`);
  }
}

process.exit(isValid ? 0 : 1);
```

**Comment by asottile** [comment]
yeah `GIT_PARAMS` is something invented by `husky`

here's the docs on commit-msg:

https://pre-commit.com/#pre-commit-for-commit-messages

**Comment by asottile** [comment]
hopefully that helped, if you have additional questions feel free to open another issue or comment here or whatever -- thanks again for the issue!

**Comment by cristian05** [comment]
@asottile How can I obtain the current contents of the commit message? Its not clear for me how do this in the [documentation](https://pre-commit.com/#pre-commit-for-commit-messages).

**Comment by asottile** [comment]
is this unclear?

> `commit-msg` hooks will be passed a single filename -- this file contains the current contents of the commit message

**Comment by cristian05** [comment]
Yeah, I'm sorry it's still not clear to me. if I have: 

```
- id: commit-msg-local
  name: Check Commit Message
  language: system
  entry: python scripts/commit_message.py
  always_run: true
  stages: [commit-msg]
```

How obtain the current message inside my commig_message script? to validate it

**Comment by asottile** [comment]
in python you read files with the [`open`](https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files) function

**Comment by asottile** [comment]
you definitely don't want `always_run: true` by the way

**Comment by DimaKarpukhin** [comment]
@asottile Maybe I'm doing something wrong, but in my case, I have to do the following steps to make my hook work:

1. pass .git/COMMIT_EDITMSG  as an argument 
2. sett always_run to true 
Without it, the commit-msg hook is SKIPPED
```
    hooks:
    -   id: commit-msg-hook
        always_run: true
        args: [.git/COMMIT_EDITMSG]
        stages: [commit-msg]
```
Is it ok to do it this way?
And if not, do you have any idea what the problem might be?
