### ISSUE TITLE
Option to run pre-commit against all the files always

### ISSUE THREAD

**Issue by RaviTezu** [pre-commit/pre-commit#1519]
Hi, 

It is possible to run pre-commit against all the file during a `git commit` instead of just the modified files? I use `pylint` as one of the tools to run during a `git commit` and when you run `pylint` against a single file, it may pass as it doesn't have the context of other files, but when you run it against all the files, it may point out errors.

**Comment by asottile** [comment]
here's a (not suggested because pre-commit checks are supposed to be fast) sketch

```yaml
-   id: pylint
    entry: pylint myapp
    pass_filenames: false
```
