### ISSUE TITLE
Best practice for versioning the cache in CI environments should be documented

### ISSUE THREAD

**Issue by remeika** [pre-commit/pre-commit#1525]
Our current Circle CI build job caches pre-commit dependencies as follows:

```yaml
- save_cache:
    name: Cache pre-commit environment
    key: v1-pc-cache-{{ checksum ".pre-commit-config.yaml" }}
    paths:
      - ~/.cache/pre-commit
```

That is, we are using the hash of our configuration file to version the cache. I recently noticed that pre-commit is no longer using the cache; the CI process finds and installs a pre-existing cache, but pre-commit does not recognize it, and reinstalls its environment anyway. I checked the contents of my local cache directory, and there does not appear to be any `package.lock`-style file that complete describes the current state of the cache. The boil-the-ocean approach is to hash the entire cache directory to version the cache, but this seems pretty inefficient.

So my question is: is there a stable set of variables and files that completely specifies a valid cache configuration for circle ci?  I would be happy to update the documentation on caching once I know what the best practice is.
