### ISSUE TITLE
Args parameter problem in.pre-commit-config.yaml

### ISSUE THREAD

**Issue by xiaohuazi123** [pre-commit/pre-commit#1528]
Hello, if my ARGS parameter has multiple options, how should I enclose it
Here is my.pre-commit-config.yaml file configuration
``` yaml
 - repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
      - id: flake8
        args: [--max-line-length=120,--show-source,--ignore=(E231,E402),--max-complexity=12,--exclude=(tests/*,venv/*,*/model/*)]


```
Is this my correct configuration?
