### ISSUE TITLE
Unexpected pass with node language

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1529]
I do have an example where trying to add a node based hook gives some unexpected passing, but only in specific case.

Full example at https://review.rdoproject.org/r/#/c/28371/1/.pre-commit-config.yaml

# What happens

`pre-commit run jsonlint`: correctly identifies broken json
`pre-commit run -a`: incorrectly passes jsonlint

# Example hook config

```yaml
  - repo: https://github.com/ssbarnea/jsonlint
    rev: master
    hooks:
      - id: jsonlint
        name: jsonlint
        entry: jsonlint
        language: node
        files: '^.*\.json$'
```

I may be missing something but I do not see any good reason why running all hooks may give different results then running the hook individually. Even when all hooks run, I can see that the jsonlint hook effectively run and it was not skipped.

![](https://sbarnea.com/ss/Screen-Shot-2020-07-03-13-12-13.97.png)
