### ISSUE TITLE
Pre-commit runs twice when using prepare-commit-message

### ISSUE THREAD

**Issue by paulalex** [pre-commit/pre-commit#1532]
Hi, I am new to using pre-commit and it looks great but I have an issue where for some reason it runs twice.

Following the documentation page I have also installed `pre-commit install --hook-type prepare-commit-msg` because I want to enforce pre commit checking of commit messages to ensure they contain the correct format.

When I commit now I get my checks running, but they run twice. I am using the latest version of pre-commit, `pre-commit = "2.6.0"`.

Below is my yaml file, is this a bug or a misconfiguration on my part?

```
fail_fast: true
repos:
- repo: local
  hooks:
    - id: prepare-commit-msg
      name: prepare-commit-msg
      entry: ./commit-msg
      stages: [prepare-commit-msg]
      language: system
      verbose: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: check-json
    - id: check-yaml
- repo: local
  hooks:
    - id: format-src
      name: format-src
      entry: make format-src
      language: system
      verbose: true
    - id: pylint
      name: pylint
      entry: make lint
      language: system
      verbose: true
    - id: unit-test
      name: unit-test
      entry: make unit-test
      language: system
      verbose: true
```

I have also tried with the entry in the same repo block as the rest of my hooks and I get the same result.
