### ISSUE TITLE
autoupdate: don't update to tag without .pre-commit.hooks.yaml

### ISSUE THREAD

**Issue by Trim21** [pre-commit/pre-commit#1533]
I'm use a commit hash as ref, and the latest tag of this repo don't have a `.pre-commit.hooks.yaml`.
But when I run `autoupdate --freeze` pre-commit will throw a error that `.pre-commit-hooks.yaml does not exist`

Is it ok to just ignore tag without hook file.

**Comment by asottile** [comment]
please provide a full reproduction, version information, output, etc.

as you've written this it sounds like it is working as intended, it's unclear from the information that you've provided what you're experiencing or what you expect

**Comment by Trim21** [comment]
@asottile

My pre-commit config file:

```yaml
  - repo: https://github.com/myint/autoflake
    rev: b330072a26bb13aea8843f8083cee5332d71f78f
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports
```

and this commit is the last commit of [autoflake](https://github.com/myint/autoflake), and just merge a pr adding `.pre-commit-hooks.yaml`.
![image](https://user-images.githubusercontent.com/13553903/87238918-6849c100-c43b-11ea-9b93-499e2c470037.png)


I write a [script](https://github.com/Trim21/actions-cron/blob/master/pre_commit.js) to run `pre-commit autoupdate --freeze` and create a pr monthly. But the current beheavior of `autoupdate` is to exit with 1.

```
Updating https://github.com/myint/autoflake ... [INFO] Initializing environment for https://github.com/myint/autoflake.

=====> /home/runner/.cache/pre-commit/repoy0gbig3b/.pre-commit-hooks.yaml does not exist
Updating https://github.com/psf/black ... [INFO] Initializing environment for https://github.com/psf/black.
already up to date.
Error: The process '/home/runner/.local/bin/pre-commit' failed with exit code 1
    at ExecState._setResult (/home/runner/work/actions-cron/actions-cron/node_modules/@actions/exec/lib/toolrunner.js:574:25)
    at ExecState.CheckComplete (/home/runner/work/actions-cron/actions-cron/node_modules/@actions/exec/lib/toolrunner.js:557:18)
    at ChildProcess.<anonymous> (/home/runner/work/actions-cron/actions-cron/node_modules/@actions/exec/lib/toolrunner.js:451:27)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
##[error]Process completed with exit code 1.
```

What I'm expecting is that adding a option to ignore tags without pre-commit-hooks.
