### ISSUE TITLE
pre-commit doesn't play nicely with open Excel files

### ISSUE THREAD

**Issue by jebob** [pre-commit/pre-commit#1540]
If an unstaged file (.xlsx or .csv) is open in Microsoft Excel, then when unstaged changes are stashed pre-commit cannot stash the file and crashes. This results in the unstaged changes being lost entirely with no hope of recovery?

## Steps to replicate
* Create a repo with `A.py`, `B.py`, `C.csv` and a valid `.pre-commit-config.yaml`.

```yaml
exclude: '^$'
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.6.0
    hooks:
    -   id: trailing-whitespace
```

* Make changes to A.py and B.py. Open C.csv in Microsoft Excel, make some changes and save
* Stage A.py and commit

### Expected behaviour
pre-commit fails, leaving B.py and C.csv intact

### Actual behaviour
pre-commit fails, B.py loses all unstaged changes.
