### ISSUE TITLE
FROM_REF...TO_REF doesn't work very well with shallow clones and git 2.28 (no merge base)

### ISSUE THREAD

**Issue by jarshwah** [pre-commit/pre-commit#1554]
https://github.com/git/git/commit/1457886ce2004c49661c8769f3a5246f6a340c8d describes the change to git 2.28 that breaks FROM_REF...TO_REF with shallow clones, but this stackoverflow post explains it best: https://stackoverflow.com/a/62617192/10583

When cloning a repo shallowly, like with the checkout github action, then you typically do not have all of the commits required for the `...` form of diff to work correctly. Prior to git 2.28, it'd fallback to the `..` form internally. Now it crashes/returns no output.

```
$ git --version
git version 2.28.0
$ git diff origin/master...HEAD
fatal: origin/master...HEAD: no merge base
```

https://matthew-brett.github.io/pydagogue/git_diff_dots.html explains the dots. 2 dots means the difference between the latest FROM and the latest TO. 3 dots `...` means the difference between the FROM that TO branched from (common ancestor).

It'd be ace if we could pass through the exact ref range we were interested in, without having pre-commit force the `...` form between the 2 commits.

**Comment by asottile** [comment]
for GitHub action, use `fetch_depth: 0` , for other use cases use `--files`. deviating from `...` will pull an incorrect file list

**Comment by jarshwah** [comment]
Yes - the workaround I'm using is `fetch_depth: 100` but that's just an arbitrary number. That's going to fail for any PR with > 100 commits on it.

I disagree that deviating from `...` will necessarily pull an incorrect file list.

`...` will diff only your changes
`..` will diff the result of the merge

There are some that argue that tests should always pass on the result of a merge, not just the changeset itself. I don't necessarily subscribe to that belief, but it's not an uncommon one.

Personally I'd prefer the `...` form - but there's a chicken and egg problem when using shallow checkouts, as you don't know what the depth should be without cloning more than you need.

**Comment by asottile** [comment]
I'm sorry you disagree

**Comment by jarshwah** [comment]
I recognise that you have limited time and you can't discuss all issues to the degree that one opening an issue might like, but I'd like you to reconsider closing based on the following:

1. A full clone is terribly slow for large repos
2. Diffing against the merge commit is probably not an uncommon thing to want

I'm not asking you to change the default, I'm asking for that choice to be available to the user in some manner. If you still disagree, that's fine too.

Thanks :)

**Comment by asottile** [comment]
does `--files` not do that?

**Comment by jarshwah** [comment]
Thank you, it does :) nothing to see here

**Comment by asottile** [comment]
cheers!

**Comment by yelizariev** [comment]
@jarshwah could you share example of using ``--files``? I faced the same problem the following github actions config: https://github.com/itpp-labs/misc-addons/blob/fffd0f40d212594f4f7951004f263360e52a43c1/.github/workflows/DINAR-pr.yml#L20-L41

**Comment by asottile** [comment]
probably `--files $(git diff --name-only ...)` or something of the sort

**Comment by jarshwah** [comment]
More or less - I'll share the majority of our lint step:


```
 linting:
    name: linting
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: fetch master and pr commits
        run: |
          git fetch --no-tags --depth=1 origin +refs/heads/${{ github.base_ref }}
          git fetch --no-tags --depth=1 origin ${{ github.sha }}
      - uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - name: set PY
        run: echo "::set-env name=PY::$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ env.PY }}-precommit
          restore-keys: |
            ${{ runner.os }}-pip-precommit-
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: install precommit
        run: python -m pip install pre-commit
      - name: run precommit
        id: run-precommit
        # https://github.com/pre-commit/pre-commit/issues/1554 since we have shallow checkouts we need to generate
        # the file list ourselves.
        run: pre-commit run --show-diff-on-failure --files $(git diff --name-only --no-ext-diff -z origin/master..HEAD)
```
