### ISSUE TITLE
QST (ENH?) skip hooks based on name rather than id?

### ISSUE THREAD

**Issue by MarcoGorelli** [pre-commit/pre-commit#1556]
Currently, one can skip running a hook using the `SKIP` environment variable, which specifies a comma separated list of hook ids.

Is there a way to skip hooks _based on their name_?

Here's an example to illustrate the issue:

```
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.1.20
  hooks:
    - id: nbqa
      args: ['flake8']
      name: nbqa-flake8
      additional_dependencies: ['flake8']
    - id: nbqa
      args: ['mypy']
      name: nbqa-mypy
      additional_dependencies: ['mypy']
```

Currently I could do
```
SKIP=nbqa pre-commit run --all
```
and skip both these hooks, but it would be nice to be able to only skip one of them based on its name, e.g.
```
SKIP=nbqa-mypy pre-commit run --all
```

Is this possible? If not, would you be open to allowing it (I'd be happy to work on a PR, if welcome)?
