### ISSUE TITLE
`--all-files` doesn't honor pyproject.toml config file.

### ISSUE THREAD

**Issue by giovanism** [pre-commit/pre-commit#1562]
Hi, I'm trying to use isort and black on my CI with pre-commit. I also have a directory to exclude/skip from isort and black checks which I have configured using `pyproject.toml` on my project root directory.

Using this plain config and running with `--all-files` resulted isort and black checking against all files including previously excluded/skipped directory.
```
repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: black .
    language: python
    types: [python]
  - id: isort
    name: isort
    entry: isort .
    language: python
    types: [python]
```
I have found a workaround for black by explicitly adding `-c pyproject.toml` on the hook's entry. Unfortunately isort doesnt have such flag, afaik. However, using isort's `--show-config` shows that it loaded the configuration correctly.
