### ISSUE TITLE
Support printing custom message if a hook fails

### ISSUE THREAD

**Issue by jkff** [pre-commit/pre-commit#1565]
I'm configuring precommit for a repo inside my organization. Suppose the output of one of the hooks, or its usefulness, or how to fix it, might be not that obvious to my coworkers.

I would like to be able to configure a custom message when this hook fails - e.g. it could point to an organization-internal wiki page explaining why we have enabled this hook and how to fix common issues with it.

It could look something like this I suppose:

```
- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
  - id: black
    # "message" would be a new field for a hook
    message: "Please see http://notion.so/my-org/Python-Autoformatting for configuration and common issues"
```

**Comment by asottile** [comment]
you can easily do this without needing any special option:

```yaml
entry: bash -c 'echo "see ..." && exec black "$@"' --
```

**Comment by jkff** [comment]
@asottile Your suggestion applies to developing one's own hook that would print a custom message - while my request is about being able to print a custom message for a hook someone else wrote. I expect to use a couple dozen different hooks and I don't want to replace them all with custom-written versions that print a message. Am I missing something?

**Comment by asottile** [comment]
nope! anything a hook provider can set can be overridden in the configuration

**Comment by jkff** [comment]
I understand that I can override the "entry" to replace the shell command the hook uses, but this is still not good enough.

Suppose I want to provide a custom message for the trailing-whitespace hook.

Am I understanding correctly that you are suggesting that I do this?

```
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
    entry: bash -c 'echo "see ..." && exec trailing-whitespace-fixer "$@"' --
```

This is problematic for several reasons:
* I need to go look up the hook definition in order to find out that the original entry was called `trailing-whitespace-fixer`
* This breaks the abstraction boundary: if the hook is updated and now calls its entry `fix-trailing-whitespace` instead, my precommit config will break
* This significantly reduces readability of my precommit config - now every hook is an ugly bash command

(it also doesn't seem to work - the hook stopped checking for trailing whitespace when I wrote it this way - but I suppose that could be fixed with some debugging?)

**Comment by jkff** [comment]
(also, thanks for responding so quickly! FWIW, if I end up convincing you that this is a good idea, I'd be happy to implement it myself and send a PR)

**Comment by asottile** [comment]
doesn't have to be bash either you could do:

```yaml
entry: ./my-custom-thing trailing-whitespace-fixer
```

and then write a script which does your custom logic

but no, you're not going to convince me, this has been brought up before

**Comment by jkff** [comment]
With this approach, the abstraction boundary is still violated, and I would need a different my-custom-thing for each hook, because the messages to be printed would be different for each hook, right?

I don't want to spend much more of your time if you are certain that you don't want to have this feature - I'll stick with simply adding comments in the precommit config, that's probably good enough.

But last thing, could you point me to a previous discussion of this, so I can better understand "why not"? I tried searching through open and closed issues before filing this one, and couldn't find it.

**Comment by asottile** [comment]
you could also

```yaml
-   repo: local
    hooks:
    -   id: print-msg
        language: system
        entry: echo "..."
        verbose: true
```

this'll always print, might not do what you want but might

I can try and find it later, but github search is kinda bad and there's a lot of issues :(
