### ISSUE TITLE
Idea: support gitattributes for file inclusion/exclusion

### ISSUE THREAD

**Issue by glasserc** [pre-commit/pre-commit#1581]
git has a `gitattributes` mechanism dating back to v1.5.2. This mechanism lets you "tag" paths with arbitrary metainformation. This makes it a good, vendor-neutral place to attach information to paths that can't be gleaned from their contents (e.g. this path is a vendored dependency). I think it would be cool if `pre-commit` could understand this file and allow the use of these attributes as a mechanism for controlling which paths are subject to which hooks.

Here is a straw-man proposal for how this could look:

`.gitattributes`:
```
public/ace/**    vendored
client/**     team=frontend
```

`.pre-commit-config.yaml`:

```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
        include_types:
          - git:team=frontend
      - id: end-of-file-fixer
        exclude_types:
          - svg
          - git:vendored   # shorthand for git:vendored=true
```

Here I chose to overload `include_types` and `exclude_types` but another attribute could be used instead (`include_attributes` and `exclude_attributes`?). I'm also not exactly sure how to represent "unset" attributes in the `.pre-commit-config.yaml` format (`git:!vendored`?).

How could this be implemented? git offers a `git-check-attr` command, but I'm not sure how it could be used effectively. It takes individual paths, not pathspecs, so there's no easy way to tell it to dump all the attributes for all files. The easiest way might be just to write a parser for the file format in Python. The [gitattributes format](https://www.git-scm.com/docs/gitattributes) is relatively straightforward -- it does build on the [gitignore glob format](https://www.git-scm.com/docs/gitignore) but negative patterns are forbidden. `gitattributes` files can occur at any level of the directory hierarchy, with "closer" files having precedence over "further" ones.

What is the cost of not implementing this idea? Probably negligible. I bet most users of git do not use `gitattributes` (I only learned about it today after more than ten years of git use). Instead, developers with small repositories probably do not store this kind of metainformation in any machine-readable format, and developers with large repositories may store this information in other ways. Users who want access to this information in their git hooks can "get by" with the same sets of paths explicitly enumerated in a `.pre-commit-config.yaml` file, or alternately by writing hooks that access the information explicitly.
