### ISSUE TITLE
configurable minimum_pre_commit_version, perhaps_run

### ISSUE THREAD

**Issue by graingert** [pre-commit/pre-commit#1585]
when running an old version of pre-commit, I currently get:
```
=====> pre-commit version 2.7.1 is required but version 2.6.0 is installed.  Perhaps run `pip install --upgrade pre-commit`.
```
I'd like to be able to configure it to say:
```
=====> pre-commit version 2.7.1 is required but version 2.6.0 is installed.  Perhaps run `pip-sync`.
```
eg:

```yaml
minimum_pre_commit_version:
    version: 2.7.1
    perhaps_run: pip-sync
```
