### ISSUE TITLE
Check to make sure that the hooks in the config file are installed

### ISSUE THREAD

**Issue by ahonnecke** [pre-commit/pre-commit#1615]
Scenario:
 * I'm working with a distributed team that does not always remember to reinstall their pre-commit hooks when I update the config
 * I run the hooks in CI but they get confused when the hooks pass locally and not in CI

Proposed solution:
 * a pre-commit hook that checks to make sure the pre-commit hooks are up to date with the configuration file

Desired behavior:
 * if the config file has a new hook, or an updated hook that has not been installed, commits are rejected until the user runs `pre-commit install --install-hooks` and installs the newest version

**Comment by asottile** [comment]
It always does this already, there's no way to turn this off.

You've got a classic [XY problem](http://xyproblem.info/)

I suspect your configuration contains [unsupported values like `rev: master` or `rev: stable`](https://pre-commit.com/#using-the-latest-version-for-a-repository)

**Comment by ahonnecke** [comment]
Are these valid rev values?

```
ahonnecke@pop-os:~/$ grep rev .pre-commit-config.yaml 
    rev: 3.8.3
    rev: v3.2.0
    rev: v0.0.3
    rev: 5.5.3
    rev: v2.6.0
    rev: 19.10b0
```

**Comment by asottile** [comment]
those seem fine yeah, pre-commit ensures those are all installed at their particular versions on startup

do you have unpinned `additional_dependencies` maybe? that'd be the only other thing that would be variable

**Comment by ahonnecke** [comment]
I don't believe so, no:

```
repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: check-ast
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: check-json
    - id: check-symlinks
    - id: check-yaml
    - id: check-added-large-files
  - repo: https://github.com/ahonnecke/blacklist
    rev: v0.0.3
    hooks:
    -   id: blacklist
  - repo: https://github.com/timothycrosley/isort
    rev: 5.5.3
    hooks:
    - id: isort
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.6.0
    hooks:
    -   id: pylint
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
```
