### ISSUE TITLE
Local python hooks don't get pip installed

### ISSUE THREAD

**Issue by davidhart82** [pre-commit/pre-commit#1626]
The docs seem to suggest that hooks with the python language will get pip installed. This doesn't appear to be the case for local hooks, which is not obvious. It seems to be because the command to install is `pip install .`. There does appear to be a slightly odd looking workaround, by specifying the additional_dependencies to be the same as the entry.

An artificial example:

```yaml
repo: local
hooks:
    -   id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
        additional_dependencies: [isort]
```
