### ISSUE TITLE
[FEATURE REQUEST] Requesting to skip certain hooks

### ISSUE THREAD

**Issue by flw-cn** [pre-commit/pre-commit#1650]
I've been using `pre-commit` to help me alert my oversights and improve the code quality of my repository, and it feels great. But when I wanted to hold other team members to the same standard, I ran into a bit of a problem.

My plan was to add a call to `pre-commit` to my GitHub workflow, which would automatically check my code when it received a PR.

Since my `.pre-commit-config.yaml` uses the golang checking suite from https://github.com/dnephin/pre-commit-golang, which includes a call to `golangci-lint`, so I had to download an extra `golangci-lint` in my workflow, but I actually have a dedicated step to call `golangci/golangci-lint-action@v2` in my workflow already, which is definitely a waste of resources and causes some confusion.

So I thought it would be best if I could skip the `pre-commit` call to `golangci-lint` in my workflow.

Here is my config file:

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-case-conflict
        .......... and many hooks
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.3.5
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-build
      - id: golangci-lint
```

and workflow:

```yaml
    - uses: golangci/golangci-lint-action@v2
      with:
        version: v1.31

    - name: Get GolangCI-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0

    - uses: pre-commit/action@v2.0.0
```
