### ISSUE TITLE
'SyntaxError: Unexpected token {' when running eslint hook.

### ISSUE THREAD

**Issue by HaGuesto** [pre-commit/pre-commit#1682]
I'm trying to migrate in our new mono-repo the frontend linting on staged files from husky to pre-commit [as recommended here](https://stackoverflow.com/questions/64001471/pylint-with-pre-commit-and-esllint-with-husky/64002300#64002300).

When I try to run 
```
pre-commit run eslint
```
I get the following error
```
eslint...................................................................Failed
- hook id: eslint
- duration: 0.06s
- exit code: 1

/home/hans/.cache/pre-commit/repo0q_v76eh/node_env-system/lib/node_modules/eslint/bin/eslint.js:93
        } catch {
                ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

This is the eslint hook in the `pre-commit-config.yaml`
```
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v7.12.1
  hooks:
  - id: eslint
    verbose: true
    args: ['--fix']
    additional_dependencies: ['eslint@7.12.1', 'eslint-plugin-jsx-a11y']
    files: \.[jt]sx?$ 
    types: [file]
```
My pre-commit version is 2.8.2
