### ISSUE TITLE
SKIP still attempts to install hook

### ISSUE THREAD

**Issue by Yajo** [pre-commit/pre-commit#1689]
According to https://pre-commit.com/#temporarily-disabling-hooks:

> The `SKIP` environment variable is a comma separated list of hook ids. This allows you to skip a single hook

In a project of mine, I have this hook:

```yaml
  - repo: https://github.com/prettier/prettier
    rev: 2.1.2
    hooks:
      - id: prettier
        name: prettier + plugin-xml
        additional_dependencies:
          - "@prettier/plugin-xml@0.12.0"
        args:
          - --plugin=@prettier/plugin-xml
```

I don't know if you're aware of the prettiermageddon that happened recently, but many hooks out there got just broken, in 2 ways:

1. You cannot install it unless you pin node version `14.14.0`.
1. Once installed, you cannot execute it (even with node version pinned) if you're using plugins (as I do above).

Due to us using https://github.com/copier-org/copier to maintain repo templates, I have to execute pre-commit with old configs when updating templates.

Well... details apart, I can live with it by using `SKIP` when updating the template, but that presents a different problem: **pre-commit is still trying to install prettier the old way**.

So, that's the main point of this issue: **if I use `SKIP`, then pre-commit shouldn't attempt to install repos that only contain skipped hooks**.
