### ISSUE TITLE
Path to the hook repo as `args` or `entry`

### ISSUE THREAD

**Issue by zaufi** [pre-commit/pre-commit#1694]
I'm trying to make a hook that runs the CMake script (w/ `cmake -P script.cmake` command).
Unfortunately, I can't find a way to specify the full path to the `script.cmake` file which is in the root of the hook repo.

Is there any way to do that?

**Comment by asottile** [comment]
can you show what you have so far?  the `language` / etc. is probably relevant to the answer (for instance with `language: script` you'd use a path relative to `argv[0]` (in bash: `$0` for instance)

**Comment by zaufi** [comment]
I have the following `.pre-commit-hooks.yaml` in my repo:
```yaml
- id: validate-xml
  name: Validate XMLs
  description: 'Extract XSD/DTD from the XML and execute `xmllint` to validate'
  entry: cmake
  args: ['-P', 'pre-commit-validate.cmake']
  language: system
  types: [file, non-executable, text, xml]
  files: '\.xml$'
  stages: [commit]
```
The problem is that the `pre-commit` runs in the working directory with the `.pre-commit-config.yaml` file but my script (`pre-commit-validate.cmake`) laid in the hook repo (internally managed by `pre-commit`) and there is no way to specify a full path to it in the `.pre-commit-hooks.yaml`.
