### ISSUE TITLE
windows recognize types: executable wrongly

### ISSUE THREAD

**Issue by hanxifu** [pre-commit/pre-commit#1695]
Hi,

Here's a sample of a local hook.

```yaml
- id: test
  name: test
  entry: ..
  language: python
  types: [executable]
```

Seems like you're using `identify.identify.tags_from_path` to determine if a file is executable, but `os.X_OK` will return a wrong answer on Windows. Is there any workaround for this issue?

I've checked the file with `ls -la` on windows git bash, there's no `x` permission.
