### ISSUE TITLE
Question: Is it possible to add --show-diff-on-failure to git hook runs and not just CLI runs?

### ISSUE THREAD

**Issue by xdesai** [pre-commit/pre-commit#1712]
Sorry if a github issue is not the correct place for this question. We can close it out and take this somewhere else if need be.

From https://pre-commit.com/#pre-commit-run I learned about --show-diff-on-failure and it's something that I have been wanting in precommit since we started using it. It seems clear to me how to implement this when running precommit on the command line. But we use a .pre-commit-config.yaml and git hooks to run pre-commit and I couldn't find a way to turn this setting on.
Is it possible and I'm just missing something? Or is this technically a feature request?

**Comment by asottile** [comment]
the option is only intended for usage in CI, not for use in git hooks

that said, you could do this as a hook:

```yaml
-   repo: local
    hooks:
    -   id: git-diff
        name: git diff
        entry: git diff --exit-code
        language: system
        pass_filenames: false
        always_run: true
```
