### ISSUE TITLE
flake8 exclude parameter does not seem to be taken into account

### ISSUE THREAD

**Issue by jaepetto** [pre-commit/pre-commit#1723]
I have the following configuration (setup.cfg):
```
[flake8]
max-line-length = 120
exclude = .tox,.git,*/migrations/*,*/static/CACHE/*,docs,node_modules,venv,*/vendors/*,*/scripts/*
```

However, when pre-commit runs, some files within the `scripts` folder get rejected:
```
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...........................................(no files to check)Skipped
black....................................................................Passed
isort....................................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

scripts/users.py:94:9: E722 do not use bare 'except'
scripts/users.py:125:1: E402 module level import not at top of file
...
```

I also tried with a slightly different config:
```
[flake8]
max-line-length = 120
exclude = .tox,.git,*/migrations/*,*/static/CACHE/*,docs,node_modules,venv,*/vendors/*,scripts/*
```

but I get the following errors.

How can I make sure that the correct `setup.cfg` file is used?
Is there anything else I'm doing wrong?

**Comment by MarcoGorelli** [comment]
@jaepetto the `exclude` option from `setup.cfg` works when you run `flake8` on a directory, if you run `flake8` on your file (as is done when running it as a pre-commit hook) it'll have no effect.

E.g. try running
```
flake8 scripts/users.py
```

Instead, use `exclude` in `.pre-commit-config.yaml`, e.g.:
```
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        exclude: ^scripts/users\.py$
```

**Comment by jaepetto** [comment]
@MarcoGorelli Thanks for the tip. I'll try that.

In the meantime, I also discovered that updating the `pre-commit-config.yaml` did the trick:
```
exclude: 'docs|node_modules|migrations|.git|.tox|scripts|vendors'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.5.4
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
        additional_dependencies: [flake8-isort]
```

If I understand well, the change you are proposing will exclude the files _only_ at the flake8 stage. While the change I made will exclude the files at every stages.

Is that correct?
