### ISSUE TITLE
Feature Request: Allow defining/including groups of hooks/configs as a hook group

### ISSUE THREAD

**Issue by teejae** [pre-commit/pre-commit#1724]
Somewhat related to:
https://github.com/pre-commit/pre-commit/issues/554

Use case:
In my company, we have lots of repos (in various languages/functions), but want to standardize on having the same pre-commits across all repos.
- `pre-commit-hooks` repo that's accessible Github org-wide
  - hooks
    - java formatting hook
    - java lint
    - java build
    - java test
    - python lint
    - python test
    - etc..
- some Java repos
- some Python repos
- etc..

Ideally 

So for a given Java repo, we'd want to run all the java hooks

Current version: Example Java repo `pre-commit-config.yaml`:
```yaml
repos:
  ## Standard hooks

  # See https://pre-commit.com/hooks.html
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/ryanrhee/shellcheck-py
    rev: v0.7.1.1
    hooks:
      - id: shellcheck

   ## All Java Hooks
  - repo: <org pre-commit-hooks repo>
    rev: 1.2.3
    hooks:
    - id: java-format
    - id: java-lint
    - id: java-build
    - id: java-test
```

Groups version: Example Java repo `pre-commit-config.yaml`:
```yaml
repos:
  - repo: <org pre-commit-hooks repo>
    rev: 1.2.3
    hooks:
    - id: standard-hooks-group
    - id: all-java-hooks-group
```

Is there something I'm missing in how to define files now that I could already include sets of hooks from other repos, including hooks from 3rd parties (like Python's black formatter)?

Thanks for making pre-commit great!
