### ISSUE TITLE
Allow passing files as single arguments to system command

### ISSUE THREAD

**Issue by skorokithakis** [pre-commit/pre-commit#1728]
Sorry if this has been asked before, but I can't find anything in the docs, web or issues. My problem is simple, I have a "system" command that accepts one argument, so I want to run it once per file, but `pre-commit` passes multiple files to it. How can I avoid that and run the command once per changed file instead?

**Comment by paulhfischer** [comment]
i don't think there's an option for that (filenames are always passed in as arguments, see [here](https://github.com/pre-commit/pre-commit/blob/bf85379619e4aa5019412f3f3237a8c3c3e225e3/pre_commit/languages/helpers.py#L126-L136) and a hook command is only called once, see [here](https://github.com/pre-commit/pre-commit/blob/bf85379619e4aa5019412f3f3237a8c3c3e225e3/pre_commit/commands/run.py#L194)). you could use something like
```yaml
repos:
    - repo: local
      hooks:
          - id: myhook
            name: myhook
            entry: bash -c 'for file in "$@"; do mycommand "$file"; done'
            language: system
```
to split the arguments being passed to your command.
