### ISSUE TITLE
"pre-commit run --hook-stage push run-pytest -v" says there are no files to check but "git push" runs pytest 

### ISSUE THREAD

**Issue by drjasonharrison** [pre-commit/pre-commit#1729]
My .pre-commit-config.yaml contains:

```
default_stages: [commit]
repos:
-   repo: local
    hooks:
    -   id: run-pytest
        description: run pytest
        name: run pytest # displayed when git push hook is executed
        entry: python3
        args: [-m, pytest, --cov=processor, processor/test/*]
        language: system
        types: [python]
        pass_filenames: false
        stages: [push]
```

when I try running the pytest-hook manually:

```
$ pre-commit run --hook-stage push run-pytest -v
run pytest...........................................(no files to check)Skipped
- hook id: run-pytest
```

but when I use `git push`
```
$ git push
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
run pytest...............................................................Failed
- hook id: run-pytest
- exit code: 4

============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-4.6.11, py-1.9.0, pluggy-0.13.1
rootdir: /home/jason/the-processor
plugins: cov-2.10.1, dotenv-0.5.2
collected 0 items                                                              

========================= no tests ran in 0.00 seconds =========================
ERROR: file not found: processor/test/*
```

Is it possible that the earlier attempt to manually run the `run-pytest` hook didn't skip, but failed?

If not, why would the `run-pytest` hook fail to run?
