### ISSUE TITLE
Auto-update github-action 

### ISSUE THREAD

**Issue by mBouamama** [pre-commit/pre-commit#1730]
Hi,
i use pre-commit in my project, and i notice version for repo like that:

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-case-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
        args: ['--django']
    -   id: requirements-txt-fixer
    -   id: double-quote-string-fixer
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-typing-imports==1.10.0]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
    -   id: autopep8
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        exclude: ^(tests/|docs/)
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes

```
I want to auto update my pre-commit.config.yaml, like pyupbot with requirements.txt witch open a pr when it detected a new version, did you have the same things?

I found on internet that: do you think is a best practise?
```yaml
name: Pre-commit auto-update
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.CPR_GITHUB_TOKEN }}
          branch: update/pre-commit-autoupdate
          title: Auto-update pre-commit hooks
          commit-message: Auto-update pre-commit hooks
          body: |
            Update versions of tools in pre-commit
            configs to latest version
          labels: dependencies

```
Thx for your amazing work!!
Regards;
