### ISSUE TITLE
Installing additional_dependencies with `language: conda` fails due to disregarding channels

### ISSUE THREAD

**Issue by siboehm** [pre-commit/pre-commit#1738]
# Example:
flake8-action/.pre-commit-hooks.yaml
```yaml
-   id: flake8-conda
    name: flake8-conda
    description: This hook runs flake8.
    entry: flake8
    language: conda
    types: [python]
    require_serial: true
```
flake8-action/environment.yaml
```yaml
channels:
- conda-forge
dependencies:
- flake8=3.8.4
```

test_repo/.pre-commit-config.yaml
```yaml
repos:
  - repo: ../flake8-action
    rev: <COMMIT-SHA>
    hooks:
     - id: flake8-conda
       additional_dependencies: [flake8-docstrings, flake8-rst-docstrings]
```

Now running `pre-commit` in `test_repo` fails with: 
```
[INFO] Initializing environment for ../flake8-action.
[INFO] Initializing environment for ../flake8-action:flake8-docstrings,flake8-rst-docstrings.
[INFO] Installing environment for ../flake8-action.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/simon/miniconda3/bin/python', '/home/simon/miniconda3/condabin/conda', 'install', '-p', '/home/simon/.cache/pre-commit/repomsutw5a0/conda-default', 'flake8-docstrings', 'flake8-rst-docstrings')
return code: 1
expected return code: 0
stdout:
    Collecting package metadata (current_repodata.json): ...working... done
    Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
    Collecting package metadata (repodata.json): ...working... done
    Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
    
stderr:
    
    PackagesNotFoundError: The following packages are not available from current channels:
    
      - flake8-docstrings
      - flake8-rst-docstrings
    
    Current channels:
    
      - https://repo.anaconda.com/pkgs/main/linux-64
      - https://repo.anaconda.com/pkgs/main/noarch
      - https://repo.anaconda.com/pkgs/r/linux-64
      - https://repo.anaconda.com/pkgs/r/noarch
    
    To search for alternate channels that may provide the conda package you're
    looking for, navigate to
    
        https://anaconda.org
    
    and use the search bar at the top of the page.
    
    
    
Check the log at /home/simon/.cache/pre-commit/pre-commit.log
```
# Reason
This happens because additional_dependencies are installed using `conda install`, which doesn't respect the `channels` set in `environment.yml`.
https://github.com/pre-commit/pre-commit/blob/0ed79309763f80affcf43698d4e4019c73b3ec93/pre_commit/languages/conda.py#L63-L71

I encountered this while trying to set-up `pre-commit` as part of our CI. The workaround is to create a conda environment which has `conda-forge` configured as one of the default channels and setup pre-commit in there.

Is this expected behaviour or a bug? If it's a bug I can code up a fix, probably by loading the `environment.yml` and saving an updated version, which has the additional dependencies added, to `env_dir`.
