### ISSUE TITLE
How to use pre-commit for multipe folders and local script on Windows?

### ISSUE THREAD

**Issue by richardnguyen99** [pre-commit/pre-commit#1742]
I have a project that contains a backend written in Python and a frontend written in Javascript. For python, I use the clone repo from `https://github.com/psf/black`. For javascript, I'm currently using `eslint` and `npm script` to check. Here's my `.pre-commit-config.yaml`:

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
        files: ^services/auth

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: cd services/client && npm run lint
        always_run: true
        language: system
```

But I cannot run it on Windows. I tested on Linux and it works just fine, but it's not my computer. The error says:

```
- hook id: eslint
- exit code: 1

Executable `cd` not found
```

I tried to look up for the solution, which was originally how to run pre-commit for multiple subdirectories, but this is the best I've got. Any idea how to achieve that? Thank you!

**Comment by asottile** [comment]
dupe #1417 #1356 #1348 #1140 #1110 #1061#466

notably your error is because `cd` is not a command, it is a shell builtin and pre-commit does not use shells because shells reduce portability and make shell injection vulnerabilities too easy (if you follow the dupes there's a bunch of examples of how to do what you want)

**Comment by asottile** [comment]
it shouldn't work on linux either so there's something you're not showing / telling

**Comment by paulhfischer** [comment]
for `npm`you could use the `--prefix` flag, e.g. `npm run --prefix services/client lint`.

**Comment by richardnguyen99** [comment]
> dupe #1417 #1356 #1348 #1140 #1110 #1061#466
> 
> notably your error is because `cd` is not a command, it is a shell builtin and pre-commit does not use shells because shells reduce portability and make shell injection vulnerabilities too easy (if you follow the dupes there's a bunch of examples of how to do what you want)

Thanks for your reply but all of the dupes you mentioned don't work. First, they all either use bash commands, which is not available on Windows, or use other online repos for other languages. Second, I just want pre-commit to execute the local npm script, like `husky`, for Javascript files, so I don't want to clone.

**Comment by richardnguyen99** [comment]
> for `npm` you could use the `--prefix` flag, e.g. `npm run --prefix services/client lint`.

Thank you! It works just fine, after I modified a bit.

```yaml
- repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npm run --prefix services/client eslint
        files: ^services\/client\/.ts[x]?$/
        always_run: true
        language: system
```
I'm not sure why I had to change `lint` to `eslint` but it works, so...

**Comment by asottile** [comment]
> 
> 
> > dupe #1417 #1356 #1348 #1140 #1110 #1061#466
> > notably your error is because `cd` is not a command, it is a shell builtin and pre-commit does not use shells because shells reduce portability and make shell injection vulnerabilities too easy (if you follow the dupes there's a bunch of examples of how to do what you want)
> 
> Thanks for your reply but all of the dupes you mentioned don't work. First, they all either use bash commands, which is not available on Windows, or use other online repos for other languages. Second, I just want pre-commit to execute the local npm script, like `husky`, for Javascript files, so I don't want to clone.

bash has to be available on windows if you're using `git` -- it's part of the git distribution

**Comment by richardnguyen99** [comment]
> > > dupe #1417 #1356 #1348 #1140 #1110 #1061#466
> > > notably your error is because `cd` is not a command, it is a shell builtin and pre-commit does not use shells because shells reduce portability and make shell injection vulnerabilities too easy (if you follow the dupes there's a bunch of examples of how to do what you want)
> > 
> > 
> > Thanks for your reply but all of the dupes you mentioned don't work. First, they all either use bash commands, which is not available on Windows, or use other online repos for other languages. Second, I just want pre-commit to execute the local npm script, like `husky`, for Javascript files, so I don't want to clone.
> 
> bash has to be available on windows if you're using `git` -- it's part of the git distribution

It's probably something wrong with my Git installation, but I once tried `bash -c "command"` from one post, it didn't work.

**Comment by asottile** [comment]
"it didn't work" isn't a useful bug report, show what you're seeing

**Comment by richardnguyen99** [comment]
> "it didn't work" isn't a useful bug report, show what you're seeing

The error is the same type but it said `Executable: bash not found`.

**Comment by asottile** [comment]
That doesn't look like pre-commit's error messaging?

**Comment by richardnguyen99** [comment]
I'm not sure I understand that question butI assume you think I use Git bash on Windows, which I don't. I only use Powershell and Cmd. Yes, I installed Git Bash for Windows but I don't use the interface.

**Comment by richardnguyen99** [comment]
I just checked with Git Bash for Windows, and it works as well. It turns out that you don't need to specify the `files` config in `hooks` as for Powershell. Here's the config for Git Bash:

```yaml
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c "npm run --prefix services/client lint"
        always_run: true
        language: system

```
