### ISSUE TITLE
Empty file path with custom local hook

### ISSUE THREAD

**Issue by patrick91** [pre-commit/pre-commit#1745]
Hi there, I'm trying to setup pre-commit for a mono-repo (backend and frontend of an app I'm using) and I'm encountering an "error" where the path passed to the hook is empty, here's an example of hook:

```
repos:
  - repo: local
    hooks:
      - id: example
        name: run example
        language: system
        entry: bash -c 'cd backend && echo hello && echo $@ && echo "${@/backend\//./}" && exit 1'
        types: [python]
        files: ^backend/
```

The idea is to run hooks from the correct folder so they find the right configuration files :)

This is my stage:

```
❯ git status
On branch main
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   .pre-commit-config.yaml
	modified:   backend/api/schema.py
	modified:   frontend/components/activate-screen/modal.tsx
	modified:   frontend/components/add-media-card/modal.tsx
	new file:   frontend/components/loading.tsx
```

And this is the output:

```
❯ git commit
run example..............................................................Failed
- hook id: example
- exit code: 1

hello


```

Am I doing something wrong with using "$@"? Let me know if you need more information 😊

**Comment by paulhfischer** [comment]
- `bash -c` shifts the arguments. thus. if pre-commit passes `foo1  foo2 foo3` as arguments, `$@` will expand to `foo2 foo3`
- you have `types: [python]`, thus only `backend/api/schema.py` will be matched => `$@` expands to ` `

**Comment by paulhfischer** [comment]
this topic is also discussed in #1110 #1356 #1417 #1742

**Comment by paulhfischer** [comment]
i don't know which hooks you are trying to run, but many also support specifying the config location (e.g. for black your entry could be `black --config backend/pyproject.toml` without using `cd`)

**Comment by patrick91** [comment]
I've solved by doing this:

```yaml
repos:
  repo: local
  hooks:
      - id: prettier
        name: run prettier
        language: system
        entry: bash run_hook.sh "npm run prettier" frontend
        files: ^frontend/
```

and run_hook.sh:

```sh
COMMAND=$1
FOLDER=$2

shift 2;

cd $FOLDER && $COMMAND "${@/backend\//./}"
```

@paulhfischer thank you! I think my solution is good for my use-case! not sure all the tools I'm using support passing a folder or config path, also this solution allows me to use the version specified in package.json and pyproject.toml :)
