### ISSUE TITLE
Homebrew virtualenv not working with python3.9

### ISSUE THREAD

**Issue by lma-wish** [pre-commit/pre-commit#1754]
A hook with something like

``` Yaml
- id: python-type-check-hook
  name: Type check our python files
  entry: mypy
  language: python
  language_version: python3
  types: [python]
  args:
    - --config-file=mypy.ini
  verbose: true
```

Works everywhere (`containers`, `CI`, `linux`) but not work on Mac 11.1

```
An unexpected error has occurred: CalledProcessError: Command: ('/usr/local/opt/python@2/bin/python2.7', '-mvirtualenv', '/Users/lma/.cache/pre-commit/repoauhKCG/py_env-python3', '-p', 'python3')
Return code: 100
Expected return code: 0
Output: 
    Already using interpreter /usr/local/opt/python@3.9/bin/python3.9
    Using base prefix '/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9'
    New python executable in /Users/lma/.cache/pre-commit/repoauhKCG/py_env-python3/bin/python3.9
    Also creating executable in /Users/lma/.cache/pre-commit/repoauhKCG/py_env-python3/bin/python
    ERROR: The executable /Users/lma/.cache/pre-commit/repoauhKCG/py_env-python3/bin/python3.9 is not functioning
    ERROR: It thinks sys.prefix is '/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9' (should be '/Users/lma/.cache/pre-commit/repoauhKCG/py_env-python3')
    ERROR: virtualenv is not compatible with this system or executable
    Running virtualenv with interpreter /usr/local/bin/python3
    
Errors: (none)

Check the log at /Users/lma/.cache/pre-commit/pre-commit.log
```

It is not the issue of pre-commit itself but anyone has any insight what is going on? and how to fix it?

Thanks for the help
