### ISSUE TITLE
ESLint with Vue plugin not working

### ISSUE THREAD

**Issue by bdelate** [pre-commit/pre-commit#1764]
I am trying to setup a hook for ESlint which includes the Vue plugin. All the existing hooks are working correctly. The ESLint hook works on javascript files but it ignores `*.vue` files.

The monorepo contains multiple projects (ie: languages) which are in use:

```
repo
    .pre-commit-config.yaml    
    .flake8
    .isort.cfg
    .eslintrc.js
    frontend (this is the vue app)
        package.json
    backend (this is a python app)
        requirements.txt
```
As a sanity check, if I run `npm run lint` everything is linted as expected including the `*.vue` files.

`.pre-commit-config.yaml`:

```yml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-docstring-first
      - id: no-commit-to-branch
        args: [-b, master]
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.2.1"
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v7.18.0"
    hooks:
      - id: eslint
        types_or: [javascript, jsx, ts, tsx, vue]
        additional_dependencies:
          - eslint-plugin-vue@v7.5.0
```

`package.json`:

```json
{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "twilio-video": "^2.10.0",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/eslint-config-airbnb": "^5.0.2",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-vue": "^7.5.0",
    "vue-template-compiler": "^2.6.11"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "eslint:recommended",
      "plugin:vue/recommended",
      "@vue/airbnb"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
```

`.eslintrc.js`:

```javascript
module.exports = {
  env: {
    browser: true,
    es2020: true,
  },
  extends: ["plugin:vue/recommended", "airbnb-base"],
  parserOptions: {
    ecmaVersion: 11,
    sourceType: "module",
  },
  plugins: ["vue"],
  rules: { quotes: ["error", "double"] },
};
```

I have also tried using a regex expression in the `.pre-commit-config.yaml` file to include both `*.js` and `*.vue` files but that also just ignores the vue files.

I have setup the above based on: [Vue Eslint](https://eslint.vuejs.org/) and [Pre commit ESLint](https://github.com/pre-commit/mirrors-eslint)

Am I missing anything? Is anything setup incorrectly?
