### ISSUE TITLE
results of hook during commit different from results through pre-commit run hook

### ISSUE THREAD

**Issue by gaucheph** [pre-commit/pre-commit#1776]
i'm having an issue with the mypy hook at the moment.

during a commit, the mypy hook runs and detects some issues with my code. however, when i run `pre-commit run mypy --files=myfile.py` those same issues are not detected and the manual hook run passes fine.

what's going on here? how can i learn what pre-commit is actually doing so that i can eliminate it as the source of my confusion?

things i've tried:

- changing the `rev` key in my pre-commit-config.yaml for the mypy hook to upgrade it [same issues]
- running a different mypy installation with the same `args` [no issues]
- setting various combinations of recommendations for skipping mypy issues like using `# type: ignore` [same issues]

here's what i have for `mypy` in my pre-commit-config.yaml:

```yaml
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.782'
  hooks:
  - id: mypy
    args: [--ignore-missing-imports, --follow-imports=skip, --no-strict-optional]
    additional_dependencies:
    - 'pydantic'
```
