### ISSUE TITLE
[feature] ability to override 'fail commit' on files changes on a per hook basis

### ISSUE THREAD

**Issue by jpatallah** [pre-commit/pre-commit#1782]
Hello,

Can you please implement an override so that pre-commit won't fail the commit on files changed on a per hook basis.  For example:

If terraform_fmt runs and updates the format of a file.....just do the commit.  As it stands, you end up having to run the commit again, and since terraform fmt already fixed the format the first time, then it passes.  

Would be nice to have something like the below that could be configured in .pre-commit-config.yaml
```
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  hooks:
    - id: terraform_fmt
      fail_on_modify_files: false
```
