### ISSUE TITLE
usage of prepare-commit-msg

### ISSUE THREAD

**Issue by blackliner** [pre-commit/pre-commit#1793]
from https://pre-commit.com/#pre-commit-for-commit-messages:
`prepare-commit-msg hooks can be configured by setting stages: [prepare-commit-msg].`

How do I configure it? How does `.pre-commit-config.yaml` have to look like for this to work?

**Comment by asottile** [comment]
The documentation shows you the ways you can configure stages:

- [at the configuration level](https://pre-commit.com/#config-stages)
- [at the manifest level](https://pre-commit.com/#hooks-stages)

**Comment by blackliner** [comment]
if anyone is looking for a real answer:
```yaml
repos:
  - repo: local
    hooks:
      - id: prepare-commit-msg
        name: Prepare Commit Message
        description: Add statistics and a message template to the commit message.
        entry: ./scripts/internal/git-hooks/prepare-commit-msg
        language: script
        stages: [prepare-commit-msg]
```
