### ISSUE TITLE
Do version numbers have to have a '.'?

### ISSUE THREAD

**Issue by paddyroddy** [pre-commit/pre-commit#1794]
Looking at this line it looks to be testing for the presence of a dot in the version number https://github.com/pre-commit/pre-commit/blob/d827e9aa7211456965bf7d16f06ac6a85b0f2984/pre_commit/clientlib.py#L124 but what if a repo is just following a simple `v1`/`v2` model?

I'm using this repo https://gitlab.salort.eu/jsalort/latexhook/-/tags which has a `v1` tag.  My `.pre-commit-config.yaml` looks like this:
```
repos:
    - repo: https://gitlab.salort.eu/jsalort/latexhook
      rev: v1
      hooks:
          - id: latexindent
```

This means every time i commit I get this error at the top
![image](https://user-images.githubusercontent.com/15052188/107364174-05a0cc80-6ad3-11eb-9079-e32b5e4eb6ca.png)

My version is `pre-commit==2.10.1` and I don't think this used to happen
