### ISSUE TITLE
Use black hook with --check option only

### ISSUE THREAD

**Issue by ckaldemeyer** [pre-commit/pre-commit#1804]
Hi everyone,

I am new to pre-commit and want to use it in combination with [black](https://black.readthedocs.io/en/stable/) as described [here](https://www.mattlayman.com/blog/2018/python-code-black/).

```
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
```

Now my problem is that I do not actually want to execute `black` to re-format the code but instead want to only check it on every commit using the following command `black . --check --verbose` which I have already integrated in our CI.

This only has informative character and leaves the formatting to the programmer.

Can anyone give me a hint on how to accomplish this?

Thanks in advance
Cord
