### ISSUE TITLE
How to run pyclean?

### ISSUE THREAD

**Issue by Ceres445** [pre-commit/pre-commit#1821]
I added this to my `.pre-commit-config.yaml` file
```yaml
-   repo: local
    hooks:
    -   id: pyclean
        name: pyclean
        entry: pyclean .
        language: system
        types: [python]
```
I added pyclean to requirements and commited my changes, however I get
```
pyclean..............................................(no files to check)Skipped
```
I saw [this](https://github.com/pre-commit/pre-commit/issues/1245) and tried changing the configuration but it didn't change anything.
running `pyclean .` works on my computer.
