### ISSUE TITLE
How to implement bump version hook?

### ISSUE THREAD

**Issue by dudicoco** [pre-commit/pre-commit#1825]
Hi,

I would like to implement a hook which runs a version bumping tool such as https://github.com/c4urself/bump2version.

The hook should bump the version within a file if any other files within that directory were changed, and only if the version file wasn't changed manually.

The issue here is how to check if the file wasn't changed manually or already autobumped in one of the previous commits since ORIGIN?

Thanks

**Comment by asottile** [comment]
sorry, I don't have cycles to help you design your code -- you probably want to look at `git` history / `diff` to solve your problem

**Comment by dudicoco** [comment]
Thanks @asottile.

For anyone interested, I was able to do this with `bump2version` and `git diff`:

```
- repo: local
  hooks:
  - id: bump-version
    name: Bump version
    entry: bump_version.sh
    language: script
    exclude: (.pre-commit-config.yaml)|(.github/)
```

```
#!/bin/bash
set -e

if git diff --exit-code origin/master VERSION; then
  bump2version --allow-dirty patch VERSION --current-version `cat VERSION`
fi
```
