### ISSUE TITLE
Hook not installed for all stages

### ISSUE THREAD

**Issue by ypicard** [pre-commit/pre-commit#1834]
Hi,
I have the following .pre-commit-config.yaml file in my repository:

```
repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: conventional-commits
        name: Conventional Commits
        description: Check Conventional Commits specification is respected
        entry: ./.githooks/conventional-commit.sh
        language: script
        stages: [commit-msg]
```

I have a `pipenv` script that I use to install and configure pre-commit: 
`setup = "pre-commit install --install-hooks --overwrite"`

When I commit something, the `black` hook runs correctly, but the `conventional-commits` does not. I think it is not installed and triggered for the `commit-msg` hook, but I really don't understand why.

Doesn't `pre-commit` install install all hooks for the specified stages in the config file ? What am i supposed to do ?
