### ISSUE TITLE
Local repo hook failed to find tox.ini

### ISSUE THREAD

**Issue by arazi47** [pre-commit/pre-commit#1846]
Hey there. In the pre-commit config file I have this:

```
repos:
-   repo: local
    hooks:
    - id: black
      name: black
      entry: tox -e py3-black
      language: system
      types: [python]
```

However, it says that the `tox.ini` file cannot be found.
![image](https://user-images.githubusercontent.com/6633145/111502977-03273780-874f-11eb-965f-d4cc881eaadd.png)
I'm guessing this is because the script does not run in the directory where `tox.ini` is located. Can I fix this somehow? (not in a hacky way, if possible).

Thanks a lot!

P.S.: I know I can do it the other way around, run `pre-commit` from `tox`, but for my use case running `tox` from `pre-commit` would be ideal.
