### ISSUE TITLE
Github action caching

### ISSUE THREAD

**Issue by dudicoco** [pre-commit/pre-commit#1855]
Hi,

Looking at the code of the official pre-commit GitHub action, caching is implemented within the code.

However, when using hooks of type `docker` or `docker_image` it seems that the docker images are not being cached, making executions longer.

In addition, the example within the readme shows that an additional cache action should be configured, although cache is built into the code: https://pre-commit.com/index.html#github-actions-example
Is the additional cache action needed?

Thanks

**Comment by asottile** [comment]
github actions doesn't have a way to cache docker images

**Comment by dudicoco** [comment]
@asottile what about the second part regarding the example configuration:
```
    - name: set PY
      run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
```

Is this needed considering that caching is already baked into the action's code?
