### ISSUE TITLE
Support changing directory before hook installation

### ISSUE THREAD

**Issue by tpansino** [pre-commit/pre-commit#1858]
### Background

I'm tinkering with adding a pre-commit hook for the wonderful [Mega-Linter](https://github.com/nvuillam/mega-linter) project (a Python/Docker/Node hard fork of the Shell-based [GitHub Super-Linter](https://github.com/github/super-linter)).

The Mega-Linter has a [Node CLI](https://nvuillam.github.io/mega-linter/mega-linter-runner/), however the `package.json` for it lives in a [`mega-linter-runner` subdirectory](https://github.com/nvuillam/mega-linter/tree/master/mega-linter-runner) of the root folder of Mega-Linter repo. This means, per the pre-commit [Node](https://pre-commit.com/#node) docs, it can't be installed:

> The hook repository must have a package.json. It will be installed via `npm install .`

### Questions

1. Can the install hook be customized so that I can point at the subdirectory via hook metadata?
1. If not - what are my other options? The CLI mostly just wraps a Docker image, so I've gotten that to work directly with a `local` hook:

    ```
    repos:
    - repo: local
        hooks:
          - id: mega-linter
            name: Mega-Linter
            language: docker_image
            entry: -e DEFAULT_WORKSPACE=/src nvuillam/mega-linter:v4
    ```

    I don't _love_ this experience though, as it breaks the abstraction layer of the CLI. I also think hooks are way more discoverable and adopted when there is a `.pre-commit-hooks.yaml` in the root of the repo, indicating a known method of use for pre-commit users, vs using a `local` hook.
