### ISSUE TITLE
How to specify local path as arguments on hook

### ISSUE THREAD

**Issue by jordisantamaria** [pre-commit/pre-commit#1874]
Hi, I try to include arg for my own config file of markdownlint, but It says can't find the file, I guess It's because It's checking for files in the repository downloaded? no idea

How I should do to use my own config file in the hook?

The error: 
`Cannot read or parse config file  .markdownlint.json: ENOENT: no such file or directory, open ' .markdownlint.json'`

My config
```
repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
    - id: markdownlint
      args: [-f, -c .markdownlint.json]
```
