### ISSUE TITLE
How to pin a specific rev

### ISSUE THREAD

**Issue by os-ia** [pre-commit/pre-commit#1879]
I'm using a `pylint` plugin ([pylint-odoo](https://github.com/OCA/pylint-odoo), `v2.7.4`) that requires a specific pylint version (`2.5.3`), but each time I run pre-commit's `autoupgrade` command I have to fix the `rev`. I would like to pin the rev.

```
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.5.3
    hooks:
      - id: pylint
        name: pylint-odoo
        types: ["file", "python"]
        exclude: .github/
        args: ["--rcfile=.pylintrc", "--valid_odoo_versions=12.0"]
        additional_dependencies: [pylint-odoo==3.7.1]
```
