### ISSUE TITLE
pre-commit is not working as expected

### ISSUE THREAD

**Issue by YikSanChan** [pre-commit/pre-commit#1884]
Hi,

My project is structured like this:

```
> tree
.
└── python
    ├── Makefile
    └── main.py
```

I put `.pre-commit-config.yaml` in the root, and I want it to run formatter check `defined in python/Makefile` every time I commit.

```
# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint
        stages: [ commit ]
        language: system
        entry: cd python && make lint
```

However, even though `make lint` throws error in my setup, I can still pass the check successfully, which is not what I expect.

```
> cd python && make lint
black -l 79 --check *.py
would reformat main.py
Oh no! 💥 💔 💥
1 file would be reformatted.
make: *** [lint] Error 1

> gcmm "more whitespaces"
Lint.....................................................................Passed
[master fd26230] more whitespaces
 1 file changed, 1 insertion(+), 1 deletion(-)
```

I wonder why? Here's the full MVP repo https://github.com/YikSanChan/pre-commit-issue-not-working

Note: I have installed pre-commit and black locally.
