### ISSUE TITLE
pre-commit commit-msg hook is SKIPPED

### ISSUE THREAD

**Issue by DimaKarpukhin** [pre-commit/pre-commit#1886]
@asottile Maybe I'm doing something wrong, but in my case, I have to do the following steps to make my hook work:

1. pass .git/COMMIT_EDITMSG as an argument
2. sett always_run to true
Without it, the commit-msg hook is SKIPPED
```
    hooks:
    -   id: commit-msg-hook
        always_run: true
        args: [.git/COMMIT_EDITMSG]
        stages: [commit-msg]
```
Is it ok to do it this way?
And if not, do you have any idea what the problem might be?

**Comment by asottile** [comment]
I obviously can't help you unless you show the definition of your hook.  I cannot see your screen

**Comment by DimaKarpukhin** [comment]
Thank you for the quick response. 
Here is the hook ==>
It exits nonzero in a case of any problem in ```__validate_input(msg)``` and ``` __check_msg_convention(msg)``` functions
![1619017275706](https://user-images.githubusercontent.com/45074360/115575879-a7127e80-a2cb-11eb-9d72-b92c4a6c898c.png)

And that is how I define it to use in my project after pip install ```commit-msg-hook```
```
repos:
-   repo: https://github.com/DimaKarpukhin/commit-msg-hook.git
    rev: v0.0.9
    hooks:
    -   id: commit-msg-hook
        always_run: true
        args: [.git/COMMIT_EDITMSG]
        stages: [commit-msg]
```
Link to repo: https://github.com/DimaKarpukhin/commit-msg-hook.git
