### ISSUE TITLE
Local only hooks?

### ISSUE THREAD

**Issue by pzelnip** [pre-commit/pre-commit#1887]
My current scenario is my team uses pre-commit to set up Black as a pre-commit hook, and as such we have the config for that hook defined in our `.pre-commit-config.yaml` file.

I'd like to set up a pre-push hook on my local machine that does a check before I push to  our remotes.  However, if I modify the `.pre-commit-config.yaml` file, that check (which really is only applicable to my local machine because it's due to my own personal workflow) will be imposed on the rest of my team.

Is there a way to have a hook set up on a local basis only, or is pre-commit "all or nothing"?  Like my current workaround is to not use pre-commit at all locally, but that means I'm also not running that black pre-commit hook (which isn't a huge deal, but if in the future our team adopts more hooks that are managed by pre-commit then that may be an issue).

**Comment by asottile** [comment]
there is not, the pre-commit configuration is meant to standardize the workflow of the repository

that said, if you're the only one using `pre-push` you could set up an alternative configuration and use `pre-commit install --hook-type pre-push --config path/to/alternate/config.yaml`

**Comment by asottile** [comment]
you could also make a special hook to accomplish this:

```yaml
-   repo: local
    hooks:
    -   id: local-customizations
        name: local-customizations
        entry: bash -c 'if [ -f local-pre-commit-checks.yaml ]; then exec pre-commit run --config local-pre-commit-checks.yaml --files "$@"; fi' --
        language: system
```
