### ISSUE TITLE
Passing pipe to args

### ISSUE THREAD

**Issue by dudicoco** [pre-commit/pre-commit#1891]
Hi,

I would like to run the following via docker_image hook:
```
docker run --rm -v "$PWD:/mnt" koalaman/shellcheck:stable test.sh -f diff | patch -p 1
```

The problem is that I can't add the pipe to the command, i've tried the following:
```
  - id: shellcheck
    language: docker_image
    entry: koalaman/shellcheck:v0.7.1
    args:
    - -f
    - diff
    - '|'
    - patch
    - -p
    - '1'
    types:
    - shell
```

And also this way:
```
  - id: shellcheck
    language: docker_image
    entry: koalaman/shellcheck:v0.7.1 -f diff | patch -p 1
    types:
    - shell
```

Both ways did not work and yielded the same result.

Is it possible to pipe a command?

Thanks

**Comment by asottile** [comment]
pre-commit does not involve a shell.  if you need shells (and you are accepting the risks of using a shell) you can set the entry to `bash -c '...'` and do whatever shell scripting you need in there

fwiw, I'd recommend https://github.com/shellcheck-py/shellcheck-py over the docker approach, you're likely to have a better and faster user experience

**Comment by dudicoco** [comment]
@asottile I have tried setting the entrypoint, but the image containers nothing but the shellcheck binary.

I have considered using shellcheck-py before as well, is there a way to achieve the piping using that hook?

**Comment by asottile** [comment]
if the container doesn't contain a shell then I'm afraid there's not much that can be done in the way of piping, but it should work fine with any other `language` such as `python` which is used for `shellcheck-py`

**Comment by dudicoco** [comment]
@asottile i've tried using `shellcheck-py` but it seems that the file names are not being passed when using `bash -c`:
```
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.7.2.1
  hooks:
  - id: shellcheck
    entry: bash -c shellcheck $@ -f diff | patch -p 1
```

Any ideas?
