### ISSUE TITLE
`install-hooks` hangs indefinitely - git shallow clone

### ISSUE THREAD

**Issue by cdce8p** [pre-commit/pre-commit#1924]
Originally posted here: https://github.com/PyCQA/pylint/issues/4505

The `pre-commit install-hooks` command hangs indefinitely with the following config
```yaml
  - repo: https://github.com/pycqa/pylint
    rev: v2.8.2
    hooks:
      - id: pylint
        additional_dependencies: [
          pylint_django,
        ]
```

The issue seems to be that pylint started using `setuptools_scm` with version `2.8.2`. pre-commit probably only does a shallow git clone without tags which results in version `0.1.dev1...` being installed. `pylint_django` requires at least `pylint>=2.0` so the install will fail.

Is there an option to specify that `pre-commit` should do a full clone with all tags and history? That should fix it.
Ideally this could be set as the default in the hook config upstream if required.
