### ISSUE TITLE
Set language to system, for a repo may not be feasible

### ISSUE THREAD

**Issue by saeedshojaee** [pre-commit/pre-commit#1927]
I recently updated pre-commit from 2.9.3 to 2.13.0, and started to get an error on dvc-pre-commit. In the last commit there is a new check on the `pre-commit/repository.py` line 121-138. It prevents the users to change the language from repos default to system. 
Here is my minimal example.

```
#.pre-commit-config.yaml
repos:
  - repo: https://github.com/iterative/dvc
    rev: 2.0.15
    hooks:
      - id: dvc-pre-commit
        language: system  # overrides default language: python
        language_version: default # overrides default language-version: python3
        stages:
          - commit
```

If you take a look at take a look at  `pre-commit/repository.py`, the `ret["language-version"]` is set to `python3`,  I can set the language version to a different value in the `.pre-commit-config.yaml`, but regardless of any effort this error will be raised:
```
[ERROR] The hook `dvc-pre-push` specifies `additional_dependencies` but is using language `system` which does not install an environment.  Perhaps you meant to use a specific language?
```
