### ISSUE TITLE
Question: setting up `pylint` check

### ISSUE THREAD

**Issue by ehontoria** [pre-commit/pre-commit#1937]
# Description
Hi folks! I'm trying to set up using `pylint` with `pylint-django` in my repository but running into an issue where if I run `pylint` on the command line everything is fine, but when I try to run it as part of `pre-commit` I end up with a lot of the following:

```
some_file.py:8:0: E0401: Unable to import 'some-package' (import-error)
```

# Configuration
I'm using the following `pre-commit` configuration:
```
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.7.4
    hooks:
        - id: pylint
          args: ["--rcfile", ".pylintrc"]
          additional_dependencies:
              - pylint-django==2.3.0
              - astroid==2.5.2
              - django==1.11.29
 ```

Unfortunately multiple upstream issues means I'm pigeon-holed into these versions for the moment.

`pre-commit` version: 1.21.0
`python` version: 3.7.7
