### ISSUE TITLE
Surpress warnings with --silent

### ISSUE THREAD

**Issue by mihaigalos** [pre-commit/pre-commit#1953]
Hi,

I've dockerized pre-commit and every time I run in, it mounts my repo in the docker and runs `pre-commit run --all-files`.

Every time, however, I'm getting warnings which I would like to surpress or remove:
```bash
[WARNING] The 'rev' field of repo 'https://github.com/pre-commit/pre-commit-hooks' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
[WARNING] The 'rev' field of repo 'https://github.com/psf/black' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
```

I guess these comes from the `black` and `pre-commit-hooks` github references in the config file. Any ideas how to reduce verbosity here?
I'm mounting my cache (`~/.cache/pre-commit`) into docker.

Here is my `.pre-commit-config.yaml`:
```yaml
exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
        files: (^|/)a/.+\.(py|html|sh|css|js)$
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: trailing-whitespace
      - id: pretty-format-json

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3

-   repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
```
