### ISSUE TITLE
Using environment variables in `pre-commit-config.yaml`

### ISSUE THREAD

**Issue by queensferryme** [pre-commit/pre-commit#1955]
I am using `mypy` with `pre-commit`. As `pre-commit` runs in isolated environments, I have to manually specify a bunch of deps in `additional_dependencies` so that `mypy` could run smoothly just as in my local dev environment. The config looks like this:

```yaml
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
    - id: mypy
      name: Type Check
      # As `mypy` runs in an isolated environment, it is necessary to manually specify
      # some libraries of the current (poetry) environment for `mypy` to work properly.
      additional_dependencies:
        - fastapi
        - pydantic
        - pyquery
        - pytest
        - rsserpent
        - types-requests
```

So I have came up with this "clever" idea: I know that `pip` supports installing from a file-system path like `pip install $PWD`, so why not put the environmenet variable `$PWD` in `additional_dependencies` and all the dependencies in my local dev environment will be automatically installed, hence eliminating the needs to specify a bunch of deps manually. The config looks like this:

```yaml
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
    - id: mypy
      name: Type Check
      # As `mypy` runs in an isolated environment, it is necessary to manually specify
      # some libraries of the current (poetry) environment for `mypy` to work properly.
      additional_dependencies:
        - ${PWD}
        - types-requests
```

This kind of syntax (yaml interpolation with env vars) is supported in docker-compose ([link](https://docs.docker.com/compose/environment-variables/)), but unfortunately failed in `pre-commit` with these errors:

```
✗ pre-commit run --all-files
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/queensferry/.cache/pre-commit/repo9bnvw3qi/py_env-python3.7/bin/python', '-mpip', 'install', '.', '${PWD}', 'types-requests')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    ERROR: Invalid requirement: '${PWD}'
    
Check the log at /Users/queensferry/.cache/pre-commit/pre-commit.log
```

My dev environment setup ([repo](https://github.com/RSSerpent/rsserpent-plugin-example)):
```
Python 3.7.10
Poetry version 1.1.6
pre-commit 2.13.0
```

So my questions are:
- am I doing this in a wrong way?
- is there any way to achieve this in `pre-commit`?

Huge thanks in advance.
