### ISSUE TITLE
define different hooks depending on the operating system

### ISSUE THREAD

**Issue by dpinol** [pre-commit/pre-commit#1960]
I'd like to specify different entry script entries depending on the operating system. Eg

```
    hooks:
      - id: formatw
        name: format
        os: windows
        entry: bin/format.bat
        language: script
      - id: formatl
        name: formatl
        os: linux
        entry: bin/format.sh
        language: script
```

What I tried was having a bootstrap script which invokes the corresponding .sh or .bat depending on the operating system. 
This works if I invoke this unique bootstrap script directly from both windows or linux terminals.
However, it looks like python requires that the invoked script to have .sh extension in Linux and .bat in Windows, and hence there's no way to configure the name of the bootstrap script so that it works in both systems. 

Error messages I got: 
### In Linux, if the script has bat or no extension
[Errno 8] Exec format error: '/mnt/c/Users/Dani/source/repos/sc-engine/format.bat
[Errno 8] Exec format error: '/mnt/c/Users/Dani/source/repos/sc-engine/format'

### In windows if the script does not have .bat extension
[WinError 193] %1 is not a valid Win32 application

This is the bootstrap script I try to use (got it at https://nastytester.com/posts/script-that-works-in-windows-and-linux.html)
```
echo off

goto(){
# Linux code here
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
$SCRIPT_DIR/bin/format.sh
}

goto $@
exit

:(){
bin\format.bat
exit
```
