### ISSUE TITLE
`flake8` check additional files other than `*.py`

### ISSUE THREAD

**Issue by ehontoria** [pre-commit/pre-commit#1961]
Hi folks,

I'm trying to configure `flake8` to check files other than just `*.py` but am having a tough time.

On the `flake8` command line `flake8 --filename '*.<some ending>'` works and picks up the file I would like, but using the same setup in my `.pre-commit-config.yaml` doesn't seem to be working:
```
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
        -   id: flake8
            args: ["--filename", "'*.<some ending>'"]
```

The file in question is edited, still not getting picked up when I run `pre-commit run flake8`.
```
flake8...............................................(no files to check)Skipped
```

Any idea what is going on?

**Comment by asottile** [comment]
flake8 isn't really intended to lint non-python, but you can configure it to do so

first check if your extension is registered with [identify](https://github.com/pre-commit/identify) -- this changes whether you can utilize `types` or not

flake8 by default uses `types: [python]` so you may need to override that

```yaml
    -   id: flake8
        # override and use a different type
        types: [pyi]
    -   id: flake8
        # use a union of types
        types: [file]. # reset to default
        types_or: [python, pyi]
    -   id: flake8
        # use some extension not registered by identify
        types: [file]. # reset to default
        files: \.wat$
```

note that you can specify hooks as many times as you want

apologies if this is misformatted, I'm moving and don't have internet yet so this is on my phone
