### ISSUE TITLE
Different executable resolution for `system` language across `pre-commit run` and `git commit` with pyenv

### ISSUE THREAD

**Issue by ned2** [pre-commit/pre-commit#1971]
## Context

I'm using a `system` hook to run pylint, as suggested by the pre-commit docs with the `.pre-commit-config.yaml` below.

I've installed pylint into my virtual environment, which is managed by pyenv.

```yaml
repos:
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
```

## The issue

When I run `pre-commit run` the hook runs fine. However, when I run `git commit` pre-commit attempts to run the hook, but fails with pyenv not finding the executable.

```
pyenv: pylint: command not found

The `pylint' command exists in these Python versions:
  3.9.6/envs/my_venv
  my_venv
```

I've also tried using `pyenv exec pylint` for the `entry` to help pyenv out, but same issue. 

Obviously I'm hoping that the hook would how I'm trying to use it, but am aware that the `system` language is not the happy path and may not do exactly what I want. 

What seems concerning is the asymmetry between `pre-commit run` and `git commit` which I gather there is a goal of maintaining  behaviour parity across.

## Possible cause

It looks like the problem might lie in `pre_commit.parse_shebang.find_executable()`.

The virtualenv's bin is on the PATH when running `pre-commit run` but not when running `git commit`, meaning that `find_executable` returns `/home/ubuntu/.pyenv/versions/my_venv/bin/pylint` in the former, but `/home/ubuntu/.pyenv/shims/pylint` in the latter, which is the pyenv shim that when run in the isolated environment set up by pre-commit isn't able to resolve to the relevant executable, because it doesn't know which pyenv version to use.

An cludgy workaround for my use case is to manually set `PYENV_VERSION` in the hook config, but this is not ideal, although as mentioned, the real problem is maybe the asymmetry?

Workaround:

```yaml
repos:
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: env PYENV_VERSION=my_venv pylint
        language: system
        types: [python]
```
