### ISSUE TITLE
Directory not excluded when pre-commit hook is installed

### ISSUE THREAD

**Issue by nickperkins** [pre-commit/pre-commit#1988]
When I run pre-commit manually using `pre-commit run -a`, the directory `infra` is ignored. I have run `pre-commit install` to have the git hooks installed, but now the the directory is being included again.

Yaml config is:
```yaml
exclude: |
        (?x)^(
             infra/
            )
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.50.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_tflint
    - id: terraform_tfsec
 ```
