### ISSUE TITLE
Working with windows GitKraken Hook not working

### ISSUE THREAD

**Issue by zollen** [pre-commit/pre-commit#1990]
I am running window 10 with GitKraken and Eclipse IDE.
Here is my .pre-commit-config.yaml at the root level of my git project.
```
repos:
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
-   repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
    -   id: isort
-   repo: https://github.com/econchick/interrogate
    rev: 1.4.0  
    hooks:
    - id: interrogate
      args: [-vv, -i, --fail-under=80]
```

[WINDOW PROMPT] pre-commit-2.13.0.pyz install
I can see .git/hooks/pre-commit
But It appear pre-commit is a python script designed to run on Linux/Unix shell, but not Window. When I commit a file, GitKraken hook log showed the following error:
```
The system cannot find the path specified.
Hook process exited.
```
