### ISSUE TITLE
Pass list of staged files as arg. [QUESTION]

### ISSUE THREAD

**Issue by Morpheus636** [pre-commit/pre-commit#1998]
Hi, sorry if this is the wrong place to ask, but I couldn't find an answer in the documentation.

I have a pre-commit hook shown below:

```yaml
      - id: black
        name: Code Formatter (black)
        stages: [ commit ]
        language: system
        entry: poetry run black 
        types: [ python ]
 ```
 
 I need to pass a list of all the staged .py files to it, what is the optimal way to do that?
