### ISSUE TITLE
CalledProcessError: command: ('gem', 'build', 'fake_gem__.gemspec')

### ISSUE THREAD

**Issue by mmeendez8** [pre-commit/pre-commit#1999]
Hi, 

Thanks for this package, since I discovered I have not stopped using it in all my projects :rocket: 

This might be related with https://github.com/pre-commit/pre-commit/issues/418 but since it is such an old issue I decided to open a new one here.

I am getting the following error:
```
[INFO] Installing environment for https://github.com/jumanjihouse/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('gem', 'build', 'fake_gem__.gemspec')
return code: 1
expected return code: 0
stdout:
    Executable `gem` not found
stderr: (none)
Check the log at /home/mmendez/.cache/pre-commit/pre-commit.log
```

It is actually happening on all my conda envs. Cannot figure out what is happening.

This is my `pre-commit-config.yaml`:

```yaml
repos:
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.8.3
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
      - id: yapf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
      - id: markdownlint
        args: ["-r", "~MD002,~MD013,~MD024,~MD029,~MD033,~MD034,~MD036", "-t", "allow_different_nesting"]
  - repo: https://github.com/myint/docformatter
    rev: v1.3.1
    hooks:
      - id: docformatter
        args: ["--in-place", "--wrap-descriptions", "79"]
```
