### ISSUE TITLE
redirect repo

### ISSUE THREAD

**Issue by frnmst** [pre-commit/pre-commit#2003]
Hello,

I wonder if it's possible to redirect a `repo` URL in the pre-commit-config file: this might be useful if the developer of a hook
moves the repo home repository, for example from github to gitlab. Can this be implemented by adding a `redirect_repo` key
(or something) in the `.pre-commit-hooks.yaml` file of the old repository? As a reference here is one of my hooks with the new key:

```yaml
- id: md-toc
  name: Update markdown table-of-contents
  description: 'Replace TOC marker with a table of contents'
  language: python
  types: [markdown]  # as detected by pre-commit with identify-cli
  entry: md_toc
  args: [-p, github]
  redirect_repo: https://some.other.url/frnmst/md-toc
```

This feature should work with the `autoupdate` command. Things like infinite redirects must be avoided of course.
What do you think?
