### ISSUE TITLE
Exclude not working

### ISSUE THREAD

**Issue by ozamed** [pre-commit/pre-commit#2006]
Hey everyone,

I'm trying to ignore a folder by using `exclude` but it's not working. When I commit files in the specified folder, it's still running hooks.

Here is my `.pre-commit-config.yaml`
```yaml
default_language_version:
    python: python3.9.6

repos:
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black
        entry: bash -c 'black "$@"; git add -u' --
        files: my_api
        exclude: ^migrations/
        args: ['--line-length=79']
-   repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
    -   id: isort
        entry: bash -c 'isort "$@"; git add -u' --
        files: my_api
        exclude: ^migrations/
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle
        files: my_api
        exclude: ^migrations/
        args: ['--add-ignore=D100', '--convention=google']
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        files: my_api
        exclude: ^migrations/
```
