### ISSUE TITLE
black's language_version: python3 overrides default_language_version

### ISSUE THREAD

**Issue by ikonst** [pre-commit/pre-commit#2009]
My repo specifies:
```yaml
default_language_version:
  python: python3.8
```
and uses:
```yaml
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black
```

black's hooks [specifies](https://github.com/psf/black/blob/e465acf6f8dc82152b0e9187ed6e934b97c678c8/.pre-commit-hooks.yaml#L6) `language_version: python3` in order to require Python 3 but not prescribe anything more specific, but this overrides my more-specific `python3.8` with whatever `python3` points to on any given system.
