### ISSUE TITLE
InvalidManifestError occurring in gitlab CI

### ISSUE THREAD

**Issue by mmerickel** [pre-commit/pre-commit#2012]
```yaml
pre-commit:
  image: python:3.8-buster
  variables:
    XDG_CACHE_HOME: ${CI_PROJECT_DIR}/.ci-cache
    PYTHONUSERBASE: ${CI_PROJECT_DIR}/.ci-cache
  cache:
    # bust the cache if the python version changes
    key: ${CI_JOB_IMAGE}
    paths:
      - ${XDG_CACHE_HOME}
  before_script:
    - mkdir -p ${XDG_CACHE_HOME}/bin
    - export PATH=${XDG_CACHE_HOME}/bin:$PATH
    - pip install --user -U pre-commit
  script:
    - pre-commit run --all-files
```

Initial run works fine. Subsequent runs, especially on other branches, seem to fail.

```
An error has occurred: InvalidManifestError: 
=====> /builds/Q98qWn8u/0/michael/test/.ci-cache/pre-commit/repok8o7wel2/.pre-commit-hooks.yaml is not a file
Check the log at /builds/Q_5TAHoE/0/michael/test/.ci-cache/pre-commit/pre-commit.log
```

What appears to be the issue is that the gitlab runner may change the absolute path in the CI runner but the virtualenv or other info is being cached by the absolute path. It seems to me that the gitlab runner maintains a symlink to `/builds/<project_path>` but that the absolute path changes underneath it. This is using the gitlab kubernetes executor.

Any ideas how to mitigate this issue? I was hoping that `pre-commit run --all-files` would not fail here and rather would work relative to the XDG_CACHE_HOME folder or would delete the cache and reinstall maybe?

**Comment by asottile** [comment]
the pre-commit cache must stay at a constant location from when it is created -- if it gets moved all bets are off

**Comment by asottile** [comment]
but I suspect what your actual issue is would be your `cache: key:` which needs to be project-specific

**Comment by mmerickel** [comment]
Ok slow down for a second! I'm following the instructions here https://pre-commit.com/#gitlab-ci-example so I'm hoping at least we can figure out how to improve those - it probably shouldn't be closed quite yet. I know I tweaked a few things but:

1) The docs are not showing a comprehensive example showing how to install pre-commit and run it. Maybe I'm doing something wrong here.
2) I'm using the documented XDG_CACHE_HOME variable instead of PRE_COMMIT_HOME which should be fine.

**Comment by mmerickel** [comment]
As a general rule we like to cache things across branches so the cache key isn't typically a problem. I'm hoping that pre-commit could be resilient to this like other things we use. For example using the symlink'd path instead of the realpath? I haven't looked at pre-commit's code to sort out what's happening.

**Comment by asottile** [comment]
> I'm following the instructions here

you're not though -- yours is completely different!

> it probably shouldn't be closed quite yet

there's nothing actionable -- you need to adjust your cache scope as the docs indicate you should do

>  I'm hoping that pre-commit could be resilient to this like other things we use

it can't, hook environments are not relocatable

**Comment by mmerickel** [comment]
> you're not though -- yours is completely different!

In what way is it completely different so I can tweak and try it out? The example in the docs is not comprehensive. The XDG_CACHE_HOME is supported by pre-commit here https://pre-commit.com/#managing-ci-caches and the examples do not show how to install pre-commit. I'm using XDG_CACHE_HOME because it caches both `pip install` and pre-commit.

The default gitlab cache key is to cache across jobs/branches/etc which is the same as what I'm doing here with one minor distinction that is not relevant as I'm not changing the image between runs.

**Comment by mmerickel** [comment]
Looking further I can confirm gitlab is changing the absolute path in some (currently unknown) scenarios. pre-commit is storing those absolute paths in the sqlite database at `$XDG_CACHE_HOME/pre-commit/db.db` and I see entries from multiple absolute paths root paths. It'd be nice if pre-commit were more resilient to this but I'll see if I can find the reasons why gitlab-runner is changing the build paths as well.

It's worth noting as well that several of the repos stored in `db.db` are from old versions of the pre-commit dependencies and that the InvalidManifestError is related to one of the old ones. The Q_5TAHoE folder is new, and the error above in the original message I pasted was from Q98qWn8u. For example:

```
sqlite> select * from configs;
/builds/Q98qWn8u/0/michael/test/.pre-commit-config.yaml
/builds/Q_5TAHoE/0/michael/test/.pre-commit-config.yaml
sqlite> select * from repos;
https://github.com/pre-commit/pre-commit-hooks|v2.3.0|/builds/Q98qWn8u/0/michael/test/.ci-cache/pre-commit/repok8o7wel2
https://github.com/adrienverge/yamllint|v1.17.0|/builds/Q98qWn8u/0/michael/test/.ci-cache/pre-commit/repok6erd_dw
https://github.com/antonbabenko/pre-commit-terraform|v1.45.0|/builds/Q98qWn8u/0/michael/test/.ci-cache/pre-commit/repos71_txc0
https://github.com/psf/black|20.8b1|/builds/Q98qWn8u/0/michael/test/.ci-cache/pre-commit/repo16qow_33
https://github.com/pre-commit/pre-commit-hooks|v4.0.1|/builds/Q_5TAHoE/0/michael/test/.ci-cache/pre-commit/repowyzaz4ib
https://github.com/adrienverge/yamllint|v1.26.1|/builds/Q_5TAHoE/0/michael/test/.ci-cache/pre-commit/repo0oa_064o
https://github.com/antonbabenko/pre-commit-terraform|v1.50.0|/builds/Q_5TAHoE/0/michael/test/.ci-cache/pre-commit/repojfqsqupq
https://github.com/psf/black|21.7b0|/builds/Q_5TAHoE/0/michael/test/.ci-cache/pre-commit/repoxbrr130y
```

**Comment by mmerickel** [comment]
So the build folder prefix is due to sharing the cache across multiple runners which is supported in gitlab when using a shared runner cache in something like S3. The syntax is `{builds_dir}/$RUNNER_TOKEN_KEY/$CONCURRENT_ID/$NAMESPACE/$PROJECT_NAME`. I'll followup with gitlab and try to understand why the folder in the CI environment is not stable. I opened https://gitlab.com/gitlab-org/gitlab-runner/-/issues/28139 related to that.

**Comment by mmerickel** [comment]
Ultimately I apologize for the extra debugging in this ticket but I think there's still something to be done here.

For pre-commit the takeaway is that `pre-commit run --all-files` seems to be choosing to fail here because it has cached a now-invalid location. It seems to me that `pre-commit run --all-files` should not be erroring here and instead should be reinstalling the package into the new location. This feels like it's in the spirit of pre-commit in how it does not provide clear commands for uninstalling/reinstalling things from the cache and rather suggests simply letting `pre-commit run` sort things out.

**Comment by asottile** [comment]
I disagree, you're running in an unsupported way where you've changed the internals of the cache.  if you're redirecting the cache location it's on you to make sure that continues to work.

for example, if I went into system32 and deleted a random dll I wouldn't expect anything to work.

**Comment by mmerickel** [comment]
When you say "you" here are you suggesting that I'm doing something in my config or are you referring to the issues I've identified with the gitlab runner? To my knowledge I'm following the patterns in the pre-commit docs with respect to caching - I asked above for examples of things to tweak if the config contains something unsupported.

**Comment by mmerickel** [comment]
Here is an updated config that does work for gitlab on kubernetes/docker runners assuming `[runners.custom_build_dir] enabled = true` is set. I can contribute a PR improving those docs if that would be okay with you.

```yaml
pre-commit:
  image: python:3.9-buster
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_PROJECT_PATH
    XDG_CACHE_HOME: $CI_PROJECT_DIR/.ci-cache
    PYTHONUSERBASE: $CI_PROJECT_DIR/.ci-cache
  cache:
    # bust the cache if the python version changes
    key: ${CI_JOB_IMAGE}
    paths:
      - ${XDG_CACHE_HOME}
  before_script:
    - export PATH=${XDG_CACHE_HOME}/bin:$PATH
    - pip install --user -U pre-commit
  script:
    - pre-commit run --all-files
```
