### ISSUE TITLE
Run `--all-files` skips all hooks (no files to check)

### ISSUE THREAD

**Issue by russoale** [pre-commit/pre-commit#2017]
Hi,

I have a hard time to understand why my pre-commit hooks skip all files, see output:
```
╰─± pre-commit run --all-files
Check for merge conflicts............................(no files to check)Skipped
Check for added large files..........................(no files to check)Skipped
Check docstring is first.............................(no files to check)Skipped
Check JSON...........................................(no files to check)Skipped
Check Toml...........................................(no files to check)Skipped
Check Xml............................................(no files to check)Skipped
Check Yaml...........................................(no files to check)Skipped
Trim Trailing Whitespace.............................(no files to check)Skipped
Fix End of Files.....................................(no files to check)Skipped
Fix requirements.txt.................................(no files to check)Skipped
Don't commit to branch...................................................Passed
black................................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
pylint...............................................(no files to check)Skipped
```
`pre-commit 2.13.0`

So I actually did only add a new hook and wanted to run on all files. 
Am I doing something wrong ?

**Comment by asottile** [comment]
it's especially difficult to know when you haven't supplied your configuration -- I can't see your screen

**Comment by russoale** [comment]
Sorry, you are right. So our project structure looks like this

```
.github/
docs/
projects/
src/
tests/
```

Basically projects only contains a couple of notebooks. So I would like to use pre-commit in my CI by running it on src and tests.

```
default_language_version:
  python: python3

exclude: |
    (?x)^(
        projects|
        docs|
        build
    )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: no-commit-to-branch
        args: [--branch, master, --branch, beta, --branch, alpha, --branch, develop]

  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/pycqa/pylint
    rev: v2.9.6
    hooks:
      - id: pylint
        args: [ "src", "--rcfile=.pylintrc", "--exit-zero" ]
```

Thanks for your support.
