### ISSUE TITLE
Hook execution result is not the same as expected from command line

### ISSUE THREAD

**Issue by tkachenkomaria244** [pre-commit/pre-commit#2033]
Hook in .pre-commit-config.yaml:
repos:

```yaml
-   repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.6.4
    hooks:    
    -   id: sqlfluff-lint
        name: Check code convention errors
        files: (?i)([/]|\\)Views([/]|\\)\w*[.]sql$
        args: [--rules "L013,L016,L026,L027,L028"]
        args: [--format, yaml]
        additional_dependencies: ['git+https://fakename.com/sqlfluff_plugin_dma.git#egg=sqlfluff-plugin-DMA'].
```

Expected command to execute:
"sqlfluff lint --rules L013,L016,L026,L027,L028 --format yaml D:\fake_path\Views\v_v.sql"
But pre-commit hook execution result doesn't take into account parameter "args: [--rules "L013,L016,L026,L027,L028"].

If I execute "sqlfluff lint --rules L013,L016,L026,L027,L028 --format yaml D:\fake_path\Views\v_v.sql" on virtual env prepared by pre-commit all work as expected and parameter "args: [--rules "L013,L016,L026,L027,L028"] is processed correctly.

Please advise what can be the reason.
Thanks.
