### ISSUE TITLE
Support additional_dependencies with system hook?

### ISSUE THREAD

**Issue by peterjc** [pre-commit/pre-commit#2042]
Most of the hook languages are cross platform, but some may be operating system specific - particularly "system" hooks https://pre-commit.com/#system where for example using bash ought to work on Linux or macOS, but is unlikely to work on Windows.

One idea would be to be able to declare a dependency on the operating system, another would be for ``additional_dependencies: [...]`` to be interpreted as a list of executables on the ``$PATH`` as in this example - where the hook is skipped if a dependency is missing?:

```yaml
repos:
-   repo: local
    hooks:
    -   id: contrib-sorting
        name: Check sorting of contributor names
        entry: bash -c 'grep "^- " CONTRIB.rst | LC_ALL=C sort -u -c -f'
        language: system
        additional_dependencies: ['bash', 'grep', 'sort']
        files: ^CONTRIB\.rst$
```

Currently that is not supported:

```
[ERROR] The hook `contrib-sorting` specifies `additional_dependencies` but is using language `system` which does not install an environment.  Perhaps you meant to use a specific language?
```
