### ISSUE TITLE
Commandline Arguments to golang 

### ISSUE THREAD

**Issue by Nightreaver** [pre-commit/pre-commit#2051]
### describe your issue

I wanted to run a pre-commit hook with the golang extension, and I tried to add commandline arguments to the file that's going to get started.

I seems like whenever I do

```yaml
  entry: mygomod --set-true
  language: golang
```
Its been ignored, or am I doing it wrong?

### pre-commit --version

pre-commit 2.14.0

### .pre-commit-config.yaml

```yaml
---
repos:
  - repo: https://myrepo
    rev: b0846eeb27f0758fd5ef2ebba6f645e8d822a124
    hooks:
      - id: mygohook
```
