### ISSUE TITLE
commit-msg Hooks Crash On Aborted Commit

### ISSUE THREAD

**Issue by Kurt-von-Laven** [pre-commit/pre-commit#2052]
### describe your issue

1. `pre-commit install --hook-type commit-msg`
2. touch foo && git add foo && git commit
3. Save an empty commit message, aborting the commit.

[commitizen-tools/commitizen](https://commitizen-tools.github.io/commitizen/) and [gitlint](https://jorisroovers.com/gitlint/) crash for instance:

```
commitizen check..............................................................Failed
- hook id: commitizen
- exit code: 14

commit validation: failed!
please enter a commit message in the commitizen format.
commit "": "# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch initial-version
#
# Changes to be committed:
#       ...
pattern: (build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(\(\S+\))?!?:(\s.*)


gitlint.......................................................................Failed
- hook id: gitlint
- exit code: 2

1: T8 Title is too short (0<5)
3: B6 Body message is missing
```

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.18.1
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.1
    hooks:
      - id: gitlint
```

### ~/.cache/pre-commit/pre-commit.log (if present)
(not present)
