### ISSUE TITLE
files are (wrongfully?) skipped on git rebase --continue with post-rewrite hooks

### ISSUE THREAD

**Issue by christian-steinmeyer** [pre-commit/pre-commit#2060]
### describe your issue

We're experimenting with a new approach that uses `git rebase` to directly address issues of a PR and change the original commit. In that context, I've ran
- `git rebase <SHA>`
- mark some commits with `edit`
- git stops the rebase for editing
- do some changes (that don't comply with my post-rewrite hooks)
- `git add <FILE>`
- `git rebase --continue`

I expected this to fail as the changes I've made do not satisfy the hooks. 
While the hooks are triggered, they are skipped as the file does not seem to be picked up as changed by pre-commit (`(no files to check)Skipped`).

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
default_stages:
  - commit
  - post-rewrite

repos:
  # general file format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
```
