### ISSUE TITLE
[WARNING] Unexpected key(s) present at root: ci

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#2064]
### describe your issue

Running pre-commit on a repository that has "ci:" block configured inside `.pre-commit-config.yaml` does produce undesired runtime warning.

```
[WARNING] Unexpected key(s) present at root: ci
```

While I can understand that this feature proved very useful for spotting typos in config, the introduction of "ci" options did make it bit spammy.

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
ci:
  # format compatible with commitlint
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  autoupdate_schedule: monthly
repos:
  ...
```
