### ISSUE TITLE
`default_stages` in config yaml doesn't overrride `stages` in hooks yaml

### ISSUE THREAD

**Issue by scop** [pre-commit/pre-commit#2076]
### describe your issue

The [`stages`](https://pre-commit.com/#hooks-stages) defined in the `.pre-commit-hooks.yaml` that defines a hook can be overridden by the user by specifying `stages` for the hook in their '.pre-commit-config.yaml`. This is good.

However, the user override does not happen if the user configures `default_stages` in their config; in that case the stages defined in the hook's yaml prevails. I think this is not what should happen; instead `default_stages` specified by user should override `stages` specified in hook's yaml, just like a per hook `stages` in config yaml does.

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
default_stages: [commit]  # does not override .pre-commit-hooks.yaml defined stages: [commit-msg] for somehook below # crafted example, for illustration only

repos:
  - repo: https://example.com/some/hook
    rev: x
    hooks:
      - id: somehook
        # defining stages: here _would_ override stages from somehook's .pre-commit-hooks.yaml
```
