### ISSUE TITLE
autoupdate does not update additional_dependencies (e.g. blacken-docs & black)

### ISSUE THREAD

**Issue by peterjc** [pre-commit/pre-commit#2082]
### describe your issue

Issues noticed in https://github.com/biopython/biopython/pull/3758 and similar, locally:

```
$ pre-commit autoupdate
Updating https://github.com/pre-commit/pre-commit-hooks ... already up to date.
Updating https://github.com/psf/black ... [INFO] Initializing environment for https://github.com/psf/black.
updating 21.7b0 -> 21.9b0.
Updating https://gitlab.com/pycqa/flake8 ... already up to date.
Updating https://github.com/asottile/blacken-docs ... updating v1.10.0 -> v1.11.0.
Updating https://github.com/myint/rstcheck ... 
=====> /Users/pc40583/.cache/pre-commit/repo6_ob7tr9/.pre-commit-hooks.yaml is not a file
Updating https://github.com/PyCQA/doc8 ... [INFO] Initializing environment for https://github.com/PyCQA/doc8.
updating 0.9.0 -> 0.9.1.
Updating https://github.com/codespell-project/codespell ... already up to date.
```

Yet:

```
$ git diff
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index f8f1b5c23..a815fc3ca 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -15,7 +15,7 @@ repos:
         files: \.py$
     -   id: mixed-line-ending
 -   repo: https://github.com/psf/black
-    rev: 21.7b0
+    rev: 21.9b0
     hooks:
     -   id: black
         args: [--check]
@@ -33,7 +33,7 @@ repos:
             'pydocstyle>=6.0.0',
         ]
 -   repo: https://github.com/asottile/blacken-docs
-    rev: v1.10.0
+    rev: v1.11.0
     hooks:
     -   id: blacken-docs
         additional_dependencies: [black==21.7b0]
@@ -44,7 +44,7 @@ repos:
     -   id: rstcheck
         args: [--report=warning]
 -   repo: https://github.com/PyCQA/doc8
-    rev: 0.9.0
+    rev: 0.9.1
     hooks:
     -   id: doc8
         additional_dependencies: [pygments]
```

To make that clearer:

```
$ grep -A 1 black .pre-commit-config.yaml 
-   repo: https://github.com/psf/black
    rev: 21.9b0
--
    -   id: black
        args: [--check]
--
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
--
    -   id: blacken-docs
        additional_dependencies: [black==21.7b0]
        exclude: ^.github/
```

i.e. The top level black hook was updated from 21.7b0 to 21.9b0, but not the ``additional_dependencies`` entry for blacken-docs

### pre-commit --version

pre-commit 2.13.0

### .pre-commit-config.yaml

```yaml
# See CONTRIBUTING.rst, we expect this to be run via a git pre-commit hook.
# You can also run the checks directly at the terminal, e.g.
#
# $ pre-commit run --all-files
#
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-executables-have-shebangs
        files: \.(py|sh)$
    -   id: check-json
    -   id: debug-statements
    -   id: end-of-file-fixer
        files: \.py$
    -   id: mixed-line-ending
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    -   id: black
        args: [--check]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-blind-except',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-docstrings',
            'flake8-implicit-str-concat',
            'flake8-rst-docstrings>=0.2.3',
            'pydocstyle>=6.0.0',
        ]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==21.7b0]
        exclude: ^.github/
-   repo: https://github.com/myint/rstcheck
    rev: 3f92957478422df87bd730abde66f089cc1ee19b
    hooks:
    -   id: rstcheck
        args: [--report=warning]
-   repo: https://github.com/PyCQA/doc8
    rev: 0.9.1
    hooks:
    -   id: doc8
        additional_dependencies: [pygments]
        args: [--quiet,--ignore-path=Doc/examples/ec_*.txt, --ignore=D004]
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
        files: \.(rst|md|tex)$
        args: [
            --ignore-regex,
            '(^|\W)([A-Z]{2,3})(\W|$)',
            -L,
            'ser,hsa,hist,fpr'
        ]
-   repo: local
    hooks:
    -   id: doi-link-style
        name: Enforce https://doi.org/ style
        description: Check DOI link style, see https://www.crossref.org/display-guidelines/
        entry: '(?i)(doi:|dx\.doi\.org|http://doi\.org)'
        language: pygrep
        files: \.(rst|tex)$
ci:
    # Settings for the https://pre-commit.ci/ continuous integration service
    autofix_prs: false
    # Default message is more verbose
    autoupdate_commit_msg: '[pre-commit.ci] autoupdate'
    # Default is weekly
    autoupdate_schedule: quarterly
    # Currently pre-commit.ci checks all files, and flake8 takes too long
    # and causes a timeout - so as a short-term workaround, skip it:
    skip: [flake8]
```
