### ISSUE TITLE
Pass additional arguments via command line

### ISSUE THREAD

**Issue by twodayslate** [pre-commit/pre-commit#2083]
I do not think it is currently possible to pass additional arguments to an entry via the command line.

For example if I have the following `.pre-commit-config.yaml`:
```
repos:
- repo: local
  hooks:
    - id: custom-linter
      name: My Custom Linter
      entry: my-custom-linter arg1 arg2
      language: system
      types: [text]
```
`my-custom-linter arg1 arg2` is then run when the `custom-linter` hook runs. 

If hook fails for whatever reason I would then like to run `pre-commit run custom-linter -- additional_arg` (or similar) which would run `my-custom-linter arg1 arg2 additional_arg`
