### ISSUE TITLE
Whats the best way to use credentials

### ISSUE THREAD

**Issue by svramusi** [pre-commit/pre-commit#2088]
### describe your issue

What's the correct way to store/use credentials? I need to use my email address and api-key to access artifactory for the pip-compile hook and certainly can't commit them.

### pre-commit --version

6.3.0

### .pre-commit-config.yaml

```yaml
- repo: https://github.com/jazzband/pip-tools
  rev: 6.3.0
  hooks:
    - id: pip-compile
      name: pip-compile setup.py
      files: ^(setup\.py|requirements\.txt)$
      args: [
        -i,
        "https://{email-address}:{api-key}@artifactory-url/api/pypi/pypi/simple",
        --no-emit-index-url,
        --output-file=requirements.txt
      ]
```
