### ISSUE TITLE
Skipped hook

### ISSUE THREAD

**Issue by LouisNoailles** [pre-commit/pre-commit#2090]
### describe your issue

Hi,
I am trying to use this repo with `pre-commit` but when I use it to check my code format, it apply modification and I want to not commit them directly.

My repo with staged changes before format looks like this with `git status`:
```
$ git status     
On branch <branch-name>
Your branch is ahead of 'origin/<branch-name>' by 1 commit.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   tests/test_commands.rs
```

and commiting leads to this:
```
$ git commit -m "test"
Formatting source files
Formatting done, changed files: tests/test_commands.rs
fmt..................................................(no files to check)Skipped
[<branch-name> <commit-hash>] test
```
And the file  is modified by the formatter which is not what I expect.

I would have it to fail to commit and having a status like this:
```
$ git status     
On branch 209-add-cargo-fmt-to-git-hooks-pre-commit
Your branch is ahead of 'origin/<branch-name>' by 1 commit.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   tests/test_commands.rs

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	tests/test_commands.rs
```

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
        name: fmt
        description: Format files with cargo fmt.
        entry: cargo fmt --
        language: system
        types: [rust]
        args: ["--", "--check"]
```
Using the `check` argument prevent the modification of the file which makes it event more frustrating and is not what I want to do.

I want it to make unstaged changes to the file that I can `add` and then `commit`.
