### ISSUE TITLE
procedure to make init.templatedir for automatic enable of pre-commit fails on Cygwin due to path formats

### ISSUE THREAD

**Issue by moschlegel** [pre-commit/pre-commit#2100]
### describe your issue

When I run the automatic enable procedure with pre-commit version 2.15.0 to automate enabling of pre-commit:
(see [automatically enabling pre-commit on repositories](https://pre-commit.com/#automatically-enabling-pre-commit-on-repositories)  )

```
pre-commit init-templatedir ~/.git-template

pre-commit installed at /cygdrive/c/Users/username/.git-template\hooks\pre-commit
```
The "pre-commit init-templatedir ~/.git-template" command fails with no error message but the ~/.git-template does not become populated with the hooks/ dir and the pre-commit file

It seems to interpret that since the OS is Windows it should use backspaces. But since the environment is Cygwin it should have really used path:
/cygdrive/c/Users/username/.git-template/hooks/pre-commit
or possibly doubled backslashes so one would be lost due to escaping and would leave a single backslash
/cygdrive/c/Users/username/.git-template\\hooks\\pre-commit

Request:   Have pre-commit detect "Cygwin" case and use a cygwin compatible path when loading the ~/.git-template/hooks/pre-commit

### pre-commit --version

2.15.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
    # default maxkb is 500
    args: ['--maxkb=1000']
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-yaml
  - id: mixed-line-ending
  - id: no-commit-to-branch
    args: ['--pattern', '^build[0-9]+\.[0-9]+(\.[0-9]+)?/test_team/main$' ]
  - id: trailing-whitespace
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.5
  hooks:
  - id: forbid-binary
    exclude: .*\.jar
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.10
  hooks:
  - id: forbid-tabs
  - id: remove-crlf
```
