### ISSUE TITLE
Set hook-level environment variables

### ISSUE THREAD

**Issue by jkopczyn** [pre-commit/pre-commit#2101]
(`pre-commit 2.9.3`)

My project uses pre-commit to run tests, of several varieties. Some of these should run in different environments; for example, we have a local DB for testing purposes, and want `pytest` to run against that for unit tests and integration tests, but not for end-to-end tests, which should use the real DB. For non-automated use, we do this with
```python
$ stage=local pytest -m "unit or integration"
$ pytest -m "end-to-end"
```
It is *possible* to emulate this within precommit, e.g.
```yaml
      - id: tests                                                                   
        name: Unit tests
        entry: sh -c "stage=local pytest -m \"unit\" --durations=25 --durations-min=1.0"
        language: system
        always_run: true
        pass_filenames: false
        stages: [push]
      - id: endtoend                                                                   
        name: Unit tests
        entry: pytest -m "end_to_end" --durations=25 --durations-min=1.0
        language: system
        always_run: true
        pass_filenames: false
        stages: [push]
```
but this is brittle; it would be much better to have
```yaml
      - id: tests                                                                   
        name: Unit tests
        environment:
                stage=local
        entry: pytest -m "unit" --durations=25 --durations-min=1.0
        language: system
        always_run: true
        pass_filenames: false
        stages: [push]
      - id: endtoend                                                                   
        name: Unit tests
        entry: pytest -m "end_to_end" --durations=25 --durations-min=1.0
        language: system
        always_run: true
        pass_filenames: false
        stages: [push]
```
or something like that. Is this possible? I see #758, but that covers installation and it specifically mentions that runtime would be different, but not (AFAICT) how it would differ.
