### ISSUE TITLE
Having trouble with `git push --tags`

### ISSUE THREAD

**Issue by ihincks** [pre-commit/pre-commit#2107]
### describe your issue

I have configured a hook to be run on pre-push. When performing normal non-empty pushes with `git push`, the hook runs properly. However, pushes with only simple tags do not trigger the hook, which is unexpected from my perspective:

```yaml
git tag simple_version
git push --tags
```

I have verified that the auto-generated `.git/hooks/pre-push` script is actually being run in this case by prepending with a python raise.

### pre-commit --version

2.15.0

### .pre-commit-config.yaml

```yaml
repos:
    - repo: local
      hooks:
          - id: check-version
            always_run: true
            entry: python hooks/check_version.py
            language: python
            name: check version consistency
            stages: [push]
```
