### ISSUE TITLE
Multiline Regular Expression failing to match correctly

### ISSUE THREAD

**Issue by pzelnip** [pre-commit/pre-commit#2110]
### describe your issue

Following the instructions at https://pre-commit.com/#regular-expressions I tried creating a verbose multiline regex to match both a directory and a specific file for a hook.   My pre-commit yaml file:

```
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
                project/static/common/somedir/|
                project/static/common/aspecificfile.js
            )$
```

In this project I have a file at `project/static/common/somedir/somefile.js`, which I'd expect to be excluded, but running pre-commit seems to match it:

```
$ pre-commit run --all-files
Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing project/static/common/somedir/somefile.js
```

Changing the pre-commit to not do a multiline regex seems to work, ie if I change the yaml to:

```
        exclude: project/static/common/somedir/|project/static/common/aspecificfile.js
```

It successfully excludes both clauses:

```
$ pre-commit run --all-files
Fix End of Files.........................................................Passed
```

I have a repo set up with this at: https://github.com/pzelnip/pre-commit-test

Not sure what I'm doing wrong.

### pre-commit --version

pre-commit 2.12.1

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
                project/static/common/somedir/|
                project/static/common/aspecificfile.js
            )$
```

### ~/.cache/pre-commit/pre-commit.log (if present)

```
$ cat ~/.cache/pre-commit/pre-commit.log
cat: /Users/adam.parkin/.cache/pre-commit/pre-commit.log: No such file or directory
```
