### ISSUE TITLE
pre-commit autoupdate not picking latest flake8 since master -> main

### ISSUE THREAD

**Issue by lafrech** [pre-commit/pre-commit#2112]
### describe your issue

    $ pre-commit autoupdate
    Updating https://gitlab.com/pycqa/flake8 ... updating 4.0.1 -> 3.9.2.

4.0.1 is indeed latest tag as of today: https://github.com/PyCQA/flake8/tags

    $ pre-commit autoupdate --bleeding-edge
    Updating https://gitlab.com/pycqa/flake8 ... [INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
    updating 3.9.2 -> 21d3c70d676007470908d39b73f0521d39b3b997.

21d3 is not the latest commit either, it is in fact the last commit before master -> main.

Looks like I might have just found an explanation but I can't tell whether this is an issue with pre-commit or with the flake8 repo (or with me...).

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.29.0
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/python/black
  rev: 21.9b0
  hooks:
  - id: black
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear>=21.4.3]
- repo: https://github.com/asottile/blacken-docs
  rev: v1.11.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==21.9b2]
```
