### ISSUE TITLE
[QUESTION] ``additional_dependencies`` and current project extras

### ISSUE THREAD

**Issue by s0undt3ch** [pre-commit/pre-commit#2113]
### describe your issue

I there a way to install the project's extras for which pre-commit is running against?

I have a pylint step on my pre-commit config, however, the current project's ``dev`` and ``tests`` dependencies don't seem to be getting installed since I'm getting this from pylint
```
Lint Test Suite..............................................................Failed
- hook id: pylint
- duration: 1.19s
- exit code: 2

************* Module tests.conftest
tests/conftest.py:6: [E0401(import-error), ] Unable to import 'pytest'
tests/conftest.py:7: [E0401(import-error), ] Unable to import 'saltfactories.utils'
```

Is there a workaround this, besides keeping the dependencies in sync on both `setup.cfg` and `.pre-commit-config.yml`?

### pre-commit --version

2.15.0

### .pre-commit-config.yaml

```yaml
- repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a4
    hooks:
      - id: pylint
        name: Lint Code
        args: [
          '--output-format=parseable',
          '--rcfile=.pylintrc',
        ]
        files: ^tests/.*\.py$
        exclude: saf/version.py
        additional_dependencies:
          - .[dev,tests]
          - pyenchant
```
