### ISSUE TITLE
Dry run mode (printing warning vs. interrupting the commit)

### ISSUE THREAD

**Issue by jmcazaux** [pre-commit/pre-commit#2123]
### describe your issue

I have not found a way to have hooks running in _dry run_ mode (i.e. printing warnings vs. interrupting the commit).

It can be useful when you are about to enforce _something_ but want to provide a buffer before doing so.

The issue is that it seems it is not possible to keep the output of a hook unless it returns 1 (which then interrupts the commit).

### pre-commit --version

2.15.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: ../pre-commit-hooks
  rev: b38bb29611d1a255366530c21efa5f1409a65f87
  hooks:
  - id: check-branch-name
```
