### ISSUE TITLE
Local entry with relative path attempts using /bin/sh in powershell

### ISSUE THREAD

**Issue by Nieju** [pre-commit/pre-commit#2124]
### describe your issue

Local hook attempts to use `/bin/sh` with `unix` like relative path on windows with powershell.

`entry: ./gradlew test` will fail with the error `/bin/sh` not found when run within `powershell`.
Running `./gradlew test` from `powershell` works fine

### pre-commit --version

2.15.0

### .pre-commit-config.yaml

```yaml
- repo: local
    hooks:
      - id: gradle-test
        name: unittests
        description: Runs unit tests with gradle
        entry: ./gradlew test
        pass_filenames: false
        language: system
```
