### ISSUE TITLE
Does it clash when you use black and isort together?

### ISSUE THREAD

**Issue by vvanglro** [pre-commit/pre-commit#2130]
### describe your issue

When both are used together they trigger a formatting alert every time
When I get rid of one of them it's fine

### pre-commit --version

2.15.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
    - id: python-no-print
      name: check for print()
      description: 'A quick check for the `print()` built-in function'
      entry: '\bprint\('
      language: pygrep
      types: [python]
      exclude: ^scripts/
  - repo: https://hub.fastgit.org/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys", "--no-ensure-ascii", "--indent", "2"]
  - repo: https://hub.fastgit.org/psf/black
    rev: 21.5b1
    hooks:
      - id: black
  - repo: https://hub.fastgit.org/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
  - repo: https://hub.fastgit.org/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--max-line-length=120, --ignore=F632 W503]
  - repo: https://hub.fastgit.org/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
```

**Comment by asottile** [comment]
sounds like you've misconfigured `isort` -- check their documentation

**Comment by asottile** [comment]
or if you want a different sorter which is compatible out of the box: https://github.com/asottile/reorder_python_imports

**Comment by ksdaftari** [comment]
@vvanglro believe you need to configure isort to use profile = "black" as talked about integration with pre-commit at bottom of https://pycqa.github.io/isort/docs/configuration/black_compatibility.html

**Comment by vvanglro** [comment]
> @vvanglro believe you need to configure isort to use profile = "black" as talked about integration with pre-commit at bottom of https://pycqa.github.io/isort/docs/configuration/black_compatibility.html

thx
Yes, it will be solved after adding the configuration.

```yaml
hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
```
