### ISSUE TITLE
Question: are you open to have pre-commit fetch the rev from poetry.lock?

### ISSUE THREAD

**Issue by fredrikaverpil** [pre-commit/pre-commit#2131]
Hi @asottile !

I'm trying to get pre-commit to fly alongside poetry at work. I'd love to avoid manually keeping the `rev` in the `.pre-commit-config.yml` file in sync with whatever is in poetry's `poetry.lock` file. I'm thinking instead have pre-commit somehow read the package version from the `poetry.lock` file.

I take it this is not possible today (?) and I was wondering if you are open to this idea. If so, I could help see if maybe I can implement that.

Perhaps the rev could be fetched from an arbitrary file (such as `poetry.lock`, `Pipfile.lock`, `requirements.txt` and so on). And using e.g. regex the rev could be extracted from that file and used by pre-commit.

Let me know what you think.
Anyway, thanks for all your great work, as always! 😃

**Comment by asottile** [comment]
I am not

**Comment by asottile** [comment]
but you can write a hook which does what you want

**Comment by alanwilter** [comment]
Do we have anything new on this topic? I'm really keen to use `pre-commit` but I won't if I have to keep looking at `rev`.

`poetry` does the requirements maintenance already. So, did someone come out with hook for that? If not, could you @asottile tell me more how I could create such hook?

**Comment by alanwilter** [comment]
Never mind what I said, I found about `repo: local`, it's perfect.

```yaml
repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true
    -   id: black
        name: black
        entry: black --diff --check .
        language: system
        types: [python]
        require_serial: true
```

**Comment by asottile** [comment]
and by perfect you've:

1. missed the point of pre-commit, now a contributor needs to globally install and manage linters and their versions
2. introduced several subtle bugs, for instance you're double-formatting every file

but if that's what you want to do, `language: system` and `repo: local` are the escape hatch to do whatever you want

**Comment by alanwilter** [comment]
I see your point but I disagree about (1), if using `poetry`, contributor will have to use it. Or should I do:

```yml
repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: poetry run flake8
...
 ```
?

For (2), I admit I've just found out about `pre-commit` today, so I'm very green and I don't know what do you mean by 

> double-formatting every file

Would please enlighten me?

**Comment by asottile** [comment]
(1) now you would require `poetry` everywhere for (2) your configuration is malformed -- which wouldn't happen if you use the upstream configuration

generally the point of pre-commit is that it runs and manages your linters so you don't need to install and manage them elsewhere (there's no point in having them in poetry *and* pre-commit, pick one or the other)

**Comment by alanwilter** [comment]
I still fail to see your point. Your `pre-commit` does solve a huge issue I have with some contributors that don't have their IDE setup with black and flake8 (like I do with my VSCode but they use e.g. Atom and don't seem to know how to setup). So they commit only to find out that GitHub action failed the lintering stages...
And I won't give up `poetry`, as it manages very well my dependencies and devdependencies. 

For (2), I use [YAML VSCode extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml). So I don't even have any say in the formatting and I happy with that.

That's the format I have now. Perhaps I have pasted the ones above from an example I got elsewhere.
```yaml
repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
```
Anyway, a huge thanks to you for providing `pre-commit`.
