### ISSUE TITLE
[Feature Request]: Show aliases (`--show-aliases`)

### ISSUE THREAD

**Issue by diegovalenzuelaiturra** [pre-commit/pre-commit#2142]
Hello!

In the `alias` I usually include useful information, using prefixes such as `check_`, `fix_`, etc, or even more self-explanatory (easier to remember) names than hooks `id`s - So I think allowing `aliases` to be displayed when running `pre-commit` would be very useful.

* Example configuration file
```yaml
# .pre-commit-config.yaml

# Actions that check things are executed first than actions that modify things.
# So, we make sure that the 'pre-commit' stops running the hooks after the first failure.
fail_fast: true

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        alias: check-imports-order
        args: [--jobs=8, --check]
      - id: isort
        alias: sort-imports
        args: [--jobs=8]
```

- Current behavior:
```bash
# pre-commit run --all-files
isort ................................................................Passed
isort ................................................................Passed
```

- Requested behavior:
```bash
# pre-commit run --all-files --show-aliases
isort [check-imports-order] ..........................................Passed
isort [sort-imports] .................................................Passed
```
