### ISSUE TITLE
Run hook only if specific files has changed

### ISSUE THREAD

**Issue by brendalf** [pre-commit/pre-commit#2146]
Hi, folks!
On GitLab, we have a feature that runs a ci/cd job only if certain files changed.
For example:
```
validate_config:
  stage: build
  script:
    - make validate_config
  only:
    refs:
      - master
    changes:
      - config.toml

```
I want to execute this verification whenever the developer makes a commit changing this file.
Do we have a feature similar to this inside pre-commit? I couldn't find it on the docs.

For now, the pre commit is running a make rule that checks (with `git diff`) if the file has changed before running the script.

If we don't have this feature, I would like to work on this if you all agree that is a nice to have feature.
