### ISSUE TITLE
Question: how to handle partial commits?

### ISSUE THREAD

**Issue by jenstroeger** [pre-commit/pre-commit#2148]
### describe your issue

So, I’m a little befuddled at the moment because I’m trying to understand what exactly is going on with pre-commit.

In my playground repo I’ve added Python [type stubs](https://mypy.readthedocs.io/en/stable/stubs.html) and these new `.pyi` files are staged together with the occasional related `.py` file. I also have pre-commit hooks for `pylint` and `mypy` configured.

When I run `git commit` then the hooks run on the _staged_ files, in which case `pylint` flags two files with
```
src/orm/meta.py:1:0: R0801: Similar lines in 2 files
==orm.meta:[6:72]
==orm.meta:[6:72]
```
which are the two that have both `.py` and `.pyi` staged! And `mypy` flags
```
src/orm/meta.py: error: Duplicate module named "orm.meta" (also at "src/orm/meta.pyi")
```
which is one of the these two. That same behavior is reproducible when I run `pre-commit run`.

However, when I run `pre-commit run --all-files` (i.e. not only staged files) then the `pylint` error disappears and the `mypy` error changes to a different file (same complaint, though) which has _only_ the `.pyi` file staged.

Finally, when I run `pylint` and `mypy` manually, none of the issues are flagged and the code is clean. In that case I think (🤞🏼) I have used the same command-line args but I realize that the context environment is different compared to running pre-commit (which runs [hooks in their own environment](https://pre-commit.com/#pre-commit-install-hooks)).

What’s the recommended way forward, here:
 - `git --no-verify commit` feels a bit naughty and I worry that subsequent commits may break because this one wasn’t actually clean; or
 - `SKIP=mypy,pylint git commit` and [temporarily disabling](https://pre-commit.com/#temporarily-disabling-hooks) also feels hackish but given the staged files may be the correct way of going about this?

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.9
default_stages: [commit]

repos:

  # Commitizen enforces semantic and conventional commit messages.
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Sort imports.
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  # Add Black code formatters.
  - repo: https://github.com/ambv/black
    rev: 21.11b1
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.0
    hooks:
      - id: blacken-docs
        args: [--line-length, "120"]
        additional_dependencies: [black==21.11b1]

  # Upgrade and rewrite Python idioms.
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        files: ^src/orm/|^tests/|setup.py
        args: [--py39-plus]

  # Similar to pylint, with a few more/different checks.
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      files: ^src/orm/|^tests/|setup.py
      additional_dependencies: [flake8-builtins==1.5.3,flake8-docstrings==1.6.0,flake8-pyi==20.10.0,flake8-rst-docstrings==0.2.3,pep8-naming==0.12.1]

  # Run Pylint from the local repo to make sure venv packages
  # specified in setup.py are available.
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        files: ^src/orm/|^tests/|setup.py
        args: []

  # Type-check all Python code.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        files: ^src/orm/|^tests/|setup.py
        additional_dependencies: [hypothesis==6.21.6,types-setuptools==57.4.0,"sqlalchemy[mypy]==1.4.26"]
        args: [--ignore-missing-imports, --config-file, mypy.ini]

  # Enable a whole bunch of useful helper hooks, too.
  # See https://pre-commit.com/hooks.html for more hooks.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]

  # On push to the origin, run the unit tests.
  - repo: local
    hooks:
    - id: tox
      name: tox
      entry: tox
      language: python
      verbose: true
      always_run: true
      pass_filenames: false
      stages: [push]
```
