### ISSUE TITLE
Get cache path of hook repo

### ISSUE THREAD

**Issue by janosh** [pre-commit/pre-commit#2159]
`pre-commit` stores the repos it installs in `.cache/pre-commit` but the subdirectories don't have descriptive names:

```
drwx------   18 janosh  staff   576B Nov 20 09:47 repor1u0rb7q
drwx------   11 janosh  staff   352B Dec 12 18:38 repory1ba9fw
drwx------   11 janosh  staff   352B Sep 19 07:24 reporyt4q41t
drwx------   10 janosh  staff   320B Nov 21 08:34 repos6xj2mfy
drwx------   15 janosh  staff   480B Nov 24 10:46 repoty4mktj6
drwx------   10 janosh  staff   320B Oct  5 17:02 repou8q9peht
drwx------   26 janosh  staff   832B Sep 15 07:50 repou9tzzobe
...
```

If I wan't to manually inspect the files `pre-commit` uses for a given hook, how can I get the directory corresponding to a particular hook?

**Comment by asottile** [comment]
this is intentionally implementation detail

you should not touch those

**Comment by janosh** [comment]
I need this for debugging.

**Comment by asottile** [comment]
describe your actual issue?

**Comment by janosh** [comment]
Trying to figure out why `mirrors-eslint` appears to be having trouble using `@typescript-eslint/eslint-plugin` correctly when specified as additional dep. My `eslint` hook config is

```yml
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.3.0
    hooks:
      - id: eslint
        types: [file]
        files: \.(svelte|js|ts)$
        additional_dependencies:
          - eslint
          - svelte
          - typescript
          - eslint-plugin-svelte3
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'
```

As shown in this screen recording, `eslint` is unable to parse Svelte files. The odd thing is by renaming (or deleting) `@typescript-eslint` from `node_modules`, it works as expected:

```sh
mv site/node_modules/@typescript-eslint{-tmp,}
```

https://user-images.githubusercontent.com/30958850/145854424-1fcc3663-c4a8-4dc6-a536-5f69ee972303.mp4
