### ISSUE TITLE
Conda | Activate environment for hooks

### ISSUE THREAD

**Issue by igaloly** [pre-commit/pre-commit#2160]
### describe your issue

I want that all of my hooks will run under some specific environment.
Currently, i run `conda run -n service-development` before each command.
I'de like a more "beautiful way" to perform this.

### pre-commit --version

2.7.1

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    # -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: isort
        name: sort imports
        entry: conda run -n service-development isort --filter-files
        language: conda
        types: [python]
    -   id: black
        name: black
        entry: conda run -n service-development black
        language: conda
        types: [python]
    -   id: flake8
        name: flake8
        entry: conda run -n service-development flake8
        language: conda
        types: [python]
    -   id: mypy
        name: mypy
        entry: conda run -n service-development mypy
        language: conda
        types: [python]
```
