### ISSUE TITLE
No support for multi-user environments or non-local home directories

### ISSUE THREAD

**Issue by lbreitk** [pre-commit/pre-commit#2162]
### describe your issue

Upon trying to configure and use pre-commit, I ran into a few issues:
- it defaults to using `~/.cache/pre-commit` - all of our users use LDAP accounts with nfs-mounted home directories. Upon using `strace`, it seems to hang upon trying to get a file lock, and not even a `CTRL+C` will get the session back, I have to completely exit the ssh session
- I have repositories on servers with multiple users using a single repository - this means that if I had 10 users working on a repository in a server, that I now have 10 duplicates of the data, when it could just be a single directory - which leads to the next problem
- When I set an environment variable to use the directory `/srv/repository/.cache/pre-commit`, I then found that many of the files and directories are set to user read only, meaning I now have to add code to automatically change the permissions periodically so that other users will be able to use the same cache and take advantage of `pre-commit`
- even after setting the cache directory to `/srv/repository/.cache/pre-commit`, when pre-commit is first run by an LDAP user, it still hangs. Usage of `strace`, `ps`, and `lsof` reveal that it's trying to access `~/.local/share/virtualenv`, which is still on a network mount, and thus hangs. 

I looked at the website, and read through the github issues and haven't found any solutions.

### pre-commit --version

2.16.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-toml
      - id: fix-encoding-pragma
      - id: requirements-txt-fixer

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v5.3.1  # put latest release tag from https://github.com/ansible-community/ansible-lint/releases/
    hooks:
      - id: ansible-lint
```
