### ISSUE TITLE
Mypy runs on all files of a project

### ISSUE THREAD

**Issue by aleksandrinvictor** [pre-commit/pre-commit#2165]
I am trying to run mypy only for commited files but it runs on all files of a project.
![image](https://user-images.githubusercontent.com/23315693/146910364-a8e8e08e-1f7d-430b-9f73-496ce15f4478.png)

### pre-commit --version

pre-commit 2.16.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: meta
  hooks:
  - id: identity
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: requirements-txt-fixer
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    args: ["--config-file=mypy.ini"]
- repo: https://github.com/pycqa/isort
  rev: 5.5.2
  hooks:
  - id: isort
    args: ["--profile", "black"]
- repo: https://github.com/psf/black
  rev: 21.8b0
  hooks:
    - id: black
      language_version: python3.9
      args: [--line-length=120]
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
```
