### ISSUE TITLE
Local pre-commit hook for Rust dependency stylua results in "Executable `stylua` not found"

### ISSUE THREAD

**Issue by rouge8** [pre-commit/pre-commit#2171]
## describe your issue

Local pre-commit hook for Rust dependency stylua results in "Executable stylua not found". 

## pre-commit --version

pre-commit 2.16.0

## .pre-commit-config.yaml

```yaml
---
repos:
  - repo: local
    hooks:
      - id: stylua
        name: StyLua
        language: rust
        additional_dependencies: [stylua:0.11.2]
        entry: stylua
        types: [lua]
```

## ~/.cache/pre-commit/pre-commit.log (if present)

n/a
