### ISSUE TITLE
First-class Podman support

### ISSUE THREAD

**Issue by MLNW** [pre-commit/pre-commit#2173]
### describe your issue

Especially since the license/usage changes to Docker this year, it is evident that other virtualization tools will be used more often.

I for one have been replacing Docker with Podman for a long time now.
It would be great if it could also gain first-class support in pre-commit.

Since it is a drop-in replacement for Docker it would be great if the `docker` and `docker_image` languages could also be used when there is no docker but only podman installed.

The current workaround is to add a script to the path called `docker` that just forwards all CLI parameters to podman.
Something along the lines of:
```bash
# In /usr/bin/docker
#!/usr/bin/sh
exec /usr/bin/podman "$@"
```

### pre-commit --version

pre-commit 2.16.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: local
    hooks:
      - id: vale
        name: Validate Style Guide with Vale
        description: Validate Style Guide with Vale
        language: docker_image
        entry: docker.io/jdkato/vale
        pass_filenames: true
        always_run: false
        verbose: true
        require_serial: false
```
