### ISSUE TITLE
Hook for Post-Merge stage when a file changes does not work

### ISSUE THREAD

**Issue by fran-martin** [pre-commit/pre-commit#2174]
### describe your issue

I created a local hook that is run at `post-merge` stage and executes `pipenv install` if the `Pipfile` changes.

Below is my `.pre-commit-config.yaml` that might interact when I execute `git merge <pipfile_changed_branch>` where that branch contains new changes for the `Pipfile`.

The thing that I've been playing around with the `stages` and for the `commit` stage, this works perfectly.

`pre-commit` is installed in a Python environment using `pipenv` and listed in the `[packages]` section of the `Pipfile`.

Am I missing something?

### pre-commit --version

pre-commit 2.16.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: local
  hooks:
    - id: pipenv-install
      stages: [post-merge]
      name: pipenv-install
      entry: pipenv install
      language: system
      files: Pipfile
```
