### ISSUE TITLE
Add documentation on how to use the identity hook

### ISSUE THREAD

**Issue by DanKaplanSES** [pre-commit/pre-commit#2180]
### describe your issue

Based on the advice I received from https://github.com/pre-commit/pre-commit/issues/2179 I tried to add an identity hook to my script to troubleshoot why my configuration isn't working as expected.

This is the output of running `pre-commit`:

```
Firebase Identity....................................(no files to check)Skipped
- hook id: identity
Firebase Formatter...................................(no files to check)Skipped
```

I'm sure I'm not using this correctly, but there are no examples showing the right way to use this hook. I'd like the documentation to include an example.

### pre-commit --version

pre-commit 2.16.0

### .pre-commit-config.yaml

```yaml
repos:
    - repo: meta
      hooks:
          - id: identity
            name: Firebase Identity
            language: system
            entry: bash -c 'cd firebase/functions && echo "$PWD"'
            pass_filenames: false
            types: [ts]
            files: ^firebase/functions/.*
    - repo: local
      hooks:
          - id: firebase-formatter
            name: Firebase Formatter
            language: system
            entry: bash -c 'cd firebase/functions && echo "$PWD"'
            pass_filenames: false
            types: [ts]
            files: ^firebase/functions/.*
```

### ~/.cache/pre-commit/pre-commit.log (if present)

This file didn't exist.

**Comment by asottile** [comment]
no files to check means that nothing has matched your filters so it's not even getting to the call because you've filtered out all the files

**Comment by DanKaplanSES** [comment]
1. Okay, but how do I troubleshoot this further? Should I re-create https://github.com/pre-commit/pre-commit/issues/2179 using the template?
2. I appreciate your quick response, but what you think about adding an example to the documentation?

**Comment by asottile** [comment]
1. wouldn't even help, it never gets there because there's no files
2. you're using it correctly except that you've overridden `entry` -- you've just filtered to an empty set
3. you haven't shown the command you're running, it's possible you're not using it correctly

**Comment by asottile** [comment]
my guesses:
- maybe misunderstanding the command being run? [`pre-commit` run`](https://pre-commit.com/#pre-commit-run) -- by default runs on staged files, and you probably don't have any? -- perhaps you mean to use `--all-files`?
- the file filtering: https://pre-commit.com/#filtering-files-with-types -- this has some advice on how to check what your files are identified as via `identify-cli`

**Comment by DanKaplanSES** [comment]
I was running `pre-commit` directly. 

> by default runs on staged files 

Ah, that's what i'm doing wrong. Once I modified a typescript file, it worked correctly. See, the [documentation](https://pre-commit.com/#4-optional-run-against-all-the-files) says:

> ## 4. (optional) Run against all the files
> it's usually a good idea to run the hooks against all of the files when adding new hooks (usually pre-commit will only run on the changed files during git hooks)
> ```
>         $ pre-commit run --all-files
>         ...
> ```

But in my case, I need to execute the pre-commit script in a subdirectory. Therefore, the term `--all-files`, taken out of context, was the exact opposite of what I wanted to do. That makes me wonder something else: does `--all-files` _literally_ run on all files, or just all matches?

> wouldn't even help, it never gets there because there's no files

Perhaps you are correct, but I think it would help if verbose gave more information along the lines of https://github.com/pre-commit/pre-commit/issues/2179 If verbose told me somewhere it is looking for staged files, I would've instantly known what I was doing wrong. I think that would be more valuable than the documentation saying this, as the documentation is ~8500 words, and as far as I can tell, only a few of those words are used to explain this -- and they are wrapped in parentheses, so they are easy to pass by.

In my experience, verbose flags usually provide troubleshooting information, but for pre-commit, as far as I can tell, it only prints the hook id and the duration that hook took to run. Compare `curl example.org` to `curl -v example.org` as an example.

**Comment by asottile** [comment]
yeah, I guess I expected you to have gone through the quick start and understood the basics

**Comment by DanKaplanSES** [comment]
> yeah, I guess I expected you to have gone through the quick start and understood the basics

Well, actually I did. Not just this time, but a couple of months ago, too. Perhaps the first time I noticed the comment in the parentheses, and maybe this time I missed it. Or maybe I missed it both times, I can't remember.

Regardless, am I too take this as you're not interested in adding troubleshooting information to `-v`?

**Comment by asottile** [comment]
correct I do not want to expose the internals plus there are existing and established mechanisms for getting the same information

**Comment by DanKaplanSES** [comment]
> there are existing and established mechanisms for getting the same information

I'm still a little confused about that. I just changed my configuration file to look like this (notice how I removed the `entry` from the identity hook):

```yaml
repos:
    - repo: meta
      hooks:
          - id: identity
            name: Firebase Identity
            language: system
            pass_filenames: false
            types: [ts]
            files: ^firebase/functions/.*
    - repo: local
      hooks:
          - id: firebase-formatter
            name: Firebase Formatter
            language: system
            entry: bash -c 'cd firebase/functions && echo "$PWD"'
            pass_filenames: false
            types: [ts]
            files: ^firebase/functions/.*
```

And when I ran the command line, this was its output:

```
➜  backend pre-commit run -v
Firebase Identity........................................................Passed
- hook id: identity
- duration: 0.03s
Firebase Formatter.......................................................Passed
- hook id: firebase-formatter
- duration: 0s
```

What information is identity supposed to provide? 

Perhaps when you said, "there are existing and established mechanisms for getting the same information," you were referring to something that hasn't been brought up yet?
