### ISSUE TITLE
doesn't work in visual studio 2019 on Windows

### ISSUE THREAD

**Issue by hushigome-visco** [pre-commit/pre-commit#2182]
### describe your issue

When I try to commit from visual studio 2019, I get the following message:
```
/usr/bin/env: ‘bash’: No such file or directory
```

I have confirmed that it works from vscode and command prompt.
I rewrote the `.git/hooks/pre-commit` to below and it worked.
```
#!/usr/bin/env sh
```

As far as I can see, visual studio git hooks only support `sh`.
Are you aware of this problem?

thank you.

### pre-commit --version

pre-commit 2.16.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
      - id: clang-format
```
