### ISSUE TITLE
Permit to pass file list as environnment parameters

### ISSUE THREAD

**Issue by baby-gnu** [pre-commit/pre-commit#2186]
I try to create a `docker_image` `pre-commit` hook to lint meteor code with `package.json` under the `app/` directory but this fails:

```yaml
---
default_stages: [commit]
repos:
  - repo: local
    hooks:
      - id: meteor:lint
        name: Lint meteor code
        description: Lint javascript code with 'meteor npm run eslint'
        types: [file, javascript]
        language: docker_image
        entry: |
          geoffreybooth/meteor-base:2.5
          env HOME=/tmp /bin/bash -c 'cd app && meteor npm install && meteor npm run eslint'
```

But it's not possible since `pre-commit` just append the files to the entry:

```
/usr/bin/docker run --rm -u 1000:1000 -v /home/me/test-project:/src:rw,Z --workdir /src geoffreybooth/meteor-base:2.5 env HOME=/tmp /bin/bash -c 'cd app && meteor npm install && meteor npm run eslint' app/client/main.js
```

Another problem is that I would like to mangle the file names since they should be relative to the `app/` directory because I must run the `meteor npm run eslint` from that directory.

**Comment by baby-gnu** [comment]
Today, the only work around is to add a script in my repository:

```bash
#!/bin/bash

set -e

cd app
meteor npm install
meteor npm run eslint ${@#app/}
```

And call it in my hook

```yaml
default_stages: [commit]
repos:
  - repo: local
    hooks:
      - id: meteor:lint
        name: Lint meteor code
        description: Lint javascript code with 'meteor npm run eslint'
        types: [file, javascript]
        language: docker_image
        entry: |
          hub.eole.education/proxyhub/geoffreybooth/meteor-base:2.5
          env HOME=/tmp bin/pre-commit-meteor-lint
```
