### ISSUE TITLE
Add support for pcre / scripts / system hooks definition in .pre-commit-config.yaml

### ISSUE THREAD

**Issue by Lucas-C** [pre-commit/pre-commit#219]
Everything is in the title :)

_Rationale:_ a `pre-commit` user shouldn't have to setup a git repository to configure a pre-commit check that can be defined in 5 lines or less.

_Example:_ taken the from [do_not_commit](https://github.com/pricematch/pricematch-pre-commit-hooks/blob/master/hooks.yaml) hook:

    - id: do_not_commit
      name: Block if "DO NOT COMMIT" is found
      entry: DO NOT COMMIT
      language: pcre
      files: ^(.*)$
 
_Suggested solutions:_

1. Allow for pcre / scripts / system hooks definition in _.pre-commit-config.yaml_
2. Allow for the `repo` field in _.pre-commit-config.yaml_ to point to a subfolder (of the git repo configured with `pre-commit`) that contains a _hooks.yaml_ .
This currently crashes because `pre-commit` expect to find git repository in the folder point by `repo`.

**Comment by asottile** [comment]
I think this is along similar lines of this: https://github.com/pre-commit/pre-commit/issues/173

And is kind-of possible: https://github.com/Yelp/venv-update/blob/a5960acab7101a1e70c57945b2038fef9d005aed/.pre-commit-config.yaml#L15-L22

I'd certainly like to make this easier though :)

**Comment by Lucas-C** [comment]
Yes ! The `Yelp/venv-update` example is exactly what I wanted !
If you support this, maybe mention it in the docs ?
Although maybe allowing a `repo: local` value would be cleaner than having to point it to an existing dummy github repo.

**Comment by asottile** [comment]
Yeah that way *works* currently, I wouldn't call it supported yet since it's kinda clunky and I want a more straightforward way of doing that.  That method is unlikely to break though.  I imagine the actual implementation will be similar

**Comment by Lucas-C** [comment]
Ok. Then you can resolve this ticket if you want to track this feature elsewhere.
And thank you for your detailed answers !

**Comment by Lucas-C** [comment]
I went on and hacked around it: what do you think of the solution described in #223 ?

**Comment by asottile** [comment]
I'm going to clarify here since I think I'm a bit confused :)

I'd like to make @bukzor's config work when it changes from:

```yaml
-   repo: git://github.com/bukzor/pre-commit-system-hook.git
    sha: 64a3e3f0d11f74ccd0498ea3149c8e177dd9989c
    hooks:
    -   id: system
        name: PyLint
        entry: python -m pylint.__main__
        language: system
        files: \.py$
```

to 

```yaml
-   repo: pre-commit-locally-configured
    hooks:
    -   id: pylint
        name: PyLint
        entry: python -m pylint.__main__
        language: system
        files: \.py$
```

I think (but I might be a bit off!) that all we would need to change to support this is:
- Change the config schema to allow for missing sha in the case the repo is our special value
- In the case that our repo is the special value, the repository is a special list which contains "all hooks" (that is to say that anything we configure in our config will match a hook in this special repo)
- Allow the current code which merges the config dict on top of the manifest dict to continue to work (might need it in another place as well)

Does this sound right? (mostly wanted to just get a checklist together so it's clear what the plan is here :D)
