### ISSUE TITLE
prettier args

### ISSUE THREAD

**Issue by b-goldney** [pre-commit/pre-commit#2193]
### describe your issue

I am configuring the .pre-commit-config.yaml file for prettier, but keep receiving the following warning: "[WARNING] Unexpected key(s) present on https://github.com/pre-commit/mirrors-prettier: args".

My .pre-commit-config.yaml is pasted below. 

For args, I have tried several variations including with and without an equal sign and with and without quotes. 

Based off "[passing arguments to hooks](https://pre-commit.com/#passing-arguments-to-hooks)" I would have expected this to work.

### pre-commit --version

pre-commit 2.1.6.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    args: [--config=./react/.prettierrc]
    hooks:
      - id: prettier
```

**Comment by MarcoGorelli** [comment]
does
```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        args: [--config=./react/.prettierrc]
```
work?
