### ISSUE TITLE
configuration with stages: ["commit-msg"] and pass_filenames: false should error

### ISSUE THREAD

**Issue by smenton-tunein** [pre-commit/pre-commit#2202]
### describe your issue

I created a configuration for a custom hook to parse commit messages. I had `pass_filesnames: false` prior to realizing I needed to set the stages. After setting `stages: ["commit-msg"]` I observed it wasn't passing the path to the commit message. It took, ashamed to admit, longer than it should have to realize it was the intersection of these two options. It would be nice if the tool identified this as an error in configuration.

### pre-commit --version

pre-commit 2.16.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: local
  hooks:
  - id: ccsv-repo
    name: check for commit scope based on repo
    language: golang
    entry: ccsv
    args: ["-r"]
    pass_filenames: false
    stages: ["commit-msg"]
```
