### ISSUE TITLE
check-yaml not accepting Cloudformation function short form

### ISSUE THREAD

**Issue by gregn610** [pre-commit/pre-commit#2203]
### describe your issue

the check-yaml hook doesn't seem to like CloudFormation function short form syntax with an exclamation mark, eg.
```yaml
Outputs:
  GetMatchFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt GetMatchFunction.Arn
```

```console
pre-commit run check-yaml --all-files
check yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

could not determine a constructor for the tag '!Ref'
  in "template.yaml", line 15, column 9

```

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-base64.html

Not sure if this is a bug or if there a way to just ignore it.

Thank you.

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
```
