### ISSUE TITLE
Autoupdate to correct references of "git://github.com/"

### ISSUE THREAD

**Issue by jrottenberg** [pre-commit/pre-commit#2212]
### describe your issue

Hello !

Recent changes on github are disabling support for the Git Transport Protocol : 

https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git

I've searched briefly, and there's a lot of project that copied/paste configuration block from other sources, so references of git://github.com" on pre-commit configs are overwhelming :

https://github.com/search?q=git%3A%2F%2Fgithub.com+filename%3A.pre-commit-config.yaml+extension%3Ayaml+filename%3A.pre-commit-config.yaml&type=Code&ref=advsearch&l=&l=

Of course, I've found it in mines as well :
```
sed -i '' s/repo:\ git:/repo:\ https:/ .pre-commit-config.yaml
# or
find . -name .pre-commit-config.yaml | xargs sed -i '' s/repo:\ git:/repo:\ https:/
```

Could autoupdate, detect those `git://github.com/` and replace them automatically with `https://github.com/` ?

### pre-commit --version

2.16.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.31.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
```
