### ISSUE TITLE
Support for using pre-commit when hook is part of a submodule

### ISSUE THREAD

**Issue by fertrevino** [pre-commit/pre-commit#2220]
### describe your issue

I am running a system which has no internet access after submodules have been initialized. One of the submodules contains the pre-commit hook that I want to run. The repository structure looks as follows:

```
.
├── repo_root
└── submodule_1@some_hash
    ├── folder_1
    │   └── file
    └── external
        └── submodule_2@some_hash
```

How can one refer to the hook in submodule_2 in `pre-commint-config.yaml`? Several approaches have been tried without success.

### pre-commit --version

2.10.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: submodule_1/external/submodule_2
    rev: d3bdf1403d92f8cf2dc77bd99a5da42f0a6cef17
    hooks:
      - id: end-of-file-fixer
```
