### ISSUE TITLE
Selecting by extension not working

### ISSUE THREAD

**Issue by tdegeus** [pre-commit/pre-commit#2222]
### describe your issue

I want to format a LaTeX file `*.cls` that is not supported in *identify*. So I do 
```yaml
    types: [file]  # override `types: [tex]`
    files: \.(tex|cls)$
```
However, it seems that my file `src/goose-article.cls` is not touched. Instead when I rename to `src/goose-article.tex` it is touched. 

References:
* https://github.com/tdegeus/goose-article/pull/9
* https://github.com/cmhughes/latexindent.pl/blob/main/.pre-commit-hooks.yaml

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/cmhughes/latexindent.pl
  rev: V3.15
  hooks:
  - id: latexindent-conda
    args: [-s, -w, -l, -m]
    types: [file]  # override `types: [tex]`
    files: \.(tex|cls)$
```
