### ISSUE TITLE
auto-update the repo URL

### ISSUE THREAD

**Issue by KangOl** [pre-commit/pre-commit#2232]
As the GitLab repo of flake8 is out of sync with the GitHub repo, given the following config

```yaml
repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
```

running `pre-commit autoupdate` won't use the last version of flake8.

Yes, the GitLab repo can be synchronized.
But what about allowing hooks authors to define a `canonical_url` key in their `.pre-commit-hooks.yaml` file to help migration to a new hosting?

In the same vein, it would be great to auto-update the URL of the GitHub repos that have been renamed or transferred. GitHub does the redirect at the HTTP level, but git does not seem to care about it.
