### ISSUE TITLE
Skipping the creation of inaccessible environments

### ISSUE THREAD

**Issue by sfc-gh-kbregula** [pre-commit/pre-commit#2236]
### describe your issue

I would like to pre-commit on CI (in my case Github Action), but unfortunately for security reasons CI worker does not have access to all the repositories listed in the configuration file.

So I wanted to skip some this environment and I setted the `SKIP` environment variable which should cause this environment to be skipped. 
```yaml
  pre-commit:

    runs-on: ubuntu-latest

    env:
      SKIP: X-secret-scanner
    steps:
      - name: 🗂 Checkout (${{ github.ref }})
        # v2.4.0 = c73133d4da04e56a135ae2246682783cc7c7cb6
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: 🐍 Set up Python 3.10
        # v2.2.2 = dc73133d4da04e56a135ae2246682783cc7c7cb6
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6
        with:
          python-version: "3.10"
      - name: 👷️ Install pre-commit
        run: pip install pre-commit==2.17.0
      - name: 👷️ Run pre-commit
        run: pre-commit run --show-diff-on-failure --color=always
```
Unfortunately it didn't work. I would like it to be possible to skip initializing environment, if all hooks that are used by environment are skipped.

### pre-commit --version

2.17.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: git@github.X/X.git
  rev: X # pragma: allowlist secret
  hooks:
  - id: X-secret-scanner
```

### ~/.cache/pre-commit/pre-commit.log (if present)

```
[INFO] Initializing environment for git@github.X/X.git.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: [12](https://github.com/X/X-X-X/runs/5072460140?check_suite_focus=true#step:5:12)8
expected return code: 0
stdout: (none)
stderr:
    git@github.com: Permission denied (publickey).
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.
    
Check the log at /home/runner/.cache/pre-commit/pre-commit.log
Error: Process completed with exit code 3.
```

**Comment by asottile** [comment]
pre-commit needs to have access to the repositories in order to decide whether they are skipped or not so this can't really be implemented as you suggest

one idea for you would be to prebuild them outside of your network DMZ (`pre-commit install-hooks`) and maintain the same cache location -- more on this in [the docs](https://pre-commit.com/#managing-ci-caches)

**Comment by asottile** [comment]
though your actual error looks like you're just missing an ssh key **or** you meant to use `https://` to clone instead

**Comment by sfc-gh-kbregula** [comment]
@asottile Why do I need to download the repository to decide? I think it has all the info in pre-commit-config.yaml. Now I have no problems with skipping based on the file type or pattern, but based on the environment variable that is available.

If we have the file as below:
```yaml
repos:
- repo: git@github.X/X.git
  rev: X # pragma: allowlist secret
  hooks:
  - id: X-secret-scanner
```
And we'll set the `SKIP` environment variable to "X-secret-scanner".

This effectively the content of the file is equivalent as below:
```yaml
repos:
- repo: git@github.X/X.git
  rev: X # pragma: allowlist secret
  hooks: []
```
If we delete repositories that do not perform any operation, we have the file:
```yaml
repos: []
```
Then there is no need to create any environment.

Did I miss something?
