### ISSUE TITLE
SQLFluff dbt | Additional properties are not allowed ('seed-paths', 'model-paths' were unexpected).

### ISSUE THREAD

**Issue by mailtosumitrai** [pre-commit/pre-commit#2238]
### describe your issue

Dbt has [marked source-paths and data-paths as deprecated keys](https://github.com/dbt-labs/dbt-core/issues/1607) in dbt_project.yml in favor of model-paths and seed-paths respectively from the [release v1.0.0](https://github.com/dbt-labs/dbt-core/releases/tag/v1.0.0).

pre-commit throws this error after the change.
```
dbt.exceptions.DbtProjectError: Runtime Error
  at path []: Additional properties are not allowed ('seed-paths', 'model-paths' were unexpected)
```

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 0.8.2
  hooks:
    - id: sqlfluff-lint
      # For dbt projects, this installs the dbt "extras":
      additional_dependencies: ['dbt-snowflake', 'sqlfluff-templater-dbt']
```
