### ISSUE TITLE
Pre-commit doesn't support comma separated files list

### ISSUE THREAD

**Issue by KindDragon** [pre-commit/pre-commit#2244]
I have precommit config like this:
```
repos:
  - repo: local
    hooks:
      - id: groovy-lint-fix
        name: groovy/jenkinsfile autofixing
        entry: npm-groovy-lint --fix --verbose -c=recommended-jenkinsfile --files
        language: node
        additional_dependencies: ["npm-groovy-lint@9.4.1"]
        description: Groovy & Jenkinsfile activate autofixing of fixable rules
        types: [groovy]
```
But `--files` argument requires comma-separated list of files and only handles the first file if we separate them by whitespaces.
https://www.npmjs.com/package/npm-groovy-lint
