### ISSUE TITLE
question: steps to change working directory with or without args

### ISSUE THREAD

**Issue by yarnabrina** [pre-commit/pre-commit#2249]
I've a repo with two python packages, and hence I want to change the working directory before running the hooks. Following the recommendation on #1110, I wrote the following for `black`:

```yaml
repos:
    - repo: "https://github.com/psf/black"
      rev: "22.1.0"
      hooks:
      - id: "black"
        name: "package_1-black"
        args:
          - "--line-length"
          - "99"
        entry: bash -c 'cd /path/to/package_1 && black "$@"'
```

However, it fails with the following error:

```sh
❯ pre-commit run --all-files
package_1-black..........................................................Failed
- hook id: black
- exit code: 2

Usage: black [OPTIONS] SRC ...
Try 'black -h' for help.

Error: Invalid value for 'SRC ...': Path '99' does not exist.
```

Since `black --line-length 99 .` works if I run manually from `/path/to/package_1`, I guess it's not an issue with black. Also I checked that if I change `entry` to just `black`, it works again.

So, I want to know how to make it work with `cd`. And hopefully, this solution will be same for hooks with or without `args` section, and irrespective of operating system.

**System Information**: `macOS 12.2.1`

_Request_: I understand that it has been decided to not add changing working directory support, and that's completely okay, but if there is some documentation on how to do this in the homepage or the website, that'll be very helpful for quite a lot of people.
