### ISSUE TITLE
Using pre-commit to insert a license header

### ISSUE THREAD

**Issue by coreyackland** [pre-commit/pre-commit#2257]
### describe your issue

Objective is to add a license to each new file staged with pre-commit.  

I've created a .pre-commit-config.yaml file with the following:

```
---
repos:

  # license header
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.12
    hooks:
      - id: insert-license
        name: "Insert license header in C++ source files"
        args: [--license-filepath=util/lemons_header.txt,
               '--comment-style=/*| *| */',
               --detect-license-in-X-top-lines=16]
        types_or: [c, c++, objective-c]
```

The git repo has pre-commit 'installed', created a new file, staged it, ran pre-commit and results return with:

Insert license header in C++ source files............(no files to check)Skipped

What else might I need to add for the hook script to find the files to add the license header?

Thanks

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
---
repos:

  # license header
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.12
    hooks:
      - id: insert-license
        name: "Insert license header in C++ source files"
        args: [--license-filepath=util/lemons_header.txt,
               '--comment-style=/*| *| */',
               --detect-license-in-X-top-lines=16]
        types_or: [c, c++, objective-c]
```
