### ISSUE TITLE
`path` field in hook definition?

### ISSUE THREAD

**Issue by redsun82** [pre-commit/pre-commit#2262]
I have a case of a large private repo with a node.js repo-specific generation step that feels perfect to integrate in pre-commit. Only thing, the node package is rooted in a specific subdirectory of the repo, and it does not seem to make much sense to define a node package at the very root of the repo just for that. Would it be feasible to have a `path` field in the hook definition, so I could write something like
```yaml
- repo: local
  hooks:
  - id: check-gen
    ...
    language: node
    path: misc/foogen
```
and the node package would be installed from the `misc/foogen` directory?

I think it might even make sense for an actual git repo exporting pre-commit hooks to define some of them in completely separate packages with different dependencies, instead of itself being one big package.
