### ISSUE TITLE
Pre-commit does not work on Windows using Pip v22

### ISSUE THREAD

**Issue by john-adamson** [pre-commit/pre-commit#2263]
### describe your issue

Pre-commit no longer works in an environment with Pip upgraded to v22 first.

If pre-commit is installed it should be able to add a Git hook to the .git/hooks folder.
Additionally, running the pre-commit command should produce output.

Steps to reproduce:

1. Install Python 3.10 and Git (including Git Bash) on Windows 10
2. Open Git Bash
3. Run:
```
$ mkdir precommittest
$ cd precommittest
$ <path to installed python exe> -m venv venv
$ . ./venv/Scripts/activate
$ python -m pip install pip --upgrade
$ python -m pip install pre-commit
$ pre-commit sample-config > .pre-commit-config.yaml
$ pre-commit install
$ pre-commit run --all-files
```

The final two lines will do nothing with Pip v22.

If the `python -m pip install pip --upgrade` step is skipped then pre-commit will work as expected.

### pre-commit --version

2.17.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
```
