### ISSUE TITLE
undefined behavior with multiple pyproject.toml

### ISSUE THREAD

**Issue by blackliner** [pre-commit/pre-commit#2267]
### describe your issue

we have a toplevel `pyproject.toml` with the following content:
```
[tool.black]
line-length = 120
```
we have another `pyproject.toml` in `packages/some_python_package`:
```
[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build>=0.13",
]

build-backend = "setuptools.build_meta"
```

Our relevant `.pre-commit-config.yaml` part:
```
  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
        language_version: python3
        args: [--verbose]
```

When running the following, the top level `pyproject.toml` is used to format python files in `packages/some_python_package`:
```
export merge_base=$(git merge-base HEAD origin/develop)
pre-commit run --from-ref $merge_base --to-ref HEAD
```
In this case, black also emmits the following verbose message, confirming the usage of top level config file:
`Using configuration from /home/repo/pyproject.toml.`

but when `pre-commit` is asked to directly run on a python file in `packages/some_python_package`, the "wrong" `packages/some_python_package/pyproject.toml` is used for formating (which means, no black configuration):
```
pre-commit run --file packages/some_python_package/file.py
```

### pre-commit --version

2.17.0

### .pre-commit-config.yaml

```yaml
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
        language_version: python3
        args: [--verbose]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [--max-line-length=1024, --extend-ignore=E203]
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.28.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
```

### ~/.cache/pre-commit/pre-commit.log (if present)

N/A

**Comment by blackliner** [comment]
relevant: https://github.com/psf/black/issues/2863
but still, why is the behavior different depending on how pre-commit is called?

**Comment by asottile** [comment]
this isn't a bug with pre-commit but with a specific tool. please report it there

**Comment by blackliner** [comment]
Do you have an explanation why `black` behaves differently, depending on how I run pre-commit?

**Comment by asottile** [comment]
I don't work on black or use black so I can't explain to you how black works -- but the black maintainers almost certainly can

**Comment by blackliner** [comment]
Looks like [Where Black looks for the file](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#where-black-looks-for-the-file) is explaining it a bit:
```
By default Black looks for pyproject.toml starting from the common base directory of all files and directories passed on the command line.
```
Maybe you are passing multiple files with the --from-reff/--to-ref syntax, and `run --file` will only provide the one file.

**Comment by blackliner** [comment]
Fixed by adding an explicit --config:
```
  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
        language_version: python3
        args: [--quiet, --config, pyproject.toml] # to avoid black picking up the wrong pyproject.toml
```
