### ISSUE TITLE
'check-yaml' hook does not support '!reference' tag

### ISSUE THREAD

**Issue by AIGeneratedUsername** [pre-commit/pre-commit#2278]
### describe your issue

See https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#reference-tags
```yaml
include:
  - local: setup.yml

.teardown:
  after_script:
    - echo deleting environment

test:
  script:
    - !reference [.setup, script]
    - echo running my own command
  after_script:
    - !reference [.teardown, after_script]
```
Error:
```
check yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

could not determine a constructor for the tag '!reference'
  in ".gitlab-ci.yml", line 21, column 7
```

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
- repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
```
```


### ~/.cache/pre-commit/pre-commit.log (if present)

_No response_
