### ISSUE TITLE
Feature: execute hooks in a subdirectory

### ISSUE THREAD

**Issue by Lucas-C** [pre-commit/pre-commit#228]
Say I have a `Makefile` or `Gruntfile`, could it be possible to execute a `make check` or `grunt validate` **in a subdirectory** ?

Example:
```
- repo: local
  hooks:
  - id: grunt-validate
    name: Grunt validate
    directory: my/project/subfolder
    entry: grunt validate
    language: system
```

Note: I initially created this issue with a silly request. The edited version correctly points to the missing feature I need.

**Comment by asottile** [comment]
I think this is possible with the current tooling maybe?

```
mkdir -p bin
echo 'cd my/project/subfolder && grunt validate' > bin/grunt-validate-subfolder
chmod 755 bin/grunt-validate-subfolder
git add bin/grunt-validate-subfolder
```

With a config similar to this:

```yaml
- repo: local
  hooks:
  - id: grunt-validate
    name: Grunt validate
    files: ^my/project/subfolder
    entry: ./bin/grunt-validate-subfolder
    language: script
```

**Comment by Lucas-C** [comment]
Ok, nice workaround !
Looks perfect for my needs, resolving the issue

**Comment by Lucas-C** [comment]
Just for posterity, here is another solution that doesn't require any additional file:
```
- repo: local
  hooks:
  - id: test
    name: test
    language: system
    entry: sh
    args: [-c, 'cd my/project/subfolder && grunt validate']
    files: ''
```
