### ISSUE TITLE
push does not triggers pre-commit hooks

### ISSUE THREAD

**Issue by talaklalai** [pre-commit/pre-commit#2281]
### describe your issue

The following not triggered by push
```
repos:
  - repo: local
    hooks:
        - id: flake8
          name: flake8
          entry: flake8
          language: system
          stages: [push]
```
while change `stages: [push] `to `stages: [commit]` , does works.

linux + windows.
any minimum `hello world` project

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
        - id: flake8
          name: flake8
          entry: flake8
          language: system
          stages: [push]
```

### ~/.cache/pre-commit/pre-commit.log (if present)

no file was created.
(was created with `stages: [commit]`)
