### ISSUE TITLE
Option to concatenate ``args``

### ISSUE THREAD

**Issue by DanielNoord** [pre-commit/pre-commit#2284]
### describe your issue

I tried to find an earlier issue but couldn't find it. Please close if this has already been considered.

For a hook I have been working on I pass some standard arguments to the program (for example, `--write` to auto fix issues found by the program).
However, when I use the hook in another project and add another argument to `args` I noticed it overwrote the `--write` argument that I had defined in [.pre-commit-hooks.yaml](https://github.com/DanielNoord/pydocstringformatter/blob/main/.pre-commit-hooks.yaml).

Perhaps I am missing something, but it would be nice if there was the option to tell `pre-commit` to concatenate any options the user supplies the those supplied from the `hooks` file.

### pre-commit --version

pre-commit 2.16.0

### .pre-commit-config.yaml

```yaml
- repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.5.0
    hooks:
      - id: pydocstringformatter
        exclude: *fixtures
        args: ["--max-summary-lines=2", "--split-summary-body", "-w"]
        files: "pylint"
```
