### ISSUE TITLE
Feature Request: ability to invoke a different pre-commit config

### ISSUE THREAD

**Issue by jamesbraza** [pre-commit/pre-commit#2289]
I think it would be useful if one could invoke `pre-commit` from one config file on another config file.

This can already be accomplished with `repo: local` within a `.pre-commit-other-config.yaml` like so:

```yaml
  - repo: local
    hooks:
      - id: pre-commit-default-config
        name: pre-commit-default-config
        language: system
        entry: bash -c 'pre-commit run --config .pre-commit-config.yaml'
```

However, the full printout of the default config is reduced to just one line during invocation:

```
pre-commit-default-config......................................................Passed
```

This could enable a pattern like:
1. Fast-running config (invoking tools like `isort`, `black`): used as default `.pre-commit-config.yaml`
2. Slow-running config (invoking longer-running tools like `mypy` or `pylint`) run in CI that invokes the default `.pre-commit-config.yaml` as a sub-step

**Comment by asottile** [comment]
pre-commit intentionally does not support configuration inclusion

also your config unnecessarily uses `bash -c` and you can get the output if you use `verbose: true`

but note that you're in **intentionally unsupported territory** so you're on your own to make it work

**Comment by jamesbraza** [comment]
Even though configuration inclusion is not supported, thanks for giving suggestions on how to make the config better, so I can accomplish it if I decided to.  Here's what the updated config would look like:

```yaml
  - repo: local
    hooks:
      - id: pre-commit-other-config
        name: pre-commit-other-config
        language: system
        verbose: true
        entry: pre-commit run --config .pre-commit-other-config.yaml --files
```

The key to removing `bash -c` was use of `--files`.
