### ISSUE TITLE
[un]install doesn't work with hooks for specific stages

### ISSUE THREAD

**Issue by ghostsquad** [pre-commit/pre-commit#2298]
### describe your issue

I have a plugin that uses a specific stage: 

> `.pre-commit-checks.yaml`

```yaml
- id: ccsv
  name: check for valid commit scope
  language: golang
  entry: ccsv
  stages: ["commit-msg"]
```

pre-commit uninstall doesn't work for this hook. It requires `pre-commit uninstall --hook-type commit-msg`. Similarly, installing doesn't install all stages.

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
- repo: git@github.com:<ORG>/ccsv
  rev: 1.1.0
  hooks:
    - id: ccsv
      args: ["-r"]
```
