### ISSUE TITLE
go: command not found in pre-commit environment

### ISSUE THREAD

**Issue by luckyhacking** [pre-commit/pre-commit#2305]
### describe your issue

Use pre-commit as usual, but this time the error is reported that “go: command not found”. 

In fact, I can use it, but after I explicitly declare the PATH, it still reports an error

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/golangci/golangci-lint'
    rev: v1.44.2
    hooks:
      - id: golangci-lint

  # [dnephin/pre-commit-golang: Golang hooks for pre-commit](https://github.com/dnephin/pre-commit-golang)
  - repo: 'https://github.com/dnephin/pre-commit-golang'
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-vet
#      - id: go-lint
      - id: go-imports
#      - id: go-cyclo
#        args:
#          - '-over=15'
      - id: validate-toml
      - id: no-go-testing
      - id: golangci-lint
#      - id: go-critic
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
```

### ~/.cache/pre-commit/pre-commit.log (if present)

check yaml...........................................(no files to check)Skipped
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
golangci-lint............................................................Failed
- hook id: golangci-lint
- exit code: 3

level=warning msg="Failed to discover go env: failed to run 'go env': exec: \"go\": executable file not found in $PATH"
level=error msg="Running error: context loading failed: failed to load packages: failed to load with go/packages: err: go command required, not found: exec: \"go\": executable file not found in $PATH: stderr: "

go fmt...................................................................Failed
- hook id: go-fmt
- exit code: 127

/Users/lhgtqb7bll/.cache/pre-commit/repo3y6257l9/run-go-fmt.sh: line 8: gofmt: command not found
/Users/lhgtqb7bll/.cache/pre-commit/repo3y6257l9/run-go-fmt.sh: line 8: gofmt: command not found

go vet...................................................................Failed
- hook id: go-vet
- exit code: 127

/Users/lhgtqb7bll/.cache/pre-commit/repo3y6257l9/run-go-vet.sh: line 3: go: command not found
/Users/lhgtqb7bll/.cache/pre-commit/repo3y6257l9/run-go-vet.sh: line 3: go: command not found

go imports...............................................................Failed
- hook id: go-imports
- exit code: 127

/Users/lhgtqb7bll/.cache/pre-commit/repo3y6257l9/run-go-imports.sh: line 8: goimports: command not found
/Users/lhgtqb7bll/.cache/pre-commit/repo3y6257l9/run-go-imports.sh: line 8: goimports: command not found

validate toml........................................(no files to check)Skipped
Check files aren't using go's testing package........(no files to check)Skipped
golangci-lint............................................................Failed
- hook id: golangci-lint
- exit code: 127

/Users/lhgtqb7bll/.cache/pre-commit/repo3y6257l9/run-golangci-lint.sh: line 2: exec: golangci-lint: not found

go-unit-tests............................................................Failed
- hook id: go-unit-tests
- exit code: 1

/Users/lhgtqb7bll/.cache/pre-commit/repo3y6257l9/run-go-unit-tests.sh: line 2: go: command not found
/Users/lhgtqb7bll/.cache/pre-commit/repo3y6257l9/run-go-unit-tests.sh: line 4: go: command not found
unit tests failed
/Users/lhgtqb7bll/.cache/pre-commit/repo3y6257l9/run-go-unit-tests.sh: line 2: go: command not found
/Users/lhgtqb7bll/.cache/pre-commit/repo3y6257l9/run-go-unit-tests.sh: line 4: go: command not found
unit tests failed

go-build.................................................................Failed
- hook id: go-build
- exit code: 127

/Users/lhgtqb7bll/.cache/pre-commit/repo3y6257l9/run-go-build.sh: line 2: go: command not found
/Users/lhgtqb7bll/.cache/pre-commit/repo3y6257l9/run-go-build.sh: line 3: exec: go: not found
/Users/lhgtqb7bll/.cache/pre-commit/repo3y6257l9/run-go-build.sh: line 2: go: command not found
/Users/lhgtqb7bll/.cache/pre-commit/repo3y6257l9/run-go-build.sh: line 3: exec: go: not found

go-mod-tidy..............................................................Passed
black................................................(no files to check)Skipped
