### ISSUE TITLE
`pre-commit` not found.  Did you forget to activate your virtualenv?- using RHEL

### ISSUE THREAD

**Issue by AdiY10** [pre-commit/pre-commit#2306]
### describe your issue

I'm working with RHEL, and trying to commit using Pycharm. I'm getting this error:

"`pre-commit` not found. Did you forget to activate your virtualenv?"

![Screenshot from 2022-03-28 13-10-26](https://user-images.githubusercontent.com/83010776/160376579-bddfb3f7-fc1f-4b70-b325-29e11635f077.png)

I tried to look for a solution, but found nothing.

**important to say that when I "pre-commit run --all-files", it passes with no error.

pre-commit  version- 2.17.0

Thanks!

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
---
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.11
    hooks:
      - id: remove-tabs

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-symlinks
      - id: detect-private-key
      - id: check-ast
      - id: debug-statements

  - repo: https://github.com/pycqa/pydocstyle.git
    rev: 6.1.1
    hooks:
      - id: pydocstyle

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace


  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black

  - repo: https://github.com/tomcatling/black-nb
    rev: '0.7'
    hooks:
      - id: black-nb

  # Enable this in repositories with python packages.
  # - repo: https://github.com/mgedmin/check-manifest
  #   rev: '0.39'
  #   hooks:
  #     - id: check-manifest

  - repo: https://github.com/s-weigand/flake8-nb
    rev: v0.3.1
    hooks:
      - id: flake8-nb
        additional_dependencies: ['pep8-naming']
        # Ignore all format-related checks as Black takes care of those.
        args: ['--ignore', 'E2,W5', '--select', 'E,W,F,N', '--max-line-length=120']
```
