### ISSUE TITLE
pre-commit on macos using invalid option for declare

### ISSUE THREAD

**Issue by sms-astanley** [pre-commit/pre-commit#2308]
### describe your issue

Running pre-commit on MacOS fails when using pre-commit-terraform plugins.

```
pre-commit run -a
tflint...................................................................Passed
Terraform validate.......................................................Passed
Terraform fmt............................................................Failed
- hook id: terraform_fmt
- exit code: 2

/Users/<user>/.cache/pre-commit/repo0nc0qtfr/hooks/_common.sh: line 30: declare: -g: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

declare -g not supporting in MacOS

https://ss64.com/osx/declare.html
vs.
https://linuxcommand.org/lc3_man_pages/declareh.html

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
  hooks:
    - id: tflint
      args:
        - "--module"
        - "--config=.tflint.hcl"
    - id: terraform-validate
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.64.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
```

### ~/.cache/pre-commit/pre-commit.log (if present)

N/A

**Comment by sms-astanley** [comment]
I couldn't determine which tool was creating the script in .cache that causes the issue.  I'll dig a bit further.   I assumed incorrectly that the _common.sh was associated with pre-commit.

**Comment by asottile** [comment]
really?  it's right above the error message:

```
Terraform fmt............................................................Failed
- hook id: terraform_fmt
- exit code: 2

/Users/<user>/.cache/pre-commit/repo0nc0qtfr/hooks/_common.sh: line 30: declare: -g: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

"Terraform fmt" with hook id "terraform_fmt" which lines up directly into your configuration:

 ```yaml
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.64.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
```
