### ISSUE TITLE
pre-commit + black no longer working bc pre-commit does not lock dependencies

### ISSUE THREAD

**Issue by nbren12** [pre-commit/pre-commit#2309]
### describe your issue

pre-commit + black no longer works bc Click just released 8.1.0 3 hours ago. I bet 90% of python pre-commit users will notice this problem shortly. Yes black was relying on a private API they maybe shouldn't have, but it seems like pre-commit  should offer a more automated/default framework for locking transitive dependencies of tools. Perhaps hooks should have to specify a lock file?

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
```
```


### ~/.cache/pre-commit/pre-commit.log (if present)

_No response_
