### ISSUE TITLE
Feature request: Allow custom install for system hooks

### ISSUE THREAD

**Issue by brandon-leapyear** [pre-commit/pre-commit#2316]
Example use-cases:
* For tools like eslint or flake8 it's untenable to duplicate the list of plugins in both `.pre-commit-config.yaml` and the usual `package.json`/`requirements.txt` files. So it makes sense to use `system` or `script` to call your usual `npm run lint` or `source venv/bin/activate && lint` command. But then you don't get the ability to install these deps with `pre-commit install --install-hooks`, you have to install out-of-band
* `pre-commit` explicitly does not support tools like `pyright` which requires both Node + Python environments. So it would be nice to be able to manually set up our own environment
    * https://github.com/pre-commit/pre-commit-hooks/issues/157#issuecomment-265516255
* If you want to write pre-commit hooks for a new fancy language (or be able to manually customize the install step for an existing language), this would be a mechanism to try out the usual setup-pre-commit-env-on-install workflow without needing to add the language to pre-commit's source code

Concretely, I'm thinking that the following hook definition:
```yaml
- entry: foo
  language: node
  additional_dependencies: ['foo@1.0.0']
```
should be conceptually equivalent to something like
```yaml
# envdir set to `~/.cache/pre-commit/repo123`
- entry: bash -c 'export PATH=$envdir/node_env-default/bin:$PATH && foo'
  language: system
  install: |
    install_node $envdir/node_env-default/
    $envdir/node_env-default/bin/npm install foo@1.0.0
```

And it would allow for re-use of existing bootstrap scripts for in-repo setup
```yaml
- entry: ./venv/bin/flake8
  language: system
  install: |
    python3 -m venv venv
    venv/bin/pip install -r requirements.txt
```

Related: https://github.com/pre-commit/pre-commit/issues/1453

**Comment by asottile** [comment]
`system` / `script` is intentionally unmanaged and **at your own support**

side-stepping the managed languages is untenable, uncacheable, and will not be implemented

**Comment by asottile** [comment]
you can however put whatever you want into a script

**Comment by brandon-leapyear** [comment]
Right, but my point is to be able to hook (ha) into the `pre-commit install --install-hooks` step.

Ok, ignoring the `$envdir` aspect, do you have any concerns about the basic idea of allowing a `system` hook be able to specify install steps?

**Comment by asottile** [comment]
yes, the cache is intentionally designed to only have things come from the configuration

when you add arbitrary execution based on the working directory it is impossible to cache and impossible to deliver a performant and consistent experience for the user

plus you can already do what you're suggesting today via `language: script` -- just put your `install` steps at the top of your script

none of this is new -- there's a dozen issues which cover the same that you can search the tracker for (try "system" / "script" / "cache" for some search terms)

**Comment by brandon-leapyear** [comment]
> just put your `install` steps at the top of your script

this doesn't do what i want:

> my point is to be able to hook (ha) into the `pre-commit install --install-hooks` step

why do you not want to support `system` hooks being able to run stuff in the `pre-commit install --install-hooks` step?

> none of this is new -- there's a dozen issues which cover the same that you can search the tracker for (try "system" / "script" / "cache" for some search terms)

I tried searching, but I couldn't find anything ("cache" is also not helpful, because all issues containing a dump of pre-commit output shows `~/.cache/pre-commit` paths). Do you have any concrete issues in mind?

**Comment by asottile** [comment]
just a simple example -- what if your requirements.txt changes? or your package.json? or maybe you've got it specified in pyproject.toml or in mypkg/\_\_about\_\_.py -- what if `--install-hooks` isn't run (it's just a shortcut convenience after all)?  does it just run your install steps every time?

**Comment by brandon-leapyear** [comment]
Yes, I would imagine it being exactly equivalent to what happens today for supported languages.

* If `pre-commit run` is run for the first time without `pre-commit install --install-hooks`, it runs the install commands
* If `pre-commit install --install-hooks` is run first, it runs the install commands

The difference would be, yes, for `system` the `install` hook would run every time, as opposed to the first-class supported languages, which know if the `additional_dependencies` list has changed and can cache it. For `system`, your `install` command needs to handle caching, if at all (again, because it's still unmanaged, per the philosophy of the `system` language)

**Comment by asottile** [comment]
put it into a shell script then, use `language: script` and you have exactly what you want today without needing to adjust the framework to "support" an idea which is flawed

**Comment by brandon-leapyear** [comment]
how would i be able to run something when `pre-commit install --install-hooks` is run? i want to be able to install/download things beforehand, _before_ `pre-commit run` happens, so that all the installation happens once, whether it's a `node` hook or a `system` hook. IIUC this is _not_ currently supported today

**Comment by asottile** [comment]
why do you need that? it's no different than your cache invalidation? or `pre-commit run yoursystemhookid`?

**Comment by brandon-leapyear** [comment]
because i don't want to run the linters, just set them up. i could do
```yaml
# .pre-commit-config.yaml
- entry: ./setup-flake8.sh && flake8
  language: system
- entry: ./setup-eslint.sh && eslint
  language: system
```
and write a script like
```bash
pre-commit install --install-hooks && ./setup-flake8.sh && ./setup-eslint.sh
```
but it would be nicer to just define everything as
```yaml
# .pre-commit-config.yaml
- entry: flake8
  language: system
  install: ./setup-flake8.sh
- entry: eslint
  language: system
  install: ./setup-eslint.sh
```
and just do the usual `pre-commit install --install-hooks` to setup all my hooks (both supported-language hooks like `language: node` or `language: python`, but also my manually defined `system` hooks)
