### ISSUE TITLE
How to run/configure pre commit on specific folder?

### ISSUE THREAD

**Issue by RosterIn** [pre-commit/pre-commit#2317]
### describe your issue

I have mono repo of:

repo
> project1
>project2
.pre-commit-config.yaml

My questions:
1. How do I manually (running from command line)
run all hooks on a specific project of my choice?
2. How can I configure the pre-commit to be on project2? Is my only option to manually set each hook separately?

I found similar questions but all were very very old so I wonder if some progress was made in that area.

### pre-commit --version

latest

### .pre-commit-config.yaml

```yaml
default_stages: [commit]
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
minimum_pre_commit_version: "1.20.0"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
```
