### ISSUE TITLE
feature request: add `activate` params for python based module

### ISSUE THREAD

**Issue by cyrinux** [pre-commit/pre-commit#2318]
Hi Anthony,

I would like to be able to do `pre-commit activate detect-secrets` in order to enable the virtualenv and run `detect-secrets scan . > .secrets.baseline` from the virtualenv created by pre-commit.

In the case I got a config like this:

```
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        additional_dependencies:
          - gibberish-detector
```

Can you add an option like this ? Or maybe you got a tricks to easily find the virtualenv to enable from `.cache/pre-commit` ?

Actually I do `python3 -m venv venv; source venv/bin/enable; pip3 install detect-secrets==1.1.0` but I would like to don't do this anymore. Also, I would like prevent installing this module out of a virtualenv / system wide.  

Thanks  for your works / stream / video 😃
