### ISSUE TITLE
Does not recognise `async` with Python

### ISSUE THREAD

**Issue by dalmia** [pre-commit/pre-commit#2321]
### describe your issue

Hi there! 

I am trying to use `pre-commit` with a FastAPI project. Upon running pre-commit, I am getting this error:

```python
error: cannot format filename.py: cannot use --safe with this file; 
failed to parse source file.  AST error message: invalid syntax (<unknown>, line 17)
```

The line where it is showing the error uses the `async...await` syntax.
```python
@router.get('/')
async def get_questions():
    questions = client.quiz.questions.find({})
    return questions
```

Upon removing `async`, pre-commit runs fine. Can you please help me understand why I am seeing this error?

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: '3.9.0'
    hooks:
    -   id: flake8
        args:
        # these are errors that will be ignored by flake8
        # check out their meaning here
        # https://flake8.pycqa.org/en/latest/user/error-codes.html
        - "--ignore=E501,E203,W503"
```
