### ISSUE TITLE
Bandit: wrong version in `dist-info`

### ISSUE THREAD

**Issue by zelenyjan** [pre-commit/pre-commit#2326]
### describe your issue

When installing `bandit` using `virtualenv` it creates `bandit-1.7.4.dist-info` under `site-packages`. `pre-commit` creates `bandit-0.0.0.dist-info` in its virtualenv.

Hook works fine just  `bandit` uses version from dist-info as part of URL for issue detail. 

When run `bandit` manually URL with details is: `https://bandit.readthedocs.io/en/1.7.4/plugins/b105_hardcoded_password_string.html`.

Same config using `pre-commit` URL is `https://bandit.readthedocs.io/en/0.0.0/plugins/b105_hardcoded_password_string.html`

Not sure if its `pre-commit` or `bandit` problem...

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies:
          - toml
```
