### ISSUE TITLE
too many knobs and switches: sane-default-config

### ISSUE THREAD

**Issue by guettli** [pre-commit/pre-commit#2327]
### describe your issue

pre-commit is great. 

Except it has way too many knobs and switches.

I think it would be great if there would be a sane-default-config.

Since a sane-default-config which includes all languages could get quite big,
I think it would be nice to have sane-defaults per language.

This would simplify the user experience a lot.

At the moment it takes quite long to find a suitable config.

### pre-commit --version

pre-commit 2.18.1

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
```
