### ISSUE TITLE
precommit for elixir monorepo

### ISSUE THREAD

**Issue by SadmiB** [pre-commit/pre-commit#2330]
### describe your issue

I was expecting the hooks to run for the folders `api` and `shared` but they are getting skipped

![image](https://user-images.githubusercontent.com/26244234/161806858-3e9e0729-460f-45f1-bced-b20940d019e4.png)

### pre-commit --version

pre-commit 2.18.1

### .pre-commit-config.yaml

```yaml
repos:
- repo: local
  hooks:
  - id: mix-format
    name: 'elixir: mix format'
    entry: mix format --check-formatted
    language: system
    files: ^(api|evercam_shared)/.*\.ex

  - id: mix-credo
    name: 'elixir: mix credo'
    entry: mix credo
    language: system
    pass_filenames: false
    files: ^(api|shared)/.*\.ex

  - id: mix-test
    name: 'elixir: mix test'
    entry: mix test
    language: system
    pass_filenames: false
    files: ^(api|shared)/.*\.exs

  - id: mix-compile
    name: 'elixir: mix compile'
    entry: mix compile --force --warnings-as-errors
    language: system
    pass_filenames: false
    files: ^(api|shared)/.*\.exs

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: no-commit-to-branch
    args: [-b, master]
```
