### ISSUE TITLE
How to activate Python venv before running pre-commit?

### ISSUE THREAD

**Issue by mkucmpro** [pre-commit/pre-commit#2341]
### describe your issue

I use a Python virtual environment to install pre-commit (in Windows, if that matters).

Later, when git hook is actually invoked by git (either from command-line or from any external tool e.g. git gui, Sourcetree), one of the "pre-commit yaml hooks" fails (because it cannot find the necessary executable to run, and this is because the `Scripts` folder of the virtual environment is not in the PATH).

I can solve the problem if I **activate** the Python venv manually (from the console) before running `git commit`. However this is hard to achieve for the external tools (which ideally would automatically, without my intervention).

Another solution is to modify the hook after installation (i.e. edit .git/hooks/pre-commit) to add the activation there, just before invoking pre-commit itself. This however seems not only ugly, but against the principles of this project.

So the question I am trying to make is: how to do it correctly? 

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    - id: cmake-format

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.2
    hooks:
     - id: clang-format      
     - id: cpplint         # <-- this is the one failing when venv is not activated
```
