### ISSUE TITLE
Add modified files to the index.

### ISSUE THREAD

**Issue by dima-dmytruk23** [pre-commit/pre-commit#2346]
### describe your issue

I have a local pre-commit hook that modifies a file. I want to immediately add it to the commit, but I get an error.
```
- hook id: generate-graphql-schema
- exit code: 128
- files were modified by this hook
```

```
fatal: Unable to create '/[path_to_project]/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

I would like to do something like `black` and other formatters that can modify files and add them to a commit

### pre-commit --version

pre-commit 2.18.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: generate-graphql-schema
        name: Generate graphql schema from graphene-pydantic
        language: system
        entry: bash -c 'bash check-files.sh ; git add -u' --
```
