### ISSUE TITLE
Required a parameter `condition` on .pre-commit-config.yaml when config hooks

### ISSUE THREAD

**Issue by DoneSpeak** [pre-commit/pre-commit#2347]
### describe your issue

I want to add a customized local hooks to my project and ignore the hooks if nonexist. So I thought it would be nice if there were a parameter `condition` to determine the hook would be runned or not.

Expected:
```yaml
repos:
  - repo: local
    hooks:
      - id: commit-msg
        name: commit-msg (local-customized)
        entry: .git_hooks/commit-msg
        language: script
        stages: [commit-msg]
        condition: [ -f .git_hooks/commit-msg ]
```

### pre-commit --version

2.17.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: commit-msg
        name: commit-msg (local-customized)
        entry: .git_hooks/commit-msg
        language: script
        stages: [commit-msg]
```

try to run comman line but fail
```python
  - repo: local
    hooks:
      - id: commit-msg
        name: commit-msg-customized
        entry: HOOK=.git_hooks/commit-msg && [ -f $HOOK ] && $HOOK
        language: system
        stages: [commit-msg]
```

```
pre-commit-customized....................................................Failed
- hook id: pre-commit
- exit code: 1

Executable `HOOK=.git_hooks/pre-commit` not found
```

try to using `SKIP` or `--no-verify` when committing but the `prepare-commit-msg` still work.
