### ISSUE TITLE
GitLab CI – git unsafe repository

### ISSUE THREAD

**Issue by lcnittl** [pre-commit/pre-commit#2352]
### describe your issue

We are having problem running (tox spawned) pre-commit in CI pipelines on GitLab since the [recent security update](https://github.blog/2022-04-12-git-security-vulnerability-announced/).

As `mypackage` is using `setuptools_scm` installation of the package failed too, as well as `git show` did. Yet, both were successfully fixed by adding the suggested git option `safe.directory`.

However, for some reason, pre-commit (git called by pre-commit, to be more precise) still complains about an "unsafe repository" being "owned by someone else".

I assume, this has nothing to do with our repository, but rather with the hook repos that pre-commit clones (although, those should be owned by the current user, `runner`? Or maybe the fact that `.cache` is owned by `root` is the problem?

Do you see a way we can fix this on our side, would pre-commit need to add the hook repo directories as `safe.directory`, or does GitLab need to change ownerships of folders?

Here is the relevant part of our `tox.ini` file:

```ini
[tox]
envlist =
    pre-commit
minversion = 3.14

[testenv:pre-commit]
description = format the code base to adhere to our styles, and complain about what we cannot do automatically
passenv =
    PRE_COMMIT_HOME
basepython = python3.7
skip_install = true
deps =
    pre-commit>=2.16
commands =
    pre-commit run --all-files --show-diff-on-failure {posargs}
```

The MWE `.gitlab-ci.yaml` file:

```yaml
stages:
  - pre-test

default:
  image: registry.gitlab.com/python-devs/ci-images:active
  cache:
    key: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG
    paths:
      - ${PIP_CACHE_DIR}
      - ${VENV_DIR}
    when: always

variables:
  PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pip
  PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  PYTHON_VERSION: "3.7"
  VENV_DIR: ${CI_PROJECT_DIR}/.venv

.tox-tests:
  before_script:
    # configure_git -- without this, `git show --quiet` fails
    - git config --global --add safe.directory ${CI_PROJECT_DIR}
    # emit_versions
    - git --version
    - python3 --version
    - python3 -m pip --version
    - git show --quiet
    # setup_venv
    - python3 -m pip install -U virtualenv
    - virtualenv -p ${PYTHON_VERSION} ${VENV_DIR}
    - source ${VENV_DIR}/bin/activate
    # debugging
    - whoami
    - ls -alh .
    - stat -c "%U %G" .
    # install tox and env
    - python3 -m pip install -U tox
    - tox -e ${TESTENV} -vv --notest
  script:
    # debugging -- is safe.directory really configured?
    - git config --global safe.directory
    # run tox
    - tox -e ${TESTENV} --skip-pkg-install || cat ${PRE_COMMIT_HOME}/pre-commit.log

pre-commit:
  stage: pre-test
  extends: .tox-tests
  cache:
    key: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG
    paths:
      - ${PIP_CACHE_DIR}
      - ${PRE_COMMIT_HOME}
      - ${VENV_DIR}
    when: always
  variables:
    TESTENV: pre-commit
```

Which gives the following output (tried to shorten it -- removed lines are denoted by `<...>`):

````
Running with gitlab-runner 14.9.1 (bd40e3da)
  on tokaji Ay_2PiPK
section_start:1650460831:prepare_executor

# Preparing the "docker" executor
Using Docker executor with image registry.gitlab.com/python-devs/ci-images:active ...
Authenticating with credentials from job payload (GitLab Registry)
Pulling docker image registry.gitlab.com/python-devs/ci-images:active ...
Using docker image sha256:dee538eb4732c3d894a2c91bf0b1efbe1d8956703a9a6eb23051b79b2ec0c032 for registry.gitlab.com/python-devs/ci-images:active with digest registry.gitlab.com/python-devs/ci-images@sha256:9823e142a5bdb723fa6d5e7b1eec27eaf384bc27726bc382003071356e537e69 ...
section_end:1650460834:prepare_executor
section_start:1650460834:prepare_script

# Preparing environment
Running on runner-ay2pipk-project-16318859-concurrent-0 via 6b1029790900...
section_end:1650460834:prepare_script
section_start:1650460834:get_sources

# Getting source from Git repository

## Fetching changes with git depth set to 50...
Reinitialized existing Git repository in /builds/myorg/myproject/mypackage/.git/

## Checking out 519b7939 as mybranch...
Removing .cache/
Removing .eggs/
Removing .tox/
Removing .venv/
Removing mypackage.egg-info/
Removing mypackage/__pycache__/
Removing mypackage/devices/__pycache__/
Removing testing/__pycache__/
Removing testing/tests/__pycache__/


## Skipping Git submodules setup
section_end:1650460836:get_sources
section_start:1650460836:restore_cache

# Restoring cache

## Checking cache for pre-commit-mybranch...
No URL provided, cache will not be downloaded from shared cache server. Instead a local version of cache will be extracted.
WARNING: .venv/bin/python: chmod .venv/bin/python: no such file or directory (suppressing repeats)

## Successfully extracted cache
section_end:1650460838:restore_cache
section_start:1650460838:step_script

# Executing "step_script" stage of the job script
Using docker image sha256:dee538eb4732c3d894a2c91bf0b1efbe1d8956703a9a6eb23051b79b2ec0c032 for registry.gitlab.com/python-devs/ci-images:active with digest registry.gitlab.com/python-devs/ci-images@sha256:9823e142a5bdb723fa6d5e7b1eec27eaf384bc27726bc382003071356e537e69 ...

## $ git config --global --add safe.directory ${CI_PROJECT_DIR}

## $ git --version
git version 2.25.1

## $ python3 --version
Python 3.8.10

## $ python3 -m pip --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

## $ git show --quiet
commit 519b7939f04a403c15018ef9a5a5dbe4ae7fc8e6
Author: Christian Knittl-Frank <christian.knittl-frank@univie.ac.at>
Date:   Wed Apr 20 14:20:04 2022 +0100

    [CI/CD] WIP isolate problem for issue report

## $ python3 -m pip install -U virtualenv
Requirement already up-to-date: virtualenv in /usr/local/lib/python3.8/dist-packages (20.14.1)
<...>

## $ virtualenv -p ${PYTHON_VERSION} ${VENV_DIR}
created virtual environment CPython3.7.13.final.0-64 in 427ms
  creator CPython3Posix(dest=/builds/myorg/myproject/mypackage/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/runner/.local/share/virtualenv)
    added seed packages: distlib==0.3.4, filelock==3.6.0, importlib_metadata==4.11.3, packaging==21.3, pip==22.0.4, platformdirs==2.5.2, pluggy==1.0.0, py==1.11.0, pyparsing==3.0.8, setuptools==62.1.0, six==1.16.0, toml==0.10.2, tox==3.25.0, typing_extensions==4.2.0, virtualenv==20.14.1, wheel==0.37.1, zipp==3.8.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

## $ source ${VENV_DIR}/bin/activate

## $ whoami
runner

## $ ls -alh .
total 104K
drwxrwxrwx 10 root   root   4.0K Apr 20 13:20 .
drwxrwxrwx  4 root   root   4.0K Apr 19 11:15 ..
drwxrwxrwx  4 root   root   4.0K Apr 20 13:20 .cache
-rw-rw-rw-  1 root   root    231 Apr 19 11:15 .flake8
drwxrwxrwx  7 root   root   4.0K Apr 20 13:20 .git
-rw-rw-rw-  1 root   root     42 Apr 19 11:15 .gitattributes
-rw-rw-rw-  1 root   root   5.7K Apr 20 13:08 .gitignore
drwxrwxrwx  3 root   root   4.0K Apr 19 11:15 .gitlab
-rw-rw-rw-  1 root   root   1.5K Apr 20 13:20 .gitlab-ci.yml
-rw-rw-rw-  1 root   root   2.5K Apr 19 11:15 .pre-commit-config.yaml
-rw-rw-rw-  1 root   root     15 Apr 19 11:15 .prettierrc.yaml
drwxr-xr-x  4 runner runner 4.0K Apr 19 14:38 .venv
-rw-rw-rw-  1 root   root   1.1K Apr 19 11:15 LICENSE
-rw-rw-rw-  1 root   root   4.0K Apr 19 11:15 README.md
-rw-rw-rw-  1 root   root     30 Apr 19 11:15 bandit.yaml
drwxrwxrwx  4 root   root   4.0K Apr 19 11:15 docs
drwxrwxrwx  2 root   root   4.0K Apr 19 11:15 manuals
drwxrwxrwx  5 root   root   4.0K Apr 20 13:20 mypackage
-rw-rw-rw-  1 root   root    258 Apr 19 11:15 pyproject.toml
-rw-rw-rw-  1 root   root     38 Apr 19 11:15 pytest.ini
-rw-rw-rw-  1 root   root    153 Apr 19 11:15 requirements-dev.txt
-rw-rw-rw-  1 root   root   1.2K Apr 19 11:15 setup.cfg
-rw-rw-rw-  1 root   root    150 Apr 19 11:15 setup.py
drwxrwxrwx  4 root   root   4.0K Apr 20 13:20 testing
-rw-rw-rw-  1 root   root    891 Apr 19 11:15 tox.ini

## $ stat -c "%U %G" .
root root

## $ python3 -m pip install -U tox
Requirement already satisfied: tox in ./.venv/lib/python3.7/site-packages (3.25.0)
<...>

## $ tox -e ${TESTENV} -vv --notest
using tox.ini: /builds/myorg/myproject/mypackage/tox.ini (pid 59)
using tox-3.25.0 from /builds/myorg/myproject/mypackage/.venv/lib/python3.7/site-packages/tox/__init__.py (pid 59)
pre-commit uses /builds/myorg/myproject/mypackage/.venv/bin/python3
pre-commit start: getenv /builds/myorg/myproject/mypackage/.tox/pre-commit
pre-commit cannot reuse: no previous config /builds/myorg/myproject/mypackage/.tox/pre-commit/.tox-config1
pre-commit create: /builds/myorg/myproject/mypackage/.tox/pre-commit
setting PATH=/builds/myorg/myproject/mypackage/.tox/pre-commit/bin:/builds/myorg/myproject/mypackage/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[66] /builds/myorg/myproject/mypackage/.tox$ /builds/myorg/myproject/mypackage/.venv/bin/python3 -m virtualenv --no-download --python /builds/myorg/myproject/mypackage/.venv/bin/python3 pre-commit
created virtual environment CPython3.7.13.final.0-64 in 456ms
  creator CPython3Posix(dest=/builds/myorg/myproject/mypackage/.tox/pre-commit, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/runner/.local/share/virtualenv)
    added seed packages: pip==22.0.4, setuptools==62.1.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
pre-commit installdeps: pre-commit>=2.16
setting PATH=/builds/myorg/myproject/mypackage/.tox/pre-commit/bin:/builds/myorg/myproject/mypackage/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[75] /builds/myorg/myproject/mypackage$ /builds/myorg/myproject/mypackage/.tox/pre-commit/bin/python -m pip install 'pre-commit>=2.16'
Collecting pre-commit>=2.16
  Using cached pre_commit-2.18.1-py2.py3-none-any.whl (197 kB)
<...>
Installing collected packages: nodeenv, distlib, zipp, typing-extensions, toml, six, pyyaml, platformdirs, identify, filelock, cfgv, importlib-metadata, virtualenv, pre-commit
Successfully installed cfgv-3.3.1 distlib-0.3.4 filelock-3.6.0 identify-2.4.12 importlib-metadata-4.11.3 nodeenv-1.6.0 platformdirs-2.5.2 pre-commit-2.18.1 pyyaml-6.0 six-1.16.0 toml-0.10.2 typing-extensions-4.2.0 virtualenv-20.14.1 zipp-3.8.0
pre-commit finish: getenv /builds/myorg/myproject/mypackage/.tox/pre-commit after 9.19 seconds
pre-commit start: finishvenv
write config to /builds/myorg/myproject/mypackage/.tox/pre-commit/.tox-config1 as 'eea3adf565de0f2f81629fef1eb11cc3c4cc61c3311d47368d500e331192494a /builds/myorg/myproject/mypackage/.venv/bin/python3\n3.25.0 0 0 0\n00000000000000000000000000000000 pre-commit>=2.16'
pre-commit finish: finishvenv  after 0.02 seconds
pre-commit start: envreport
setting PATH=/builds/myorg/myproject/mypackage/.tox/pre-commit/bin:/builds/myorg/myproject/mypackage/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[82] /builds/myorg/myproject/mypackage$ /builds/myorg/myproject/mypackage/.tox/pre-commit/bin/python -m pip freeze >.tox/pre-commit/log/pre-commit-0.log
pre-commit finish: envreport  after 0.45 seconds
pre-commit installed: cfgv==3.3.1,distlib==0.3.4,filelock==3.6.0,identify==2.4.12,importlib-metadata==4.11.3,nodeenv==1.6.0,platformdirs==2.5.2,pre-commit==2.18.1,PyYAML==6.0,six==1.16.0,toml==0.10.2,typing_extensions==4.2.0,virtualenv==20.14.1,zipp==3.8.0
___________________________________ summary ____________________________________
  pre-commit: skipped tests
  congratulations :)

## $ git config --global safe.directory
/builds/myorg/myproject/mypackage

## $ tox -e ${TESTENV} --skip-pkg-install || cat ${PRE_COMMIT_HOME}/pre-commit.log
pre-commit installed: cfgv==3.3.1,distlib==0.3.4,filelock==3.6.0,identify==2.4.12,importlib-metadata==4.11.3,nodeenv==1.6.0,platformdirs==2.5.2,pre-commit==2.18.1,PyYAML==6.0,six==1.16.0,toml==0.10.2,typing_extensions==4.2.0,virtualenv==20.14.1,zipp==3.8.0
pre-commit run-test-pre: PYTHONHASHSEED='3714703806'
pre-commit run-test: commands[0] | pre-commit run --all-files --show-diff-on-failure
An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
Check the log at /builds/myorg/myproject/mypackage/.cache/pre-commit/pre-commit.log
ERROR: InvocationError for command /builds/myorg/myproject/mypackage/.tox/pre-commit/bin/pre-commit run --all-files --show-diff-on-failure (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   pre-commit: commands failed
<here is cat of pre-commit.log -- see below at ~/.cache/pre-commit/pre-commit.log>
section_end:1650460863:step_script
section_start:1650460863:archive_cache

# Saving cache for successful job

## Creating cache pre-commit-mybranch...
/builds/myorg/myproject/mypackage/.cache/pip: found 221 matching files and directories
/builds/myorg/myproject/mypackage/.cache/pre-commit: found 5 matching files and directories
/builds/myorg/myproject/mypackage/.venv: found 2302 matching files and directories
No URL provided, cache will be not uploaded to shared cache server. Cache will be stored only locally.

## Created cache
section_end:1650460865:archive_cache
section_start:1650460865:cleanup_file_variables

# Cleaning up project directory and file based variables
section_end:1650460866:cleanup_file_variables

## Job succeeded
````

Thanks for any feedback!

### pre-commit --version

pre-commit 2.18.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: name-tests-test
        args: [--django]
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      # - id: debug-statements
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.1
    hooks:
      - id: setup-cfg-fmt
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 0.5.2
    hooks:
      - id: tox-ini-fmt
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black # black-jupyter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [--recursive, --quiet, --config, bandit.yaml]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8 # E***, W***, F***
        additional_dependencies:
          - dlint # DUO***
          - flake8-2020 # YTT***
          - flake8-bugbear # B***
          - flake8-builtins # A***
          - flake8-comprehensions # C4**
          - flake8-deprecated # D***
          - flake8-variables-names # VNE***
          - mccabe # C9**
          - pep8-naming # N8**
```

### version information

```
pre-commit version: 2.18.1
git --version: git version 2.25.1
sys.version:
    3.7.13 (default, Apr 20 2022, 11:10:00)
    [GCC 9.4.0]
sys.executable: /builds/myorg/myproject/mypackage/.tox/pre-commit/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
```

```
Traceback (most recent call last):
  File "/builds/myorg/myproject/mypackage/.tox/pre-commit/lib/python3.7/site-packages/pre_commit/git.py", line 58, in get_root
    cmd_output('git', 'rev-parse', '--show-cdup')[1].strip(),
  File "/builds/myorg/myproject/mypackage/.tox/pre-commit/lib/python3.7/site-packages/pre_commit/util.py", line 152, in cmd_output
    returncode, stdout_b, stderr_b = cmd_output_b(*cmd, **kwargs)
  File "/builds/myorg/myproject/mypackage/.tox/pre-commit/lib/python3.7/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'rev-parse', '--show-cdup')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: unsafe repository ('/builds/myorg/myproject/mypackage' is owned by someone else)
    To add an exception for this directory, call:

    	git config --global --add safe.directory /builds/myorg/myproject/mypackage


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builds/myorg/myproject/mypackage/.tox/pre-commit/lib/python3.7/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/builds/myorg/myproject/mypackage/.tox/pre-commit/lib/python3.7/site-packages/pre_commit/main.py", line 326, in main
    _adjust_args_and_chdir(args)
  File "/builds/myorg/myproject/mypackage/.tox/pre-commit/lib/python3.7/site-packages/pre_commit/main.py", line 143, in _adjust_args_and_chdir
    toplevel = git.get_root()
  File "/builds/myorg/myproject/mypackage/.tox/pre-commit/lib/python3.7/site-packages/pre_commit/git.py", line 65, in get_root
    'git failed. Is it installed, and are you in a Git repository '
pre_commit.errors.FatalError: git failed. Is it installed, and are you in a Git repository directory?
```
