### ISSUE TITLE
BUG: expected environment for python to be healthy() immediately after install

### ISSUE THREAD

**Issue by Natim** [pre-commit/pre-commit#2363]
### describe your issue

When running pre-commit run I get this error:

```
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
```

### pre-commit --version

2.17.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: |
          (?x)(
            ^static/vendors|
            .min.js$|
            .po$|
            ^tmp/
          )
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]

  - repo: local
    hooks:
      - id: check-po
        name: Check .po files for errors
        language: python
        entry: python ./tools/check_po.py
        types: [text, pofile]
        exclude: |
          (?x)(
            /fr/|
            /pt_PT/
          )
        stages: [commit]
        additional_dependencies: [Babel]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--target-version=py310]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        files: "(^.*\\.js$)|(^frontend/.*$)"


  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.12.0
    hooks:
      - id: eslint
        files: "(^frontend/.*\\.[jt]sx?$)"  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        args:
          - --fix

  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v14.6.1
    hooks:
      - id: stylelint
        files: "(^frontend/src/css/.*\\.css$)"
        args:
          - --config
          - frontend/stylelint.config.js
        additional_dependencies:
          - stylelint@14.5.0
          - prettier@2.5.1
          - stylelint-config-standard@25.0.0
          - stylelint-config-prettier@9.0.3
          - stylelint-prettier@2.0.0
          - prettier-plugin-tailwindcss@0.1.7

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yaml]
```

### version information

```
pre-commit version: 2.17.0
git --version: git version 2.34.1
sys.version:
    3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
sys.executable: /usr/bin/python3.10
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
```

```
Traceback (most recent call last):
  File "/home/rhubscher/.local/lib/python3.10/site-packages/pre_commit/error_handler.py", line 70, in error_handler
    yield
  File "/home/rhubscher/.local/lib/python3.10/site-packages/pre_commit/main.py", line 396, in main
    return run(args.config, store, args)
  File "/home/rhubscher/.local/lib/python3.10/site-packages/pre_commit/commands/run.py", line 416, in run
    install_hook_envs(to_install, store)
  File "/home/rhubscher/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "/home/rhubscher/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 86, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
