### ISSUE TITLE
pre-commit autoupdate will downgrade if tagging scheme changes

### ISSUE THREAD

**Issue by chrisgilmerproj** [pre-commit/pre-commit#2364]
### describe your issue

Reference https://github.com/detailyang/pre-commit-shell/issues/12

A repo I am using for pre-commit changed the tagging scheme to include the letter `v` at the beginning. So the versions went from `1.0.5` to `v1.0.6`. When running `pre-commit autoupdate` the change asks me to go from `v1.0.6 -> 1.0.5`. 

I would expect that the `v` would be ignored when determining the semver so that it would always update. As referenced above I have also asked the maintainer to fix their tagging scheme to be consistent.

### pre-commit --version

pre-commit 2.18.1

### .pre-commit-config.yaml

```yaml
repos:

- repo: https://github.com/detailyang/pre-commit-shell
  rev: v1.0.6
  hooks:
    - id: shell-lint
```
