### ISSUE TITLE
Support --from-ref and --to-ref for hook-stage commit-msg

### ISSUE THREAD

**Issue by martin-eder-zeiss** [pre-commit/pre-commit#2365]
### describe your issue

It is currently not possible to run checks in the commit-msg hook-stage, e.g. gitlint for a range of commits (or at least I have not found a way to do so)

### pre-commit --version

2.18.1

### .pre-commit-config.yaml

```yaml
-   repo: https://github.com/jorisroovers/gitlint
    rev:  v0.17.0
    hooks:
    -   id: gitlint
```
