### ISSUE TITLE
Feature Request: Set environment variables for hooks in .pre-commit-config.yaml

### ISSUE THREAD

**Issue by calebmckay** [pre-commit/pre-commit#2367]
Some pre-commit hooks may require environment variables to be set by the user (e.g. API keys). Rather than require the user to set these environment variables in their profile or manually before running the hook, it would be nice if the environment could be injected into each individual hook through the YAML config.

Example:
```yaml
repos:
- repo: local
  hooks:
  - id: hook1
    environment:
      API_KEY: abcd1234
  - id: hook2
    environment:
      ENV_FILE: ./prod.env
```
