### ISSUE TITLE
Namespace clash with `inspect` package

### ISSUE THREAD

**Issue by emilaz** [pre-commit/pre-commit#2376]
### search tried in the issue tracker

inspect, inspect package

### describe your issue

I have a repo structure that looks something like the following

```
repo
 |  README.md
 |. requirements.txt
 |. pre-commit-config.yaml
 |
└─ inspect
        |.    __init__.py
        |.   foo.py
```

With `.pre-commit-config.yaml` being a very simple hook

```
repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    - id: autoflake
      args:
        - "--in-place"
        - "--remove-all-unused-imports"
        - "--remove-unused-variable"
        - "--ignore-init-module-imports" 
```

But when I try to run this, I'm getting pretty weird errors"

> Traceback (most recent call last):
>   File "/Users/myname/.cache/pre-commit/repo3fqwfoey/py_env-python3.10/bin/autoflake", line 5, in <module>
>     from autoflake import main
>   File "/Users/myname/.cache/pre-commit/repo3fqwfoey/py_env-python3.10/lib/python3.10/site-packages/autoflake.py", line 43, in <module>
>     import pyflakes.api
>   File "/Users/myname/.cache/pre-commit/repo3fqwfoey/py_env-python3.10/lib/python3.10/site-packages/pyflakes/api.py", line 12, in <module>
>     from pyflakes import checker, __version__
>   File "/Users/myname/.cache/pre-commit/repo3fqwfoey/py_env-python3.10/lib/python3.10/site-packages/pyflakes/checker.py", line 12, in <module>
>     import doctest
>   File "/Users/myname/.pyenv/versions/3.10.3/lib/python3.10/doctest.py", line 100, in <module>
>     import pdb
>   File "/Users/myname/.pyenv/versions/3.10.3/lib/python3.10/pdb.py", line 75, in <module>
>     import bdb
>   File "/Users/myname/.pyenv/versions/3.10.3/lib/python3.10/bdb.py", line 6, in <module>
>     from inspect import CO_GENERATOR, CO_COROUTINE, CO_ASYNC_GENERATOR
> ImportError: cannot import name 'CO_GENERATOR' from 'inspect' (/Users/myname/repo/inspect/__init__.py)
>

If I use other hooks, I'm getting similar errors. I was able to fix this by simply renaming my `inspect` package to something else, but this seems like something that shouldn't happen at all, i.e. I should be free to name files and folders in my repo as I wish to?

### pre-commit --version

2.18.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    - id: autoflake
      args:
        - "--in-place"
        - "--remove-all-unused-imports"
        - "--remove-unused-variable"
        - "--ignore-init-module-imports"
```
