### ISSUE TITLE
autoupdate doesn't update versions of additional_dependencies

### ISSUE THREAD

**Issue by ulgens** [pre-commit/pre-commit#2392]
### search tried in the issue tracker

additional_dependencies autoupdate 

### describe your issue

When I try to update my pre-commit config, `autoupdate` only updates `repo` objects, it doesn't check versions under `additional_dependencies`. My expectation with `autoupdate` is it should check and update any type of version reference in the config file.

### pre-commit --version

2.19.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        # Additional dependency updates are not handled by pre-commit autoupdate
        additional_dependencies: [flake8-bugbear==22.3.23]
```
