### ISSUE TITLE
Only install relevant virtual env when specific hook is invoked

### ISSUE THREAD

**Issue by mbkroese** [pre-commit/pre-commit#2395]
### search tried in the issue tracker

unnecessary, install, virtual, virtual-env

### describe your issue

I am working with a python monorepo.
Inside this monorepo, there are N hooks for N packages.
When I invoke one hook, like so:

```
pre-commit run <hook_id> --all
```

I expected `pre-commit` to only build the virtual env for that hook and run it.
However, from the logs I see it also builds the env for other hooks.
This makes running pre-commit very slow in CI in a monorepo.

Is there a way to deal with this?

### pre-commit --version

pre-commit 2.19.0

### .pre-commit-config.yaml

```yaml
repos:
- hooks:
  - additional_dependencies:
    - regex==2021.9.30
    - click==8.0.3
    args:
    - --line-length=120
    id: black
    language_version: python3
  repo: https://github.com/psf/black
  rev: 22.3.0
- hooks:
  - args:
    - --line-length=120
    - --profile=black
    id: isort
  repo: https://github.com/PyCQA/isort
  rev: 5.10.1
- hooks:
  - additional_dependencies:
    - flake8-bugbear
    - flake8-mutable
    args:
    - --ignore=E501,W503
    id: flake8
  - id: end-of-file-fixer
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
- hooks:
  - additional_dependencies:
    - pyspark-stubs==2.4.0.post10
    - types-PyYAML==5.4.10
    args:
    - --ignore-missing-imports
    files: ^lib/foo
    id: mypy
    name: mypy lib foo
  - additional_dependencies:
    - pyspark-stubs==2.4.0.post10
    - types-requests==2.25.6
    args:
    - --ignore-missing-imports
    files: ^lib/bar
    id: mypy
    name: mypy lib bar
  - additional_dependencies:
    - pyspark-stubs==2.4.0.post10
    args:
    - --ignore-missing-imports
    files: ^lib/baz
    id: mypy
    name: mypy lib baz
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
```
