### ISSUE TITLE
pre-commit post-rewrite failure ends with detatched head

### ISSUE THREAD

**Issue by shareefj** [pre-commit/pre-commit#2397]
### search tried in the issue tracker

yes

### describe your issue

I have a hook designed to catch changes to a requirements.txt file and alert the user when they run a clone, merge or rebase.  However, when doing a rebase, mostly I've been doing `git pull --rebase`, the hook fires and stops the rebase from finishing and I'm left in a detached head state.

The only way I've so far been able to work around this is by deleting all `.git/hooks/*` and running again.

Is there a trick I'm missing to get a rebase to complete?

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
default_stages: [commit, push]
exclude: 'vendor/'
repos:
- repo: local
  hooks:
  - id: watch-requirements
    name: Watches requirements.txt for changes
    language: script
    entry: ./hooks/alert_if_modified.py
    always_run: true
    args:
    - --filename
    - requirements.txt
    - --message
    - |
       Alert : requirements.txt has been modified; update your venv.
               try running `create_venv --rebuild $VIRTUAL_ENV`
    stages: [post-checkout, post-merge, post-rewrite]
```
