### ISSUE TITLE
Feat: Allow overriding plugin args on commandline

### ISSUE THREAD

**Issue by alexjurkiewicz** [pre-commit/pre-commit#2399]
We run pre-commit locally and in our CI. Example config file:

```yaml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.71.0
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
      args:
        - "--args=--config=__GIT_WORKING_DIR__/.tflint.hcl"
        - "--format=compact"
```

In CI, we'd like to use `--format=junit` instead. We can modify the YAML file with string/template manipulation, but that's a bit awkward. It would be nice to run something like:
```
pre-commit run --from-ref origin/HEAD --to-ref HEAD --hook-arg "terraform_tflint=--format=junit"
```
Instead.
