### ISSUE TITLE
BUG: expected environment for python to be healthy() immediately after install

### ISSUE THREAD

**Issue by snosratiershad** [pre-commit/pre-commit#2403]
### search tried in the issue tracker

I only checked github issues

### describe your issue

I used the `pre-commit install --hook-type pre-commit --hook-type commit-msg` as described in [cve-bin-tool contribution guide](https://github.com/intel/cve-bin-tool/blob/main/CONTRIBUTING.md#using-pre-commit-to-run-linters-automatically), and when first commit I got the error.

### pre-commit --version

pre-commit 2.18.1

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort

-   repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
    - id: black

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
    - id: pyupgrade
      args: ["--py37-plus"]

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit
      args: ["-c", "bandit.conf"]

-   repo: https://github.com/jorisroovers/gitlint
    rev:  v0.17.0
    hooks:
    - id: gitlint
```

### version information

```
pre-commit version: 2.18.1
git --version: git version 2.34.1
sys.version:
    3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
sys.executable: /home/salar/foss/cve-bin-tool/.venv/local/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
```

```
Traceback (most recent call last):
  File "/home/salar/.local/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/salar/.local/lib/python3.10/site-packages/pre_commit/main.py", line 343, in main
    return hook_impl(
  File "/home/salar/.local/lib/python3.10/site-packages/pre_commit/commands/hook_impl.py", line 237, in hook_impl
    return retv | run(config, store, ns)
  File "/home/salar/.local/lib/python3.10/site-packages/pre_commit/commands/run.py", line 414, in run
    install_hook_envs(to_install, store)
  File "/home/salar/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 221, in install_hook_envs
    _hook_install(hook)
  File "/home/salar/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 83, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
