### ISSUE TITLE
feature: add `all_files` option to hooks

### ISSUE THREAD

**Issue by tim-timman** [pre-commit/pre-commit#2405]
I have a use-case with `pytest` as a local hook that I think adding an `all_files` option to hooks would solve. The feature is already part of the CLI `pre-commit run` as the flags `--all-files`. I'm suggesting adding this as an option to hooks to work the same as the CLI flag. I hope I'm making myself clear and that it will be considered.

## Current issue
The pytest hook is setup as follows as suggestion[^1] due to tests often would make the pre-commit hook too slow[^2].
```yaml
repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: venv/bin/pytest
        language: script
        pass_filenames: false
        always_run: true
```
It works well except for when it comes to untracked files. One scenario where it doesn't is:
1. I write a test in a new file (untracked) that fails.
2. I then notice a variable name typo in another (tracked) file that I fix.
3. I add and try to commit the file in (2), but the test fails: no commit.

### (BAD) Potential workarounds
I could:
- use `SKIP=pytest git commit ...`.
  - But maybe I missed all the references of the variable and it would fail some other test.
- run temporarily mark the test as an expected fail or skip, or comment out the test; then commit.
  - But then I run the risk of forgetting and maybe breaking my test.
- move or rename the file so that `pytest` doesn't pick it up.
  - Simply not good.
- I could stash the untracked file `git stash push -u -- <file>, commit, and then unstash it.
  - Complicated, slow, and hard to remember and get right. Stashing untracked files feels wrong and can actually be dangerous if you slip up[^3].
- Simply don't work like that.
  - I don't think this situation too rare or easy to reasonably work around in another way.

## How `all_files` would solve the [Current issue](#current-issue)
If set to true, as in `all_files: true`, it should be implied that `always_run: true`. `all_files` would act just as the CLI flag `--all-files` passing all filtered, tracked, files to the hook that declared it.

**Alternative** `from_ref`
A `from_ref: <git ref>` (CLI flag `--from-ref`) assuming implied `to_ref: HEAD`, with `always_run: true` being implied if defined, functioning as the CLI flag for coherence.

Since `pytest` (as many other such tools) takes files as arguments, I could solve the issue with a configuration such as this instead:
```yaml
repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: venv/bin/pytest
        language: script
        pass_filenames: true
        always_run: true  # implied
        all_files: true  # <---
        # or from_ref: <initial commit ref>
```
Now, `pytest` would get passed _only_tracked files as arguments. This means the untracked test file isn't included when it's run and my test passes (assuming my typo didn't fail some other test).

Notice here though that `from_ref` is a _slightly_ worse option than `all_files` in the edge case if a test file was in the initial commit and hasn't since been modified (unlikely). It would in such a case not be included. `all_files` also seems by my intuition like the easier of the two to implement.

If my failing test was in a tracked file and not staged, pre-commit would've stashed those changes and we wouldn't have had a problem.

[^1]: https://github.com/pre-commit/pre-commit/issues/761#issuecomment-394167542
[^2]:
    https://github.com/pre-commit/pre-commit-hooks/issues/291#issuecomment-394167917
    I agree with the sentiment but disagree with the conclusion. I think there should be a hook and it should be up to the users whether their tests are fast enough or not.
[^3]: Archived version of [Git Stash Can Delete Ignored Files (git stash -u)](http://web.archive.org/web/20140310215100/http://blog.icefusion.co.uk:80/git-stash-can-delete-ignored-files-git-stash-u/)
