### ISSUE TITLE
prepare-commit-msg Not passing all parameters

### ISSUE THREAD

**Issue by M-Whitaker** [pre-commit/pre-commit#2406]
### search tried in the issue tracker

Yes

### describe your issue

When I run `git commit` with certain arguments I expect to get two or more arguments passed to argv of my script as per the specification:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/32771451/170735134-b8162715-0725-4375-b98c-32bbb1333320.png">
 

```python
def main(argv, argc):
     print(argv, argc)
```

Will print 
```
['tools/hooks/add-commit-template.py', '.git/COMMIT_EDITMSG'] 2
```
It looks to me from looking at your auto-created hook installed that you are passing all args to the script so it maybe I haven't configured this correctly.

Thanks

### pre-commit --version

pre-commit 2.19.0

### .pre-commit-config.yaml

```yaml
repos:
   - repo:
     hooks:
        - id: commit-template-local
          name: Provide Commit Message Template
          entry: tools/hooks/add-commit-template.py
          language: python
          stages: [ prepare-commit-msg ]
```
