### ISSUE TITLE
Ignore individual test fail, just report the failure.

### ISSUE THREAD

**Issue by harleypig** [pre-commit/pre-commit#2413]
Tried searching issues for: `ignore fail`, `ignore exit`, and `ignore`. I have also read the documentation on the pre-commit page. If this option exists I would appreciate a link to where it is in the docs or issues so I can see how I missed it. :)

pre-commit --version: 2.19.0

I'd like to mark some tests as report only. We have a lot of code that we are starting to add quality controls to, but we don't want to overwhelm the devs with a bunch of "FAIL! FIX IT BEFORE YOU CAN COMMIT!" messages.

Can a hook argument be added that will skip with a warning instead of failing? The hook would look something like
```yaml
repo: meta
  hooks:
  - warn_only: true  # all tests in this hook list will not fail
  - id: check-hooks-apply
    warn_only: true  # only this test will not fail
```

From a very quick look through the code it looks like this might be a simple addition [right above this code](https://github.com/pre-commit/pre-commit/blob/44cb80f74ac95f347fd66e0eb8d432b7cee4ca83/pre_commit/commands/run.py#L226):
```python
if hook.warn_only or hook.id.warn_only:
  # setup appropriate warning message
  retcode = 0
```
I'm not sure how the message would be constructed, but something along the lines of the skipped message would probably be good enough, with the warning message in yellow.

Also, allowing an environment variables, a la SKIP, like WARN_ONLY=check-hooks-apply pre-commit would be nice.
