### ISSUE TITLE
inconsistent result on pre-commit.ci and local machine(macOS)

### ISSUE THREAD

**Issue by peitili** [pre-commit/pre-commit#2416]
### search tried in the issue tracker

yes

### describe your issue

I found the reimport behavior is different on my local machine and precommit.ci. 
I ran `pre-commit run --all-files` and it passed locally, and I push to change to remote, then precommit.ci will trigger another auto-fix commit to correct the imports, then I pull the remote changes and trigger pre-commit locally, it will fix the autofixed imports again. 

example PR that demonstrate this.

https://github.com/tilezen/vector-datasource/pull/2087

my OS version
macOS 12.4

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
default_language_version:
    python: python2.7
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
      - id: autopep8
  - repo: https://github.com/asottile/yesqa
    rev: v0.0.11
    hooks:
      - id: yesqa
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
```

### ~/.cache/pre-commit/pre-commit.log (if present)

```
### version information

```
pre-commit version: 2.15.0
sys.version:
    3.10.0 (default, Oct 13 2021, 06:45:00) [Clang 13.0.0 (clang-1300.0.29.3)]
sys.executable: /usr/local/Cellar/pre-commit/2.15.0_1/libexec/bin/python3
os.name: posix
sys.platform: darwin
```

### error information

```
Interrupted (^C): KeyboardInterrupt: 
```

```
Traceback (most recent call last):
  File "/usr/local/Cellar/pre-commit/2.15.0_1/libexec/lib/python3.10/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/usr/local/Cellar/pre-commit/2.15.0_1/libexec/lib/python3.10/site-packages/pre_commit/main.py", line 368, in main
    return hook_impl(
  File "/usr/local/Cellar/pre-commit/2.15.0_1/libexec/lib/python3.10/site-packages/pre_commit/commands/hook_impl.py", line 237, in hook_impl
    return retv | run(config, store, ns)
  File "/usr/local/Cellar/pre-commit/2.15.0_1/libexec/lib/python3.10/site-packages/pre_commit/commands/run.py", line 419, in run
    return _run_hooks(config, hooks, skips, args, environ)
  File "/usr/local/Cellar/pre-commit/2.15.0_1/libexec/lib/python3.10/site-packages/pre_commit/commands/run.py", line 288, in _run_hooks
    current_retval, prior_diff = _run_single_hook(
  File "/usr/local/Cellar/pre-commit/2.15.0_1/libexec/lib/python3.10/site-packages/pre_commit/commands/run.py", line 194, in _run_single_hook
    retcode, out = language.run_hook(hook, filenames, use_color)
  File "/usr/local/Cellar/pre-commit/2.15.0_1/libexec/lib/python3.10/site-packages/pre_commit/languages/script.py", line 19, in run_hook
    return helpers.run_xargs(hook, cmd, file_args, color=color)
  File "/usr/local/Cellar/pre-commit/2.15.0_1/libexec/lib/python3.10/site-packages/pre_commit/languages/helpers.py", line 136, in run_xargs
    return xargs(cmd, file_args, **kwargs)
  File "/usr/local/Cellar/pre-commit/2.15.0_1/libexec/lib/python3.10/site-packages/pre_commit/xargs.py", line 165, in xargs
    for proc_retcode, proc_out, _ in results:
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 440, in result
    self._condition.wait(timeout)
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt
```
