### ISSUE TITLE
files filter does not match .tcc file (C++ template file)

### ISSUE THREAD

**Issue by andresmanelli** [pre-commit/pre-commit#2426]
### search tried in the issue tracker

"tcc", "no files to check" 

### describe your issue

I'm trying to execute the `uncrustify` hook on my C++ template files, named with a `.tcc` extension.

With the attached configuration I get:

```shell
$ pre-commit run identity --all-files
identity.................................................................Passed
- hook id: identity
- duration: 0.02s

internal/ControlledRecord.tcc
internal/ReadOnlyRecord.tcc
internal/Record.tcc

$ pre-commit run uncrustify --all-files
uncrustify...........................................(no files to check)Skipped
```

If I change the extension to `files: '\.(cc)'`, I get

```shell
$ pre-commit run identity --all-files
identity.................................................................Passed
- hook id: identity
- duration: 0.02s

src/ControlledRecord.cc

$ pre-commit run uncrustify --all-files
uncrustify...............................................................Passed
```

All the files are staged.

Am I doing something wrong? Sorry if this is a silly mistake I'm not seeing. Also, I noted [this](https://github.com/pre-commit/identify/issues/311), but I'm not sure that could be a problem.

Thank you !

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
default_language_version:
    python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
    - id: uncrustify
      args: [--replace, --no-backup, -q, -l=cpp]
      files: '\.(tcc)'
  - repo: meta
    hooks:
    - id: identity
      files: '\.(tcc)'
```
