### ISSUE TITLE
Access input file names in system hooks?

### ISSUE THREAD

**Issue by janosh** [pre-commit/pre-commit#2427]
Is there a way to access the input filename for `system` hooks? I'm trying to run `sort --output $file $file` on a set of simple Yaml files containing only key-value pairs.

```yml
repos:
  - repo: local
    hooks:
      - id: sort-simple-yaml
        name: Sort simple YAML files
        entry: sort --output $file $file
        language: system
        files: .+\.yml
```

Related: https://github.com/pre-commit/pre-commit/issues/522

I tried [`sort-simple-yaml`](https://github.com/pre-commit/pre-commit-hooks/issues/416) but couldn't get it to sort even when setting `files` explicitly.

```yml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: sort-simple-yaml
        files: ^.*\.yml$ # nothing happens
```

**Comment by asottile** [comment]
there's nothing special about `language: system` -- here's [how arguments are passed to hooks](https://pre-commit.com/#arguments-pattern-in-hooks)

as for the "couldn't get it to sort" you're going to have to provide more information -- and I'd start by not using a 2 year old version -- that also wouldn't be a framework issue so please make a detailed report on pre-commit/pre-commit-hooks

**Comment by asottile** [comment]
well your bash is wrong so your file has the literal contents:

```
b: 1\na: 2
```

**Comment by janosh** [comment]
```sh
echo 'b: 1\na: 2' >> test.yml
```

gives me this (maybe a Mac vs Linux discrepancy?):

![Screen Shot 2022-06-20 at 15 21 17](https://user-images.githubusercontent.com/30958850/174622762-e7e00309-c9ee-40d5-8d7b-57ff04f74440.png)

Anyway, it's just a toy example. What I'd really like to learn is how to get `sort` to sort files in place.

**Comment by asottile** [comment]
just tried it, seems to work fine to me?

```console
$ pre-commit run --all-files
file contents sorter.....................................................Failed
- hook id: file-contents-sorter
- exit code: 1
- files were modified by this hook

Sorting test.yml
```

**Comment by janosh** [comment]
Cool, didn't know about the `file-contents-sorter` hook. Will use that then.

Just to confirm, there's no documented way to access the file name in an `entry` field?

**Comment by janosh** [comment]
This doesn't work

```yml
repos:
  - repo: local
    hooks:
      - id: sort-simple-yaml
        name: Sort simple YAML files
        entry: sort --output
        language: system
        files: .+\.yml
```

because `sort` needs the file name passed twice, once as target for `--output` and once as input file. How to accomplish that.
