### ISSUE TITLE
pre-commit on stopped working when I upgraded to git version 2.36.1.windows.1

### ISSUE THREAD

**Issue by matteius** [pre-commit/pre-commit#2430]
### search tried in the issue tracker

yes

### describe your issue

I had added pre-commit linting checks to pipenv and they work great, I had been using them fine on Windows and today I checked in code that broke the linting build and Ive been debugging why pre-commit isn't outputting anything on windows git shell version 2.36.1.windows.1 ever since.

On my linux VM I also use pre-commit and when I run `pre-commit --version` I get:
pre-commit 2.17.0

On windows I used to get something, but now it just does nothing.  I have uninstalled and reinstalled pre-commit to no avail.  `which pre-commit` show that it is in fact on the path:

```
$ which pre-commit
/c/Users/matte/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/Scripts/pre-commit
```

Any ideas?

### pre-commit --version

pre-commit==2.19.0

### .pre-commit-config.yaml

```yaml
exclude: '^(pipenv/patched/|pipenv/vendor/|tests/)'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-builtin-literals
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-ast
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: WHEEL
  - id: forbid-new-submodules
  - id: trailing-whitespace
    exclude: .patch

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black

- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies: [
        'flake8-bugbear==20.1.4',
        'flake8-logging-format==0.6.0',
        'flake8-implicit-str-concat==0.2.0',
    ]
    exclude: tests/data

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
    files: \.py$

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.7.0
  hooks:
  - id: python-no-log-warn
  - id: python-no-eval
  - id: rst-backticks
    files: .*\.rst$
    types: [file]

- repo: local
  hooks:
  - id: news-fragment-filenames
    name: NEWS fragment
    language: fail
    entry: NEWS fragment files must be named *.(feature|behavior|bugfix|vendor|doc|trivial|removal|process).rst
    exclude: ^news/(towncrier_template.rst|.*\.(feature|behavior|bugfix|vendor|doc|trivial|removal|process).rst)
    files: ^news/

- repo: https://github.com/mgedmin/check-manifest
  rev: '0.46'
  hooks:
  - id: check-manifest
    stages: [manual]
```

### ~/.cache/pre-commit/pre-commit.log (if present)

n/a
