### ISSUE TITLE
pre-commit run error:  Running error: linter "gci" can't be disabled and enabled at one moment

### ISSUE THREAD

**Issue by Activity00** [pre-commit/pre-commit#2438]
### search tried in the issue tracker

linter "gci" can't be disabled and enabled at one moment

### describe your issue

golangci-lint run   no problem but  pre-cimmit run error show:

pre-commit run error:  Running error: linter "gci" can't be disabled and enabled at one moment

### pre-commit --version

v2.17.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/turo/pre-commit-hooks
    rev: v3.3.0  # You may version pin this if desired
    hooks:
      - id: golangci-lint  # Lint everything
```

### ~/.cache/pre-commit/pre-commit.log (if present)

no pre-commit.log file
