### ISSUE TITLE
Pre-receive hook failed

### ISSUE THREAD

**Issue by kidbomb** [pre-commit/pre-commit#2441]
### search tried in the issue tracker

pre-receive hook

### describe your issue

When trying to configure a pre-receive hook I got the following error:

> An error has occurred: FatalError: git toplevel unexpectedly empty! make sure you are not inside the `.git` directory of your repository.

My pre-receive hook looks like this:

```shell

while read -r oldrev newrev refname; do

    # Branch or tag got deleted, ignore the push
    [ "$newrev" = "$zero_commit" ] && continue

    # Calculate range for new branch/updated branch
    [ "$oldrev" = "$zero_commit" ] && range="$newrev" || range="$oldrev..$newrev"
        pre-commit run --from-ref $oldrev --to-ref $newrev --all-files

done
```

According to the documentation, the folloeing format should be used in a pre-receive hook workflow:

> pre-commit run --from-ref HEAD^^^ --to-ref HEAD: run against the files that have changed between HEAD^^^ and HEAD. This form is useful when leveraged in a pre-receive hook.

### pre-commit --version

v2.19.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
```
