### ISSUE TITLE
Emojis for `black` Not Working

### ISSUE THREAD

**Issue by adam-grant-hendry** [pre-commit/pre-commit#2442]
### search tried in the issue tracker

emoji

### describe your issue

I posted [Issue 3156](https://github.com/psf/black/issues/3156) on `black`'s repo, but it appears the issue may be with `pre-commit`.

My terminal (PowerShell 7.2.5) support emojis, but they are not getting printed specifically for `black` for some reason:

![image](https://user-images.githubusercontent.com/59346180/177451158-bc2afb02-673e-48e3-8cc2-0f411489a8f8.png)

Using `black` by itself on the commandline works just fine

![image](https://user-images.githubusercontent.com/59346180/177451194-5ad9b333-265b-4e8d-99df-3eaa343590a6.png)

I simply run `pre-commit run --all`. My `.pre-commit-config.yaml` is below and my `pyproject.toml` is

```toml
[tool.black]
line-length = 90
skip-string-normalization = true
target-version = ["py38"]
include = '.*\.pyi?$'
exclude = '\.eggs|\.git|\.mypy_cache|\.tox|\.venv|build|dist'

[tool.pycln]
all = true
include = '.*\.pyi?$'
extend_exclude = 'stubs/vtkmodules-stubs/all.pyi|stubs/vtkmodules-stubs/web/camera.pyi'
```

### pre-commit --version

2.19.0

### .pre-commit-config.yaml

```yaml
minimum_pre_commit_version: "2.19.0"
fail_fast: true
repos:
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.16.2
    hooks:
      - id: check-gitlab-ci
        name: (check-jsonschema) Check `.gitlab-ci.yml` formatted correctly

  - repo: local
    hooks:
      - id: pyupgrade
        name: (pyupgrade) Format source to latest python syntax
        language: system
        files: .*\.pyi?$
        entry: pyupgrade
        args: [
            "--py310-plus",
        ]

  - repo: local
    hooks:
      - id: pycln
        name: (pycln) Remove unused imports
        language: system
        files: .*\.pyi?$
        entry: pycln
        args: [
          "--config=pyproject.toml"
        ]

  - repo: local
    hooks:
      - id: black
        name: (black) Format source code
        language: system
        files: .*\.pyi?$
        entry: black
```

### ~/.cache/pre-commit/pre-commit.log (if present)

N/A (log is empty)

**Additional Info:**

- Black's version: `22.6.0`
- Pre-Commit's version: `2.19.0`
- Pycln's version: `2.0.1`
- OS and Python version: `Windows 10 x64-bit`
- PowerShell: `7.2.5`
- VSCode: `1.68.1`
