### ISSUE TITLE
Cannot override default 'files' option in hook

### ISSUE THREAD

**Issue by DudeNr33** [pre-commit/pre-commit#2443]
### search tried in the issue tracker

is:issue override files 

### describe your issue

According to [the docs](https://pre-commit.com/#pre-commit-configyaml---hooks) I understand it should be possible to override a top-level `files` option for individual hooks.
What I want to achieve is the following configuration:
* By default, only include files of a specific subfolder (let's call it `src` for this example)
* For one single hook, also run `pre-commit` on the top-level `pyproject.toml`

However, this does not work as I expect. With the config given below it will always output "no files to check".
If I remove the default `files`, the hook works as expected and only runs on `pyproject.toml`.

Thanks in advance for your help!

### pre-commit --version

2.19.0

### .pre-commit-config.yaml

```yaml
files: src

repos:
  - repo: local
    hooks:
      - id: echo
        name: echo
        entry: python -m echo
        language: system
        files: pyproject.toml
```
