### ISSUE TITLE
Remove need for stub package metadata in `additional_dependendencies` hooks.

### ISSUE THREAD

**Issue by mattyclarkson** [pre-commit/pre-commit#2447]
### search tried in the issue tracker

is:issue try-repo initialize

### describe your issue

I want to create some hooks in a repository from multiple languages.

For example, in `.pre-commit-hooks.yaml`

```
- id: eslint
  name: ESLint
  description: Lints ECMAScript, TypeScript and {T,J}SX files
  entry: eslint
  types:
   - javascript
  args: ["--fix"]
  language: node
  require_serial: false
  minimum_pre_commit_version: '0'
  additional_dependencies:
    - eslint@8.19.0
    - eslint-plugin-import@2.26.0
    - eslint-plugin-n@15.2.4
    - eslint-config-prettier@8.5.0
    - eslint-plugin-promise@6.0.0
    - eslint-config-standard@17.0.0
    - "@babel/eslint-parser@7.18.2"
    - "@babel/plugin-syntax-top-level-await@7.14.5"
- id: buildifier
  name: Buildifier
  description: Tool for formatting bazel BUILD and .bzl files with a standard convention.
  language: golang
  additional_dependencies:
    - github.com/bazelbuild/buildtools/buildifier@5.0.1
  files: (BUILD|WORKSPACE|.+\.bazel|.+\.bzl)$
  entry: buildifier
  args: ["--lint=fix"]
```

Using `pre-commit try-repo . buildifier --all-files` attempts to initialize the current repository, which means I need to have a stub `go.mod`. Then `pre-commit try-repo eslint --all-files` requires that I need a `package.json` stub to enable initializing the repo.

I imagine this is by design, but it would be pretty neat if we could use the `language`/`additional_dependencies` keys without having to pretend the current repo is an installable module.

Maybe a `initialize: False` which skips initializing the repo that holds the `.pre-commit-hooks.yaml`.

Happy to contribute if we feel this isn't against the design of `pre-commit`.

### pre-commit --version

2.17.0

### .pre-commit-config.yaml

```yaml
N/A
```

### ~/.cache/pre-commit/pre-commit.log (if present)

N/A
