### ISSUE TITLE
(feat): Pre-Commit Profiles (Distribution)

### ISSUE THREAD

**Issue by oliverbaehler** [pre-commit/pre-commit#2456]
# Proposal

I am seein the use-case, where we would want to have a standard pre-commit definition maintained at a central level and each project can just "subscribe" to the profile. This way we would be in charge on updating the profile but had an easy way to distribute it. For our example we have a lot of GitOps repositories, where we want to distribute a standard pre-commit config.

# Example

This would be a central maintained profile (just a pre-commit config).

**https://s3.company.com/pre-commit-profiles/standard.yaml**
```
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-added-large-files
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/zricethezav/gitleaks.git
  rev: v8.8.11
  hooks:
    - id: gitleaks-docker
      stages: [commit]

- repo: https://github.com/bridgecrewio/checkov.git
  rev: '2.1.44'
  hooks:
  - id: checkov
    verbose: true
    args: [--soft-fail]
```

Any implementation would then reference the profile but could also add its own repos.  I have put the profile link into the repos list, so that you can control, when the profile hooks are executed. But it's just an idea, i am sure there would be better layouts on how to configure profiles.

**some-project/.pre-commit-config.yaml**
```
repos:

# Representative for the hooks within the profile
- profile: https://s3.company.com/pre-commit-profiles/standard.yaml

# Run Stuff after the profile hooks are executed
- repo: https://github.com/stackrox/kube-linter.git
  rev: main
  hooks:
    - id: kube-linter
     stages: [commit]
```
This also assumes profiles are downloaded via http and then somehow combined when executed. I guess it could also make sense to use a git approach like with the hooks.

# Conclusion

Do you think something like this would be interesting for the project? Is there any other way we can already achieve something like this? Any other thoughts? Thanks, loving the project :)
