### ISSUE TITLE
Howto pass a volume with env variable in language docker_image

### ISSUE THREAD

**Issue by xhujerr** [pre-commit/pre-commit#2457]
Hello
I'm trying to run a hook from a docker image with use of the language [docker_image](https://pre-commit.com/#docker_image). 
What I'm trying to run is a [dockerized version](https://hub.docker.com/r/oxsecurity/megalinter) of [megalinter](https://github.com/oxsecurity/megalinter). 
I succeeded to run the docker standalone with command:
```
docker run -v ${PWD}:/tmp/lint:rw oxsecurity/megalinter:v6
```
The problematic part in pre-commit is mounting the volume from current directory. Obviously everyone clones the repo somewhere else, so I'm not able to provide an absolute path for the mount.

I tried following pre-commit config:
```yaml
---
repos:

-   repo: local
    hooks:
    -   id: dockerfile-provides-entrypoint
        name: megalinter-docker
        language: docker_image
        entry: -v ${pwd}:/tmp/lint:rw oxsecurity/megalinter:v6
        verbose: true
```        

With this docker fails with:
```
docker: Error response from daemon: create ${pwd}: "${pwd}" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
```

I've read the issue #758 and tried to change the entry to:
```
entry: bash -c "-v ${pwd}:/tmp/lint:rw oxsecurity/megalinter:v6"
```
But then pre-commit tries to download bash docker instead of the megalinter.

Specifying arguments separatelly:
```yaml
        entry: oxsecurity/megalinter:v6
        args:
          - -v
          - ${pwd}:/tmp/lint:rw
```          
didn't help either.

Any idea how to mount the current directory to a docker in the language "docker_image"?
