### ISSUE TITLE
Prettier EOF newline mysterious removed

### ISSUE THREAD

**Issue by innermatrix** [pre-commit/pre-commit#2465]
### search tried in the issue tracker

newline

### describe your issue

I have a file which has an EOF newline when I run prettier on it by hand, but when I run pre-commit prettier on it has the newline removed. Worse yet, this only happens locally and not in CI (GH actions) for some reason.

Here's what things look like:

```
$ ./node_modules/.bin/prettier src/main/resources/db/migration/R__triggers.sql --write && (hexdump -C src/main/resources/db/migration/R__triggers.sql | tail -2)
src/main/resources/db/migration/R__triggers.sql 49ms
00001720  5f 77 71 28 29 3b 0a                              |_wq();.|
00001727

$ pre-commit run --files src/main/resources/db/migration/R__triggers.sql prettier; (hexdump -C src/main/resources/db/migration/R__triggers.sql | tail -2)       
migration-versions.......................................................Passed
fix end of files.........................................................Passed
prettier.................................................................Failed
- hook id: prettier
- files were modified by this hook

src/main/resources/db/migration/R__triggers.sql

00001720  5f 77 71 28 29 3b                                 |_wq();|
00001726
```

`pre-commit autoupdate` did not help. Why would this happen? The system on which I am seeing the difference is running macOS 12.5. 

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks: []
  - repo: https://github.com/milin/giticket
    rev: v1.3
    hooks:
      - id: giticket
        args:
          - '--mode=regex_match'
  - repo: local
    hooks:
      - id: migration-versions
        name: migration-versions
        entry: ./.check-migration-versions.py
        language: python
        types: [sql]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        types_or: [graphql, html, javascript, json, markdown, python, sh, sql, ts, yaml, xml]
        exclude: |
          (?x)^(
              src/adhoc/.*|
              src/main/resources/db/migration/V.__.*\.sql|
              src/main/resources/db/migration/V..__.*\.sql|
              src/main/resources/db/migration/V1[0-2].__.*\.sql|
              src/main/resources/db/migration/V13[0-7]__.*\.sql
          )$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [graphql, html, javascript, json, markdown, python, sh, sql, ts, yaml, xml]
        additional_dependencies:
          - prettier@2.7.1
          - 'prettier-plugin-sql'
        exclude: |
          (?x)^(
              src/adhoc/.*|
              src/main/resources/db/migration/V.__.*\.sql|
              src/main/resources/db/migration/V..__.*\.sql|
              src/main/resources/db/migration/V1[0-2].__.*\.sql|
              src/main/resources/db/migration/V13[0-7]__.*\.sql
          )$
```
