### ISSUE TITLE
docker_image in docker container: AssertionError: Docker is either not running or not configured in this environment

### ISSUE THREAD

**Issue by YoungiiJC** [pre-commit/pre-commit#2468]
Hey there, I'm trying to use pre-commit with Docker. When I add a custom hook with `docker_image`, and run:
```bash
git add . && git commit --allow-empty -m "Test pre-commit"
```

I get the following error:
```bash
scraper_precommit
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
hadolint.................................................................An unexpected error has occurred: AssertionError: Docker is either not running or not configured in this environment
Check the log at /root/.cache/pre-commit/pre-commit.log
```

1. How to run hooks via `docker_image` in a container? I see some related (?) issues open for this already, but some clear instructions here would be solid for those new to Docker (me).
2. If there is a preferred approach over this, any advice would be appreciated!

thx, Jon

----

Here's my set up so far, based on this:
https://github.com/taghash/docker-pre-commit/blob/master/pre-commit

```Dockerfile
# Dockerfile.pre-commit

# seems the pre-commit docker image pulls an older version
# so wrote this instead...

FROM python:3.9 AS pre-commit

RUN apt-get update && apt-get install --no-install-recommends -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir pre-commit==2.2.0 && \
    mkdir /pre-commit

WORKDIR /pre-commit

COPY .pre-commit-config.yaml /pre-commit/.pre-commit-config.yaml

RUN git init . && \
    pre-commit &&  \
    pre-commit install

# using --all-files here for testing
CMD ["pre-commit","run","--all-files"]
```

```yaml
# .pre-commit-config.yaml
repos:
# Pre-commit
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: local
  hooks:
  # Docker
  - id: hadolint
    name: hadolint
    language: docker_image
    entry: hadolint/hadolint
  # Go
  - id: golangci-lint
    name: golangci-lint
    language: docker_image
    entry: golangci/golangci-lint:v1.47.2
```

```bash
# .git/hooks/pre-commit
cd $(git rev-parse --show-toplevel)

NAME=$(basename `git rev-parse --show-toplevel`)_precommit
docker ps -a | grep $NAME &> /dev/null
CONTAINER_EXISTS=$?

if [[ CONTAINER_EXISTS -eq 0 ]]; then
    docker restart $NAME && docker attach --no-stdin $NAME
else
    docker build -t custom-pre-commit -f Dockerfile.pre-commit .
    docker run -t -v $(pwd):/pre-commit --name $NAME custom-pre-commit
fi
```

**Comment by asottile** [comment]
running docker in docker isn't easy and isn't something in scope for me to help you with as that isn't a pre-commit problem

**Comment by YoungiiJC** [comment]
@asottile understood -- could you recommend alternative approach?

**Comment by asottile** [comment]
fwiw pre-commit works best when you don't try and put it in docker.  you're kinda most of the point of pre-commit and adding half a second to every execution

**Comment by YoungiiJC** [comment]
Well darn! Good to know I'm not using this the right way sooner than later.

My goal is to make it so another dev can pull my repo and use pre-commit with as little set up on their machine as possible. Was thinking Docker would be a good way to avoid local installations.

**Comment by asottile** [comment]
pre-commit installs tools entirely isolated from your system -- that's the point

**Comment by YoungiiJC** [comment]
I think I misunderstand what's going on here, then.

1. To install pre-commit I'll still need to do something like `brew install pre-commit`? How to create a repeatable set up instead?

2. When I run the hadolint hook, for example, without hadolint installed on my machine I get this:
```bash
# output
Lint Dockerfiles.........................................................Failed
- hook id: hadolint
- exit code: 1

Executable `hadolint` not found
```
```yaml
# .pre-commit-config.yaml
repos:
- repo: https://github.com/hadolint/hadolint
  rev: master
  hooks:
    - id: hadolint
```
Not sure how this is isolated from my system, since I need to do something like `brew install hadolint` to get it to work?
