### ISSUE TITLE
Add shellcheck disable for git hooks pre-commit not found message

### ISSUE THREAD

**Issue by harleypig** [pre-commit/pre-commit#2469]
### search tried in the issue tracker

post-checkout

### describe your issue

Shellcheck complains about backticks not expanding in single quotes.
```
.git/hooks/post-checkout|19 col 10 warning| Expressions don't expand in single quotes, use double quotes for that. [SC2016] [sh/shellcheck]
```
Adding `# shellcheck disable=SC2016` immediately before that line would resolve that issue.

This appears to affect all types of git hooks.

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
default_install_hook_types:
  - pre-commit
  - post-checkout

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-merge-conflict
    - id: check-shebang-scripts-are-executable
    - id: check-symlinks
    - id: check-toml
    - id: check-xml
    - id: check-yaml
    - id: destroyed-symlinks
    - id: detect-private-key
    - id: no-commit-to-branch
      args: ['--branch', 'master']

  - repo: https://MyCompany@dev.azure.com/MyCompany/MyProject/_git/guardrail
    rev: v0.1.19
    hooks:
      - id: warn-branch-on-checkout
        args: ['master', 'examples']
```
