### ISSUE TITLE
Ability to override hook options when using pre-commit run

### ISSUE THREAD

**Issue by aareman** [pre-commit/pre-commit#2471]
Thank you for this tool, it has greatly streamlined our dev process.

I am trying to use pre-commit for its intented purpose, but also as the formatter/linter with my editor. (so these dependencies are uniform across the team, and don't require system dependencies. 

I'll use `flake8` as my example

```yaml
  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-simplify
          - flake8-pie
          - flake8-alfred
          - flake8-django
          - flake8-pytest
          - flake8-pytest-style
          - wemake-python-styleguide

```
I can set this as the "flake8" program in my editor ( and it works amazingly well)

```shell
pre-commit run --files <FILE> flake8
```

However, when using mypy. my editor requires a lot of overriding of the args for mypy in order to parse the output (using neovim and null-ls)

Something like this

```lua
-- NULL LSP

local function pre_commit(hook_id)
    return {
        command = "pre-commit",
        args = { "run", "--files", "$FILENAME", hook_id }
    }
end

local formatting = require('null-ls').builtins.formatting
local diagnostics = require('null-ls').builtins.diagnostics
if vim.fn.exists(".pre-commit-config.yaml") then
require("null-ls").setup({
    on_attach = on_attach,
    sources = {
        formatting.djlint.with(pre_commit("djlint")),
        formatting.black.with(pre_commit("black")),
        formatting.isort.with(pre_commit("isort")),
        formatting.prettier.with(pre_commit("prettier")),
        diagnostics.flake8.with(pre_commit("flake8")),
        diagnostics.mypy.with(pre_commit("mypy")),
    },
    capabilities = capabilities
})
end
```

when looking at the requirments for the null-ls builtin mypy parser I see
![image](https://user-images.githubusercontent.com/10500823/181497112-5e673486-da24-4ff4-a899-97dd69cfbcef.png)
that they have many more arguments that they need to pass to mypy for it to work.

**Is there a way to add overriding keys in the pre-commit file for hooks in the `pre-commit run` command? Once it is being done for extra args, its probably a plus to add the ability to override other keys like entry and file conditions.**
