### ISSUE TITLE
Pre-commit asking for Github Credentials on "pre-commit run" etc

### ISSUE THREAD

**Issue by Indiana3714** [pre-commit/pre-commit#2477]
### search tried in the issue tracker

github credentials

### describe your issue

I'm trying to run pre-commit on this new mostly clean repo with valid pre commit yaml config files (not my first time using pre-commit), but it seems on my work computer that "poetry run pre-commit run" is asking for Github credentials via a popup window? (I'm on Windows) 

Eg it would say
[INFO] Initializing environment for https://github.com/pcqa/isort.

Why would that happen even when it's a public repo for example?

### pre-commit --version

2.20

### .pre-commit-config.yaml

```yaml
exclude: ^typings/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
        description: Simply check whether files parse as valid python.
      - id: check-builtin-literals
        description: Require literal syntax when initializing empty, or zero Python builtin types.
      - id: check-merge-conflict
        description: Check for files that contain merge conflict strings.
      - id: debug-statements
        description: Check for debugger imports and py37+ breakpoint() calls in python source.
      - id: end-of-file-fixer
        description: Makes sure files end in a newline and only a newline.
      - id: trailing-whitespace
        description: Trims trailing whitespace
      - id: requirements-txt-fixer
        description: Sorts entries in requirements.txt
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
```
