### ISSUE TITLE
pre-commit hook for eslint working locally but not in ci : additional_dependencies not found

### ISSUE THREAD

**Issue by lolrenx** [pre-commit/pre-commit#2487]
### search tried in the issue tracker

yes

### describe your issue

Integrating pre-commit in a monolith project in order to use it as the single tool for code quality. 
linting works fine locally but throws an error when run on githib action, logs attached at bottom. 
I understand eslint can't find the following dependency but I'm not really sure how to point it to the right place.
Maybe this is due to the js project being one folder deep ? 
```       
additional_dependencies:
          - eslint-plugin-prettier
```

project structured as follow :

```
 tree . -a -L 2 --dirsfirst
.
├── .github
│   ├── workflows
│   └── dependabot.yml
├── assets
...
├── firmwares
...
├── front
│   ├── node_modules
│   ├── public
│   ├── src
│   ├── .eslintrc.json
│   ├── .gitignore
│   ├── .prettierrc
│   ├── README.md
│   ├── jsconfig.json
│   ├── package-lock.json
│   └── package.json
├── .gitignore
├── .jscpd.json
├── .mega-linter.yml
├── .pre-commit-config.yaml
├── README.md
├── config.py
├── debug.py
├── devices.py
├── front_url
├── global_state.py
├── install
├── maintenance.py
├── run
├── run.py
├── setup.cfg
├── steps.py
└── tasks.py
```

`.pre-commit-config.yaml` at the root of the project and eslint living in the /front directory. 

CI workflow as follow: 
```yaml
---
name: Lint

on:
  pull_request:
    branches-ignore:
      - PRODUCTION

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

...

jobs:
  pre-commit-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: actions/setup-node@v3  # tried CI workflow with and without this action
      - run: npm install eslint --global  # tried CI workflow with and without this action
      - run: npm install eslint-config-prettier --global # tried CI workflow with and without this action
      - uses: pre-commit/action@v3.0.0
  ...

```

```
eslint...................................................................Failed
- hook id: eslint
- exit code: 2

Oops! Something went wrong! :(

ESLint: 8.22.0

ESLint couldn't find the plugin "eslint-plugin-prettier".

(The package "eslint-plugin-prettier" was not found when loaded as a Node module from the directory "/home/runner/work/room-emotion/room-emotion/front".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-prettier@latest --save-dev

The plugin "eslint-plugin-prettier" was referenced from the config file in "front/.eslintrc.json".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
```

[logs_21.zip](https://github.com/pre-commit/pre-commit/files/9358999/logs_21.zip)

### pre-commit --version

2.18.1

### .pre-commit-config.yaml

```yaml
---
repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--safe, --quiet]

  - repo: https://github.com/PyCQA/isort
    rev: "5.10.1"
    hooks:
      - id: isort
        args: ["--profile", "black"]
        additional_dependencies: [toml]
        exclude: docs/tutorials

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.1.0]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: check-yaml
      - id: check-toml
      - id: check-executables-have-shebangs

        exclude: _pytest/(debugging|hookspec).py
        language_version: python3

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        name: autoflake
        args:
          [
            "--in-place",
            "--remove-unused-variables",
            "--remove-all-unused-imports",
          ]
        language: python
        files: \.py$

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: [--config=setup.cfg]
        language_version: python3
        additional_dependencies:
          - flake8-typing-imports==1.12.0
          - flake8-docstrings==1.5.0
          - flake8-tidy-imports==4.7.0

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.8.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.0"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-use-type-annotations

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        files: ^(src/|testing/)
        args: []
        additional_dependencies:
          - iniconfig>=1.1.0
          - py>=1.8.2
          - attrs>=19.2.0
          - packaging
          - tomli
          - types-atomicwrites
          - types-pkg_resources

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.22.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        additional_dependencies:
          - eslint@8.22.0
          - eslint-plugin-prettier
          - eslint-config-airbnb

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
```

```json package.json
{
  "name": "front",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "eslint-config-prettier": "^8.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "sass": "^1.54.0",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "PORT=8001 react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "eslint": "^8.21.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsx-a11y": "^6.6.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.30.1",
    "eslint-plugin-react-hooks": "^4.6.0",
    "prettier": "2.7.1",
    "pretty-quick": "^2.0.2",
    "twilio": "^3.80.0"
  }
}
```
