### ISSUE TITLE
No files to check

### ISSUE THREAD

**Issue by hgrw** [pre-commit/pre-commit#2490]
### search tried in the issue tracker

"no files to check"

### describe your issue

I have been using pre-commit on a Python project without issue. Works great. Trying to set up pre-commit on a few embedded C++ projects and just cannot get pre-commit to detect staged files. Tried multiple machines and completely different repos. Following the exact process I used on my python project. FWIW, when I initially set up one of the embedded C++ projects the pre-commit hooks were running my linters. After a fresh clone I can't get it to work on any of my projects.

# Environment
OS - ubuntu 22
virtualenv (using Pipfile):
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]
obsidianhtml = "*"
cpplint = "*"
clang-format = "*"
clang-tidy = "*"

[requires]
python_version = "3.10"
```

# Steps to reproduce
I am using a simple example repo on gitlab: [https://gitlab.com/hgrw/hil-target-stm32](https://gitlab.com/hgrw/hil-target-stm32)

1. Install virtualenv: `pipenv install --dev`
2. Install pre-commit hooks: `pipenv run pre-commit install -t pre-commit`
3. observe pre-commit hook script (looks fine)
```
#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03

# start templated
INSTALL_PYTHON=/home/mars/.local/share/virtualenvs/hil-target-stm32-Anq3Q4I2/bin/python
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
# end templated

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
```
4. make a change to a file tracked by git. In this case I make a change to a file that will cause clang-format to edit the file in the pre-commit hook. `git add application/ && git status`
```
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   application/core/application.cpp

```
5. commit the file and observe skipped hooks. `git commit -m "find my files!"`
```
cppcheck.............................................(no files to check)Skipped
cpplint..............................................(no files to check)Skipped
clang-format.........................................(no files to check)Skipped
obsidianhtml.........................................(no files to check)Skipped
[main 1e74741] find my files!
 1 file changed, 1 insertion(+), 1 deletion(-)
```
I have had a play around with the pre-commit hook script (below) and teased out the invocation, `"$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"`. Looking at the underlying call I can't see any issues. PS I have tried this on multiple machines on multiple completely different embedded C++ repos and just can't get pre-commit to see my staged files. If this is user error, surely there must be some documentation that highlights the issue. 

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: cppcheck
        name: cppcheck
        stages: [commit]
        language: system
        entry: pipenv run cppcheck --error-exitcode=1 application/
        types: [python]

      - id: cpplint
        name: cpplint
        stages: [commit]
        language: system
        entry: pipenv run cpplint application/**/*.cpp application/**/*.hpp
        types: [python]

      - id: clang-format
        name: clang-format
        stages: [commit]
        language: system
        entry: pipenv run clang-format -i application/**/*.cpp application/**/*.hpp
        types: [python]

      - id: build
        name: build
        stages: [push]
        language: system
        entry:  cmake --build cmake-build-release/ --target hil-target-stm32 -j 6 && \
                cmake --build cmake-build-utest/ --target all -j 6
        types: [python]

      - id: unit-test
        name: unit-test
        stages: [push]
        language: system
        entry:  find . -type f -iname "runAllTests-*" -execdir sh -c 'for n; do $n || exit 1; done' sh {} +
        types: [python]

      - id: obsidianhtml
        name: obsidianhtml
        stages: [commit]
        language: system
        entry: pipenv run obsidianhtml -i documentation/site-generator-config.yaml
        types: [python]
```
