### ISSUE TITLE
file-contents-sorter `files:` pattern does not override default

### ISSUE THREAD

**Issue by ww-daniel-mora** [pre-commit/pre-commit#2492]
### search tried in the issue tracker

Github Issues

### describe your issue

Attempting to configure the file-contents-sorter with a file pattern that conflicts with the default regex results in `no files to check`

The documentation for the `files:` hook parameter indicates that it "overrides" the default, but, this does not appear to be the case, at least for the file-contents sorter https://pre-commit.com/index.html#config-files

This config works
``` yaml
files: '^(compile_pipeline_library/.*|.cspell.*)$'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: file-contents-sorter
      files: ^\.cspell.*\.txt$
```

This config does not work but I would expect it to since `files:` is supposed to override the default.
``` yaml
files: 'compile_pipeline_library/.*$'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: file-contents-sorter
      files: ^\.cspell.*\.txt$
```

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
files: 'compile_pipeline_library/.*$'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: file-contents-sorter
      files: ^\.cspell.*\.txt$
```
