### ISSUE TITLE
dependencies issue for custom python code

### ISSUE THREAD

**Issue by mathildeHermet** [pre-commit/pre-commit#2493]
### search tried in the issue tracker

dependencies, virtualenv

### describe your issue

I want to execute a script each time some files "/specific_dir/*.yaml" files are modified in the commit.
Problem is that it relies on these libraries  GvGen, pyyaml, six and Graphviz, and when I execute pre-commit it cannot execute my script due to the absence of these libraries.
I installed this libraries through pip install in my virtualenv. I installed pre-commit with pip in that same virtual env.
I try to set a requirements.txt file and specify this dependencies in it, then use 
```yaml
 additional_dependencies: [-r, /some/dirs/requirements.txt]
 ```
 and for the requirements.txt
 ```
GvGen==1.0
pyyaml==6.0
six==1.16.0
Graphviz==0.20.1
``` 
 It did not work

Then I have try to use 
```yaml
additional_dependencies: [six, Graphviz, GvGen, pyyaml]
```
It did not work

Maybe I missed something in the documentation or in the issues but if not it could be an interesting feature to add.
 

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        additional_dependencies: [-r, /somewhere/there/is/a/dir/requirements.txt]
        entry: pip freeze --all
        pass_filenames: false
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: render-graph
        name: render-graph
        stages: [commit]
        language: python
        entry: tools/render-graph.py --input
        verbose: true
        always_run: true
        additional_dependencies: [six, Graphviz, GvGen, pyyaml]
        pass_filenames: false
```

### ~/.cache/pre-commit/pre-commit.log (if present)

cat: /home/mhermet/.cache/pre-commit/pre-commit.log: No such file or directory
