### ISSUE TITLE
Commitizen(commit-msg) duplicate entries in output

### ISSUE THREAD

**Issue by Berk-Tosun** [pre-commit/pre-commit#2494]
### search tried in the issue tracker

duplicate hooks no files to check repeated

### describe your issue

I have a new project where I want to use the attached .pre-commit-config.yaml, which includes [commitizen](https://github.com/commitizen-tools/commitizen).

When I make a commit:

Current behavior:

> (venv) ...>git commit -m "feat(main): add fun"
>   black....................................................................Passed
>   flake8...................................................................Passed
>   bandit...................................................................Passed
>   isort....................................................................Passed
>   fix end of files.........................................................Passed
>   don't commit to branch...................................................Passed
>   black................................................(no files to check)Skipped
>   flake8...............................................(no files to check)Skipped
>   bandit...............................................(no files to check)Skipped
>   isort................................................(no files to check)Skipped
>   don't commit to branch...................................................Passed
>   commitizen check.........................................................Passed
>   [ad 0e915e7] feat(main): add fun
>    12 files changed, 450 insertions(+)
>     ...

Expected behavior:

> (venv) ...>git commit -m "feat(main): add fun"
> black....................................................................Passed
> flake8...................................................................Passed
> bandit...................................................................Passed
> isort....................................................................Passed
> fix end of files.........................................................Passed
> don't commit to branch...................................................Passed
> commitizen check.........................................................Passed
> [ad 0e915e7] feat(main): add fun
>   12 files changed, 450 insertions(+)
>   ...

Steps to reproduce:

It is a new project / clean environment. In a fresh virtual env, using python 3.8.7.

1. git init
2. pip install pre-commit
3. pre-commit install -t pre-commit -t commit-msg --install-hooks
4. git add
5. git commit

Many thanks,
Berk

### pre-commit --version

2.20

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: no-commit-to-branch
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.32.2
    hooks:
      - id: commitizen
```

**Comment by Berk-Tosun** [comment]
Could you please check the issue at the commitzen repo? There seems to be a problem not related to hooks-stages.

**Comment by asottile** [comment]
it has nothing to do with commitizen -- that one has `stages` set "correctly" already

**Comment by Berk-Tosun** [comment]
## Explanation:

Stages are specified for commitizen only (https://github.com/commitizen-tools/commitizen/blob/8cb1e22d72abd855f221556f2a1c8fc0ddded109/.pre-commit-hooks.yaml#L9). For the other hooks, stages are not specified and they use the default value of `all stages`. So the repeated messages are shown because the hooks are called at both `pre-commit` and `commit-msg` stages.

## Solution:

1. Update .pre-commit-config.yaml by adding `default_stages`

```yaml
default_stages: [commit]
repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: no-commit-to-branch
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.32.2
    hooks:
      - id: commitizen
 ```

2. Install the same way
```bash
pre-commit install -t pre-commit -t commit-msg --install-hooks
```
