### ISSUE TITLE
Don't resolve symbolic links to e.g. bash on installation time

### ISSUE THREAD

**Issue by frlan** [pre-commit/pre-commit#2497]
### search tried in the issue tracker

yes

### describe your issue

I'm using a bash from Nix-package manager on macOS. When I'm installing the hook, the shebang is updated with the resolved symlink -- which leads into the Nix-store:

```
% cat pre-commit
#!/nix/store/jcwj04sh5kpwck3l9j9q0xgm9kj24mrz-bash-5.1-p16/bin/bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03
``` 

Unfortunately this link might go away on next update of my user env as nix is relying on symlinking into the store:

```
 % echo $PATH
/Users/frlan/.nix-profile/bin
```

and garbage collecting later. 

Would it be possible to just use /usr/bin/env bash or something like that instead of following the symlink during installation time?

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
exclude: ^secrets/|^appenv$
repos:
- hooks:
  - exclude: "(?x)^(\n  secrets/|environments/.*/secrets\\.cfg|\n  .*\\.patch\n)$\n"
    id: trailing-whitespace
  - exclude: "(?x)^(\n  environments/.*/secrets\\.cfg|\n  .*\\.patch\n)$\n"
    id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-json
  - id: check-xml
  - id: check-toml
  - id: detect-private-key
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
- hooks:
  - args:
    - --profile
    - black
    - --filter-files
    id: isort
    name: isort (python)
  repo: https://github.com/pycqa/isort
  rev: 5.10.1
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 22.3.0
```
