### ISSUE TITLE
Custom network with language: Docker

### ISSUE THREAD

**Issue by benr77** [pre-commit/pre-commit#2498]
### search tried in the issue tracker

docker network

### describe your issue

When I use `language: docker` how can I specify which Docker network I want the container to connect to?

This can be done with the docker build command, such as:

```bash
docker build --network=mynetwork .
```

Looking at the source code for the Docker language I can't see how this is currently achievable. 

Thanks

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:
    - repo: local
      hooks:
          - id: phpunit-tests
            name: PHPUnit Tests
            language: docker
            entry: /src/vendor/bin/simple-phpunit
            args: [ '--testsuite=Unit' ]
            always_run: true
            pass_filenames: false
            stages: [ commit ]
```
