### ISSUE TITLE
pre-commit run --all-files only runs on staged files (re-occurrence of error?)

### ISSUE THREAD

**Issue by kbalk** [pre-commit/pre-commit#2499]
### search tried in the issue tracker

is:issue is:open all-files 

### describe your issue

This looks like a repeat of [Issue 1394](https://github.com/pre-commit/pre-commit/issues/1394) however, I'm using the pre-commit command as suggested, i.e., `pre-commit run --all-files`

If I stage the file (i.e., `git add badfile.py`), then `pre-commit run --all-files` command will find errors, otherwise it will not.

### pre-commit --version

2.19.0

### .pre-commit-config.yaml

```yaml
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
        - id: trailing-whitespace
    - repo: local
      hooks:
        - id: pylint
          name: pylint
          language: system
          types: [python]
          exclude: ^tests/
          # -j 0  Auto-detect the number of processors available to use.
          # --score n  Don't activate the evaluation score.
          entry: "pylint -j 0 --score n --disable=R0801 --load-plugins pylint.extensions.mccabe"
```
