### ISSUE TITLE
Cannot pass arguments to black hook

### ISSUE THREAD

**Issue by r-bird** [pre-commit/pre-commit#2501]
### search tried in the issue tracker

is:issue black in:title

### describe your issue

I was trying to pass the `--include` argument to black, as described in the [black docs](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html) to include another file type `*.spec` with the pattern `(\.pyi?|\.spec)$` (`\.pyi?$` is the default).

Is there any way to configure black from pre-commit?
The `pyproject.toml` is also completely ignored, when using pre-commit.

### pre-commit --version

2.15.0

### .pre-commit-config.yaml

```yaml
- repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        files: '(\.pyi?|\.spec)$' # might be necessary?
        args: ['--include', '(\\.pyi?|\\.spec)$'] # does not work (backslashes must be escaped here)
        args: ['--include=(\\.pyi?|\\.spec)$'] # also does not work
```
