### ISSUE TITLE
pre-commit autoupdate changes poetry 1.2.0 to poetry 1.2.0rc1

### ISSUE THREAD

**Issue by eviltwin** [pre-commit/pre-commit#2507]
### search tried in the issue tracker

pre-commit autoupdate rc

### describe your issue

I have a `.pre-commit-config.yaml` that includes two checks using poetry:

```
  - repo: https://github.com/python-poetry/poetry
    rev: 1.2.0
    hooks:
      - id: poetry-check
        language_version: python3.9
      - id: poetry-lock
        args: ["--check"]
        language_version: python3.9
```

The latest release of poetry is 1.2.0, following two release candidates (1.2.0rc0 and 1.2.0rc1, which were marked as pre-releases), as shown on their releases page on PyPI: https://pypi.org/project/poetry/#history

When running `pre-commit autoupdate` in my repository, `pre-commit` is changing my poetry hook to `rev: 1.2.0rc1`. I suspect this is because `0rc1` comes last lexicographically when compared to the other minor version options for the 1.2 series of releases.

I would expect `pre-commit` to exclude pre-releases entirely in favour of stable releases, or understand that `0rc1` comes _before_ `0`.

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
  - repo: https://github.com/python-poetry/poetry
    rev: 1.2.0
    hooks:
      - id: poetry-check
        language_version: python3.9
      - id: poetry-lock
        args: ["--check"]
        language_version: python3.9
  - repo: local
    hooks:
      - id: pre-commit-django-migrations
        name: Check django migrations
        entry: ./manage.py makemigrations --noinput --check --dry-run
        language: system
        types: [python]
        pass_filenames: false
```
