### ISSUE TITLE
output mode replace cannot be used when configured with pre-commit

### ISSUE THREAD

**Issue by timharsch** [pre-commit/pre-commit#2514]
### search tried in the issue tracker

replace

### describe your issue

I have a config file at:  .config/.terraform-docs.yaml

It contains this section:
```yaml
output:
  file: ""
  mode: replace
  template: |-
    {{ .Content }}
```

If i do `git commit` and I have staged an update to my template in  .config/.terraform-docs.yaml, then I always get the error:
```
terraform-docs...........................................................Failed
- hook id: terraform-docs-go
- files were modified by this hook
```

No matter if the content is exactly as it was before.  I think since the replace operation generates a new file for README.md every time and does not know that it is the exact same content as before it trips the error.

My workaround was to `git commit --no-verify` to force the commit through.  So long as there are no changes to `.config/.terraform-docs.yaml` then the terraform-docs command does not run 🤷 

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
- repo: https://github.com/terraform-docs/terraform-docs
  rev: v0.16.0
  hooks:
    - id: terraform-docs-go
      files: .config
      types: [yaml]
      args: ["markdown", "table", "--output-file", "README.md", "."]
```

### ~/.cache/pre-commit/pre-commit.log (if present)

not present
