### ISSUE TITLE
Updating .pre-commit-config.yaml to exclude some file for cpplint, but not working.

### ISSUE THREAD

**Issue by umiswing** [pre-commit/pre-commit#2515]
Hello! I want ```pre-commit``` to exclude some files when using ```cpplint```. So I set ```.pre-commit-config.yaml``` in the root of my repo like this:
```yaml
-   repo: local
    hooks:
    -   id: cpplint-cpp-source
        name: cpplint
        description: Check C++ code style using cpplint.py.
        entry: bash ./tools/codestyle/cpplint_pre_commit.hook
        language: system
        files: \.(c|cc|cxx|cpp|cu|h|hpp|hxx)$
        exclude: path/to/myfile.h
```

But the update of .pre-commit-config doesn't work, it keeps checking ```myfile.h```. I try uninstalling and installing pre-commit again, but it still does not work. I also try ```pre-commit install-hooks``` and ```pre-commit install --install-hooks```, but it's still not working.

My pre-commit version: 1.10.4
My cpplint version: 1.6.0
My python version: 3.7.13

Here is my ```cpplint_pre_commit.hook```
```shell
#!/bin/bash

TOTAL_ERRORS=0

readonly VERSION="1.6.0"

version=$(cpplint --version)

if [[ ! $TRAVIS_BRANCH ]]; then
  # install cpplint on local machine.
  if ! [[ $version == *"$VERSION"* ]]; then
    pip install cpplint==1.6.0
  fi
  # diff files on local machine. 
  files=$(git diff --cached --name-status | awk '$1 != "D" {print $2}')
else
  # diff files between PR and latest commit on Travis CI. 
  branch_ref=$(git rev-parse "$TRAVIS_BRANCH")
  head_ref=$(git rev-parse HEAD)
  files=$(git diff --name-status $branch_ref $head_ref | awk '$1 != "D" {print $2}')
fi
# The trick to remove deleted files: https://stackoverflow.com/a/2413151
for file in $files; do
    if [[ $file =~ ^(patches/.*) ]]; then
        continue;
    else
        cpplint --filter=-readability/fn_size,-build/include_what_you_use,-build/c++11,-whitespace/parens $file;
        TOTAL_ERRORS=$(expr $TOTAL_ERRORS + $?);
    fi
done

exit $TOTAL_ERRORS
```
