### ISSUE TITLE
Not working with all files

### ISSUE THREAD

**Issue by corderop** [pre-commit/pre-commit#2517]
### search tried in the issue tracker

ignoring files

### describe your issue

I noticed that pre-commit was ignoring some files. I have made sure the files were staged. Even with `--all-files` option pre-commit is ignoring it. Example from my terminal:

```bash
$ git status  

On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   src/folder/__init__.py

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   src/folder/github/__init__.py

$ git commit                                

[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/user/.cache/pre-commit/patch1663410504-3222.
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...........................................(no files to check)Skipped
black....................................................................Passed
isort....................................................................Passed
flake8...................................................................Passed
[INFO] Restored changes from /home/user/.cache/pre-commit/patch1663410504-3222.
Aborting commit due to empty commit message.

...

$ git status                            

On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   src/folder/github/__init__.py

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   src/folder/__init__.py

$ git commit

[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/user/.cache/pre-commit/patch1663410543-3509.
trim trailing whitespace.............................(no files to check)Skipped
fix end of files.....................................(no files to check)Skipped
check yaml...........................................(no files to check)Skipped
black................................................(no files to check)Skipped
isort................................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
[INFO] Restored changes from /home/user/.cache/pre-commit/patch1663410543-3509.
Aborting commit due to empty commit message.
```

After debugging this, I noticed that pre-commit was ignoring files inside `github` folder because I had `.git` in the exclude files. Not sure this should be like this. I have solved it in case this is considered a bug, although I have solved it by removing this unnecessary option.

### pre-commit --version

2.16.0

### .pre-commit-config.yaml

```yaml
exclude: 'docs|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
        additional_dependencies: [flake8-isort]
```
