### ISSUE TITLE
Support passing `args` when using `try-repo`. 

### ISSUE THREAD

**Issue by wheelerlaw** [pre-commit/pre-commit#2522]
### search tried in the issue tracker

try-repo args

### describe your issue

In the `.pre-commit-config.yaml`, it is possible to specify some additional arguments that get passed to the hook, like so:

```
- repo: https://github.com/adrienverge/yamllint
  rev: v1.26.3
  hooks:
  - id: yamllint
    args: [--format, parsable, --strict]
    exclude: charts/templates
```

But when developing a hook using the `try-repo` option, there doesn't appear to be a way to pass in additional arguments similar to the `args` field in the config. Ideally, something would look like this:

```
pre-commit try-repo ../my-new-hook helmlint --all-files --args "--additional --arguments"
```

...or something similar. 

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
n/a
```
