### ISSUE TITLE
Only first remote branch available in environment variable PRE_COMMIT_REMOTE_BRANCH

### ISSUE THREAD

**Issue by Sleepingwell** [pre-commit/pre-commit#2523]
I have written hook that I wish to run only when pushing to branches that match certain patterns (e.g. *main*). This is working fine when I only push to a single branch, but if I push to more than one, only the first appears in the environment variable *PRE_COMMIT_REMOTE_BRANCH* and hence I might not detect the branches of interest.

For reference, my hook script is (in file *.pre-commit-pytest.py*)

```python
import sys
import os
from subprocess import call

remote_branch = os.environ.get("PRE_COMMIT_REMOTE_BRANCH", "").strip().split("/")[-1]

if remote_branch in ("test", "devel", "main"):
    sys.exit(call("pytest", shell=True))
```

Which I register with

```yaml
repos:
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: venv/bin/python
        language: script
        always_run: true
        pass_filenames: false
        stages: [push]
        args:
             - .pre-commit-pytest.py
```

I realise the way I get *remote_branch* would probably not work if there were multiple remote branches listed in *PRE_COMMIT_REMOTE_BRANCH*, but I have inspected that manually.

If I push with `git push origin branch-name:test` all is good, but not when I push with, say

```bash
git push origin branch-name branch-name:test
```
