### ISSUE TITLE
"Failed" is confusing

### ISSUE THREAD

**Issue by trondhindenes** [pre-commit/pre-commit#2529]
### search tried in the issue tracker

Failed

### describe your issue

I'm completely new to pre-commit, I inherited a repo where this pre-commit is set up, and among other things it uses the `black` formatter. 

I was super-confused by it returning "Failed" on me - it ran black which did some reformattings for me, and then there's a big ref "Failed" error. I've looked at the documentation, but I can't find anywhere a mention of what that actually means. I thought there was something wrong with my setup or my black version or something to cause the pre-commit hoook to not run as it should.

Now I've learned that "Failed" in this context actually means "the pre-commit hook made some changes that you have to commit again" and I would say that that's bad UX. I totally get it in a CI scenario where one wants to check that all files are formatted correctly etc and fail if they aren't, but when running pre-commit as part of an active development process on my workstation, "Failed" makes no sense.

### pre-commit --version

2.12.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - '--skip-string-normalization'
```
```


### ~/.cache/pre-commit/pre-commit.log (if present)

_No response_
