### ISSUE TITLE
Github authentication issue with private hooks repo in GH actions 

### ISSUE THREAD

**Issue by russoale** [pre-commit/pre-commit#2532]
### search tried in the issue tracker

private, repo, tox

### describe your issue

Hi and thank you for this awesome tool. 
I am trying to run pre-commit hooks via tox in github actions for a private hook. Locally this works fine but I am struggling with Github authentication in GH actions.

```
[INFO] Initializing environment for https://github.com/<private-company-org>/hooks.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: could not read Username for 'https://github.com/': No such device or address
```

GH Action: 
```yml
jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install tox
        run: pip install tox

      - name: Cache tox environments
        uses: actions/cache@v3
        with:
          path: .tox
          key: tox-check-${{ hashFiles('requirements.txt') }}

      - name: Cache pre-commit environments
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-check-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run tox
        env:
          GITHUB_TOKEN: ${{ secrets.CELOBOT_GITHUB_TOKEN }}
        run: tox -e check
``` 

pyproject.toml:
```toml
[testenv:check]
description = Run pre-commit hook check on all files
basepython = {env:TOXPYTHON:python3.8}
passenv = *
commands =
    pre-commit run -a
```

### pre-commit --version

pre-commit 2.19.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/<private-company-org>/hooks
    rev: vx.x.x
    hooks:
      - id: ...
```
