### ISSUE TITLE
[question] How to get staged files parameter?

### ISSUE THREAD

**Issue by Gumichocopengin8** [pre-commit/pre-commit#2533]
### search tried in the issue tracker

yes

### describe your issue

First, thank you for making such a useful framework.

I currently use custom hooks to run `prettier` and `eslint`. The reason why I didn't use the supported hooks is that I already have commands for them, and didn't want to rely on supported hooks. 
When custom hooks are used, I cannot find a way to get staged files parameter in .pre-commit-config.yaml. 
Are there any ways to do that?

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
pos:
   - repo: local
     hooks:
       - id: js-lint-check
         name: JS Lint
         entry: bash -c 'make check-eslint check-prettier'
         language: system
         files: 'webui/react/src/'
         types_or: [javascript, jsx, ts, tsx]
         pass_filenames: false

```
`check-eslint` runs eslint **/*.{js,ts,tsx,jsx} and `check-prettier` runs prettier --check **/*.{js,ts,tsx,jsx}
However, I wanna run commands only for staged files instead of entire project directory
