### ISSUE TITLE
eslint works locally but fails on CI

### ISSUE THREAD

**Issue by antocuni** [pre-commit/pre-commit#2537]
### search you tried in the issue tracker

"eslint works locally". But most importantly, I checked recent issues since it started to happen only recently

### describe your issue

I have this PR:
https://github.com/pyscript/pyscript/pull/806

the pre-commit eslint step always fail in CI, but passes locally:

[pre-commit results](https://results.pre-commit.ci/run/github/461710233/1664807662.4xQMoB8hS9eE6qmYYD8j5A)

```
(venv) homer pyscript $ pre-commit run --all-file
check builtin type constructor use.......................................Passed
check for case conflicts.................................................Passed
check docstring is first.................................................Passed
check that executables have shebangs.....................................Passed
check json...............................................................Passed
check toml...............................................................Passed
check xml................................................................Passed
check yaml...............................................................Passed
detect private key.......................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
bandit...................................................................Passed
black....................................................................Passed
codespell................................................................Passed
flake8...................................................................Passed
isort (python)...........................................................Passed
Pretty format YAML.......................................................Passed
pyupgrade................................................................Passed
eslint...................................................................Passed
```

As you can see in the PR, other people tried and the result is still the same: it works locally but fails on CI.
FWIW, it always worked flawlessly until this PR.

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
# This is the configuration for pre-commit, a local framework for managing pre-commit hooks
#   Check out the docs at: https://pre-commit.com/

default_stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
        exclude: tsconfig.json
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
        exclude: \.min\.js$
    -   id: trailing-whitespace

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        args:
        -   --skip=B101,B201

-   repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
    -   id: black


-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
    -   id: codespell  # See 'setup.cfg' for args

-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8  # See 'setup.cfg' for args
        additional_dependencies: [flake8-bugbear, flake8-comprehensions]

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        args: [--profile, black]

-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: pretty-format-yaml
        args: [--autofix, --indent, '4']
        exclude: .github/ISSUE_TEMPLATE/.*\.yml$

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.38.2
    hooks:
    -   id: pyupgrade
        args:
        -   --py310-plus

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.23.1
    hooks:
    -   id: eslint
        files: pyscriptjs/src/.*\.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
        -   eslint
        -   eslint-plugin-svelte3
        -   typescript
        -   '@typescript-eslint/eslint-plugin'
        -   '@typescript-eslint/parser'

# Commented out until mdformat-myst supports custom extensions
# See https://github.com/executablebooks/mdformat-myst/pull/9
# -   repo: https://github.com/executablebooks/mdformat
#     rev: 0.7.14 # Use the ref you want to point at
#     hooks:
#     -   id: mdformat
#         additional_dependencies:
#         -   mdformat-gfm
#         -   mdformat-myst
#         -   mdformat-black
```

### ~/.cache/pre-commit/pre-commit.log (if present)

not present
