### ISSUE TITLE
macOS + SmartGit + pre-commit = 💔 

### ISSUE THREAD

**Issue by andreivt** [pre-commit/pre-commit#2538]
### search you tried in the issue tracker

smartgit pre-commit wrong path

### describe your issue

I'm running macOS 12.4, zsh, asdf via homebrew, and got a project which uses `pre-commit`. Everything is working via terminal, but not SmartGit. More specifically, I cannot commit. 
One of the errors I get:
```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- diffy (LoadError)
 from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

Added an `echo $PATH` in `.git/hooks/pre-commit`:
`/Applications/SmartGit.app/Contents/Resources/git/libexec/git-core:/Applications/SmartGit.app/Contents/Resources/git/bin:/Applications/SmartGit.app/Contents/Resources:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/utilisateur/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/opt/homebrew/opt/postgresql@12/bin:/opt/homebrew/bin:/opt/homebrew/sbin`

I did found [other tickets](https://github.com/pre-commit/pre-commit/issues?q=is%3Aissue+smartgit), but nothing worked for me.

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: bla
        name: bla
        language: system
        entry: ruby .pre-commit/my_custom_script.rb --before
        files: \.(rb|rake|jbuilder|js|jsx|ts|tsx)$
        require_serial: true
```
