### ISSUE TITLE
Failure when using check-hooks-apply and forbid-new-submodules together

### ISSUE THREAD

**Issue by rrrix** [pre-commit/pre-commit#2541]
### search you tried in the issue tracker

is:issue forbid-new-submodules check-hooks-apply 

### describe your issue

Example repository reproducing the problem: https://github.com/rrrix/forbid-new-submodules-is-not-useless 

It appears `check-hooks-apply` doesn't quite know how to handle `forbid-new-submodules`. 

After reading through the code for [check_hooks_apply.py:21](https://github.com/pre-commit/pre-commit/blob/028efcbd879ccdac7514ea4334462841bb0ca2c0/pre_commit/meta_hooks/check_hooks_apply.py#L21-L22) I determined a workaround is to add `always_run: true`:

```yaml
    hooks:
      - id: forbid-new-submodules
        always_run: true
```

Without `always_run: true`, running `pre-commit run --all-files` results in the following error:

```text
$ pre-commit run --all-files
Check hooks apply to the repository......................................Failed
- hook id: check-hooks-apply
- exit code: 1

forbid-new-submodules does not apply to this repository

forbid new submodules................................(no files to check)Skipped
```

### pre-commit --version

pre-commit 2.19.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: forbid-new-submodules
```
