### ISSUE TITLE
pre-commit picks up files unchanged between HEAD and origin/HEAD in CI

### ISSUE THREAD

**Issue by duganth** [pre-commit/pre-commit#2544]
### search you tried in the issue tracker

wrong files, unchanged files

### describe your issue

We are running pre-commit in CI on Buildkite in a container with the following command:

`pre-commit run --from-ref origin/HEAD --to-ref HEAD --config docker/pre-commit/ci.pre-commit-config.yaml`

The problem is _sometimes_ pre-commit will pick up files that were not changed on the branch. An observation I made is this usually occurs after a rebase but it does not happen after every rebase so I am not 100 percent sure. Also, if the job is run again eventually pre-commit picks up the correct files.

I am not sure if my command is wrong and therefore the results are unpredictable. Also I'm not sure what I can add to the CI job to provide more information on what is causing the issue. 

### pre-commit --version

pre-commit v4.3.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-merge-conflict
    - id: detect-private-key
    - id: detect-aws-credentials
      args: [--allow-missing-credentials]
    - id: pretty-format-json
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
    - id: requirements-txt-fixer

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.74.1
  hooks:
    - id: terraform_fmt
      args: 
        - --args=-check
    - id: terraform_tflint
      args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
- repo: local
  hooks:
    - id: module_structure
      name: Module Structure
      entry: python ./hooks/module_structure.py
      language: python  
      files: ^modules/
      require_serial: true
      additional_dependencies: ["python-hcl2"]
    - id: bare_includes
      name: Bare includes
      entry: python ./hooks/bare_includes.py
      language: python  
      files: terragrunt.hcl
      additional_dependencies: ["python-hcl2"]
    - id: terragrunt_source
      name: Terragrunt source
      entry: python ./hooks/terragrunt_source.py
      language: python  
      files: \bterragrunt.hcl
      additional_dependencies: ["python-hcl2"]
    - id: terragrunt_fmt
      name: Terragrunt format
      entry: ./hooks/terragrunt_fmt.sh
      language: script
      files: (\.hcl)$
      exclude: \.terraform\/.*$
      args: 
        - -a --terragrunt-check
    - id: version_check
      name: Version check
      files: ^modules/
      entry: python ./hooks/version_check.py
      exclude: (OWNERS.gh|README.MD|CHANGELOG.md)
      language: python
      require_serial: true
      additional_dependencies: ["python-hcl2", "GitPython", "pyyaml"]

- repo: meta
  hooks:
    - id: identity
```
