### ISSUE TITLE
Use defined git

### ISSUE THREAD

**Issue by L-o-r-e-n-z** [pre-commit/pre-commit#2548]
### search you tried in the issue tracker

git path

### describe your issue

Is there a way to define a specific git version (path to git executable) to be used by pre-commit? We use a git-tool with integrated git executable and due to this we do not have installed git on all PCs.

Is it possible to extend the config file with a `GIT_PATH` to be used?

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:
  # Some out-of-the-box hooks for pre-commit.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
```
