### ISSUE TITLE
Pre-commit hook missing argument when running git commit or using Pycharm commit button

### ISSUE THREAD

**Issue by yanchunwang** [pre-commit/pre-commit#2549]
### search you tried in the issue tracker

argument missing

### describe your issue

This is more of a question.

I am trying to use pre-commit hooks for code style checking and auto formatting. Please see my .pre-commit-config.yaml below. The pre_commit.py is the python script which runs a bunch of tools for code style checking and reformatting.

The pre_commit.py accepts arguments like --fix and --diff. I specify the arguments in the `entry`. The hook works fine when I run `pre-commit run linting-and-reformatting` in terminal, however, I found it missed the argument when I run `git commit `directly or use the Pycharn source control sidebar to commit. 

I printed the arguments received by the pre_commit.py, and it was correct when running `pre-commit run` in terminal, but for the other two scenarios (git commit and Pycharm commit button), the arguments look like this

```
Namespace(fix=False, diff=False) //Argument missed, otherwise `fix` would be True
['hook-impl', '--config=.pre-commit-config.yaml', '--hook-type=pre-commit', '--hook-dir', '/Users/myusername/Documents/Development/pre-commit-test/myrepo/.git/hooks', '--']
```
The code to parse and output the arguments in pre_commit.py is as follows:
```
   # get commandline arg --diff, --fix
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--fix", action="store_true", help="Reformat the changed files or lines automatically"
    )
    parser.add_argument(
        "--diff",
        action="store_true",
        help="Output a diff for each file on stdout without code reformatting.",
    )
    args, unknown = parser.parse_known_args()
    print(args)
    print(unknown)
```

I don't know what I did wrong, and any help would be much appreciated.

Thanks.

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: linting-and-reformatting
        name: run pre-commit linting and reformatting
        description: check and fix code style issues with darker, flakehell, black, and isort
        language: python
        types: ['python']
        pass_filenames: false
        verbose: true
        entry: python pre_commit.py --fix
        additional_dependencies:
          - flake8==3.9.2
          - black==22.10.0
          - isort==5.10.1
          - flakehell==0.9.0
default_language_version:
  python: python3.8
```
