### ISSUE TITLE
YAML inherits usage / Ablility to suppress warning "Unexpected key(s) present ..."

### ISSUE THREAD

**Issue by MaxymVlasov** [pre-commit/pre-commit#2550]
Hi, I try to be DRY as much as it possible in YAML, by using the YAML merge syntax.

```yaml
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0

    tf_updates_root_module: &tf_updates_root_module
      id: tfupdate
      exclude: '/(\.)?modules/'
    tf_updates_child_module: &tf_updates_child_module
      id: tfupdate
      files: '/(\.)?modules/'

    hooks:
      - name: Pin Terraform version (Atmos components/TF root modules)
        <<: *tf_updates_root_module
        args:
          - --args=terraform
          - --args=--version "~> 1.3"

      - name: Pin Terraform version (TF modules/TF child modules)
        <<: *tf_updates_child_module
        args:
          - --args=terraform
          - --args=--version ">= 1.3.1"

      - name: Pin AWS provider versions (Atmos components/TF root modules)
        <<: *tf_updates_root_module
        args:
          - --args=provider aws
          - --args=--version '~> 4.0'

      - name: Pin AWS provider versions  (TF modules/TF child modules)
        <<: *tf_updates_child_module
        args:
          - --args=provider aws
          - --args=--version '>= 4.0'
...
```

But if I do that, then `pre-commit` will warn me that `Unexpected key(s) present on https://github.com/antonbabenko/pre-commit-terraform: tf_updates_child_module, tf_updates_root_module` or if I pass them to root - `"Unexpected key(s) present at root...`

I quickly check the source code and not found the possibility to append a list of expected keys or disable that warnings.

---

Also would be nice to template the name too, like suggested here - https://stackoverflow.com/a/22236941:
```yaml
    root_name: &root (Atmos components/TF root modules)
    child_name: &child (TF modules/TF child modules)

      - name: !join [[Pin Terraform version, *root], ' ']
        <<: *tf_updates_root_module
        args:
          - --args=terraform
          - --args=--version "~> 1.3"

      - name: !join [[Pin Terraform version, *child], ' ']
        <<: *tf_updates_child_module
        args:
          - --args=terraform
          - --args=--version ">= 1.3.1"
```

but that also needs some functional inside pre-commit.
