### ISSUE TITLE
Autoupdate chnages flake8 back to old version

### ISSUE THREAD

**Issue by SergioG-M** [pre-commit/pre-commit#2553]
Hi,

Having this in my pre-commit.config

```   
 - repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args:
          ["--ignore=F405,E203,W503", "--max-line-length=140", "--exit-zero"]
        additional_dependencies: [flake8-isort==5.0.0]
        verbose: true
```   

After running pre-commit autoupdate it changes back to version 3.9.2

![image](https://user-images.githubusercontent.com/61322372/196652031-c0c12a7f-9ca0-4937-b35f-3c7bbcabdf3e.png)

Is there any reason for this or is it just a bug?
