### ISSUE TITLE
Feature request: docker_image should mount volume same as docker

### ISSUE THREAD

**Issue by kbroughton** [pre-commit/pre-commit#2554]
### search you tried in the issue tracker

docker

### describe your issue

The "docker" language runs a container but must be supplied a Dockerfile.
It offers the ability to mount a local volume:

https://github.com/pre-commit/pre-commit/blob/main/pre_commit/languages/docker.py#L124

The docker_image language allows for only a reference to an image and is lighter weight, but
does not support local directory mounting
https://github.com/pre-commit/pre-commit/blob/main/pre_commit/languages/docker_image.py#L15

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.2.0
    hooks:
     - id: gitleaks
       name: gitleaks-docker
       language: system
       entry: gitleaks

# I would prefer to use the docker_image language but
# it seems that the required -v mount is only available
# for "docker" language which       
#repos:
#  - repo: https://github.com/zricethezav/gitleaks
#    rev: v8.2.0
#    hooks:
#      - id:       gitleaks
#        language: docker_image
#        entry:    zricethezav/gitleaks:latest -c /src/.gitleaks.toml --source=/src


# For the "system" language to work, I have to have the user install the following
# file in /usr/local/bin/gitleaks
#!/bin/bash

#if [[ x"$@"x != "xx" ]]; then
#  docker run -v `pwd`:/path zricethezav/gitleaks:latest -c /path/.gitleaks.toml --source=/path #"$@"
#else
#  docker run -v `pwd`:/path zricethezav/gitleaks:latest -c /path/.gitleaks.toml --source=/path #protect  --staged --verbose
#fi
```
