### ISSUE TITLE
Problems with docker_image gitmodules and stages commit-msg

### ISSUE THREAD

**Issue by Dauliac** [pre-commit/pre-commit#2558]
### search you tried in the issue tracker

gitmodules

### describe your issue

Hello,
When I try to use `commit-msg` stage with gitmodules, and `docker_image` together, `pre-commit` can't  access to the `COMMIT_EDITMESSAGE` file that is in parent submodule repo
```
/tmp/repo/.git/modules/src/subrepo/COMMIT_EDITMSG No such file or directory
```

This happens because, the contain don't mount parent repo in that contains the `COMMIT_EDITMSG` file.
Indead, in gitmodules, git `.git` is empty and contains directive to catch the parent gitmodules .git:
```
cat src/subrepo/.git
 gitdir: ../../.git/modules/src/subrepo
```

This is not really a bug but a design problem in my opinion and I don't have idea how to fix this issue.

### pre-commit --version

2.19.0

### .pre-commit-config.yaml

```yaml
---
repos:
  - repo: local
    hooks:
      - id: commitlint
        name: Commitlint your commits
        stages:
          - commit-msg
        language: docker_image
        entry: gitlab.my.repo.io:4567/iac/cicd/commitlint:1-local
```
