### ISSUE TITLE
echo variable not running as expected in shell script while running pre-commit

### ISSUE THREAD

**Issue by jhon9392** [pre-commit/pre-commit#2567]
Hi Team,

I have written custom pre-commit hook that fetches variable by reading some yml file written in shell script. 
ex: 
```sh
loc="a"
echo "${loc}" >> loc.txt
```

when i run this using `pre-commit run --all` or via CI, its printing `loc` 10 times, when i run directly - printing just once.

configuration in `.pre-commit-config.yaml`
```yaml
- repo: local
    hooks:
    - id: fetch-variable
      name: fetch-variable
      description: This hook is to fetch a variable from yaml file
      language: system
      entry: bash -c "fetch-var.sh"
```
