### ISSUE TITLE
[Question]: Option to run pre-commit hooks on modified lines only

### ISSUE THREAD

**Issue by shivam-kapila** [pre-commit/pre-commit#2574]
Hi
I have been working on integrating pre-commit hooks in my python project. I have used the following hooks
1. isort
2. autopep8
3. pylint

Whenever I try to commit, it runs the pre-commit hook on the complete file rather than modified lines. The code base is really huge and hence running hook on complete files, leads to a lot of unrelated errors. I want to run it only on modified lines only. IS there a way to do so?

Here is my `.pre-commit-config.yaml`

```
repos:
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort
    description: This hook sorts imports in the files.

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: 'v1.7.0'  # Use the sha / tag you want to point at
  hooks:
  - id: autopep8
    description: This hook runs autopep8 formatter and fixes most PEP8 formatting issues automatically.

- repo: local
  hooks:
  - id: pylint
    name: pylint
    description: This hook runs pylint linter and highlights code that isn't upto the PEP8 standards.
    entry: pylint
    language: system
    types: [python]
    args:
      [
        "-rn", # Only display messages
        "-sn", # Don't display the score
        "--rcfile=.pylintrc", # Link to your config file
      ]
```
