### ISSUE TITLE
[feature] Default options for every hook

### ISSUE THREAD

**Issue by Freed-Wu** [pre-commit/pre-commit#2575]
```yaml
---
default: 
  exclude: ^foo/*$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: trailing-whitespace
```

equal to

```yaml
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        exclude: ^foo/*$
      - id: fix-byte-order-marker
        exclude: ^foo/*$
      - id: check-case-conflict
        exclude: ^foo/*$
      - id: check-shebang-scripts-are-executable
        exclude: ^foo/*$
      - id: check-merge-conflict
        exclude: ^foo/*$
      - id: trailing-whitespace
        exclude: ^foo/*$
```
