### ISSUE TITLE
`$PRE_COMMIT_LOCAL_BRANCH` env only contains one tag when `git push --tags` with multiple tags

### ISSUE THREAD

**Issue by beviz** [pre-commit/pre-commit#2577]
### search you tried in the issue tracker

push tags hook

## Context

Our team decided to restrict our release tags to must have a message in a valid format. Then we dive into how to add a hook to achieve that. Since Git doesn't have an official hook type for that, we choose pre-push hook to validate the format before the tags have been pushed.

We can get the tags in the original `.git/hooks/pre-push` using `while read -d $'0' arg` command. But in pre-commit I cannot get them in this way. There is an environment variable `$PRE_COMMIT_LOCAL_BRANCH` equals the tag name when pushing one tag, or one of the tags when pushing all.

How can I get all the tags?

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
---
repos:
  - repo: local
    hooks:
    - id: tag-message-format-check
        name: tag message format check
        entry: .shared/hooks/tag-msg.sh
        always_run: true
        language: system
        stages: [push]
```

**Comment by asottile** [comment]
try this search instead https://github.com/pre-commit/pre-commit/issues?q=is%3Aissue+pre-push+is%3Aclosed

**Comment by beviz** [comment]
@asottile I've tried many keywords  to search and went through all the results. There is no existing relevant issue whatever is open or closed which is similar to this one.

If you already know one, please help link it to this issue. Otherwise, please help answer or just reopen this one.

Thanks.

**Comment by asottile** [comment]
click the link, it's the fourth result

**Comment by beviz** [comment]
Thanks @asottile. I found it: #2523.

Don't you think his scenario plus mine deserve an improvement? like an extra env variable `**_BRANCHES` ?

**Comment by asottile** [comment]
pre-commit only runs on one of them right now, listing the others would be disingenuous (not to mention you can push more than fits in an environment variable)

**Comment by beviz** [comment]
@asottile 
We are completely using pre-commit for all git hooks, and don't want to manage a special one for this tag message thing. We can get all the tags within the prototypical `.git/hooks/pre-push`. pre-commit should at least allow us to have a prototype hook to receive the original hook's input. 

For example
```yaml
- id: tag-message-format-check
  name: tag message format check
  entry: .shared/hooks/tag-msg.sh
  stages: [push]
  *raw*: true
```
