### ISSUE TITLE
Is there support for "hidden" yaml keys? If not, is there interest in having it?

### ISSUE THREAD

**Issue by dougthor42** [pre-commit/pre-commit#2583]
### search you tried in the issue tracker

is:issue hidden

### describe your issue

Does `pre-commit` support "hidden" YAML keys? Note: hidden keys are not part of the YAML spec.

If not, is there interest in supporting it? I could take a look at implementing it, I don't expect it to be too complicated.

These are useful for defining anchors outside of their typical first appearance. For example:

```yaml
---

# Ignore pb2 and pyi files.
.hidden_key: &formatignore |
  (?x)(
    _pb2\.pyi?|
    _pb2_grpc\.pyi?|
    _pb2_client\.pyi?
    )$

repos:
  - repo: foo
    hooks:
      - id: foo
        name: foo
        exclude: *formatignore
  - repo: local
    hooks:
      - id: foobar
        name: foobar
  - repo: foobarbaz
    hooks:
      - id: foobarbaz
        name: foobarbaz
        exclude: *formatignore
```

There are a couple advantages of supporting and using "hidden" keys:

1. It makes it easy to search for the - for lack of a better term - "variable" definitions used throughout larger configs. Put all of the "variables" at the top!
3. Makes it trivial to reorder hooks. Given the example above, let's assume we now want to run the `foobarbaz` hook first. Without hidden keys, the anchor that would have been defined in the `foo` hook would need to be moved to the `foobarbaz` hook.

Such a thing is not without precedence: GitLab does a similar thing with their CI config. They ignore any top-level keys that start with a dot ([hidden jobs](https://docs.gitlab.com/ee/ci/jobs/index.html#hide-jobs] which can then be used as [job templates via YAML anchors](https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#anchors)

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
N/A
```

### ~/.cache/pre-commit/pre-commit.log (if present)

N/A
