### ISSUE TITLE
Condition for skipping a check

### ISSUE THREAD

**Issue by eradman** [pre-commit/pre-commit#2584]
At times it is helpful to skip a check because the necessary utilities are not installed. Here is how one might skip a check if `rpmlint` was not installed.

```yaml
repos:
- repo: local
  hooks:
  - id: check_rpmlint
    name : check_rpmlint
    entry: ./scripts/check_rpm_spec.sh
    files: \.spec$
    language: script
    condition: /usr/bin/which rpmlint
```

Where `condition` is some criteria used to determine if this check is able to run.  My goal is to allow checks to be skipped without obscuring the fact that a check is not available.
