### ISSUE TITLE
psf/black hook fails when black left all files unchanged?

### ISSUE THREAD

**Issue by KrishnanS2006** [pre-commit/pre-commit#2585]
### search you tried in the issue tracker

hook failed

### describe your issue

Ran `pre-commit run --all-files`

Output:
```
(venv) ➜  server git:(docs) ✗ pre-commit run --all-files
black....................................................................Failed
- hook id: black
- duration: 0.41s
- files were modified by this hook

All done! ✨ 🍰 ✨
30 files left unchanged.

(venv) ➜  server git:(docs) ✗ 
```

Black left all files unchanged as shown by the printed message; however, pre-commit thinks files were modified by the hook and therefore fails.

### pre-commit --version

pre-commit 2.19.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [-l, '99']
        language_version: python3.10
        verbose: true
        exclude: .*auvsi_suas.*
```
