### ISSUE TITLE
Pre-commit hook poetry-lock not using expected python runtime

### ISSUE THREAD

**Issue by rafrafek** [pre-commit/pre-commit#2586]
### search you tried in the issue tracker

default_language_version wrong version

### describe your issue

I want to use Python 3.11.0 for all hooks. It does not work with Poetry. Poetry uses 3.11.0, but poetry-lock hook for some reason uses 3.7.13.

<img width="579" alt="image" src="https://user-images.githubusercontent.com/23004737/200382570-22910ca2-b609-42fd-abce-f0191ae2b126.png">

Similar issue to:
https://github.com/python-poetry/poetry/issues/6946

<img width="314" alt="image" src="https://user-images.githubusercontent.com/23004737/200381821-f6bc6d06-c37c-4e02-b3b7-57ea0fef88e4.png">

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
default_language_version:
  python: python3.11.0
repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        entry: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: [ '--max-line-length=88' ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/python-poetry/poetry
    rev: 1.2.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
```
