### ISSUE TITLE
Prettier with additional dependencies doesn't find prettier

### ISSUE THREAD

**Issue by adam-moss** [pre-commit/pre-commit#2592]
### search you tried in the issue tracker

prettier and went through the 3 pages of results

### describe your issue

Adding `prettier` with `additional_dependencies` raises an error:

```sh
prettier.................................................................Failed
- hook id: prettier
- exit code: 1

Executable `prettier` not found
```

If `additional_dependencies` are not included it works as anticipated:

```sh
prettier.................................................................Passed
```

If `prettier` is added as an `additional_dependencies` it again works as anticipated:

```sh
prettier.................................................................Passed
```

This contrasts with the behaviour of `markdownlint-cli2` with `additional_dependencies` which works as anticipated:

```sh
Finding: README-template.md
Linting: 1 file(s)
Summary: 1 error(s)
README-template.md:1:1 titlecase-rule Titlecase rule [Title Case: 'Expected # Product Name, found # Product name']
```

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
%YAML 1.2
# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
---
fail_fast: true

repos:
    - repo: https://github.com/DavidAnson/markdownlint-cli2/
      rev: v0.5.1
      hooks:
          - id: markdownlint-cli2
            additional_dependencies:
                - markdownlint-rule-titlecase
                - markdownlint-cli2-formatter-junit

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0-alpha.4
      hooks:
          - id: prettier
            additional_dependencies:
                - prettier@3.0.0-alpha.4
                - eslint-config-prettier
                - stylelint-config-prettier
                - prettier-plugin-java
                - prettier-plugin-sh
                - prettier-plugin-toml
                - "@prettier/plugin-xml"

    - repo: https://github.com/codespell-project/codespell
      rev: v2.2.2
      hooks:
          - id: codespell
```
