### ISSUE TITLE
pre-push hooks are triggered conditionally when pushing a tag

### ISSUE THREAD

**Issue by beviz** [pre-commit/pre-commit#2594]
### search you tried in the issue tracker

push tag

### describe your issue

![image](https://user-images.githubusercontent.com/1106312/201513991-37c29563-9897-4ff9-a0fe-71a1e34285e9.png)

Pushing t2 is able to trigger the hooks:

```
# git push origin t2 --dry-run
Trim Trailing Whitespace.................................................Passed
To github.com:beviz/pre-commit-test.git
 * [new tag]         t2 -> t2
```

Pushing t1 will push the tag directly:

```
# git push origin t1 --dry-run 
To github.com:beviz/pre-commit-test.git
 * [new tag]         t1 -> t1
```

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: trailing-whitespace
```
