### ISSUE TITLE
flake8 W504 after black formating

### ISSUE THREAD

**Issue by e-lepilov** [pre-commit/pre-commit#2597]
### search you tried in the issue tracker

W504

### describe your issue

I have a code

```
    for creative in data:
        creative.update(
            {
                'duration': (get_video_creative_duration(creative['modifications']))
                if (
                    creative['cream_category'] == CreativeCategory.VIDEO
                    and creative['modifications']
                )
                else DEFAULT_DURATION,
                'tableau_url': generate_tableau_url(creative['name']),
            }
        )
```
        
       This code format genereted by black
       
       After running `git commit`  command I got
       
```
Check Yaml...........................................(no files to check)Skipped
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
Debug Statements (Python)................................................Passed
Fix double quoted strings................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

apps/creative_performer/utils.py:50:21: W503 line break before binary operator

black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted apps/creative_performer/utils.py
```
The line `and creative['modifications']` are invalid. It turns out that I can't make changes because black always makes its own changes to the code, but these changes don't comply with flake8 rules. Is there any way I can fix it without disabling rule W508? I can't commit at the moment. 

### pre-commit --version

pre-commit==2.20.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: double-quote-string-fixer

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bandit", "flake8-bugbear"]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        exclude: ^.*\b(migrations)\b.*$
```
