### ISSUE TITLE
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.

### ISSUE THREAD

**Issue by ejsc1** [pre-commit/pre-commit#2606]
### search you tried in the issue tracker

https://gitlab.com/pycqa/flake8

### describe your issue

Hello,

See: https://github.com/pwr-Solaar/Solaar/issues/1858#issuecomment-1321172021

How do I change the URL?

Thanks.

### pre-commit --version

pre-commit/action@v3.0.0

### .pre-commit-config.yaml

```yaml
name: checks

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4.1.0
        with:
          python-version: '3.10'

      - uses: pre-commit/action@v3.0.0
```
