### ISSUE TITLE
hooks file, same entry(command) and 2 ids with different args

### ISSUE THREAD

**Issue by sarnold** [pre-commit/pre-commit#2612]
### search you tried in the issue tracker

hook ids multiple, hooks file entry same name 

### describe your issue

Working on a mirror hooks repo for asterisklint, I have 2 hook ids using the same (base) command, but each one has their own arg (either using `entry: cmd arg` or `entry: cmd` with `args: ["arg"]`) and different file names.  So far using `pre-commit try-repo` only seems to work correctly with a single hook id.  As soon as I add the second hook id the first hook starts picking up both file names and the second hook runs but does not find any files.

Probably there is something wrong with my config?  Or is this an actual bug?  Looking at existing hooks, one solution might be a (python) wrapper script for each command, but I was hoping there was something I'm missing in the config/setup.  (also thanks for the nice tooling...)

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
-   id: dialplan-check
    name: dialplan-check
    description: 'Run asterisklint dialplan-check on extensions.conf files'
    entry: asterisklint
    language: python
    types: [text]
    files: extensions\.conf$
    args: ["dialplan-check"]
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: '2.9.2'

-   id: func-odbc-check
    name: func-odbc-check
    description: 'Run asterisklint func_odbc-check on func_odbc.conf files'
    entry: asterisklint
    language: python
    types: [text]
    files: func_odbc\.conf$
    args: ["func_odbc-check"]
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: '2.9.2'
```
