### ISSUE TITLE
No package metadata was found for pre-commit

### ISSUE THREAD

**Issue by dmitry-mightydevops** [pre-commit/pre-commit#2617]
### search you tried in the issue tracker

No package metadata was found for pre-commit

### describe your issue

Unable to install pre-commit inside Docker container based on `FROM python:3.9.15-alpine3.16`

```sh
python --version
Python 3.9.15

⬢ [Docker] ✗  pip install pre-commit
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pre-commit in /home/terraform/.local/lib/python3.9/site-packages (2.20.0)
Requirement already satisfied: cfgv>=2.0.0 in /home/terraform/.local/lib/python3.9/site-packages (from pre-commit) (3.3.1)
Requirement already satisfied: pyyaml>=5.1 in /home/terraform/.local/lib/python3.9/site-packages (from pre-commit) (6.0)
Requirement already satisfied: nodeenv>=0.11.1 in /home/terraform/.local/lib/python3.9/site-packages (from pre-commit) (1.7.0)
Requirement already satisfied: identify>=1.0.0 in /home/terraform/.local/lib/python3.9/site-packages (from pre-commit) (2.5.9)
Requirement already satisfied: virtualenv>=20.0.8 in /home/terraform/.local/lib/python3.9/site-packages (from pre-commit) (20.16.7)
Requirement already satisfied: toml in /home/terraform/.local/lib/python3.9/site-packages (from pre-commit) (0.10.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from nodeenv>=0.11.1->pre-commit) (58.1.0)
Requirement already satisfied: filelock<4,>=3.4.1 in /home/terraform/.local/lib/python3.9/site-packages (from virtualenv>=20.0.8->pre-commit) (3.8.0)
Requirement already satisfied: platformdirs<3,>=2.4 in /home/terraform/.local/lib/python3.9/site-packages (from virtualenv>=20.0.8->pre-commit) (2.5.4)
Requirement already satisfied: distlib<1,>=0.3.6 in /home/terraform/.local/lib/python3.9/site-packages (from virtualenv>=20.0.8->pre-commit) (0.3.6)

pre-commit install 

Traceback (most recent call last):
  File "/usr/bin/pre-commit", line 33, in <module>
    sys.exit(load_entry_point('pre-commit==2.20.0', 'console_scripts', 'pre-commit')())
  File "/usr/bin/pre-commit", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for pre-commit
```

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.50.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs

- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: forbid-new-submodules
    - id: no-commit-to-branch
    - id: check-symlinks
    - id: mixed-line-ending
      args: [--fix=auto]

    # Common errors
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]

    # Cross platform
    - id: check-case-conflict

    # Security
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key
```
