### ISSUE TITLE
The pre-commit autoupdate ignores `default_language_version` when `autoupdate` 

### ISSUE THREAD

**Issue by Czaki** [pre-commit/pre-commit#2619]
### search you tried in the issue tracker

default_language_version autoupdate

### describe your issue

I got pre-commit.ci autoupdate PR in which falke8 is updated to 6.0.0 even if `default_language_version` is specified to python 3.7. 

https://github.com/Czaki/nme/pull/20#issue-1467321781

In the pre-commit.ci repository, I found information that they use a plain `pre-commit autoupdate` call. 

Maybe important information is that flake8 6.0.0 specify a minimum version to 3.8.1

### pre-commit --version

same as pre-commit.ci

### .pre-commit-config.yaml

```yaml
default_language_version:
    python: python3.7

repos:
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      pass_filenames: true
-   repo: https://github.com/PyCQA/autoflake
    rev: 'v1.7.7'  # Use the revision sha / tag you want to point at
    hooks:
    -   id: autoflake
        args: ["--remove-all-unused-imports", "-i"]
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      pass_filenames: true
      # this seems to need to be here in addition to setup.cfg
      exclude: vendored|__init__.py|examples
      additional_dependencies:
      - flake8-tidy-imports
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: .*\.md
    - id: debug-statements
    - id: mixed-line-ending
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
    - id: pyupgrade
      args: ["--py37-plus"]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: rst-backticks
-   repo: https://github.com/PyCQA/isort
    rev: '5.10.1'  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
```
