### ISSUE TITLE
Existing Node environment not detected correctly

### ISSUE THREAD

**Issue by lbhm** [pre-commit/pre-commit#2620]
### search you tried in the issue tracker

node, npm

### describe your issue

I am using `pre-commit` in a website project together with the `eslint` plugin. When trying to run `pre-commit` on a server with an older GCC version (9.3.1), creating the environment for `mirrors-eslint` fails because newer GLIBC versions are not found. After some digging, it appears to me that `pre-commit` tries to install a new `node` environment (with a Node version that my GCC doesn't support) even though I have `node` and `npm` installed on the system.

I therefore looked into the `pre-commit` codebase and in my understanding `pre-commit` should use the existing Node environement if `node` and `npm` are found as executables [[1]](https://github.com/pre-commit/pre-commit/blob/main/pre_commit/languages/node.py#L34).

Does anyone have an idea why `pre-commit` nevertheless wants to install the default Node environemt (see below)? 

Node and npm versions:
```bash
$ npm --version
8.18.0
$ node --version
v16.18.1
```

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
    exclude: .*.html
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.28.0
  hooks:
  - id: eslint
```

### version information

```
pre-commit version: 2.20.0
git --version: git version 2.24.4
sys.version:
    3.8.15 (default, Oct 18 2022, 09:42:36) 
    [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
sys.executable: /usr/bin/python3.8
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('~/.cache/pre-commit/repotcmioeo9/node_env-default/bin/node', '~/.cache/pre-commit/repotcmioeo9/node_env-default/bin/npm', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    ~/.cache/pre-commit/repotcmioeo9/node_env-default/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ~/.cache/pre-commit/repotcmioeo9/node_env-default/bin/node)
    ~/.cache/pre-commit/repotcmioeo9/node_env-default/bin/node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by ~/.cache/pre-commit/repotcmioeo9/node_env-default/bin/node)
    ~/.cache/pre-commit/repotcmioeo9/node_env-default/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ~/.cache/pre-commit/repotcmioeo9/node_env-default/bin/node)
    ~/.cache/pre-commit/repotcmioeo9/node_env-default/bin/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ~/.cache/pre-commit/repotcmioeo9/node_env-default/bin/node)
    ~/.cache/pre-commit/repotcmioeo9/node_env-default/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ~/.cache/pre-commit/repotcmioeo9/node_env-default/bin/node)
    ~/.cache/pre-commit/repotcmioeo9/node_env-default/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ~/.cache/pre-commit/repotcmioeo9/node_env-default/bin/node)
    
```
