### ISSUE TITLE
Add an option to pass absolute filenames to hooks

### ISSUE THREAD

**Issue by imankulov** [pre-commit/pre-commit#2621]
### search you tried in the issue tracker

absolute filenames, monorepo, subdirectories

### describe your issue

**Use case**. 

My repo has subdirectories for different projects ("api" and "frontend").

Most tools from the JavaScript ecosystem make implicit assumptions about the current working directory. E.g., they import modules from "./node_modules" and search for configuration files in the current directory.

I would love to run frontend linters after changing the working directory to "frontend," but the naive approach doesn't work because pre-commit passes relative filenames to hooks.

**Example**

Running "prettier" against a file in my frontend codebase, located in a "frontend" directory should go like this:

```
cd frontend && npx run prettier --write src/index.js
```

A naive approach to implementing it with a local webhook does not work.

```
- id: prettier
  language: system
  entry: cd frontend && npx run prettier --write
```

As pre-commit passes relative filenames to the hook, the prettier command gets "frontend/src/index.js" as an argument.

**Workarounds**

I can see a few workarounds.

**Disable passing filenames to a linter.** Lint the entire project on every related change (my current workaround):

```
- id: prettier
  language: system
  pass_filenames: false
  entry: cd frontend && npx run prettier --write ./src
```

**Wrapper.** Create a wrapper around JavaScript linters that would take filenames, adjust them and call the linter with corrected paths ([outlined here](https://github.com/pre-commit/pre-commit/issues/1110#issuecomment-525937018), and [here](https://github.com/pre-commit/pre-commit/issues/1417#issuecomment-1208212944)). There is also a [workaround script](https://github.com/streamlit/streamlit/blob/master/scripts/run_in_subdirectory.py) in a streamlit repo.

**Suggested solution**

We can introduce a hook option "absolute_filenames" to convert filenames to absolute before passing them to the hook. The local hook author still manually changes the current working directory, but relative filenames don't get in their way.

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
## My workaround

repos:
  - repo: local
    hooks:
      # Run eslint
      - id: eslint
        language: system
        name: eslint
        entry: yarn run --cwd=frontend eslint --cache --fix src
        pass_filenames: false
        types_or: [javascript, jsx, ts, tsx]

      # Run prettier
      - id: prettier
        language: system
        name: prettier
        entry: yarn run --cwd=frontend prettier --write src
        pass_filenames: false
        types_or: [javascript, jsx, ts, tsx, css, json, yaml, markdown]

      # Run TypeScript checker
      - id: tsc
        language: system
        name: tsc
        entry: yarn run --cwd=frontend tsc --noEmit
        pass_filenames: false
        types_or: [ts, tsx]
```
