### ISSUE TITLE
pre-commit - pass_filenames for single file

### ISSUE THREAD

**Issue by rinaudjaws** [pre-commit/pre-commit#2622]
### search you tried in the issue tracker

Yes

### describe your issue

I was doing the following pre-commit-hook for shell to simply append changed files to a list.

I was expecting when adding a single yaml file `test.yaml`, "$@" should contain the `test.yaml` inside a created param file.

Instead: `param` flle is not created and commit is allowed:
`test-params..............................................................Passed`

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: local
    hooks:
    -   id: params
        name: test-params
        entry: echo "$@" > params
        language: system
        files: \.(json|yaml|yml)$
        pass_filenames: true
```
