### ISSUE TITLE
Force Recreation of Hook Environments

### ISSUE THREAD

**Issue by JMMarchant** [pre-commit/pre-commit#2633]
### search you tried in the issue tracker

reinstall hooks environment

### describe your issue

Is there a way to force `pre-commit` to reinstall/recreate the hooks environments? We often run into the issue where the installed version of a dependency in a hook environment (for example `flake8-bugbear` in a `flake8` environment) gets out of sync with the latest version that would be pulled down on a brand new `pre-commit install` call. Without the nuclear option of just deleting `.cache/pre-commit` is there a way to tell `pre-commit` to recreate the environment for a given hook?

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-docstrings
```
