### ISSUE TITLE
Undocumented Behavior

### ISSUE THREAD

**Issue by ebram96** [pre-commit/pre-commit#2636]
I've this conf file:
```
files: "sub/dir"
repos:
  - repo: local
    hooks:
      - id: some-hook
        files: "somePattern\.cfg"
```

What is the behavior when I have a global `files` pattern and hook-specific pattern?
Will the hook-specific override the global one? Or, will it run within the matches from global pattern?

I'm sorry if this is already documented, but, I couldn't really find it.
