### ISSUE TITLE
Adding powershell linter hook - best practice

### ISSUE THREAD

**Issue by juju4** [pre-commit/pre-commit#2645]
### search you tried in the issue tracker

powershell, return code, exit code

### describe your issue

I'm working on a repository containing powershell scripts.
I have a pre-commit already enabled for other checks and I want to add powershell linting with https://github.com/PowerShell/PSScriptAnalyzer.

I added a hook config as
https://github.com/PowerShell/PSScriptAnalyzer/compare/master...juju4:PSScriptAnalyzer:devel-precommit
```
-   id: powershell_scriptanalyzer
    name: Powershell lint with PSScriptAnalyzer
    description: This runs PSScriptAnalyzer on your powershell files
    entry: pre-commit powershell_scriptanalyzer
    language: script
    files: ^.*\.ps1$
    types: [text]
    entry: pwsh -Command "Invoke-ScriptAnalyzer -Settings PSGallery -Recurse -ReportSummary -EnableExit -Path ."
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '0'
    pass_filenames: false
    verbose: true
```

In the target repo, I added following config
```
-   repo: https://github.com/juju4/PSScriptAnalyzer
    rev: 4d6a4a36c78df215bc8fa637d05929eb7a9112d9
    hooks:
    -   id: powershell_scriptanalyzer
        entry: /usr/local/bin/pwsh -Command "Invoke-ScriptAnalyzer -Settings PSGallery -Recurse -ReportSummary -EnableExit -Path ."
```

3 minor issues as using entry to deal with them for now.
* As I'm executing on non-windows system, I have to customize/duplicate entry value with pwsh full path. not sure if better way?
* to support powershell cmdlet include/exclude rules or severity (https://github.com/PowerShell/PSScriptAnalyzer/blob/master/docs/Cmdlets/Invoke-ScriptAnalyzer.md), I again have to customize entry. any way to define pre-commit fields to pass that inside the pwsh Command? default args apply outside.
* same problem applies if want pass_filenames=true. `/usr/local/bin/pwsh -Command "Invoke-ScriptAnalyzer -Settings PSGallery -Recurse -ReportSummary -EnableExit -Path $@"` did not work in my tests.

Else happy to take more comments

Thanks a lot for your work!

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/juju4/PSScriptAnalyzer
    rev: 4d6a4a36c78df215bc8fa637d05929eb7a9112d9
    hooks:
    -   id: powershell_scriptanalyzer
        entry: /usr/local/bin/pwsh -Command "Invoke-ScriptAnalyzer -Settings PSGallery -Recurse -ReportSummary -EnableExit -Path ."
```

**Comment by asottile** [comment]
you shouldn't need a full path to `pwsh` -- it will look up on path automatically

`pass_filenames: true` is the recommended way to set up hooks -- otherwise you don't really benefit from pre-commit's file matching at all and then have to re-implement it using the tool.

I think what you actually want is to use `language: dotnet` which will build the executables which you'll call directly without using `pwsh` at all

**Comment by juju4** [comment]
If I don't pass the full path for pwsh, I get
```
- hook id: powershell_scriptanalyzer
- duration: 0s
- exit code: 1

Executable `<HOME>/.cache/pre-commit/<RANDOM>/pwsh` not found
```

ok for pass_filenames true but how?
if using $@ and pass_filenames true, I get
```
- hook id: powershell_scriptanalyzer
- duration: 0.69s
- exit code: 1

Invoke-ScriptAnalyzer: A positional parameter cannot be found that accepts argument '<MODIFIED FILES>'
```

on dotnet, not sure how, https://github.com/PowerShell/PSScriptAnalyzer is not a dotnet app.
from quick check, dotnet fails saying missing application pack.

**Comment by asottile** [comment]
that's because you've incorrectly set `language: script` which is to be used for *scripts*

**Comment by juju4** [comment]
I tested locally with following pre-commit-config
```
repos:
-   repo: https://github.com/juju4/PSScriptAnalyzer
    rev: 4d6a4a36c78df215bc8fa637d05929eb7a9112d9
    hooks:
    -   id: powershell_scriptanalyzer
        entry: /usr/local/bin/pwsh -Command "Invoke-ScriptAnalyzer -Settings PSGallery -Recurse -ReportSummary -EnableExit -Path ."
        language: dotnet
```
which should be valid unless language can't be overriden but behavior below shown it applies

full output
```

% pre-commit run -a powershell_scriptanalyzer
[INFO] Installing environment for https://github.com/juju4/PSScriptAnalyzer.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/bin/bash', '/usr/local/bin/dotnet', 'pack', '--configuration', 'Release', '--output', 'pre-commit-build')
return code: 145
expected return code: 0
stdout:
    7.0.100 [/usr/local/Cellar/dotnet/7.0.100/libexec/sdk]

stderr:
    The command could not be loaded, possibly because:
      * You intended to execute a .NET application:
          The application 'pack' does not exist.
      * You intended to execute a .NET SDK command:
          A compatible .NET SDK was not found.

    Requested SDK version: 3.1.424
    global.json file: /Users/USERNAME/.cache/pre-commit/repo8rpcf_st/global.json

    Installed SDKs:

    Install the [3.1.424] .NET SDK or update [/Users/USERNAME/.cache/pre-commit/repo8rpcf_st/global.json] to match an installed SDK.

    Learn about SDK resolution:
    https://aka.ms/dotnet/sdk-not-found
```
