### ISSUE TITLE
Make Go a first class language

### ISSUE THREAD

**Issue by taoufik07** [pre-commit/pre-commit#2649]
Hey, as many tools are now built using golang, it would be good to have it as a first class language.

I've hacked a little [POC](https://github.com/pre-commit/pre-commit/compare/main...taoufik07:pre-commit:golang_playground?expand=1) heavily inspired by the ruby lang and using https://github.com/stefanmaric/g as a go version manager.

Please let me know if that's what you had in mind before I go any further.

**Comment by asottile** [comment]
we can't depend on `g` -- but go is simple enough to provision by downloading the appropriate prebuilt bundle from the go website

**Comment by taoufik07** [comment]
Even better, I've updated the [POC](https://github.com/pre-commit/pre-commit/compare/main...taoufik07:pre-commit:golang_playground?expand=1), please let me know if I should open a draft PR.

Downloading golang and installing packages (e.g. tfsec) takes ~50s on a relatively speedy connection and a performant computer, I'm not sure if we can do something about that. Having the download language would help, but that's another discussion.

**Comment by trallnag** [comment]
awesome thanks a lot for this! this will also make it possible to use go hooks with pre-commit.ci

**Comment by asottile** [comment]
@trallnag what do you mean? pre-commit ci already supports go hooks?

**Comment by trallnag** [comment]
I tried to use the following hook some time ago on [pre-commit.ci](pre-commit.ci) and it failed due to Go not being available:

```yaml
repo: https://github.com/golangci/golangci-lint
rev: v1.50.1
hooks:
  - id: golangci-lint
```

So I had to add the hook to `ci.skip`.

Here is the hook declaration:

```yaml
- id: golangci-lint
  name: golangci-lint
  description: Fast linters runner for Go.
  entry: golangci-lint run --fix
  types: [go]
  language: golang
  pass_filenames: false
```
