### ISSUE TITLE
Passing args to docker_image

### ISSUE THREAD

**Issue by KUGA2** [pre-commit/pre-commit#2650]
### search you tried in the issue tracker

docker_image args

### describe your issue

I tried to make my own hook with docker_image.

.pre-commit-hooks.yaml:
```
- id: shellcheck
  name: ShellCheck
  description: |
    Run ShellCheck on all shell files
  language: docker_image
#  entry: koalaman/shellcheck:latest
  entry: alpine:latest echo TMP Checking Arguments --
  args: [--severity=style]
  types: [shell]
```

I want the default severity to be style, but users may overwrite it (see .pre-commit-config.yaml). It seems like the severity from the user is not passed:

```
$ pre-commit try-repo Build/myHook/ shellcheck --verbose --all-files
...
TMP Checking Filenames -- --severity=style bla.sh
```

What am I doing wrong here?

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: Build/pre-commit-template-docker_image
    rev: 02ee589
    hooks:
    - id: shellcheck
      args: [--severity=warning]
```

### ~/.cache/pre-commit/pre-commit.log (if present)

Not present
