### ISSUE TITLE
windows run path error

### ISSUE THREAD

**Issue by mainjzb** [pre-commit/pre-commit#2654]
### search you tried in the issue tracker

yes

### describe your issue

```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: goimports
        name: goimports
        entry: scripts/goimports.sh
        language: script
        types: [ go ]
        pass_filenames: true
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-mod-tidy-repo
      - id: golangci-lint-mod
      - id: my-cmd
        name: goimports
        alias: goimports
        args: [ scripts/goimports.sh, github.com/bookstairs/bookhunter ]
```
got result 
```
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check for added large files..............................................Passed
goimports................................................................Failed
- hook id: goimports
- exit code: 1

Executable `C:\git\devgo\scripts\goimports.sh` not found

go-mod-tidy-repo.........................................................Failed
- hook id: go-mod-tidy-repo
- exit code: 127

/bin/bash: C:Usersmainj.cachepre-commitrepov811f5a4go-mod-tidy-repo.sh: No such file or directory

golangci-lint-mod........................................................Failed
- hook id: golangci-lint-mod
- exit code: 127

/bin/bash: C:Usersmainj.cachepre-commitrepov811f5a4golangci-lint-mod.sh: No such file or directory

goimports................................................................Failed
- hook id: my-cmd
- exit code: 127

/bin/bash: C:Usersmainj.cachepre-commitrepov811f5a4my-cmd.sh: No such file or directory
/bin/bash: C:Usersmainj.cachepre-commitrepov811f5a4my-cmd.sh: No such file or directory
```

why my path miss `\`

### pre-commit --version

pre-commit 2.21.0

git version 2.33.0.windows.2
