### ISSUE TITLE
Unable to determine how to use pre-existing virtualenv for a hook

### ISSUE THREAD

**Issue by EliRibble** [pre-commit/pre-commit#266]
Sorry, I'm not sure if an issue is the right place to put this, but considering I've spent some time reading source and docs and haven't found the answer it seems fair to consider this a documentation bug.

My use case is this: I have many Python projects I work on. Each one has its own virtualenv where I install the dependencies. I'd like to use pre-commit to run pylint. Pylint needs to run out of the same virtualenv as the project so that it can import the dependencies for its static analysis. When running the pylint hook from https://github.com/pre-commit/mirrors-pylint it appears that the command that is actually run is:

`bash -c . '/Users/eliribble/.pre-commit/repoq_elftwa/py_env-default/bin/activate' && xargs -0 -s4000 pylint`

Looking at the source and the docs I can't find a way to indicate to the hook that it should use my virtualenv for the project rather than the virtualenv at `/Users/eliribble/.pre-commit/repoq_elftwa/py_env-default`. Is there a way to do that?

**Comment by chriskuehl** [comment]
One option is to add a hook to `.pre-commit-config.yaml` like:

```yaml
-   repo: local
    hooks:
    -   id: system
        name: PyLint
        entry: python -m pylint.__main__
        language: system
        files: \.py$
```

(stolen from https://github.com/Yelp/pgctl)

Does that work for you? If so, it's probably worth documenting somewhere.

**Comment by asottile** [comment]
Yeah we're still missing proper documentation from #226

We'll track that work here: https://github.com/pre-commit/pre-commit.github.io/issues/50

@EliRibble do local hooks satisfy your requirements?

**Comment by EliRibble** [comment]
Yeah, that will work, though I changed it a bit since we already had a bash script which hands across the correct settings file to pylint. Looks like this, for anyone who hits the same thing:

```
-   repo: local
    hooks:
    -   id: system
        name: PyLint
        entry: ./pylint.sh
        language: system
        files: \.py$
```

Thanks for the fast response.
