### ISSUE TITLE
Built in review of file changes, or auto addition of modification ...

### ISSUE THREAD

**Issue by galyfray** [pre-commit/pre-commit#2675]
### search you tried in the issue tracker

is:issue auto commit modification 

### describe your issue

Hi,
On my python project, I use poetry to handle dependencies. As I didn't want to set up poetry in my CI I added a pre commit hook that export my dependencies to a format readable by pip.
This creates files that only my hooks works on. I would like to have a way to not have to re-run the hooks multiple time to pass those well confined hooks. 

I have read that you are not really prone to easily change your mind. That's why I am not explicitly asking for a way to automatically commit changes from certain hooks. I do think this feature would be powerful and useful for users, but I also understand that this can be quickly dangerous. 

If I have read correctly the last issue related to this, in the past pre-commit did run all hooks even if the first one failed due to file changes. This lead to some weird, unwanted behaviour. 
My proposition to address the issue I have (and I think I am not the only one) is to add a way to specify if a task should not prevent other hooks from running. The committing would still be prevented, but this would allow the users to run the hooks fewer times. 

Another proposition would be to show the changes done by a hook and ask the user if he approves them and want to continue to the other hooks. I do not know which one seems the most feasible and reasonable for you.

For example, I would use this tag to tell my two poetry-export task to not fail fast, but I would let the others failing quickly the process to avoid any issues.

I do not think those are the only way to address the issue I have, it is just the ones I propose. Let me know if you have better ideas.

### pre-commit --version

2.21

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.2.2'
    hooks:
      - id: poetry-export
      - id: poetry-export
        args : ["-f", "requirements.txt", "-o", "requirements-dev.txt", "--with", "dev"]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.0'
    hooks:
    -   id: autopep8
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args: ["--in-place", "--pre-summary-newline"]
  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort
        name: isort
        args: ["-l 119", "--conda-env", "./venv"]
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.4'
    hooks:
    - id: bandit
      args: ["-c", "pyproject.toml"]
      additional_dependencies: [ "bandit[toml]" ]
```
