### ISSUE TITLE
mypy on pre-commit CI fails to install -> pre-commit app fails

### ISSUE THREAD

**Issue by giovp** [pre-commit/pre-commit#2678]
### search you tried in the issue tracker

mypy

### describe your issue

I'm using pre-commit CI github app and in the past days mypy fails to install, see e.g. https://results.pre-commit.ci/run/github/544045123/1672938659.iE11PF5cRnWoIq6zDY_caA

actually not sure if this is the best place to report this... thanks for any input!

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
fail_fast: false
default_language_version:
    python: python3
default_stages:
    - commit
    - push
minimum_pre_commit_version: 2.16.0
repos:
    - repo: https://github.com/psf/black
      rev: 22.12.0
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0-alpha.4
      hooks:
          - id: prettier
    - repo: https://github.com/asottile/blacken-docs
      rev: v1.12.1
      hooks:
          - id: blacken-docs
    - repo: https://github.com/PyCQA/isort
      rev: 5.11.4
      hooks:
          - id: isort
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.991
      hooks:
          - id: mypy
            additional_dependencies: [numpy==1.23.0]
            exclude: tests/|docs/
    - repo: https://github.com/asottile/yesqa
      rev: v1.4.0
      hooks:
          - id: yesqa
            additional_dependencies:
                - flake8-tidy-imports
                - flake8-docstrings
                - flake8-rst-docstrings
                - flake8-comprehensions
                - flake8-bugbear
                - flake8-blind-except
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: detect-private-key
          - id: check-ast
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: trailing-whitespace
          - id: check-case-conflict
    - repo: https://github.com/myint/autoflake
      rev: v2.0.0
      hooks:
          - id: autoflake
            args:
                - --in-place
                - --remove-all-unused-imports
                - --remove-unused-variable
                - --ignore-init-module-imports
    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-tidy-imports
                - flake8-docstrings
                - flake8-rst-docstrings
                - flake8-comprehensions
                - flake8-bugbear
                - flake8-blind-except
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
          - id: pyupgrade
            args: [--py3-plus, --py39-plus, --keep-runtime-typing]
    - repo: local
      hooks:
          - id: forbid-to-commit
            name: Don't commit rej files
            entry: |
                Cannot commit .rej files. These indicate merge conflicts that arise during automated template updates.
                Fix the merge conflicts manually and remove the .rej files.
            language: fail
            files: '.*\.rej$'
    - repo: https://github.com/PyCQA/doc8
      rev: v1.1.1
      hooks:
          - id: doc8
```
