### ISSUE TITLE
Using pre-commits with git-worktree and flutter results in unknown flutter versions

### ISSUE THREAD

**Issue by prestontw** [pre-commit/pre-commit#2681]
### search you tried in the issue tracker

flutter, worktree

### describe your issue

Thank you for this awesome tool! I was running `flutter` pre-commit checks in my repository but getting strange results. As another piece of this puzzle, I was working inside of a git worktree.

I expected that the version of flutter I was using (`beta`) to be used in pre-commit.
(Something like
```
pre-commit-in-worktree on  pre-commit-in-worktree is 📦 v1.0.0+1 via 🎯 took 27s 
❯ flutter --version
Flutter 3.7.0-1.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 9b4416aaa7 (2 days ago) • 2023-01-04 17:29:34 -0600
Engine • revision 7b8906637f
Tools • Dart 2.19.0 (build 2.19.0-444.3.beta) • DevTools 2.20.0
```
)

I got instead `unknown` versions or branches of the git-worktree I was working on listed as versions when reported in `pre-commit`'s output: 
```
flutter-version..........................................................Passed
- hook id: flutter-version
- duration: 29.98s

Flutter • channel unknown • unknown source
Framework • revision 951e00f39e (7 minutes ago) • 2023-01-06 10:46:25 -0600
Engine • revision 7b8906637f
Tools • Dart 2.19.0 (build 2.19.0-444.3.beta) • DevTools 2.20.0
```

I reproduced this in https://github.com/prestontw/flutter-pre-commit-git_worktree-minimal-repo along with instructions on how to reproduce.

### pre-commit --version

pre-commit 2.21.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: flutter-analyze
        name: flutter-analyze
        language: system
        entry: bash -c "flutter analyze"
        verbose: true
    -   id: flutter-version
        name: flutter-version
        language: system
        entry: bash -c "flutter --version"
        verbose: true
    -   id: flutter-channel-list
        name: flutter-channel-list
        language: system
        entry: bash -c "flutter channel"
        verbose: true
    -   id: flutter-test
        name: flutter-test
        language: system
        entry: bash -c "flutter test"
        verbose: true
    -   id: flutter-version-2
        name: flutter-version-2
        language: system
        entry: bash -c "flutter --version"
        verbose: true
```
