### ISSUE TITLE
unable to find python version

### ISSUE THREAD

**Issue by xileftenurb** [pre-commit/pre-commit#2682]
### search you tried in the issue tracker

python version, python in local folder, python not found, python to be healthy immediatly

### describe your issue

I was doing `pre-commit run` for the first time on my computer, (Ubuntu 22.04.1 LTS)
and got an error like what it could not find the right version of python. in fact it could not find any version of python. (see the pre-commit.log)

after investigation on my side,
the `pyvenv.cfg` is here, but there is no "bin" folder next to it,
the `bin` folder is in a `local` folder.

that why pre_commit is unable to find it.

I tryed to uninstall and reinstall pre-commit
also tried `pre-commit clean` and `pre-commit cg`
also tried the `virtualenv --reset-app-data venv -vvvv` that I found in some issue, but it did not fix anything.

### pre-commit --version

pre-commit 2.21.0

### .pre-commit-config.yaml

```yaml
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: no-commit-to-branch

      - id: check-xml
      - id: check-json
      - id: check-yaml

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: script-must-have-extension
      - id: script-must-not-have-extension

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]  # Optionally only show errors and warnings

  - repo: https://github.com/frnmst/md-toc
    rev: 8.1.7
    hooks:
      - id: md-toc
        args: [-p, --skip-lines, '2', 'github']

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
```

### version information

```
pre-commit version: 2.21.0
git --version: git version 2.34.1
sys.version:
    3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /home/fbrunet/.cache/pre-commit/repocfjzu3lg/py_env-python3/bin/python>>
- expected version: 3.10.6.final.0

```

```
Traceback (most recent call last):
  File "/home/fbrunet/.local/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/fbrunet/.local/lib/python3.10/site-packages/pre_commit/main.py", line 394, in main
    return run(args.config, store, args)
  File "/home/fbrunet/.local/lib/python3.10/site-packages/pre_commit/commands/run.py", line 428, in run
    install_hook_envs(to_install, store)
  File "/home/fbrunet/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/home/fbrunet/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 84, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /home/fbrunet/.cache/pre-commit/repocfjzu3lg/py_env-python3/bin/python>>
- expected version: 3.10.6.final.0
