### ISSUE TITLE
Are multiple fixes supported in CI?

### ISSUE THREAD

**Issue by max-sixty** [pre-commit/pre-commit#2687]
### search you tried in the issue tracker

ci autofix

### describe your issue

I was confused by what happened here: https://github.com/PRQL/prql/pull/1470#issuecomment-1375300206. My collaborator had to specifically request `autofix` for pre-commit to fix the second mistake, even though we have the default, which does autofix.

As I wrote on that issue:

> I don't get why this was required — this should be the default. Possibly because it was failing on a commit from itself, and pre-commit doesn't know whether it might be in a loop, so disables that?

Is there something we could be doing to allow multiple repos to apply fixes?

Thanks!

### pre-commit --version

ci

### .pre-commit-config.yaml

```yaml
# From https://github.com/prql/prql/blob/main/.pre-commit-config.yaml

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '(.*\.snap|.*render-link.html)'
      - id: check-yaml
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier
          - prettier-plugin-go-template
  - repo: https://github.com/crate-ci/typos
    rev: v1.13.6
    hooks:
      - id: typos
        # https://github.com/crate-ci/typos/issues/347
        pass_filenames: false
  - repo: https://github.com/r0x0d/pre-commit-rust
    rev: v1.0.1
    hooks:
      - id: fmt
      - id: clippy
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.215
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.10.3
    hooks:
      - id: markdown-link-check
        files: \.md$
        args: ["--config=.github/.markdown-link-check.json"]
  # This is quite strict, and doesn't fix a large enough share of the issues it
  # finds, so we don't include it. But it's reasonable to run every now & again
  # manually and take its fixes.
  #
  # - repo: https://github.com/DavidAnson/markdownlint-cli2
  #   rev: v0.5.1
  #   hooks:
  #     - id: markdownlint-cli2
  #       args: ["--fix"]
  #       additional_dependencies:
  #         - markdown-it-footnote
ci:
  # Currently network access isn't supported in the CI product.
  skip: [fmt, clippy, markdown-link-check]
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
```
