### ISSUE TITLE
Using option --config with a configuration file not in root folder does not work with git commit

### ISSUE THREAD

**Issue by thomasfinchbr** [pre-commit/pre-commit#2691]
### search you tried in the issue tracker

--config

### describe your issue

After running `pre-commit install --config=config\.pre-commit-config.yaml`, where I change the configuration file location when I run `git commit` I get this error at the command line:

No .pre-commit-config.yaml file was found.

It seems that the path of the configuration file is not being passed on. 

### pre-commit --version

pre-commit 2.21.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        additional_dependencies: ['toml']
        args:
        - --config=config/pyproject.toml

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -  id: end-of-file-fixer
    -  id: trailing-whitespace
    -  id: check-added-large-files
    -  id: check-merge-conflict

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0  # Use the ref you want to point at
    hooks:
    -   id: python-use-type-annotations
    -   id: python-check-mock-methods

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.31.0
    hooks:
    -   id: commitizen
        additional_dependencies: ['toml']
        stages: [commit-msg]
```
