### ISSUE TITLE
Autoupdate is not working for repos with maintenance branches

### ISSUE THREAD

**Issue by jirikuncar** [pre-commit/pre-commit#2695]
### search you tried in the issue tracker

autoupdate

### describe your issue

Tags on maintenance branches are not detected.

Proposal:

Use logic from `git tags -l` instead `git describe FETCH_HEAD --tags --abbrev=0`.

### pre-commit --version

master

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.3.0"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
```
