### ISSUE TITLE
issue with pip-audit

### ISSUE THREAD

**Issue by Nicolaus93** [pre-commit/pre-commit#2698]
### search you tried in the issue tracker

pip audit

### describe your issue

Setuptools and wheel are not needed in my project, but they're installed when creating the virtual environment for pip-audit. Unfortunately, they're installed with old versions, causing pip-audit to fail: 
![image-20230111-122916](https://user-images.githubusercontent.com/13076944/212475943-284fb845-5d00-4ef6-83a0-28624c8c1465.png)

I don't understand where the versions of setuptools (63.4.1) and wheel (0.37.1) are retrieved from. 
If I understand it correctly, when precommit installs the hooks, the process is the following:

1. it clones their repositories in a folder like /root/.cache/precommit
2. for every hook, it initializes a virtual environment in the cloned hook repo, with the python interpreter used to run pre-commit
3. the virtual environment is initialized with the command `python -mvirtualenv /path/to/new_pyenv`. 

Unfortunately, the previous command by default includes setuptools and wheel even if they're not actually needed (I believe pip-audit uses [flit](https://github.com/pypa/pip-audit/blob/4f6ccd65a098a222f26b94a274e1c1afe2467110/pyproject.toml#L2)):

![image (3)](https://user-images.githubusercontent.com/13076944/212476150-1c3db8f7-2b94-4d9d-a1b8-fb8bea586955.png)

Ideally, I would like to run`python -mvirtualenv /path/to/new_pyenv` with the additional arguments `--no-setuptools` and `--no-wheel`:

![image (5)](https://user-images.githubusercontent.com/13076944/212476103-9c37bbd1-91e1-4549-9ec9-4eb9a1970fe9.png)

I think this is not possible. I digged into the precommit code and it seems there's no way to add additional arguments to the [command creating the virtual environment](https://github.com/pre-commit/pre-commit/blob/ceb429b25380dacee34ba6997e5dd3d5f09b811a/pre_commit/languages/python.py#L209).

I fixed the issue for now by updating setuptools and wheel using the additional dependencies argument: `additional_dependencies: ["setuptools>=65.5.1", "wheel>=0.38.1"]`. I was wondering if there's a way to not include `setuptools` and `wheel` at all though.

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9 # frozen: v4.4.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  #  - repo: https://github.com/python-poetry/poetry
  #    rev: 1.2.0rc1
  #    hooks:
  #      - id: poetry-check
  - repo: https://github.com/trailofbits/pip-audit
    rev: d3c6051781bfdd49b18e545013da2360ffe9e83b # frozen: v2.4.13
    hooks:
      - id: pip-audit
  - repo: https://github.com/PyCQA/bandit
    rev: "1ed79063e3672a1c6d91ee27cb648e07a7465344" # frozen: 1.7.4
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies:
          - toml
  - repo: https://github.com/pycqa/isort
    rev: 4e97b170469b7c8ef29afe944ebfb057791457aa # frozen: 5.11.4
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
  - repo: https://github.com/psf/black
    rev: 2ddea293a88919650266472186620a98a4a8bb37 # frozen: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: 7ae9389351f4090e3993de28015a05a18ca6b8a7 # frozen: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black>=20.8b1]
  - repo: https://github.com/PyCQA/flake8
    rev: c838a5e98878f17889cfce311e1406d252f87ec5 # frozen: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black>=0.1.1
          - flake8-typing-imports==1.14.0
        language_version: python3
  - repo: https://github.com/asottile/pyupgrade
    rev: 01cee377ba3a5264c7fbe7b6beae7b575f764dc3 # frozen: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/radix-ai/auto-smart-commit
    rev: 4ed772adf00c42e15e7eb7f1ce65bb7729891cb5 # frozen: v1.0.2
    hooks:
      - id: auto-smart-commit
```
