### ISSUE TITLE
Manually override cache in CI jobs

### ISSUE THREAD

**Issue by gipert** [pre-commit/pre-commit#2710]
### search you tried in the issue tracker

pre-commit.ci override cache 

### describe your issue

My pre-commit CI jobs are suddenly failing because of a [new check introduced by flake8-bugbear](https://github.com/PyCQA/flake8-bugbear#23114), despite Flake8's version staying constant. The new behavior was then promptly reverted in a [second release](https://github.com/PyCQA/flake8-bugbear#23117). My (possibly wrong) interpretation is that [the CI job](https://results.pre-commit.ci/run/github/151981074/1674041440.W7YiqLveQOueD7Bx1aBlrA) is still failing (contrary to what happens locally) because of a caching issue.

I was wondering whether there is a way to manually override the cache in CI. I could not find any reference in the docs.

### pre-commit --version

Don't know how to check this in CI

### .pre-commit-config.yaml

```yaml
- repo: https://github.com/PyCQA/flake8
  rev: "6.0.0"
  hooks:
  - id: flake8
    additional_dependencies: [
      flake8-bugbear,
      flake8-print,
      pep8-naming
    ]
```
