### ISSUE TITLE
Generate a pre-commit file coverage report

### ISSUE THREAD

**Issue by hofbi** [pre-commit/pre-commit#2712]
I use `pre-commit` in many of my projects, both open source and industry, and really like it, thank you for that. In one of my industry projects, we have a big codebase. This means we cannot introduce new `pre-commit` hooks including its fixes in a single pull request, but need to roll them out incrementally using `files` and `exclude` regular expressions.

To get some information, how far we are in the integration progress, it would be great to have a metric for that. Motivated by this, I thought about having something like a `pre-commit` file coverage. This means `pre-commit` could generate a report similar to a code coverage report that, for each hook, shows which files or folders are covered by the respective hook. Maybe we could even generate some [gcovr](https://gcovr.com/en/stable/)-compatible files to make use of an established tool.

In general, I don't want to make this a concrete task or feature request, but just drop this idea and get some feedback. If you like it, we could think about how this could look like and how it could be implemented.

**Comment by asottile** [comment]
you can get an understanding of the files that are covered by using the [`meta` `identity`](https://pre-commit.com/#meta-identity) hook with whatever filters you're using -- then you can use that to figure out what's covered or not

for example:

```yaml
-   repo: meta
    hooks:
    -   id: identity
        log_file: all.txt
    -   id: identity
        types: [python]
        files: ^foo/
        log_file: foo
```
