### ISSUE TITLE
SQLFluff fails on Rule L003 in CI but not locally (using pre-commit hooks)

### ISSUE THREAD

**Issue by christopherekfeldt** [pre-commit/pre-commit#2715]
### search you tried in the issue tracker

yes

### describe your issue

Origin issue can be found here: 
 
https://github.com/sqlfluff/sqlfluff/issues/4304

### pre-commit --version

2.21.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0 # Get the latest from: https://github.com/pre-commit/pre-commit-hooks/releases
  hooks:
    # Standard lint
    - id: end-of-file-fixer
      exclude: ^dbt/dbt_packages
    - id: trailing-whitespace
      exclude: ^dbt/dbt_packages
    - id: check-merge-conflict

    # Specific file format linters
    - id: check-yaml
      exclude: ^dbt/dbt_packages
    - id: check-toml
      exclude: ^dbt/dbt_packages
    - id: check-shebang-scripts-are-executable
      exclude: ^dbt/dbt_packages
    - id: check-symlinks
      exclude: ^dbt/dbt_packages

    # Cross platform
    - id: mixed-line-ending
      args: [--fix=lf]
      exclude: ^dbt/dbt_packages

    # Security linters
    - id: detect-private-key

- repo: https://github.com/sqlfluff/sqlfluff
  rev: 1.4.5 # Get the latest from: https://github.com/sqlfluff/sqlfluff/releases
  hooks:
    - id: sqlfluff-lint
      args: [--config, "dbt/.sqlfluff", --processes, "0" ]
      additional_dependencies: ['dbt-bigquery==1.3.0', 'sqlfluff-templater-dbt']
    - id: sqlfluff-fix
      args: [--config, "dbt/.sqlfluff", --processes, "0" ]
      additional_dependencies: ['dbt-bigquery==1.3.0', 'sqlfluff-templater-dbt']

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt

- repo: https://github.com/psf/black
  rev: 22.12.0 # Get the latest from: https://github.com/psf/black/releases
  hooks:
    - id: black
      exclude: ^dbt/dbt_packages
```
