### ISSUE TITLE
Pinning transitive dependencies with lockfile/constraints

### ISSUE THREAD

**Issue by hterik** [pre-commit/pre-commit#2731]
### search you tried in the issue tracker

constraints.txt

### describe your issue

Yesterday, **poetry-core** released version [1.5](https://github.com/python-poetry/poetry-core/releases/tag/1.5.0), that wasn't 100% backwards compatible.  
Some pre-commit hooks that transitively depended on poetry-core, for example **isort**, then also started to break [1], **even if you pinned `rev`-field in `pre-commit-config.yaml`**.
Note that this is not an issue in upstream, it's a issue with creating reproducible environments. We made no change to the `pre-commit-config.yaml` and were already using pinned revisions at every possible location, yet it broke. 

A solution is needed that can generate a lockfile in a format that is easy to integrate into the `pre-commit-config.yaml`, similar to constraints.txt.

The solution of using `additional_dependencies` proposed in https://github.com/pre-commit/pre-commit/issues/1963 is not very user friendly
* Not easy to run `pip freeze` in the virtualenvs automatically created by pre-commit.
* Requires post-processing the output of `pip freeze` before it can be put inside `additional_dependencies`
* Bloats the `pre-commit-config.yaml`. 

Adding something like a `pre-commit freeze` command would help a lot with the first two pain points. 
The last point i don't really have strong opinions about, having it in a separate file would be better, but if a command to generate the necessary content is available, this is more of a cosmetic issue.

Other solutions outside of the box are also welcome. Anything that enables reproducible environments.

------
[1] (Fix for isort is now available https://github.com/PyCQA/isort/commit/0d219a6e0b49b7f84ef0702b2387d5e14299bb8e, this doesn't invalidate the need of having a pinning functionality in general. )

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pycqa/isort
    rev: c5e8fa75dda5f764d20f66a215d71c21cfa198e1  # frozen: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--line-length", "120"]
```
