### ISSUE TITLE
Skipped reason is wrong (no files instead of wrong stage)

### ISSUE THREAD

**Issue by mrcljx** [pre-commit/pre-commit#2744]
### search you tried in the issue tracker

skipped stage

### describe your issue

Next to a black `pre-commit` hook I also have a `post-commit` hook configured.

During `post-commit` the output reads:

```
black.........................................................(no files to check)Skipped
ctags.............................................................................Passed
```

This suggests that the `black` only didn't run because there were no files to check,
but it actually is because `black` is only configured to run during the `pre-commit` stage.

To reduce confusion it would be great if this:

- read as `(wrong stage)Skipped`
- was not shown at all in non-verbose mode.

### pre-commit --version

pre-commit 2.19.0

### .pre-commit-config.yaml

```yaml
default_install_hook_types:
  - pre-commit
  - post-checkout

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        args: [--config, pyproject.toml]
        files: \.(py|pyi)$
      - id: ctags
        name: ctags
        stages: [post-checkout]
        language: system
        entry: .pre-commit/update-ctags.sh
        pass_filenames: false
        always_run: true
```
