### ISSUE TITLE
Github blocked

### ISSUE THREAD

**Issue by hliebert** [pre-commit/pre-commit#2745]
### search you tried in the issue tracker

proxy, blocked, github

### describe your issue

My workplace blocks Github (and maintains a pypi mirror).  Is there a way I can make pre-commit point to the python package on my local machine instead of the git repo? pre-commit, black, isort etc are all installed, but I cannot fetch things from github. 

### pre-commit --version

3.0.3

### .pre-commit-config.yaml

```yaml
default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.0.3
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [--unittest]
      - id: no-commit-to-branch
        args: [--branch, release]
      - id: pretty-format-json
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--line-length=120]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=120]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--line_length=120]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ["--convention=numpy"]

  - repo: https://github.com/asottile/pyupgrade
    rev: 3.3.1
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]
```
