### ISSUE TITLE
AttributeError: 'str' object has no attribute 'value'

### ISSUE THREAD

**Issue by dataspun** [pre-commit/pre-commit#2749]
### search you tried in the issue tracker

AttributeError

### describe your issue

pycln....................................................................Failed
- hook id: pycln
- exit code: 1

Traceback (most recent call last):

  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,

  File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)

  File "C:\Users\Username\.cache\pre-commit\repoqxmi1iil\py_env-python3\Scripts\pycln.EXE\__main__.py", line 7, in <module>
    sys.exit(app())

  File "C:\Users\Username\.cache\pre-commit\repoqxmi1iil\py_env-python3\lib\site-packages\pycln\cli.py", line 167, in main
    configs = Config(

  File "<string>", line 18, in __init__

  File "C:\Users\Username\.cache\pre-commit\repoqxmi1iil\py_env-python3\lib\site-packages\pycln\utils\config.py", line 34, in __post_init__
    ParseConfigFile(file_path, self)

  File "C:\Users\Username\.cache\pre-commit\repoqxmi1iil\py_env-python3\lib\site-packages\pycln\utils\config.py", line 127, in __init__
    self._config.__post_init__()

  File "C:\Users\Username\.cache\pre-commit\repoqxmi1iil\py_env-python3\lib\site-packages\pycln\utils\config.py", line 37, in __post_init__
    self._check_regex()

  File "C:\Users\Username\.cache\pre-commit\repoqxmi1iil\py_env-python3\lib\site-packages\pycln\utils\config.py", line 110, in _check_regex
    str(self.extend_exclude), regexu.EXCLUDE

  File "C:\Users\Username\.cache\pre-commit\repoqxmi1iil\py_env-python3\lib\site-packages\tomlkit\items.py", line 1415, in __str__
    return str([v.value.value for v in self._iter_items() if v.value is not None])

  File "C:\Users\Username\.cache\pre-commit\repoqxmi1iil\py_env-python3\lib\site-packages\tomlkit\items.py", line 1415, in <listcomp>
    return str([v.value.value for v in self._iter_items() if v.value is not None])

AttributeError: 'str' object has no attribute 'value'

### pre-commit --version

pre-commit 2.21.0

### .pre-commit-config.yaml

```yaml
repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ["-r", "-c", "pyproject.toml"]
        additional_dependencies: [ "bandit[toml]" ]
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
    -   id: pycln
        args: ["--config=pyproject.toml"]
```
