### ISSUE TITLE
Don't work with unstaged files on Windows

### ISSUE THREAD

**Issue by LorhanSohaky** [pre-commit/pre-commit#2764]
### search you tried in the issue tracker

unstaged

### describe your issue

When running `pre-commit run --all-files` the unstaged files are not formatted. But when I execute `black src\wsl_manager\example.py --line-length 79 --preview` the code is formatted.

I tried to reproduce the same behavior in [codesandbox](https://codesandbox.io/p/sandbox/peaceful-sun-bub7ou?file=%2Fmain.py&selection=%5B%7B%22endColumn%22%3A45%2C%22endLineNumber%22%3A22%2C%22startColumn%22%3A45%2C%22startLineNumber%22%3A22%7D%5D), but it seems that it is related to the Windows environment.

System version `Microsoft Windows [versão 10.0.22621.1265]`

https://user-images.githubusercontent.com/16273730/219922450-9862741f-a228-472a-8a97-f297b24d2a72.mp4

### pre-commit --version

pre-commit 3.0.4

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        args: ["--line-length", "79", "--preview"]
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        args: ["--profile", "black", "--line-length", "79"]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
```

### ~/.cache/pre-commit/pre-commit.log (if present)

I cant find in Windows
