### ISSUE TITLE
Problem with "python/python3" key

### ISSUE THREAD

**Issue by SergiiPachkovskyi** [pre-commit/pre-commit#2780]
### search you tried in the issue tracker

different python commands

### describe your issue

I have python 3.11 and access to it through the `python` command. My temmate has 3.11 too through the `python3` command.
When he add new repo to .pre-commit-config.yaml with `entry: python3 manage.py test` I got ann error. How can I fix this?

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
- repo: local
    hooks:
      - id: django-test
        name: django-test
        entry: python3 manage.py test
        always_run: true
        pass_filenames: false
        language: system
```
