### ISSUE TITLE
How to add files back to staging area after hook fail

### ISSUE THREAD

**Issue by fanto88** [pre-commit/pre-commit#2786]
### search you tried in the issue tracker

back to staged 

### describe your issue

It's not really a bug report, i couldn't find any other way to open a thread.

I know for security reason you have to add files back manually if an hooks fails, but is there a way to make this automatically? 

For example, i'm using

`  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: fix-encoding-pragma --remove
      - id: debug-statements
 `
 
 I would like for those to add the files back to the staging area after the hooks run instead of report failed, is that possible?

Thanks

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
- repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: fix-encoding-pragma --remove
      - id: debug-statements
```
