### ISSUE TITLE
additional_dependencies: executable in a different language

### ISSUE THREAD

**Issue by tdegeus** [pre-commit/pre-commit#2791]
### search you tried in the issue tracker

"nested", "mixed language", "additional_dependencies"

### describe your actual problem

I have a `python` tool, in which I would like to use a `perl` executable (that has a pre-commit hook, should that be relevant). I can make it work with conda:
```yaml
- id: texcleanup
  name: texcleanup
  description: Run texcleanup
  minimum_pre_commit_version: 2.1.0
  entry: texcleanup
  language: conda
  types: [tex]
  additional_dependencies: [texplain, latexindent.pl]
```

But I also want to make it work without conda. 
This is what I tried, but this tries to install `latexindent.pl` with python, which naturally fails as it is written in `perl`.
```yaml
- id: texcleanup
  name: texcleanup
  description: Run texcleanup
  minimum_pre_commit_version: 2.1.0
  entry: texcleanup
  language: python
  types: [tex]
  additional_dependencies: [https://github.com/cmhughes/latexindent.pl]
```

### pre-commit --version

pre-commit 3.0.4
