### ISSUE TITLE
No such file or directory: '/github/home/.cache/pre-commit/repo4mrvfeou/rbenv-system/.install_state_v1staging'

### ISSUE THREAD

**Issue by lmilbaum** [pre-commit/pre-commit#2799]
### search you tried in the issue tracker

Found this one #1658

### describe your issue

Running pre-commit GitHub action in a [custom container](https://github.com/platform-engineering-org/helper/blob/main/Dockerfile).

Workflow is [broken](https://github.com/platform-engineering-org/bootstrap/actions/runs/4342905858/jobs/7584289627):
```
[INFO] Installing environment for https://github.com/markdownlint/markdownlint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: '/github/home/.cache/pre-commit/repo4mrvfeou/rbenv-system/.install_state_v1staging'
```

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
---
ci:
  skip: [terraform_fmt, terraform_validate, terragrunt_validate]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: check-docstring-first
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args:
          - "--branch"
          - "main"
      - id: check-symlinks
      - id: detect-private-key
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: check-json
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        additional_dependencies: [rake]
  - repo: https://github.com/maxbrunet/pre-commit-renovate
    rev: 34.157.1
    hooks:
      - id: renovate-config-validator
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1
    hooks:
      - id: terraform_providers_lock
        args:
          - --tf-init-args=-upgrade
      - id: terraform_fmt
      - id: terraform_validate
      - id: terragrunt_validate
```

**Comment by asottile** [comment]
you found an exact duplicate, why did you make an issue?

**Comment by asottile** [comment]
you've not shown what you've tried so I don't know how to help you.  right now it looks like you've tried nothing

**Comment by lmilbaum** [comment]
I've tried to check rbenv is installed the container. It is not. 
I've checked the ruby version. It is 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux].
What else can I try?

**Comment by asottile** [comment]
clearly that container is broken -- why do you need that container?  also looks like your CI is running both pre-commit.ci and github actions pre-commit -- which is kind of wasteful

**Comment by lmilbaum** [comment]
> clearly that container is broken -- why do you need that container? also looks like your CI is running both pre-commit.ci and github actions pre-commit -- which is kind of wasteful

Agree. It is broken but I don't have enough ruby expriance to figure out what is broken and fix it. The container is built by me and it used for baking all my team tooling in a container image instead of installing/upgrading them on our laptops.

**Comment by asottile** [comment]
if your company wants paid support I'm happy to provide it -- but this seems like you've already got several solutions which don't involve that container

**Comment by lmilbaum** [comment]
I am pocking the pre-commit code. It seems like the language ruby ENVIRONMENT_DIR is set to rbenv while the container image doesn't have it.
Even if I do install rbenv, the error is still there.

**Comment by lmilbaum** [comment]
In repository.py line 108,  it tries to write a file in a directory which doesn't exist. Could you provide me a hint who is responsible to create it?

**Comment by pbrkr** [comment]
@asottile I'm seeing the same issue described here, and do not have `rbenv` installed so #1658 doesn't give a solution.

Looking at the code, the `install_environment()` function at https://github.com/pre-commit/pre-commit/blob/8d84a7a2702b074a8b46f5e38af28bd576291251/pre_commit/languages/ruby.py#L114 seems to be responsible for creating the environment directory. If the version is `system`, we don't run `rbenv init -`. So are we expecting `gem build ...` to create the `rbenv-system` directory?

I've looked in `~/.cache/pre-commit/pre-commit.log` but I don't see any useful information.

If the output of `gem build ...` contains some useful information on what's going wrong, it's being dropped. `cmd_output_b()` (https://github.com/pre-commit/pre-commit/blob/8d84a7a2702b074a8b46f5e38af28bd576291251/pre_commit/util.py#L89) collects the stdout & stderr of the called process and returns them, but `setup_cmd()` (https://github.com/pre-commit/pre-commit/blob/8d84a7a2702b074a8b46f5e38af28bd576291251/pre_commit/lang_base.py#L91) is ignoring them. Perhaps more verbose output is needed in the case of an error.

**Comment by jaysoffian** [comment]
Seeing same thing as https://github.com/pre-commit/pre-commit/issues/2799#issuecomment-1510465720

Occurs during `pre-commit install-hooks` with this hook:

```yaml
repos:
  - repo: https://github.com/rubocop/rubocop
    rev: v1.52.0
    hooks:
      - id: rubocop

```

### version information

```
pre-commit version: 3.3.2
git --version: git version 2.39.3
sys.version:
    3.11.2 (main, Mar  9 2023, 21:49:05) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]
sys.executable: .../bin/python3.11
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/pre-commit/repo238a8i_c/rbenv-system/.install_state_v1staging'
```

```
Traceback (most recent call last):
  File ".../lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File ".../lib/python3.11/site-packages/pre_commit/main.py", line 410, in main
    return install_hooks(args.config, store)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pre_commit/commands/install_uninstall.py", line 146, in install_hooks
    install_hook_envs(all_hooks(load_config(config_file), store), store)
  File ".../lib/python3.11/site-packages/pre_commit/repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File ".../lib/python3.11/site-packages/pre_commit/repository.py", line 111, in _hook_install
    with open(staging, 'w') as state_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/pre-commit/repo238a8i_c/rbenv-system/.install_state_v1staging'
```

(I've partially elided the Python paths above.)

There directory `/root/.cache/pre-commit/repo238a8i_c/rbenv-system` does NOT exist. I'm not sure what's supposed to create it.
