### ISSUE TITLE
Add if condition inside bash script

### ISSUE THREAD

**Issue by fanto88** [pre-commit/pre-commit#2802]
### search you tried in the issue tracker

conditional 

### describe your issue

It's possible to add a check if a folder exists before running command? Otherwise the hook will fail

Basically i would like to check if the folder exists, if yes then execute the hook, otherwise exit the hook without failing.

I know about the SKIP https://pre-commit.com/#temporarily-disabling-hooks, but i didn't understand how i could use that programmatically without having to write like

```SKIP=pretty-quick git commit -m "foo"```

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
- repo: local
    hooks:
      - id: pretty-quick
        name: Prettify staged js/ts/yml files
        language: system
        entry: bash -c '[ -d "frontend" ] && cd frontend && yarn pretty-quick' --
```
