### ISSUE TITLE
unexpected flag: --java-opt with a Coursier-based hook (dustinsand/pre-commit-jvm)

### ISSUE THREAD

**Issue by vorburger** [pre-commit/pre-commit#2807]
### search you tried in the issue tracker

java-opt

### describe your issue

https://github.com/dustinsand/pre-commit-jvm/issues/8 may actually be something wrong in pre-commit's Coursier launch, not in that particular hook?  Basically https://github.com/google/google-java-format seems to receive an `unexpected flag: --java-opt`... but I don't see anything in `dustinsand/pre-commit-jvm` which could be related to that (its "code" seems super trivial) - so presumably `pre-commit` somehow passes an argument to Courier wrong? Perhaps it's related to the coursier version - maybe their CLI arguments changed? I have Coursier version 2.1.0-RC5.

### pre-commit --version

pre-commit 3.1.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      # TODO - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.1
    hooks:
      - id: editorconfig-checker

  - repo: https://github.com/dustinsand/pre-commit-jvm
    rev: v0.7.0
    hooks:
      - id: google-java-formatter-jdk11
        args: [--replace, --set-exit-if-changed]
```

### ~/.cache/pre-commit/pre-commit.log (if present)

It's not present. Is there a way to launch it with some debug kind of arg to get more details about what exactly it launches how?
