### ISSUE TITLE
[Windows 11] Significant perf decrease using Powershell vs Ubuntu(WSL)

### ISSUE THREAD

**Issue by ave-nabulio** [pre-commit/pre-commit#2828]
### search you tried in the issue tracker

performance powershell; slow; powershell slow

### describe your issue

Trying to use [sqlfluff](https://docs.sqlfluff.com/en/stable/gettingstarted.html) as a prehook within Powershell, the time to run the command `pre-commit run --files .\test.sql` is huge.

the test.sql file:
```sql
SELECT a + b  AS foo,
c AS bar from my_table
```

**Timing:**
- Ubuntu **0.72s**
- Powershell **9.52s**

**My assumptions:**
- It is not related to the number of files parsed: I ran the same command on both OS and Powershell is one order slower than Ubuntu
- It is not related to the sqlfluff hook because running the command `sqlfluff lint test.sql --dialect bigquery` is taking:

Ubuntu: 
```shell
real    0m0.660s
user    0m0.590s
sys     0m0.070s
```

Powershell:
```powershell
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 340
Ticks             : 13401286
TotalDays         : 1.55107476851852E-05
TotalHours        : 0.000372257944444444
TotalMinutes      : 0.0223354766666667
TotalSeconds      : 1.3401286
TotalMilliseconds : 1340.1286
```

**What I tried**
1) Change the Python version 3.(8, 9, 10)
2) Change the pre-commit version

**To reproduce the issue:**
```powershell
virtualenv --python python3.10 venv
pip install pre-commit
pre-commit install
```
add the test.sql file mentioned above then `pre-commit run --files .\test.sql`

----

Thus I suppose this is a bug from pre-commit. Anyone can reproduce the issue or have any ideas ?

Thanky you very much for you support!

### pre-commit --version

3.2.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 2.0.2
  hooks:
    - id: sqlfluff-lint
      # For dbt projects, this installs the dbt "extras".
      # You will need to select the relevant dbt adapter for your dialect
      # (https://docs.getdbt.com/docs/available-adapters):
      args: [--dialect, "bigquery"]
      # additional_dependencies: ['<dbt-adapter>', 'sqlfluff-templater-dbt']
```

### ~/.cache/pre-commit/pre-commit.log (if present)

None
