### ISSUE TITLE
Fails to run when using tea

### ISSUE THREAD

**Issue by jylin** [pre-commit/pre-commit#2830]
### search you tried in the issue tracker

tea

### describe your issue

When using Python automatically installed from https://tea.xyz, it seems pre-commit fails to detect Python version. Adding a default_language_version to my config did not seem to fix it either.

```
An unexpected error has occurred: CalledProcessError: command: ('/Users/aa/.tea/pre-commit.com/v3.2.0/venv/bin/python', '-mvirtualenv', '/Users/aa/.cache/pre-commit/repoa42tj295/py_env-python3.11')
return code: 1
stdout:
    RuntimeError: failed to detect cpython3.11.2-64|cpython3.11.2|cpython3.11-64|cpython3.11|cpython3-64|cpython3|cpython-64|cpython|python3.11.2-64|python3.11.2|python3.11-64|python3.11|python3-64|python3|python-64|python in /Users/aa/.tea/python.org/v3.11.2
stderr: (none)
Check the log at /Users/aa/.cache/pre-commit/pre-commit.log
```

### pre-commit --version

3.2.0

### .pre-commit-config.yaml

```yaml
default_language_version:
  python: python3
repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
```
