### ISSUE TITLE
autoupdate down grade poetry hooks version

### ISSUE THREAD

**Issue by trim21** [pre-commit/pre-commit#2831]
### search you tried in the issue tracker

autoupdate

### describe your issue

run autoupdate with repo https://github.com/python-poetry/poetry ref 1.4.1

but auto update downgrade it to 1.4.0

### pre-commit --version

3.2.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.4.1"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        name: poetry-lock-check
        args: [--check]
```
