### ISSUE TITLE
fix-encoding-pragma hooks always fails

### ISSUE THREAD

**Issue by fanto88** [pre-commit/pre-commit#2837]
### search you tried in the issue tracker

fix-encoding-pragma, always fails, debug-statements

### describe your issue

When running the hooks in the pre-commit-config.yaml the hook fix-encoding-pragma e debug-statements fails (remove the # -*- coding: utf-8 -*- for example, but fails) and then i can't proceed to the commit. If i try to commit again i get the same error.

I tried adding: bash -c 'fix-encoding-pragma --remove "$@"; git add -u' to execute the hook and then add back the file to the staged area, but doesn't seems to work. Any solution to make the hook run and add the files back?

Thanks, Davide

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
- repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: requirements-txt-fixer
      - id: fix-encoding-pragma
        entry: bash -c 'fix-encoding-pragma --remove "$@"; git add -u'
      - id: debug-statements
        entry: bash -c 'debug-statements "$@"; git add -u'
```
