### ISSUE TITLE
Error: spawn E2BIG

### ISSUE THREAD

**Issue by pokey** [pre-commit/pre-commit#2841]
### search you tried in the issue tracker

E2BIG

### describe your issue

When running the pre-commit GitHub action with prettier, I get the following error:

```
node:internal/child_process:420
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at spawn (node:child_process:733:9)
    at spawn (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@7.31.0/node_modules/pnpm/dist/pnpm.cjs:83487:19)
    at runCmd_ (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@7.31.0/node_modules/pnpm/dist/pnpm.cjs:99638:20)
    at runCmd (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@7.31.0/node_modules/pnpm/dist/pnpm.cjs:99579:9)
    at runPackageLifecycle (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@7.31.0/node_modules/pnpm/dist/pnpm.cjs:99546:7)
    at Array.<anonymous> (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@7.31.0/node_modules/pnpm/dist/pnpm.cjs:99019:13)
    at LOOP (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@7.31.0/node_modules/pnpm/dist/pnpm.cjs:99046:18)
    at chain (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@7.31.0/node_modules/pnpm/dist/pnpm.cjs:99053:9)
    at lifecycle_ (/home/runner/setup-pnpm/node_modules/.pnpm/pnpm@7.31.0/node_modules/pnpm/dist/pnpm.cjs:99520:7) {
  errno: -7,
  code: 'E2BIG',
  syscall: 'spawn'
}
```

It seems like pre-commit is a bit too aggressive with the number of arguments it uses.  It appears to take into account args passed in to `args` here

https://github.com/pre-commit/pre-commit/blob/5027592625f8df286dea831e84e7bf83021b7c1b/pre_commit/xargs.py#L79

but if a subcommand has a couple additional args, it can spill over the limit.  It would be great either to:

- Be more conservative, eg try to stay 10 args below the limit?  I don't think that would sacrifice too much
- Add a setting that can be used to indicate how many args a given subcommand may use?

Here is a failed run https://github.com/cursorless-dev/cursorless/actions/runs/4650363149/jobs/8229305045?pr=1404

Fwiw it works locally, but this still feels like a bug with `pre-commit` itself rather than the `pre-commit` GitHub action.  Happy to move the issue there tho if preferred

### pre-commit --version

pre-commit 3.2.2

### .pre-commit-config.yaml

```yaml
minimum_pre_commit_version: "2.9.0"
ci:
  autoupdate_schedule: monthly
exclude: /vendor/
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: local
    hooks:
      - id: forbid-symlinks
        name: Forbid symlinks
        entry: Forbid symlinks
        language: fail
        types: [symlink]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude_types: [svg]
        exclude: patches/.*\.patch
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        # Trailing whitespace breaks yaml files if you use a multiline string
        # with a line that has trailing white space. Many of our recorded
        # tests use strings with trailing white space to represent the final
        # document contents. For example
        # packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/ruby/changeCondition.yml
        exclude: ^packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/.*/[^/]*\.yml$
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        files: \.(ts|tsx)$
        language: system
        entry: pnpm pre-commit:eslint
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        types: [text]
        language: system
        entry: pnpm pre-commit:prettier
  - repo: https://github.com/ikamensh/flynt/
    rev: "0.78"
    hooks:
      - id: flynt
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.260"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/wenkokke/talonfmt
    rev: 1.9.5
    hooks:
      - id: talonfmt
        args: ["--in-place"]
```
