### ISSUE TITLE
An unexpected error has occurred: CalledProcessError

### ISSUE THREAD

**Issue by jjkim0816** [pre-commit/pre-commit#2842]
### search you tried in the issue tracker

pylint

### describe your issue

I use Pycharm, And I should commit&push on Git repo, but I can't it.
I installed plug-in in Pycharm, and I did set environment on "Settings > Other settings > Pylint".
Is there the fault that I did not another setting?

### pre-commit --version

pre-commit 3.2.1

### .pre-commit-config.yaml

```yaml
default_language_version:
    python: python3.8

repos:
    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
        - id: black
          args:
            - --line-length=240

    - repo: https://github.com/pycqa/pylint
      rev: pylint-2.5.3
      hooks:
        - id: pylint
          verbose: true
          exclude: tests/
          args:
            - --rcfile=.pylintrc
```

### ~/.cache/pre-commit/pre-commit.log (if present)

An unexpected error has occurred: CalledProcessError: command: ('/Users/aimmo-aiy-0204/.cache/pre-commit/repoz7q27sgn/py_env-python3.8/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /Users/aimmo-aiy-0204/.cache/pre-commit/repoz7q27sgn
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> [1 lines of output]
          error in pylint setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.5.*'
          [end of output]
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
