### ISSUE TITLE
cache pre-commit package itself

### ISSUE THREAD

**Issue by maciejskorski** [pre-commit/pre-commit#2847]
### search you tried in the issue tracker

cache pre-commit package

### describe your actual problem

While I am supper happy that hooks can be cached - which reduces minutes to pay - I wonder **whether the package can be cached itself**. As of now, the workflow seems to be: 1. install pre-commit from internet 2. restore cached hooks if any 3. run hooks. I would like to optimize the first step. I could try to cache its sources by another action, but I am interested to know if this is reasonable to expect `pre-commit` to support this? Thanks!!!

```
Run pre-commit/action@v3.0.0
Run python -m pip install pre-commit
Collecting pre-commit
  Downloading pre_commit-2.21.0-py2.py3-none-any.whl (201 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.9/201.9 kB 5.5 MB/s eta 0:00:00
...
Run actions/cache@v3
Received 20920437 of 20920437 (100.0%), 75.0 MBs/sec
Cache Size: ~20 MB (20920437 B)
/usr/bin/tar -xf /home/runner/work/_temp/45[13](https://github.com/Snarto-ml/duplicate-detection/actions/runs/4740612421/jobs/8416676613#step:4:15)fc90-b99d-4683-985d-23[15](https://github.com/Snarto-ml/duplicate-detection/actions/runs/4740612421/jobs/8416676613#step:4:17)e[36](https://github.com/Snarto-ml/duplicate-detection/actions/runs/4740612421/jobs/8416676613#step:4:38)[54](https://github.com/Snarto-ml/duplicate-detection/actions/runs/4740612421/jobs/8416676613#step:4:57)c6a/cache.tzst -P -C /home/runner/work/duplicate-detection/duplicate-detection --use-compress-program unzstd
Cache restored successfully
Run pre-commit run --show-diff-on-failure --color=always --all-files
check yaml...............................................................Passed
black-jupyter............................................................Passed
```

### pre-commit --version

pre-commit 2.21.0

**Comment by asottile** [comment]
it's a pip package like any other

**Comment by maciejskorski** [comment]
> it's a pip package like any other

This is trivial and I **seek for integration with pre-commit**. Here is a solution not using the pre-commit action
```
name: pre-commit

on:
  push:
    branches: [experiments]
  pull_request:
    branches: [experiments, main]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: cache pre-commit deps
      id: cache_pre_commit
      uses: actions/cache@v3
      env:
          cache-name: cache-pre-commit
      with:
        path: |
          .pre_commit_venv 
          ~/.cache/pre-commit
        key: ${{ env.cache-name }}-${{ hashFiles('.pre-commit-config.yaml','~/.cache/pre-commit/*') }}
    - name: install pre-commit
      if: steps.cache_pre_commit.outputs.cache-hit != 'true'
      run: |
        python -m venv .pre_commit_venv
        . .pre_commit_venv/bin/activate
        pip install --upgrade pip
        pip install pre-commit
        pre-commit install --install-hooks
        pre-commit gc
    - name: run pre-commit hooks
      run: |
        . .pre_commit_venv/bin/activate  
        pre-commit run --color=always --all-files
```
