### ISSUE TITLE
use local executable wrapper option

### ISSUE THREAD

**Issue by divansantana** [pre-commit/pre-commit#2849]
### search you tried in the issue tracker

local executable wrapper

### describe your actual problem

Is there a way, to get pre-commit to not install a binary, but just
use a local binary wrapper?

For instance my OS (OpenBSD) can't build tfsec, but I have a tfsec in
my path, which runs a docker image with the correct version.

Could I somehow pass some option to pre-commit to simply use the local
wrapper rather then attempting (&failing) to install the executable?

### pre-commit --version

pre-commit 3.2.2

**Comment by asottile** [comment]
what have you tried? the docs have some things that are exactly what you're asking for and using similar words to the ones you've used here

**Comment by divansantana** [comment]
I did read through the docs and issues but didn't see anything there.  Checked now after you suggested it's there and got this, which works:

```yaml
  - repo: local
    hooks:
      - id: tfsec
        name: TFSec
        description: TFsec is a tool to statically analyze Terraform.
        language: system
        entry: tfsec
        pass_filenames: false
```

Thank you and apologies.
