### ISSUE TITLE
'pre-commit validate-config' works fine but pre-commit outputs warning

### ISSUE THREAD

**Issue by bibs2091** [pre-commit/pre-commit#2851]
### search you tried in the issue tracker

2064

### describe your issue

I am trying to make my pre-commit-config DRY.
When I run `pre-commit` i face this warning:
`[WARNING] Unexpected key(s) present at root: base_hook_config`
Yet the installation complete normally, which is confusing because `pre-commit validate-config` output nothing.

Expected: either both have warnings or none has a warning.

### pre-commit --version

3.2.2

### .pre-commit-config.yaml

```yaml
base_hook_config:  &base_hook_config
  language: system
  types: [python]
  require_serial: true
  exclude: '\.ipynb$|docs/.*'

repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8
        args: [--config, .flake8]
        <<: *base_hook_config

      - id: mypy
        name: mypy
        entry: poetry run mypy
        args: [--ignore-missing-imports, --config-file, .mypy.ini]
        <<: *base_hook_config
```
