### ISSUE TITLE
Allow hook_types execution per repo

### ISSUE THREAD

**Issue by evairmarinho** [pre-commit/pre-commit#2852]
### search you tried in the issue tracker

hook

### describe your actual problem

I would like the commit-msg hook to run only for the pre-commit-hooks from the commitize repository. I've used this setup below, but apparently it's replaying pre-commit hooks from another repository.

Current `.pre-commit-config.yaml`
```yml
default_install_hook_types: [pre-commit,commit-msg]
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.76.1
    hooks:
      - id: terraform_validate
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_tfsec
        args:
            - '--args=--no-color'
            - '--args=--exclude-downloaded-modules'
      - id: terraform_docs
        args:
         - '--args=--sort-by required'

```

Purpose `.pre-commit-config.yaml`
```yml
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    hook_types: [commit-msg]
    rev: v2.42.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
  - repo: https://github.com/antonbabenko/pre-commit-terraform.git 
    hook_types: [pre-commit] # could be default
    rev: v1.76.1
    hooks:
      - id: terraform_validate
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_tfsec
        args:
            - '--args=--no-color'
            - '--args=--exclude-downloaded-modules'
      - id: terraform_docs
        args:
         - '--args=--sort-by required'

```

### pre-commit --version

pre-commit 3.2.2
