### ISSUE TITLE
Hook being skipped for file types it should match

### ISSUE THREAD

**Issue by sysadmiral** [pre-commit/pre-commit#2853]
### search you tried in the issue tracker

skipped is:closed is:issue

### describe your issue

I have a terraform directory. Laid out as:

```
\_foo
 \_.tf files
 \_.hcl lockfile
other_stuff
```

My `.pre-commit-config.yaml` includes a hook to run `terraform-docs` in `foo`:

```
      - name: foo-terraform-docs
        id: terraform-docs-system
        alias: foo-terraform-docs
        args: ["./foo/"]
        files: "foo/"
        pass_filenames: false

        types: [
          hcl,
          terraform
        ]
```

If I run `terraform-docs` on the cli it works with `terraform-docs ./foo/`. But `pre-commit` will Skip the hook every time.

Have looked through other issues but couldn't see anything that helped what I was doing.

### pre-commit --version

pre-commit 3.1.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: detect-private-key
    - id: fix-byte-order-marker
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-no-color
          - --args=-diff
          - --args=-check
      - id: terraform_tfsec
        args:
          - --args=--config-file=.config/tfsec.yml
        types: [terraform]
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - name: foo-terraform-docs
        id: terraform-docs-system
        alias: foo-terraform-docs
        args: ["./foo"]
        files: "foo/"
        pass_filenames: false

        types: [
          hcl,
          terraform
        ]
```
