### ISSUE TITLE
Changes from pyupgrade hook not detected

### ISSUE THREAD

**Issue by intgr** [pre-commit/pre-commit#2862]
### search you tried in the issue tracker

pyupgrade, ignored, skipped

### describe your issue

I'm using pre-commit with pyupgrade in two very simlar projects.

After bumping `pyupgrade` args to `--py38-plus` in one project (django-stubs), pre-commit.ci automatically pushed fixes https://github.com/typeddjango/django-stubs/pull/1459/commits/025eec11a5b4d1ae2efb5f8727439029ce1d61af

But in another project (djangorestframework-stubs), after updating `pyupgrade` to `--py38-plus`, pre-commit does not notice that files need fixing: https://github.com/typeddjango/djangorestframework-stubs/pull/399

----

I can reproduce this locally, in branch `drop-python-37` from https://github.com/intgr/djangorestframework-stubs.git

```
% pre-commit run --all-files -v pyupgrade
pyupgrade................................................................Passed
- hook id: pyupgrade
- duration: 1.24s
% git diff
[no changes]
```

How can I debug this? There should be a flag to tell `pre-commit` to display the exact commands it's executing.

----

When I run `pyupgrade` manually from command line, I get 4 changed files:

```
% pyupgrade --py38-plus rest_framework-stubs/*.pyi
Rewriting rest_framework-stubs/decorators.pyi
Rewriting rest_framework-stubs/fields.pyi
Rewriting rest_framework-stubs/serializers.pyi
Rewriting rest_framework-stubs/status.pyi
% git diff --stat
 rest_framework-stubs/decorators.pyi  | 3 ++-
 rest_framework-stubs/fields.pyi      | 3 ++-
 rest_framework-stubs/serializers.pyi | 2 +-
 rest_framework-stubs/status.pyi      | 2 +-
 4 files changed, 6 insertions(+), 4 deletions(-)
```

### pre-commit --version

pre-commit 2.21.0 and pre-commit 3.2.2 (tested with both)

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: check-merge-conflict
      - id: end-of-file-fixer
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (pyi)
        types: [pyi]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
        - flake8-pyi==22.11.0
        types: []
        files: ^.*.pyi?$

ci:
    autofix_commit_msg: '[pre-commit.ci] auto fixes from pre-commit.com hooks'
    autofix_prs: true
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    submodules: false
```

### ~/.cache/pre-commit/pre-commit.log (if present)

(not present)
