### ISSUE TITLE
Git URL rewriting not working

### ISSUE THREAD

**Issue by mkschreder** [pre-commit/pre-commit#2875]
### search you tried in the issue tracker

insteadOf

### describe your issue

When I want to checkout repositories in CI using CI token, I use git url config value with "insteadOf" to rewrite the URL. This works for all repositories besides pre-commit hooks. I would expect that pre-commit would use global git options on checkout and rewrite the repository urls as well, however this is not what is happening.

Did I miss something?

### pre-commit --version

3.2.2

### .pre-commit-config.yaml

```yaml
For example:


- repo: git@host:mirrors/yamllint
    rev: v1.31.0
    hooks:
      - id: yamllint
```
```


### ~/.cache/pre-commit/pre-commit.log (if present)

_No response_
