### ISSUE TITLE
Filename starting with dash fail with most hooks

### ISSUE THREAD

**Issue by dzamlo** [pre-commit/pre-commit#2896]
### search you tried in the issue tracker

dash, --, -

### describe your issue

For most hooks, filenames are passed as argument to the command. A filename that start with a dash is then interpreted by the command as an option instead of a filename.

One way to solve the issue is to prefix the filenames with `./`.

You can see https://github.com/cachix/pre-commit-hooks.nix/issues/303 for more context.

### pre-commit --version

pre-commit 3.3.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.6.0-2
    hooks:
      - id: shfmt
```
