### ISSUE TITLE
local hook for r does not with latest {renv} releases anymore since template is incompatible with it

### ISSUE THREAD

**Issue by lorenzwalthert** [pre-commit/pre-commit#2899]
### search you tried in the issue tracker

renv, the concrete error I get

### describe your issue

I wanted to install a local hook and it failed when I had a recent version of {renv} globally installed.

```
    # Bootstrapping renv 0.12.5 --------------------------------------------------
    * Downloading renv 0.12.5 from CRAN archive ... OK
    * Installing renv 0.12.5 ... Done!
    * Successfully installed and loaded renv 0.12.5.
    Error in aliased_path(path) : could not find function "aliased_path"
    Calls: source ... eval -> <Anonymous> -> renv_load_switch -> warningf
    Traceback (most recent calls last):
    20: source("renv/activate.R")
    19: withVisible(eval(ei, envir))
    18: eval(ei, envir)
    17: eval(ei, envir)
    16: local(...)
    15: eval.parent(substitute(eval(quote(expr), envir)))
    14: eval(expr, p)
    13: eval(expr, p)
    12: eval(quote(...), new.env())
    11: eval(quote(...), new.env())
    10: renv::load()
     9: renv_load_switch(project)
     8: warningf(fmt, renv_path_pretty(project))
     7: warning(sprintf(fmt, ...), call. = call., immediate. = immediate.)
     6: sprintf(fmt, ...)
     5: base::sprintf(fmt, ...)
     4: renv_path_pretty(project)
     3: shQuote(aliased_path(path), type = "cmd")
     2: gsub("(\\\\*)\"", "\\1\\1\\\\\"", string)
     1: is.factor(x)
    Execution halted
    
Check the log at /Users/lorenz/.cache/pre-commit/pre-commit.log
lorenz@Lorenzs-MacBook-Air-2 precommit % pre-commit autoupdate
Updating https://github.com/lorenzwalthert/precommit ... already up to date.
Updating https://github.com/pre-commit/pre-commit-hooks ... 
lorenz@Lorenzs-MacBook-Air-2 precommit % pre-commit install
pre-commit installed at .git/hooks/pre-commit
lorenz@Lorenzs-MacBook-Air-2 precommit % pre-commit install --install-hooks
pre-commit installed at .git/hooks/pre-commit
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Library/Frameworks/R.framework/Resources/bin/Rscript', '--vanilla', '-e', '    options(install.packages.compile.from.source = "never", pkgType = "binary")\n            prefix_dir <- \'/Users/lorenz/.cache/pre-commit/repoggf39dap\'\n        options(\n            repos = c(CRAN = "https://cran.rstudio.com"),\n            renv.consent = TRUE\n        )\n        source("renv/activate.R")\n        renv::restore()\n        activate_statement <- paste0(\n          \'suppressWarnings({\',\n          \'old <- setwd("\', getwd(), \'"); \',\n          \'source("renv/activate.R"); \',\n          \'setwd(old); \',\n          \'renv::load("\', getwd(), \'");})\'\n        )\n        writeLines(activate_statement, \'activate.R\')\n        is_package <- tryCatch(\n          {\n              path_desc <- file.path(prefix_dir, \'DESCRIPTION\')\n              suppressWarnings(desc <- read.dcf(path_desc))\n              "Package" %in% colnames(desc)\n          },\n          error = function(...) FALSE\n        )\n        if (is_package) {\n            renv::install(prefix_dir)\n        }\n        \n    ')
return code: 1
stdout: (none)
stderr:
    # Bootstrapping renv 0.12.5 --------------------------------------------------
    * Downloading renv 0.12.5 from CRAN archive ... OK
    * Installing renv 0.12.5 ... Done!
    * Successfully installed and loaded renv 0.12.5.
    Error in aliased_path(path) : could not find function "aliased_path"
    Calls: source ... eval -> <Anonymous> -> renv_load_switch -> warningf
    Traceback (most recent calls last):
    20: source("renv/activate.R")
    19: withVisible(eval(ei, envir))
    18: eval(ei, envir)
    17: eval(ei, envir)
    16: local(...)
    15: eval.parent(substitute(eval(quote(expr), envir)))
    14: eval(expr, p)
    13: eval(expr, p)
    12: eval(quote(...), new.env())
    11: eval(quote(...), new.env())
    10: renv::load()
     9: renv_load_switch(project)
     8: warningf(fmt, renv_path_pretty(project))
     7: warning(sprintf(fmt, ...), call. = call., immediate. = immediate.)
     6: sprintf(fmt, ...)
     5: base::sprintf(fmt, ...)
     4: renv_path_pretty(project)
     3: shQuote(aliased_path(path), type = "cmd")
     2: gsub("(\\\\*)\"", "\\1\\1\\\\\"", string)
     1: is.factor(x)
    Execution halted
```

I hope the {renv} maintainers can ensure compatibility with older versions of their own package better. Otherwise, we might periodically update [`pre_commit/resources/empty_template_activate.R`](https://github.com/pre-commit/pre-commit/blob/main/pre_commit/resources/empty_template_activate.R). I filed an issue with {renv}, (https://github.com/rstudio/renv/issues/1358) this issue is primary for cross-reference.

### pre-commit --version

pre-commit 3.0.2

### .pre-commit-config.yaml

```yaml
repos:
-   repo: local
    hooks:
    -   id: consistent-release-tag
        name: consistent-release-tag
        entry: Rscript inst/hooks/local/consistent-release-tag.R
        language: r
        additional_dependencies:
        -    docopt
        -    fs
        -    yaml
        -    purrr 
        -    rlang 
        -    git2r
        -    desc
        -    glue
        stages: [commit, push]
    -   id: hooks-config-to-inst
        name: hooks-config-to-inst
        entry: Rscript inst/hooks/local/hooks-config-to-inst.R
        language: r
        stages: [commit, push]
        additional_dependencies:
        -    fs
        require_serial: True
    -   id: spell-check-exclude-identical
        name: spell-check-exclude-identical
        entry: Rscript inst/hooks/local/spell-check-exclude-identical.R
        language: r
        stages: [commit, push]
        additional_dependencies:
        -    magrittr
        -    purrr
        -    yaml
        -    here
        -    rlang
        require_serial: True
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .Rdata, .csv and similar.
        language: fail
        files: '\.(Rhistory|csv|RData|Rds|rds)$'
        # `exclude: <regex>` to allow committing specific files.
    -   id: spell-check-ordered-exclude
        name: Ordered regex pattern for spell-check exclusion
        description: Ensure alphabetical order in `exclude:` key of spell check.
        entry: Rscript inst/hooks/local/spell-check-ordered-exclude.R
        language: r
        files: '^(.*/|)\.?pre-commit-config.*\.yaml$'
        additional_dependencies:
        -    magrittr
        -    yaml
        -    purrr
        -    rlang
```
