### ISSUE TITLE
Pre-commit hook ignores flake8 exclude option

### ISSUE THREAD

**Issue by sevapopov2** [pre-commit/pre-commit#2912]
### search you tried in the issue tracker

flake8 exclude issue, flask migrations exclude issue

### describe your issue

I have the following issue:
I have a local flake8 hook that is running with pipenv and I added flask migrations folder to flake8 exclude option in my setup.cfg file.
Flake8 ignores this folder and reports 0 issues while pre-commit hook still tracks the folder and I cannot do the commit.
here is [setup.cfg file](https://github.com/sevapopov2/daisy-world/blob/main/setup.cfg)
And here is [my pre-commit.yaml file](https://github.com/sevapopov2/daisy-world/blob/main/.pre-commit-config.yaml)
Expected result:
pre-commit hook ignores everything what's written in flake8's exclude parameter.
Actual result:
migrations folder is still not ignored by pre-commit hook and I have to uninstall hooks for making a commit.
Here is a fragment of pre-commit.yaml file with my local flake8's hook:

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: "pipenv run flake8"
        language: system
        types: [python]
What can I do with that?
Thank you!

### pre-commit --version

pre-commit 3.3.2

### .pre-commit-config.yaml

```yaml
# pre-commit hooks for project
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: detect-private-key

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: "pipenv run flake8"
        language: system
        types: [python]
```
