### ISSUE TITLE
Yarn doesn't trigger scripts and directly returns passed on M2 Mac

### ISSUE THREAD

**Issue by jasonsrogers** [pre-commit/pre-commit#2921]
### search you tried in the issue tracker

any issue with "yarn" in it, 

### describe your issue

Hi all

I recently upgraded from an intel mac to a m2 mac. I got everything else up and running except for an issue while running  pre-commit.

I have scripts like `test`

in my terminal I can run: 

`npm run test`, `yarn test`, `yarn run test`, `npx yarn run test`

and they'll output the test results when the test fails (I left one failing so that it would always output something)

However when I run it inside my pre-commit

```
  - id: v2unittest
        name: Run unittests against v2 Frontend 2
        entry: bash -c 'cd frontend-v2 && exec yarn test'
        language: system
        files: ^frontend-v2/
```

It will straightaway output: 

```
Run unittests against v2 Frontend 2......................................Passed
```

instead of the failed test output

I've played about with various ways of calling `yarn` and I could even call non existing scripts like `yarn does:not:exist` and get the same passed result.

I've run the same pre-commit step on my old machine and it worked

So there is an issue somewhere between `pre-commit` and M2 macbooks that I've not been able to resolve. 

Please let me know if there is a known fix or if you need more information

Thanks

### pre-commit --version

pre-commit 3.3.3

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
default_language_version:
  python: python3
repos:
 - repo: local
    hooks:
      - id: v2linting
        name: Run linting against v2 Frontend
        entry: bash -c 'cd frontend-v2 && exec yarn lint:yarn'
        language: system
        files: ^frontend-v2/
      - id: v2unittest
        name: Run unittests against v2 Frontend 2
        entry: bash -c 'cd frontend-v2 && exec yarn run test'
        language: system
        files: ^frontend-v2/
```
