### ISSUE TITLE
Add option to pass additional dependencies to hooks

### ISSUE THREAD

**Issue by blarghmatey** [pre-commit/pre-commit#293]
I am currently working on implementing this framework and one of the things I am trying to run is eslint. As part of that I have a number of plugins that are in my configuration file. I think that, rather than forcing anyone who is using plugins to create a new hook definition with a corresponding package.json it might be useful to add a global option to pass a list of dependencies in the configuration file.

For instance, something lilke this:
```yaml
-   repo: https://github.com/pre-commit/mirrors-eslint
    sha: 135f285caf8e6e886b28c8e98fdff402b69c4490
    hooks:
    -   id: eslint
        language_version: '0.12.7'
        dependencies: [eslint-plugin-react, eslint-plugin-html]
```
and have those dependencies installed into the generated environment for that language.

I am going to work on implementing this in my forked repo but would like feedback on whether this is a desired feature or any implementation advice on how best to facilitate this.
