### ISSUE TITLE
Add `working-directory` property to hooks

### ISSUE THREAD

**Issue by dustindortch** [pre-commit/pre-commit#2934]
### search you tried in the issue tracker

working directory

### describe your actual problem

For a given hook, it would be nice to specify a working directory in the event that the command doesn't have a great way to pass a specific directory to it.  Or even use that working directory property as a variable for passing directly to the command:

```yaml
...
-id: my_task
  name: run my task
  description: run my task returns a configuration file from template
  entry: /bin/bash -c 'my_task ${working-directory}'
  language: script
  pass_filenames: false
  working-directory: sub_directory
---
```

Being able to set a default for each `id` in the `repo` would also be valuable.

### pre-commit --version

3.3.2
