### ISSUE TITLE
Pre-commit run --all-files does not respect exclude or provide an except option

### ISSUE THREAD

**Issue by masonsmorales** [pre-commit/pre-commit#2936]
### search you tried in the issue tracker

is:issue "pre-commit run all-files"  exclude 

### describe your issue

One of our pre-commit hooks runs `coverage run -m pytest tests/`. When we are doing development, it's occasionally useful to use `pre-commit run --all-files`. However, one of our tests takes a long time to run, so we leave that test to our CI pipeline and have that long-running test file specified in an `exclude` statement for that hook in our pre-commit configuration. However, when running `pre-commit run --all-files` it ignores `exclude` and runs this hook against the file anyway. We would like to see pre-commit either honor `exclude` in the config in this scenario, or provide an additional argument, such as `except` on `pre-commit run --all-files` where we can specify one or more files/paths to not run the pre-commit hooks against.

### pre-commit --version

3.3.2

### .pre-commit-config.yaml

```yaml
- repo: local
  hooks:
    - id: coverage
      entry: "coverage run -m pytest tests --ignore=tests/some_long_running_test.py"
      name: Run coverage
      types: [python]
      exclude: tests/some_long_running_test.py
      language: system
```
