### ISSUE TITLE
CYGWIN - docker_image hook mount point incorrect

### ISSUE THREAD

**Issue by mdeweerd** [pre-commit/pre-commit#2938]
### search you tried in the issue tracker

is:issue docker_image  cygwin  

### describe your issue

I am using pre-commit under cygwin which generally works file.

However for a docker file it is indicated that the mount point is '-v$PWD:/src'.  I think that $PWD it the path as cygwin reports it, but it is window's docke r that is run, so it should be the windows path which can be found with `(cygpath -w $pwd)`.

As the path is wrong the 'shellscript' hook shown below reports: "protected/scripts/loadLT4.sh: protected/scripts/loadLT4.sh: openBinaryFile: does not exist (No such file or directory)"

The following is how I made the corresponding hook that relies on Dockerfile work.
I mounted the working directory to "/mnt' and chose that  as the workdir (I could not append a mount point to /src because docker does not accept duplicate mount points).

```yaml
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        entry: -v.:/mnt --workdir=/mnt docker.io/koalaman/shellcheck:v0.9.0
```

### pre-commit --version

pre-commit 3.3.3

### .pre-commit-config.yaml

```yaml
---
files: (?x)^(( protected|themes)/.*\.(php|py|pl|pm|json|md|sh|yaml|cfg|txt)|[^/]*
  )$
repos:
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
```
