### ISSUE TITLE
Swiftlint hook hangs longer than running swiftlint alone

### ISSUE THREAD

**Issue by lilidotshi** [pre-commit/pre-commit#2945]
### search you tried in the issue tracker

swiftlint

### describe your issue

Pre-commit seems to be hanging 5-10 seconds longer when trying to run the swiftlint hook. For example, ran a `time pre-commit run` with the result

```
SwiftLint................................................................Passed

________________________________________________________
Executed in   12.07 secs    fish           external
   usr time    4.50 secs    0.08 millis    4.50 secs
   sys time   12.27 secs    2.90 millis   12.27 secs
```

Running `swiftlint` over all the files conversely shows a run time of about 5-6 seconds
```
Executed in    5.21 secs    fish           external
   usr time   13.55 secs    0.09 millis   13.55 secs
   sys time    2.87 secs    2.45 millis    2.87 secs
```

### pre-commit --version

3.3.3

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.51.13
    hooks:
    -    id: swiftformat
-   repo: https://github.com/realm/SwiftLint
    rev: 0.52.4
    hooks:
    -    id: swiftlint
```
