### ISSUE TITLE
Cannot pass arguments to hook via pre-commit run hook_id

### ISSUE THREAD

**Issue by Nuru** [pre-commit/pre-commit#2955]
### search you tried in the issue tracker

args

### describe your issue

I want to run a hook against all files, but the hook needs an argument. In my YAML config I have

```yaml
hooks:
  - id: terraform_docs
    args: ["--args=--lockfile=false"]
```

Based on [the documentation](https://pre-commit.com/#pre-commit-run) I though I could run

```
pre-commit run --all-files terraform_docs --args=--lockfile=false
```

but that does not work. It fails with 

```
pre-commit: error: unrecognized arguments: --args=--lockfile=false
```

I could not find a way to get this to work.

### pre-commit --version

3.3.2

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.75.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args: ["--args=--lockfile=false"]
```
