### ISSUE TITLE
Prettier and ESLint hooks fails to find modules on GitHub Actions

### ISSUE THREAD

**Issue by Jarmos-san** [pre-commit/pre-commit#2957]
### search you tried in the issue tracker

Prettier and ESLint hooks fails in CI

### describe your issue

We setup the `mirrors-prettier` and `mirrors-eslint` hooks locally and it works perfectly fine locally but fails on our GitHub Actions workflow. Screenshot of the error stack is provided below:

![image](https://github.com/pre-commit/pre-commit/assets/31373860/b7e8e188-504b-4a97-b868-fe57a1451cc8)

### pre-commit --version

pre-commit 3.3.3

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args:
          - --maxkb=1000

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1
    hooks:
      - id: prettier
        additional_dependencies:
          - "prettier@3.0.1"
          - "@trivago/prettier-plugin-sort-imports"
          - "prettier-plugin-tailwindcss"

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.46.0
    hooks:
      - id: eslint
        additional_dependencies:
          - "eslint@v8.47.0"
          - "eslint-config-next"
          - "eslint-config-prettier"
```
