### ISSUE TITLE
Support rev (or add new) field as image tag for docker and docker_image languages

### ISSUE THREAD

**Issue by lhriley** [pre-commit/pre-commit#2968]
### search you tried in the issue tracker

rev docker

### describe your actual problem

When creating / using hooks based on the `docker` or `docker_image` languages, it would be really useful to support passing the `rev` field (or a new field?) to the function that runs the hook.

This would allow the hook owner to set a floating default (such as `latest`) in the git repo, but allow users to override this value in order to pin to a specific version of the hook's container image.

This would help to mitigate compatibility issues across major version changes and reduce the overhead of maintaining hooks based on container images in general.

To maintain backward compatibility, the `entry` string interpolation would only happen in the case that:

1. the `tag` field was not `None`, OR
2. the `entry` field contained special template characters

Examples of proposed hook ([source](https://github.com/norwoodj/helm-docs)):

new field:
```yaml
- id: helm-docs-container
  args: []
  description: Uses the container image of 'helm-docs' to create documentation from the Helm chart's 'values.yaml' file, and inserts the result into a corresponding 'README.md' file.
  entry: jnorwood/helm-docs
  tag: v1.11.0
  files: (README\.md\.gotmpl|(Chart|requirements|values)\.yaml)$
  language: docker_image
  name: Helm Docs Container
  require_serial: true
```

```yaml
- id: helm-docs-container
  args: []
  description: Uses the container image of 'helm-docs' to create documentation from the Helm chart's 'values.yaml' file, and inserts the result into a corresponding 'README.md' file.
  entry: jnorwood/helm-docs
  tag: latest
  files: (README\.md\.gotmpl|(Chart|requirements|values)\.yaml)$
  language: docker_image
  name: Helm Docs Container
  require_serial: true
```

variable / template:
```yaml
- id: helm-docs-container
  args: []
  description: Uses the container image of 'helm-docs' to create documentation from the Helm chart's 'values.yaml' file, and inserts the result into a corresponding 'README.md' file.
  entry: jnorwood/helm-docs:{{ rev | default "v1.11.0" }}
  files: (README\.md\.gotmpl|(Chart|requirements|values)\.yaml)$
  language: docker_image
  name: Helm Docs Container
  require_serial: true
```

```yaml
- id: helm-docs-container
  args: []
  description: Uses the container image of 'helm-docs' to create documentation from the Helm chart's 'values.yaml' file, and inserts the result into a corresponding 'README.md' file.
  entry: jnorwood/helm-docs:{{ rev | default "latest" }}
  files: (README\.md\.gotmpl|(Chart|requirements|values)\.yaml)$
  language: docker_image
  name: Helm Docs Container
  require_serial: true
```

### pre-commit --version

pre-commit 3.3.3
