### ISSUE TITLE
Config file isn't passing for flake8 hook

### ISSUE THREAD

**Issue by sevapopov2** [pre-commit/pre-commit#2969]
### search you tried in the issue tracker

passing config for flake8 hook

### describe your issue

I am the new user of flake8 hook so there is a chance that I missunderstood something.
I tried to use flake8 with my settings from setup.cfg file but it seems like they didn't work.
When I check for issues with flake8 in my Visual studio code there are no problems, however when I run pre-commit run command there is the following error for flake8 hook:
$ pre-commit                                                                                                                                                
trim trailing whitespace.................................................Passed                                                                             
fix end of files.........................................................Passed                                                                             
check yaml...............................................................Passed                                                                             
check for added large files..............................................Passed                                                                             
fix utf-8 byte order marker..............................................Passed                                                                             
detect private key.......................................................Passed                                                                             
fix double quoted strings................................................Passed                                                                             
flake8...................................................................Failed                                                                             
- hook id: flake8                                                                                                                                           
- exit code: 1                                                                                                                                              
                                                                                                                                                            
main.py:1:1: D300 Use """triple double quotes"""                                                                                                            
'''Main file to launch the game.'''                                                                                                                         
^                                                                                                                                                           
src/consts.py:1:1: D300 Use """triple double quotes"""                                                                                                      
'''Constants used in the game project.'''                                                                                                                   
^                                                                                                                                                           
2     D300 Use """triple double quotes"""                                                                                                                   
2                                                                                                                                                           
                                                                                                                                                            
mypy.....................................................................Passed                                                                             
                                                                                                                                                            
The thing is that I have flake8-quotes plugin attached and there quote is set to single ', however I think pre-commit doesn't except that.
How can I fix it?
Should I attach any parameter to pre-commit hook configuration?


### pre-commit --version

3.3.3

### .pre-commit-config.yaml

```yaml
# pre-commit hooks for project
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: detect-private-key
      - id: double-quote-string-fixer

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          [
            flake8-builtins,
            flake8-docstrings,
            flake8-import-order,
            flake8-variables-names,
            flake8-quotes,
          ]
        # exclude: migrations

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
```


### ~/.cache/pre-commit/pre-commit.log (if present)

_No response_
