### ISSUE TITLE
GitLab CI PermissionError: [Errno 13] Permission denied: '.git/hooks/pre-commit' at install time

### ISSUE THREAD

**Issue by HealthyPear** [pre-commit/pre-commit#2977]
### search you tried in the issue tracker

Permission denied

### describe your issue

(Not sure if this is a bug, I just used the template for it...)

I am working on GitLab with a _micromamba_ docker image and I have been doing (successfully) the following until now

```
pre-commit:
  stage: pre-commit
  before_script:
    - echo "Running pre-commit..."
  script:
    - micromamba install -c conda-forge git pre-commit
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - pre-commit install
    - git fetch origin
    - pre-commit run --from-ref "origin/master" --to-ref "$CI_COMMIT_SHA" --show-diff-on-failure
  after_script:
    - |
      if [ "$CI_JOB_STATUS" = "failed" ]
      then
          echo "please install the pre-commit hooks before pushing!" 
      elif [ "$CI_JOB_STATUS" = "success" ]
      then
          echo "All good!"
      fi
```

yesterday I started seeing this job failing with the error message

`An unexpected error has occurred: PermissionError: [Errno 13] Permission denied: '.git/hooks/pre-commit'`

the log file was not very useful, so I started debugging the problem stragin from the most obvious solution

- try to change permission with chmod 777

this failed as apparently I can't do this from a docker container)

- try to set `PRE_COMMIT_HOME` to `/home/mambauser/.cache/pre-commit`

I added 

```
variables:
    PRE_COMMIT_HOME: /home/mambauser/.cache/pre-commit
````

before the `script` section
but then it is not clear from the documentation how pre-commit loads this, so I tried to export the variable as `export $PRE_COMMIT_HOME` before doing `pre-commit install`, but then I get `/usr/bin/bash: line 141: export: `/home/mambauser/.cache/pre-commit': not a valid identifier` which I have never seen before and apparently it means that I am using some kind of invalid character (no clue which one though)

Is there any standard (updated) recipe for using pre-commit with GitLab CI + docker executor?

Also, has anything changed in later releases that might have changed this behaviour (I should have probably pinned the version).

### pre-commit --version

3.3.3

### .pre-commit-config.yaml

```yaml
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml # checks yaml files for parseable syntax
      - id: check-toml # checks toml files for parseable syntax
      - id: check-json # checks json files for parseable syntax
      - id: check-merge-conflict # checks for files that contain merge conflict strings
      - id: check-added-large-files # prevents giant files from being committed
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems
      - id: check-symlinks # checks for symlinks which do not point to anything
      - id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.270
    hooks:
      - id: ruff
  - repo: https://github.com/rstcheck/rstcheck
    rev: v6.1.2
    hooks:
      - id: rstcheck
        additional_dependencies: [sphinx]
        args: ["--config=.rstcheck.cfg"]
```

### version information
```
pre-commit version: 3.3.3
git --version: git version 2.42.0
sys.version:
    3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
sys.executable: /opt/conda/bin/python3.11
os.name: posix
sys.platform: linux
```
### error information
```
An unexpected error has occurred: PermissionError: [Errno 13] Permission denied: '.git/hooks/pre-commit'
```
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/opt/conda/lib/python3.11/site-packages/pre_commit/main.py", line 396, in main
    return install(
           ^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pre_commit/commands/install_uninstall.py", line 132, in install
    _install_hook_script(
  File "/opt/conda/lib/python3.11/site-packages/pre_commit/commands/install_uninstall.py", line 92, in _install_hook_script
    with open(hook_path, 'w') as hook_file:
         ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '.git/hooks/pre-commit'
```
