### ISSUE TITLE
Support config files not named .pre-commit-hooks.yaml

### ISSUE THREAD

**Issue by rbyrne5JLR** [pre-commit/pre-commit#2983]
### search you tried in the issue tracker

custom config file

### describe your actual problem

I would like to specify a custom config file when in include a repo like the below

```

repos:
  - repo: https://github.com/my_pre_commit_configs
    rev: 1.0.19
    config: "my_custom_config.yml"
    hooks:
      - id: check-added-large-files
      ....
```

The reason we want this is that we have created multiple base pre-commit-config.yml files and want to be able to include the appropriate one for the parent project. Currently we add the base repo as a submodule and symlink to the appropriate config file but this doesn't allow per project modifications. So we would like to be able to include the base config and be able to modify the top level config with the hooks and excludes on a per project bases. Something like the feature above would enable this

### pre-commit --version

pre-commit-2.20.0
