### ISSUE TITLE
coursier: additional_dependencies with non-default channel

### ISSUE THREAD

**Issue by junghoon-vans** [pre-commit/pre-commit#2986]
### search you tried in the issue tracker

https://github.com/pre-commit/pre-commit/pull/2702

#### Description

Currently, coursier's `additional_dependencies` only supports the default [channel](https://get-coursier.io/docs/cli-install#channels).
This means it can't pull dependencies from repositories like `central`.

##### AS-IS

```yaml
repos:
- repo: https://github.com/junghoon-vans/pre-coursier
  rev: v0.2.0
  hooks:
  - id: scalafmt
    args: ["--config-str", "version = 2.4.2, runner.dialect = scala3"]
    additional_dependencies: ["scalafmt:2.4.2"] # This is available

  - id: checkstyle
    args: [".", "-c", "./checkstyle.xml"]
    additional_dependencies: ["checkstyle:10.8.0"] # This is not avaliable
```

#### Solution

How about changing `central` to the default repository for more dependencies?
In fact, coursier's default repository also fetches files from central.

##### TO-BE

```yaml
repos:
- repo: https://github.com/junghoon-vans/pre-coursier
  rev: v0.2.0
  hooks:
  - id: scalafmt
    args: ["--config-str", "version = 2.4.2, runner.dialect = scala3"]
    additional_dependencies: ["org.scalameta::scalafmt-cli:2.4.2"]

  - id: checkstyle
    args: [".", "-c", "./checkstyle.xml"]
    additional_dependencies: ["com.puppycrawl.tools:checkstyle:10.8.0"]
```

> But the library must be explicitly marked in additional_dependencies.

### pre-commit --version

pre-commit:3.4.0

**Comment by asottile** [comment]
you can already put `--channel, ...` in additional_dependencies to accomplish what you want

**Comment by junghoon-vans** [comment]
@asottile Thank you for your advice.
Am I correct that you are referring to running something like this?

```yaml
repos:
- repo: https://github.com/junghoon-vans/pre-coursier
  rev: v0.2.0
  hooks:
      - id: checkstyle
        args: [".", "-c", "./sun_checks.xml"]
        additional_dependencies: ["--channel", "central", "com.puppycrawl.tools:checkstyle:10.8.0"]
```

However, this will result in an error when executed.

```
❯ pre-commit run --all-files -v
[INFO] Installing environment for https://github.com/junghoon-vans/pre-coursier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/opt/homebrew/bin/cs', 'install', '--dir', '/Users/jeonghun/.cache/pre-commit/repodauna3u9/coursier-default', '--channel', 'central', 'com.puppycrawl.tools:checkstyle:10.8.0')
return code: 1
stdout: (none)
stderr:
    Downloading https://repo1.maven.org/maven2/io/get-coursier/apps/maven-metadata.xml
    Downloaded https://repo1.maven.org/maven2/io/get-coursier/apps/maven-metadata.xml
    Downloading https://repo1.maven.org/maven2/io/get-coursier/apps/1.0.40/apps-1.0.40.pom
    Downloaded https://repo1.maven.org/maven2/io/get-coursier/apps/1.0.40/apps-1.0.40.pom
    Downloading https://repo1.maven.org/maven2/io/get-coursier/apps/1.0.40/apps-1.0.40.jar
    Downloaded https://repo1.maven.org/maven2/io/get-coursier/apps/1.0.40/apps-1.0.40.jar
    Cannot find app com.puppycrawl.tools in channels /Users/jeonghun/.cache/pre-commit/repodauna3u9/central, io.get-coursier:apps
Check the log at /Users/jeonghun/.cache/pre-commit/pre-commit.log
```

I was wondering if I should pass `--default-channel=false`, so I put it in, but I still get the error.

```
❯ pre-commit run --all-files -v
[INFO] Initializing environment for https://github.com/junghoon-vans/pre-coursier:--default-channels=false --channel central com.puppycrawl.tools:checkstyle:10.8.0.
[INFO] Installing environment for https://github.com/junghoon-vans/pre-coursier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/opt/homebrew/bin/cs', 'fetch', '--default-channels=false --channel central com.puppycrawl.tools:checkstyle:10.8.0')
return code: 1
stdout: (none)
stderr:
    Argument --default-channels: Unrecognized flag value: false --channel central com.puppycrawl.tools:checkstyle:10.8.0
Check the log at /Users/jeonghun/.cache/pre-commit/pre-commit.log
```

**Comment by asottile** [comment]
yeah I'm not super familiar with coursier myself -- if you can show me commands to install checkstyle using coursier outside of pre-commit I can tell you what the pre-commit config should look like

**Comment by junghoon-vans** [comment]
@asottile sure this is two way to install checkstyle using coursier.

### General

```bash
cs install com.puppycrawl.tools:checkstyle:latest.release
```

Since checkstyle is an application that is not in coursier's default channel, it must be explicitly specified.

### Application descriptors

```json
{
    "mainClass": "com.puppycrawl.tools.checkstyle.Main",
    "repositories": [
      "central"
    ],
    "dependencies": [
      "com.puppycrawl.tools:checkstyle:latest.release"
    ]
}
```

Once you've registered your `checkstyle.json` in your `.pre-commit-channel` as above, you can use it as shown below.

```bash
cs install --default-channels=false --channel=.pre-commit-channel checkstyle:latest.release
```

Since it's registered to a custom channel, you don't need to explicitly show the library.

**Comment by asottile** [comment]
sorry took me a while to get back to this -- I think given that it needs additional metadata since it's not traditionally packaged via coursier then it's not possible with `additional_dependencies` unfortunately

**Comment by junghoon-vans** [comment]
@asottile 
So why not specify the `repositories` specified inside the [application descriptors](https://get-coursier.io/docs/cli-appdescriptors) as the repositories for `additional_dependencies`?

Currently, pre-commit seems to use the channel in the application descriptors with disable default channel.

https://github.com/pre-commit/pre-commit/blob/5f4b82899929ffdaf94f81ed01dec4e9a1d98636/pre_commit/languages/coursier.py#L51C17-L51C25

so it makes more sense for additional Dependencies to **also use** channel in the application descriptors.

### Example

**.pre-commit-channel/checkstyle.json**
```json
{
    "mainClass": "com.puppycrawl.tools.checkstyle.Main",
    "repositories": [
      "central",
      "https://some.custom.maven/repository"
    ],
    "dependencies": [
      "com.puppycrawl.tools:checkstyle:latest.release"
    ]
}
```

Define two repositories.

**.pre-commit-config.yaml**
```yaml
repos:
- repo: https://github.com/junghoon-vans/pre-coursier
  rev: v0.2.0
  hooks:
      - id: checkstyle
        args: [".", "-c", "./sun_checks.xml"]
        additional_dependencies: ["com.puppycrawl.tools:checkstyle:10.8.0"]
```

Additional dependencies are pulled from the repository that defined in `.pre-commit-channel/checkstyle.json`
