### ISSUE TITLE
prepare-commit-msg script doesnt receive all args

### ISSUE THREAD

**Issue by danilobuerger** [pre-commit/pre-commit#2987]
### search you tried in the issue tracker

prepare-commit-msg

### describe your issue

I am using a custom `prepare-commit-msg` bash script. 
On `git commit -m "..."` I would except the args to be:
```
.git/COMMIT_EDITMSG message
```
However, I am only receiving
```
.git/COMMIT_EDITMSG 
```
When checking `.git/hooks/prepare-commit-msg` and outputing `${ARGS[@]}` I see all the args:
```
hook-impl --config=.pre-commit-config.yaml --hook-type=prepare-commit-msg --hook-dir /.../.git/hooks -- .git/COMMIT_EDITMSG message
```
But only `.git/COMMIT_EDITMSG` is passed to my script.

### pre-commit --version

3.3.3

### .pre-commit-config.yaml

```yaml
default_install_hook_types:
  - pre-commit
  - prepare-commit-msg
repos:
  - repo: local
    hooks:
      - id: test
        name: test
        language: script
        entry: .githooks/prepare-commit-msg
        stages:
          - prepare-commit-msg
```
