### ISSUE TITLE
autoupdate pulling in alpha versions when not requested

### ISSUE THREAD

**Issue by tartansandal** [pre-commit/pre-commit#2988]
### search you tried in the issue tracker

autoupdate

### describe your issue

When I run 

```
pre-commit autoupdate
```

I get 

```
...
[https://github.com/pycqa/pylint] updating v2.17.4 -> v3.0.0a7
...
```

When I look at GitHub for the latest release for pylint, it's `v2.17.5`.

I don't have `bleading-edge` set on either the command line or the configuration

### pre-commit --version

pre-commit 3.3.2

### .pre-commit-config.yaml

```yaml
default_stages: [commit]

repos:
    - repo: meta
      hooks:
          - id: check-hooks-apply

          - id: check-useless-excludes

    - repo: local
      hooks:
          - id: check-submodules
            name: Check submodules
            language: script
            entry: ./.git-hooks/check_submodules.py

          - id: check-noqa
            name: Check noqa
            language: pygrep
            description: Enforce that `noqa` is not used.
            types: [python]
            entry: '(?i)# noqa'

          - id: check-duplicated-commands
            name: Check for duplicated console commands
            language: script
            entry: ./.git-hooks/check_console_commands_are_unique.py
            files: "todoist/apps/admin_console/static/js/console.coffee"

          - id: check-blacks-versions-matches-blacken-docs
            name: Check Black's versions matches blacken-doc's
            language: python
            entry: ./.git-hooks/check_blacks_versions_matches_blacken_docs.py
            additional_dependencies: [pyaml]
            files: ".pre-commit-config.yaml"

          - id: check-no-dead-code-via-vulture
            name: Vulture check for dead code (run `vulture | grep function`)
            language: python
            entry: ./.git-hooks/vulture.sh
            additional_dependencies: [vulture]
            stages: [push]

          # This is an almost-copy of https://github.com/pre-commit/mirrors-mypy/blob/main/.pre-commit-hooks.yaml
          - id: mypy
            name: mypy
            entry: poetry run mypy
            language: system
            'types_or': [python, pyi]
            args: [
              "--ignore-missing-imports",
              "--scripts-are-modules",
            ]
            require_serial: true

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      # Ruff version.
      rev: 'v0.0.287'
      hooks:
        - id: ruff

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: 'v0.0.287'
      hooks:
        - id: ruff
          alias: ruff-fix
          stages: [ manual ]
          args:
            - --fix

    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.10.0
      hooks:
        - id: python-check-blanket-type-ignore

        - id: python-check-mock-methods

        - id: python-no-eval

        - id: python-no-log-warn

        - id: python-use-type-annotations

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: mixed-line-ending
            exclude: "\
              fixtures/test_import_export/utf16.csv|\
              fixtures/test_import_export/test_user_p1.csv|\
              fixtures/test_import_export/test_user_p2.csv"

          - id: check-merge-conflict

          - id: check-case-conflict

          - id: debug-statements

          - id: check-ast

          - id: check-json

          - id: check-symlinks

          - id: destroyed-symlinks

          - id: check-executables-have-shebangs

          - id: check-shebang-scripts-are-executable

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.3 # Should match the additional_dependencies below and package-lock.json
      hooks:
          - id: prettier
            additional_dependencies:
                # W/A: https://github.com/prettier/pre-commit/issues/16#issuecomment-713501862
                - prettier@3.0.1  # Should match rev and package-lock.json
                - '@doist/prettier-config@4.0.0' # Should match package-lock.json

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.10.1
      hooks:
        - id: pyupgrade
          args:
              - --py311-plus
              # We need this while ist_libs uses `mock` in production code. :/
              # https://github.com/Doist/backend-issues/issues/2399
              - --keep-mock
              # Required by tools like Pydantic that use type information at runtime.
              # https://github.com/asottile/pyupgrade/issues/622#issuecomment-1088766572
              - --keep-runtime-typing

    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args:
                # No clue why we have to be explicit about it. This is supposed
                # to be the default.
                - --settings-file
                - .isort.cfg

    - repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
          - id: black

    - repo: https://github.com/asottile/blacken-docs
      rev: 1.16.0
      hooks:
          - id: blacken-docs
            additional_dependencies: [black==23.7.0]

    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.3.0
      hooks:
          - id: pydocstyle
            additional_dependencies:
              - tomli # https://github.com/PyCQA/pydocstyle/issues/603

    - repo: https://github.com/pycqa/pylint
      rev: v3.0.0a7
      hooks:
          - id: pylint
            # Too slow to run on every commit.
            # This is run on .github/workflows/pre-commit.yml
            stages: [manual]
            args:
                # pre-commit creates a virtualenv per tool, and it doesn't
                # install the verified repo's dependencies. So, we don't check.
                - --disable=import-error
                # These need to get taken out, one by one
                - --disable=abstract-method
                - --disable=broad-except
                - --disable=cyclic-import
                - --disable=duplicate-code
                - --disable=fixme
                - --disable=global-statement
                - --disable=import-outside-toplevel
                - --disable=invalid-name
                - --disable=missing-class-docstring
                - --disable=missing-function-docstring
                - --disable=no-member
                - --disable=protected-access
                - --disable=redefined-outer-name
                - --disable=unsubscriptable-object
                - --disable=unsupported-membership-test
                - --disable=unused-argument
                - --disable=unused-import
                - --allowed-redefined-builtins=id,type,format,input,filter
            additional_dependencies:
                - click
                - requests

    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.9.0.5
      hooks:
          - id: shellcheck

    - repo: https://github.com/AleksaC/hadolint-py
      rev: v2.12.0.2
      hooks:
          - id: hadolint
            args: [--ignore, DL3008]
```
