### ISSUE TITLE
Run on all the stages but `manual`

### ISSUE THREAD

**Issue by 0x2b3bfa0** [pre-commit/pre-commit#2990]
### search you tried in the issue tracker

negate stage, exclude stage

### describe your actual problem

Could we have some kind of `exclude_stages`[^1] setting to e.g. run a hook on all the default/specified stages but the `manual` one?

I believe this feature can be useful to trigger the `manual` stage when running on GitHub Actions and excluding some checks that only make sense locally.

#### Desired syntax
```yaml
repos:
- repo: https://github.com/python-poetry/poetry
  rev: 1.6.1
  hooks:
  - id: poetry-check
  - id: poetry-lock # disable on CI; this hook always changes something
    exclude_stages: [manual]
```

#### Functional workaround
```yaml
repos:
- repo: https://github.com/python-poetry/poetry
  rev: 1.6.1
  hooks:
  - id: poetry-check
    args: [--directory=backend]
  - id: poetry-lock
    args: [--directory=backend]
    stages: # all but manual
    - commit-msg
    - post-checkout
    - post-commit
    - post-merge
    - post-rewrite
    - pre-commit
    - pre-merge-commit
    - pre-push
    - pre-rebase
    - prepare-commit-msg
```

### Related
* https://github.com/pre-commit/pre-commit/issues/1049#issuecomment-496753920 ✅ 
* https://github.com/pre-commit/pre-commit/issues/2985 ❓ 

### pre-commit --version

pre-commit 3.3.3

[^1]: Similar to [`exclude_types`](https://pre-commit.com/#config-exclude_types)
