### ISSUE TITLE
prettier hook additional dependencies do not work

### ISSUE THREAD

**Issue by shankarino** [pre-commit/pre-commit#2997]
### search you tried in the issue tracker

prettier

### describe your issue

I am posting here since [prettier-mirror](https://github.com/pre-commit/mirrors-prettier) does not have issues.

Prettier is failing when using additional dependencies. For instance, when using the example in the doc https://github.com/pre-commit/mirrors-prettier/blob/fc260393cc4ec09f8fc0a5ba4437f481c8b55dc1/README.md?plain=1#L27-L35 pre-commit fails with

```text
[error] Cannot find package '@prettier/plugin-xml@0.12.0' imported from /Users/shankarino/my-repo/noop.js
```

### pre-commit --version

pre-commit 3.4.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        args:
          - --plugin=@prettier/plugin-xml@0.12.0
        additional_dependencies:
          - prettier
          - '@prettier/plugin-xml@0.12.0'
```
