### ISSUE TITLE
CI doesn't run weekly autoupdate

### ISSUE THREAD

**Issue by chemelli74** [pre-commit/pre-commit#3003]
### search you tried in the issue tracker

CI, autoupdate

### describe your issue

I added the CI config to `.pre-commit-config.yaml` as descried in the documentation but the task doesn't run.

Here the config details: https://github.com/chemelli74/aiovodafone/blob/main/.pre-commit-config.yaml#L6-L9

Simone

### pre-commit --version

v3.4.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "CHANGELOG.md|.copier-answers.yml"
default_stages: [commit]

ci:
  autofix_commit_msg: "chore(pre-commit.ci): auto fixes"
  autoupdate_commit_msg: "chore(pre-commit.ci): pre-commit autoupdate"
  autoupdate_schedule: weekly

repos:
[...]
```
