### ISSUE TITLE
[docs] ensure the recommendations put pyupgrade before black

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pre-commit/pre-commit#3004]
### search you tried in the issue tracker

black pyupgrade

### describe your issue

in tooling calling pre-commit  to  clean up code from a code-generator after its rendered into files
we ran into a curious issue

both black and pyupgrade are used there

the tool invokes pre-commit twice to ensure tis clean

depending on the order of black and pyupgrade the second call to pre-commit could fail in case pyupgraded did something right that would trigger a need to use black again

as such it would be very helpful if the docs (that show examples of hook order that can trigger the bad interaction between the 2 tools

in case this is viewed positive i'm happy to create a mr with the changes

### pre-commit --version

any

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    - id: black
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    - id: pyupgrade
```
