### ISSUE TITLE
failenames passed to `entry` drop the first one

### ISSUE THREAD

**Issue by nikaro** [pre-commit/pre-commit#3008]
### search you tried in the issue tracker

bash drop filename

### describe your issue

When i try to loop on passed filenames it miss some files, the first one of each batch (when not using `require_serial: true`).

This is somnething already highligthed by this comment: https://github.com/pre-commit/pre-commit/issues/1110#issuecomment-747812172 but i still see at different places that the recommended workaround is to use the bash variable `$@`.

### pre-commit --version

pre-commit 3.4.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      # this one show the issue
      - id: echo-at
        name: echo $@
        language: system
        files: ^(.*/)?pyproject\.toml$
        entry: bash -xc 'echo "$@"'
        require_serial: true
      # this is an actual working workaround
      - id: echo-merge
        name: echo merge
        language: system
        files: ^(.*/)?pyproject\.toml$
        entry: bash -xc 'MERGE=("$0" "$@"); echo "${MERGE[@]}"'
        require_serial: true
      - id: for-merge
        name: for merge
        language: system
        files: ^(.*/)?pyproject\.toml$
        entry: bash -xc 'MERGE=("$0" "$@"); for f in "${MERGE[@]}"; do echo "$f"; done'
        require_serial: true
```

### Exemple output

```
echo $@..................................................................Passed
- hook id: echo-at
- duration: 0.03s

+ echo d/e/pyproject.toml f/pyproject.toml g/h/i/j/k/pyproject.toml l/m/pyproject.toml pyproject.toml
d/e/pyproject.toml f/pyproject.toml g/h/i/j/k/pyproject.toml l/m/pyproject.toml pyproject.toml

echo merge...............................................................Passed
- hook id: echo-merge
- duration: 0.03s

+ MERGE=("$0" "$@")
+ echo a/b/c/pyproject.toml d/e/pyproject.toml f/pyproject.toml g/h/i/j/k/pyproject.toml l/m/pyproject.toml pyproject.toml
a/b/c/pyproject.toml d/e/pyproject.toml f/pyproject.toml g/h/i/j/k/pyproject.toml l/m/pyproject.toml pyproject.toml

for merge................................................................Passed
- hook id: for-merge
- duration: 0.03s

+ MERGE=("$0" "$@")
+ for f in '"${MERGE[@]}"'
+ echo a/b/c/pyproject.toml
a/b/c/pyproject.toml
+ for f in '"${MERGE[@]}"'
+ echo d/e/pyproject.toml
d/e/pyproject.toml
+ for f in '"${MERGE[@]}"'
+ echo f/pyproject.toml
f/pyproject.toml
+ for f in '"${MERGE[@]}"'
+ echo g/h/i/j/k/pyproject.toml
g/h/i/j/k/pyproject.toml
+ for f in '"${MERGE[@]}"'
+ echo l/m/pyproject.toml
l/m/pyproject.toml
+ for f in '"${MERGE[@]}"'
+ echo pyproject.toml
pyproject.toml
```
