### ISSUE TITLE
pre-commit seems to install outdated codespell version

### ISSUE THREAD

**Issue by ernestum** [pre-commit/pre-commit#3009]
### search you tried in the issue tracker

codespell

### describe your issue

As part of my pipeline, I run `pre-commit run --all codespell`, which I have configured using:

```yaml
  repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
  - id: codespell
    args: ["--skip=*.pyc,tests/testdata/*,*.ipynb,*.csv","--ignore-words-list=reacher,ith,iff"]
```

Suddenly I run into:

```python
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/m/.cache/pre-commit/repot4h_wvoy/py_env-python3/bin/codespell", line 5, in <module>
    from codespell_lib import _script_main
  File "/home/m/.cache/pre-commit/repot4h_wvoy/py_env-python3/lib/python3.8/site-packages/codespell_lib/__init__.py", line 1, in <module>
    from ._codespell import _script_main, main
  File "/home/m/.cache/pre-commit/repot4h_wvoy/py_env-python3/lib/python3.8/site-packages/codespell_lib/_codespell.py", line 29, in <module>
    from ._version import __version__ as VERSION  # noqa: N812
  File "/home/m/.cache/pre-commit/repot4h_wvoy/py_env-python3/lib/python3.8/site-packages/codespell_lib/_version.py", line 4
    __version__ : str = version : str = '0.1.dev1+g355e50e'
                                ^
SyntaxError: invalid syntax
```

Looking into the version file of codespell I see:

```python
# file generated by setuptools_scm
# don't change, don't track in version control
from __future__ import annotations
__version__ : str = version : str = '0.1.dev1+g355e50e'
__version_tuple__ : 'tuple[int | str, ...]' = \
  version_tuple : 'tuple[int | str, ...]' = (0, 1, 'dev1', 'g355e50e')
```

So pre-commit seems to have installed a weird development version of codespell instead of version `2.2.5`.

I could replicate this on my local machine where I tried to
1. clean the pip cache (`pip cache purge`)
2. run `pre-commit clean`

For some reason it keeps installing the old development release.

How would I further investigate the issue? The `--verbose` option did not show any more helpful installation instructions.

### pre-commit --version

pre-commit 3.4.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
# Linting
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude_types: [jupyter]
  - id: check-toml
  - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black
  - id: black-jupyter
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
# Python static analysis
- repo: https://github.com/pycqa/flake8
  rev: '6.1.0'
  hooks:
  - id: flake8
    additional_dependencies:
      - darglint~=1.8.1
      - flake8-blind-except==0.2.1
      - flake8-builtins~=1.5.3
      - flake8-commas~=2.1.0
      - flake8-debugger~=4.1.2
      - flake8-docstrings~=1.6.0
# Shell static analysis
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.9.0
  hooks:
  - id: shellcheck
  # precommit invokes shellcheck once per file. shellcheck complains if file
  # includes another file not given on the command line. Ignore this, since
  # they'll just get checked in a separate shellcheck invocation.
    args: ["-e", "SC1091"]
# Misc
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
  - id: codespell
    args: ["--skip=*.pyc,tests/testdata/*,*.ipynb,*.csv","--ignore-words-list=reacher,ith,iff"]
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.18
  hooks:
  - id: circleci-config-validate
# Hooks that run in local environment (not isolated venv) as they need
# same dependencies as our package.
- repo: local
  hooks:
  - id: check-notebooks
    name: check-notebooks
    entry: ./ci/clean_notebooks.py --check ./docs/tutorials/
    language: script
    types: [jupyter]
    pass_filenames: false
  # Run mypy directly from local repo rather than using mirror-mypy
  # so that it uses installed dependencies. Adapted from:
  # https://jaredkhan.com/blog/mypy-pre-commit
  - id: mypy
    name: mypy
    language: system
    types: [python]
    entry: mypy --follow-imports=silent --show-error-codes
    # use require_serial so that script
    # is only called once per commit
    require_serial: true
    # Print the number of files as a sanity-check
    verbose: true
  - id: pytype
    name: pytype
    language: system
    types: [python]
    entry: "bash -c 'pytype -j ${NUM_CPUS:-auto}'"
    require_serial: true
    verbose: true
  - id: docs
    name: docs
    language: system
    types_or: [python, rst]
    entry: bash -c "cd docs/ && make clean && SKIP_DOCTEST=True NB_EXECUTION_MODE=off make html"
    require_serial: true
    verbose: true
    pass_filenames: false
```
