### ISSUE TITLE
difference between running mypy directly vs with pre-commit

### ISSUE THREAD

**Issue by ZeN220** [pre-commit/pre-commit#3017]
### search you tried in the issue tracker

https://github.com/pre-commit/pre-commit/issues/1580

### describe your issue

I read the above issue and as I understand it, my problem is described in the second paragraph of this comment:
https://github.com/pre-commit/pre-commit/issues/1580#issuecomment-679413936
but nevertheless, I have no idea what I need to do to make mypy work the same way both directly and with pre-commit

### pre-commit --version

3.3.3

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.5.1"
    hooks:
      - id: mypy
        additional_dependencies: [
          types_toml==0.10.8.7,
          types_redis==4.6.0.7
        ]
```
