### ISSUE TITLE
Install the current project for a hook

### ISSUE THREAD

**Issue by WhyNotHugo** [pre-commit/pre-commit#3019]
### search you tried in the issue tracker

current project install extras

### describe your issue

I'm trying to write a hook that should install the current project with some extras:

```yaml
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: python
        entry: mypy
        types_or: [python, pyi]
        additional_dependencies:
          - .[dev]
```

My `pyproject.toml` defines these extras:

```toml
dev = [
  "mypy",
  "dj_database_url",
  "django-stubs[compatible-mypy]",
  "types-freezegun",
  "types-pyOpenSSL",
  "types-pytz",
  "types-requests",
  "types-backports",
]
```

I _could_ duplicate all these dependencies into `additional_dependencies`, but these always end up diverging over time and are a source for extra maintenance work.

However, this doesn't work; looks like the project with its extras are not being installed:

```console
> pre-commit run mypy --all
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

Executable `mypy` not found
```

Am I perhaps using the wrong syntax? Is this actually supported?

### pre-commit --version

pre-commit 3.4.0

### .pre-commit-config.yaml

See above for changes relevant to this issue; I don't think there's anything relevant below.

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-added-large-files
      - id: debug-statements
  - repo: https://github.com/psf/black
    rev: "23.7.0"
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: mypy
        types_or: [python, pyi]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.282'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
ci:
  skip:
    - mypy
```

### ~/.cache/pre-commit/pre-commit.log (if present)

n/a
