### ISSUE TITLE
Potential bug: forbid-binary with git-lfs

### ISSUE THREAD

**Issue by mihaigalos** [pre-commit/pre-commit#3028]
### search you tried in the issue tracker

lfs

### describe your issue

`bash`:
```bash
git lfs track "*.pdf"
git add foo.pdf && git commit -m "chore: Test LFS"
```
This now fails since the files are binary [here](https://github.com/pre-commit/pre-commit/blob/0d8b2451ca61d93c3d26746da83b63c7821c73f4/pre_commit/commands/run.py#L79), even though they're stored as pointers:

```
Forbid binaries..........................................................Failed
- hook id: forbid-binary
- exit code: 1
```

Maybe there's an easy fix around this, potentially even looking at `.gitattributes`?

### pre-commit --version

pre-commit 3.3.3

### .pre-commit-config.yaml

```yaml
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: forbid-binary
```
