### ISSUE TITLE
mirror-prettier freezes at installation step

### ISSUE THREAD

**Issue by 12rambau** [pre-commit/pre-commit#3034]
### search you tried in the issue tracker

"prettier"

### describe your issue

Whenver I want to use pre-commit on a new machine, installing mirror-prettier take ages. 
it starts as this: 
```
[INFO] Installing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
```

And then get stuck for 5 to 10 minutes. 

until now I didn't really cared but now that I started to code using Github codespace I install it more often and make it barely usable. I don't have more informations as the printing freezes. 

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: "https://github.com/psf/black"
    rev: "22.3.0"
    hooks:
      - id: black
        stages: [commit]

  - repo: "https://github.com/commitizen-tools/commitizen"
    rev: "v2.18.0"
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: "https://github.com/kynan/nbstripout"
    rev: "0.5.0"
    hooks:
      - id: nbstripout
        stages: [commit]

  - repo: "https://github.com/pre-commit/mirrors-prettier"
    rev: "v2.7.1"
    hooks:
      - id: prettier
        stages: [commit]
        exclude: tests\/test_.+\.

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.215"
    hooks:
      - id: ruff
        stages: [commit]

  - repo: https://github.com/PyCQA/doc8
    rev: "v1.1.1"
    hooks:
      - id: doc8
        stages: [commit]

  - repo: https://github.com/FHPythonUtils/LicenseCheck
    rev: "2023.5.1"
    hooks:
      - id: licensecheck
        stages: [commit]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        stages: [commit]
        additional_dependencies:
          - tomli

  # Prevent committing inline conflict markers
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
        stages: [commit]
        args: [--assume-in-merge]
```
