### ISSUE TITLE
Pre-commit skips files even when i have the type staged during commit

### ISSUE THREAD

**Issue by DestinedCodes** [pre-commit/pre-commit#3046]
### search you tried in the issue tracker

Staged, skips

### describe your issue

I just setup orecommit on a repo, when i do pre-commit run without the --all-files flag it works perfectly since it detects the staged files and runs the hook on them. But with same condition when i run git commit it skips. I have some delibrate errors some files and those files are staged when i do git commit it skips but when i do pre-commit run it works

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: no-commit-to-branch
        args: ['--pattern', '^(?!^(build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)/[-a-zA-Z0-9]+)']

-   repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:                                                                                  -   id: black
        language_version: python
        args:
            - --line-length=79

-   repo: https://github.com/asottile/seed-isort-config                                     rev: v2.2.0
    hooks:
    -   id: seed-isort-config

-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args:
        - --profile
        - black

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake

-   repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
    -   id: docformatter

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        args:
        - --max-line-length=79
        - --extend-ignore=W503

-   repo: https://github.com/pylint-dev/pylint
    rev: v3.0.1
    hooks:
    -   id: pylint
        args:
        -   '*.py'
        -   --disable=import-error

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    -   id: mypy
        args:
        - --strict
        - --ignore-missing-imports
        - --allow-untyped-decorators

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit

-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
    -   id: commitlint
        stages: [ commit-msg ]
        additional_dependencies: [ "@commitlint/config-conventional" ]
```
