### ISSUE TITLE
`pre-commit run` gets all refs regardless of `--from-ref`

### ISSUE THREAD

**Issue by aentwist** [pre-commit/pre-commit#3056]
### search you tried in the issue tracker

from-ref

## Description

I am writing a pre-commit hook for a commit message linter, commitlint. commitlint takes a series of commits and checks their commit messages. It can either run on all commits or a subset of commits.

The end goal is to run on a subset of commits. In order to hope I can get this working I need to be able to specify a 'from commit' argument. That way, the correct behavior might be achieved

- on commit-msg
- on manual
- in CI, no matter what CI variable is provided for the base SHA

pre-commit does not allow passing options to the hook from the CLI. But, this might be ok because `pre-commit run` has a `--from-ref` option. However, I notice when using this option that **all** of the refs are still passed to the hook.

Idea: send all refs and filter to a subset with commitlint -> not practical/possible, would need a different hook with different args for each usage (commit-msg, manual, GitHub Actions, GitLab CI, Travis, etc.)
Idea: filter refs to a subset with pre-commit and run commitlint on all -> doesn't work, still sends all refs

I propose that this is either fixed with a fancy git command or pre-commit somehow makes the values of options `--from-ref` (and `--to-ref`) available (via variables?)

###### Run on commit-msg

```shell
commitlint --edit
```

(tricky)

###### Run on all commits

```shell
commitlint --from
```

In a repo where commitlint fails refs before my-ref and passes on refs from my-ref: this fails even when filtering commits with `pre-commit run --hook-stage=manual --from-ref=my-ref --to-ref=HEAD`. I have verified this by hardcoding the ref in the commitlint command and not using pre-commit `--from-ref`, i.e.

```yaml
entry: commitlint --from=my-ref
```

with `pre-commit run --hook-stage manual` (passes).

###### Run on a local branch

```shell
commitlint --from="$(git merge-base --fork-point main)"
```

###### Run in GitHub Actions

```shell
commitlint --from=$GITHUB_BASE_REF
```

###### Run in GitLab CI

```shell
commitlint --from=$CI_MERGE_REQUEST_DIFF_BASE_SHA
```

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

Since I am developing this it uses a local setup for now.

```yaml
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
repos:
  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        stages: [commit-msg, manual]
        language: node
        # I'm actually using `commitlint --from` here because I installed `commitlint` globally, but don't worry about that
        entry: npx -- commitlint --from
        pass_filenames: false
        always_run: true
        additional_dependencies:
          - "@commitlint/config-conventional"
```

## Setup

I have nodejs installed with asdf.

```shell
npm init  # just leave everything blank
npm i -D commitlint @commitlint/config-conventional
```

### .commitlintrc.json

```json
{
  "extends": ["@commitlint/config-conventional"]
}

```
