### ISSUE TITLE
Objective-C not supported fail

### ISSUE THREAD

**Issue by daniInfi7** [pre-commit/pre-commit#3058]
### search you tried in the issue tracker

objective, Objective-C

### describe your issue

I dont know if this is an issue with pre-commit or clang-format, but when I run just pure clang-format from the terminal it works. However when running with pre-commit I receive the following error:

clang-format.............................................................Failed
- hook id: clang-format
- exit code: 1

Configuration file(s) do(es) not support Objective-C: D:\proje.....

It seems like 'types_or' would not be applied, and furthermore, there are only c/h files which I want to commit.

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v17.0.4
  hooks:
  - id: clang-format
    'types_or': [c, c++]
    name: clang-format
    description: This hook formats the code to the specific c format.
    args: ["-style=file"]
```
