### ISSUE TITLE
`files` and `types` not filtering correctly

### ISSUE THREAD

**Issue by moshemoshe137** [pre-commit/pre-commit#3066]
### search you tried in the issue tracker

nbqa, jupyter, files, types,filter

### describe your issue

I sincerely apologize if this is a duplicate. I have been searching for hours to no avail.

`pre-commit` seems to run on files it should not. I have tried filtering the hook `nbqa-mypy` using both `files` and `types`, but neither seems to work. Despite trying to filter, `nbqa-mypy` is running on regular Python files:
```
EAB_tools: [dev]> pre-commit run nbqa-mypy -vv -a
nbqa-mypy................................................................Failed
- hook id: nbqa-mypy
- duration: 2.08s
- exit code: 1

EAB_tools\io\display.py:628: error: Unused "type: ignore" comment
            if figure._suptitle is not None:  # type: ignore
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
EAB_tools\io\display.py:629: error: Unused "type: ignore" comment
                filename = figure._suptitle.get_text()  # type: ignore
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 2 errors in 1 file (checked 1 source file)
```
I have tried `pre-commit clear`ing multiple times, as well as changing the revs of `nbqa` and `mypy`. I have tried using `pre-commit 3.4.0` and `pre-commit 3.5.0`. I am on Windows 10 with Python 3.11.6.

Thank you so much for your help and for this wonderful tool.

### pre-commit --version

pre-commit 3.4.0

### .pre-commit-config.yaml

```yaml
default_stages: [ commit, merge-commit, push, prepare-commit-msg, commit-msg,
                  post-checkout, post-commit, post-merge, post-rewrite ]
exclude: |
  (?x)(
  LICENSE|
  \.(html|csv|svg)$
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files  # Prevent giant files from being committed.
      - id: check-ast  # Simply check whether files parse as valid python.
      - id: check-case-conflict  # Check for files with names that would conflict on a
                                 # case-insensitive filesystem like macOS HFS+ or
                                 # Windows FAT.
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: check-toml  # checks toml files for parseable syntax.
      - id: check-yaml  # checks yaml files for parseable syntax.
      - id: destroyed-symlinks  # Detects symlinks which are changed to regular files
                                # with a content of a path which that symlink was
                                # pointing to. This usually happens on Windows when a
                                # user clones a repository that has symlinks, but they
                                # do not have the permission to create symlinks.
      - id: detect-private-key  # Checks for the existence of private keys.
      - id: end-of-file-fixer  # Makes sure files end in a newline and only a newline.
      - id: mixed-line-ending  # Replaces or checks mixed line ending.
      - id: trailing-whitespace  # Trims trailing whitespace.

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black-jupyter

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==22.12.6
          - flake8-comprehensions==3.10.1

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy .
        language: system
        pass_filenames: false
        types:
          - python

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - --py39-plus

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.2.2
    hooks:
      - id: pydocstyle
        additional_dependencies:
          - toml
          - tomli
        # Don't let `pre-commit` pass filenames
        # Instead, use `pydocstyle`'s default settings from pyproject.toml
        pass_filenames: false

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        args: ['--extra-keys=cell.metadata.pycharm']
        stages:
          - manual
      - id: nbstripout
        name: nbstripout pycharm metadata
        alias: nbstripout-pycharm
        args:
          - '--extra-keys=cell.metadata.pycharm'
          - --keep-output
          - --keep-count

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.0
    hooks:
      - id: nbqa-check-ast
      - id: nbqa-flake8
        additional_dependencies:
          - flake8==6.0.0
          - flake8-bugbear==22.12.6
          - flake8-comprehensions==3.10.1
        args:
          - '--extend-ignore=E402'  # module level import not at top of file
      - id: nbqa-isort
        additional_dependencies:
          - isort==5.12.0
      - id: nbqa-mypy
        additional_dependencies:
          - mypy==0.991
        files: .*\.ipynb$
        types:
          - jupyter
      - id: nbqa-pyupgrade
        additional_dependencies:
          - pyupgrade==v3.3.1
        args:
          - --py39-plus  # Synchronize with args in regular hook
  - repo: https://github.com/python-jsonschema/check-jsonschema.git
    rev: 0.20.0
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
```
