### ISSUE TITLE
pre-commit takes a long time when GIT_DIR is set

### ISSUE THREAD

**Issue by brandonchinn178** [pre-commit/pre-commit#3067]
### search you tried in the issue tracker

GIT_DIR

### describe your issue

We want to have separate pre-commit configurations in subdirectories of a monorepo, that's all kicked off by a top-level pre-commit config. So we have a pre-commit hook that cd's into each subdirectory and runs pre-commit in the subdirectory.

It turns out that this takes a long time when running hooks with `git commit`. Specifically, `git commit` sets `GIT_DIR`, and running `pre-commit` while 1) in a subdirectory, and 2) `GIT_DIR` is set will cause `_get_diff()` to return the contents of all files.

Minimal repro:
```
export GIT_DIR=$(git rev-parse --git-dir)
cd subdir

# slow in a large repo; _get_diff() returns all the file contents
pre-commit run check-symlinks
```

It's perhaps a niche edge case, but unintuitive. Maybe pre-commit should run `git diff` with `GIT_DIR` omitted from the environment?

### pre-commit --version

2.10.1

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0  # upgrade only after DevVM uses Python 3.7
  hooks:
  - id: check-symlinks
```
