### ISSUE TITLE
Local dotnet format killing PC by running multiple copies

### ISSUE THREAD

**Issue by cvallance** [pre-commit/pre-commit#3069]
### search you tried in the issue tracker

dotnet

### describe your issue

I was setting up a local pre-commit hook for dotnet format as per the second set of instructions here, https://github.com/dotnet/format/blob/main/docs/integrations.md#pre-commitcom-hook-to-reformat 

When running it with a large number of changes it was killing my PC (gobble up my entire 64gb of ram and pegged the CPU).

Running `find . -name "*.cs" -print0 | xargs -0 dotnet format --include` on the directory seemed to run just fine, so I ran an experiment and found that it must be running multiple copies of `dotnet format`.

E.g. if I changed the config to:
```
      - id: test-echo
        name: test-echo
        language: system
        entry: echo BLAH ||
        types_or: [ "c#" ]
        stages: [commit]
        verbose: true
```

And then run `pre-commit run test --all-files` I see `BLAH || files.cs on.cs files.cs on.cs files.cs` 29 times... i.e. it ran the echo command 29 times, which I assume it's doing for dotnet as well.

Is this intended behaviour? Can I change it via some kind of configuration?

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format --include
        types_or: [ "c#" ]
        stages: [commit]
```

### ~/.cache/pre-commit/pre-commit.log (if present)

NA
