### ISSUE TITLE
Using --files flag to apply the run on specific subfolder

### ISSUE THREAD

**Issue by zivkaziv-airis** [pre-commit/pre-commit#3075]
### search you tried in the issue tracker

subfolder

### describe your issue

Hey,
In the last 2 days I've been trying so many different things and couldn't find the answer (so sorry if you find it duplicated)
I'm trying to run the pre-commit using the cli on **specific subfolder** without any luck and I don't understand why.

I'm running the following command
`pre-commit run --config /my_repo/ci/hooks/.pre-commit-config.yaml --files /my_repo/folder_1`

And I was expecting to see all the files under `folder_1` folder, but it seems not to apply on any file.
 
Do I need to specify the files regex pattern differently? 
Thanks

### pre-commit --version

3.5.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: meta
    hooks:
    -   id: identity
        name: identity
```

### ~/.cache/pre-commit/pre-commit.log (if present)

black................................................(no files to check)Skipped
identity.............................................(no files to check)Skipped
