### ISSUE TITLE
pre-commit can not find a file to process

### ISSUE THREAD

**Issue by qu4d** [pre-commit/pre-commit#3076]
### search you tried in the issue tracker

poetry, no files to check, missing files

### describe your issue

For some reason the combination of poetry's `virtualenvs.in-project true` and pre-commit leads to missing steps (missing files).
```
sw_vers
ProductName:            macOS
ProductVersion:         14.1.1
BuildVersion:           23B81
```
```
git -v
git version 2.43.0
```
```
poetry -V
Poetry (version 1.7.1)
```
```
pre-commit --version
pre-commit 3.5.0
```
```
pyenv -v
pyenv 2.3.32
pyenv versions
  system
  3.9.18
  3.10.13
  3.11.6
* 3.12.0 (set by /Users/kv/.pyenv/version)
```
steps to reproduce
```
poetry config virtualenvs.in-project true
poetry init
poetry shell
poetry install
poetry add pre-commit --dev (not sure if we can use local pre-commit dependency)
git init
pre-commit install
git add . 
git commit -am 'feat: app setup' 
```
leads to
```
commitizen check.........................................................Passed
check python ast.....................................(no files to check)Skipped
check for case conflicts.................................................Passed
check docstring is first.............................(no files to check)Skipped
check json...........................................(no files to check)Skipped
check for merge conflicts................................................Passed
check toml...........................................(no files to check)Skipped
check yaml...........................................(no files to check)Skipped
debug statements (python)............................(no files to check)Skipped
detect private key.......................................................Passed
don't commit to branch...................................................Failed
- hook id: no-commit-to-branch
- exit code: 1
fix requirements.txt.................................(no files to check)Skipped
prettier.............................................(no files to check)Skipped
Pretty format TOML...................................(no files to check)Skipped
docformatter.........................................(no files to check)Skipped
isort................................................(no files to check)Skipped
black................................................(no files to check)Skipped
pylint...............................................(no files to check)Skipped
```
I expect toml files to be formatted:
```
pre-commit run
check for added large files..............................................Passed
check python ast.....................................(no files to check)Skipped
check for case conflicts.................................................Passed
check docstring is first.............................(no files to check)Skipped
check json...........................................(no files to check)Skipped
check for merge conflicts................................................Passed
check toml...............................................................Passed
check yaml...............................................................Passed
debug statements (python)............................(no files to check)Skipped
detect private key.......................................................Passed
fix end of files.........................................................Passed
don't commit to branch...................................................Failed
- hook id: no-commit-to-branch
- exit code: 1
fix requirements.txt.................................(no files to check)Skipped
trim trailing whitespace.................................................Passed
prettier.................................................................Passed
Pretty format TOML.......................................................Failed
- hook id: pretty-format-toml
- exit code: 1
- files were modified by this hook

File poetry.lock is not pretty-formatted
Fixing file poetry.lock
File pyproject.toml is not pretty-formatted
Fixing file pyproject.toml

docformatter.........................................(no files to check)Skipped
isort................................................(no files to check)Skipped
black................................................(no files to check)Skipped
pylint...............................................(no files to check)Skipped
```

### pre-commit --version

3.5.0

### .pre-commit-config.yaml

```yaml
default_install_hook_types:
  - commit-msg

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.12.0
    hooks:
      - id: commitizen

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.11.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [--black, --in-place]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.11.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
```

**Comment by asottile** [comment]
please read the section on commiting in the docs

**Comment by qu4d** [comment]
I would appreciate I you could point me to the specific section

**Comment by asottile** [comment]
not at a computer, please try first I am not a glorified search engine

**Comment by qu4d** [comment]
for those who found this "issue"
the problem was in creating only `commit-msg` (should be used only for `commitizen`), but not `pre-commit` to run other files
here is the working code:
```
default_install_hook_types:
  - commit-msg
  - pre-commit

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.12.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
```
