### ISSUE TITLE
The use of args

### ISSUE THREAD

**Issue by transreductionist** [pre-commit/pre-commit#3080]
### search you tried in the issue tracker

passing args

### describe your issue

This is not an issue, but a question. I have read the docs several times on passing args to the hook using the .pre-commit-config.yaml (see included config). I have also searched online quite a bit, even extensively. The code I implemented is below, and was based on pre-commit hook no_commit_to_branch. The code works correctly and will commit if the branch name is not master or main.

I do not understand why, after setting the args in the config to `[--branch, staging, --pattern, <regex string>]`, the regex string is not in the argv for --pattern, and in fact neither is staging for --branch. I am sure I have missed something fundamental about the use of args. 

Can you explain to me what I have done incorrectly?

```python
"""Prevent committing to an inappropriate branch."""
from __future__ import annotations
import argparse
from typing import AbstractSet
from typing import Sequence


def no_commit_to_branch(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser = args_for_protected(parser)
    parser = args_for_patterns(parser)
    protected, patterns = __get_protected_branches_and_patterns(parser, argv)

    print('*****', protected)
    print('*****', patterns)

    return_code = is_on_branch(protected, patterns)

    return return_code


def args_for_patterns(parser):
    parser = __add_git_pattern_switch(parser)
    return parser


def __add_git_pattern_switch(parser):
    parser.add_argument('-p', '--pattern', action='append', help="Regex pattern",)
    return parser


def __get_protected_branches_and_patterns(parser, argv):
    args = parser.parse_args(argv)
    protected = frozenset(args.branch or ('master', 'main'))
    patterns = frozenset(args.pattern or ())
    return protected, patterns


if __name__ == '__main__':
    raise SystemExit(no_commit_to_branch())
```

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: no-commit-to-branch
        args: [--branch, staging, --pattern, <regex string>]
        name: no-commit-to-branch
        description: Make sure the commit isn't to master.
        language: system
        entry: bash -c 'src_py/cenv/python .git/hooks/no-commit-to-branch.py'
        types: [python]
        pass_filenames: false
        verbose: true
        log_file: .git/hooks/pre_commit_log
```

### version information

```
pre-commit version: 3.5.0
git --version: git version 2.40.0.windows.1
sys.version:
    3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
sys.executable: C:\src_py\cenv\python.exe
os.name: nt
sys.platform: win32
```
