### ISSUE TITLE
args inside `pre-commit-hooks.yaml` not working

### ISSUE THREAD

**Issue by ThomasMarwitzQC** [pre-commit/pre-commit#3087]
### search you tried in the issue tracker

pre-commit args for hook in pre-commit-hooks.yaml 

### describe your issue

I expected the `args` property to work and to pass default arguments to my hook specified in `pre-commit-hooks.yaml`.

I tried the following formats:
```
-   id: insert-license
    name: Insert license in comments
    description: "Insert a short license disclaimer as a header comment in source files"
    entry: insert-license
    language: conda
    args: ["--license-base64=Q29weXJpZ2h0IChDKSAyMDQyLCBQZWFyQ29ycCwgSW5jLgpTUERYLUxpY2Vuc2UtSWRlbnRpZmllcjogTGljZW5zZVJlZi1QZWFyQ29ycAo="]
    types: [text]
```
and 
```
-   id: insert-license
    name: Insert license in comments
    description: "Insert a short license disclaimer as a header comment in source files"
    entry: insert-license
    language: conda
    args: ["--license-base64", "Q29weXJpZ2h0IChDKSAyMDQyLCBQZWFyQ29ycCwgSW5jLgpTUERYLUxpY2Vuc2UtSWRlbnRpZmllcjogTGljZW5zZVJlZi1QZWFyQ29ycAo="]
    types: [text]
```

However, this doesn't work for me. The hook complains about not receiving the argument `--license-base64`.

This stackoverflow [article](https://stackoverflow.com/questions/64810779/are-args-in-pre-commit-config-yaml-overwriting-args-in-pre-commit-hooks-yaml) had me trying to pass the argument via `entry`, i.e. `entry: insert-license --license-base64 Q29...`. That worked for me, so I will probably stick with that solution. However, I'm wondering what I did wrong regarding the `args` property. 

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: ../../pre-commit-insert-license
    rev: 61b3388
    hooks:
      - id: insert-license
        types: [python]
        args:
          - --dynamic-years
          - --comment-style
          - "#"
```
