### ISSUE TITLE
uses old .flake8 config if .flake8 change not staged

### ISSUE THREAD

**Issue by tljstewart** [pre-commit/pre-commit#3088]
### search you tried in the issue tracker

`flake8` `config`

### describe your issue

i run flake8 from a makefile, pre-commit hook uses old .flake8 config if .flake8 change not staged with current commit. Expect behaviour is to use current working directory .flake8 regardless of git status

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: "config/run_id.txt"
      - id: check-yaml
        exclude: "mkdocs.yml"
      - id: check-added-large-files
        args: ["--maxkb=1000"]
        exclude: "notebooks"
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: detect-private-key
  - repo: local
    hooks:
      - id: style
        name: style
        entry: make
        args: ["style"]
        language: system
        pass_filenames: false
      # - id: clean
      # name: clean
      # entry: make
      # args: ["clean"]
      # language: system
      # pass_filenames: false
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
#       args: ["--severity=warning"]  # Optionally only show errors and warnings
```
