### ISSUE TITLE
Allow passing extra argument to "language" program

### ISSUE THREAD

**Issue by mdeweerd** [pre-commit/pre-commit#3097]
### search you tried in the issue tracker

is:issue trace 

### describe your actual problem

It would be useful to allow passing argument to the "language" program - not only to the script itself.

For instance, to debug why a third party commit hook fails, it would be handy to be able to run `python -m trace -t thirdparty-script.py "$@"` .  And to ignore libraries while tracing even `python -m trace --ignore-dir=/usr/lib -t ` .

In practice, I wanted to debug the following:
```yaml
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: remove-tabs
        exclude: (\.sh)$
```

The following:
```
pre-commit run -a -v remove-tabs
```

Fails with:
```
Tabs remover.............................................................Failed
- hook id: remove-tabs
- duration: 1.4s
- exit code: 127
```

That is not an expected outcome according to https://github.com/Lucas-C/pre-commit-hooks/blob/master/pre_commit_hooks/remove_tabs.py#L40-L45 .

So I added and ran the identity hook:

```yaml
  - repo: meta
    hooks:
      - id: identity
        exclude: (\.sh)$
        verbose: true
        log_file: rmtabs.log
```

I copied https://raw.githubusercontent.com/Lucas-C/pre-commit-hooks/master/pre_commit_hooks/remove_tabs.py locally and ran:

```shell
python3 -m trace -t ./rmtabs  --whitespaces-count 4 $(cat rmtabs.log)
```

Which finished normally with `rmtabs(42):     return 0` in the trace.

Therefore, debugging as close to the original setup as possible might help to identify the issue.  And IMHO this is a feature that would more generally be useful for debugging, or getting traces from end users for instance.

Possibly this feature does not pin-point the exact issue in my actual case - it could simply show that the script that is called actually exits normally.

### pre-commit --version

pre-commit 3.4.0

**Comment by asottile** [comment]
you can override `entry`

**Comment by mdeweerd** [comment]
Yes, I can override entry.

```yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        entry: ls -l
      - id: trailing-whitespace
        entry: /usr/bin/python3 -m trace -t trailing_whitespace_fixer.py
```

- The first override shows that we are in the working or git root;
- The second shows that even after looking up the proper base name of the script that is called (not the text that is mentioned as 'entry:' for the hook itself), it does not find the script.

One idea of the extra argument is to avoid having to look for proper paths/do other local clones of the hood repositories/... .

Anyway, a "indefinite pausing" issue with the above targets seems hard to debug as it does not seem to happen when calling the core script with the trace active on pre-commit
`/usr/bin/python3 -m trace  -t /usr/local/bin/pre-commit run -a -v`.  The heisenberg principle applied to computer programs...
