### ISSUE TITLE
Prettier additional dependencies are not found

### ISSUE THREAD

**Issue by ClementChaumel** [pre-commit/pre-commit#3098]
### search you tried in the issue tracker

prettier, additional_dependencies, Cannot find package

### describe your issue

When running ` pre-commit run --all-files` the prettier hook fails with `[error] Cannot find package 'prettier-plugin-tailwindcss' imported from [MyWorkingDir]/noop.js` 

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
# configure shared hooks that you want to run on all repositories here
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.1.0' # Use the sha / tag you want to point at
    hooks:
    - id: prettier
      additional_dependencies:
      - prettier@3.1.0
      - prettier-plugin-tailwindcss
      files: '^frontend/.*\.tsx?$'
      verbose: true
      args: [--config=./frontend/.prettierrc.cjs]
```
