### ISSUE TITLE
hooks should merge arguments from config with hooks before running

### ISSUE THREAD

**Issue by krish2718** [pre-commit/pre-commit#3103]
### search you tried in the issue tracker

args additional config and hooks

### describe your issue

I have a hook with args as below:
```
- id: xyz-ci
  entry: xyz
  args:
    - --ci
```   
I was expecting both the args to be passed to the hook, but the `args` from `config` override the `args` from `hooks`. As per docs, it says *additional parameters*, so, shouldn't it combine the args from config with the hooks?

> [args](https://pre-commit.com/#hooks-args)
> 
> (optional: default []) list of additional parameters to pass to the hook.

### pre-commit --version

pre-commit 3.6.0

### .pre-commit-config.yaml

```yaml
repos:
   - repo: ...
     hooks:
       - id: xyz-ci
         args: 
            - --abc
```
