### ISSUE TITLE
`pip install .` works but hook "executable not found" error when running pre-commit

### ISSUE THREAD

**Issue by Greedquest** [pre-commit/pre-commit#3105]
### search you tried in the issue tracker

is:issue "Executable not found" is:closed sort:updated-desc 

### describe your issue

I am trying to run a custom python script as a pre-commit hook on VBA files.
To do this I have added a pyproject.toml to the root of my repo

```toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hooks"
version = "1.0.0"
dependencies = ["gitpython"]

[project.scripts]
vba-case-check = "hooks.vba_case_check:main"
```

and there is a hooks/vba_case_check.py file with a main method taking zero arguments in my repo.

when I `pip install .` at the root of my repo, I get a vba-case-check.exe on the PATH.

However in the terminal I get
```
(precommit) PS C:\Username\Documents\GitHub\OnEvent> pre-commit run
[INFO] Initializing environment for local.
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
VBA Case Check...........................................................Failed
- hook id: vba-case-check
- exit code: 1

Executable `vba-case-check` not found
```

even though `vba-case-check.exe` works when I `pip install .` inside a venv

### pre-commit --version

pre-commit 3.6.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: local
    hooks:
    - id: vba-case-check
      name: VBA Case Check
      description: This hook reverts hunks in VBA files that only change casing.
      entry: vba-case-check
      language: python
      types: [file]
      files: \.(bas|cls|doccls)$
      require_serial: true
```
