### ISSUE TITLE
Different behavior between local usage and Github Actions

### ISSUE THREAD

**Issue by cedric-spinergie** [pre-commit/pre-commit#3109]
### search you tried in the issue tracker

Tons of different variants of "unreported errors in CI and local", "CI mismatch with local" across the repositories pre-commit, flake8 and pycodestyle.

### describe your issue

I am trying to setup `pre-commit` so it runs in our CI to perform our checks.  
Currently, we have a `flake8` hook. This hook reports errors in our CI that are not reported when running locally with the exact same command.

CI:
```
flake8...................................................................Failed
- hook id: flake8
- duration: 3.46s
- exit code: 1
cedric_test.py:2:23: E201 whitespace after '{'
cedric_test.py:2:32: E202 whitespace before '}'
```

Local:
```
> pre-commit run flake8 --all-files --verbose
flake8...................................................................Passed
- hook id: flake8
- duration: 0.44s
```

File with error:
```py
def my_test_function(num: int):
    print(f"""Num is {   num    }""")
```

At first I didn't notice the error but the CI reported it and I thought it made sense but I could never reproduce it locally.  
To be fair, I don't know where to publish this issue, the GHA repo for pre-commit? The flake8 repos? The pycodestyle repo? Here? Stack Overflow? I had no idea so I'm trying here.

I also found the following StackOverflow question: https://stackoverflow.com/questions/37614726/flake8-not-reporting-on-lines-that-are-too-long that made me realize I might have some config leftover somewhere on my computer. To make sure, I manually did `flake8 --ignore=E502` to try and take precedence but the error still didn't appear.  

Here is the ENTIRE workflow triggering the error. Both jobs report the errors.
```yml
on:
  workflow_call:

jobs:
  pre-commit-on-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # requites to grab the history of the PR
          fetch-depth: 0

      - uses: actions/setup-python@v3

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --color=always --verbose --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}

  pre-commit-all-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --color=always --verbose --all-files

```

Here is another workflow we have (that I'm trying to replace with pre-commit) that only runs flake8 and doesn't report the error either (to make sure it's not due to my PC):
```yml
on:
  workflow_call:

jobs:
  backend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - name: Flake8 python lint checks
        run: |
          pip3 install flake8==6.1.0
          flake8
```

What leaves me quite surprised is that I expect `pre-commit` to be idempotent with a given configuration. I thought it would install exactly the same thing on my computer as it does on the CI. (We would then get the exact same errors).

### pre-commit --version

Both 3.4.0 and 3.6.0 had the problem

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
```
