### ISSUE TITLE
`types: [c]` doesn't pick up `.h` files, but `identify-cli` does

### ISSUE THREAD

**Issue by max-sixty** [pre-commit/pre-commit#3111]
### search you tried in the issue tracker

types identify, identify-cli, hpp, h

### describe your issue

I have this config:

```yaml
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
        types: [c, c++]
```

I was surprised that a `.h` file wasn't getting picked up. It looks like `pre-commit` uses `identify`, so I checked how that identified it. It _does_ tag it as a `c` & `c++` file:

```sh
$ identify-cli prqlc/bindings/prqlc-c/prqlc.h
["c", "c++", "file", "header", "non-executable", "text"]
```

Note that it has an _additional_ field `header` relative to a `.cpp` file.

```sh
$ identify-cli prqlc/bindings/prqlc-c/examples/minimal-cpp/main.cpp
["c++", "file", "non-executable", "text"]
```

Any ideas why pre-commit & identify differ here?

### pre-commit --version

pre-commit 3.6.0

### .pre-commit-config.yaml

```yaml
(Snippet above, full version is at https://github.com/PRQL/prql/blob/main/.pre-commit-config.yaml if that's helpful)
```
