### ISSUE TITLE
Pre-commit does not correctly check files when a commit is ammended

### ISSUE THREAD

**Issue by ylatuya** [pre-commit/pre-commit#3112]
### search you tried in the issue tracker

git commit ammend

### describe your issue

We are migrating our hooks system to pre-commit in [GStreamer](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/5920) and the process has been great so far. Thanks a lot for the amazing work you have done with pre-commit ❤️

I would like to report what I believe might be a bug. When amending a commit that contains files that should be checked by the hooks, the files are not checked, and  instead, the hook returns `(no files to check)Skipped`

```bash
➜  gstreamer git:(pre-commit) ✗ git commit --amend
dotnet-format........................................(no files to check)Skipped
gst-indent...........................................(no files to check)Skipped
rustfmt..............................................(no files to check)Skipped
gitlint..................................................................Passed
dotnet-format........................................(no files to check)Skipped
gst-indent...........................................(no files to check)Skipped
rustfmt..............................................(no files to check)Skipped
[pre-commit d3f0f8b027] DO NOT MERGE: check pre-commit hooks in the CI
 Date: Mon Jan 15 13:03:42 2024 +0100
 3 files changed, 6 insertions(+), 4 deletions(-)
```

This commit has 3 files (a C file, a C# file and a Rust file) that should have been checked. If I run pre-commit for that commit, it checks them correctly.

```bash
➜  gstreamer git:(pre-commit) ✗  pre-commit run  --from-ref HEAD^  --to-ref HEAD --verbose
dotnet-format............................................................Failed
- hook id: dotnet-format
- duration: 3.55s
- files were modified by this hook

  Formatting code files in workspace '/Users/andoni/git/gstreamer/subprojects/gstreamer-sharp/gstreamer-sharp.sln'.
Warnings were encountered while loading the workspace. Set the verbosity option to the 'diagnostic' level to log warnings.
Required references did not load for gstreamer-sharp or referenced project. Run `dotnet restore` prior to formatting.
  Formatted code file '/Users/andoni/git/gstreamer/subprojects/gstreamer-sharp/sources/custom/Caps.cs'.
  Format complete in 3164ms.


gst-indent...............................................................Failed
- hook id: gst-indent
- duration: 0.02s
- files were modified by this hook
rustfmt..................................................................Failed
- hook id: rustfmt
- duration: 0.15s
- files were modified by this hook

Using rustfmt config file /Users/andoni/git/gstreamer/rustfmt.toml for /Users/andoni/git/gstreamer/subprojects/gstreamer/libs/gst/helpers/ptp/args.rs
Formatting /Users/andoni/git/gstreamer/subprojects/gstreamer/libs/gst/helpers/ptp/args.rs
Spent 0.008 secs in the parsing phase, and 0.003 secs in the formatting phase

```

I would expect that pre-commit correctly checks modified files by a commit when running `git commit --amend`. 

### pre-commit --version

pre-commit 3.6.0

### .pre-commit-config.yaml

```yaml
default_install_hook_types: [pre-commit, commit-msg]
fail_fast: false
repos:
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
    -   id: gitlint
-   repo: local
    hooks:
    # Use dotnet format installed on your machine
    -   id: dotnet-format
        name: dotnet-format
        language: system
        files: ^subprojects/gstreamer-sharp/.*
        entry: dotnet format subprojects/gstreamer-sharp/gstreamer-sharp.sln -v normal --include
        types_or: ["c#", "vb"]
    -   id: gst-indent
        name: gst-indent
        language: system
        entry: ./scripts/gst-indent
        types_or: ["c"]
    # The rust hook uses cargo fmt, which requires a Cargo.toml
    # We use a local hook to run rustfmt directly
    -   id: rustfmt
        name: rustfmt
        language: system
        entry: rustfmt --verbose --edition 2021
        types_or: ["rust"]
```
