### ISSUE TITLE
Node hooks not installing dependencies 

### ISSUE THREAD

**Issue by rkesters** [pre-commit/pre-commit#3117]
### search you tried in the issue tracker

node

### describe your issue

I have create hook in node, when running the hook I get the error below. When looking at the installed location of the hook, I do not see the node_modules directory. 

```sh
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '/Users/kestersor/DEC/code/icam/repos/iac/dist/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.18.2
```

repo for hook is `https://github.com/rkesters/commit-msg-helper.git`

### pre-commit --version

pre-commit 3.6.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: /Users/kestersor/DEC/code/github/commit-msg-helper
    rev: f728848
    hooks:
    -   id: commit-msg-helper
        verbose: true
```

### ~/.cache/pre-commit/pre-commit.log (if present)

none

**Comment by asottile** [comment]
your output doesn't look like one that I woudl expect from pre-commit -- the file it should be running should look like `/Users/kestersor/.pre-commit/cache/repoXXX/node_<SOMETHING>/bin/<SOMETHING>`

can you share the full command you ran and its unredacted output?

**Comment by rkesters** [comment]
This is what i ran: 

```sh
01/26/24 16:40❯ git amend
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...............................................................Passed
Check for added large files..............................................Passed
Check Yaml...........................................(no files to check)Skipped
Check for added large files..............................................Passed
Commit Message Helper....................................................Failed
- hook id: commit-msg-helper
- duration: 0.6s
- exit code: 1

node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '/Users/kestersor/DEC/code/icam/repos/iac/dist/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.18.2

```

**Comment by asottile** [comment]
that output doesn't match your configuration -- can you show a new isolated example?

**Comment by rkesters** [comment]
This is the config in the repo I'm testing in:
```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: /Users/kestersor/DEC/code/github/commit-msg-helper
    rev: f728848
    hooks:
    -   id: commit-msg-helper
        verbose: true
```
this is the output
```sh
01/26/24 16:57❯ git commit -am 'test' 
Commit Message Helper....................................................Failed
- hook id: commit-msg-helper
- duration: 1.15s
- exit code: 1

node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '/Users/kestersor/DEC/code/icam/repos/iac/dist/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.18.2
```
