### ISSUE TITLE
Types / files filtering *.ipp files

### ISSUE THREAD

**Issue by paulgessinger** [pre-commit/pre-commit#3118]
### search you tried in the issue tracker

types, files

### describe your issue

I'm trying to get the [clang-format](https://github.com/pre-commit/mirrors-clang-format) to run on `ipp` files. 
The documentation gives an example on how this can be achieved for json checking:

```yaml
-   id: check-json
    types: [file]  # override `types: [json]`
    files: \.(json|myext)$
```

I'm using 

```yaml
- id: clang-format
  types: [file]
  files: \.(cpp|hpp|ipp|cu|cuh)$
```

This does not run on `ipp` files, and seems to still restrict to the default C++ file types.

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v14.0.0'
    hooks:
      - id: clang-format
        types: [file]
        files: \.(cpp|hpp|ipp|cu|cuh)$
```
