### ISSUE TITLE
Running `local` hook with `stages: [commit-msg]` never triggers

### ISSUE THREAD

**Issue by norman-zon** [pre-commit/pre-commit#3120]
### search you tried in the issue tracker

repo:local commit-msg, stages, local stages

### describe your issue

I am exploring your idea of running pre-commit in pre-commit, that you outlined [here](https://stackoverflow.com/a/59055569).

I would like to expand this approach to not only have a single central config, but to have "collection hooks" for different languages, but each with a set of "mandatory" hooks that are shared.

The repo is setup like this:

```
.
├── hooks
│   ├── mandatory-commit-msg.yaml
│   └── terraform.yaml
├── .pre-commit-hooks.yaml
└── run-hooks
```

run-hooks.yaml:

```python
#!/usr/bin/env python3
import os
import argparse

# idea taken from https://stackoverflow.com/a/59055569

HERE = os.path.dirname(os.path.realpath(__file__))

def main():
    parser = argparse.ArgumentParser(description='Run pre-commit with an arbitrary hooks file.')
    parser.add_argument('--hook-path', metavar='hook_path', type=str, required=True,
                            help='Path to the hooks file')
    parser.add_argument('additional_args', metavar='additional_args', type=str, nargs='*',
                        help='Additional pre-commit arguments')

    args = parser.parse_args()

    cfg = os.path.join(HERE, args.hook_path)

    cmd = ['pre-commit', 'run', '--config', cfg]

    if args.additional_args[-1] == ".git/COMMIT_EDITMSG":
        cmd += ['--hook-stage', 'commit-msg', '--commit-msg-filename'] + args.additional_args
    else:
        cmd += ['--files'] + args.additional_args
    os.execvp(cmd[0], cmd)

if __name__ == '__main__':
    exit(main())

```

hooks/mandatory-commit-msg.yaml

```yaml
repos:
  - repo: https://gitlab.com/repo-hooks/pre-commit-trailer
    rev: v1.1.0
    hooks:
      - id: add-pre-commit-config-trailer
        stages: [commit-msg]
```

hooks/terraform.yaml

```yaml
repos:
- repo: local
  hooks:
    - id: mandatory-commit-msg
      name: mandatory commit-msg hooks
      language: script
      entry: ./run-hooks --hook-path ./hooks/mandatory-commit-msg.yaml
      stages: [commit-msg]
      verbose: true

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.86.0
  hooks:
    - id: terragrunt_fmt
    ...
```

.pre-commit-hooks.yaml

```yaml
-   id: mandatory-commit-msg
    name: mandatory commit-msg hooks
    language: script
    entry: ./run-hooks --hook-path ./hooks/mandatory-commit-msg.yaml
    stages: [commit-msg]
    verbose: true

-   id: terraform
    name: terraform/terragrunt hooks
    language: script
    entry: ./run-hooks --hook-path ./hooks/terraform.yaml
    stages: [pre-commit]
    verbose: true

```

Nevertheless, the `mandatory-commit-msg` hook is never run:

```sh
 git commit --allow-empty -m 'test TEST'
terraform/terragrunt hooks...........................(no files to check)Skipped
- hook id: terraform
[pre-commit xxxxxx] test TEST
```

I read the docs regarding `repo: local` and the `commit-msg` stage, but can't find a plausible reason why this won't work.

PS:

ideally I would want to call `mandatory-commit-message` defined in `.pre-commit-hooks` directly, without having to specify it in `terraform.yaml`like so:

```yaml
epos:
- repo: local
  hooks:
    - id: mandatory-commit-msg

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.86.0
  hooks:
    - id: terragrunt_fmt
    ....
``` 

but I understand that's not how `repo: local`is designed to work, although it would be nice if you would consider adding this feature.

### pre-commit --version

3.6.0.

### .pre-commit-config.yaml

```yaml
default_install_hook_types: [pre-commit, commit-msg]
repos:
- repo: git@github.com:MYORG/ops-pre-commit.git
  rev: v0.2.1
  hooks:
    - id: terraform
```

**Comment by asottile** [comment]
you probably forgot to run `pre-commit install` with the correct arguments

everything beyond that is at your own support since `repo: local` and `language: script` are the escape hatches

**Comment by norman-zon** [comment]
I installed both hooks properly: ` pre-commit install --install-hooks -t pre-commit -t commit-msg`, still it does not trigger.

**Comment by norman-zon** [comment]
The hook is there:

```
cat .git/hooks/commit-msg
#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03

# start templated
INSTALL_PYTHON=/opt/homebrew/opt/pre-commit/libexec/bin/python3.12
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=commit-msg)
# end templated

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
```

**Comment by asottile** [comment]
your `.pre-commit-config.yaml`

**Comment by norman-zon** [comment]
In my config only the `terraform` hook is configured, that's right. But this hook includes a hook that has `stages: [commit-msg]` set. So it should cascade, right?

If I change `hooks/terraform.yaml` to point to the repo it lives in via git instead of local like this:

```yaml
repos:
  - repo: git@github.com:MYORG/ops-pre-commit.git
     rev: v0.2.1
     hooks:
       - id: mandatory-commit-msg

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.86.0
  hooks:
    - id: terragrunt_fmt
    ...
```

But then I arther do this with `local` instead of checking out a repo in itself

**Comment by asottile** [comment]
why would it cascade? you've only configured the `pre-commit` stage

it's not magic, it just does what you tell it to

**Comment by asottile** [comment]
yes and that's completely different.  the difference is now you are selecting a hook which has the `commit-msg` stage enabled

**Comment by norman-zon** [comment]
Isn't that the same I do here aswell?

```
repos:
- repo: local
  hooks:
    - id: mandatory-commit-msg
      name: mandatory commit-msg hooks
      language: script
      entry: ./run-hooks --hook-path ./hooks/mandatory-commit-msg.yaml
      stages: [commit-msg]
      verbose: true

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.86.0
  hooks:
    - id: terragrunt_fmt
```

**Comment by asottile** [comment]
and what happens with that one?

**Comment by norman-zon** [comment]
this is the code from my first post. the hook is not triggered

**Comment by asottile** [comment]
your first post does not have that config

**Comment by asottile** [comment]
ok what hooks in your actual config have the commit-msg stage

**Comment by norman-zon** [comment]
none. as in my second example, where it works though.
That's what i mean by cascading. My local (actual) conf does not have stages set, but the hooks that are called from there, do.

So what is the functional difference between

```yaml
-   id: commit-msg
    name: commit-msg hook
    language: system
    entry: echo "commit-msg hook"
    stages: [commit-msg]
    verbose: true

```

and 

```yaml
repos:
- repo: local
  hooks:
    - id: mandatory-commit-msg
      name: mandatory commit-msg hooks
      language: script
      entry: ./run-hooks --hook-path ./hooks/mandatory-commit-msg.yaml
      stages: [commit-msg]
      verbose: true
```
