### ISSUE TITLE
Warning message Unexpected key(s) present at root

### ISSUE THREAD

**Issue by qs5779** [pre-commit/pre-commit#3127]
### search you tried in the issue tracker

[WARNING] Unexpected key(s) present at root: default_install_hook_types

### describe your issue

[WARNING] Unexpected key(s) present at root: default_install_hook_types

### pre-commit --version

pre-commit 3.6.0

### .pre-commit-config.yaml

```yaml
$ cat .pre-commit-config.yaml                                                       (develop -> origin/develop|✔)
exclude: '^docs/conf.py'
default_install_hook_types: ["pre-commit", "commit-msg"]
default_stages: ["commit"]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows
  - id: no-commit-to-branch
    args: ['--branch', 'main']

- repo: local
  hooks:
    - id: isort
      name: isort
      entry: isort
      require_serial: true
      language: python
      language_version: python3
      types_or: [cython, pyi, python]
      args: ['--filter-files']
      minimum_pre_commit_version: '2.9.2'
      additional_dependencies: ['isort==5.10.1']
    - id: encryption-check
      name: Ansible Vault Encryption Check
      description: Checks that vault files are encrypted
      entry: /usr/local/bin/encryption-check.sh
      files: ((^|/)vault|vault.y[a]{0,1}ml$|.vault$)
      language: script
    - id: commit-msg
      name: conventional commit messages
      language: pygrep
      entry: '^(chore|test|feat|fix|build|docs|refactor)!?: ((?!.*(ing))(?!.*(ed))).*$'
      args: [--multiline, --negate]
      stages: [commit-msg]

- repo: https://github.com/psf/black
  rev: 24.1.1 #stable 0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    args: ['--max-line-length=88']
    # You can add flake8 plugins via `additional_dependencies`:
    additional_dependencies: [flake8-quotes]
```
