### ISSUE TITLE
missin prettier versions in mirrors-prettier

### ISSUE THREAD

**Issue by salzhrani** [pre-commit/pre-commit#3128]
### search you tried in the issue tracker

prettier

### describe your issue

the latest 3.X version is 3.1.0 while the latest in prettier repo is 3.2.5. there are a couple of versions missing

### pre-commit --version

3.6.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^src/
```
