### ISSUE TITLE
Can this gitlab CI pipeline be improved by using caching or pre-commit install-hooks?

### ISSUE THREAD

**Issue by gothicVI** [pre-commit/pre-commit#3129]
### search you tried in the issue tracker

gitlab, CI

### describe your actual problem

Not really a feature request but for sure not a bug - more like a question.
We're using the following `.gitlab-ci.yml` which runs several pre-commit checks in parallel due to the long runtimes - it's a big repository.
For each parallel run, all the dependencies need to be downloaded again and pre-commit needs to be initialized again which takes quite some time. Can this be improved somehow?
```
image: python:latest

stages:
  - pre-commit
  - build_doc
  - deploy_doc

pre_commit_builtin:
  stage: pre-commit
  only:
    - main
    - merge_requests
  before_script:
    - pip install -r requirements.txt
  script:
    - pre-commit run check-added-large-files --all-files
    - pre-commit run check-ast --all-files
    - pre-commit run check-executables-have-shebangs --all-files
    - pre-commit run check-shebang-scripts-are-executable --all-files
    - pre-commit run check-merge-conflict --all-files
    - pre-commit run debug-statements --all-files
    - pre-commit run end-of-file-fixer --all-files
    - pre-commit run mixed-line-ending --all-files
    - pre-commit run requirements-txt-fixer --all-files
    - pre-commit run trailing-whitespace --all-files

shellcheck:
  image: koalaman/shellcheck-alpine:latest
  stage: pre-commit
  only:
    - main
    - merge_requests
  before_script:
    - apk update && apk add git
  script:
#    - git ls-files --exclude='*.sh' --ignored -c -z | xargs -0r shellcheck
    - find . -name "*.sh" | grep -vE "nas_accounting/(bsb-check-free-nas-storage|my-nfs-mount-test).sh" | xargs -r -n 1 shellcheck

pre_commit_autopep8:
  stage: pre-commit
  only:
    - main
    - merge_requests
  before_script:
    - pip install -r requirements.txt
  script:
    - pre-commit run autopep8 --all-files

pre_commit_bandit:
  stage: pre-commit
  only:
    - main
    - merge_requests
  before_script:
    - pip install -r requirements.txt
  script:
    - pre-commit run bandit --all-files

pre_commit_pyupgrade:
  stage: pre-commit
  only:
    - main
    - merge_requests
  before_script:
    - pip install -r requirements.txt
  script:
    - pre-commit run pyupgrade --all-files

pre_commit_black:
  stage: pre-commit
  only:
    - main
    - merge_requests
  before_script:
    - pip install -r requirements.txt
  script:
    - pre-commit run black --all-files

pre_commit_isort:
  stage: pre-commit
  only:
    - main
    - merge_requests
  before_script:
    - pip install -r requirements.txt
  script:
    - pre-commit run isort --all-files

pre_commit_flake8:
  stage: pre-commit
  only:
    - main
    - merge_requests
  before_script:
    - pip install -r requirements.txt
  script:
    - pre-commit run flake8 --all-files

pre_commit_pycodestyle:
  stage: pre-commit
  only:
    - main
    - merge_requests
  before_script:
    - pip install -r requirements.txt
  script:
    - pre-commit run pycodestyle --all-files

pre_commit_pydocstyle:
  stage: pre-commit
  only:
    - main
    - merge_requests
  before_script:
    - pip install -r requirements.txt
  script:
    - pre-commit run pydocstyle --all-files

pre_commit_pylint:
  stage: pre-commit
  only:
    - main
    - merge_requests
  before_script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@our-gitlab.xyz/some_repo /tmp/some_repo
    - cd /tmp/some_repo
    - pip install -r requirements.txt
    - python3 -m pip install pip build
    - python3 -m build
    - python3 -m pip install -e .
    - cd -
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@our-gitlab.xyz/another_one /tmp/another_one
    - cd /tmp/another_one
    - pip install -r requirements.txt
    - python3 -m pip install pip build
    - python3 -m build
    - python3 -m pip install -e .
    - cd -
    - pip install -r requirements.txt
  script:
    - pre-commit run pylint --all-files

pre_commit_mypy:
  stage: pre-commit
  only:
    - main
    - merge_requests
  before_script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@our-gitlab.xyz/some_repo /tmp/some_repo # same as above!
    - cd /tmp/some_repo
    - pip install -r requirements.txt
    - python3 -m pip install pip build
    - python3 -m build
    - python3 -m pip install -e .
    - cd -
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@our-gitlab.xyz/another_one /tmp/another_one # same as above!
    - cd /tmp/another_one
    - pip install -r requirements.txt
    - python3 -m pip install pip build
    - python3 -m build
    - python3 -m pip install -e .
    - cd -
    - pip install -r requirements.txt
  script:
    - pre-commit run mypy --all-files

build_pages:
  stage: build_doc
  only:
    - main
    - merge_requests
  before_script:
    - apt update && apt install -y default-jre
    - pip install -r requirements.txt
  script:
    - sphinx-build ./docs ./docs/_build/html
  artifacts:
    paths:
      - ./docs/_build/html

pages:
  stage: deploy_doc
  only:
    - main
  dependencies:
    - build_pages
  script:
    - cp -rv ./docs/_build/html ./public
  artifacts:
    paths:
      - ./public

```
I've looked at https://pre-commit.com/#gitlab-ci-example and https://docs.gitlab.com/ee/ci/caching/#good-caching-practices but I don't fully understand what we'd need to change.

I've also been thinking if all of the dependencies could be placed in a Docker image which would then be used to run each pre-commit but I found no config that would allow me to get remotely close to getting that done.

Any help would be greatly appreciated.

Thanks!

### pre-commit --version

pre-commit 3.6.1
