### ISSUE TITLE
`mirrors-prettier` not supporting `prettier` version 3 after `v3.1.0`

### ISSUE THREAD

**Issue by jamesbraza** [pre-commit/pre-commit#3133]
### search you tried in the issue tracker

is:issue sort:updated-desc mirrors-prettier prettier v3 

### describe your issue

The last (as of 2/23/2024) non-alpha `prettier` mirror for `pre-commit` was `v3.1.0`: [pre-commit/mirrors-prettier/tags](https://github.com/pre-commit/mirrors-prettier/tags). After that only alpha versions for `prettier` v4 are added.

From [prettier/prettier/releases](https://github.com/prettier/prettier/releases), it looks like `prettier` is now on `v3.2.5`. In other words, https://github.com/pre-commit/mirrors-prettier is no longer supporting `prettier` v3.

The request is: can we have [pre-commit/mirrors-prettier](https://github.com/pre-commit/mirrors-prettier) continue supporting major version 3 of `prettier`?

---

There are two dupe chains right now:

1. Not pulling in `prettier` v3 (which this falls into): https://github.com/pre-commit/pre-commit/issues/3128, https://github.com/pre-commit/pre-commit-mirror-maker/issues/206, https://github.com/pre-commit/pre-commit-mirror-maker/issues/207
2. Filtering `prettier` alpha/beta versions (which is different): https://github.com/pre-commit/pre-commit/issues/3108, https://github.com/pre-commit/pre-commit-mirror-maker/issues/202, https://github.com/pre-commit/pre-commit-mirror-maker/issues/146

For dupe chain 1 (which I am interested in), I was unable to find a "terminal" issue in the dupe chain. So, please if this is closed as a dupe, can you link the terminal issue. Thanks in advance!

### pre-commit --version

3.6.2

### .pre-commit-config.yaml

```yaml
repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
```

### ~/.cache/pre-commit/pre-commit.log (if present)

n/a

**Comment by Mikaela** [comment]
I would say the relevant link is https://github.com/pre-commit/mirrors-prettier/pull/39 and use `additional_dependencies` (and check spelling from someone better at English than I am).

**Comment by jamesbraza** [comment]
Thank you so much @Mikaela, that works as a workaround to get the latest `prettier` v3. Though it doesn't play nice with `pre-commit autoupdate`.

```yaml
repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            additional_dependencies:
                - prettier@3.2.5 # SEE: https://github.com/pre-commit/pre-commit/issues/3133
```

It would be great if the most recent major version 3 was used automatically as the https://github.com/pre-commit/mirrors-prettier version (as happened in the past), so I will keep this open
