### ISSUE TITLE
pre-commit ignores failures in env setup

### ISSUE THREAD

**Issue by brandonchinn178** [pre-commit/pre-commit#3137]
### search you tried in the issue tracker

python error env

### describe your issue

We added ruff as a pre-commit hook, but when running pre-commit hooks, one of our devs got ``Executable `ruff` not found``.

This happened because the default version of python on their machine was Python 3.6, but ruff requires 3.7. What was surprising is that pre-commit didn't show any installation failures. It seems like this line should add `check=True`:
https://github.com/pre-commit/pre-commit/blob/7b868c3508dd3a4c1f1930dc25f5433f2dac7950/pre_commit%2Flanguages%2Fpython.py#L214

### pre-commit --version

2.10.1 (we're on an old version because of company policy, but the github source code doesnt look like it solves this issue)

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
      - id: ruff-format
```
