### ISSUE TITLE
when I userd the fixture in pytest, it will have some problems.

### ISSUE THREAD

**Issue by PasserAhao** [pre-commit/pre-commit#3138]
### search you tried in the issue tracker

pytest or fixture

### describe your issue

```python

import json
import pytest
from common.pytest_utils import pyclient


@pytest.fixture(scope="class")  
def robot_datas(request):
    from system_mgmt.models import Robot

    test_robot = Robot()
    ......
    test_robot.save()

    def clean_test_data():
        Robot.objects.filter(id=test_robot.id).delete()

    request.addfinalizer(clean_test_data)
    return test_robot, Robot


class TestRobot:
    def test_creat_dingtalk_robot(self, pyclient, robot_datas):
        _, robot = robot_datas
        datas = {}
        res = pyclient.post("/system/mgmt/robot/", datas)
        ......
```

### pre-commit --version

pre-commit: 2.17.0

### .pre-commit-config.yaml

```yaml
default_stages: [commit]
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.21.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
    - id: black
      language_version: python3.6
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: flake8
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.2
    hooks:
    - id: isort
  - repo: local
    hooks:
      - id: check-migrate
        name: check migrate
        entry: python scripts/check_migrate/check_migrate.py
        language: system
        types: [python]
      - id: check-commit-message
        name: Check commit message
        entry: python scripts/check_commit_message.py
        language: system
        stages: [commit-msg]
      - id: check-requirements
        name: Check Requirements
        entry: python scripts/check_requirements.py
        language: system
```

### ~/.cache/pre-commit/pre-commit.log (if present)

pyupgrade................................................................Passed
Check for merge conflicts................................................Passed
black....................................................................Passed
Flake8...................................................................Failed
- hook id: flake8
- exit code: 1
test_units/demo/view_test.py:8: [F401] 'common.pytest_utils.pyclient' imported but unused
from common.pytest_utils import pyclient
^
test_units/demo/view_test.py:38: [F811] redefinition of unused 'pyclient' from line 8
    def test_creat_dingtalk_robot(self, pyclient, robot_datas):
                                        ^
1     F401 'common.pytest_utils.pyclient' imported but unused
1     F811 redefinition of unused 'pyclient' from line 8
2
isort....................................................................Passed
check migrate............................................................Passed
Check Requirements.......................................................Passed
