### ISSUE TITLE
Running pre-commit uninstall still shows the "no .pre-commit-config.yaml file found" message

### ISSUE THREAD

**Issue by Mo0rBy** [pre-commit/pre-commit#3140]
### search you tried in the issue tracker

yes

### describe your issue

I have ran `pre-commit uninstall`, but pre-commits are still being run, and if I remove the `.pre-commit-config.yaml` file, I am blocked from making commits as the file is missing. This prompts me to do `pre-commit uninstall` which I execute again, but I am still blocked from making commits with the same message.

### pre-commit --version

3.6.2

### .pre-commit-config.yaml

```yaml
---
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        name: Check commit message format
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespaces
      - id: end-of-file-fixer
        name: Check ends of files
      - id: check-merge-conflict
        name: Check for merge-conflicts
      - id: check-yaml
        name: Check for un-parseable yaml
        args: [--allow-multiple-documents]
      - id: check-executables-have-shebangs
        name: Check shell script for shebang lines
      - id: check-shebang-scripts-are-executable
        name: Check shell scripts are executable

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2']
        name: Check yaml formatting

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: markdown-toc

  - repo: local
    hooks:
      - id: kustomize-build
        name: All relevant namespaces must pass 'kustomize build'
        description: This executes 'kustomize build' for all relevant namespaces.
        entry: .pre-commit-scripts/kustomize_build.sh
        language: script
        pass_filenames: false
```
