### ISSUE TITLE
Bash Variable Expansion Not Working

### ISSUE THREAD

**Issue by aaronmell** [pre-commit/pre-commit#3145]
### search you tried in the issue tracker

expansion

### describe your issue

See https://github.com/antonbabenko/pre-commit-terraform/issues/638 for more information. The hooks support bash variable expansion. Variable expansion works when I run the scripts directly. It does not work when I run the hooks through pre-commit.

### pre-commit --version

pre-commit 3.6.2

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.88.0
  hooks:
    - id: terraform_trivy
      verbose: true
      files: '^terraform-v2/root-modules/'
      types: [file]
      args:
        - --args=--config-policy="/Users/${USER}/PATH_TO_POLICY/"
        - --args=--skip-dirs="terraform/**"
```

### ~/.cache/pre-commit/pre-commit.log (if present)

pre-commit version: 3.6.2
git --version: git version 2.39.3 (Apple Git-145)
sys.version:
    3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]
sys.executable: /opt/homebrew/opt/python@3.11/bin/python3.11
os.name: posix
sys.platform: darwin
