### ISSUE TITLE
Variable and slow runtimes

### ISSUE THREAD

**Issue by ilyakamens** [pre-commit/pre-commit#3147]
### search you tried in the issue tracker

slow; variable runtime; unpredictable

### describe your issue

`pre-commit` seems to run slowly sometimes with no changes made by me between runs.

For example, this is what I'd expect, and is in line with our current system without `pre-commit`:

<img width="500" alt="image" src="https://github.com/pre-commit/pre-commit/assets/3293811/8dacdd3c-999c-42a5-ae09-1ef50c1ee60d">

This is another run seconds later with no configuration or additional files changed:

<img width="500" alt="image" src="https://github.com/pre-commit/pre-commit/assets/3293811/9ee20458-bbd3-496a-88ed-8db1cda32002">

In both cases there was one Python file changed. (Maybe another file or two for integrating `pre-commit`.) In the slow case, every lint step takes longer; for example, the first three take > 500ms each when it's slow, but all take < 500ms combined when it's fast. And just to clarify, every step was slower when it ran slowly.

This is the Docker image it's running in: `python:3.10.10-slim-bullseye`

This is what we have in `git_hooks/pre-commit`:

```bash
files=$(git diff --name-only --cached  --diff-filter=d)
./docker-shell lint ${files}
```

And here's what that `lint` command looks like:

```bash
elif [[ "$1" == "lint" ]]; then
  paths="${*:2}"
  paths="${paths:-.}"
  docker exec -t ${container} bash -c "cd /app && TRANSLATIONSPATH=$translationspath pre-commit run --files $paths"
elif ... then
```

And here's what the `lint` command looked liked before attempting to migrate to `pre-commit`:

```bash
elif [[ "$1" == "lint" ]]; then
  paths="${*:2}"
  paths="${paths:-.}"
  docker exec -t ${container} bash -c "cd /app &&
    pybabel extract --omit-header --no-location -F babel.cfg -o ${translationspath}/messages-lint.pot . 2> /dev/null &&
    (diff -q ${translationspath}/messages{,-lint}.pot ||
    echo \"message.pot should have changed. Run './docker-shell translate' to fix\") &&
    flake8 $paths &&
    black --check $paths &&
    isort --check-only ${*:2} &&
    pyright ${*:2}"
elif ... then
```

(I verified that `$paths` is correct; it was only one or three normal-sized files.)

Please let me know what additional information I can provide. I'd love to get this sorted out so I can merge my PR and get us to fully adopt it at my workplace!

### pre-commit --version

pre-commit 3.6.2

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--check]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [--check-only]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]
      - id: check-translations
        name: check-translations
        entry: bash ./scripts/linters/check-translations.sh
        language: system
        types: [python]
```

**Comment by asottile** [comment]
your `language: system` is resulting in a fork bomb.

`language: system` is at your own support and when you deviate from the golden path you're on your own to debug it.

**Comment by ilyakamens** [comment]
Got it. I understand how that explains slowness for the hooks under `repo: local`. In my description above, I mentioned that the first three were also subject to variable runtime:

```
- id: end-of-file-fixer
- id: trailing-whitespace
- id: check-yaml
```

Does `language: system` explain what I've described for those hooks as well? I reran my tests using only those hooks with the following configuration:

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
```

<br>Here's a fast run:

<img width="500" alt="image" src="https://github.com/pre-commit/pre-commit/assets/3293811/4ed0877a-33cf-497a-a7d4-5c1ba5e8b125">

<br>And here's a slow run:

<img width="500" alt="image" src="https://github.com/pre-commit/pre-commit/assets/3293811/a4ec4fe3-b57e-459f-9c91-a21767d23959">

<br>So you can see what I mean, here's a video of how I expect it to run:

https://github.com/pre-commit/pre-commit/assets/3293811/d993f6e5-8b4c-4925-b386-30092018dddc

<br>And here's a video when it's slow:

https://github.com/pre-commit/pre-commit/assets/3293811/3f08bb4d-6068-4c2f-a792-76a352aab7dd

<br>The difference is quite noticeable. In the examples above, I'm linting one YAML file 23 lines long. Please advise.
