### ISSUE TITLE
Pre-commit Python Not Found

### ISSUE THREAD

**Issue by daniel-lewis-ab** [pre-commit/pre-commit#3158]
### search you tried in the issue tracker

https://github.com/pre-commit/pre-commit/issues?q=is%3Aissue+%22Executable+python+not+found%22+is%3Aclosed+

### describe your issue

So I ran into the pre-commit python not found error.  I searched as described in the developer complaint.  I found these pages.  They didn't have the answer because they said "search for the error message".

Nice catch 22.  I'll go back to wasting my time looking for the answer now, since I couldn't just search for the error message and find it.

### pre-commit --version

3.6.2

### .pre-commit-config.yaml

```yaml
exclude: "^data/pipelines_db.json$|^mkdocs.yaml$|^docs/json/.*"

repos:
  # Pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
        # don't remove line-breaks in markdown
        args: [--markdown-linebreak-ext=md]
      - id: debug-statements
      - id: detect-private-key
      - id: check-yaml
      - id: end-of-file-fixer

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2
    hooks:
      - id: prettier
        types: [yaml]

  # codespell
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args:
          ["--ignore-words-list", "hist, parms, wit, ba, te", "--skip", "*.txt"]

  # Make sure commited notebooks have no output
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout

  - repo: local
    hooks:
      # linter
      - id: ruff
        name: ruff
        entry: ruff --diff --fix .
        language: system
        pass_filenames: false
        args: [--line-length, "120"]
      # formatter
      - id: black
        name: black
        entry: black --diff .
        language: system
        pass_filenames: false
        args: [--line-length, "120"]
```

### ~/.cache/pre-commit/pre-commit.log (if present)

cat /home/dl/.cache/pre-commit/pre-commit.log
### version information

```
pre-commit version: 3.6.2
git --version: git version 2.34.1
sys.version:
    3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('python', '-mpip', 'install', '.')
return code: 1
stdout:
    Executable `python` not found
stderr: (none)
```

```
Traceback (most recent call last):
  File "/home/dl/.local/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/dl/.local/lib/python3.10/site-packages/pre_commit/main.py", line 417, in main
    return run(args.config, store, args)
  File "/home/dl/.local/lib/python3.10/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/home/dl/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 238, in install_hook_envs
    _hook_install(hook)
  File "/home/dl/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 94, in _hook_install
    lang.install_environment(
  File "/home/dl/.local/lib/python3.10/site-packages/pre_commit/languages/python.py", line 214, in install_environment
    lang_base.setup_cmd(prefix, install_cmd)
  File "/home/dl/.local/lib/python3.10/site-packages/pre_commit/lang_base.py", line 86, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/home/dl/.local/lib/python3.10/site-packages/pre_commit/util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('python', '-mpip', 'install', '.')
return code: 1
stdout:
    Executable `python` not found
stderr: (none)
