### ISSUE TITLE
Missing files when using `entry: bash -c "... $@"`

### ISSUE THREAD

**Issue by FalloutBoy42** [pre-commit/pre-commit#3166]
### search you tried in the issue tracker

Missing files, bash -c

### describe your issue

I need to set some environment variables like discussed in [758](https://github.com/pre-commit/pre-commit/issues/758). 
So I tried to use something like `entry: bash -c 'MY_VAR="$(pwd)/xxx" echo $@'`.
Setting the environment variables works as expected but it seems that `$@` does not contain all files.

Let say I commit 6 files `f1.py, f2.py, f3.py, f4.py, f5.py, f6.py`.

- With `entry: echo xxx` the output is:
`xxx f1.py f2.py f3.py f4.py`
`xxx f5.py f6.py`
- With  `entry: bash -c 'echo xxx $@'` the output is:
`xxx f2.py f3.py f4.py`
`xxx f6.py`

The first file in each line is missing. 

Looks like a bug to me or is there a reason? 

### pre-commit --version

3.6.2

### .pre-commit-config.yaml

```yaml
repos:
- repo: local
  hooks:
    - id: mypy
      name: Mypy
      entry: bash -c 'MY_VAR="$(pwd)/xxx" echo $@'
      types: [python]
      files: 'someDir/'
      language: system
```
