### ISSUE TITLE
pre-commit in pre-commit creating excessive log output

### ISSUE THREAD

**Issue by ryan-dyer-sp** [pre-commit/pre-commit#3174]
### search you tried in the issue tracker

none

### describe your issue

I am trying to follow the steps here:
https://github.com/pre-commit/pre-commit/issues/731#issuecomment-376945745

Everything works as shown except when performing a run -a.  During this I receive 4 repetitive blocks of output

.pre-commit-hooks.yaml
```
-   id: tf-org-hook
    name: org-wide terraform hooks
    language: script
    entry: ./run-hooks
    verbose: true
```

hooks.yaml
```
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: end-of-file-fixer
  - id: check-added-large-files
- repo: https://github.com/awslabs/cfn-python-lint
  rev: v0.83.8 # The version of cfn-lint to use
  hooks:
  - id: cfn-lint-rc
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.86.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
  - id: terraform_fmt
    args:
    - --args=-write=true
  - id: terraform_tflint
    args:
    - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
  - id: terraform_providers_lock
    args:
    - --hook-config=--mode=always-regenerate-lockfile
- repo: git@github.com:X/pre-commit-hooks.git
  rev: v1.0.2
  hooks:
  - id: jira-ticket-prepend
```

run-hooks
```
#!/usr/bin/env python
import os
import sys

HERE = os.path.dirname(os.path.realpath(__file__))


def main():
    cfg = os.path.join(HERE, 'hooks.yaml')
    cmd = ['pre-commit', 'run', '--config', cfg, '--files'] + sys.argv[1:]
    os.execvp(cmd[0], cmd)


if __name__ == '__main__':
    exit(main())
```

Run output:
```
pre-commit run -a
org-wide terraform hooks.................................................Passed
- hook id: tf-org-hook
- duration: 1.69s

trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check for added large files..............................................Passed
AWS CloudFormation Linter................................................Passed
Terraform fmt............................................................Passed
Terraform validate with tflint...........................................Passed
Lock terraform provider versions.....................(no files to check)Skipped
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check for added large files..............................................Passed
AWS CloudFormation Linter................................................Passed
Terraform fmt............................................................Passed
Terraform validate with tflint...........................................Passed
Lock terraform provider versions.....................(no files to check)Skipped
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check for added large files..............................................Passed
AWS CloudFormation Linter................................................Passed
Terraform fmt............................................................Passed
Terraform validate with tflint...........................................Passed
Lock terraform provider versions.....................(no files to check)Skipped
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check for added large files..............................................Passed
AWS CloudFormation Linter................................................Passed
Terraform fmt............................................................Passed
Terraform validate with tflint...........................................Passed
Lock terraform provider versions.....................(no files to check)Skipped
```

### pre-commit --version

3.6.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/X/pre-commit-configs
    rev: b72c6ace3251eb0db4e6aa85a1caa6387f695e74
    hooks:
    -   id: tf-org-hook
```
