### ISSUE TITLE
SKIP is not recognized

### ISSUE THREAD

**Issue by MichaelMorozovCodit** [pre-commit/pre-commit#3177]
### search you tried in the issue tracker

is:issue skip not recognized 

### describe your issue

When I wanted to skip a hook, I got this error:

```
PS C:\Users\MichaelMorozov\source\repos\devsecops-baseline> SKIP=vacuum git commit -m "message"
SKIP=vacuum: The term 'SKIP=vacuum' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

So I had to resort to $env:SKIP="vacuum";git commit -m"message":

```
PS C:\Users\MichaelMorozov\source\repos\devsecops-baseline> $env:SKIP='vacuum'; git commit -m "message"
checking for updates.....................................................Passed
check for added large files..............................................Passed
detect private key.......................................................Passed
gitleaks secret detection................................................Passed
vacuum..................................................................Skipped
[main 99fdeba] message
 3 files changed, 70 insertions(+), 2 deletions(-)
```

Running on Windows 11.

### pre-commit --version

pre-commit 3.7.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://gitlab.com/vojko.pribudic/pre-commit-update
    rev: v0.2.1
    hooks:
    -   id: pre-commit-update
        name: checking for updates
        stages: ["commit"]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files # prevents giant files from being committed
        stages: ["commit", "push"]
        args: [--maxkb=1000]
    -   id: detect-private-key # detects the presence of private keys
        stages: ["commit", "push"]
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
    -   id: gitleaks
        entry: gitleaks
        args: ["protect", "--verbose", "--redact", "--staged"]
        pass_filenames: false
        name: gitleaks secret detection
        description: Detect hardcoded secrets using Gitleaks
        stages: ["commit", "push"]
-   repo: https://github.com/daveshanley/vacuum
    rev: v0.9.12
    hooks:
    -   id: vacuum
        name: vacuum
        description: OpenAPI linter and quality checker
        entry: vacuum lint
        files: openapi.json
        stages: ["commit"]
```
