### ISSUE TITLE
Output reported in blocks

### ISSUE THREAD

**Issue by skwde** [pre-commit/pre-commit#3179]
### search you tried in the issue tracker

block / output

### describe your issue

`pre-commit` seems to call linters in batches and shows all blocks even if no errors have been found for the files checked in a certain block.

Block with errors look like

```out
markdownlint-cli2 v0.13.0 (markdownlint v0.34.0)
Finding: <some files, probably the oncs checked>
Linting: 37 file(s)
Summary: 1 error(s)
<file and line> <error with link>
```

they hide between blocks reporting no errors

```out
markdownlint-cli2 v0.13.0 (markdownlint v0.34.0)
Finding: <some files, probably the oncs checked>
Linting: 28 file(s)
Summary: 0 error(s)
```

This makes it very hard to find and identify the actual problems.

This problem does not occur when I call the specific linter without pre-commit on all files.

See related issue here: https://github.com/DavidAnson/markdownlint-cli2/issues/301

### pre-commit --version

pre-commit 3.7.0

### .pre-commit-config.yaml

```yaml
---
repos:
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
      - id: markdownlint-cli2
        additional_dependencies:
          - markdownlint-cli2-formatter-pretty
```
