### ISSUE TITLE
Support creating custom pre-commit environments

### ISSUE THREAD

**Issue by Fr0d0Beutl1n** [pre-commit/pre-commit#3180]
### search you tried in the issue tracker

custom environment

### describe your actual problem

Pre-commit can automatically create environments (e.g. a Python virtual environment) for a fixed set of programming languages.  
I propose to add support for creating custom/user-defined environments.

For example we could either
* add an `install_environment` hook to the `script` language
* or add a `custom` language that behaves like `script` but has an additional `install_environment` script hook

**Example usage**

In this example a hook is defined with the `custom` language.
The command specified as `install_environment` is called once to setup the hook environment.
Afterwards the command specified as `entry` is executed as usual.

```
- repo: https://github.com/pre-commit/pre-commit-hooks
  hooks:
    - id: my-script
      name: My Script
      language: custom
      install_environment: setup.sh
      entry: my-script.sh
```

### pre-commit --version

pre-commit 3.0.4
