### ISSUE TITLE
how to mark file types to bianry by extensions?

### ISSUE THREAD

**Issue by trim21** [pre-commit/pre-commit#3181]
### search you tried in the issue tracker

bianry type file/type file by extension 

### describe your actual problem

I have a binary file format looks like text but it's not. And I don't want any hooks with `type: [text]` to run on it. I have many hooks and I want to know is there a way to mark file type by extension? 

`.gitattributes` support `*.ext binary`, is it doable with pre-commit?

for example, currently I have to add `exclude` to all hooks I'm using and may run on text file, can I do it by some global config key to set `{pattern: '*.ext', type: bianry}` ?

I even try to rename them to `.bin` and it still doesn't treated as binary file:

```
$ identify-cli.exe my_file_name.bin
["executable", "file", "text"]
```

### pre-commit --version

3.7.0

**Comment by asottile** [comment]
you're looking for `exclude`

**Comment by trim21** [comment]
I'm not sure...

For example, I'm using https://github.com/pre-commit/pre-commit-hooks

I hope text file hook `end-of-file-fixer` could skip, but hook `check-added-large-files` could still work.

**Comment by asottile** [comment]
what have you tried?

**Comment by trim21** [comment]
create a repo with this config:

```yaml
default_stages: [commit]

exclude: '.*\.bin'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files # check for file bigger than 500kb
        args: ["--maxkb=123"]
      - id: end-of-file-fixer
```

add a `test.bin` with huge sige, and commit

then it passed.
