### ISSUE TITLE
`pre-commit g` does not delete temporary patch files from cache

### ISSUE THREAD

**Issue by pmhahn** [pre-commit/pre-commit#3183]
### search you tried in the issue tracker

gc cache patch temporary

### describe your issue

Looking into `~/.cache/pre-commit` I find many files names `patch00000-00000` and `patch00000` from several years ago until recently, which seem to contain the output of previous `git diff`s. Even a `pre-commit gc` does not clean them up.

```console
$ ls -1d patch* * | wc -l
2516
```

Can I delete them manually? (I did; the directory is named `cache` and any app is supposed to work without it)

Please change 'pre-commit gc` to also cleanup those temporary files.

Why is `pre-commit` leaving behind those files in the first place?

### pre-commit --version

pre-commit 3.6.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
```
