### ISSUE TITLE
More verbose messaging/reason in `pygrep` hooks

### ISSUE THREAD

**Issue by mxr** [pre-commit/pre-commit#3195]
### search you tried in the issue tracker

pygrep

### describe your actual problem

`pygrep` hooks can be confusing to users because the output only shows the matched string. It would be helpful to have some way to tell the user what to do when the hook fails. Although users don't always read error messages (understatement), for the ones that do, an error message is a reasonable place to provide next steps for how to resolve the issue.

Maybe the `description` field could be co-opted for this and printed out when the hook is run with `--verbose`?

### pre-commit --version

latest

**Comment by asottile** [comment]
I don't want description to be load bearing.  use `name` if you need to communicate what it doesas that's what it's for

**Comment by mxr** [comment]
OK, to confirm, you mean like this?

```yaml
-   id: use-bar-instead-of-foo
    name: use bar instead of foo because foo is deprecated
    entry: '\bfoo\b'
    language: pygrep
```
