### ISSUE TITLE
Pre-push hook stuck

### ISSUE THREAD

**Issue by iclick0n** [pre-commit/pre-commit#3198]
### search you tried in the issue tracker

pre-push

### describe your issue

I ran git push, but the hook didn't seem to trigger. Interestingly, the hook activates with git commit, and pre-commit try-repo functions normally. For debugging, I manually executed .git/hooks/pre-push, but it hung indefinitely without logs or errors, while .git/hooks/pre-commit operated as expected.

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: /pre-commit-github
    rev: 44f9b874113dd8379e3a3cf653bc4c72df714ac8
    hooks:
    -   id: check-test
        stages: [pre-push, pre-commit]
```
