### ISSUE TITLE
--all-files flag does not work for untracked files

### ISSUE THREAD

**Issue by aahnik** [pre-commit/pre-commit#3200]
### search you tried in the issue tracker

--all-files

### describe your issue

as per docs https://pre-commit.com/#4-optional-run-against-all-the-files

**ASSUMPTION**: Expected behavior:  output of  `pre-commit run --files ./**/**` and `pre-commit run --all-files` should be same.

I dug into the implementation of `--all-files`

(you can git checkout this commit hash: 16023286d2e2, which is the latest commit at the time of me writing this)

```python
# pre_commit/commands/run.py Line 266
elif args.all_files:
        return git.get_all_files()
        
 # ...
 
 # pre_commit/git.py Line 154
 def get_all_files() -> list[str]:
    return zsplit(cmd_output('git', 'ls-files', '-z')[1])
    # this does not give untracked files

```

     

### pre-commit --version

3.7.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        entry: isort
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.10 
        entry: black
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
    - id: markdownlint-cli2
```
