### ISSUE TITLE
Fail when trying to ```additional_dependencies=[googleads==3.8.0]```

### ISSUE THREAD

**Issue by knyazer** [pre-commit/pre-commit#3202]
### search you tried in the issue tracker

google ads, google

### describe your issue

I was setting up a pyright hook on a repo that uses fastapi. Fastapi depends on pydantic, which in turn depends on ```googleads==3.8.0```. And installation of it fails, with ```error in googleads setup command: use_2to3 is invalid.```. I think the issue might be with the default container used for the pre-commit, but I don't really have time to look into it right now, so that's just an assumption.

### pre-commit --version

3.2.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff 
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.362
    hooks:
    - id: pyright
      additional_dependencies: [pytest, fastapi, beartype, orjson, numpy, parselmouth]
      args: []
```

### ~/.cache/pre-commit/pre-commit.log (if present)

      Using cached googleads-3.8.0.tar.gz (23 kB)
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'error'
stderr:
      error: subprocess-exited-with-error

      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> [1 lines of output]
          error in googleads setup command: use_2to3 is invalid.
          [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: subprocess-exited-with-error

    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.
