### ISSUE TITLE
running single hook on a single file runs all hooks `pre-commit run --files [filename] [hook name]`

### ISSUE THREAD

**Issue by drjasonharrison** [pre-commit/pre-commit#3210]
### search you tried in the issue tracker

"pre-commit run"

### describe your issue

The documentation has:

> Usage 
>
> Run pre-commit install to install pre-commit into your git hooks. pre-commit will now run on every commit. Every time you clone a project using pre-commit running pre-commit install should always be the first thing you do. 
> 
> If you want to manually run all pre-commit hooks on a repository, run pre-commit run --all-files. To run individual hooks use pre-commit run <hook_id>.

Unfortunately there is nothing in this description or in the output of `pre-commit run --help` that specifically excludes or includes the possibility of "running individual hooks on individual files"

Previously I was successfully able to use pre-commit to format markdown documents by using:
```pre-commit run --files  "${FILE_PATH}" end-of-file-fixer > /dev/null```

However, since I hadn't been looking at the output of pre-commit and failed to notice that  pre-commit was running all of my hooks until it failed a hook:

```
$ pre-commit run --files README.md end-of-file-fixer
Check for added large files..............................................Passed
Check for case conflicts.................................................Passed
Check that executables have shebangs.................(no files to check)Skipped
Check JSON...........................................(no files to check)Skipped
Check for merge conflicts................................................Passed
Check that scripts with shebangs are executable..........................Passed
Check Toml...........................................(no files to check)Skipped
Check Yaml...........................................(no files to check)Skipped
Detect AWS Credentials...................................................Passed
Detect Private Key.......................................................Passed
Fix End of Files.........................................................Passed
Forbid new submodules....................................................Passed
Mixed line ending........................................................Passed
Don't commit to branch...................................................Failed
- hook id: no-commit-to-branch
- exit code: 1
```

I tried various other combinations of hook identifier and the `--files` option

```
pre-commit run end-of-file-fixer
[WARNING] Unstaged files detected.
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/jason/.cache/pre-commit/patch1717091905-14331.
fix end of files.........................................................Passed
[INFO] Restored changes from /home/jason/.cache/pre-commit/patch1717091905-14331.
```

So I knew it is possible to run a single hook on all staged files. And this article gives examples of many ways of running hooks but does not have a "run a single hook against one or more files" https://adamj.eu/tech/2022/10/20/pre-commit-various-ways-to-run-hooks/ 

Can you please confirm if running a single hook on a file, staged or not, is possible? --all-files works, I'm looking for the --files option to be attended to.

### pre-commit --version

pre-commit 3.7.1

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    node: 16.14.2 # force all unspecified node hooks to run node 16
    python: python3.6 # force all unspecified python hooks to run python 3.10
default_stages: [commit]
fail_fast: true
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          # to temporarily skip check-added-large-files hook:
          # SKIP=check-added-large-files git commit -m "message"
          - id: check-added-large-files
            args: [--maxkb 1000]
            stages: [commit]
          - id: check-case-conflict
            stages: [commit]
          - id: check-executables-have-shebangs
            exclude: |
                (?x)(
                  .py
                )
            stages: [commit]
          - id: check-json
            exclude: |
                (?x)(
                  ^.vscode/|
                  ^Pipfile.lock$
                )
            stages: [commit]
          - id: check-merge-conflict
            stages: [commit]
          - id: check-shebang-scripts-are-executable
            stages: [commit]
          - id: check-toml
          - id: check-yaml
            stages: [commit]
          - id: detect-aws-credentials
            args: [--allow-missing-credentials]
          - id: detect-private-key
          - id: end-of-file-fixer
            stages: [commit]
          - id: forbid-new-submodules
          - id: mixed-line-ending
            args: [--fix=lf]
            stages: [commit]
          - id: no-commit-to-branch # by default protects main and master
          - id: pretty-format-json
            args: [--autofix, --no-sort-keys, "--indent", "4"]
            exclude: |
                (?x)(
                  ^.vscode/|
                  ^Pipfile.lock$
                )
          - id: trailing-whitespace
            stages: [commit]

    # isort is also configured in pyproject.toml
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: "v5.10.1"
      hooks:
          - id: isort
            args: [--profile, black, --skip, external, --filter-files]
            stages: [commit]

    - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
      rev: "v1.1.1"
      hooks:
          - id: dockerfile_lint
            stages: [commit]

    # use hadolint until dockerfilelint is supported
    - repo: https://github.com/hadolint/hadolint
      rev: v2.12.1-beta
      hooks:
          - id: hadolint-docker
            name: Lint Dockerfiles
            description: Runs hadolint Docker image to lint Dockerfiles
            language: docker_image
            types: [dockerfile]
            entry: ghcr.io/hadolint/hadolint hadolint
            args: [--no-fail]
            # args: [--config, hadolint.yaml]

    # black is also configured in pyproject.toml
    - repo: https://github.com/ambv/black
      rev: "22.3.0"
      hooks:
          - id: black
            args: [--config, pyproject.toml]
            stages: [commit]

    - repo: https://github.com/pycqa/flake8
      rev: "5.0.4" # pick a git hash / tag to point to
      hooks:
          - id: flake8
            stages: [commit]

    # May require Node 14 which may require GLIBC_2.28,
    # Try again with Ubuntu 20
    # - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    #   rev: v0.1.0
    #   hooks:
    #     - id: dockerfilelint
    #       stages: [commit]

    # run shellcheck and shfmt-docker before update-all-readme
    # use shellcheck before shfmt as errors in the script break shfmt
    # To install shellcheck: https://github.com/koalaman/shellcheck#installing
    - repo: https://github.com/koalaman/shellcheck-precommit
      rev: v0.9.0
      hooks:
          - id: shellcheck
            # --severity: Specify minimum severity of errors to consider.
            # Valid values in order of severity are error, warning, info and style.
            # The default is style.
            #
            # --format: Specify the output format. gcc is compatible with code editors.
            args: ["--severity=error", "--format=gcc"]
            stages: [commit]

    - repo: https://github.com/scop/pre-commit-shfmt
      rev: v3.7.0-1
      hooks:
          - id: shfmt-docker # Docker image (requires Docker to run)
            args: ["-i", "4"]
            stages: [commit]

    # update README.md before running doctoc
    - repo: local
      hooks:
          - id: update-all-readme
            description: update all README.md
            name: Update all README.md's
            entry: bash ./bash/update-all-readme.bash
            args: []
            language: system
            types_or: [bash, python]
            pass_filenames: false
            stages: [commit]

    # use doctoc while markdown-toc can't handle multiple files at a time
    - repo: https://github.com/thlorenz/doctoc
      rev: "v2.2.0"
      hooks:
          - id: doctoc
            stages: [commit]
            exclude: ^CHANGE-LOG.*\.md$

    - repo: https://github.com/iterative/dvc
      rev: 2.8.1
      hooks:
          - id: dvc-pre-commit
            language_version: python3
            stages: [commit]

          - id: dvc-pre-push
            # use s3/gs/etc instead of all to only install specific cloud support
            additional_dependencies: [".[all]"]
            language_version: python3
            stages: [push]

          - always_run: true
            id: dvc-post-checkout
            language_version: python3
            stages: [post-checkout]

    # check if script outputs have changed
    - repo: local
      hooks:
          - id: check-script-outputs
            description: check script outputs
            name: Check script outputs.
            entry: bash ./tests/run-tests.bash
            args: []
            language: system
            types_or: [bash, python]
            pass_filenames: false
            stages: [commit]
            exclude: ^.*.md$
```
