### ISSUE TITLE
Respect `default_language_version` for local python hooks

### ISSUE THREAD

**Issue by Repiteo** [pre-commit/pre-commit#3215]
### search you tried in the issue tracker

is:issue local python language_version OR default_language_version 

### describe your actual problem

I'm wanting to setup the [Godot repository](https://github.com/godotengine/godot) with support for pre-commit on our local python scripts. …Well, technically it's *already* setup; however, as we want to make the system as multi-platform as possible, we'd ideally want a solution which can support any python call out-of-the-box. Unfortunately, `python3` isn't guaranteed to exist on Windows machines, nor `python` on MacOS; as it stands, someone users are going to have to do the symlink workaround. But this isn't the only workaround, as the documentation [already provides](https://pre-commit.com/#overriding-language-version) a notice on how it can automatically convert the inputs themselves:

> on windows the [pep394](https://www.python.org/dev/peps/pep-0394/) name will be translated into a py launcher call for portability. So continue to use names like `python3` (`py -3`) or `python3.6` (`py -3.6`) even on windows.

This initially seemed like the ticket to solve the portability issue, but that section of the documentation only applies to a specific portion: `default_language_version` (and `language_version` by extension). Local python hooks are meant to be run with `system`/`script` as their language as it stands, but even specifying the language as `python` doesn't make any real difference. Either way, it'll either require a prefixed variation of the non-portable `python`, or rely on a shebang that also isn't guaranteed to be portable.

## Proposed Implementation:
```yaml
default_language_version:
  python: python3.8

repos:
  - repo: local
    hooks:
      - id: some-hook
        name: Some Hook
        language: python
        entry: path/to/some_hook.py
```
This would end up calling `py -3.8 path/to/some_hook.py` on Windows and `python3.8 path/to/some_hook.py` otherwise. This would bypass the need to rely on a non-portable prefix and/or shebang entirely. This wouldn't conflict with the established conventions of keeping the local repo in a separate/dummy position, as this is strictly assigning the executable call in a portable manner & leaving everything else as-is.

### pre-commit --version

pre-commit 3.7.1

**Comment by asottile** [comment]
what have you tried and what isn't working? local hooks do use that setting

**Comment by Repiteo** [comment]
I'll trim some exerpts then. We currently use:
```yaml
repos:
  - repo: local
    hooks:
      - id: make-rst
        name: make-rst
        language: python
        entry: python3 doc/tools/make_rst.py doc/classes modules platform --dry-run --color
        pass_filenames: false
        files: ^(doc/classes|.*/doc_classes)/.*\.xml$
```
On unconfigured Windows machines, this will output:
```
make-rst.................................................................Failed
- hook id: make-rst
- duration: 0.09s
- exit code: 9009

Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
```
If I instead omit the `python3` argument & define a default language instead, like below:
```yaml
default_language_version:
  python: python3

repos:
  - repo: local
    hooks:
      - id: make-rst
        name: make-rst
        language: python
        entry: doc/tools/make_rst.py doc/classes, modules, platform, --dry-run, --color
        pass_filenames: false
        files: ^(doc/classes|.*/doc_classes)/.*\.xml$
```
…Then trying to run this once again doesn't change anything; it *still* outputs the same kind of error:
```
make-rst.................................................................Failed
- hook id: make-rst
- duration: 0.08s
- exit code: 9009

Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
```
Well, maybe the shebang has something to do with it? If I remove the `#!/usr/bin/env python3` line from `doc/tools/make_rst.py` and run the above code once more:
```
make-rst.................................................................Failed
- hook id: make-rst
- duration: 0s
- exit code: 1

[WinError 193] %1 is not a valid Win32 application
```
This confuses me the most. Why would it be giving the above error if it's calling the valid `py -3` instead? This makes me think that it's trying to read the shebang no matter what. I'm even more confident in this because readding the shebang as `#!/usr/bin/env python` results in success:
```
make-rst.................................................................Passed
```
Unless I'm misreading things or missing something obvious, local python hooks don't use `default_language_version` nor `language_version` whatsoever. More than that, they don't appear to call a python version whatsoever, just taking the entry/args as-is and placing them in a command line; they require either prepending a non-portable `python3` argument or calling a file with a non-portable `python3` shebang.
