### ISSUE TITLE
Regression in `nodeenv` 1.9.0

### ISSUE THREAD

**Issue by Alexander-Shukaev** [pre-commit/pre-commit#3220]
### search you tried in the issue tracker

nodeenv

### describe your issue

FYI: ekalinin/nodeenv#356

In my environment I simply blacklisted it with `nodeenv!=1.9.0` and suggest the same is done in `pre-commit` requirements explicitly.

### pre-commit --version

3.7.1

### .pre-commit-config.yaml

```yaml
- repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint-fix
        stages: [manual]
      - id: markdownlint
        stages: [manual]
```
