### ISSUE TITLE
Unable to redirect stderr

### ISSUE THREAD

**Issue by rlsanders4** [pre-commit/pre-commit#3221]
### search you tried in the issue tracker

stderr, standard error, redirect output

### describe your issue

I am attempting to redirect the stderr output from a pre-commit failure into a text file. The stderr output displays correctly in the terminal, but I am unable to redirect it.

Output in the terminal without redirection:
<img width="797" alt="image" src="https://github.com/pre-commit/pre-commit/assets/59902221/f5453420-9f70-4cab-b769-f4924d5aa680">

Command used to redirect output:
```
git commit -m "test" 2> stderr.txt
```

Redirecting the output always results in an empty file when the pre-commit fails. I have no problem redirecting the output for sucessful pre-commit runs.

### pre-commit --version

pre-commit 3.7.1

### .pre-commit-config.yaml

```yaml
repos: <private repo>
    rev: <private version>
    hooks:
      - id: <private hook>
```
