### ISSUE TITLE
pre-commit autoupdate bug?

### ISSUE THREAD

**Issue by uweschmitt** [pre-commit/pre-commit#3224]
### search you tried in the issue tracker

autoupdate

### describe your issue

```
$ venv/bin/pre-commit autoupdate
[https://github.com/tbroadley/spellchecker-cli]
=====> /var/folders/k8/zfp7dvcs1m326gz1brql1tv80000gn/T/tmphs2msd1b/.pre-commit-hooks.yaml is not a file
```

I'm running this on a Mac M1 with Mac OS 14.3.1 (23D60)

### pre-commit --version

pre-commit 3.7.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/tbroadley/spellchecker-cli
    rev: 5c625d2b4686a09981bcf57b17
    hooks:
      - id: spellchecker-cli
        name: spellcheck
        types: [markdown]
        args:
            - '--dictionaries'
            - 'spellchecker-ignore.txt'
            - '--language'
            - 'en-GB'
            - '--plugins'
            - 'spell'
            - 'indefinite-article'
            - 'frontmatter'
            - 'syntax-urls'
            - '--frontmatter-keys'
            - 'title'
            - '--files'
```

### ~/.cache/pre-commit/pre-commit.log (if present)

This error did not create any entry in pre-commit.log
