### ISSUE TITLE
Pre-commit to only apply to staged .swift files

### ISSUE THREAD

**Issue by harrison-phonehub** [pre-commit/pre-commit#3226]
### search you tried in the issue tracker

staged file types

### describe your issue

When running pre-commit, it will attempt to run swiftlint on all files in the staged section on git, such as .sh files or storyboard files.

I have attempted to implement `types: [swift]` and/or `files: \.swift$`, but this then triggers swiftlint to run on ALL files in the project, not just those in the 'staged' section of git.

Is anyone aware of ways to prevent swiftlint running across all .swift files in the project, just only those in the 'staged' section?

### pre-commit --version

pre-commit 3.7.1

### .pre-commit-config.yaml

```yaml
repos:
-   repo: local
    hooks:
    -   id: swiftlint
        name: Swift Linter
        description: Running a linter before commit.
        language: system
        always_run: true
        entry: swiftlint --strict --config swiftlint.yml
        types: [swift]
        files: \.swift$
        stages:
            - pre-commit
```
