### ISSUE TITLE
pre-commit touching files it doesn't actually edit

### ISSUE THREAD

**Issue by rlrosa** [pre-commit/pre-commit#3233]
### search you tried in the issue tracker

touch

### describe your issue

My typical work flow is:

1. open a file with `vim`
2. make changes to the file
3. save the changes
4. when I'm at a point where a commit makes sense use `git add -p` to pick the relevant part of the changes and `git commit -m "something"`. Some changes are left un-committed and un-staged.
5. repeat 2+3 until I'm done

When `pre-commit` runs it seems to `touch` files. I continue editing the file in `vim` and when I try to save I'll face a warning that "the file was modified since I started editing", and I always struggle to remember if it's the hook or if I actually popped/stashes things and should be worried about dropping unsaved changes.

In the cases I'm describing the hook did nothing other than check. That should be a read operation and shouldn't touch the files at all.
Am I missing something?

Thanks

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
# Global excludes:
~frozen code
exclude: '^external|^obsolete'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=1000']      # Default is 500kb, but currently brewst has a 1MB limit and we want to replicate that.
    -   id: check-ast               # Checks whether the files parse as valid python
        exclude: 'template.py$'
    -   id: check-merge-conflict    # checks for the >>> <<<< strings from merge conflicts not resolved
```
