### ISSUE TITLE
Allow using builtin environment variable or exec python code in args for hooks

### ISSUE THREAD

**Issue by thomasbeyens** [pre-commit/pre-commit#3242]
### search you tried in the issue tracker

environment , relative path, path, args, python

### describe your actual problem

I have the following hook in my pre-commit config file:

``` 
- repo: https://github.com/MarketSquare/robotframework-tidy
    rev: 4.8.1
    hooks:
      - id: robotidy
        args: [ --config=tools/pre-commit/pyproject.toml ]
```

In this case, I have to add the path for the --config as an absolute path. We created a submodule for the pre-commit config files, which should be used for all projects in our company. 

The `pyproject.toml` file is thus, always sitting next to the .pre-commit-config.yaml file. Therefore I would like to be able to use something like:

```  
...
        args: [ --config=$(PRE_COMMIT_CFG_PATH)/pyproject.toml ]
```
or even something like the following:

```
...
        args: [ --config=exec('import os; print(os.getcwd())')/pyproject.toml ]
```

Of course this is just one example, I could image this could be used for many other useful operations.

### pre-commit --version

3.6.0
