### ISSUE TITLE
Install additional dependencies from local Python pre-commit hook

### ISSUE THREAD

**Issue by davidrudlstorfer** [pre-commit/pre-commit#3243]
### search you tried in the issue tracker

additional_dependencies, local, python

### Prerequisites

We are currently trying to move custom local code checks (written in Python) within a large educational C++ code project to pre-commit hooks. Based on the [documentation](https://pre-commit.com/#repository-local-hooks), we want to utilize a _local_ pre-commit hook as our code checks are  tightly coupled to the repository.

### Minimal example

The problem/question/bug can be condensed down into the following minimal setup, with an exemplary code project structure looking like this:

```
.
└── pre_commit_test_repo/
    ├── src/
    │   └── utils/
    │       ├── __init__.py
    │       └── test_file.py
    ├── .pre-commit-config.yaml
    └── pyproject.toml
```

The individual files contain the following settings/code:

**__init__.py**

```
"""Init file."""
```

**test_file.py**

```
def main():

    print("Success!")

if __name__ == "__main__":

    main()
```

**.pre-commit-config.yml**

```
repos:
  - repo: local
    hooks:
      - id: test
        name: test
        language: python
        entry: test_file
        additional_dependencies: ['.']
        verbose: true
        always_run: true
```

**pyproject.toml**

```
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Test"
version = "1.0"

[tool.setuptools.packages.find]
where = ["src"]
include = ["utils"]

[project.scripts]
test_file = "utils.test_file:main"
```

### Expected behaviour

We expect that pre-commit simply installs the additional requirements provided as the `pyproject.toml` file. This should initialize the Python `utils` module within the virtual environment of pre-commit

### Outcome

Once we execute `git add .` and `git commit` the following error occurs:

```
test.....................................................................Failed
- hook id: test
- duration: 0s
- exit code: 1

Executable `test_file` not found
```

Unfortunately, after an exhaustive search trough closed issues and the documentation we are not able to solve this problem. Any help would be appreciated. Thanks in advance!

________________

CC @sebproell

### pre-commit --version

pre-commit version: 3.7.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: test
        name: test
        language: python
        entry: test_file
        additional_dependencies: ['.']
        verbose: true
        always_run: true
```
