### ISSUE TITLE
Wrong pip version used

### ISSUE THREAD

**Issue by timothee-dione-evooq** [pre-commit/pre-commit#3248]
### search you tried in the issue tracker

pip

### describe your issue

Hi,
I try running this hook on Ubuntu 23.10, and when I launch the command "pre-commit run", I systematically get the following error:

ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-bolo7r0i/
WARNING: You are using pip version 19.1, however version 20.3.4 is available.

The point is the following:

My current pip version is 23.2
Furtermore, I tried running the command in a virtual environment where I especially updated pip version and the same error appeared following that thread: https://stackoverflow.com/questions/77701033/should-i-install-pre-commit-into-a-python-virtual-environment-or-python-global/77705569#77705569. The result remained the same.
Does someone have an idea on how I can resolve it ?

Thanks

### pre-commit --version

23.2

### .pre-commit-config.yaml

```yaml
---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-d, "{extends: default, rules: {line-length: {max: 140}}}"]
```
