### ISSUE TITLE
Installed hooks with incorrect path names for import

### ISSUE THREAD

**Issue by kharigardner** [pre-commit/pre-commit#3255]
### search you tried in the issue tracker

incorrect path name

### describe your issue

For the `python-poetry` pre-commit hooks, when pre-commit is installing the hooks, it installs the packages in the .cache as

![Capture](https://github.com/user-attachments/assets/c6c4bf3d-7347-4039-8629-1330b8e91687)

This leads to a `ModuleNotFoundError` when running all of the poetry pre commit hooks:

```bash
poetry-lock..............................................................Failed
- hook id: poetry-lock
- exit code: 1

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Khari.Gardner\.cache\pre-commit\repo1l6ix5zp\py_env-python3.11\Scripts\poetry.EXE\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'poetry.console'
```

No matter running `pre-commit gc` or `pre-commit clean`, it will reinstall the hooks, and then upon subsquent run, result in this error.

### pre-commit --version

3.7.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: check-yaml-configs
        name: Check YAML configs
        entry: poetry run python psds_admin/dataops/yaml_compile_test.py
        language: system
        types: [yaml]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-install
        args: [--sync, --with, "dev,docs,iac", -E, datascience]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
  # - repo: https://gitlab.com/iamlikeme/nbhooks
  #  rev: 1.0.0
  #  hooks: this hook is outdated, disable it for now
  #    - id: nb-ensure-clean
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.1.0
    hooks:
      - id: sqlfluff-fix
      - id: sqlfluff-lint
  
default_install_hook_types: 
  - pre-commit
  - post-checkout
  - post-merge
```
