### ISSUE TITLE
Executable `eslint` not found

### ISSUE THREAD

**Issue by glenveegee** [pre-commit/pre-commit#3261]
### search you tried in the issue tracker

is:issue is:open "not found" in:title executable in:title 

### describe your issue

After clearing my local pre-commit cache with `pre-commit clean` and then checking my code with `pre-commit run --all-files`...

The eslint dependency as well as the additional eslint dependencies are pulled down from `mirrors-eslint`

```sh
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-eslint.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-eslint:@typescript-eslint/eslint-plugin@6.11.0,@typescript-eslint/parser@6.11.0,eslint@8.54.0,eslint-config-prettier@9.0.0,eslint-plugin-i18next@6.0.3,eslint-plugin-import@2.29.0,eslint-plugin-prettier@5.0.1,eslint-plugin-storybook@0.6.15,eslint-plugin-unicorn@49.0.0,eslint-plugin-unused-imports@3.0.0,prettier@3.1.0.
...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-eslint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
```
and the eslint hook runs but fails with `Executable 'eslint' not found` as follows:

```sh
eslint...................................................................Failed
- hook id: eslint
- exit code: 1

Executable `eslint` not found
```

This change has happened in the last 3 weeks. It is now failing for completely unchanged code that has been re-run since 21 June 2024 at 17:51:49 BST which is when it last worked without any errors.

### pre-commit --version

pre-commit 3.6.2

### .pre-commit-config.yaml

```yaml
default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.54.0
    hooks:
      - id: eslint
        additional_dependencies:
          - '@typescript-eslint/eslint-plugin@5.59.7'
          - '@typescript-eslint/parser@5.59.7'
          - eslint@8.54.0
          - eslint-config-prettier@8.8.0
          - eslint-plugin-i18next@6.0.0-8
          - eslint-plugin-import@2.27.5
          - eslint-plugin-prettier@5.0.0
          - eslint-plugin-storybook@0.6.11
          - eslint-plugin-unicorn@38.0.1
          - eslint-plugin-unused-imports@2.0.0
          - esquery@1.4.0 # 1.4.1 breaks eslint, so we have to explicitly pin this version
        files: '^my_frontend\/(.*)\.[jt]sx?$'
        types: [file]
        args: ['--parser-options',  '{ tsconfigRootDir: "my_frontend" }', '--fix']
```

**Comment by glenveegee** [comment]
FWIW: There are only two node-like packages in the cache and they look as follows:

**Comment by asottile** [comment]
my guess is a regression in npm, what version did the environment that had one end up with? (it's normal for there to be two and once to not have an env: that's how additional_dependencies works and the initial one is to determine the configuration -- that's not the problem)

**Comment by glenveegee** [comment]
The npm version for the one that had the node env was `v10.8.2`

**Comment by asottile** [comment]
can you try forcing an older one via `language_version` ?  and poking around in the v structure created there to see where that missing binary went?

**Comment by glenveegee** [comment]
Nailed it! It looks like an NPM regression. From my tests:

**Comment by glenveegee** [comment]
Looking at the various language_versions I tried the pre-commit cache looks as follows:

```
ls -1 /Users/irbaboon/.cache/pre-commit/*

/Users/irbaboon/.cache/pre-commit/README
/Users/irbaboon/.cache/pre-commit/db.db
/Users/irbaboon/.cache/pre-commit/pre-commit.log

/Users/irbaboon/.cache/pre-commit/repoc329_tmp:
LICENSE
README.md
node_env-18.20.4
node_env-20.15.1
node_env-22.5.0
node_env-default
package.json

/Users/irbaboon/.cache/pre-commit/repotqv7zcew:
LICENSE
README.md
package.json
```

And when I compare the contents of the bin folder for `node_env-20.15.1` with that of `node_env-22.5.0` I see this...

```
Only in /Users/irbaboon/.cache/pre-commit/repoc329_tmp/node_env-20.15.1/bin: eslint
Only in /Users/irbaboon/.cache/pre-commit/repoc329_tmp/node_env-20.15.1/bin: eslint-config-prettier
Only in /Users/irbaboon/.cache/pre-commit/repoc329_tmp/node_env-20.15.1/bin: prettier
Only in /Users/irbaboon/.cache/pre-commit/repoc329_tmp/node_env-20.15.1/lib/node_modules/@typescript-eslint/eslint-plugin/node_modules: .bin
Only in /Users/irbaboon/.cache/pre-commit/repoc329_tmp/node_env-20.15.1/lib/node_modules/@typescript-eslint/parser/node_modules: .bin
Only in /Users/irbaboon/.cache/pre-commit/repoc329_tmp/node_env-20.15.1/lib/node_modules/eslint/node_modules: .bin
Only in /Users/irbaboon/.cache/pre-commit/repoc329_tmp/node_env-20.15.1/lib/node_modules/eslint-plugin-import/node_modules: .bin
Only in /Users/irbaboon/.cache/pre-commit/repoc329_tmp/node_env-20.15.1/lib/node_modules/eslint-plugin-storybook/node_modules: .bin
Only in /Users/irbaboon/.cache/pre-commit/repoc329_tmp/node_env-20.15.1/lib/node_modules/eslint-plugin-unicorn/node_modules: .bin
Only in /Users/irbaboon/.cache/pre-commit/repoc329_tmp/node_env-20.15.1/lib/node_modules/eslint-plugin-unicorn/node_modules/normalize-package-data/node_modules: .bin
Only in /Users/irbaboon/.cache/pre-commit/repoc329_tmp/node_env-20.15.1/lib/node_modules/eslint-plugin-unicorn/node_modules/regjsparser/node_modules: .bin
Only in /Users/irbaboon/.cache/pre-commit/repoc329_tmp/node_env-20.15.1/lib/node_modules/npm/node_modules: function-bind
Only in /Users/irbaboon/.cache/pre-commit/repoc329_tmp/node_env-22.5.0/lib/node_modules/npm/node_modules/pacote: bin
Only in /Users/irbaboon/.cache/pre-commit/repoc329_tmp/node_env-20.15.1/lib/node_modules/npm/node_modules/pacote/lib: bin.js
```

**Comment by KingMichaelPark** [comment]
Getting a similar executable not found for `biome` which is also installed via npm

**Comment by asottile** [comment]
@glenveegee can you try with other 22.x versions? hoping to nail down which one has the regression but I can't seem to reproduce it on my end yet

**Comment by asottile** [comment]
I believe this is the root cause -- though it's unclear why pre-commit proceeds here.  for me the reproduction of the steps pre-commit _would_ run just hangs forever: https://github.com/nodejs/node/issues/53902

anyway it looks like the workaround is to use `language_version: (anything but 22.5.0)` and there's not much pre-commit can do here about a breakage coming from nodejs itself 😆

**Comment by kratsg** [comment]
Sorry to necro this issue again, but I found rather (unexpected?) behavior. The following configuration gives me the original issue

```
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.39.1"
    hooks:
      - id: eslint
        language_version: "22.4.1"
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
```

and it is true that there no `eslint` executable under `/bin` If I explicitly add the following:

```
additional_dependencies:
    - eslint
```

then the executable shows up. Is there maybe an issue with the hook configuration? (I ran `pre-commit clean` in between)


```
/Users/kratsg/.cache/pre-commit/reporq_5fp6e/node_env-22.4.1/bin:
total 109M
drwxr-xr-x 12 kratsg  384 Jan  7 12:52 ./
drwxr-xr-x  8 kratsg  256 Jan  7 12:52 ../
-rwxr-xr-x  1 kratsg 3.8K Jan  7 12:52 activate
-rwxr-xr-x  1 kratsg 4.3K Jan  7 12:52 activate.fish
lrwxr-xr-x  1 kratsg   45 Jan  7 12:52 corepack -> ../lib/node_modules/corepack/dist/corepack.js
lrwxr-xr-x  1 kratsg   40 Jan  7 12:52 eslint -> ../lib/node_modules/eslint/bin/eslint.js
lrwxr-xr-x  1 kratsg   53 Jan  7 12:52 eslint-config-prettier -> ../lib/node_modules/eslint-config-prettier/bin/cli.js
-rwxr-xr-x  1 kratsg 109M Jul  8  2024 node
lrwxr-xr-x  1 kratsg    4 Jan  7 12:52 nodejs -> node
lrwxr-xr-x  1 kratsg   38 Jan  7 12:52 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxr-xr-x  1 kratsg   38 Jan  7 12:52 npx -> ../lib/node_modules/npm/bin/npx-cli.js
-rwxr-xr-x  1 kratsg  375 Jan  7 12:52 shim
```
