### ISSUE TITLE
While Performing Powershell linting using Pre-commit through hook 'PSScriptanalyzer' I am getting below error: Invoke-ScriptAnalyzer : A positional parameter cannot be found that accepts argument 

### ISSUE THREAD

**Issue by Shubhij12** [pre-commit/pre-commit#3268]
### search you tried in the issue tracker

Psscriptanalyzer

### describe your issue

This is reference to below: since it was wrongly created under different repo.

While Performing Powershell linting using Pre-commit through hook 'PSScriptanalyzer' I am getting below error: Invoke-ScriptAnalyzer : A positional parameter cannot be found that accepts argument #1070

I have Installed PSScriptAnalyzer module in my local and while plugin it with precommit i have given below config file:
While i am passing multiple ps1 files, getting below error. For Single file its executing correctly.

Please find following Config file

### pre-commit --version

pre-commit 3.7.1

### .pre-commit-config.yaml

```yaml
repo: local
hooks:
id: PSScriptAnalyzer
name: PSScriptAnalyzer
description: Run PSScriptAnalyzer on commit
language: system
entry: powershell -NoProfile -NonInteractive -Command Invoke-ScriptAnalyzer -EnableExit -Path
files: ^.*.ps1$
pass_filenames: true
```
