### ISSUE TITLE
`Duplicate module` between `.py` and `.pyi` stub in mypy

### ISSUE THREAD

**Issue by ZhiyuanChen** [pre-commit/pre-commit#3269]
### search you tried in the issue tracker

Duplicate module mypy stub

### describe your issue

```
feishu/im/messages.pyi: error: Duplicate module named "feishu.im.messages" (also at "feishu/im/messages.py")
feishu/im/messages.pyi: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
feishu/im/messages.pyi: note: Common resolutions include: a) using `--exclude` to avoid checking one of them, b) adding `__init__.py` somewhere, c) using `--explicit-package-bases` or adjusting MYPYPATH
Found 1 error in 1 file (errors prevented further checking)
```

### pre-commit --version

pre-commit 3.7.1

### .pre-commit-config.yaml

```yaml
default_language_version:
  python: python3
repos:
  - repo: https://github.com/PSF/black
    rev: 24.3.0
    hooks:
      - id: black
        args: [--safe, --quiet]
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--keep-runtime-typing]
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 1.7.0
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
        # exclude: '**/*.pyi'
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: [--ignore-words=.codespell-whitelist.txt]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-symlinks
      - id: pretty-format-json
      - id: check-json
      - id: check-xml
      - id: check-toml
      - id: check-yaml
        files: "feishu"
      - id: debug-statements
      - id: end-of-file-fixer
        files: "feishu"
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
```
