### ISSUE TITLE
No output for docker_image hooks on WSL

### ISSUE THREAD

**Issue by sanzoghenzo** [pre-commit/pre-commit#3276]
### search you tried in the issue tracker

wsl, output, docker_image

### describe your issue

If I run pre-commit hooks that uses docker_image, such as trivy and hadolint, inside a WSL (ubuntu 22,04), I only get the exit status, but no error messages are shown.

```
trivyfs-docker...........................................................Failed
- hook id: trivyfs-docker
- exit code: 1
trivyconfig-docker.......................................................Failed
- hook id: trivyconfig-docker
- exit code: 1
Lint Dockerfiles.........................................................Failed
- hook id: hadolint-docker
- exit code: 1
```

Running the same pre-commit config directly on windows works fine.

Running the docker manually works with `docker run --rm -i -v ${PWD}:/src ghcr.io/hadolint/hadolint hadolint /src/Dockerfile`.
If I remove the `-i` flag (I did a quick check to the code, and it seems it is not used) nothing shows up. May this be the issue?

One thing I should mention, I'm using Rancher Desktop instead of Docker Desktop to provide docker to both windows and WSL distributions.

### pre-commit --version

3.7.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/mxab/pre-commit-trivy.git
    rev: v0.12.0
    hooks:
      - id: trivyfs-docker
        args: [--skip-dirs, ./tests, .]
      - id: trivyconfig-docker
        args: [--skip-dirs, ./tests, .]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
```
