### ISSUE TITLE
Include other config files

### ISSUE THREAD

**Issue by pkaeding** [pre-commit/pre-commit#3281]
### search you tried in the issue tracker

include config files

### describe your actual problem

I want to have a global set of precommit hooks, and per-repo hooks.  I want the global set to run on all commits I make, regardless of the repo, and then I want the local ones to run (if configured). 

This kind of works, in the global config (configured as the global with `git config --global core.hooksPath /path/to/global-hooks`):

```
repos:
  - repo: local
    hooks:
      - ... global hooks configured here
      - id: include-local
        name: include-local
        description: Check for repo-local pre-commit hook
        entry: |
          bash -c 'if [ -e ./.git/hooks/pre-commit ]; then
              exec ./.git/hooks/pre-commit 
          fi'
        language: system
        stages: ["commit"]
```

However, the 'include-local' hook returns no output until the whole set of local hooks is done running. I believe this is because this top-level hook needs to know when it is done running to decide if it passed or failed.

Is there a better way? If not, I'd like to request a better way to solve this use-case.

### pre-commit --version

pre-commit 3.7.1
