### ISSUE TITLE
Run just one hook when two or more hooks have the same id

### ISSUE THREAD

**Issue by notatallshaw-gts** [pre-commit/pre-commit#3288]
### search you tried in the issue tracker

"same id"

### describe your actual problem

I have two separate situations where this comes up, but both can be described as "runs the same hook from the same repo with different configuration".

One is where I have overlapping files but I have different configuration, e.g.

```yaml
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.3
  hooks:
    -   id: ruff
        args: ["--select", "E"]
        name: Ruff Errors
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.3
  hooks:
    -   id: ruff
        args: ["--select", "UP"]
        name: Ruff Upgrades
```

And the other is where I am in a monorepo context and I have two different teams that have different config based on different files:

```yaml
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.3
  hooks:
    -   id: ruff
        name: Ruff (mono1)
        args: ["--config", "ruff.mono1.toml"]
        files: "mono1pattern"
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.1
  hooks:
    -   id: ruff
        name: Ruff (mono2)
        args: ["--config", "ruff.mono2.toml"]
        files: "mono2pattern"
```

This works great locally, but during CI pipeline I want to be able to selectively just run and report on the results from "Ruff Errors" or "Ruff (mono2)", so that I can clearly name the CI jobs and failures, and decide whether to run the next step in the pipeline or not.

If I am reading all the issues and docs correctly it appears that if two or more hooks have the same id I must run all hooks with that id? And that I can't select a specific hook based on anything else? And there's no way to change the id that I get from the external repo? Let me know if I am wrong though.

### pre-commit --version

pre-commit 3.8.0
