### ISSUE TITLE
Install prebuilt node failed to download

### ISSUE THREAD

**Issue by ToddEricksonCR** [pre-commit/pre-commit#3291]
### search you tried in the issue tracker

Install prebuilt node (v16.14.0) .Failed to download from https://nodejs.org/download/release/vv16.14.0/node-vv16.14.0-darwin-x64.tar.gz

### describe your issue

I am trying to run pre-commit on a node project on my Intel Mac and getting:
stderr:
     * Install prebuilt node (v16.14.0) .Failed to download from https://nodejs.org/download/release/vv16.14.0/node-vv16.14.0-darwin-x64.tar.gz
 *Note:* It looks like there is an extra v in the node version but I can't figure out why.

### pre-commit --version

pre-commit 3.8.0

### .pre-commit-config.yaml

```yaml
#fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed (500kB)
      - id: check-byte-order-marker # Forbid files which have a UTF-8 byte-order marker
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-docstring-first # Checks a common error of defining a docstring after code.
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: check-toml # This hook checks toml files for parseable syntax.
      - id: check-yaml # This hook checks yaml files for parseable syntax.
        args:
        - --unsafe
      - id: detect-aws-credentials # Detects *your* aws credentials from the aws cli credentials file
        args:
        - --allow-missing-credentials
      - id: detect-private-key # Detects the presence of private keys
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline.
        exclude: '^appscript/'
      - id: mixed-line-ending # Replaces or checks mixed line ending
      - id: no-commit-to-branch # Don't commit to branch
      - id: trailing-whitespace # This hook trims trailing whitespace.
        args: ["--markdown-linebreak-ext=md"]
        files: ".js"
  # eslint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.29.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.29.0
          - eslint-config-airbnb-base@15.0.0
        exclude: '^appscript/'
```

### ~/.cache/pre-commit/pre-commit.log (if present)

[pre-commit.log](https://github.com/user-attachments/files/16935609/pre-commit.log)
