### ISSUE TITLE
there is no access to commit_msg_filename in prepare-commit-msg hook

### ISSUE THREAD

**Issue by twistfire92** [pre-commit/pre-commit#3292]
### search you tried in the issue tracker

prepare-commit-msg

### describe your issue

I trying to create a pre-commit-msg hook and expect to have access to commit_msg_filename. But all I have is `PRE_COMMIT_COMMIT_MSG_SOURCE` and `PRE_COMMIT_COMMIT_OBJECT_NAME ` environment variables.

As we know from [prepare-commit-msg docs](https://git-scm.com/docs/githooks#_prepare_commit_msg), The first parameter is the name of the file that contains the commit log message.

But we don't have access to this parameter.

I suggest to expose PRE_COMMIT_COMMIT_MSG_FILENAME to the hook.

### pre-commit --version

pre-commit 3.6.0

### .pre-commit-config.yaml

```yaml
default_install_hook_types: [pre-commit, prepare-commit-msg]
repos:
  - repo: ../hook-repo
    rev: 9170a4f8247593825da53a53a931d167e8553d55
    hooks:
      - id: foo
        verbose: true
```
