### ISSUE TITLE
Pre-push hook skipped when pushing only a new branch

### ISSUE THREAD

**Issue by kilbouri** [pre-commit/pre-commit#3296]
### search you tried in the issue tracker

is:issue is:open push

### describe your issue

I was attempting to create a pre-push hook that would prevent me from pushing any branch with `temp/` in the name, the format I use when I create a local-only branch (e.g. to save working state before checking out another branch). I don't even want to be able to _create_ such a branch on the remote, which I could using simply `git switch -c "temp/foo" && git push`.

After a lot of trial and error, and a bit of source reading, I *think* have narrowed it down to an empty `ancestors` output in [_pre_push_ns](https://github.com/pre-commit/pre-commit/blob/main/pre_commit/commands/hook_impl.py#L144). For example, I wrote a simple script to observe what the hook would receive on `stdin` and got this:
`refs/heads/temp 4cde358b7457b1fafc361c6e50c5e4947be0a41c refs/heads/temp 0000000000000000000000000000000000000000`. Manually tracing the source code, I end up running
`git rev-list 4cde358b7457b1fafc361c6e50c5e4947be0a41c --topo-order --reverse --not --remotes=origin` which yields no output.

I'm sure there's good reason for this case not running the hook, I just wish this worked.

### pre-commit --version

pre-commit 3.8.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: no-push-temp-branch
        name: no-push-temp-branch
        entry: sh -c "echo 'HELLO!' && exit 1" # I got very desperate
        language: system
        always_run: true
        pass_filenames: false
```
