### ISSUE TITLE
`pre-commit run` installs environment when seemingly already installed

### ISSUE THREAD

**Issue by injust** [pre-commit/pre-commit#3297]
### search you tried in the issue tracker

"installs environment"

### describe your issue

I have pre-commit installed in my repo. When I commit, all the hooks run (their environments were already installed).

But when I do `pre-commit run`, it installs the environments _again_, before running the hooks. Should pre-commit be using the same environment for both ways of running the hooks?

### pre-commit --version

pre-commit 3.8.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: [--py312-plus]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: [--disable-error-code=import-untyped]
        additional_dependencies:
          [
            anyio,
            APScheduler @ git+https://github.com/agronholm/apscheduler@master,
            attrs,
            httpx,
            loguru,
            packaging,
            tenacity,
          ]
```
