### ISSUE TITLE
automatically enabling pre-commit on repositories

### ISSUE THREAD

**Issue by isnethub** [pre-commit/pre-commit#3298]
### search you tried in the issue tracker

automatically enabling pre-commit on repositories

### describe your issue

Hello, I have tried to implement the `automatically enabling pre-commit on repositories` in a Docker, but it fails to work and cannot tell what I am missing:

Docker (related commands only):
```bash
RUN pip3 install pre-commit
ENV DIR=/usr/local/share/git-template
RUN mkdir -p ${DIR}
RUN git config --system init.templateDir ${DIR}
RUN pre-commit init-templatedir ${DIR}
```
1. I have multiple repositories each with different configuration file. A sample is provided.
2. I was expecting, cloning a repository containing a config file `.pre-commit-config.yaml` will automatically initialize the repository for the pre-commit, but this is not working.
3. I have tried `RUN git config --global init.templateDir ${DIR}`, same results.

NOTE: This might not be an issue, but I could not find the forum to post it, sorry for any inconvenience.

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-isort
        args: ["--max-line-length=110", "--ignore=E266,W503"]

-   repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
      - id: yapf

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
    - id: mypy
      args: [--ignore-missing-imports, --show-column-numbers]

- repo: https://github.com/pycqa/pylint
  rev: v2.14.5
  hooks:
  -   id: pylint
      args: ["--rcfile=pylintrc"]
```
