### ISSUE TITLE
Data loss footgun with parallel execution

### ISSUE THREAD

**Issue by dansimau** [pre-commit/pre-commit#3303]
### search you tried in the issue tracker

Yes

### describe your issue

I just lost my work.

* I cloned a repo that uses pre-commit
* Made some changes
* Then ran `git commit`. Several of the linters I am running reported issues.
* When I fixed the issues and re-ran my tests, I was dismayed to find several files I was working on were 0 bytes.

What happened?

```
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        types: [python]
        entry: poetry run black .
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        types: [python]
        entry: poetry run isort .
```

Can you spot the issue?

From what I'm able to deduce this afternoon:

* pre-commit runs hooks in parallel by default
* In order to provide some safety for hooks that may write to files, pre-commit chunks filenames and passes them to the hook
* The person writing the configuration above did not know this and instead passed `.` which caused the hook to run on all files
* Two hooks wrote to the same files at the same time

I understand this is a misconfiguration, but it is an easy mistake to make.

Some ideas on how we could help people avoid data loss:

* Make parallel execution opt-in
* Detect a lone `.` argument in `entry` or arguments that match top level files/directories and bail unless `pass_filenames` is explicitly set to `False`
* Put a warning in the documentation. Today there is nothing on https://pre-commit.com/ that even mentions hooks are run in parallel or how parallel execution works
* `pass_filenames=True` implicitly sets `require_serial=True` unless overridden
* Detect and warn on combination of `require_serial=False` and `pass_filenames=False`

### pre-commit --version

3.7.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        types: [python]
        entry: poetry run black .
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        types: [python]
        entry: poetry run isort .
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        language: system
        types: [python]
        entry: poetry run flake8
```
