### ISSUE TITLE
`types_or: [jupyter]` is ignored when used with `post-rewrite` and `always_run: True`

### ISSUE THREAD

**Issue by Lhenzo** [pre-commit/pre-commit#3306]
### search you tried in the issue tracker

yes

### describe your issue

I use https://github.com/astral-sh/ruff-pre-commit and the preview feature for pycodestyle like such:
```yaml
      - id: ruff
        alias: ruff-nb-pycodestyle
        name: ruff | check for E and W errors on notebooks and fix them
        args: [--fix, --exit-non-zero-on-fix, --preview, --select, "E,W"]
        types_or: [jupyter]
```

Runs fine and return `Skipped` when no jupyter notebooks were modified. 
But adding

```yaml
        stages: [pre-commit, post-rewrite, manual]
        always_run: True
```

Makes it run always (that's what I want) but on all files (I only want to target jupyter notebooks).

I've tried:
1. change types_or to types
2. try other types

Any idea what is going on?

Thank you a lot!

### pre-commit --version

pre-commit==3.8.0

### .pre-commit-config.yaml

```yaml
- repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        alias: ruff-py
        name: ruff-py | run ruff linter on python files
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python]
        exclude: ^notebook/

      - id: ruff
        alias: ruff-pycodestyle
        name: ruff | check for E and W errors on python files and fix them
        args: [--fix, --exit-non-zero-on-fix, --preview, --select, "E,W"]
        types_or: [python]
        exclude: ^notebook/

      - id: ruff
        alias: ruff-nb
        name: ruff-nb | run ruff linter on notebooks
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [jupyter]

      - id: ruff
        alias: ruff-nb-pycodestyle
        name: ruff | check for E and W errors on notebooks and fix them
        args: [--fix, --exit-non-zero-on-fix, --preview, --select, "E,W"]
        stages: [pre-commit, post-rewrite, manual]
        always_run: True
        types_or: [jupyter]
```
