### ISSUE TITLE
--all-files ignores exclude_types

### ISSUE THREAD

**Issue by rkingsbury** [pre-commit/pre-commit#3309]
### search you tried in the issue tracker

Yes

### describe your issue

I want to run the `pretty-format-json` hook on _only_ .json files, but not .ipynb files (which `identify` consider .json files, since that's the underlying format)

I have the following filter in my `pre-commit-config.yaml`, but when I run `pre-commit run --all-files`, jupyter notebooks are still formatted.

```
      - id: pretty-format-json
        exclude_types: [jupyter]
```

Note that _it appears_ this is because I'm using `--all-files`, but I can't find this behavior documented anywhere. My expectation was that `--all-files` would run on all files in the repo _that match the filters specified in the config file_ (as opposed to just those being staged for commit), not every single file, regardless of filters. Am I just misunderstanding?

Noting some related discussion:
[python regex for file extension](https://github.com/pre-commit/pre-commit-hooks/pull/937)
https://github.com/pre-commit/identify/pull/401

### pre-commit --version

3,7.1

### .pre-commit-config.yaml

```yaml
exclude: "^docs/conf.py"

default_stages: [commit]

default_install_hook_types: [pre-commit, commit-msg]

ci:
  autoupdate_schedule: monthly
  # skip: [mypy]
  autofix_commit_msg: pre-commit auto-fixes
  autoupdate_commit_msg: pre-commit autoupdate

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      - id: ruff
        args: [--fix, --ignore, "D,E501", "--show-fixes"]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        stages: [commit, commit-msg]
        exclude_types: [html, svg, json, csv]
        additional_dependencies: [tomli] # needed to read pyproject.toml below py3.11

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude_types: [json] #TODO:re-enabling json
      - id: mixed-line-ending
        exclude_types: [svg]
      - id: trailing-whitespace
        exclude_types: [svg]
      - id: check-yaml
      - id: pretty-format-json
        exclude_types: [jupyter]
```

### ~/.cache/pre-commit/pre-commit.log (if present)

Not present
