### ISSUE TITLE
Does not install custom cargo versions with language: rust

### ISSUE THREAD

**Issue by benediktsatalia** [pre-commit/pre-commit#3319]
### search you tried in the issue tracker

Rust install custom cargo

### describe your issue

When one uses `language: rust` together with `language_version: ...` the right version is not available when running the hook. This results in an error if we force the version using `cargo +version ...`.

Steps to reproduce:

```
mkdir new-repo
cd new-repo
cargo init
```

Then create `.pre-commit-config.yaml` with the following content:

```
repos:
  - repo: local
    hooks:
      - id: check-1.77
        name: check-1.77
        entry: cargo +1.77 check
        language: rust
        language_version: "1.77"
        pass_filenames: false
        types_or: [rust, toml]
```

Make sure to use a version you have not installed already locally, so check that `cargo +1.77 check` fails locally.

```
git add src
pre-commit run
```

This results in the following error:

```
check-1.77...............................................................Failed
- hook id: check-1.77
- exit code: 1

error: toolchain '1.77-x86_64-unknown-linux-gnu' is not installed
```

which should not happen since pre-commit should install the appropriate toolchain.

I tried to debug this a bit by looking at the code of this repo and I think the problem is that `rustup toolchain install` installs the toolchain to the directory specified via the `RUSTUP_HOME` variable which is set [to a temporary directory that gets released immediatly after installing the toolchain](https://github.com/pre-commit/pre-commit/blob/a2f7b80e8952594985e2719d0d12cb194a5e855e/pre_commit/languages/rust.py#L85C52-L85C63) (so the whole directory gets cleaned afterwards and not reused). So we end up spending time installing the toolchain into a temporary directory that is not used anywhere else anymore.

### pre-commit --version

pre-commit 3.6.2

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: check-1.77
        name: check-1.77
        entry: cargo +1.77 check
        language: rust
        language_version: "1.77"
        pass_filenames: false
        types_or: [rust, toml]
```
