### ISSUE TITLE
Customizing `actions/cache` key in `pre-commit/action`

### ISSUE THREAD

**Issue by jamesbraza** [pre-commit/pre-commit#3331]
### search you tried in the issue tracker

is:issue cache override

### describe your actual problem

I use https://github.com/pre-commit/action, `uv`, and this https://github.com/pre-commit/mirrors-mypy:

```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - dep-1
          - dep-2
          - ...
```

I also have a `uv.lock` that I use for local development.

I would like to be able to couple the `pre-commit/action`'s `actions/cache` key to a hash of `uv.lock`: https://github.com/pre-commit/action/blob/v3.0.1/action.yml#L18

Is there some way we can expose a cache key suffix as one of the `inputs` to the `pre-commit/action`? Would you be willing to accept a PR for this?

### pre-commit --version

pre-commit 4.0.1
