### ISSUE TITLE
Automatically re-run a hook on all files when certain files are changed

### ISSUE THREAD

**Issue by jonsim** [pre-commit/pre-commit#3337]
### search you tried in the issue tracker

run on all files when changed, config file changes, --all-files

### describe your actual problem

Imagine a pre-commit config that runs a single linter in a hook (e.g. pylint). It is possible to 'break' the repo's adherence to the linter by changing it's config file (e.g. `.pylintrc`) but forgetting to run `pre-commit run --all-files pylint`. This is also difficult to catch in an automated run without always running with `--all-files`, which can be slow.

One simple solution to this problem would be to add a new option to the hook mapping (e.g. `run_all_when_changed`). This option would take a regex and, when any changed file matches the regex, re-run the hook on all matching files, equivalent to `--all-files`. I envisage this to be used as:
```
repos:
-   repo: <whatever>
    rev: v1.2.3
    hooks:
    -   id: some-linter
        files: '\.py$'
        run_all_when_changed: '^\.some-linter\.cfg$'
```

Does that seem reasonable? I'm surprised this hasn't been requested before, but I've searched everything I can think of and turned up nothing. I'm very happy to submit a PR, but I assume adding new config options is not done lightly.

### pre-commit --version

pre-commit 4.0.1
