### ISSUE TITLE
Security enhancement: Add hash verification for hook installations

### ISSUE THREAD

**Issue by youtux** [pre-commit/pre-commit#3343]
### search you tried in the issue tracker

hash freeze security

### describe your actual problem

Currently, specifying pre-commit hooks using tags instead of git hashes can pose a security risk if a package is hijacked and the tag is rewritten.

Proposal:
Implement a hash verification system similar to other package managers (pip, poetry, cargo, npm) by:
1. Adding an optional `hash` field in the configuration:
  ```yaml
  - repo: "https://github.com/asottile/pyupgrade"
    rev: "v3.15.2"
    hash: "12af25eb252deaaecb6b259df40d01f42e716dc3"
    hooks:
      - id: "pyupgrade"
  ```
2. Maintaining current `rev` field semantics.
3. Throwing an error if the `hash` doesn't match the git hash of the checked-out revision.
This enhancement would significantly improve security while maintaining compatibility with existing configurations.
Would the pre-commit team consider implementing this feature?

### pre-commit --version

pre-commit 4.0.1
