### ISSUE TITLE
If multiple projects a tracked in a repo `pre-commit autoupdate` can switch to a different project's tag

### ISSUE THREAD

**Issue by bbannier** [pre-commit/pre-commit#3349]
### search you tried in the issue tracker

sort:updated-desc is:issue autoupdate best

### describe your actual problem

Currently `pre-commit autoupdate` switches to the first most recent "version-like" tag in a repo, https://github.com/pre-commit/pre-commit/blob/9da45a686ab3959488020382abf897d6b9418d05/pre_commit/git.py#L239-L244

This works deterministically. If however multiple projects are tracked in the same repo with their own release tags this can lead to switching from one project tag to another one's on `autoupdate`, e.g., https://github.com/crate-ci/typos tracks both [`typos-dict`](https://crates.io/crates/typos-dict) as well as [`typos-cli`](https://crates.io/crates/typos-cli) (exposed as `typos` pre-commit hook) in the same repo; GH releases are only created for `typos-cli` tags. Not every release of `typos-cli` coincides with a `typos-dict` release, so that e.g., upgrading from

```yaml
  - repo: https://github.com/crate-ci/typos
    rev: v1.27.0
    hooks:
      - id: typos
```

would today autoupdate to

```yaml
  - repo: https://github.com/crate-ci/typos
    rev: typos-dict-v0.11.34
    hooks:
      - id: typos
```

If a future release of `typos-cli` does not coincide with a `typos-dict` release the rev could switch to `vA.B.C` again. This not only introduces churn, but also makes it harder to see what version upgrade actually happened.

One way to address this could be to take the previous rev into account in `get_best_candidate_tag`, e.g., by passing a `prev_tag: Optinal[str] = None`. If this is present we could return a new tag which best matches the previous one, e.g., by using the one with the longest prefix match.

### pre-commit --version

pre-commit 4.0.1
