### ISSUE TITLE
`stages: [pre-push, manual]` disables a hook when running `pre-commit run --all-files`

### ISSUE THREAD

**Issue by cclauss** [pre-commit/pre-commit#3350]
### search you tried in the issue tracker

manual stage disabled

### describe your issue

We want a slow-running hook to run only on pre-push, not pre-commit so we set `stages: [pre-push, manual]`.  However, the hook is, unfortunately, ___not___ run on `pre-commit run --all-files`.  This also means the hook will never be run on pre-commit.ci.

Let's use `trailing-whitespace` to simulate that hook...
% `git checkout master`
```
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
```
% `git pull`
```
Already up to date.
```
`# We want a slow-running hook to run only on pre-push and not on pre-commit.`
% `pre-commit install --install-hooks --hook-type pre-commit --hook-type pre-push`
```
pre-commit installed at .git/hooks/pre-commit
pre-commit installed at .git/hooks/pre-push
```
% `git checkout -b pre-commit-trailing-whitespace-test`
```
Switched to a new branch 'pre-commit-trailing-whitespace-test'
```
% `pre-commit autoupdate`
```
[https://github.com/pre-commit/pre-commit-hooks] already up to date!
```
% `cat .pre-commit-config.yaml`
```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-push, manual]  # <-- Note this configuration.
```
% `pre-commit run --all-files`  # Bad: The hook is not run on manual invocation.

---

% `echo "trailing whitespace line 1    " > trailing_whitespace.txt`
% `git add trailing_whitespace.txt`
% `git commit -am "Add trailing whitespace line 1"`  # Good: pre-commit hook does not run.
```
[pre-commit-trailing-whitespace-test 7c2e68d] Add trailing whitespace line 1
 1 file changed, 1 insertion(+)
 create mode 100644 trailing_whitespace.txt
```
% `echo "trailing whitespace line 2    " >> trailing_whitespace.txt`
% `git commit -am "Add trailing whitespace line 2"`  # Good: pre-commit hook does not run.
```
[pre-commit-trailing-whitespace-test 955363d] Add trailing whitespace line 2
 1 file changed, 1 insertion(+)
```
% `cat trailing_whitespace.txt`
```
trailing whitespace line 1
trailing whitespace line 2
```
% `pre-commit run --all-files`  # Bad: The hook is not run on manual invocation.
% `git push`  # Good: The hook runs on pre-push.
```
trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing trailing_whitespace.txt
```
% `git commit -am "pre-commit run --all-files"`  # Good: pre-commit hook does not run.
```
[pre-commit-trailing-whitespace-test 2bc7880] pre-commit run --all-files
 1 file changed, 2 insertions(+), 2 deletions(-)
```
% `git push`  # Good: The hook runs on pre-push.
```
trim trailing whitespace.................................................Passed
```

---

### pre-commit --version

pre-commit 4.0.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-push, manual]  # <-- Note this configuration.
```
