### ISSUE TITLE
how to specify entry relative to hook's parent repo, not the repo invoking it

### ISSUE THREAD

**Issue by atloo1** [pre-commit/pre-commit#3352]
### search you tried in the issue tracker

relative path, bash hook

### describe your issue

I'm trying to implement my own Bash script `pre-commit` hook. I have 3 files in 2 repos.

`my-pre-commit-hook/.pre-commit-hooks.yaml`:
```
- id: my-pre-commit-hook
  name: my-pre-commit-hook
  description: retcode 0
  entry: bash /absolute/path/to/my-pre-commit-hook/hook.sh
  language: system
```

`my-pre-commit-hook/hook.sh`:
```
#!/bin/bash
exit 0
  ```

`use-my-pre-commit-hook/.pre-commit-config.yaml`:
```
repos:
  - repo: /absolute/path/to/my-pre-commit-hook
    rev: latest_my-pre-commit-hook_commit_hash
    hooks:
    - id: my-pre-commit-hook
```

This will become remote, so I want `.pre-commit-hooks.yaml` to use paths relative to the parent repo, e.g.`/absolute/path/to/my-pre-commit-hook/hook.sh` → `./hook.sh`. However, this gives:
```
- exit code: 127

/usr/bin/bash: ./hook.sh: No such file or directory
```

### pre-commit --version

4.0.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: /absolute/path/to/my-pre-commit-hook
    rev: latest_my-pre-commit-hook_commit_hash
    hooks:
    - id: my-pre-commit-hook
```

### ~/.cache/pre-commit/pre-commit.log (if present)

/usr/bin/bash: ./hook.sh: No such file or directory
