### ISSUE TITLE
unnecessary files during file tracing 

### ISSUE THREAD

**Issue by oleg14038** [pre-commit/pre-commit#3354]
### search you tried in the issue tracker

https://github.com/pre-commit/pre-commit/issues/new?assignees=&labels=&projects=&template=00_bug.yaml

### describe your issue

I'm sorry, when switching to a new version of pre-commit, it checks for unnecessary files during file tracing 
How can I fix this?

   Traceback (most recent call last):
          File "/home/oleg/.cache/pre-commit/repo5f3iojsg/py_env-python3/lib/python3.12/site-packages/pre_commit_hooks/debug_statement_hook.py", line 57, in check_file
            ast_obj = ast.parse(f.read(), filename=filename)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/home/oleg/miniconda3/lib/python3.12/ast.py", line 52, in parse
            return compile(source, filename, mode, flags,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### pre-commit --version

pre=commit - 

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/PyCQA/docformatter
    rev: "eb1df347edd128b30cd3368dddc3aa65edcfac38"
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-descriptions=79, --style=google]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: "v3.1.0"
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/psf/black.git
    rev: "24.10.0"
    hooks:
      - id: black
  - repo: https://github.com/mwouts/jupytext
    rev: v1.14.1
    hooks:
     - id: jupytext
       entry: jupytext --to py *.ipynb
       language: python
       types: [jupyter]
       args:
         - --from=ipynb
         - --to=py:percent
         - --pipe=black
         - --pipe=isort - --profile black --filter-files
         - --opt=notebook_metadata_filter=-kernelspec
         - --sync
         - --pre-commit
         - --paired-paths
       additional_dependencies:
         - black==22.10.0
         - isort==5.11.5
       exclude: '.*\.md$'
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.0
    hooks:
      - id: nbqa-black
        name: nbqa-black
        description: Run 'black' on a Jupyter Notebook
        entry: nbqa black
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies: [black]
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.19.0"
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/pycqa/isort
    rev: "5.13.2"
    hooks:
      - id: isort
        args:
          - --check
          - --float-to-top
  - repo: https://github.com/nbQA-dev/nbQA
    rev: "1.9.0"
    hooks:
      - id: nbqa
        entry: nbqa blacken-docs
        name: nbqa-blacken-docs
        alias: nbqa-blacken-docs
        additional_dependencies: [blacken-docs]
        args:
          - --nbqa-md
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.0
    hooks:
      - id: nbqa-pyupgrade
        name: nbqa-pyupgrade
        description: Run 'pyupgrade' on a Jupyter Notebook
        entry: nbqa pyupgrade
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies: [pyupgrade]
      - id: nbqa-isort
        name: nbqa-isort
        description: Run 'isort' on a Jupyter Notebook
        entry: nbqa isort
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies: [isort]
        args:
          - --check
          - --float-to-top

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        args:
          - --ignore-regex=^\s*"image\/(jpeg|png|gif|bmp|tiff)":\s.*
          - --ignore-regex=[A-Za-z0-9+/]{100,}
          - --skip=*.js,*.html,*.css,*.svg",*.json,*.png,*.jpg,*.yml,*.yaml
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.0
    hooks:
      - id: nbqa-flake8
        args:
          - --ignore=E501,E712,W291,F632,E203,F821,F403,W391
          - --exclude=.*,__init__.py
        name: nbqa-flake8
        description: Run 'flake8' on a Jupyter Notebook
        entry: nbqa flake8
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies:
          - flake8-variables-names
          - pep8-naming
          - flake8-functions-names

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          - --ignore=E501,E712,W291,F632,E203,F821,F403,W391
          - --exclude=.*,__init__.py
        additional_dependencies:
          - flake8-variables-names
          - pep8-naming
          - flake8-functions-names

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.0
    hooks:
      - id: nbqa-mypy
        name: nbqa-mypy
        description: Run 'mypy' on a Jupyter Notebook
        entry: nbqa mypy
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies:
          - mypy
          - pandas-stubs
          - git+https://github.com/numpy/numpy-stubs
          - mypy-extensions
          - types-requests
          - types-PyYAML
          - types-setuptools

        args:
          # - --cache-dir=/dev/null
          # - --cache-dir=nul
          # - --no-incremental
          - --non-interactive
          - --install-types
          - --explicit-package-bases
          - --ignore-missing-imports
          - --disallow-untyped-calls
          - --disallow-untyped-defs
          - --disallow-untyped-decorators
          - --strict
          - --extra-checks
          - --disallow-any-decorated
          - --disallow-any-generics
          - --local-partial-types
          - --pretty
          - --force-uppercase-builtins
          - --force-union-syntax
          - --warn-unreachable
          - --warn-redundant-casts
          - --warn-return-any
          - --disallow-any-explicit



  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args:
          # - --cache-dir=/dev/null
          # - --cache-dir=nul
          # - --no-incremental
          - --non-interactive
          - --install-types
          - --explicit-package-bases
          - --ignore-missing-imports
          - --disallow-untyped-calls
          - --disallow-untyped-defs
          - --disallow-untyped-decorators
          - --strict
          - --extra-checks
          - --disallow-any-decorated
          - --disallow-any-generics
          - --local-partial-types
          - --pretty
          - --force-uppercase-builtins
          - --force-union-syntax
          - --warn-unreachable
          - --warn-redundant-casts
          - --warn-return-any
          - --disallow-any-explicit


        additional_dependencies:
          - mypy
          - pandas-stubs
          - git+https://github.com/numpy/numpy-stubs
          - mypy-extensions
          - types-requests
          - types-PyYAML
          - types-setuptools

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.0
    hooks:
      - id: nbqa-pylint
        name: nbqa-pylint
        description: Run 'pylint' on a Jupyter Notebook
        entry: nbqa pylint
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies: [pylint]
        args:
          - --ignore=no_check*,__init__.py
          - --max-line-length=79
          - --const-naming-style=any
          - --disable=E0401,W0104,R0903,R1721,E1101,E0611,F0002,C0305


  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: "v3.0.0a5"
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        args:
          [
            "--ignore=no_check*,__init__.py",
            "--max-line-length=79",
            "--const-naming-style=any",
            "--disable=E0401,W0104,R0903,R1721,E1101,E0611,F0002,C0305,line-too-long"
          ]
        additional_dependencies: [pylint]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.0
    hooks:
      - id: nbqa-pydocstyle
        name: nbqa-pydocstyle
        description: Run 'pydocstyle' on a Jupyter Notebook
        entry: nbqa pydocstyle
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies: [pydocstyle]
```

### ~/.cache/pre-commit/pre-commit.log (if present)

repos:
  - repo: https://github.com/PyCQA/docformatter
    rev: "eb1df347edd128b30cd3368dddc3aa65edcfac38"
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-descriptions=79, --style=google]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: "v3.1.0"
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/psf/black.git
    rev: "24.10.0"
    hooks:
      - id: black
  - repo: https://github.com/mwouts/jupytext
    rev: v1.14.1
    hooks:
     - id: jupytext
       entry: jupytext --to py *.ipynb
       language: python
       types: [jupyter]
       args:
         - --from=ipynb
         - --to=py:percent
         - --pipe=black
         - --pipe=isort - --profile black --filter-files
         - --opt=notebook_metadata_filter=-kernelspec
         - --sync
         - --pre-commit
         - --paired-paths
       additional_dependencies:
         - black==22.10.0
         - isort==5.11.5
       exclude: '.*\.md$'
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.0
    hooks:
      - id: nbqa-black
        name: nbqa-black
        description: Run 'black' on a Jupyter Notebook
        entry: nbqa black
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies: [black]
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.19.0"
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/pycqa/isort
    rev: "5.13.2"
    hooks:
      - id: isort
        args:
          - --check
          - --float-to-top
  - repo: https://github.com/nbQA-dev/nbQA
    rev: "1.9.0"
    hooks:
      - id: nbqa
        entry: nbqa blacken-docs
        name: nbqa-blacken-docs
        alias: nbqa-blacken-docs
        additional_dependencies: [blacken-docs]
        args:
          - --nbqa-md
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.0
    hooks:
      - id: nbqa-pyupgrade
        name: nbqa-pyupgrade
        description: Run 'pyupgrade' on a Jupyter Notebook
        entry: nbqa pyupgrade
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies: [pyupgrade]
      - id: nbqa-isort
        name: nbqa-isort
        description: Run 'isort' on a Jupyter Notebook
        entry: nbqa isort
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies: [isort]
        args:
          - --check
          - --float-to-top

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        args:
          - --ignore-regex=^\s*"image\/(jpeg|png|gif|bmp|tiff)":\s.*
          - --ignore-regex=[A-Za-z0-9+/]{100,}
          - --skip=*.js,*.html,*.css,*.svg",*.json,*.png,*.jpg,*.yml,*.yaml
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.0
    hooks:
      - id: nbqa-flake8
        args:
          - --ignore=E501,E712,W291,F632,E203,F821,F403,W391
          - --exclude=.*,__init__.py
        name: nbqa-flake8
        description: Run 'flake8' on a Jupyter Notebook
        entry: nbqa flake8
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies:
          - flake8-variables-names
          - pep8-naming
          - flake8-functions-names

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          - --ignore=E501,E712,W291,F632,E203,F821,F403,W391
          - --exclude=.*,__init__.py
        additional_dependencies:
          - flake8-variables-names
          - pep8-naming
          - flake8-functions-names

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.0
    hooks:
      - id: nbqa-mypy
        name: nbqa-mypy
        description: Run 'mypy' on a Jupyter Notebook
        entry: nbqa mypy
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies:
          - mypy
          - pandas-stubs
          - git+https://github.com/numpy/numpy-stubs
          - mypy-extensions
          - types-requests
          - types-PyYAML
          - types-setuptools

        args:
          # - --cache-dir=/dev/null
          # - --cache-dir=nul
          # - --no-incremental
          - --non-interactive
          - --install-types
          - --explicit-package-bases
          - --ignore-missing-imports
          - --disallow-untyped-calls
          - --disallow-untyped-defs
          - --disallow-untyped-decorators
          - --strict
          - --extra-checks
          - --disallow-any-decorated
          - --disallow-any-generics
          - --local-partial-types
          - --pretty
          - --force-uppercase-builtins
          - --force-union-syntax
          - --warn-unreachable
          - --warn-redundant-casts
          - --warn-return-any
          - --disallow-any-explicit

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args:
          # - --cache-dir=/dev/null
          # - --cache-dir=nul
          # - --no-incremental
          - --non-interactive
          - --install-types
          - --explicit-package-bases
          - --ignore-missing-imports
          - --disallow-untyped-calls
          - --disallow-untyped-defs
          - --disallow-untyped-decorators
          - --strict
          - --extra-checks
          - --disallow-any-decorated
          - --disallow-any-generics
          - --local-partial-types
          - --pretty
          - --force-uppercase-builtins
          - --force-union-syntax
          - --warn-unreachable
          - --warn-redundant-casts
          - --warn-return-any
          - --disallow-any-explicit

        additional_dependencies:
          - mypy
          - pandas-stubs
          - git+https://github.com/numpy/numpy-stubs
          - mypy-extensions
          - types-requests
          - types-PyYAML
          - types-setuptools

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.0
    hooks:
      - id: nbqa-pylint
        name: nbqa-pylint
        description: Run 'pylint' on a Jupyter Notebook
        entry: nbqa pylint
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies: [pylint]
        args:
          - --ignore=no_check*,__init__.py
          - --max-line-length=79
          - --const-naming-style=any
          - --disable=E0401,W0104,R0903,R1721,E1101,E0611,F0002,C0305

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: "v3.0.0a5"
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        args:
          [
            "--ignore=no_check*,__init__.py",
            "--max-line-length=79",
            "--const-naming-style=any",
            "--disable=E0401,W0104,R0903,R1721,E1101,E0611,F0002,C0305,line-too-long"
          ]
        additional_dependencies: [pylint]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.0
    hooks:
      - id: nbqa-pydocstyle
        name: nbqa-pydocstyle
        description: Run 'pydocstyle' on a Jupyter Notebook
        entry: nbqa pydocstyle
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies: [pydocstyle]
