### ISSUE TITLE
Using rustup components directly

### ISSUE THREAD

**Issue by ernieIzde8ski** [pre-commit/pre-commit#3355]
### search you tried in the issue tracker

`is:issue rust`, `is:issue rustup`, `is:issue rust toolchain`

### describe your actual problem

The Rust toolchain itself comes with some great utilities, so I frequently write local hooks like these:

<details>

<summary> Snippet of .pre-commit-config.yaml </summary>

```yaml
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        # only the nightly toolchain supports all configuration options
        entry: cargo +nightly fmt
        types:
          - rust
        language: system
        pass_filenames: false
      - id: clippy
        name: cargo clippy
        entry: cargo clippy
        types:
          - rust
        language: system
        pass_filenames: false
      - id: cargo-test
        name: cargo test
        entry: cargo test
        types:
          - rust
        language: system
        pass_filenames: false
```

</details>

Unfortunately, none of these should be installed as Rust crates, all being internal or having deprecated crates, which brings me to my question:

1. Is it possible already to natively use Rust toolchain components from within pre-commit? I ask just to be safe, though docs don't seemingly suggest it (apart from writing a system hook).
2. If not, could I have the go-ahead to implement a rustup language?

### pre-commit --version

pre-commit 4.0.1
