### ISSUE TITLE
pre-commit failing on Windows path with spaces

### ISSUE THREAD

**Issue by cpadilla** [pre-commit/pre-commit#3362]
### search you tried in the issue tracker

windows spaces in filepath

### describe your issue

My coworker tried running a commit hook I created in an enterprise Github and ran into the following issue because his user path contains his full name with a space included.

```
$ pre-commit run --all-files
[INFO] Initializing environment for https://github.cms.gov/common-working-file-modernization/check-file-endings.
Check File Endings (local)...............................................Failed
- hook id: check-file-endings
- exit code: 1

C:\Users\Jordan : The term 'C:\Users\Jordan' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ C:\Users\Jordan Firari\.cache\pre-commit\repo3sqzkgw3\check-file-endi ...
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Jordan:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Correct me if I'm mistaken, but this appears to be an issue in calling the pre-commit hook "check-file-endings" and not from any of the code that that pre-commit hook I wrote is running.

### pre-commit --version

4.0.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.cms.gov/common-working-file-modernization/check-file-endings
    rev: 1.0.1
    hooks:
      - id: check-file-endings
```
