### ISSUE TITLE
Parallel Hooks + Windows

### ISSUE THREAD

**Issue by jaredhinzecs** [pre-commit/pre-commit#3365]
### search you tried in the issue tracker

parallel

### describe your issue

Noticed [this post back in 2018](https://github.com/pre-commit/pre-commit/issues/510) alleged that `pre-commit` was suited to run hooks in parallel on [v1.13.0](https://github.com/pre-commit/pre-commit/releases/tag/v1.13.0).

On Windows 11, I run pre-commit in Msys2 and note the hooks run consecutively.
I would expect these hooks be capable of running in parallel.

### pre-commit --version

pre-commit 4.0.1

### .pre-commit-config.yaml

```yaml
---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
    exclude: '^helm/charts/'
  - id: detect-aws-credentials
    args: ["--allow-missing-credentials"]
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: trailing-whitespace

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.92.0
  hooks:
  - id: terraform_fmt
  - id: terraform_tflint
  - id: terraform_validate
  - id: terraform_trivy
  - id: terraform_checkov
  - id: terraform_providers_lock
    files: .terraform.lock.hcl
    args:
    - '--args=-platform=windows_amd64'
    - '--args=-platform=darwin_amd64'
    - '--args=-platform=linux_amd64'
    - '--args=-platform=linux_arm64'
```

### ~/.cache/pre-commit/pre-commit.log (if present)

N/A
