### ISSUE TITLE
Bug in shell after using pre-commit-packer

### ISSUE THREAD

**Issue by smutel** [pre-commit/pre-commit#3367]
### search you tried in the issue tracker

yes

### describe your issue

I would like to use pre-commit to validate packer files.
I am using https://github.com/cisagov/pre-commit-packer.
After the execution of pre-commit, I shell is completely blocked.
I need to type the command `reset` to re-init it.

I know that this behavior is caused by this piece of code in the pre-commit-packer hook called `packer_fmt.sh`:
```sh
for file in "${FILES[@]}"; do
  if ! packer fmt "${ARGS[@]}" -- "$file"; then
    error=1
    echo
    echo "Failed path: $file"
    echo "================================"
  fi
done
```

### pre-commit --version

pre-commit 4.0.1

### .pre-commit-config.yaml

```yaml
repos:  
  - repo: https://github.com/cisagov/pre-commit-packer
    rev: v0.3.0
    hooks:
      - id: packer_fmt
```
