### ISSUE TITLE
pre-commit not using my environment.yml file 

### ISSUE THREAD

**Issue by nickvigilante** [pre-commit/pre-commit#3369]
### search you tried in the issue tracker

conda environment.yml

### describe your issue

I'm trying to set up a linter in a private repository, and some of the local hooks I've created rely on a conda environment. I found [this issue](https://github.com/pre-commit/pre-commit/issues/1204) that suggested the conda implementation wouldn't pass in an environment.yml file, but the docs suggest that the hook repository (in this case, the local repository) has an environment.yml. In our environment, we have the environment.yml file and the .pre-commit-config.yaml files in the same directory.

If I don't manually create and activate the environment beforehand, I get errors saying that certain commands I install can't be found. I reproduced the behavior here: https://github.com/nickvigilante/pre-commit-conda-issue/tree/main

Rough steps to reproduce (I was having issues getting pre-commit to detect that there were files I wanted it to run against, and it kept skipping my check):

1. `git clone https://github.com/nickvigilante/pre-commit-conda-issue`
2. `pip install pre-commit`
3. `pre-commit install`
4. `pre-commit run -a -v`

Expected behavior: it fails and says one file modified, and it cleans up the Python in each of the Markdown files.
Observed behavior: it fails saying `doccmd` not found.

### pre-commit --version

pre-commit 4.0.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: ruff-md
        name: Run Ruff formatter on Markdown files
        files: 'index\.md$'
        language: conda
        entry: doccmd
        args:
          - "-l"
          - "py"
          - "-l"
          - "python"
          - "-c"
          - "ruff format"
          - "--myst-extension"
          - ".qmd"
          - "--no-pad-file"
```

### ~/.cache/pre-commit/pre-commit.log (if present)

Not present.
