### ISSUE TITLE
Find tags on non-default branches

### ISSUE THREAD

**Issue by vivodi** [pre-commit/pre-commit#3379]
### search you tried in the issue tracker

#2831,#3010

### describe your issue

Pre-commit's automatic update cannot find tags on non-default branches:
```console
$ git clone https://github.com/python-poetry/poetry.git
$ cd poetry
$ git describe --tags --abbrev=0

1.8.0
```
However, this command lists the truly latest tag:
```console
$ git describe --tags $(git rev-list --tags --max-count=1)

1.8.5
```
Currently, pre-commit's update strategy is clearly flawed. If you insist that this design is correct, then I'll have no choice but to rely on Renovate for updates.

### pre-commit --version

v4.0.1

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/python-poetry/poetry
  rev: '1.8.5'
  hooks:
    - id: poetry-check
```
