### ISSUE TITLE
Add support for nested list as `additional_dependencies` value

### ISSUE THREAD

**Issue by rodrigorabioglio** [pre-commit/pre-commit#3380]
### search you tried in the issue tracker

flatten, additional_dependencies

### describe your actual problem

**TL,DR:** 

I want to use yaml anchors to manage "aditional_dependencies" easily. For this to work, the `additional_dependencies` key could support nested lists - and pre-commit would flatten it before installing dependencies for a given hook. 

**Context** 

We use pre-commit for a Monorepo. Many team users are not familiarized with using multiple environments for each "sub-repo".  To simplify development workflow I want to declare dependencies for specific hooks, avoiding "package not found" erros when trying to run hooks.

Some hooks have common dependencies. I want to keep them together as yaml anchors to make dependencies update simpler and make sure the use the sam packages/libraries. 

Lets say we have hooks A,B with the following dependencies: 

A: x
B: x,y,z

I would like to have a yaml like: 

```
base_deps: &base_deps
    - x
  
b_deps: &b_deps
   - y
   - z
 

repos:
   repo: local
   hooks:
     -  id: A
         ...
        additional_dependencies:
              - *base_deps
      -  id: B
         ...
        additional_dependencies:
              - *base_deps
              - *b_deps
```

With this sample config I get the following error:

`An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='local')
==> At key: hooks
==> At Hook(id=B)
==> At key: additional_dependencies
==> At index 2
=====> Expected string got list`

### pre-commit --version

pre-commit 3.7.0
