### ISSUE TITLE
pre-commit with --all-files get pre commit hook run multiple times

### ISSUE THREAD

**Issue by annieanqiyu** [pre-commit/pre-commit#3397]
### search you tried in the issue tracker

Online 

### describe your issue

Hi team i am in a big repo and when i execute `pre-commit run  --verbose --config .pre-commit-config-ci.yaml --show-diff-on-failure --all-files` I found out the hook was executed more than one time and different file groups are passed in. It seems at background the --all-files will split the files into group and execute hook one by one. Is there a way to run all the files at once? 

### pre-commit --version

pre-commit 3.8.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: <a customized pre commit hook repo with more hooks>
    rev: v1.2.0
    hooks:
      - id: check-pr-summary
        args: [--build_language=gradle, --owner=xxx, --repo=xxx, --is_in_jenkins=True, --github_access_token_env_name=GITHUB_TOKEN]
        files: ^src/.*
        require_serial: true
```

### ~/.cache/pre-commit/pre-commit.log (if present)

```
 pre-commit run  --verbose --config .pre-commit-config-ci.yaml --show-diff-on-failure --all-files

check pr summary.........................................................Failed
- hook id: check-pr-summary
- duration: 0.2s
- exit code: 1

Error retrieving branch name from system env.
Error retrieving branch name from system env.
```
Error is expected but the problem is executed twice. In detailed log, found the filenames passed in are two groups
