### ISSUE TITLE
Crash since version 4.1.0

### ISSUE THREAD

**Issue by gmonacho** [pre-commit/pre-commit#3402]
### search you tried in the issue tracker

keyerror src

### describe your issue

Hi, since i installed the verison 4.1.0
i encounter this error:
```
An unexpected error has occurred: KeyError: 'src'
Check the log at /home/gmonacho/.cache/pre-commit/pre-commit.log
```

### pre-commit --version

4.1.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
    - id: system
      name: Commit Message Check
      entry: hooks/commitlint.sh
      pass_filenames: false
      language: script
      stages: [commit-msg]
    - id: system
      name: Python Typing Check
      entry: hooks/pyright.sh
      pass_filenames: false
      language: script
      stages: [pre-commit, pre-push]
    - id: system
      name: Python Linting and Formatting
      entry: hooks/ruff.sh
      pass_filenames: false
      language: script
      stages: [pre-commit, pre-push]
```

### ~/.cache/pre-commit/pre-commit.log (if present)

Traceback (most recent call last):
  File "/home/gmonacho/Documents/Projects/Web/Keskireste/keskireste-shared/.venv/lib/python3.13/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/gmonacho/Documents/Projects/Web/Keskireste/keskireste-shared/.venv/lib/python3.13/site-packages/pre_commit/main.py", line 417, in main
    return run(args.config, store, args)
  File "/home/gmonacho/Documents/Projects/Web/Keskireste/keskireste-shared/.venv/lib/python3.13/site-packages/pre_commit/commands/run.py", line 425, in run
    for hook in all_hooks(config, store)
                ~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/gmonacho/Documents/Projects/Web/Keskireste/keskireste-shared/.venv/lib/python3.13/site-packages/pre_commit/repository.py", line 233, in all_hooks
    return tuple(
        hook
        for repo in root_config['repos']
        for hook in _repository_hooks(repo, store, root_config)
    )
  File "/home/gmonacho/Documents/Projects/Web/Keskireste/keskireste-shared/.venv/lib/python3.13/site-packages/pre_commit/repository.py", line 236, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmonacho/Documents/Projects/Web/Keskireste/keskireste-shared/.venv/lib/python3.13/site-packages/pre_commit/repository.py", line 209, in _repository_hooks
    return _non_cloned_repository_hooks(repo_config, store, root_config)
  File "/home/gmonacho/Documents/Projects/Web/Keskireste/keskireste-shared/.venv/lib/python3.13/site-packages/pre_commit/repository.py", line 161, in _non_cloned_repository_hooks
    return tuple(
        Hook.create(
    ...<4 lines>...
        for hook in repo_config['hooks']
    )
  File "/home/gmonacho/Documents/Projects/Web/Keskireste/keskireste-shared/.venv/lib/python3.13/site-packages/pre_commit/repository.py", line 162, in <genexpr>
    Hook.create(
    ~~~~~~~~~~~^
        repo_config['repo'],
        ^^^^^^^^^^^^^^^^^^^^
        _prefix(hook['language'], hook['additional_dependencies']),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        _hook(hook, root_config=root_config),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/gmonacho/Documents/Projects/Web/Keskireste/keskireste-shared/.venv/lib/python3.13/site-packages/pre_commit/hook.py", line 57, in create
    return cls(src=src, prefix=prefix, **{k: dct[k] for k in _KEYS})
                                             ~~~^^^
KeyError: 'src'
