### ISSUE TITLE
commit-msg stage not triggered

### ISSUE THREAD

**Issue by nappa85** [pre-commit/pre-commit#3408]
### search you tried in the issue tracker

commit-msg

### describe your issue

Hello,
I'm trying to create an hook that checks the changelog has been updated, to do that I need access to the pending commit message, from the docs it should be enough to use the `commit-msg` stage.

I've already run `pre-commit install -t commit-msg` and the script is present in `.git/hooks/commit-msg`

The idea is to move the file to a standard path so I can use it later inside the Makefile.
Fact is that the script is never invoked when I run `git commit -m "my commit message"`, I tried putting all values on `stages`, so `[commit-msg,post-checkout,post-commit,post-merge,post-rewrite,pre-commit,pre-merge-commit,pre-push,pre-rebase,prepare-commit-msg]`, and it's called exactly 3 times with different parameters, in facts that's the behavior for `pre-commit` stage, so I'm quite sure only `pre-commit` stage is triggered.

At this point I'm out of debugging ideas, I'm probably getting something really wrong

### pre-commit --version

4.0.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: move_commit_msg
        name: move commit message
        entry: move_commit_msg.sh
        language: script
        stages: [commit-msg]
        args:
          - .git/TEMP_COMMIT_MSG
        verbose: true
      - id: lint
        name: lint the code
        entry: make lint
        language: system
```

### ~/.cache/pre-commit/pre-commit.log (if present)

Deleted before trying, not recreated
