### ISSUE TITLE
`Duplicate "color"` for prettier linter

### ISSUE THREAD

**Issue by floriantschopp** [pre-commit/pre-commit#3409]
### search you tried in the issue tracker

prettier, Dublicate, color

### describe your issue

Today, after doing a `pre-commit clean` and running `pre-commit run prettier --all-files` (even on an empty repo), I get the following error
```
prettier.................................................................Failed
- hook id: prettier
- exit code: 1

Duplicate "color"
```

My `.pre-commit-config.yaml` did not change and neither the pre-commit version

### pre-commit --version

pre-commit 4.0.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude_types: [html, inc]
        require_serial: True
```

**Comment by asottile** [comment]
I don't know why you would think we can help with prettier's problems but this is definitely not the right place

**Comment by floriantschopp** [comment]
Digged a bit deeper, and it seems the main issue is also known upstream: https://github.com/prettier/prettier/issues/17170

If anyone else is having similar issues, feel free to use this:
```
  - repo: https://github.com/floriantschopp/mirrors-prettier
    rev: 3.5.1
    hooks:
      - id: prettier
        require_serial: True
```
