### ISSUE TITLE
Version 4.1.0: Expected one of commit, commit-msg, manual, merge-commit, post-checkout, post-commit, post-merge, prepare-commit-msg, push but got: 'pre-commit'

### ISSUE THREAD

**Issue by Zethson** [pre-commit/pre-commit#3411]
### search you tried in the issue tracker

Expected one of commit, commit-msg, manual, merge-commit, post-checkout, post-commit, post-merge, prepare-commit-msg, push but got: 'pre-commit'

### describe your issue

My CI job installs pre-commit 4.1.0 but I nevertheless run into the "Expected one of commit, commit-msg, manual, merge-commit, post-checkout, post-commit, post-merge, prepare-commit-msg, push but got: 'pre-commit' error. I know that this is an issue with old versions but in this case, I am not caching anything (I deleted the cache and removed all caching related Github Actions code). The log says that I installed version 4.1.0

### pre-commit --version

4.1.0

### .pre-commit-config.yaml

```yaml
fail_fast: false
default_language_version:
  python: python3
default_stages:
  - pre-commit
  - pre-push
minimum_pre_commit_version: 4.0.0
repos:
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.5.1
    hooks:
      - id: prettier
        exclude: |
          (?x)(
            docs/changelog.md
          )
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        exclude: |
          (?x)(
              docs/examples/|
              docs/notes/
          )
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --unsafe-fixes]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: detect-private-key
      - id: check-ast
      - id: end-of-file-fixer
        exclude: |
          (?x)(
              .github/workflows/latest-changes.jinja2
            )
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
      - id: check-case-conflict
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: ["types-requests", "types-attrs"]
```

### ~/.cache/pre-commit/pre-commit.log (if present)

Not present
