### ISSUE TITLE
Run --all-files doesn't take into account exclude

### ISSUE THREAD

**Issue by Mavtti** [pre-commit/pre-commit#3412]
### search you tried in the issue tracker

is:issue --all-files exclude 

### describe your issue

Hey, I'm currently setting up mypy in our repo. I've added mypy to pre-commit. Since we are slowly integrating it into our codebase, I've excluded from the pre-commit, the files that were not refacto yet.

Thing is, when I add a modification to one of these excluded files and commit it, pre-commit works as expected and the mypy check passes.
But when I run `pre-commit run --all-files`, mypy returns errors on these excluded files.

I've seen [this issue](https://github.com/pre-commit/pre-commit/issues/2936) but there's no info in it.

Don't know how I can solve this since it's not the expected behavior according to the reply.
If you need more information, feel free to ask.

Thanks !

### pre-commit --version

pre-commit 4.1.0

### .pre-commit-config.yaml

```yaml
default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [--config-file=./pyproject.toml]
        exclude: "foo\/(deploy|clients)\/.+.py"
        files: ^foo/
```
