### ISSUE TITLE
TypeError when running pre-commit

### ISSUE THREAD

**Issue by finchertrilliant** [pre-commit/pre-commit#3419]
### search you tried in the issue tracker

typeerror

### describe your issue

On OSX 15.3.1 using python 3.8.17, I get a `TypeError` whenever trying to run pre-commit, even just `pre-commit -V`. Full stack trace is attached.

I additionally tried an earlier version, but anything 4.x gives me the same error. If I got back to 3.5.0 I no longer get the issue.

[20250227_error.txt](https://github.com/user-attachments/files/19055907/20250227_error.txt)

### pre-commit --version

pre-commit 4.1.0

### .pre-commit-config.yaml

```yaml
exclude: >
      (?x)(
          \.mypy_cache/
          | \.pytest_cache/
          | \.venv/
          | build/
          | dist/
          | notebooks/
          | tools/cookiecutter/{{
          | \S+\.egg-info/
          | \.vscode/
          | tsconfig\.json
      )
repos:
  - repo: https://github.com/srstevenson/nb-clean
    rev: 3.0.1
    hooks:
      - id: nb-clean

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: mixed-line-ending
      - id: check-added-large-files

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
        args: [-d=relaxed]
        exclude: |
          (?x)(
              apps/.*/deploy/templates/.*|
              libs/helm-tools/ttl_cronjob/.*|
              libs/helm-tools/tests/fixtures/.*
          )

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat-footnote
          - mdformat-gfm-alerts

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.10.0
    hooks:
      - id: markdownlint-cli2
        language_version: 18.17.0 # Specify the Node.js version

  - repo: local
    hooks:
      - id: root-env-setup
        name: root-env-setup
        language: system
        always_run: true
        require_serial: true
        pass_filenames: false
        entry: uv sync

      # these two hooks actually modify files, so let's run them
      # early, before other checks even happen.
      - id: isort
        name: isort
        language: system
        require_serial: true
        types: [file]
        files: \.(py|xsh)
        entry: uv run isort

      - id: black
        name: black
        language: system
        require_serial: true
        types: [python]
        entry: uv run black --config pyproject.toml

      - id: flake8
        name: flake8
        language: system
        require_serial: true
        types: [python]
        entry: uv run flake8 --config .flake8

      - id: validate
        name: validate
        language: system
        always_run: true
        fail_fast: true
        require_serial: true
        pass_filenames: false
        files: ^(libs/.*|apps/.*)
        # have to pass --only-changed here and *no* filenames to ensure running against projects with deleted files
        entry: uv run mono validate --only-changed

      - id: mono-docker-lock
        name: mono-docker-lock
        language: system
        always_run: true
        fail_fast: false
        require_serial: true
        pass_filenames: false
        entry: uv run mono docker lock

      - id: ci-update-orchestration
        name: ci-update-orchestration
        language: system
        pass_filenames: false
        fail_fast: true
        require_serial: true
        files: ^(libs/.*|apps/.*)pyproject\.toml
        entry: uv run mono ci-update

      - id: root-mypy
        name: root-mypy
        entry: uv run mypy scripts
        language: system
        pass_filenames: false
        require_serial: true

      - id: env-setup
        name: env-setup
        language: system
        require_serial: true
        pass_filenames: false
        files: ^(libs/.*|apps/.*)
        verbose: true
        # this ensures envs are set up for subsequent steps, without having to run setup for those steps each time.
        # have to pass --only-changed here and *no* filenames to ensure running against projects with deleted files
        # since this could for instance trigger a type check in those projects
        # only run on non-merge commits - assume that main has already performed these checks
        entry: ./scripts/run-if-not-merge.sh uv run mono venvs install --include-downstream --only-changed --fail-fast

      - id: project-pre-commits
        name: project-pre-commits
        language: system
        require_serial: true
        files: ^(libs/.*|apps/.*)
        # python paths get passed here and filtered to project dirs
        # only run on non-merge commits - assume that main has already performed these checks
        entry: ./scripts/run-if-not-merge.sh uv run mono pre-commit --skip-setup --fail-fast

      - id: project-mypys
        name: project-mypys
        language: system
        verbose: true
        always_run: true
        require_serial: true
        pass_filenames: false
        files: ^(libs/.*|apps/.*)
        # have to pass --only-changed here and *no* filenames to ensure running against projects with deleted files
        # only run on non-merge commits - assume that main has already performed these checks
        entry: ./scripts/run-if-not-merge.sh uv run mono typecheck --skip-setup --include-downstream --only-changed --fail-fast

      - id: generate-labels-yaml
        name: generate-labels-yaml
        language: system
        always_run: true
        pass_filenames: false
        entry: uv run python scripts/ci/generate_labels_yaml.py
        require_serial: true
```
