### ISSUE TITLE
Dockerfile build path for local repos

### ISSUE THREAD

**Issue by bok11** [pre-commit/pre-commit#3436]
### search you tried in the issue tracker

dockerfile path

### describe your actual problem

I am developing a repo, that provides an OCI package defining yaml schemas, including examples.
Seperately i have a gitops repo, consuming the API's.

I made a pre-commit hook to validate the examples against the definition, and want to use this hook both in the repo for the OCI package and in the gitops repo.

**What I have done so far** 

1. Created the script and dockerized it in the OCI repo under hooks/definition-check

2. in the OCI repo in .pre-commit-hooks.yaml to be able to import it from other repos:
``` 
 - id: definition-check
    name: definition-check
    entry: docker run --rm -v "$(pwd):/workdir" hooks/definition-check
    language: docker
```

3. In the OCI repo .pre-commit-config.yaml i have this:
```
- repo: local
  hooks:
  - id: definition-check
    name: Definition Check
    entry: docker run --rm -v "$(pwd):/workdir" hooks/definition-check
    language: docker
    args: [ --file hooks/definition-check/Dockerfile ]
    files: ^api/.*\.yaml$
    description: Validate API definitions
```

**The issue**
When running the pre-commit hook, I see it fails to build because it looks for the dockerfile in the root of the repo, but the file lives in hooks/definition-check

** What i want to achieve**
I want two things:
* I want to run the pre-commit locally to check that i didnt break the examples when changing stuff in the OCI package.

* Import the hook in a different repo as a remote check, like we do with https://github.com/pre-commit/pre-commit-hooks

### pre-commit --version

pre-commit 4.0.1
