### ISSUE TITLE
Add option to simply run a command, without git repo

### ISSUE THREAD

**Issue by hvdklauw** [pre-commit/pre-commit#344]
Would be really great if pre commit supported the option to run a certain command to do the checking, just handling the passing of filenames to the command.

This would allow isort to work correctly (see #181, about why it doesn't work). And would allow a CI environment to use the same executable, without the need for another repo just to manage something that is in fact related to the project.

Also this would make sure my editor (Atom in this case) will use the exact same version of the file as the pre-commit hook, preventing issues from everything looking fine in my editor, but then the hook failing because of a version difference.

**Comment by asottile** [comment]
I believe this satisfies this: https://github.com/pre-commit/pre-commit/pull/226

It needs documentation however

**Comment by asottile** [comment]
That said, I've written https://github.com/asottile/reorder_python_imports which works entirely statically opposed to the dynamic analysis that isort does -- we use it at yelp and it works great for our usecases :)

**Comment by asottile** [comment]
In your case I believe the config you'd want is:

```yaml
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort
        language: system
        files: '\.py$'
```
