### ISSUE TITLE
Allow specifying hook working directory

### ISSUE THREAD

**Issue by Goldziher** [pre-commit/pre-commit#3445]
### search you tried in the issue tracker

working_dir, working directory, specify working directory

### describe your actual problem

Hi @asottile,

First off - this tool is amazing. I use it daily, in many languages and I introduce it to every place that doesn't have it.

Hands down incredible work.

To the issue at hand- I searched and didn't find mention of this.

I have a use case for being able to specify the working directory for hooks - this happens in monorepos mostly. 

Example:

```yaml
    - repo: local
      hooks:
          - id: typecheck
            name: typecheck
            entry: cd frontend && pnpm run typecheck
            require_serial: true
            language: system
            files: ^frontend/.*\.(?:m|c)?tsx?$
```

In this case I need to `cd frontend` because the root where I have the `.pre-commit-config.yaml` has no `tsconfig.json`, which causes an error. 

It would be cleaner to being able to specify the working_dir like so:

```yaml
    - repo: local
      hooks:
          - id: typecheck
            name: typecheck
            entry: cd frontend && pnpm run typecheck
            require_serial: true
            language: system
            working_dir: frontend
            files: *\.(?:m|c)?tsx?$
```

### pre-commit --version

any
