### ISSUE TITLE
Pre-commit install-hooks doesn't work with Python 3.8

### ISSUE THREAD

**Issue by matteogrechi** [pre-commit/pre-commit#3447]
### search you tried in the issue tracker

Issues flagged as Bugs and/or Python

### describe your issue

I'm using pre-commit 3.4.0 in a python 3.8 virtual environment (venv) on Ubuntu 22.04 

When running `pre-commit install-hooks` the installation process gets stucked:
```bash
(.venv) user@my_machine ~/my_project_folder $ pre-commit install-hooks
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
```

With Python 3.8 and pre-commit version 2.9 I have the same problem.

With Python 3.10 and pre-commit version 3.4 everything works fine.

Do you have any ideas on how to solve this?

Thank you very much!

### pre-commit --version

pre-commit 3.4.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
```

### ~/.cache/pre-commit/pre-commit.log (if present)

The ~/.cache/pre-commit/pre-commit.log doesn't show anything relevant: it's me killing the process with CTRL + C
