### ISSUE TITLE
pre-commit does not support the interactive mode

### ISSUE THREAD

**Issue by 2107-Nisha** [pre-commit/pre-commit#3456]
### search you tried in the issue tracker

....

### describe your issue

I created a hook to run and audit detect-secrets, but it fails because, during the audit, it doesn't take any input. Is there any solution available for this?

### pre-commit --version

pre-commit 3.8.0

### .pre-commit-config.yaml

```yaml
repos:
    - repo: https://github.com/IBM/detect-secrets
      rev: 0.13.1+ibm.61.dss
      hooks:
        - id: detect-secrets  # pragma: whitelist secret
          args: [--baseline, .secrets.baseline, --no-keyword-scan]
          stages: [commit, push]

    - repo: local
      hooks:
      - id: detect-secrets-precheck
        name: detect-secrets-precheck
        entry: .github/githooks/precheck-detect-secrets.sh
        language: script
        stages: [commit]
```
