### ISSUE TITLE
pre-commit + mypy get confused about minimum python requirements

### ISSUE THREAD

**Issue by kratsg** [pre-commit/pre-commit#3458]
### search you tried in the issue tracker

minimum mypy python requirement

### describe your issue

With this file (`debug.py`)

```python
import pytensor
```

and running `pre-commit`:

```
$ pre-commit run --files debug.py
mypy.....................................................................Failed
- hook id: mypy
- exit code: 2

/Users/kratsg/.cache/pre-commit/repocimxhi9a/py_env-python3.12/lib/python3.12/site-packages/pytensor/tensor/math.py:4169: error: Pattern matching is only supported in Python 3.10 and greater  [syntax]
Found 1 error in 1 file (errors prevented further checking)
```

No `pre-commit.log` is present. How do I teach `pre-commit` to pick up compatible dependencies from `mypy`'s project_version configuration? In this case, I need to manually add

```yaml
additional_dependencies:
  - "pytensor < 2.20.0"
```

in order for this to work (but this hard-coding might be a symptom of me doing something else wrong).

### pre-commit --version

pre-commit 3.7.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.15.0"
    hooks:
      - id: mypy
        files: debug.py
        args: []
        additional_dependencies:
          - pytensor
```
