### ISSUE TITLE
"pre-commit install --color <option>" ignores the color setting

### ISSUE THREAD

**Issue by robinverduijn** [pre-commit/pre-commit#3459]
### search you tried in the issue tracker

https://github.com/pre-commit/pre-commit/issues?q=is%3Aissue%20color%20

### describe your issue

Thanks for your work on pre-commit, it is a great tool and very helpful to the dev community!

Please let me know if my expectations are wrong, but I ran `pre-commit install --color never` to install pre-commit and have it skip color output when hooks get run because the colors are hard to read with my terminal settings. However, when pre-commit hooks get run they still output in color:

<img width="654" alt="Image" src="https://github.com/user-attachments/assets/806d96e1-945f-42f1-9470-b2f311e8e320" />

I understand that I can specify `export PRE_COMMIT_COLOR=never` in my environment and this will get heeded, but the documentation for `pre-commit install` indicates the `--color` flag is supported:

```
$ pre-commit install --help
usage: pre-commit install [-h] [--color {auto,always,never}] [-c CONFIG] [-f] [--install-hooks]
                          [-t {commit-msg,post-checkout,post-commit,post-merge,post-rewrite,pre-commit,pre-merge-commit,pre-push,pre-rebase,prepare-commit-msg}] [--allow-missing-config]

options:
  -h, --help            show this help message and exit
  --color {auto,always,never}
                        Whether to use color in output. Defaults to `never`.
  -c, --config CONFIG   Path to alternate config file
  -f, --overwrite       Overwrite existing hooks / remove migration mode.
  --install-hooks       Whether to install hook environments for all environments in the config file.
  -t, --hook-type {commit-msg,post-checkout,post-commit,post-merge,post-rewrite,pre-commit,pre-merge-commit,pre-push,pre-rebase,prepare-commit-msg}
  --allow-missing-config
                        Whether to allow a missing `pre-commit` configuration file or exit with a failure code.
```

Since `pre-commit install` accepts the `--color` flag I was expecting that to have some effect, perhaps by passing the specified `--color` value on in the generated `.git/hooks/pre-commit` script. Is that a reasonable assumption? If so, would you welcome a PR to do so?

Otherwise, if the color setting specified to `pre-commit install` is not intended to have this effect, would it be an idea to remove it from the documentation for the install command?

### pre-commit --version

pre-commit 4.2.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.8
  hooks:
    - id: ruff-format
```
