### ISSUE TITLE
Support environment variable for rev element

### ISSUE THREAD

**Issue by ramarov** [pre-commit/pre-commit#3465]
### search you tried in the issue tracker

support environment variable

### describe your actual problem

I want to pre-commit to download repos with specific version. I want to set version as environment variable, so that I don't need to change the code whenever I need to change the version. I can just change version in the OS environment variable without me need to modify pre-commit configuration file

```
repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: ${SQLFLUFF_VERSION}
    hooks:
    - id: sqlfluff-fix
```

### pre-commit --version

pre-commit 3.8.0
