### ISSUE TITLE
Support for Rancher Desktop as Docker Drop-in-Replacement

### ISSUE THREAD

**Issue by Lukas-solar** [pre-commit/pre-commit#3471]
### search you tried in the issue tracker

rancher

### describe your issue

Rancher Desktop installs docker cli to `~/.rd/bin/docker` and set up PATH like this

    ### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
    export PATH="/home/lukas/.rd/bin:$PATH"
    ### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)

If i execute pre-commit with a "language: docker_image" hook locally in my shell then everything works.
If i hit `git commit` and git hooks gets involved i get the error:

    - exit code: 1
    Executable `docker` not found

I can fix that by expanding PATH within `.git/hooks/pre-commit`.

Could you guys implement an mechanism to detect path of docker while `pre-commit install` and write that down in `templated` part of `.git/hooks/pre-commit`? Thanks a lot!

Related to https://github.com/pre-commit/pre-commit/issues/2964

### pre-commit --version

pre-commit 4.2.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
```
