### ISSUE TITLE
pre-commit install dose not install commit-msg stage when default_install_hook_type: [commit-msg] is set

### ISSUE THREAD

**Issue by angu-software** [pre-commit/pre-commit#3472]
### search you tried in the issue tracker

is:issue default_install_hook_type commit-msg 

### describe your issue

Hello!

I try to set up a commit message hook for my local repo

I specified `default_install_hook_type: [commit-msg]` in `.pre-commit-config.yaml` and run `pre-commit install`

According to the documentation this would automatically install the commit-msg stage.

Unfortunately it does not.

pre-commit reports:

```text
$> pre-commit install                
[WARNING] Unexpected key(s) present on local: default_install_hook_types
pre-commit installed at .git/hooks/pre-commit
```

I can install the commit-msg hook type manually, but this is not what I intend.

```text
$> pre-commit install --hook-type commit-msg
pre-commit installed at .git/hooks/commit-msg
```

Cheers
ANGU

### pre-commit --version

pre-commit 4.2.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: local
    default_install_hook_types: [commit-msg]
    hooks:
    -   id: check-commit-msg-format
        name: check-commit-msg-format
        entry: Scripts/GitHooks/pre-commit/check-commit-msg-format.sh
        language: script
        stages: [commit-msg]
        pass_filenames: true
```
