### ISSUE TITLE
Define used hooks in `pyproject.toml` on top of `.pre-commit-config.yaml`

### ISSUE THREAD

**Issue by saroad2** [pre-commit/pre-commit#3474]
### search you tried in the issue tracker

pyproject, config

### describe your actual problem

# TL;DR
It would be nice if a user could define the hooks they want to use in a repo in `pyproject.toml` instead of `.pre-commit-config.yaml`.

# The Core Idea
At the moment, in order to define which hooks are going to be used in a specific repo, one needs to define a `.pre-commit-config.yaml` file and define the hooks there.

Most python tools support defining their config in both their own unique configration file and in a project `pyproject.toml` file. For example:
1. You can define the [*mypy* config](https://mypy.readthedocs.io/en/stable/config_file.html) in both a `mypy.ini` file and `pyproject.toml`
2. You can define the [*coverage* config](https://coverage.readthedocs.io/en/latest/config.html) in both `.coverage` file and `pyproject.toml`
3. etc.

It would be nice if  *pre-commit* could support this ability as well.

# Proposed Solution
*pre-commit* will try to read config initially  from `.pre-commit.config..yaml`. If this file is missing, it will search for a `pyproject.toml`. If this file exists, it will be read the config from a `[tool.pre-commit]` section.

In this way, the following `.pre-commit-config.yaml` file:

```yaml
repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]
-   repo: https://github.com/hhatto/autopep8
    rev: v2.3.2
    hooks:
    -   id: autopep8
-   repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
    -   id: flake8
```

Will look like this in a `pyproject.toml`:

```toml
[[tool.pre-commit.repos]]
repo = "https://github.com/asottile/pyupgrade"
rev = "v3.20.0"
hooks = [{id = "pyupgrade", args = ["--py39-plus"]}]

[[tool.pre-commit.repos]]
repo = "https://github.com/hhatto/autopep8"
rev = "v2.3.2"
hooks = [{id = "autopep8"}]

[[tool.pre-commit.repos]]
repo = "https://github.com/PyCQA/flake8"
rev = "7.2.0"
hooks = [{id = "flake8"}]
```

I think it will be beneficial for pre-commit to provide `.pyproject.toml` support as part of its capabilities.

Please let me know what you think.

### pre-commit --version

latest
