### ISSUE TITLE
Language rust failed to run cargo

### ISSUE THREAD

**Issue by hofbi** [pre-commit/pre-commit#3476]
### search you tried in the issue tracker

hermetic rust, hermetic cargo, system cargo

### describe your issue

Important note: I do not have cargo or any rust related code installed on my system. The documentation for [rust ](https://pre-commit.com/#rust) says "pre-commit will bootstrap rust if it is not present." so I would assume that no system rust/cargo is required. Is this assumption correct?

If I try to use https://github.com/EmbarkStudios/cargo-deny/blob/main/.pre-commit-hooks.yaml in my pre-commit config referenced below, I run into the following error when running `pre-commit run --all-files cargo-deny`

```
check Cargo dependencies.............................................................Failed
- hook id: cargo-deny
- exit code: 1

2025-06-02 15:42:46 [ERROR] failed to fetch crates: failed to run cargo: No such file or directory (os error 2)
2025-06-02 15:42:46 [ERROR] failed to start `cargo metadata`: No such file or directory (os error 2): No such file or directory (os error 2)
```

Both cargo-deny's hook config as well as the Cargo.toml seem to be valid

### pre-commit --version

4.2.0

### .pre-commit-config.yaml

```yaml
minimum_pre_commit_version: '3'
default_install_hook_types: [pre-commit]
default_stages: [pre-commit]
repos:
- repo: https://github.com/EmbarkStudios/cargo-deny
    rev: 0.16.1
    hooks:
      - id: cargo-deny
        language_version: 1.82.0
```

### ~/.cache/pre-commit/pre-commit.log (if present)

The log file does not exist

**Comment by asottile** [comment]
please follow the issue template

**Comment by hofbi** [comment]
I updated the issue with all information I have available

**Comment by asottile** [comment]
please include the commands you ran and their full output

**Comment by hofbi** [comment]
done

**Comment by asottile** [comment]
that output isn't from pre-commit so outside my control

**Comment by hofbi** [comment]
And how about this one

```yaml
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format Rust files with cargo fmt
        language: rust
        types: [rust]
        entry: cargo fmt --
```

with 

```
pre-commit run --all-files cargo-fmt                                                                                                                                                                                                                   
cargo fmt................................................................Failed
- hook id: cargo-fmt
- exit code: 1

Executable `cargo` not found
```

Is a system cargo required to run rust hooks or should pre-commit care about the setup?
