### ISSUE TITLE
Wrong python version detected in new venv with django-cookiecutter

### ISSUE THREAD

**Issue by millerthegorilla** [pre-commit/pre-commit#3487]
### search you tried in the issue tracker

virtualenv python version did not match created version: - actual version: 3.13.5.final.0 - expected version: 3.13.3.final.0

### describe your issue

I installed cookie-cutter in pip using a venv running python version 3.13.5 and then used cookie-cutter to install django-cookiecutter.  Then I ran git init and pre-commit install.
When I ran git commit, pre-commit reported the following...
```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy 
immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: 3.13.5.final.0
- expected version: 3.13.3.final.0
```

### pre-commit --version

pre-commit 4.2.0

### .pre-commit-config.yaml

```yaml
exclude: '^docs/|/migrations/|devcontainer.json'
default_stages: [pre-commit]
minimum_pre_commit_version: "3.2.0"

default_language_version:
  python: python3.13.5

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.25.0'
    hooks:
      - id: django-upgrade
        args: ['--target-version', '5.0']

  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      # Linter
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      # Formatter
      - id: ruff-format

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
```

### version information

```
pre-commit version: 4.2.0
git --version: git version 2.50.0
sys.version:
    3.13.5 (main, Jun 12 2025, 00:00:00) [GCC 15.1.1 20250521 (Red Hat 15.1.1-2)]
sys.executable: /var/home/user/src/trakset/.venv/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: 3.13.5.final.0
- expected version: 3.13.3.final.0

```

```
Traceback (most recent call last):
  File "/var/home/user/src/trakset/.venv/lib64/python3.13/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/var/home/user/src/trakset/.venv/lib64/python3.13/site-packages/pre_commit/main.py", line 389, in main
    return hook_impl(
        store,
    ...<5 lines>...
        args=args.rest[1:],
    )
  File "/var/home/user/src/trakset/.venv/lib64/python3.13/site-packages/pre_commit/commands/hook_impl.py", line 271, in hook_impl
    return retv | run(config, store, ns)
                  ~~~^^^^^^^^^^^^^^^^^^^
  File "/var/home/user/src/trakset/.venv/lib64/python3.13/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/var/home/user/src/trakset/.venv/lib64/python3.13/site-packages/pre_commit/repository.py", line 229, in install_hook_envs
    _hook_install(hook)
    ~~~~~~~~~~~~~^^^^^^
  File "/var/home/user/src/trakset/.venv/lib64/python3.13/site-packages/pre_commit/repository.py", line 90, in _hook_install
    raise AssertionError(
    ...<4 lines>...
    )
AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: 3.13.5.final.0
- expected version: 3.13.3.final.0
