### ISSUE TITLE
support hooks located in repository

### ISSUE THREAD

**Issue by gretel** [pre-commit/pre-commit#367]
```
- repo: ./pre-commit-hooks
  sha: ''
  hooks:
  - id: vault
```
```
Updating pre-commit-hooks...An unexpected error has occurred: CalledProcessError: Command: ('/usr/local/bin/git', 'clone', '--no-checkout', 'pre-commit-hooks', '/Users/gretel/.pre-commit/repoiXzY0j')
Return code: 128
Expected return code: 0
Output: (none)
Errors:
    fatal: repository 'pre-commit-hooks' does not exist
```
