### ISSUE TITLE
Add support for "xargs -n1" hooks?

### ISSUE THREAD

**Issue by chriskuehl** [pre-commit/pre-commit#394]
Some hooks are only written to run against a single file at a time. An example is `stylefmt`.

You can hack around it with a wrapper script, but it's nice to avoid those when possible. The pre-commit xargs implementation already would make it easy to partition into groups of one file.

How do you feel instead about adding a hook parameter like `max_files_per_exec` (questionable name)? Zero or default could keep the current behavior, and you could set to `1` to get the behavior we want here.

cc @SBoudrias

P.S. here's a crazy hack just for kicks:

```yaml
-   repo: local
    hooks:
    -   id: test
        name: test
        language: system
        files: .*
        entry: /bin/bash
        args: ['-c', 'echo $@ | xargs -n1 stylefmt', 'garbage']
```

**Comment by asottile** [comment]
Shouldn't we just contribute to stylelint to fix their bug?

**Comment by SBoudrias** [comment]
stylefmt signature is `stylefmt input.css output.css`, so it's not really an issue of them not taking multiple names, but that their function signature will format the first file and overwrite the second one passed in.

**Comment by asottile** [comment]
Other formatters take an `--in-place` argument, I'm sure stylefmt would be amenable to such a PR.

Sorry, thought we were still taking about stylelint (the other issue) :D

**Comment by chriskuehl** [comment]
Okay, in that case it sounds like we don't even have a use-case for this currently. I think we can close the ticket until we do.

**Comment by asottile** [comment]
Turns out `nim check` has this same problem

We worked around this by doing something like this:

```yaml
    -   id: nim-check
        name: nim check
        entry: bash -xc 'echo "$@" | xargs --verbose -n1 nim check' --
        language: system
        # types: [nim]
        files: '\.nim$'
```

**Comment by asottile** [comment]
slight adjustment, to properly handle spaces you need:

```yaml
    entry: bash -c 'for x in "$@"; do ... "$x"; done' --
```

**Comment by tdegeus** [comment]
How can the work-around be made to work with `args`?
```
    -   id: nim-check
        name: nim check
        entry: bash -c 'for x in "$@"; do nim check ??? "$x"; done' --
        language: system
        files: '\.nim$'
```

**Comment by asottile** [comment]
it's a shell so you can do whatever you want in there

`entry: bash -c 'for x in "$@"; do nim check --args --here $x; done' --`

**Comment by tdegeus** [comment]
Thanks, but that is not what I meant. Suppose that you provide a hook with 
```yaml
    -   id: nim-check
        name: nim check
        entry: bash -c 'for x in "$@"; do nim check ??? "$x"; done' --
        language: system
        files: '\.nim$'
```
and the user has a config
```yaml
repos:
- repo: ...
  rev: ...
  hooks:
  - id: nim-check
    args: [-a, -b, -c]
```
