### ISSUE TITLE
Expose `negate` and deprecate pcre hooks

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#404]
See https://github.com/pre-commit/pre-commit/blob/b05cc4077e621cec637b22d6ad2b80ee84749f97/pre_commit/xargs.py#L48

I imagine something like this:

``` yaml
- id: test
  language: system
  negate_returncode: true
  entry: grep -P herp
```

Instead of the equivalent pcre hook
