### ISSUE TITLE
Explictly specify a stage of push, but script run during commit

### ISSUE THREAD

**Issue by kbalk** [pre-commit/pre-commit#417]
I'm not sure if I've misunderstood the documentation or made a mistake in my .yaml file.  I'm attempting to run py.test during the 'push' stage, but pre-commit is invoking py.test during the commit stage.  I'm using Python 2.7.11 and git 2.7.4.  The yaml file appears as follows:
```
-   repo: local
    stages:
    - push
    hooks:
    -   id: py.test
        name: py.test
        language: system
        entry: python -m py.test
        files: \.py$
        args:
        - tests
        - --run-services
```

**Comment by asottile** [comment]
Stages is configured per-hook. You'll want to move that in like this:

```
-   repo: local
    hooks:
    -   id: py.test
        name: py.test
        language: system
        entry: python -m py.test
        files: \.py$
        stages: [push]
        args:
        - tests
        - --run-services
```
