### ISSUE TITLE
Allow to execute Python hooks outside a virtualenv

### ISSUE THREAD

**Issue by Lucas-C** [pre-commit/pre-commit#426]
Hi.

I developped a new hook to check Python dependencies against [safety-db](//github.com/pyupio/safety-db):
https://github.com/Lucas-C/pre-commit-hooks-safety

It works perfectly well but only if I remove the `VIRTUAL_ENV` environment variable in `languages.python.py:get_env_patch` :
https://github.com/pre-commit/pre-commit/blob/d5ebea3/pre_commit/languages/python.py#L28

Would you be open to a PR that makes it possible to NOT run a Python hook in a virtualenv, based on a `hooks.yaml` config entry ?

**Comment by asottile** [comment]
So that environment variable doesn't actually control whether or not it is in a virtualenv.

For non-virtualenv executables (ones that are installed at the system) you'd use a `system` hook.  (Or `script` for scripts).

I think you'd probably just configure this as a `local` hook:

```yaml
-   repo: local
    hooks:
        -   id: safety-db
            entry: safety
            args: [check, --full-report]
            language: system
```
