### ISSUE TITLE
Question: support for multiple configurations?

### ISSUE THREAD

**Issue by snakescott** [pre-commit/pre-commit#432]
I'm interested in experimenting with different sets of hooks, having different hooks run on my build system versus locally, etc. 

Straightforward ways this might be possible:
- ``` pre-commit run --yaml $PATH --all-files```
- ```PRE_COMMIT_YAML_PATH=$PATH git commit -m "example"```

A more advanced option would be something like adding a ```groups``` yaml key as a sibling of  ```id``` e.g.

```yaml
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.4.2
    hooks:
    -   id: trailing-whitespace
        groups: [basic, advanced]
    -   id: flake8
        groups: [advanced]
```

You could then have ```pre-commit run --groups ...``` and perhaps ```pre-commit set-commit-groups ...```

I don't see anything like this discussed in the docs. Are there advanced/undocumented features that might support this? Is this functionality inline with pre-commit's project goals, or too complicated/promotes a workflow the project doesn't agree with?
