### ISSUE TITLE
support custom hooks's requirements?

### ISSUE THREAD

**Issue by daoiqi** [pre-commit/pre-commit#464]
https://github.com/pre-commit/pre-commit-hooks/blob/master/hooks.yaml#L114

this hook, run `flake8`, As we know, flake8 has many extension. such as <https://github.com/ebeweber/flake8-mutable>.   should run `pip install flake8-mutable` then install it to system python site-package path.

but, `pre-commit install && pre-commit`, it will create `~/.pre-comit/repoxxxxx/py_env-default/` directory.
so the `flake8-mutable` not will in this path.

every repo every python virtual env.

`.pre-commit-config.yaml` will support as below?

```yaml
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.4.2
    hooks:
    -   id: flake8
        requirement: ["pip install flake8-mutable"]
```
