### ISSUE TITLE
Guidance on pre-commit + monorepos

### ISSUE THREAD

**Issue by snakescott** [pre-commit/pre-commit#466]
Any thoughts on using pre-commit in a monorepo (http://danluu.com/monorepo/) setting, with each project having its own `.pre-commit-config.yaml` file? For example, will pre-commit be happy/sad with

- project root not being repo root
- multiple invocations of `pre-commit install`
- etc

I expect to play around and experiment but any early guidance (e.g., "I have seen people try and fail at this, beware" or "Yelp actually does exactly this with steps X, Y, Z") is welcome!

**Comment by asottile** [comment]
Aww man I typed up a response to this and never pressed reply.  I guess I'll try and remember what I said the first time!

Though it's not explicitly designed for a monorepo I can imagine one way you could use the existing configuration to support this goal with a single configuration file.

```yaml
# configure shared hooks that you want to run on all repositories here
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.6.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

# For hooks that only apply to specific repositories, list them below
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.6.1
    hooks:
    -   id: flake8
        name: 'flake8 (for repo1)'
        # Only run on repo1 files
        files: '^repo1/.*\.py'
    -   id: flake8
        name: 'flake8 (for repo2)'
        # Only run on repo2 files
        files: '^repo2/.*\.py'
        # maybe repo2 wants specific argument configuration
        args: [--max-line-length=131]
    # maybe repo3 is python3 only
    -   id: flake8
        name: 'flake8 (for repo3)'
        files: '^repo3/.*\.py'
        language_version: python3

    # etc.
```

Note that the same `repo` can be configured multiple times and within the repo the same hook id can also be repeated
