### ISSUE TITLE
Python support for virtual environments

### ISSUE THREAD

**Issue by woutervb** [pre-commit/pre-commit#485]
I make havy use of virtual environments, both for python 2 and pyton 3 project development.

Currently the 'default' behaviour seems to be to install the books in ~/.pre-commit with as python interpreter the one that is 'currently' active. So when installing hooks from a python3 virtual env. This hook will called with an python 3 interpreter, when installing another hook from python2, it will run, using python2.

As some hooks give different results (e.g. yapf) depending on the python interpreter used, this leads to 'strange' behaviour.

A solution could be to check for a virtual environment and if pre-commit is run inside such a setup, use the virtuel environment to install the hooks and run the hooks from.

This will stop wondering why sometimes files are reformatted, for no other reason than that they are 'processed' with a different interpreter.

**Comment by chriskuehl** [comment]
Yup, you're right that if you don't explicitly request a Python version, it "defaults" to the currently-running Python to create the virtualenv (since that's the Python virtualenv runs as).

Our recommendation for how to handle this is to specifically request a Python version using `language_version`. Here's an example from one of our `.pre-commit-config.yaml` files:

```yaml
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: trailing-whitespace
        exclude: ^assets/vendor/
        language_version: python3.6
    -   id: end-of-file-fixer
        exclude: ^assets/vendor/
        language_version: python3.6
    -   id: autopep8-wrapper
        language_version: python3.6
    -   id: check-json
        files: \.(jshintrc|json)$
        language_version: python3.6
    -   id: check-yaml
        language_version: python3.6
```

In general, I think our recommendation is to specify a `language_version` on basically every hook. Otherwise you can get confusing behavior when the hooks were first run with a different Python version. (Some hooks, like `check-yaml`, don't really matter -- any version of Python should be able to run the hook with the same results -- but the ones that e.g. parse the AST matter a lot.)

I know copying and pasting the language_version after every hook isn't great. This is one of the problems with the current config format, but unfortunately we can't really fix it in a backwards-compatible way (since the top-level is a list). Eventually we're going to take the breaking change in the config format and will have a way to specify a project-wide default for language versions.
