### ISSUE TITLE
A config option to store hook output into a file

### ISSUE THREAD

**Issue by alex-hutton** [pre-commit/pre-commit#499]
Hi, this is a feature request and if people would like it then I will submit a pull request.

What I would like is to be able to specify in the config an output file on  a per hook basis. When the hook is run, it will output to that file (as well as to STDOUT as currently).

The reason I want this is because I want to run pre-commit on Jenkins and I want the reports of certain tools to be stored in files so that they can be easily consumed by Jenkins.

**Comment by asottile** [comment]
This sounds reasonable.

You _can_ hack it into the current scheme but it's not pretty nor very portable (without first-class support):

```yaml
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: flake8
        entry: bash -c -o pipefail 'exec flake8 $@ |& tee -a flake8.log' --
```

To verify:

```
# important, since we use `-a` to append to the log (since pre-commit will invoke 1..many times)
rm flake8.log
pre-commit run flake8 --all-files || true  # if you want to demonstrate a failure writing to the log
cat flake8.log
```

For me (after breaking a file) this looks like this:
```
$ rm flake8.log 
$ pre-commit run flake8 --all-files 
Flake8...................................................................Failed
hookid: flake8

setup.py:1:1: F401 'os' imported but unused

$ cat flake8.log 
setup.py:1:1: F401 'os' imported but unused
```


As for first class, I think if you want to implement this I'd accept something like this:

```yaml
    -   id: flake8
        log_file: flake8.log
```

Note that pre-commit combines stdout and stderr, so you'd get combined stdout / stderr into that log file.
