### ISSUE TITLE
Support for the plugins get run as external/system commands 

### ISSUE THREAD

**Issue by melezhik** [pre-commit/pre-commit#508]
Hi! I read a docs but could not find a proper way to do this.

Say I have plugin as "external" command 'foo arg1 arg2 ...' and want to use it with pre commits. I wande If it's possible ? 

Obviously this external command has no repository, no language  explicitly defended at pre-commit hooks.yaml scope ( location of foo script and  a language to run it is resolved by OS itself,  depending on value of PATH env var and shebang found at foo script. ), as well as 'files' field  does not make a sense here.

So the question is how can we use pre-commits for such external/system commands?

**Comment by asottile** [comment]
I believe you're looking for the [system](http://pre-commit.com/#system) language.

**Comment by asottile** [comment]
And or [repository local hooks](http://pre-commit.com/#repository-local-hooks)

**Comment by melezhik** [comment]
@asottile Thanks for fast response! Could you put here an example hooks.yaml here? The docs are quite terse. Say I what run system command foo with arguments  "--param  a=1 --param b=2" , also I want to pass somehow location to local git repository where my hook resides, as command line for system command parameter as well , is it possible?

**Comment by asottile** [comment]
Something like this should work I think:

```yaml
-   repo: local
    hooks:
    -   id: foo
        name: foo
        entry: foo --param a=1 --param b=2 . 
        language: system
        # does not take file arguments 
        always_run: true
        # due to a bug (already fixed in master) this is required but does nothing 
        files: '' 
```

Typing on my phone so excuse me if there's a typo or two :).  This is pretty close to some of the examples in the second link. 

Note that I pass `.` as the git directory. Pre-commit will always with cwd at the root of the repository

**Comment by melezhik** [comment]
Good! Thanks.

Unfortunately passing directly as '.' won't work for me ( my plugins requiremt is passing file locations as absolute paths ) , can I pass git repository directory path as absolute one? Not sure if yaml supports something like $pwd ... ?

**Comment by melezhik** [comment]
Ideally 'entry: foo --param a=1 --param b=2 --param path=$(PWD)' would work for me, but this is not yaml compatible )))

**Comment by melezhik** [comment]
Probably need to dig into , googling on  yaml/env vars subject ...

**Comment by melezhik** [comment]
Looks like yaml itself does not support such a feature out of the box, and one should extend it on application, yaml parses side ? Is it possible for pre-commit hooks.yaml ?

**Comment by asottile** [comment]
You can probably do `entry: bash -c '... $PWD' `?

**Comment by melezhik** [comment]
Sure,  let me try various methods and I will let you know later . Basicly you answered my question, I need to take few tweaks on my side though -)

**Comment by asottile** [comment]
<3 feel free to bounce off ideas

**Comment by melezhik** [comment]
Ok, looks like my first plugin works, but I can't see the output as it hidden by pre-hook executor:

```
$ git commit -a -mok
perl6-prove..............................................................Passed
[master beb069e] ok
 1 file changed, 1 insertion(+), 1 deletion(-)

$ cat .pre-commit-config.yaml
-   repo: local
    hooks:
    -   id: perl6-prove
        name: perl6-prove
        entry: sparrow plg run perl6-prove --param a=1 --param b=2 --param path=$PWD
        language: system
        always_run: true
        files: ''

```
 Compare with when run directly:

```
$ sparrow plg run perl6-prove  --param path=$PWD

[p] perl6-prove at 2017-03-11 08:11:29
path is: /home/vagrant/projects/perl6-prove
OK
ok      scenario succeeded
STATUS  SUCCEED

```

How can I make pre-commit shows the plugin output?

**Comment by melezhik** [comment]
So I end up with this .pre-commit-config.yaml : 
```
-   repo: local
    hooks:
    -   id: perl6-prove
        name: perl6-prove
        entry: bash -c "sparrow plg run perl6-prove --param a=1 --param b=2 --param path=$PWD"
        language: system
        always_run: true
        files: ''
```
And it work for me. But the output issue is still here. Should I raise a new ticket on this, as my original question is satisfied?
