### ISSUE TITLE
Support default args for system hooks

### ISSUE THREAD

**Issue by alexjurkiewicz** [pre-commit/pre-commit#522]
I'd like to create a `tsfmt` hook with hook definition like this:
```yaml
-   id: tsfmt
    name: TypeScript Formatter (tsfmt)
    description: Code formatting for TypeScript files.
    entry: tsfmt
    args: ['--verify']
    language: system
    files: \.(ts|tsx)$
```

As you can see I need to run `tsfmt --verify $file` to get correct output for pre-commit to parse. Is it a deliberate decision that hook definitions do not support args like this? Or can I submit a PR to add support :)
