### ISSUE TITLE
How do i create a hook that does this 

### ISSUE THREAD

**Issue by awebdeveloper** [pre-commit/pre-commit#547]
i am trying to write a pre-commit plugin for https://github.com/JamieMason/ImageOptim-CLI and this is the only way to use it.  So how do i create a hook for this

`find "ica-slidebox-img-2-2-4.png"  |  imageoptim  --quit --no-color --image-alpha --min-quality=60
`

or this pre commit code into a hook

`images=$(git diff --exit-code --cached --name-only --diff-filter=ACM -- '*.png' '*.jpg')
$(exit $?) || (echo "$images" | imageoptim && git add $images)
`

Info : https://github.com/JamieMason/ImageOptim-CLI/issues/145

**Comment by asottile** [comment]
Just a guess:

```yaml
-   repo: local
    hooks:
    -   id: imageoptim
         name: imageoptim
         entry: bash -c 'echo "$@" | imageoptim --quit --no-color --image-alpha --min-quality=60' --
         language: node
         additional_dependencies: [ImageOptim-Cli@...]
         files: '\.(png|jpg)$'
```

Note you'll lose portability due to bash, but it should work on posixlikes.

Unfortunate that their "commandline interface" doesn't actually support a commandline 🤔
