### ISSUE TITLE
Feature request - hook groups and run hooks by group

### ISSUE THREAD

**Issue by lopopolo** [pre-commit/pre-commit#554]
I'm migrating some tasks from a `Makefile` to my pre-commit config. This gives me the equivalent of `make all`, but I'd like to be able to tag groups of hooks as `lint` or `build` tasks so I can do something like:

```
pre-commit install --group lint
pre-commit run -a --group build
```

I'd like to do this because I otherwise have a ton of duplication between my `Makefile` and pre-commit config.

**Comment by asottile** [comment]
One way this can be done today (without modification) is through multiple configuration files.

Use `.pre-commit-config.yaml` as your default commit / lint / etc. configuration.
Use `-C` (`--config`) to select another configuration for build / etc.

I'm not sure what this would look like otherwise (at least until configuration v2 is completed #414).

Does multiple config files solve this for you?

**Comment by lopopolo** [comment]
I want to lint on pre-commit hook. I want to do other things on pre-commit as well.

I want to be able to also only lint.

Using multiple configs would still cause duplication, unless there were a way to include my lint config in the main pre-commit config.

**Comment by asottile** [comment]
Sure, it was just a suggestion using the current tech :)

What would you want/expect this to look like in configuration?

**Comment by lopopolo** [comment]
```yaml
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  sha: v0.9.1
  hooks:
  - id: check-added-large-files
  - id: check-ast
    language_version: python3
    groups:
    - lint
    - python
  - id: check-byte-order-marker
    groups:
    - lint
  - id: check-case-conflict
  - id: check-docstring-first
    groups:
    - lint
    - python
  - id: check-executables-have-shebangs
  - id: check-json
    groups:
    - lint
    - javascript
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
    groups:
    - lint
    - ansible
  - id: detect-aws-credentials
    groups:
    - packer
    - terraform
  - id: detect-private-key
  - id: end-of-file-fixer
```

and then be able to run all hooks in a particular group:

```console
$ pre-commit run -a --group lint

```
