### ISSUE TITLE
Install node packages from npm instead of git

### ISSUE THREAD

**Issue by gagern** [pre-commit/pre-commit#579]
The node ecosystem is very much centered around npm, and therefore it would make sense to install hooks from there instead of grabbing them from git repositories. This is particularly true for packages which perform non-trivial work when creating a release, like compiling native binaries, minifying resources, cross-compiling various languages, including git submodules and whatnot. The node package will usually contain all of this, the source tree likely not. I guess the same might be true for Python with PyPI, and other common repositories for other languages.

**Comment by asottile** [comment]
For example (not actually tested, but you get the idea):

```yaml
-   repo: local
    hooks:
    -   id: eslint
        name: eslint
        entry: eslint
        language: node
        types: [javascript]
        additional_dependencies: [eslint@4.3.0]
```
