### ISSUE TITLE
Support list of regexps for `exclude` configuration

### ISSUE THREAD

**Issue by tdeo** [pre-commit/pre-commit#591]
Hi,

I'm running into a use case where we have a regex disabling the use of the ruby HTTParty library across (because we built a wrapper around it that handles our proxy settings). However, in some rare cases, we want to specifically use it (for instance because we're posting to localhost, or something in the internal network), and the exclude option for this hook has been growing and is not very elegant:
```yaml
- id: no_httparty
  exclude: ^(path_to_some_file_which_has_a_good_reason_to_use_httparty.rb|some_other_file.rb|...|...|...)$
```

It would be nice it there would be support for either:
- specifying `exclude` a list of patterns:
```yaml
- id: no_httparty
  exclude:
    - ^path_to_some_file_which_has_a_good_reason_to_use_httparty.rb$
    - ^some_other_file.rb$
    - ...
```
- supporting inline disable for pre-commit hooks (maybe in the way pep8 or rubocop do it)

Let me know if one of those options seems reasonable, I'd be happy to give a shot at a PR.

Thanks
