### ISSUE TITLE
Support using existing Docker images as hooks

### ISSUE THREAD

**Issue by jsok** [pre-commit/pre-commit#597]
Currently a `language: docker` hook only supports running a Docker image which it built itself (via a `Dockerfile`).

However this seems a little unnecessary and expensive since we can and should be building and publishing our Docker images to a registry.

Would there be interest in supporting using existing images as hooks? It should be simple and I'd be happy to make the PR.

## Proposed `.pre-commit-hooks.yaml` change

```yaml
-   id: flake8-docker
    name: flake8 (via docker)
    description: flake8, but provided by docker
    files: \.py$

    language: docker
    # Image to `docker pull`
    docker_image: my.registry.example.com/pre-commit-hooks/flake8:latest
    # Optional: use `ENTRYPOINT` of the image if not specified
    entry: flake8
```

**Comment by asottile** [comment]
First: thanks for the issue :) 

My main hesitation is I don't really want to add language specific configuration. 

I think you could simulate the same thing by having a trivial dockerfile with just `FROM <image>` which would largely get you the same result. Thoughts?

**Comment by jsok** [comment]
Yep totally get it 👍 

I think I can solve my underlying desire in a different way by just writing a wrapper script that calls `docker run` and users can override the image if desired using `args`.

**Comment by asottile** [comment]
@jsok actually now that I think about this more, I might be able to write a `language` which makes this work better -- would something like this be useful?

```yaml
-   id: flake8-docker
    name: flake8 (via docker)
    language: docker_image
    entry: my.registry.example.com/pre-commit-hooks/flake8:latest
    files: [python]
```

A downside would be that it would have to *depend* on the `ENTRYPOINT` of the image? so maybe not the best idea?
