### ISSUE TITLE
commit-msg stage does not work

### ISSUE THREAD

**Issue by sobolevn** [pre-commit/pre-commit#623]
Everything works as expected when running just `pre-commit install`, then hooks work.
But when running `pre-commit install -t commit-msg` `IOError` happens, since template could not be found.

Here's the detailed information.

## Env

- `python2.7`
- `pipenv 7.3.7`
- `pre-commit 1.1.1`

Actually tested with both `python2` and `python3`.

## Configuration

```yaml
- repo: local
  hooks:
    - id: gitlint
      name: gitlint
      entry: "bash -c 'gitlint lint'"
      language: system
      stages: [commit-msg]

    - id: pytest
      name: pytest
      entry: "bash -c 'python manage.py test'"
      language: system

    - id: safety
      name: safety
      entry: "bash -c 'safety check'"
      language: system
```

## Output

```
» pre-commit install -t commit-msg
Running in migration mode with existing hooks at /Users/sobolev/Desktop/test/.git/hooks/commit-msg.legacy
Use -f to use only pre-commit.
An unexpected error has occurred: IOError: [Errno 2] No such file or directory: '/Users/sobolev/.virtualenvs/test-p4WySO70/lib/python2.7/site-packages/pre_commit/resources/commit-msg-tmpl'
Check the log at /Users/sobolev/.cache/pre-commit/pre-commit.log
```

When I do `ls /Users/sobolev/.virtualenvs/test-p4WySO70/lib/python2.7/site-packages/pre_commit/resources/commit-msg-tmpl`  that's what is see:

```
(test-p4WySO70) ~/Desktop/test  master ✗                                  ✚ 2 ⚡
» ls /Users/sobolev/.virtualenvs/test-p4WySO70/lib/python2.7/site-packages/pre_commit/resources                
empty_template  pre-push-tmpl  ruby-build.tar.gz
hook-tmpl       rbenv.tar.gz   ruby-download.tar.gz
```
