### ISSUE TITLE
Difficulty working with both Python 2 and Python 3 repositories.

### ISSUE THREAD

**Issue by wting** [pre-commit/pre-commit#644]
We're installing pre-commit at the user level via Homebrew or `pip install --user`, but running into issues where pre-commit 0.x.x only works with Python 2 repositories and pre-commit 1.x.x only works with Python 3 repositories.

As a result the dev has to install and switch between multiple pre-commit versions depending on what Python version the repository is using (via `brew switch pre-commit 0.18.2`).

Any ideas for a better approach to this problem?

**Comment by asottile** [comment]
The intended way to handle this is to specify `language_version` for each python hook in your repository as [documented here](http://pre-commit.com/#overriding-language-version)

pre-commit *defaults* to making virtualenvs in the same interpreter as it is running, but can make environments for any version of the language.

I have some pie-in-the-sky ideas to make this work better with a configuration of something like this:

```yaml
default_language_versions:
    python: python2.7
repos:
    -    repo: ...
          ...
```

but I haven't gotten around to implementing this yet.  As of now, the way to do this is to specify it for each hook (for example):

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
        language_version: python3.6
    -   id: autopep8-wrapper
        language_version: python3.6
    -   id: debug-statements
        language_version: python3.6
    -   id: flake8
        language_version: python3.6
```


> but running into issues where pre-commit 0.x.x only works with Python 2 repositories and pre-commit 1.x.x only works with Python 3 repositories.

Just want to make sure this part is clear, this assertion is incorrect -- the interpreter which pre-commit is running in does support running hooks in different language versions.

Thanks for the issue!
