### ISSUE TITLE
Question: pre-commit as an executable container

### ISSUE THREAD

**Issue by gganeshan** [pre-commit/pre-commit#670]
I am trying to run pre-commit as an executable container but it does not honor the path provided to it outside the container.

## Use case: 
Use _builder_ container during in our CI to perform the pre-commit checks for us. 
The _builder_ container will have all the good stuff such as pre-commit, shellcheck, pylint, yamllint etc as required by a specific project.

The idea behind this is that every project may have slightly different requirements around pre-commit checks (esp. linting based on the program being used) but we dont want our Jenkins build server to be polluted with these packages. Instead we want the developers to ***bring their own*** _builder_ containers to perform project specific pre-commit checks.

## Issue:
I created an image containing pre-commit and all the linters I need. But when I run this executable container, it expects the repo to be inside the container. It does not honor the path outside the container.

## Question:
Do you know if there is a way to resolve this and make it honor the path outside the container without mounting the REPO_PATH as volume??

#### Dockerfile:
```
FROM <RHEL:7.3>

RUN yum install \
      -y \
       git \
       pylint \
       python2-pip \
       ShellCheck \
       yamllint \
    && yum clean all

RUN pip install -Iv --compile --no-cache-dir \
  pre-commit \
  && \
  :

ENTRYPOINT ["pre-commit"]
```
#### pre-commit-config.yaml
```
---
# This file configures the pre-commit tool for this project.
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: requirements-txt-fixer

  - repo: git://github.com/pre-commit/mirrors-pylint
    sha: v1.7.4
    hooks:
      - id: pylint
   
  - repo: https://github.com/adrienverge/yamllint.git
    sha: v1.10.0
    hooks:
      - id: yamllint

  # Run shellcheck.
  - repo: git://github.com/detailyang/pre-commit-shell
    sha: 1.0.2
    hooks:
      - id: shell-lint
```
#### bashrc function:
```
function pc {
  docker run --rm -it \
  --cap-drop all \
  pre-commit $@
}
```
#### Execution:
```
$ pc run .
An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
Check the log at /root/.cache/pre-commit/pre-commit.log
```
