### ISSUE TITLE
cannot get "files" option to work for every file with .eb extension

### ISSUE THREAD

**Issue by pescobar** [pre-commit/pre-commit#683]
Hi,

I am trying to use pre-commit with the repo https://github.com/easybuilders/easybuild-easyconfigs . This repo includes many .eb files with python syntax so I would like to apply the "autopep8 wrapper" in pre-commit to every .eb file. I am trying to use the "files" option in pre-commit but I cannot get it working. Probably I have a stupid mistake in my regular expression but I cannot find it. This is the config I am using:

```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
      - id: autopep8-wrapper
        files: .*.eb$
      - id: check-ast
        files: '(.*.eb$)'
      - id: trailing-whitespace
      - id: end-of-file-fixer
```
I have checked the regex with some online regex editor and they seem to match with .eb files. I also tried few other variants of the regex but I couldn't get it working. 

Out of ideas I tried the "types" option in pre-commit and it worked if I use `types: ["file", "non-executable", "text"]` but this match with many other files that don't include python code. I would need to apply autopep8-wrapper only to .eb files and the `files` option seems the best for this.

Any suggestion about how to modify the `files` option in my pre-commit config so autopep8-wrapper is applied to every .eb file?

Thanks in advance for any help.

**Comment by asottile** [comment]
Thanks for the issue!

Ah this is probably because these hooks also use `types` and have `types: [python]`.  `types` and `files` are an `AND` operation (that is, `files: \.eb$` will only further filter the files matched by `types: [python]`).

In this case, you'll want to override the base `types` back to all files and then filter to files matching `.eb` -- something like this:

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
      - id: autopep8-wrapper
        types: [file]
        files: \.eb$
      - id: check-ast
        types: [file]
        files: \.eb$
      # you'll probably also want to lint python files as well
      - id: autopep8-wrapper
      - id: check-ast
```

pre-commit allows you to specify multiple configurations of the same hook.  If you want to differentiate them you can even override name:

```yaml
      - id: autopep8-wrapper
        name: 'autopep8-wrapper (.eb)'
        types: [file]
        files: \.eb$
      - id: autopep8-wrapper
```

You'll get something like this:

```
autopep8 wrapper (.eb)......................................................Passed
autopep8 wrapper............................................................Passed
```
