### ISSUE TITLE
meta `check-useless-excludes` hook does not consider things excluded by `files` filter

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#704]
For instance:

https://github.com/Yelp/pyramid-hypernova/blob/ca166e698897ec46ca129e5dbce8d5ccb8d544ec/.pre-commit-config.yaml#L6-L8

```yaml
    -   id: end-of-file-fixer
        language_version: python3.6
        exclude: ^\.activate\.sh$
```

`end-of-file-fixer` uses `types: [text]` which will exclude the `.activate.sh` symlink
