### ISSUE TITLE
Dynamic exclude base on language version

### ISSUE THREAD

**Issue by fruch** [pre-commit/pre-commit#705]
I have a python repo that need to support both python2 and python3. 
up until now I had two docker builds in my CI one for each, and they share the exact same precommit configuration file.

but now I've introduced some files in the repo using python3 only syntax (async/await)

How can I skip those files for python2 and not for python3, I hate to use two different config file for this purpose (not very DRY)

Is there any feature in pre-commit that can help ?

Israel

**Comment by chriskuehl** [comment]
I'm not sure how your project is set up, but assuming you have the Python 3 files separate from the Python 2 files, what if you ran linters (in this example, `flake8`) on the files separately?

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.9.1
    hooks:
    -   id: flake8
        name: flake8 (Python 2)
        # Adjust as necessary
        files: ^py2/
        language_version: python2.7
    -   id: flake8
        name: flake8 (Python 3)
        # Adjust as necessary
        files: ^py3/
        language_version: python3.6
```

There's also the `exclude` key which you could use instead.
