### ISSUE TITLE
When using `types`, why is it necessary to specify a noop `files`?

### ISSUE THREAD

**Issue by magicmark** [pre-commit/pre-commit#706]
@chriskuehl 

I'd expect something like this to match my stuff:

```yaml
-   repo: https://github.com/prettier/prettier
    sha: 1.10.2
    hooks:
    -   id: prettier
        name: prettier (scss, markdown)
        types: [markdown, scss]
```

As evidenced, it doesn't: https://i.fluffy.cc/mMkBxvs5XF8Lbf8bxxXFRxWClBk8Cg58.html

This is because we apparently also need to add a `files: ''`

Is this behavior intentional?

From reading [the docs](https://pre-commit.com/#filtering-files-with-types), it's not obvious that this is the case - maybe we could clarify this? :)

Thanks!
