### ISSUE TITLE
Issue running pre-commit when specifying an array of `types`?

### ISSUE THREAD

**Issue by magicmark** [pre-commit/pre-commit#707]
Consider the following config:

```yaml
repos:
-   repo: https://github.com/prettier/prettier
    sha: 1.10.2
    hooks:
    -   id: prettier
        name: prettier (markdown)
        files: ''
        types: [markdown]
    -   id: prettier
        name: prettier (javascript + markdown)
        files: ''
        types: [javascript, markdown]
```

Only the first hook matches anything. The second hook does not:

```bash
╔═ mark@mark: ~/vpg/repro git:(master) virtualenv:(venv)
╚═ ♪ pre-commit run -a
prettier (markdown)......................................................Failed
hookid: prettier

Files were modified by this hook. Additional output:

README.md 134ms

prettier (javascript + markdown).....................(no files to check)Skipped
```

(Full repro: https://github.com/magicmark/pre-commit-issue-repro)

Am I doing something wrong in the second example?

Thanks!
