### ISSUE TITLE
Add hook for checking .travis.yml and tox.ini

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#71]
Mostly for environments.  The environments in the tox.ini file specified as follows:

```
[tox]
envlist = py26,py27,py33,pypy
```

Should be represented in .travis.yml

``` yaml
language: python
env: # These should match the tox env list
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=pypy
```
