### ISSUE TITLE
Question: always_skip unless called explicitly

### ISSUE THREAD

**Issue by hectorv** [pre-commit/pre-commit#719]
Is there a way to add a hook to `.pre-commit-config.yaml` but have it always skip unless it's called explicitly? Granted, this is a weird use-case where I'm basically just trying to benefit from `pre-commit`'s package management abilities :)
So for example, while doing `git commit` or `pre-commit run` it would be marked as `Skipped` but would run when called like this:
```
pre-commit run <hook>
```

For context, I'm trying to simplify setting up [prmd](https://github.com/interagent/prmd) (a Ruby package) on Python repos. This already works (as part of a script)
`pre-commit run --verbose prmd --files <json>`
where
```
-   repo: /path/to/mirrors-prmd
    sha: v0.11.7
    hooks:
    -   id: prmd
        entry: prmd render
        args:
        - --template=main/api/doc/templates
```
but now I would like to prevent this hook from running in all other instances :)
As I said, weird use-case... maybe I just need to go to sleep now 😴
