### ISSUE TITLE
Allow specifying custom virtual environment for hooks

### ISSUE THREAD

**Issue by dspechnikov** [pre-commit/pre-commit#761]
My use case is Python-specific, but I believe this applies to other languages as well.

I'd like to run `pytest` as a pre-commit hook. It requires all project dependencies installed in the virtual environment. Currently, the only way to do that is to copy-paste them to `additional_dependencies` which is almost impossible to maintain.

The best solution would be to allow to reuse project virtual environment via environment variable since it is different for every developer. Something like a custom command to install dependencies would be okay too.

**Comment by asottile** [comment]
This can be accomplished with a [`system` / `script`](https://pre-commit.com/#repository-local-hooks) hook -- it is suggested to do this as a local hook

Here's an example of how this might work (note that pre-commit will *not* manage this environment so it's up to you to make it happen):

```yaml
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: venv/bin/pytest
        language: script
        pass_filenames: false
        # alternatively you could `types: [python]` so it only runs when python files change
        # though tests might be invalidated if you were to say change a data file
        always_run: true
```

Also note that running tests as part of your commit might frustrate your users, generally we try and stick to _fast_ hooks (linters) when possible.
