### ISSUE TITLE
Question: Using hooks at different stages

### ISSUE THREAD

**Issue by mattlqx** [pre-commit/pre-commit#768]
1. In order to utilize hooks that run in different stages, pre-commit needs to install itself as the hook in each one (e.g. "pre-commit" and "commit-msg"). By default however, pre-commit only installs itself in "pre-commit" and you can't specify multiple types with the -t argument. It would be nice if pre-commit would see that a hook in the config can only be used in a specific stage (e.g. "commit-msg") and install itself there rather than requiring explicit knowledge and direction from the user.
1. Most hooks that don't explicitly limit themselves to a single stage, so if pre-commit is installed as hook multiple times (e.g. "pre-commit" and "commit-msg"), you'll get multiple runs of the unrestricted hooks for each commit. To avoid that, in your config file, you'd be required to specify a single stage for each hook. This can become pretty redundant.

For example:
```
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0
  hooks:
  # Git state
  - id: check-merge-conflict
    stages: [commit]
  - id: check-added-large-files
    stages: [commit]
  # Sensitive information
  - id: detect-private-key
    stages: [commit]
  - id: detect-aws-credentials
    stages: [commit]
  # Generic file state
  - id: trailing-whitespace
    stages: [commit]
  - id: mixed-line-ending
    stages: [commit]
  - id: end-of-file-fixer
    stages: [commit]
  - id: check-executables-have-shebangs
    stages: [commit]
  # Language syntax/formatting
  - id: check-yaml
    stages: [commit]
  - id: check-json
    stages: [commit]
  - id: pretty-format-json
    stages: [commit]
- repo: https://github.com/mattlqx/pre-commit-sign
  rev: v1.1.1
  hooks:
  - id: sign-commit
```

Am I understanding the limitations of stages correctly? Can anything be improved from the framework side to make commit and commit-msg stages not duplicate work or be more intelligent about what runs where? Maybe keep track of if a hook ran in the commit stage and avoid running it in the commit-msg stage?
