### ISSUE TITLE
Add hook option to run hook once per changed file

### ISSUE THREAD

**Issue by alexjurkiewicz** [pre-commit/pre-commit#771]
I was trying to add a simple hook file for [cfn-lint](https://github.com/awslabs/cfn-python-lint).

The `.pre-commit-hooks.yaml` config file I am testing looks like:

```yaml
-   id: cfn-python-lint
    name: AWSLabs CloudFormation Linter
    entry: cfn-lint
    language: python
    files: \.(json|yaml|yml)$
    language_version: python2
```

Unfortunately, `cfn-lint` only supports testing one file at a time. So currently I'd also need to add a wrapper script that loops over all input files.

It would be nice to instead add a new YAML directive like:

```yaml
    files_per_run: 1
```

Instead, and have `pre-commit` handle this case.
