### ISSUE TITLE
docker_image: --entrypoint ignores parameters

### ISSUE THREAD

**Issue by aexvir** [pre-commit/pre-commit#795]
From my tests it seems that the syntax:

```yaml
- repo: local
  hooks:
    - id: format
      name: code-formatter
      language: docker_image
      entry: --entrypoint binary --parameter 120 image:latest
```

Ignores the parameters while:

```yaml
- repo: local
  hooks:
    - id: format
      name: code-formatter
      language: docker_image
      entry: image:latest binary --parameter 120
```

Works perfectly fine...

Is this a known bug? Or am I doing something wrong?

OS: macOS 10.13.5
pre-commit: 1.10.3
