### ISSUE TITLE
additional_dependencies are not installed into local virtual env

### ISSUE THREAD

**Issue by 1oglop1** [pre-commit/pre-commit#813]
Hi I tried to find a suitable workaround for 
https://github.com/pre-commit/mirrors-pylint/issues/9
with this configuration
```
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: python -m pylint.__main__
        language: system
        types: [python]
```

but then I got errors that pylint is not installed, I expected it to be installed by pre-commit.
I tried to use 
```
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: python -m pylint.__main__
        language: system
        types: [python]
        additional_dependencies: [pylint]
```

But no dependencies were installed and I still got an error:
```
Error while finding module specification for 'pylint.__main__' (ModuleNotFoundError: No module named 'pylint')
```
