### ISSUE TITLE
Include *.sls files

### ISSUE THREAD

**Issue by fauust** [pre-commit/pre-commit#826]
Hi,
is there a way to include other files extension?
I am thinking on saltstack sls files that also use yaml.

Is the following wrong?
```
- repo: https://github.com/adrienverge/yamllint.git
    sha: v1.11.1
    hooks:
      - id: yamllint
        files: \.(yaml|yml|sls)$
```

**Comment by asottile** [comment]
saltstack files aren't _quite_ yaml though you could lint them as such (they're jinja templated yaml)

`yamllint` uses [`types`](https://github.com/adrienverge/yamllint/blob/e4e99f0aba5bc894712a720d8516db556e48acf1/.pre-commit-hooks.yaml#L11) to select filenames.  [`types` and `files` are `AND`ed](https://pre-commit.com/#filtering-files-with-types).

There was some discussion on [`identify`](https://github.com/chriskuehl/identify/pull/31) about identifying `.sls` files as yaml, but instead we made a new `type` for them.

Note also that `types: [yaml, salt]` won't work (that'll never match anything) because `types` is also evaluated with `AND`.  When [`types_or`](https://github.com/pre-commit/pre-commit/issues/607) becomes a thing then that'll be possible with type filtering.

The answer to how you can do what you want is to override the base `types`:

```yaml
    -   id: yamllint
        types: [file]
        files: \.(yaml|yml|sls)$
```
