### ISSUE TITLE
Pre-commit hook ignores isort config

### ISSUE THREAD

**Issue by timonbimon** [pre-commit/pre-commit#842]
Hi there, 

I am running isort as one of my pre-commit hooks and when I tried changing the isort settings in my tox.ini nothing happens. It seems like the pre-commit hook is ignoring the config. Any idea why this might be happening? Help would be greatly appreciated. :)

```
➜ cat .pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
    language_version: python3.7
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.7
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0
  hooks:
  - id: flake8
    language_version: python3.7
```

and this is in my tox.ini

```ini
[isort]
known_first_party=lumi
multi_line_output=3
include_trailing_comma=True
force_grid_wrap=0
combine_as_imports=True
line_length=88
```

In particular it is not recognizing my own package as a first party even though I put it in the config.
