### ISSUE TITLE
Unable to force check for specific file extension

### ISSUE THREAD

**Issue by s0undt3ch** [pre-commit/pre-commit#855]
I seem to be unable to run a check for a particular file extension:

My pre commit config:
```
---
- repo: https://github.com/adrienverge/yamllint.git
  sha: v1.12.1
  hooks:
    - id: yamllint
      files: '\.(yml|meta|mta)$'
      types: [text, yaml]
```

Although I have `yml|meta|mta` I'm only really interested in `*.meta` files.
For testing purposes I copied the `.meta` file to `.yml` and to `.mta` because `meta` could be considered a special keyword or similar

Run output:
```
❯ pre-commit run -vvvv --files salt/locke/system/user/win_uiaccess_apps_elevation.yml salt/locke/system/user/win_uiaccess_apps_elevation.meta salt/locke/system/user/win_uiaccess_apps_elevation.mta     
[yamllint] yamllint......................................................Failed
hookid: yamllint

salt/locke/system/user/win_uiaccess_apps_elevation.yml
  2:101     warning  line too long (152 > 100 characters)  (line-length)
  3:101     warning  line too long (136 > 100 characters)  (line-length)
  16:101    warning  line too long (158 > 100 characters)  (line-length)
  18:13     warning  truthy value should be true or false  (truthy)
  23:9      error    wrong indentation: expected 6 but found 8  (indentation)
  24:9      error    wrong indentation: expected 6 but found 8  (indentation)
  25:9      error    wrong indentation: expected 6 but found 8  (indentation)
  26:9      error    wrong indentation: expected 6 but found 8  (indentation)
  28:9      error    wrong indentation: expected 6 but found 8  (indentation)
  29:9      error    wrong indentation: expected 6 but found 8  (indentation)
  30:9      error    wrong indentation: expected 6 but found 8  (indentation)
  31:9      error    wrong indentation: expected 6 but found 8  (indentation)
  32:9      error    wrong indentation: expected 6 but found 8  (indentation)
  33:9      error    wrong indentation: expected 6 but found 8  (indentation)
  34:9      error    wrong indentation: expected 6 but found 8  (indentation)
  35:9      error    wrong indentation: expected 6 but found 8  (indentation)
  36:9      error    wrong indentation: expected 6 but found 8  (indentation)
  37:9      error    wrong indentation: expected 6 but found 8  (indentation)
  39:9      error    wrong indentation: expected 6 but found 8  (indentation)
  40:9      error    wrong indentation: expected 6 but found 8  (indentation)
  41:9      error    wrong indentation: expected 6 but found 8  (indentation)
  42:9      error    wrong indentation: expected 6 but found 8  (indentation)
  43:9      error    wrong indentation: expected 6 but found 8  (indentation)
```
The other files seem to don't even go through the check.

What am I doing wrong here?

**Comment by asottile** [comment]
types and files are evacuated with `and`. types will limit to .yaml / .yml and then that'll never match your files expression.

Setting `types: [files] `  (to override the base manifest) will do what you want

**Comment by s0undt3ch** [comment]
```yaml
---
- repo: https://github.com/adrienverge/yamllint.git
  sha: v1.12.1
  hooks:
    - id: yamllint
      files: '\.(yml|meta|mta)$'
      types: [files]
```
```
❯ pre-commit run -vvvv --files salt/locke/system/user/win_uiaccess_apps_elevation.meta salt/locke/system/user/win_uiaccess_apps_elevation.mta salt/locke/system/user/win_uiaccess_apps_elevation.yml     
An error has occurred: InvalidConfigError:
==> File /home/vampas/projects/SaltStack/console/lock/features/pre-commit/.pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='https://github.com/adrienverge/yamllint.git')
==> At key: hooks
==> At Hook(id='yamllint')
==> At key: types
==> At index 0
=====> Type tag 'files' is not recognized.  Try upgrading identify and pre-commit?
Check the log at /home/vampas/.cache/pre-commit/pre-commit.log
```
Doesn't work...

**Comment by s0undt3ch** [comment]
Should be `file`:
```yaml
---
- repo: https://github.com/adrienverge/yamllint.git
  sha: v1.12.1
  hooks:
    - id: yamllint
      files: '\.(yml|meta|mta)$'
      types: [files]
```
This works. Thanks!
