### ISSUE TITLE
Allow detection of tool configuration changes

### ISSUE THREAD

**Issue by EdJoJob** [pre-commit/pre-commit#859]
It should be possible for pre-commit to be configured so that a change in a tool configuration file would result in something approximately equivalent to `pre-commit run --all-files <hook>` where `<hook>` is the hook that would use that configuration file.

I would imagine that this would look something like:
```yaml
repos:
  - repo: https://github.com/someuser/somehook
    hooks:
      - id: somehook
        tool_config: some/path/from/git/root
```
