### ISSUE TITLE
"identity" meta hook

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#865]
Pretty often I or a bug reporter reaches for the "simplest hook possible" -- often to debug what files are being passed through.

Let's add an "identity" hook which does the following:

1. Is always verbose
2. prints the filenames passed to it
3. Always succeeds

Basically make something like this, but without depending on "actual" `echo`:

```yaml
-   id: identity
    name: identity
    entry: echo
    verbose: true
    language: system
```
