### ISSUE TITLE
ability to run the same hook twice

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#866]
I am trying to implement the behavior described below regarding yamllint which should allow introdcution of linting gradually:
* ``python -m pre_commit yamllint -- --strict``
* ``python -m pre_commit yamllint --all-files``

I need to run both commands because first one will mark even warnings on touched files as failures and the second one will fail if any of the non-modified files has a real error (ignoring warnings).

At this moment this does not seem possible to achieve because hooks do not allow positional arguments (like --strict). 

Also I was not able to identify a way to add the same hook twice inside `.pre-commit-config.yaml` file.

Why is this important? In real life the amount of non-compliance can be big and it would be close to impossible to adopt a more strict code-style on a very active repository. Thus is better to start with the desired style only for touched files.

**Comment by asottile** [comment]
Simply list the hook twice:

```yaml
-   repo: https://github.com/adrienverge/yamllint
    rev: ...
    hooks:
    -   id: yamllint
        args: [--strict]
        # ...
    -   id: yamllint
        # ...
```
