### ISSUE TITLE
Add config option to ask user to continue anyway

### ISSUE THREAD

**Issue by SimonHeimberg** [pre-commit/pre-commit#871]
When the config for some code-style (eslint, php-cs, ...) is not (yet) fine tuned, it would be handier to answer an interactive question than to redo the commit with SET=hook_id.

When there is no tty, the hook would fail.

suggestion for configuration:
```yaml
#.pre-commit-config.yaml
-   repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
    -   id: some-unreliable-check
        ask_on_fail: true
```
