### ISSUE TITLE
allow a hook to show output before completion

### ISSUE THREAD

**Issue by SimonHeimberg** [pre-commit/pre-commit#872]
For some tools, it could be handy to show output before completion.
Some fixers could ask if some corrections should be done. (`phpcs -a` is similar, it waits for manual fixing and rechecks.) Some legacy code could be used. Showing progress of a tool could be another use case.

I plan to call my current pre-commit-shell-scipt ([a bash script](https://github.com/EmchBerger/cube-common-develop/blob/development/src/CodeStyle/check-commit-cube.sh)) with pre-commit (this project). Later I would split up the script and use implementation of #871 ;-)

```yaml
verbose: full
# or 
verbose: linewise
# or
verbose: buffer 2 # write when no new output after 2 sec
```
