### ISSUE TITLE
Add pre-commit repo setting to specify local repository

### ISSUE THREAD

**Issue by meyer9** [pre-commit/pre-commit#873]
```yaml
- repo: local
  sha: HEAD
  hooks:
    - id: go-build
```

Something like this should run the script from the repository the hook is being run from. Then, git repos can specify per-repository hooks.
