### ISSUE TITLE
Can I show warning message without blocking the commit?

### ISSUE THREAD

**Issue by barbossa** [pre-commit/pre-commit#923]
I want to run [safety](https://github.com/pyupio/safety) on each commit. I want to show errors messages from safety as warnings. I do not want that safety errors blocking my commits. How I can do this?

My .pre-commit-config.yaml is very simple.

```
- repo: local
  hooks:
    - id: safety
      name: safety
      entry: safety check --bare --full-report
      pass_filenames: false
      language: system
```
