### ISSUE TITLE
Resolving arguments at runtime

### ISSUE THREAD

**Issue by jjshanks** [pre-commit/pre-commit#925]
I'm trying to use a docker image as a hook but need to mount a volume to it. When I try adding $(pwd) or `pwd` as part of the volume argument for the entrypoint neither gets resolved. Unfortunately volumes need to be an absolute path. Is there a way to have the current absolute path usable when the hook runs?

```
repos:
-   repo: local
    hooks:
    - id: black
      name: black
      language: docker_image
      entry: --rm -t -v $(pwd):/pre-commit --entrypoint="black" black
```

```
/usr/bin/docker: Error response from daemon: create $(pwd): "$(pwd)" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
```

**Comment by asottile** [comment]
both `docker` and `docker_image` will always end up with these arguments:

https://github.com/pre-commit/pre-commit/blob/160238220f022035c8ef869c9a8642f622c02118/pre_commit/languages/docker.py#L80-L85

(notably, a volume to `/src`, a workingdir of `/src`, and running as the current user)

Here's a config I was able to get working:

```
repos:
-   repo: local
    hooks:
    -   id: black-docker
        name: black-docker
        language: docker_image
        types: [python]
        entry: kiwicom/black black
```

```
$ pre-commit  run --all-files
black-docker.............................................................Failed
hookid: black-docker

Files were modified by this hook. Additional output:

Unable to find image 'kiwicom/black:latest' locally
latest: Pulling from kiwicom/black
8e3ba11ec2a2: Pulling fs layer
2baa13bb50be: Pulling fs layer
86492d6243e4: Pulling fs layer
f9dd5cba45b9: Pulling fs layer
26495a2f03be: Pulling fs layer
3c8327c0e4cf: Pulling fs layer
f9dd5cba45b9: Waiting
8e3ba11ec2a2: Download complete
8e3ba11ec2a2: Pull complete
2baa13bb50be: Verifying Checksum
2baa13bb50be: Download complete
f9dd5cba45b9: Verifying Checksum
f9dd5cba45b9: Download complete
2baa13bb50be: Pull complete
26495a2f03be: Verifying Checksum
26495a2f03be: Download complete
3c8327c0e4cf: Verifying Checksum
3c8327c0e4cf: Download complete
86492d6243e4: Verifying Checksum
86492d6243e4: Download complete
86492d6243e4: Pull complete
f9dd5cba45b9: Pull complete
26495a2f03be: Pull complete
3c8327c0e4cf: Pull complete
Digest: sha256:a103f5200c195cd6a69c35f92ff5d28bb095fb5d75ae7cb5935905e2bad77789
Status: Downloaded newer image for kiwicom/black:latest
reformatted /src/setup.py
reformatted /src/astpretty.py
reformatted /src/tests/astpretty_test.py
All done! ✨ 🍰 ✨
3 files reformatted, 1 file left unchanged.
```

Though I don't think you need to use it via docker, https://github.com/ambv/black supports pre-commit out of the box:

```yaml
repos:
-   repo: https://github.com/ambv/black
    rev: ...
    hooks:
    -   id: black
```
