### ISSUE TITLE
Running hook on untracked files

### ISSUE THREAD

**Issue by hoshsadiq** [pre-commit/pre-commit#930]
Hi all,

I am trying to get a hook to run on untracked files. Is there a way of doing this?

Use case is that we're using CloudFormation for our infrastructure, and we have enhanced it using Jinja2. The rendered files are put in a `build/` dir that's not tracked in git, and we'd like run cfn lint and yaml lint on these files.

I've tried the following:
```yaml
repos:
-   repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.13.0
    hooks:
    - id: cfn-python-lint
      files: build/output/prod/myapp/templates/root.yaml
```

However, when I run it I get the following:

```
root@4dd1a98ce9ce:/workdir# pre-commit run
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /root/.cache/pre-commit/patch1548931914.
AWSLabs CloudFormation Linter........................(no files to check)Skipped
[INFO] Restored changes from /root/.cache/pre-commit/patch1548931914.
```

EDIT: forgot to add:
```
root@4dd1a98ce9ce:/workdir# ls -l build/output/prod/myapp/templates/root.yaml
-rw-r--r-- 1 root root 1236 Jan 30 14:40 build/output/prod/myapp/templates/root.yaml
```

**Comment by asottile** [comment]
~generally pre-commit is only designed to run on checked-in files.  However I think you can achieve what you want with something like this:

```yaml
repos:
-   repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.13.0
    hooks:
    - id: cfn-python-lint
      always_run: true  # run whether or not there are files to check
      pass_filenames: false  # don't pass the default-matched filenames
      args: [build/output/prod/myapp/templates/root.yaml]
```
