### ISSUE TITLE
Make user for docker optional

### ISSUE THREAD

**Issue by DrPsychick** [pre-commit/pre-commit#939]
Hi,

can we make the `--user` argument to docker optional somehow?
https://github.com/pre-commit/pre-commit/blob/2fa0fabb05e147417f0cd9c619f94547874bda46/pre_commit/languages/docker.py#L80

Issue:
```
- repo: local
  hooks:
  - id: travis-lint
    name: travis-lint
    language: docker_image
    entry: caktux/travis-cli
    args: ["lint"]
    files: .travis.yml
```
does not work, because it tries to run inside the docker container with my local (host) UID which does not exist. As a result the `$HOME` variable is not set and travis fails.

workaround:
```
- repo: local
  hooks:
  - id: travis-lint
    name: travis-lint
    language: docker_image
    entry: --user root caktux/travis-cli
    args: ["lint"]
    files: .travis.yml
```
Provide `/tmp` as home directory (`--env HOME=/tmp`) because it is writable or simply set the `--user` parameter again. That fixes the issue with travis, but it does not fix the **issue**:

> pre-commit should not silently assume that the host user exists inside the container.

Proposed solution:
* keep default user if it needs be
* allow the user to overwrite the default user, for example like this:
```
[...]
    language: docker_image
    entry: my/image
    docker_user: 1000:1000
[...]
```
* or simply remove the default and allow the user to set it on the command line as in the workaround above

I hope this helps!
