### ISSUE TITLE
Binding pre-commit-config.yaml package versions to repo package.json?

### ISSUE THREAD

**Issue by kortina** [pre-commit/pre-commit#945]
I was wondering if there is a recommendation for binding the version numbers specified in `.pre-commit-config.yaml` to versions in my repo's `package.json`?

We already maintain, for example, version numbers for `prettier` and `eslint` in a `package.json` and I am worried our pre-commit config will get out of sync w these.

Any way to reference a package file from the pre-commit config to try to avoid this?

**Comment by asottile** [comment]
there is not a way to reference / include outside of the `.pre-commit-config.yaml` -- for instance see #730 / #880

that said, the desire to implement this has come up a few times and the suggestion I've given is to write a hook to synchronize the two.  I haven't seen an implementation of that yet but would welcome one if it were implemented.

That way you could do something like:

```yaml
-   repo: https://github.com/pre-commit/sync-versions
    rev: v1.0.0
    hooks:
    -   id: sync-versions
```

by default it would probably use

```yaml
    files: ^(\.pre-commit-config.yaml|package-lock\.json|requirements.*\.txt)$
```

or something of the sort and then expand to support more languages in the future?

**Comment by kortina** [comment]
OK, that was going to be my backup plan. 

And in this case, https://github.com/pre-commit/sync-versions is a fictitious repo yet to be written, correct?

**Comment by asottile** [comment]
indeedy

**Comment by gtback** [comment]
I just ran into this same issue today. @peterwj are you already working on a hook? If not, I can try to take a look at making one pretty soon.

**Comment by peterwj** [comment]
@gtback I ended up using the `language: system` and [repository local hooks](https://pre-commit.com/#repository-local-hooks) approach that Anthony linked above -- the `entry` calls an `npm` script that runs `eslint` over the files passed in via command line args.  works great, since the only place I specify dependencies now is `package.json`.

**Comment by gtback** [comment]
@peterwj any chance you could share that script, unless it's closely tied to your code itself? I'm sure others (selfishly, including myself) could benefit from it, even though it's probably a pretty simple script.

**Comment by peterwj** [comment]
sure!

in package.json:
```
...
    "scripts": {
        "eslint:fix": "eslint --fix"
    },
...
```

in .pre-commit-config.yaml:
```
repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        language: system
        files: '\.(js|vue)$'  # replace this with a regex for files you want to lint 
        entry: npm run eslint:fix
```
