### ISSUE TITLE
pre-commit not using project pipenv virtualenv

### ISSUE THREAD

**Issue by peterhadlaw** [pre-commit/pre-commit#950]
Hello, I'm trying to get `isort` to work with my project's pipenv / Pipfile based dependency management.

I installed / initiated pre-commit in the following manner:

```zsh
$ pipenv install --dev
$ pipenv run pre-commit install --color never -f -t pre-push
$ pipenv run pre-commit install --color never -f -t pre-commit
```

I have a `.python-version` file in my project root specifying `3.6.6`

Here is what my Pipfile looks like:

```ini
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
<trimmed>
pre-commit = "*"
isort = {extras = ["pipfile"],version = "*"}
<trimmed>

[packages]
<trimmed>

[requires]
python_version = "3.6.6"
```

And here's what the relevant part of my `.pre-commit-config.yaml` looks like:

```yaml
default_stages: [push]
default_language_version:
  python: python3.6
repos:
- repo: local
  hooks:
  - id: isort
    stages: [commit,push]
    name: isort
    entry: pipenv run isort -rc
    language: system
```

And finally, here's the error I'm getting from pre-commit: 

```
isort....................................................................[41mFailed[0m
hookid: isort

Warning: Your Pipfile requires python_version 3.6.6, but you are using 3.7.0 (/Users/pjh/.local/share/v/d/bin/python).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
Loading .env environment variables…
pyenv: isort: command not found
```

**Comment by asottile** [comment]
Very strange, I'll take a look when I'm at a computer. In the meantime you might want to check out https://github.com/pre-commit/mirrors-isort

**Comment by peterhadlaw** [comment]
Hello @asottile, thanks for the quick response :) Yeah the `mirrors-isort` package doesn't take the `pipenv` / `Pipfile` virtualenv into account and thus fails to know which packages are "first party" vs. "thirdparty" and so on. Hence the need for the command `pipenv run isort`. 

Again, any help is very much appreciated!

**Comment by asottile** [comment]
Yep, the bottom of the readme has some help for that via https://github.com/asottile/seed-isort-config

**Comment by peterhadlaw** [comment]
Yeah I did take a moment to look further, but it seems there are the same symptoms. (I see that you also are the main contributor to the `mirrors-isort`, which led me to dive in further before commenting again and try more using your advice.)

So I did the following: 
1. `pipenv install --dev seed-isort-config`
2. Modified my `.pre-commit-config.yaml` to the following: 

```yaml
repos:
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.5.0
  hooks:
  - id: seed-isort-config
- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v4.3.4'  # Use the revision sha / tag you want to point at
  hooks:
  - id: isort
    stages: [commit,push]
```

3. `pre-commit install --color never -f -t pre-push`
4. `pre-commit install --color never -f -t pre-commit`

After running the pre-commit hooks, `isort` still thinks third party packages are first party packages.
