### ISSUE TITLE
Use current interpreter for custom hooks

### ISSUE THREAD

**Issue by gpkc** [pre-commit/pre-commit#954]
Suppose I have the following snippet in my config:
```
    - repo: local
      hooks:
          - id: py3
            name: py3
            language: python
            entry: python -c "import sys; print(sys.executable)"
            verbose: true
            pass_filenames: false
            always_run: true
```
This might output something like:
`/root/.cache/pre-commit/repohx_jzd4i/py_env-python3/bin/python`
Which shows that the `python` executable used within those hooks is the one created by `pre-commit`.

What I would like instead is a way to use the `python` used when running `pre-commit`. Is there a way to do that without having to input the full interpreter path in the config file (for portability)?
