### ISSUE TITLE
Intermittent running of plugins

### ISSUE THREAD

**Issue by philipobrien** [pre-commit/pre-commit#983]
I'm using pre-commit to run black and flake8. I have been observing some weird (or maybe expected?) behaviour, however, where flake8 will show as `Passed` but if I re-run `git add; git commit`, having changed none of the source files, it will show as `Failed`

`pre-commit-config.yaml` is

```
fail_fast: false
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      always_run: true
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
      always_run: true
```
<img width="787" alt="Screenshot 2019-03-28 at 16 18 52" src="https://user-images.githubusercontent.com/1763813/55174378-3db7f400-5175-11e9-8a4c-501bd8b9e14c.png">
