### ISSUE TITLE
'files' in hooks not searching files correctly.

### ISSUE THREAD

**Issue by dominic-pucci** [pre-commit/pre-commit#991]
I am following the example at the bottom of https://github.com/aws-cloudformation/cfn-python-lint

No matter what filter I try for the 'files' directive, it doesn't match any .yml files in the specified subdirectory.

The pre-commit-config.yaml that I am using is:
```yaml
repos:
-   repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.18.1  # The version of cfn-lint to use
    hooks:
    -   id: cfn-python-lint
        files: cloudformation-templates/.*\.(json|yml|yaml)$
```

My apologies for the indentation, I couldn't get it to format correctly here.
