### ISSUE TITLE
autoupdate back-versioning

### ISSUE THREAD

**Issue by acdha** [pre-commit/pre-commit#993]
I have a `.pre-commit-config.yaml` file like this:

```yaml
repos:
    - repo: https://github.com/prettier/prettier
      rev: 1.16.4
      hooks:
          - id: prettier
            files: \.(css|less|scss|ts|tsx|graphql|gql|json|js|jsx|md)$
```

This works normally but if I run `pre-commit autoupdate` it unexpectedly back-levels prettier:

```
Updating https://github.com/prettier/prettier...updating 1.16.4 -> 1.16.2.
```

https://github.com/prettier/prettier/releases shows the tag exists and it's not immediately obvious to me why the older release is being selected.
